### ISSUE TITLE
Cannot use URL with PORT

### ISSUE THREAD

**Issue by schleichermann** [guzzle/guzzle#1001]
I am using the latest version of guzzle. 

    (from composer.json)
    "guzzlehttp/guzzle": "~5" 

    (from composer.lock)
    "name": "guzzlehttp/guzzle",
    "version": "5.2.0",

When I attempt to request (GET or POST) with a URL that contains a PORT number:

    $response = $client->get('http://www.hostdnshere.com:8888', array());

I get the following error:

    string(68) "cURL error 7: Failed to connect to 184.107.174.82: Permission denied"

When I do the same but omit the PORT: 

    $response = $client->get('http://www.hostdnshere.com', array());

The request succeeds without issue. I have searched the documentation and Googled the web but cannot find out how to set the port for the host since it cannot be included.

**Comment by schleichermann** [comment]
Additionally, I have tested it all using cURL on the server form which the requests are being sent, with and without the PORT, works like a charm no matter what so I know its not an issue with the Server, DNS, Proxies, or PORTS.

**Comment by sjagr** [comment]
My attempt at reproduction in my MAMP environment..

`composer.json`:

    {
        "name": "schuylerjager/guzzle-test",
        "require": {
            "guzzlehttp/guzzle": "~5.2"
        },
        "authors": [
            {
                "name": "Schuyler Jager",
                "email": "s.jager@gmail.com"
            }
        ]
    }

`index.php`:

	<?php
	require_once('vendor/autoload.php');
	$client = new GuzzleHttp\Client();
	$response = $client->get('http://localhost:8888/test.php', array());
	echo $response;

`test.php`:

    hi

Results of executing `http://localhost:8888`:

>HTTP/1.1 200 OK Date: Thu, 12 Mar 2015 18:46:07 GMT Server: Apache/2.2.29 (Unix) mod_fastcgi/2.4.6 mod_wsgi/3.4 Python/2.7.8 PHP/5.6.2 mod_ssl/2.2.29 OpenSSL/0.9.8zc DAV/2 mod_perl/2.0.8 Perl/v5.20.0 X-Powered-By: PHP/5.6.2 Content-Length: 2 Content-Type: text/html; charset=UTF-8 hi

Can you reproduce with my example?

**Comment by schleichermann** [comment]
Yeah, I reproduced your test and it works fine. I am running Guzzle from a PHP class within a Laravel 4.2 application where I am getting the error. When I check the composer.json file Guzzle is only listed in there once as displayed above, but when I look in the composer.lock file I see guzzle/guzzle as well as guzzlehttp/guzzle as being installed by composer, even when I delete the vendor bin and lock file and do a clean composer install. So some other package is relying on Guzzle but since the two have separate namespaces I would assume they would not conflict with one another.

**Comment by schleichermann** [comment]
And I am fully qualifying the latest version in the PHP class

    use GuzzleHttp\Client;
    use GuzzleHttp\Exception\RequestException;

**Comment by schleichermann** [comment]
As well as fully qualifying it on creation to make sure the latest Guzzle is being used to instantiate the object.

    $client = new GuzzleHttp\Client();

**Comment by schleichermann** [comment]
For all those banging their heads against the wall due to the

    "cURL error 7: Failed to connect to 000.000.000.000: Permission denied"

error, it all boils down to 'SELINUX'. That is right, any cURL wrapper written in any programming language can be affected by the fact that when 'SELINUX' is set to 'enforcing' it takes issue with cURL being executed against a URL that has a non-standard PORT in it (i.e. my.domain.com:8888).

Recommended for local development only, if you wish to use non-standard PORTS in your URL's, is to set 'SELINUX' to 'disabled'. The proper solution in production will be to use clean URLs without PORTs in them in order to leave 'SELINUX' enabled.

Open:

    nano /etc/selinux/config

Locate: 

    SELINUX=enforcing

Change: 

    SELINUX=disabled

Those using CentOS will most likely be running into this issue since 'SELINUX' is set to 'enforcing' by default.

**Comment by felipsmartins** [comment]
I run into the same, on OpenShift servers (Red Hat)

**Comment by bigmeech** [comment]
@felipsmartins How did you solve your issue? I'm using the free openshift for a nodejs proxy application and cant make any requests to an external service on port 8081. even the curl command to that ip:port gives me a permission denied. Please tell me you got it to work somehow :(

**Comment by felipsmartins** [comment]
@bigmeech I did not get workaround this issue. Not sure whether it's impossible solve this problem, but I'll take a look later.

**Comment by felipsmartins** [comment]
@bigmeech Also, have you seen this: http://stackoverflow.com/questions/30363274/accessing-port-7000-from-openshift-server

**Comment by bigmeech** [comment]
@felipsmartins okay thanks. I ended up moving my code to heroku though. As it turns out openshift has restrictions on services you can call especially when they are bound to non-standard ports. It uses SELinux policy for security so there is literally no way around it. Wasted a whole running a goose chase before i stumbled on this https://books.google.co.uk/books?id=K6aSAwAAQBAJ&pg=PA61&lpg=PA61&dq=openshift+selinux+policy&source=bl&ots=1B69uRpZRB&sig=4Nh_rzz_xHMcZjgCKz0bl6cSDxo&hl=en&sa=X&ved=0ahUKEwjS2vj4kdfJAhWCORQKHWCODX0Q6AEIRzAH#v=onepage&q=openshift%20selinux%20policy&f=false

**Comment by felipsmartins** [comment]
Nice, @bigmeech ! Many thanks for book info.

**Comment by nmfzone** [comment]
This issue still exists in my environment. Guzzle ^6.0. ElementaryOS Freya (based on Ubuntu 14.04).

When i try to make request to the url that has port (in my case because i use Laravel default port, so the url is http://localhost:8000), my browser will load, then never stops.

Anyone have solutions?

**Comment by rafiudeen92** [comment]
[google.com](url)

**Comment by panique** [comment]
same here! Guzzle simply cannot handle custom ports :/
Isn't it weird that only few people seems to have this problem ?

**Comment by mihirpatel83** [comment]
Same here.
1) Sucess
    ```
    Base URI - http://xxx.xxx.xxx.xxx:3000
    $client->post('gmail/auth');
```
2) Fails
    ```
Base URI - http://xxx.xxx.xxx.xxx:3000/gmail OR http://xxx.xxx.xxx.xxx:3000/gmail/
                  or
    $client->post('auth');
```

**Comment by asmdk** [comment]
It depends how you make a request:

`
// does not work because you should set up port through separate method
$url = 'https://somehost:8080/api/user';
$this->client->request('GET', $url);

// this one works, because url is parsed and port is set up automatically
$url = 'https://somehost:8080/api/user';
$uri = new Uri($url);
$this->client->request('GET', $uri);
`

Also if during init client you pass the host, it will be work also.

**Comment by japostulo** [comment]
We need to use withPort method

GuzzleHttp\Psr7zUtils::uriFor('http://localhost')->withPort('8000')
