### ISSUE TITLE
when dumping response object, statusCode is null

### ISSUE THREAD

**Issue by poolerMF** [guzzle/guzzle#1002]
everything works OK ... but when I dump response object, statusCode,reasonPhrase and other are NULL .. but if I call  method getStatusCode() it return correct data

this should be changed and method parseStatusLine() should by called in setHeaders(), not in getStatusCode() ...

setHeaders() should be:

    public function setHeaders(array $headers)
    {
        parent::setHeaders($headers);

        $this->resetStatusLine();
        $this->parseStatusLine();
    }

**Comment by mtdowling** [comment]
Can you provide a reproducible snippet of code please?

**Comment by poolerMF** [comment]
$response = $container->get("buzz.browser")->get('http://.......');
    dump($response);
    $response->getStatusCode();
    dump($response);

FIRST DUMP:
Response { ▼
  -protocolVersion: null
  -statusCode: null
  -reasonPhrase: null
  -headers: array:7 [▶]
  -content: "{"jsonrpc":"2.0","id":null,"error":{"code":-32700,"message":"Parse error"}}"
}

SECOND DUMP:
Response { ▼
  -protocolVersion: 1.1
  -statusCode: 200
  -reasonPhrase: "OK"
  -headers: array:7 [▶]
  -content: "{"jsonrpc":"2.0","id":null,"error":{"code":-32700,"message":"Parse error"}}"
}

**Comment by mtdowling** [comment]
Are you sure you're using Guzzle here? It appears you're using Buzz.

**Comment by poolerMF** [comment]
I'm sorry, you are right :)
