### ISSUE TITLE
Put() to Apiary.io Produces a cURL error Transfer closed with outstanding read data remaining

### ISSUE THREAD

**Issue by lchoate** [guzzle/guzzle#1003]
## Testing with Apiary.io produces an error 

[curl.haxx.se](http://curl.haxx.se/libcurl/c/libcurl-errors.html) says cURL error 18 is a descrepancy between what the server said it would send back (bytes) and what it actually did. However, the call completes as far as the api is concerned, the HTTP204 is given. Should I try/catch my way out of this? It seems like we'd want guzzle to handle this exception pretty gracefully. What do you think?

```Fatal error:  Uncaught exception **GuzzleHttp\Ring\Exception\RingException' with message 'cURL error 18: transfer closed with outstanding read data remaining** in /Users/lucas/websites/embedded-theme/vendor/guzzlehttp/ringphp/src/Client/CurlFactory.php:126
Stack trace:
#0 /Users/lucas/websites/embedded-theme/vendor/guzzlehttp/ringphp/src/Client/CurlFactory.php(90): GuzzleHttp\Ring\Client\CurlFactory::createErrorResponse(Object(GuzzleHttp\Ring\Client\CurlHandler), Array, Array)
#1 /Users/lucas/websites/embedded-theme/vendor/guzzlehttp/ringphp/src/Client/CurlHandler.php(77): GuzzleHttp\Ring\Client\CurlFactory::createResponse(Object(GuzzleHttp\Ring\Client\CurlHandler), Array, Array, Array, Resource id #71)
#2 /Users/lucas/websites/embedded-theme/vendor/guzzlehttp/ringphp/src/Client/Middleware.php(54): GuzzleHttp\Ring\Client\CurlHandler-&gt;__invoke(Array)
#3 /Users/lucas/websites/embedded-theme/vendor/guzzlehttp/ringphp/src/Client/Middleware.php(30): GuzzleHttp\Ring\Client\Middleware::GuzzleHttp\Ring\Client\{closure}(Array)
#4 /Us in /Users/lucas/websites/embedded-theme/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php on line 51```

### The code that produces the error is a simple put
It works fine when using a get()
```<?php 
    $res = $client->put($app->api_uri."student/".$data['studentid'],
                ['headers' => ['accept' => 'application/json','x-api-key'=>$app->getApi_key()],
                'json' => json_encode($data)]
                             );
     $responsecode = $res->getStatusCode();
     ?>
```

Apiary says it looks fine to them...
![apiary.io traffic](http://damndad.com/wp-content/uploads/2015/03/screencapture-docs-embedded-apiary-io-traffic.png)

**Comment by mtdowling** [comment]
I don't see how Guzzle would handle this without throwing an exception. The server was supposed to send more data to the client but closed the connection (or maybe even the client closed it for some reason).

**Comment by lchoate** [comment]
Fair enough. The concern was that the other side reported that the transaction worked fine and since I can watch both in real time, we see the API responded in milliseconds where my app timed out waiting for that response. I'll close the issue.
