### ISSUE TITLE
Get curl_errno from RequestException

### ISSUE THREAD

**Issue by RomeroMsk** [guzzle/guzzle#1006]
Please, add the way for getting cURL error number from `GuzzleHttp\Exception\RequestException`. Why not pass it to exception code?

**Comment by mtdowling** [comment]
Guzzle has a layer of abstraction over curl, allowing you to swap out curl for any other underlying transport mechanism. This is why the curl error is not the exception code. Relying on that behavior would couple you to curl, which is discouraged.

Why do you need the error code?

**Comment by RomeroMsk** [comment]
I need it to filter by code and see charts in logging system. Maybe I can somehow get this code from exception?

**Comment by RomeroMsk** [comment]
I understand about abstraction, but why not add a code to ConnectException constructor call? Now exception code is not using (it is default 0 value), adding it will not brake anything.

**Comment by kamilsk** [comment]
> Maybe I can somehow get this code from exception?
If you want you can get cURL error code from exception message: "cURL error 6: Could not resolve host: ...".

But ConnectException should know nothing about the internals of cURL and its error codes.

**Comment by mtdowling** [comment]
I've added this as a new feature to Guzzle 6: https://github.com/guzzle/guzzle/commit/251954e092406d79bde5913e8fd1cba6a25d7162. In Guzzle 5, you could just parse the exception message as @kamilsk stated. Keep in mind that doing this (either using the added feature in Guzzle 6 or parsing the message), you're coupling your code to a specific handler.

**Comment by silverdr** [comment]
I have a similar problem - I can't really tell the user "cURL error 6: See http://curl.haxx.se/libcurl/c/libcurl-errors.html". Is there a way to retrieve something more user-friedly?

**Comment by silverdr** [comment]
As a response to my previous comment above - I just sent a pull request for RingPHP, which in current version doesn't set the plain text error message when PHP version < 5.5
