### ISSUE TITLE
Built-in rate limiting

### ISSUE THREAD

**Issue by njohansson** [guzzle/guzzle#1008]
Quite many APIs enforce rate limiting. I would find it useful to have built-in functionality in Guzzle letting me configure how many requests per time unit I want Guzzle to be able to issue.

For example, say I need to do 2000 API requests and the API I'm calling has a strict 10 requests / second maximum. If avg request time is 1 second I could use a Pool:send() with a pool_size of e.g. 8 (some spare room) to try to keep things under control and be nice to the receiving server.

Instead of implementing a strategy that push as hard as it can and backs off when receiving throttling responses I find it would be useful to make more efficient use of resources (at both ends) and be able to configure "10 requests / second" and make sure Guzzle do not ever attempt to perform more than this.

I apologize if there's a way to easily implement this already, if so a pointer in the right direction would be much appreciated. However, I do think it could be useful as a general feature.

**Comment by mtdowling** [comment]
I don't think this will be a feature in Guzzle, but it should be possible to achieve with the Pool object by decorating the iterator you provide the pool to keep track of the speed in which it yields requests. When the number of requests/second is greater than what you'd like, you can sleep or add the "delay" request option to a request to sleep at the HTTP handler layer.

Maybe this would be a good third-party project that uses Guzzle.
