### ISSUE TITLE
Check intermediate dirs in 'save_to' option

### ISSUE THREAD

**Issue by indeyets** [guzzle/guzzle#1010]
In cases when `save_to` option gets string with a path it is important to make sure, that intermediate directories exist. Otherwise, when attempt to save the file is made `Could not call the CURLOPT_HEADERFUNCTION` warning is given and file isn't saved.

There are 2 possible user-friendly solutions:

1. create directories
2. bail-out early, telling that directory does not exist

**Comment by mtdowling** [comment]
Encountering that error is a bug, and it should be fixed. I don't want to create directories from Guzzle, but I do think ensuring that the file can be created is a requirement. I prefer to not do this early on, but only lazily on the first write (e.g., because you might not even send the request).

**Comment by mtdowling** [comment]
Fixed in https://github.com/guzzle/RingPHP/commit/06bab717fb6df6aca74faa9512ea46b55cc80c1a
