### ISSUE TITLE
Redirects in Pool results in 'error'

### ISSUE THREAD

**Issue by pvdbroek** [guzzle/guzzle#1013]
I'm using a pool to call a number of urls and I'm having some trouble with redirects.

I would expect that a redirect would be followed 'below the surface', and the new url would then be called as if it was defined in $requests. What I'm seeing, is that a redirect (both 302 or 301) is being handelled by the 'error' part, and if I lookup the error code in the 'error' option-code, it gives 301 or 302. 

How can I tell guzzle to follow redirects?

Some relevant code I'm using:

	$client = new \GuzzleHttp\Client();

	$options = [
		'pool_size' => 3,

		'complete' => function (\GuzzleHttp\Event\CompleteEvent $event) {
			.......
		},
		'error' => function (\GuzzleHttp\Event\ErrorEvent $event)  {
			.........
		},
	];

	\GuzzleHttp\Pool::send($client, $requests, $options);

**Comment by mtdowling** [comment]
Redirects should not result in an error. What's the result that is being given for the error?

**Comment by pvdbroek** [comment]
Hmm it looks like it is a bit more complicated, as most of the redirects are indeed followed correctly, but the following redirect results in an error:

http://www.dress-for-less.nl/tmpl/shop.tmpl?main_cat=1%3Bcat%3D1
-> 301 to ->
http://www.dress-for-less.nl/tmpl/shop.tmpl?main_cat=1;cat%3D1

As you can see, the only difference is an escaped " ; " (%3B).

This redirect results in an error.

The full content of the Respose can be found below:


GuzzleHttp\Message\Response Object
(
    [reasonPhrase:GuzzleHttp\Message\Response:private] => Moved Permanently
    [statusCode:GuzzleHttp\Message\Response:private] => 301
    [effectiveUrl:GuzzleHttp\Message\Response:private] => http://www.dress-for-less.nl/tmpl/shop.tmpl?main_cat=1%3Bcat%3D1
    [headers:GuzzleHttp\Message\AbstractMessage:private] => Array
        (
            [date] => Array
                (
                    [0] => Mon, 30 Mar 2015 12:27:37 GMT
                )

            [server] => Array
                (
                    [0] => Apache
                )

            [location] => Array
                (
                    [0] => /tmpl/shop.tmpl?main_cat=1;cat%3D1
                )

            [vary] => Array
                (
                    [0] => Accept-Encoding
                )

            [content-length] => Array
                (
                    [0] => 242
                )

            [connection] => Array
                (
                    [0] => close
                )

            [content-type] => Array
                (
                    [0] => text/html; charset=iso-8859-1
                )

        )

    [headerNames:GuzzleHttp\Message\AbstractMessage:private] => Array
        (
            [date] => Date
            [server] => Server
            [location] => Location
            [vary] => Vary
            [content-length] => Content-Length
            [connection] => Connection
            [content-type] => Content-Type
        )

    [body:GuzzleHttp\Message\AbstractMessage:private] => GuzzleHttp\Stream\Stream Object
        (
            [stream:GuzzleHttp\Stream\Stream:private] => Resource id #506
            [size:GuzzleHttp\Stream\Stream:private] =>
            [seekable:GuzzleHttp\Stream\Stream:private] => 1
            [readable:GuzzleHttp\Stream\Stream:private] => 1
            [writable:GuzzleHttp\Stream\Stream:private] => 1
            [uri:GuzzleHttp\Stream\Stream:private] => php://temp
            [customMetadata:GuzzleHttp\Stream\Stream:private] => Array
                (
                )

        )

    [protocolVersion:GuzzleHttp\Message\AbstractMessage:private] => 1.1
)

**Comment by mtdowling** [comment]
What's the error after following the redirect? 404?

**Comment by pvdbroek** [comment]
The errorcode is 301. Maybe guzzle sees the two (slightly different) urls as a redirect to the same url, and to prefend an infinite loop, it gives an error?

**Comment by mtdowling** [comment]
Can you tell me what the exception class is that's inside of the error event? Is it a TooManyRedirectsException? I bet the same error occurs if you send the request outside of the pool as well. Can you confirm?

**Comment by mtdowling** [comment]
Guzzle 5 automatically decomposes a query string into key value pairs and then url-encodes it when sending a request. This mimics how http_build_query() works for example. Because of this, the ";" is being percent-encoded and causing a redirect loop. You'll need to disable percent-encoding when contacting this web service.

```php
<?php
require 'vendor/autoload.php';
$c = new GuzzleHttp\Client(['defaults' => ['debug' => true]]);
$request = $c->createRequest('GET', 'http://www.dress-for-less.nl/tmpl/shop.tmpl?main_cat=1;cat%3D1');
$request->getQuery()->setEncodingType(false);
echo $c->send($request);
```

I don't think this is something that can be changed in a backwards compatible way in Guzzle 5.

That said, .this URI works fine with Guzzle 6 (which is based on PSR-7).
