### ISSUE TITLE
Stop running download in Progress Event

### ISSUE THREAD

**Issue by bcremer** [guzzle/guzzle#1014]
Is there any way to stop a running request for example in the progress event?

```
$client = new Client();
$request = $client->createRequest('GET', $url);

$startTime = microtime(true);
$request->getEmitter()->on('progress', function (ProgressEvent $e) use ($startTime) {
    if (microtime(true) - $startTime > 3) {
        return $e->stopRequest(); // stop running request
    }
});

$response = $client->send($request);
```

My use case is a large file download initiated by the user in the browser limited by PHPs max_execution_time.
The download is done using ajax calls that download parts of the file using the range header, premature end the request after a few seconds so a new ajax requests continues the download using the offset from the partly downloaded file.

**Comment by mtdowling** [comment]
This is not possible with the progress event. You could try using the ``timeout`` request option instead.
