### ISSUE TITLE
Compatibility with PHP7

### ISSUE THREAD

**Issue by stefanruijsenaars** [guzzle/guzzle#1015]
Copying @Berdir from https://github.com/guzzle/RingPHP/issues/22:

>Drupal8 has a critical release blocker to be compatible with PHP7.
>
>The installer currently fails because of guzzle. I tried to fix those errors myself, but I can't really make sense of the code, apart from the first one, which seems easy enough to fix:
>
>Fatal error: Redefinition of parameter $_ in /vendor/guzzlehttp/ringphp/src/Client/StreamHandler.php on line 313
>=> This seems easy enough, I guess it's no longer possible to have multiple identical parametes
>
>Fatal error: Argument 3 passed to GuzzleHttp\Ring\Client\StreamHandler::createResponse() must be of the type array, null given, called in /vendor/guzzlehttp/ringphp/src/Client/StreamHandler.php on line 34 and defined in /vendor/guzzlehttp/ringphp/src/Client/StreamHandler.php on line 40
>=> I can't figure out where headers would be set, it's just passed around by reference but never set?
>
>Fatal error: Argument 1 passed to GuzzleHttp\Message\FutureResponse::proxy() must implement interface GuzzleHttp\Ring\Future\FutureInterface, null given, called in /src/RequestFsm.php on line 133 and defined in /src/Message/FutureResponse.php on line 36
>=> This is coming from testCanSpecifyHandler(), somehow that trick with throwing an exception doesn't seem to work anymore...
>
>Didn't get past the last one yet...
>
>For reference, this is the Drupal issue: https://www.drupal.org/node/2454439#comment-9768963

**Comment by mtdowling** [comment]
Can you send a PR?

**Comment by mtdowling** [comment]
All of the RingPHP specific errors are fixed. Are there any Guzzle specific errors?

**Comment by Berdir** [comment]
Thanks for fixing them. The FutureResponse error is AFAIK in guzzle, not in RingPHP, so that might still be failing when running the Guzzle tests on PHP7. 

I've seen in https://github.com/md-systems/pathauto/pull/31/files that it's possible to add PHP7 but allow failures. We could do that to have an easy way to see those errors and then remove the allow_failures when they're all fixed?

**Comment by mtdowling** [comment]
I think everything is working now. Feel free to open new issues with specific problems that need to be addressed.
