### ISSUE TITLE
Request to google api

### ISSUE THREAD

**Issue by urazov** [guzzle/guzzle#1023]
Hi guzzle team! 
Please write the sample of code that makes request with json in post's body and query parameter at the same time.

Approximately request should looks like:
POST https://www.googleapis.com/calendar/v3/calendars/id_calendar/events?key=secret_key

Body: 
{
 "end": {
  "date": "2015-04-10"
 },
 "start": {
  "date": "2015-04-09"
 }
} 

Thanks a lot!

**Comment by mtdowling** [comment]
Hi! Please send support requests to the gitter channel or the forum: https://gitter.im/guzzle/guzzle - https://groups.google.com/forum/#!forum/guzzle
