### ISSUE TITLE
InvalidArgumentOnly one auth mechanism allowed

### ISSUE THREAD

**Issue by kichuit19** [guzzle/guzzle#1030]
Hi

  We are facing issue while downloading file from our URL using Guzzel as
  
  **"InvalidArgumentOnly one auth mechanism allowed; only the X-Amz-Algorithm query parameter, Signature query string parameter or the Authorization header"**

  **Sample code**

 ```  
       $client = new Client();
        $request = $this->client->createRequest('GET','url',[ 'auth' => ['usename', 'password', 'Digest']]);
        $response = $this->client->send($request);
        echo $response;
 ```

##### System specification:

 OS : Ubuntu 14.04 64-bit
 PHP:  PHP 5.5.9
 Curl version : curl 7.35.0 (x86_64-pc-linux-gnu) libcurl/7.35.0 OpenSSL/1.0.1f zlib/1.2.8 libidn/1.28 librtmp/2.3

##### But the above code working fine for us in following version
 OS : ubuntu 14.04 64-bit
 PHP: PHP 5.4.35
 Curl version : curl 7.22.0 (x86_64-pc-linux-gnu) libcurl/7.22.0 OpenSSL/1.0.1 zlib/1.2.3.4 libidn/1.23 librtmp/2.3

**Comment by mtdowling** [comment]
I've never seen that error. Is it coming from the API?

**Comment by kamilsk** [comment]
Can you show dump of two requests on different environments?

Perhaps this tool will be useful: https://github.com/namshi/cuzzle

**Comment by kichuit19** [comment]
Below are the dumps of the request

1. curl \ 'URL' \ -A 'Guzzle/5.2.0 curl/7.35.0 PHP/5.5.9-1ubuntu4.7'

2. curl \ 'URL' \ -A 'Guzzle/5.2.0 curl/7.22.0 PHP/5.4.35-1+deb.sury.org~precise+1'

we have did some work around on this issue, i don't know whether its correct or not

#### guzzlehttp/ringphp/src/Client/CurlFactory.php 

in a getDefaultOptions() method we have added  **CURLOPT_FOLLOWLOCATION => true** after adding this we are getting our expected result, if we set it as false the issue remains the same

Is there any option set CURLOPT_FOLLOWLOCATION from our end as a config

please give me some suggestion on this

**Comment by kamilsk** [comment]
> Is there any option set CURLOPT_FOLLOWLOCATION from our end as a config

Yes, you can
http://guzzle.readthedocs.org/en/latest/clients.html#config
```php
$client->get('url', [
    'auth' => ['usename', 'password', 'Digest']
    'config' => [
        'curl' => [
            CURLOPT_FOLLOWLOCATION => true
        ]
    ]
]);
```

**Comment by kichuit19** [comment]
yes it's working fine now, thanks @kamilsk and @mtdowling

**Comment by kamilsk** [comment]
Glad to be of help! The issue is no longer relevant?
