### ISSUE TITLE
cURL error 35 + 52

### ISSUE THREAD

**Issue by alixaxel** [guzzle/guzzle#1031]
I'm running a batch of 32 continuous requests and occasionally I'm seeing the following exceptions:

```shell
cURL error 35: SSL connect error [./vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:49]
cURL error 52: Server returned nothing (no headers, no data) [./vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:49]
```

Once the application gets to this point the only way to resume Guzzle requests is to restart it. I'm using Guzzle Pool with a pool_size of 32, and I suspect the problem may be with some timeout configuration.

Has anyone faced the same issue? Can I overcome this with any Guzzle/cURL setting?

**Comment by kamilsk** [comment]
http://stackoverflow.com/questions/4073404/curl-errno-35-unknown-ssl-protocol-error-in-connection-to-secure-site443
http://guzzle.readthedocs.org/en/latest/clients.html#config

```php
$client->get('/', [
    'config' => [
        'curl' => [
            CURLOPT_SSLVERSION => 3 // replace 3 with whatever SSL version the remote server is using
        ]
    ]
]);
```

no?

**Comment by alixaxel** [comment]
@kamilsk Unfortunately no, I'm still facing the same issues.

**Comment by mtdowling** [comment]
I'm not sure how to fix these at the curl level, but you could just retry these failures using something like the retry-subscriber: https://github.com/guzzle/retry-subscriber

**Comment by konrness** [comment]
@alixaxel did you ever find the cause of your Curl Error 52?

**Comment by alixaxel** [comment]
@konrness No, at some point it just disappeared. I suspect the server/firewall dropped those requests.

**Comment by bricebentler** [comment]
@kamilsk Very helpful for me.
