### ISSUE TITLE
POST: Bad request

### ISSUE THREAD

**Issue by jonathan-s** [guzzle/guzzle#1034]
I've been trying to make a POST request with the following code but not getting it to work. I get a bad request. How would I see the full response of a bad request rather than just getting that error? Also, when I use the same fields but make a regular cURL request it works. So I'm pretty stumped.  

       use GuzzleHttp\Client as NewGuzzle;
       
        $url = 'https://api.serverdensity.io/users/users?token=tokenhere';
        $user = [
            'body' => [
                'login' => 'duck',
                'firstName' => 'mr duck',
                'lastName' => 'lame',
                'password' => 'dummy'
            ]
        ];

        $client = new NewGuzzle();
        $response = $client->post($url, $user);
        echo $response;

**Comment by kamilsk** [comment]
Do you mean this?

```php
// configuring
try {
    $response = $client->post($url, $user);
} catch (RequestException $e) {
    print_r($e->getResponse());
}
```

> Also, when I use the same fields but make a regular cURL request it works

That shows the result of the query in cURL?

**Comment by jonathan-s** [comment]
Thanks, that's exactly what I was looking for!

**Comment by kamilsk** [comment]
Could I ask you to close the issue? I have no rights to it.
