### ISSUE TITLE
getTransaction is protected and should be public

### ISSUE THREAD

**Issue by rdohms** [guzzle/guzzle#1035]
Looking here: https://github.com/guzzle/guzzle/blob/master/src/Event/AbstractRequestEvent.php#L57

`getTransaction` is a protected getter, of a protected property, which seems to be a mistake.

Should this be public? My use case is lower down in using the guzzle-services library, i want to throw a custom exception but in order to not have it be wrapped by a CommandException i need to extend from it. This means i need the transaction to be fed into the exception, which due to the getter above i cannot get from the ErrorEvent.

Any ideas?

**Comment by mtdowling** [comment]
I would be fine with it being public. 

We've been doing a lot of discovery work in the AWS PHP SDK, and found the event/exception system wrapping exceptions quite hard to work with. We will likely be implementing something similar from the SDK into Guzzle services. I think Jeremy will be the lead on it.
