### ISSUE TITLE
Unable to add a listener

### ISSUE THREAD

**Issue by jonathan-s** [guzzle/guzzle#1036]
This is somewhat what my class looks like. Then when I test the functionality it doesn't work. 
    
    class ClientClass
    {
         use HasEmitterTrait;

        public function authenticate($token, $method)
        {
            $emitter = $this->getEmitter();

            $emitter->on('before', function(BeforeEvent $event){
                echo "coolest in town";
            });
        }
    }

This is my testing function that fails. It doesn't register any listeners at all. Any clues on where things go wrong? If though the authenticate is called once and then should add a listener no listener is added at all. 

         /**
         * @test
         * @dataProvider getAuthenticationFullData
         */
        public function shouldAuthenticateUsingAllGivenParameters($token, $method)
        {
            $client = new GuzzleClient();
            $listeners = $client->getEmitter()->listeners('before');
            $this->assertCount(0, $listeners);

            $httpClient = new TestHttpClient(array(), $client);
            $httpClient->authenticate($token, $method);

            $listeners = $client->getEmitter()->listeners('before');
            $this->assertCount(1, $listeners);
        }

        public function getAuthenticationFullData()
        {
            return array(
                array('tokenHere', Client::AUTH_URL_TOKEN)
            );
        }

**Comment by jonathan-s** [comment]
Ok, an update. Checking the client code it contains one listener. Though the test doesn't catch that... hmm.

**Comment by jonathan-s** [comment]
Ok, related to this issue. Is it possible to use a function that is not anonymous but defined elsewhere. How would you do it?

**Comment by kamilsk** [comment]
How `TestHttpClient` looks like?
I see you call `$httpClient->authenticate()`, but check listeners in `$client`.

**Comment by kamilsk** [comment]
> Ok, related to this issue. Is it possible to use a function that is not anonymous but defined elsewhere. How would you do it?

I think you can use any valid callback like this
```php
$emitter->on('before', [$this, 'existingMethod']);
```

**Comment by jonathan-s** [comment]
Yup, I noticed that and that resolved that issue. 
Regarding the valid callback, can $this be a class for instance?

**Comment by kamilsk** [comment]
> Regarding the valid callback, can $this be a class for instance?
I think yes
```php
$emitter->on('before', ['\Some\Class', 'existingMethod']);
```
or
```php
$emitter->on('before', '\Some\Class::existingMethod');
```
or
```php
$emitter->on('before', ['\Some\Class', 'parent::existingMethod']);
```

**Comment by kamilsk** [comment]
> Checking the client code it contains one listener. Though the test doesn't catch that... hmm.
Update: I figured that one out.

What was the error?

**Comment by jonathan-s** [comment]
> What was the error?

I was updating code test code that was written for guzzle3 and it seems like the event listeners transferred between inherited classes there. In guzzle5 it's more isolated. So just making sure that it was `$httpClient` rather than `$client` solved that issue. As you pointed out :)

**Comment by mtdowling** [comment]
Looks like you're all set here.
