### ISSUE TITLE
Is this compatible with Laravel 5? Getting stream output.

### ISSUE THREAD

**Issue by panelo** [guzzle/guzzle#1040]
After installing i tried to implement in controller...

    <?php namespace App\Http\Controllers;

    use \GuzzleHttp\Client;

    class SampleController extends \Controller {
        public function getIndex() {
		    $client = new Client();
		    $response = $client->get('http://httpbin.org/get');
		    dd($response->getBody());
        }
    }

but i'm getting this output instead of the proper one with that URL.

    Stream {#287 ▼
      -stream: :stream {@11 ▶}
      -size: null
      -seekable: true
      -readable: true
      -writable: true
      -uri: "php://temp"
      -customMetadata: []
    }

did i miss something?

**Comment by mtdowling** [comment]
I have no idea what Laravel does here. If you need to give Laravel a string, just cast the body to a string:

`dd((string) $response->getBody());`

**Comment by panelo** [comment]
that works, but I wonder if it works the same as a proper restful format because of the """? Need to retrieve it in views (e.g. return \View::make('samplerest')->with('tests',$body);)

    """
      {
        "args": {}, 
        "headers": {
          "Host": "httpbin.org", 
          "User-Agent": "Guzzle/5.2.0 curl/7.35.0 PHP/5.5.9-1ubuntu4.5"
       }, 
        "origin": "101.164.236.102", 
        "url": "http://httpbin.org/get"
      }
      """

**Comment by panelo** [comment]
I got it! turns out I need to json_decode rather than string.

    $body = json_decode($response->getBody());

**Comment by kamilsk** [comment]
@panelo, you can use `$response->json();` instead of `json_decode($response->getBody());`
