### ISSUE TITLE
GuzzleHttp\Exception\RequestException: Undefined variable: response

### ISSUE THREAD

**Issue by jonathan-s** [guzzle/guzzle#1043]
I'm getting this error after running this code. $httpMethod is 'GET' and $path is a regular url path.

        $request = $this->client->createRequest($httpMethod, $path);
        $response = $this->client->send($request);

`$this->client` is an instance of `GuzzleHttp\Client`.

The full traceback I get is the following. Any clues where things might go wrong? Or what could trigger the error? 

    GuzzleHttp\Exception\RequestException: Undefined variable: response

    /Users/jonathan/projects/api-php-wrapper/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:51
    /Users/jonathan/projects/api-php-wrapper/vendor/guzzlehttp/guzzle/src/RequestFsm.php:147
    /Users/jonathan/projects/api-php-wrapper/vendor/guzzlehttp/guzzle/src/RequestFsm.php:132
    /Users/jonathan/projects/api-php-wrapper/vendor/react/promise/src/FulfilledPromise.php:24
    /Users/jonathan/projects/api-php-wrapper/vendor/guzzlehttp/ringphp/src/Future/CompletedFutureValue.php:55
    /Users/jonathan/projects/api-php-wrapper/vendor/guzzlehttp/guzzle/src/Message/FutureResponse.php:43
    /Users/jonathan/projects/api-php-wrapper/vendor/guzzlehttp/guzzle/src/RequestFsm.php:135
    /Users/jonathan/projects/api-php-wrapper/vendor/guzzlehttp/guzzle/src/Client.php:232
    /Users/jonathan/projects/api-php-wrapper/lib/serverdensity/HttpClient/HttpClient.php:166
    /Users/jonathan/projects/api-php-wrapper/test/serverdensity/Tests/functional/UserTest.php:81

    Caused by
    PHPUnit_Framework_Error_Notice: Undefined variable: response

    /Users/jonathan/projects/api-php-wrapper/lib/serverdensity/HttpClient/Listener/ErrorListener.php:41
    /Users/jonathan/projects/api-php-wrapper/lib/serverdensity/HttpClient/HttpClient.php:62
    /Users/jonathan/projects/api-php-wrapper/vendor/guzzlehttp/guzzle/src/Event/Emitter.php:109
    /Users/jonathan/projects/api-php-wrapper/vendor/guzzlehttp/guzzle/src/RequestFsm.php:106
    /Users/jonathan/projects/api-php-wrapper/vendor/guzzlehttp/guzzle/src/RequestFsm.php:132
    /Users/jonathan/projects/api-php-wrapper/vendor/react/promise/src/FulfilledPromise.php:24
    /Users/jonathan/projects/api-php-wrapper/vendor/guzzlehttp/ringphp/src/Future/CompletedFutureValue.php:55
    /Users/jonathan/projects/api-php-wrapper/vendor/guzzlehttp/guzzle/src/Message/FutureResponse.php:43
    /Users/jonathan/projects/api-php-wrapper/vendor/guzzlehttp/guzzle/src/RequestFsm.php:135
    /Users/jonathan/projects/api-php-wrapper/vendor/guzzlehttp/guzzle/src/Client.php:232
    /Users/jonathan/projects/api-php-wrapper/lib/serverdensity/HttpClient/HttpClient.php:166
    /Users/jonathan/projects/api-php-wrapper/test/serverdensity/Tests/functional/UserTest.php:81

**Comment by kamilsk** [comment]
I think you need to carefully look at the test code.

**Comment by jonathan-s** [comment]
@kamilsk, the thing is that the test code only consists of the following two lines.

        $client = new HttpClient();
        $client->request($baseUrl.$url, null, 'GET');

The next level calls the request function: 

    public function request($path, $body = null, $httpMethod = 'GET', array $headers = array(), array $options = array())
    {
        if(!empty($body)){
            $options = array_merge($options, ['body' => $body]);
        }

        $listeners = $this->client->getEmitter()->listeners('before');
        echo "Number of request authlisteners: ".count($listeners)."\n";

        echo $httpMethod." ".$path;
        $request = $this->client->createRequest($httpMethod, $path);
        $response = $this->client->send($request); // this is line 166 of HttpClient
        echo $response; // even if I remove this I get the same result. 
    }

**Comment by jonathan-s** [comment]
It turns out that I get this error when I trigger this function which attaches an event. If I don't trigger it, it works fine. 

    public function authenticate($token, $method)
    {
        $this->client->getEmitter()->on(
            'before', function (BeforeEvent $event){
                $auth = new AuthListener($token, $method);
                $auth->onRequestBeforeSend($event);
            });
    }

even if empty all the contents on the `onRequestBeforeSend` function I get this error, so it seems like it has something to do with attaching the listener.

**Comment by jonathan-s** [comment]
The `undefined variable: response`, came from ErrorListener.php in the traceback. Fixing that, then leads to you back to the `authenticate` function where it complains about undefined token and undefined method. 

If you define it in the closure as such

    public function authenticate($token, $method)
    {
        $this->client->getEmitter()->on(
            'before', function (BeforeEvent $event, $token, $method){
                $auth = new AuthListener($token, $method);
                $auth->onRequestBeforeSend($event);
            });
    }

It gives me another error of `Missing argument 3 for closure` called in emitter on line 109. So it seems like `$eventName` is missing. Which makes me wonder if I'm attaching the events in a wrong way and how you should do it in a proper way. 

    public function emit($eventName, EventInterface $event)
    {
        if (isset($this->listeners[$eventName])) {
            foreach ($this->listeners($eventName) as $listener) {
                $listener($event, $eventName);
                if ($event->isPropagationStopped()) {
                    break;
                }
            }
        }
        return $event;
    }

**Comment by kamilsk** [comment]
> It gives me another error of Missing argument 3 for closure called in guzzle's

```php
public function authenticate($token, $method)
{
    $this->client->getEmitter()->on(
        'before', function (BeforeEvent $event, $token) use ($method){
            $auth = new AuthListener($token, $method);
            $auth->onRequestBeforeSend($event);
        });
}
```
Are you sure that the token is passed? I would recommend the following
```php
public function authenticate($token, $method)
{
    $this->client->getEmitter()->on(
        'before', function (BeforeEvent $event) use ($token, $method) {
            $auth = new AuthListener($token, $method);
            $auth->onRequestBeforeSend($event);
        });
}
```

**Comment by jonathan-s** [comment]
@kamilsk Magic! I didn't know you could use that construct. Thanks a bunch for the help <3

**Comment by kamilsk** [comment]
Happy to help! :sunny:
