### ISSUE TITLE
Client error response [status code] 400 [reason phrase] Bad Request [url] 

### ISSUE THREAD

**Issue by andamhan** [guzzle/guzzle#1044]
Keep getting this error back from guzzle (3.9), tried all sorts of configurations  (latest below). Is this a known issue with guzzle or a config issue?

$client = new \Guzzle\Service\Client(Config::get('config.restURL').'/rest/Account/');	
		$client->setDefaultOption('headers', array(
			'Accept-Encoding' => 'gzip,deflate',
			'Content-Type' => 'application/json'
			));

		try {
		   $response = $client->post('CreateAccount',[
		    'body' => json_encode([
		    		'mvnoID' => '6',
		    		'CustomerId' => 'CUST0000903518',
		    		'RatePlanId' => 'NP',
		    		'Sim' => '8944110064810088876',
		    		'AccountStatus' => '2'
		    	])	    
			])->send();

		}catch (Exception $e) {
		    print_r($e->getResponse());
		}

**Comment by kamilsk** [comment]
what shows `print_r($e->getResponse())`?

**Comment by kamilsk** [comment]
in particular `$e->getResponse()->getBody()`

**Comment by andamhan** [comment]
Guzzle\Http\EntityBody Object ( [contentEncoding:protected] => [rewindFunction:protected] => [stream:protected] => Resource id #238 [size:protected] => [cache:protected] => Array ( [wrapper_type] => PHP [stream_type] => TEMP [mode] => w+b [unread_bytes] => 0 [seekable] => 1 [uri] => php://temp [is_local] => 1 [is_readable] => 1 [is_writable] => 1 ) [customData:protected] => Array ( ) )

**Comment by andamhan** [comment]
that's the getBody() response, cheers!

**Comment by kamilsk** [comment]
`(string) $e->getResponse()->getBody()`

**Comment by mtdowling** [comment]
You might need to set a Content-Type on the request. If that does not work, you could try posting to the Guzzle Gitter channel or StackOverflow.

**Comment by sameer1001** [comment]
Hey, Was this issue resolved by adding Content-Type on the request? We are also having similar issues. It doesn't happen always, only occasionally some requests fail with this error. We are using Guzzle 3.9.3.

**Comment by andamhan** [comment]
Can't remember exactly what solved it, but I'm now setting up the client as per below before posting the request:

        	```
$client = new \GuzzleHttp\Client();
			$client->setDefaultOption('headers', array(
				'Accept-Encoding' => 'gzip,deflate',
				'Content-Type' => 'application/json'
				));
```

**Comment by sagikazarmark** [comment]
Note that Guzzle 3 and 4 are EOL and unsupported.

**Comment by Glideh** [comment]
I had this issue with Guzzle 6, trying to test an API implemented with Symfony 3.

```php
$client = new Client(['base_uri' => 'http://nginx',]);
$client->get('/api/hello');
```

I found the issue by reading the big markedup response with cURL:

```bash
$ curl -i http://nginx
```

Turned out I forgot to add `nginx` as trusted host in the config...

**Comment by navidman** [comment]
> Hey, Was this issue resolved by adding Content-Type on the request? We are also having similar issues. It doesn't happen always, only occasionally some requests fail with this error. We are using Guzzle 3.9.3.

I have same problem. sometimes it happens. can you please share how did you solve this issue?
