### ISSUE TITLE
What ever happened to useUrlEncoding? setEncodingType doesn't seem to function?

### ISSUE THREAD

**Issue by chielteuben** [guzzle/guzzle#1045]
I've been going through the docs, the changelog, everything, it was never stated that useUrlEncoding was phased out / replaced. Not a line about setEncodingType (I actually discovered it through stackoverflow).  
  
I'm trying to prevent Guzzle from encoding the email field I'm trying to post but no matter what it'll resort to replacing @ with %40. That is with setEncodingType set to false.
I've looked at the source of setEncodingType and for what I can see it should simply work.

A simple example:
$client = new Client();
$request = $client->createRequest('POST', $baseUrl . 'test/post');
$request->setHeader('Content-Type', 'application/json');
$request->addHeader('Authorization', 'Token ' . $tokenTest);
$request->getQuery()->setEncodingType(false);
$request->getBody()->setField('email', 'testing@testing.com');
$response = $client->send($request);

Ends up with a 400 Bad Request (because the service expects a non encoded field), I've confirmed through wireshark that the email field is actually being sent as testing%40testing.com
That is with setEncodingType to false. Any ideas?

**Comment by mtdowling** [comment]
You are setting the encoding type of the query string and not of the body, so this is not related.

When sending a POST with Guzzle's built-in POST functionality, Guzzle sends the body of the post encoded with RFC 1738. This decision was made based on http://www.w3.org/TR/html401/interact/forms.html#h-17.13.4.1. If you need to send a similar request that diverges from this encoding type, then you'll need to create the body of the request manually and inject it into the request using setBody().

**Comment by milsanore** [comment]
Does the equivalent of a setBody() function exist in guzzle 6? Thanks

**Comment by sagikazarmark** [comment]
No, PSR-7 requests are immutable. Please check the PSR-7 standard page for details: http://www.php-fig.org/psr/psr-7/
