### ISSUE TITLE
Next Release?

### ISSUE THREAD

**Issue by GrahamCampbell** [guzzle/guzzle#1046]
Is there any chance you could tag another release please so we could get the recent changes in a stable release?

**Comment by mtdowling** [comment]
![soon](http://img1.wikia.nocookie.net/__cb20140818144207/degrassi/images/5/52/Soon-raccoon.gif)

**Comment by GrahamCampbell** [comment]
:P

**Comment by kamilsk** [comment]
@GrahamCampbell https://github.com/guzzle/guzzle/releases/tag/5.3.0 is out

**Comment by GrahamCampbell** [comment]
Awesome.
