### ISSUE TITLE
Error 500 results in no response in ErrorEvent?

### ISSUE THREAD

**Issue by skoop** [guzzle/guzzle#1048]
While working on a project where we use Guzzle to connect to a third party service, we ran into an issue: The 3rd party service returns an error 500. Our code logs all errors (regardless of error code):

```php
        $extra = [
            'request' => (string) $event->getRequest()->getBody(),
            'response' => (string) $event->getResponse()->getBody(),
        ];

        $this->logger->log(
            Logger::EMERG,
            $exception->getMessage(),
            $extra
        );
```

In case of an error 500, this results in:

  > Fatal error:  Call to a member function getBody() on a non-object

As it turns out, the 3rd party service returns a body with the error 500 though that gives more information about the cause of the error. Is there a way we can get the response from the event in this case?

**Comment by kamilsk** [comment]
> In case of an error 500, this results in
> > Fatal error: Call to a member function getBody() on a non-object

Look carefully at the method signature: `@return ResponseInterface|null`

**Comment by skoop** [comment]
I realize it can be bull, but I don't understand why. Even an error 500 should return a response.

**Comment by mtdowling** [comment]
Comment out the call to get the response and take a look at the exception being thrown. What is the message and stack trace?

**Comment by mtdowling** [comment]
Is this issue ok to close or do you have more info?

**Comment by mtdowling** [comment]
Closing. Let me know if you have more info.
