### ISSUE TITLE
API information

### ISSUE THREAD

**Issue by Ninir** [guzzle/guzzle#1049]
Hey guys,

I'm working on a projet (well, a mailer) which allows to use one of many HTTP Clients (Buzz, Guzzle, etc). A "Adapter" design pattern is used for this.
Guzzle3 is well handled and the Guzzle Http adapter is being implemented (so version 4+, the composer version chosen is 5.2).

I have this interface for all of my adapters:

```php
/**
 * @param string $endpoint
 * @param string $content
 * @param array $headers
 * @param array $files
 * @return mixed
 */
function send($endpoint, $content, array $headers = array(), array $files = array());
```

Since the `$content` can be a string (built with http_build_query or json_encoded), I don't have any special field related.
Moreover, It is possible to add attachments.

The Guzzle v3 was defined as is:

```php
public function send($endpoint, $content, array $headers = array(), array $files = array())
{
    $request = $this->client->createRequest(RequestInterface::POST, $endpoint, $headers, $content, array('exceptions' => false));
    if ($files && $request instanceof EntityEnclosingRequestInterface) {
        $request->addPostFiles($files);
    }
    $response = $request->send();

    // Do something with the answer
}
```

As of Guzzle v4, the body must be of `StreamInterface`. As I need to add files (the 4th parameter), the body has to be of `PostBody`, in order to call the `addFile` method. Am I still right?

I thought about using `PostBody`, but my `$content` variabke is a string that may not be attached to a given field... Am i missing something?

Thanks for your help

**Comment by mtdowling** [comment]
> As of Guzzle v4, the body must be of StreamInterface. As I need to add files (the 4th parameter), the body has to be of PostBody, in order to call the addFile method. Am I still right?

Yes, but don't do that.

Just build the body of the request based on the provided arguments. If you only get `$content` then set the body of the request using just the `$content`. If you are given `$content` and `$files` then set the body of the request to a https://github.com/guzzle/guzzle/blob/master/src/Post/PostBody.php.

Based on your current example, I'm not sure that they `$content` parameter is even used if you provide `$files`. Perhaps you should be parsing the `$content` variable into an array and adding it to the PostBody.

**Comment by Ninir** [comment]
@mtdowling Thanks for your time.

Sorry for being a bit naive on this but... how is it even possible to use the PostBody, add files and set a content which is json_encoded for instance?

It may not be in the pipe... or maybe I'm trying to do something really odd?
