### ISSUE TITLE
Option to disable encoding of path

### ISSUE THREAD

**Issue by gunnarlium** [guzzle/guzzle#1051]
I'm using Guzzle to send purge requests to Varnish. In order to play nice with Varnish, I need to request this kind of url: `http://12.23.34.56/resource\?id=1`. The problem is that Guzzle encodes the backslash, meaning the wrong resource will be purged.

The only way I found to override this behavior was to replace the entire Url class, and use `$request->setUrl()` with my custom url implementation.

Is there a better way to achieve this?

**Comment by mtdowling** [comment]
A backslash is not a valid character in the path of a URI: https://tools.ietf.org/html/rfc3986#appendix-A

Even if Guzzle did not encode this character, I think more recent versions of cURL would. I suggest updating your VCL to not rely on backslahses or to percent-decode a percent-encoded "\".
