### ISSUE TITLE
Cannot add specific header to a particular field in multipart body requests

### ISSUE THREAD

**Issue by jreinke** [guzzle/guzzle#1052]
Hi there,

I am trying to upload files through PostFile object which works great but I also need to specify a field with application/json content type in the same request and this is not possible AFAIK.

Here is a sample request:
```
--554b1c2290206
Content-Disposition: form-data; name="id"

1234
--554b1c2290206
Content-Type: application/json                      <= WHAT I NEED TO SEND
Content-Disposition: form-data; name="json_field"

{"foo":[{"key1":"value1","key2":"value2"}]}
--554b1c2290206
Content-Type: application/octet-stream
Content-Disposition: form-data; name="files"; filename="sample.txt"

File contents
--554b1c2290206--
```

FYI, I am stuck because of `getFieldString()` method not handling any specific header here:  https://github.com/guzzle/guzzle/blob/master/src/Post/MultipartBody.php#L52

Thanks for any suggestion/fix and keep up the good work!

**Comment by mtdowling** [comment]
You can create a MultipartBody directly and supply a PostFile instance that has your custom headers.

See:
- https://github.com/guzzle/guzzle/blob/master/src/Post/MultipartBody.php#L27
- https://github.com/guzzle/guzzle/blob/master/src/Post/PostFile.php#L22

**Comment by jreinke** [comment]
I am not talking about the header of the file itself but about the header of another specific field that is part of the global request. The header I want to specify is on the `json_field` field and not on the `files` one.

**Comment by mtdowling** [comment]
Yeah, you're going to have to send the `json_field` parameter as a file in the MultipartBody so that you can provide a content-type.

**Comment by jreinke** [comment]
It works indeed but it seems to be a workaround rather than a real feature implementation. This field is not a file and sending a filename does not really make sense...
BTW, thanks for the tip.

**Comment by mtdowling** [comment]
Agreed. I think this workaround will have to do for now. The next version will have much better support for this. I thought about backporting the changes that are being made in the PSR-7 compatible v6, but I'm not sure it can be done in a way that makes sense.

Fyi: http://guzzle.readthedocs.org/en/v6/request-options.html#multipart
