### ISSUE TITLE
Guzzle POST 404 not found - Works in Curl and Postman

### ISSUE THREAD

**Issue by panelo** [guzzle/guzzle#1053]
Hi, i'm currently having this problem with regards to POST. It works well on curl and postman but not on guzzle. I'm using laravel. Not sure if i'm doing it right.

Here's my controller

    use GuzzleHttp\Client;

    public function postForm(Request $request)
    {
        $client = new Client(); 
        $response = $client->post('http://api.company.com/v1/members',
             array(
                 'body' => array(
                     'firstname' => $firstname,
                     'middlename' => $middlename,
                     'lastname' => $lastname,
                     'locationID' => $locationID,
                     'phonetypeID' => $phonetypeID,
                     'phone' => $phone,
                     'emailtypeID' => $emailtypeID,
                     'email' => $email,
                     'sourceID' => $sourceID,
                     'typeID' => $typeID
                 )
             )
         );
         $body = $response->send();
         $content = view('member.create_result')->with('member',json_decode($body, TRUE));
         return Admin::view($content, 'Member Added');
    }

and this is the error i'm getting

     Client error response [url] http://api.company.com/v1/members [status code] 404 [reason phrase] Not Found

here's what I get with getResponse

    Response {#345 ▼
      -reasonPhrase: "Not Found"
      -statusCode: 404
      -effectiveUrl: "http://api.company.com/v1/members"
      -headers: array:10 [▶]
      -headerNames: array:10 [▶]
      -body: Stream {#346 ▶}
      -protocolVersion: "1.1"
    }

and this one from getRequest - method is GET instead of POST and body is null?

    Request {#338 ▼
      -url: Url {#342 ▶}
      -method: "GET"
      -transferOptions: Collection {#340 ▶}
      -headers: array:3 [▶]
      -headerNames: array:3 [▶]
      -body: null
      -protocolVersion: "1.1"
      -emitter: Emitter {#337 ▶}
    }

**Comment by panelo** [comment]
Please ignore, turns out my problem is just a simple case of trailing slash (/). I was actually posting it as http://api.company.com/v1/members/ instead of just http://api.company.com/v1/members

**Comment by DannyFeliz** [comment]
I had the same error but in my case the problem was that I was making the GET request without the http protocol I mean something like this  [api.company.com/v1/members](api.company.com/v1/members)  instead of http://api.company.com/v1/members
