### ISSUE TITLE
Infos about Segmentation Fault

### ISSUE THREAD

**Issue by caBBAlainB** [guzzle/guzzle#1054]
Hello,
I'd like your idea on an issue which is certainly not caused by guzzle but I try to find experimented users who could point me on a potential reason.

I use the https://github.com/sitra-tourisme/sitra-api-php/ API which relies on GuzzleHttp.
I write my website with cakePHP 3.0 and I **successfully** implemented it in a controller as a webservice.
Now, I want to use it in php-cli so I wrote the same code in a shell.

The test code is the following one::

	use Cake\Console\Shell;
        use \Sitra\ApiClient;

        class SitraShell extends Shell
	{
		public function main()
		{
			$client = new \Sitra\ApiClient\Client([ ... ]); // no prblem here the array contains good datas.
			$exportFiles = $client->getExportFiles([
						'url' => "http://export.......zip"
					]);
	// I get a Segmentation Fault caused by the call to $client->getHttpClient() line 154 of \Sitra\ApiClient\Client.php
	    }
        ...
     }

The concerned API code is https://github.com/sitra-tourisme/sitra-api-php/blob/master/src/Sitra/ApiClient/Client.php

As you can see, the first line in getExportFiles() is $this->getHttpClient() ans as you may know, the only thing getHttpClient() do is return $this->client! https://github.com/guzzle/command/blob/master/src/AbstractClient.php

So, thanks to these few informations, can anyone guess what could happen here. Maybe a problem in the Sitra's constructor??

I'm running the shell on php 5.4.37.

Regards,
Alain

**Comment by mtdowling** [comment]
Maybe try updating PHP? You could also try using http://phpdbg.com/ to step through the code.

If you can provide a Guzzle specific issue, then please do let me know through a GitHub issue. However, I think this question is better suited for StackOverflow or the Guzzle forums: https://groups.google.com/forum/#!forum/guzzle
