### ISSUE TITLE
empty user

### ISSUE THREAD

**Issue by narmiel** [guzzle/guzzle#1057]
if we have empty-string user (yep its strange and rare situation, but its possible) then setAuth will not work, because:

Request.php (307)  method setAuth:

        // If we got false or null, disable authentication
        if (!$user) {

Example site where empty user and password http://www.cdsinfo.ru/

so it forsed to do something like:
->setHeader('Authorization', 'Basic ' . base64_encode(':'));

perhaps will better use if ($user === null)  condition?

**Comment by kamilsk** [comment]
where, which version? I can't find
> Request.php (307) method setAuth

on "guzzlehttp/guzzle": "~5.0" (https://github.com/guzzle/guzzle/blob/master/src/Message/Request.php)

**Comment by mtdowling** [comment]
Yeah, this issue is related to Guzzle 3. You can open an issue on the Guzzle 3 repo, but Guzzle 3 is now end of life: https://github.com/guzzle/guzzle3
