### ISSUE TITLE
Headers missing -> Set-Cookie header missing

### ISSUE THREAD

**Issue by isomis** [guzzle/guzzle#1058]
In Curl this is working:

// login and get the cookie section
$ch = curl_init();
curl_setopt($ch, CURLOPT_URL,$url);
curl_setopt($ch, CURLOPT_POSTFIELDS, "username=test&secretkey=test");
curl_setopt($ch, CURLOPT_HTTPHEADER, array('Content-Type: application/x-www-form-urlencoded'));
curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
curl_setopt($ch, CURLOPT_HEADER, 1);
$server_output = curl_exec ($ch);

// get the header size
$header_size = curl_getinfo($ch, CURLINFO_HEADER_SIZE);
$header      = substr($server_output, 0, $header_size);

print_r($header);exit;

We get all the headers back we needed. But in Ghuzzle we dont get all the headers:

		$user = array(
	  'username' => 'test',
	  'secretkey' => 'test'
	);
   	$client = new GuzzleHttp\Client();
    $response = $client->post($url,array(
            'body'   => $user
        )
    );

print_r($response->getHeaders());exit;

In postman the headers we are missing are the headers under the tab "cookies". I think ghuzzle dont process this cookies in headers. How can i retrieve them?

**Comment by kamilsk** [comment]
```php
$cookieJar = new ArrayCookieJar();
$cookiePlugin = new CookiePlugin($cookieJar);
$httpClient->addSubscriber($cookiePlugin);
```
"Guzzle automagically gets the Cookies set from the response and adds them to our client"

http://guzzle.readthedocs.org/en/latest/quickstart.html?highlight=cookie#cookies
http://www.pixelite.co.nz/article/guzzle-http-post-authentication-and-form-submission-symfony-20/

**Comment by kamilsk** [comment]
`Headers missing -> Set-Cookie header missing`, I think it is more correct

**Comment by isomis** [comment]
@kamilsk addSubscriber is not part of guzzle anymore?

**Comment by kamilsk** [comment]
Maybe I'm wrong
```php
$client = new \GuzzleHttp\Client();
$emitter = $client->getEmitter();
$cookieJar = new \GuzzleHttp\Cookie\CookieJar();
$subscriber = new \GuzzleHttp\Subscriber\Cookie($cookieJar);
$emitter->attach($subscriber);
```

More details: http://guzzle.readthedocs.org/en/latest/events.html

**Comment by isomis** [comment]
thnx @kamilsk.

I tried but i think i'am doing something wrong:

	$user = array(
	  'username' => 'matthijs',
	  'secretkey' => 'matthijs'
	);
   	$client = new GuzzleHttp\Client();

	$emitter = $client->getEmitter();
	$cookieJar = new \GuzzleHttp\Cookie\CookieJar();
	$subscriber = new \GuzzleHttp\Subscriber\Cookie($cookieJar);
	$emitter->attach($subscriber);

    $response = $client->post($url,array(
      		'cookies' => true,
            'body'   => $user,
            'headers' => ['Content-Type' => 'application/x-www-form-urlencoded']
        )
    );

	print_r($response->getHeaders());exit;

**Comment by kamilsk** [comment]
all cookies in CookieJar: see how works \GuzzleHttp\Cookie\CookieJar::extractCookies, \GuzzleHttp\Cookie\CookieJar::toArray

**Comment by isomis** [comment]
@kamilsk  I tried but get a empty array:

	$user = array(
	  'username' => 'matthijs',
	  'secretkey' => 'matthijs'
	);
   	$client = new GuzzleHttp\Client();

	$emitter = $client->getEmitter();
	$cookieJar = new \GuzzleHttp\Cookie\CookieJar();
	$subscriber = new \GuzzleHttp\Subscriber\Cookie($cookieJar);
	$emitter->attach($subscriber);

    $response = $client->post($url,array(
      		'cookies' => $cookieJar,
            'body'   => $user,
            'headers' => ['Content-Type' => 'application/x-www-form-urlencoded']
        )
    );


	print_r($cookieJar->toArray());exit;

**Comment by kamilsk** [comment]
I give up! :) @mtdowling, can you help?

**Comment by isomis** [comment]
@kamilsk this tutorial seems to be the solution: http://www.pixelite.co.nz/article/guzzle-http-post-authentication-and-form-submission-symfony-20/

But its not working anymore with new guzzle version.

**Comment by kamilsk** [comment]
@isomis, `$response->getHeaderAsArray('Set-Cookie')` is empty?

**Comment by isomis** [comment]
This gives curl:



HTTP/1.1 200 OK
Date: Fri, 15 May 2015 11:18:18 GMT
Set-Cookie: APSCOOKIE_9536802507013306922="Era%3D1%26Payload%3DGBKCtGfmzz13FQj4pAH2ZTcI+oA+iLoI2fI1J6TcoqiMA+pgBEN9pssNpk0oEQOW%0ANHqJq5zV3cLsqW9fO4bIJgpiGZIcPn2EOX4qB36bnEnp7WNpeeu8vxHczVQcZYdJ%0ABHD1GmWBk5p6iOcAfQyCqDGpLA5oeKXUyvg4eJNgGghPO60NcsXlAremnPJBBPFR%0AgY84POVH%2F22EWombBxLRAXdSygiDHTcwPefcHfprl5A%3D%0A%26AuthHash%3DvhsU69GlSx2AGKCk+Hw6BZY92%2FQA%0A"; path=/; HttpOnly
Set-Cookie: ccsrftoken="85C9147F75DF79AE624C411772B8B90"; path=/
Set-cookie: opmode=;expires=Thu, 01 Jan 1970 00:00:01 GMT;path=/
Set-cookie: rl=;expires=Thu, 01 Jan 1970 00:00:01 GMT;path=/
Set-cookie: vmeval=;expires=Thu, 01 Jan 1970 00:00:01 GMT;path=/
Transfer-Encoding: chunked
Content-Type: text/html; charset=utf-8
X-Frame-Options: SAMEORIGIN
X-UA-Compatible: IE=Edge

with this: 

// login and get the cookie section
$ch = curl_init();
curl_setopt($ch, CURLOPT_URL,"http://5.255.69.212:10440/logincheck");
curl_setopt($ch, CURLOPT_POSTFIELDS, "username=api1test&secretkey=api101!");
curl_setopt($ch, CURLOPT_HTTPHEADER, array('Content-Type: application/x-www-form-urlencoded'));
curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
curl_setopt($ch, CURLOPT_HEADER, 1);
$server_output = curl_exec ($ch);

// get the header size
$header_size = curl_getinfo($ch, CURLINFO_HEADER_SIZE);
$header      = substr($server_output, 0, $header_size);

print_r($header);exit;

With guzzle and the correct login i get this with 2 headers less:

Array
(
    [Date] => Array
        (
            [0] => Fri, 15 May 2015 11:19:34 GMT
        )

    [Set-cookie] => Array
        (
            [0] => opmode=;expires=Thu, 01 Jan 1970 00:00:01 GMT;path=/
            [1] => rl=;expires=Thu, 01 Jan 1970 00:00:01 GMT;path=/
            [2] => vmeval=;expires=Thu, 01 Jan 1970 00:00:01 GMT;path=/
        )

    [Transfer-Encoding] => Array
        (
            [0] => chunked
        )

    [Content-Type] => Array
        (
            [0] => text/html; charset=utf-8
        )

    [X-Frame-Options] => Array
        (
            [0] => SAMEORIGIN
        )

    [X-UA-Compatible] => Array
        (
            [0] => IE=Edge
        )

)

**Comment by kamilsk** [comment]
```php
use GuzzleHttp\Cookie\SetCookie;

$cookie = SetCookie::fromString('APSCOOKIE_9536802507013306922="Era%3D1%26Payload%3DGBKCtGfmzz13FQj4pAH2ZTcI+oA+iLoI2fI1J6TcoqiMA+pgBEN9pssNpk0oEQOW%0ANHqJq5zV3cLsqW9fO4bIJgpiGZIcPn2EOX4qB36bnEnp7WNpeeu8vxHczVQcZYdJ%0ABHD1GmWBk5p6iOcAfQyCqDGpLA5oeKXUyvg4eJNgGghPO60NcsXlAremnPJBBPFR%0AgY84POVH%2F22EWombBxLRAXdSygiDHTcwPefcHfprl5A%3D%0A%26AuthHash%3DvhsU69GlSx2AGKCk+Hw6BZY92%2FQA%0A"; path=/; HttpOnly');
var_dump($cookie->toArray());

$cookie = SetCookie::fromString('ccsrftoken="85C9147F75DF79AE624C411772B8B90"; path=/');
var_dump($cookie->toArray());
```
works correctly

The only difference is `Set-Cookie` and `Set-cookie`, but I don't think this is the reason.

**Comment by isomis** [comment]
@kamilsk i don't set the cookies, i get this Set-Cookie and Set-cookie after a post request with curl. But in guzzle i getting it not. Login is correct, because with wrong login data you don't get anything.

**Comment by kamilsk** [comment]
@isomis, I understand that this is from the response. I meant that maybe Guzzle processed only Set-cookie and ignored Set-Cookie from behind the register.

**Comment by isomis** [comment]
@kamilsk I already was thinking that. If he makes a array with key names, then there gonna be a problem. So i think you are correct. 

But in older guzzle version you had something like getRawHeaders().  That will be great, because this API sucks with lowercase and uppercase duplicated keys.

**Comment by isomis** [comment]
In messageFactory.php i print the headers:

    public function createResponse(
        $statusCode,
        array $headers = [],
        $body = null,
        array $options = []
    ) {
        if (null !== $body) {
            $body = Stream::factory($body);
        }
     print_r($headers);exit;
        return new Response($statusCode, $headers, $body, $options);
    }

The result is with all the headers:

Array
(
    [Date] => Array
        (
            [0] => Fri, 15 May 2015 12:10:03 GMT
        )

    [Set-Cookie] => Array
        (
            [0] => APSCOOKIE_9536802507013306922="Era%3D1%26Payload%3DSnKmrHH91zQm0pj1HJYLpSnDhFiIHx5y0LlKWvIRmVY%2FMc40LxBL5QWV5FcckrPg%0AV2R5UiDmxJiqYaNVMy7X8JstpmKB6oe0754VY6N5AC91PU3kGnJwV%2FqULrRqc2JX%0AA9DZYkp0K7lqen5IMzcqheK0a7UebIjamb1bcpo81Vlmdhl7uOx70jvFbIs9tXi4%0A84cHNpjxbFgP4900Se2z3g+lnCsi1U8EfaStOlgNDY5Pe2IOLORF3g%3D%3D%0A%26AuthHash%3DHKI%2FUub2UVuyi739IdhZgAG2pk0A%0A"; path=/; HttpOnly
            [1] => ccsrftoken="F9953BDE238B14F43262F1C952DE592"; path=/
        )

    [Set-cookie] => Array
        (
            [0] => opmode=;expires=Thu, 01 Jan 1970 00:00:01 GMT;path=/
            [1] => rl=;expires=Thu, 01 Jan 1970 00:00:01 GMT;path=/
            [2] => vmeval=;expires=Thu, 01 Jan 1970 00:00:01 GMT;path=/
        )

    [Transfer-Encoding] => Array
        (
            [0] => chunked
        )

    [Content-Type] => Array
        (
            [0] => text/html; charset=utf-8
        )

    [X-Frame-Options] => Array
        (
            [0] => SAMEORIGIN
        )

    [X-UA-Compatible] => Array
        (
            [0] => IE=Edge
        )

)

**Comment by mtdowling** [comment]
Looks like there's a bug with dealing with case sensitivity and headers when creating messages.

```php
<?php
require 'vendor/autoload.php';

$request = new GuzzleHttp\Message\Request('GET', '/', [
    'Set-Cookie' => 'foo=bar, baz=bam',
    'Set-cookie' => 'hi=there'
]);

$request->addHeader('Set-COOKIE', 'testing=123');
var_dump($request->getHeader('Set-cookie'));
```

Outputs:

```
string(21) "hi=there, testing=123"
```

After the request is created, case insensitivity works as expected. It's just in the request creation that this is broken.

**Comment by isomis** [comment]
@mtdowling its how you look at it, the api is broken. You dont send same keys with lowercase and uppercase. But it will be nice, if we can fix this.

**Comment by mtdowling** [comment]
There's nothing broken or crappy about the API. It's simply a bug in the message constructor.

**Comment by isomis** [comment]
@mtdowling How can we fix it? Is there something i can do on my side?

**Comment by kamilsk** [comment]
@mtdowling ?

**Comment by mtdowling** [comment]
There's a bug somewhere in the ctor of a message related to how request headers are set on the message. Probably related to this: https://github.com/guzzle/guzzle/blob/master/src/Message/Request.php#L53

**Comment by isomis** [comment]
I think its no bug, php can not handle this kind of arrays. A solutions is putting the values in a inside array with [].

So you get 

"set-cook" => array(key1 => $value1 , key2, value2)
