### ISSUE TITLE
$response->getBody() returns null

### ISSUE THREAD

**Issue by sterichards** [guzzle/guzzle#1060]
require 'guzzle.phar';

$client = new Guzzle\Http\Client();

$request = $client->createRequest("POST", "http://192.168.33.99/app_dev.php/avnetibm/files");

$postBody = $request->getBody();

var_dump($postBody); exit(); // NULL

Not sure why it's returning NULL

**Comment by kamilsk** [comment]
Because http://guzzle.readthedocs.org/en/latest/quickstart.html#make-a-request
```php
$request = $client->createRequest('GET', 'http://www.foo.com');
$response = $client->send($request);
```

**Comment by kamilsk** [comment]
And the title does not match content of issue:
`$response->getBody()` -> `$request->getBody()`

**Comment by mtdowling** [comment]
Responses also don't always have a body (e.g., HEAD requests).
