### ISSUE TITLE
Uploading large images is timing out

### ISSUE THREAD

**Issue by mikeklein13** [guzzle/guzzle#1061]
Hello,

I'm not sure if this is a bug with guzzle or my environment.

When I upload large images it hangs at a certain number of bytes every time.

More details can be found here http://stackoverflow.com/questions/30332441/cant-seem-to-upload-large-files-with-php-guzzle

Thanks

**Comment by mtdowling** [comment]
Can you set `debug` to true when sending the request? If that doesn't reveal anything, then perhaps take a look at a tcpdump of the transfer.

**Comment by kamilsk** [comment]
@mikeklein13 ping
