### ISSUE TITLE
Consider removing the global re-decleration check in functions.php [V6]

### ISSUE THREAD

**Issue by frankdejonge** [guzzle/guzzle#1063]
As somebody who's dealt with this on a framework level, I can strongly suggest to remove the global overwrite checks from the functions file. If people want to use an altered version, they should be able to define that without conflicting with the one defined by guzzle. Especially with the "use function" syntax php provides this solve a non-problem imo.

In it's current state this global function check can lead to unexpected side-effects. Consider the following scenario:

A project uses guzzle, but also __latest fab lib X__. Both expose the `uri_template` function, but with a different response. Both functions.php files are loaded automatically, then the user then "use function"'s the guzzle function it actually won't use that but fall back to __latest fab lib X__'s function. This will cause confusion. Especially considering __latest fab lib X__ might be included in the project at a later time. This can then potentially break existing functionality, leaving the dev clueless of what caused this.

Ref: https://github.com/guzzle/guzzle/blob/guzzle-v6/src/functions.php#L19

**Comment by jeremeamia** [comment]
The purpose for this is an optimization to take advantage to the [uri_template PECL extension](https://pecl.php.net/package/uri_template), if it is present.

**Comment by mtdowling** [comment]
We aren't redeclaring `uri_template` -- this function is namespaced so it causes no issue. We're simply adding a progressive enhancement that will use the C extension if installed, otherwise use the PHP userland implementation.

**Comment by kamilsk** [comment]
@mtdowling, perhaps this refers to the following case:
```php
// inside function.php of "latest fab lib X"
function uri_template() { return 1; }
```
User try to call Guzzle uri_template
```php
echo \GuzzleHttp\uri_template(...args); // will output 1
```
Maybe it is better to use `extension_loaded`?

**Comment by kamilsk** [comment]
@frankdejonge, am I right?

**Comment by frankdejonge** [comment]
@jeremeamia @mtdowling in that case, wouldn't it be safer/better to use the `extension_loaded` function? It seems you're implicitly checking it now, while explicitly seems better.

**Comment by frankdejonge** [comment]
@kamilsk that's correct.

**Comment by mtdowling** [comment]
> in that case, wouldn't it be safer/better to use the extension_loaded function?

sure

**Comment by kamilsk** [comment]
@mtdowling, @frankdejonge, done by https://github.com/guzzle/guzzle/pull/1070, but not tested yet

**Comment by mtdowling** [comment]
Thanks @kamilsk
