### ISSUE TITLE
Stable packages contain useless files: too big packages

### ISSUE THREAD

**Issue by laurentj** [guzzle/guzzle#1064]
When installing a stable version of the guzzle package with Composer, we have all files of the repository. However, when using a stable version, we don't need build/, we don't need test/, and we don't need docs/ since you have a beautiful website for that.

Please add a .gitattributes file at the root of the repository, and so Composer will not install useless files (for stable releases). It will save bytes & band-width for the download and disk space: the package size would reduce by 62% (1,1MB to 420 KB)

```
.gitattributes export-ignore
.gitignore export-ignore
build/* export-ignore
docs/* export-ignore
tests/*  export-ignore
Makefile export-ignore
phpunit.xml.dist export-ignore
.travis export-ignore
.editorconfig export-ignore
```

**Comment by virgofx** [comment]
+1

**Comment by mtdowling** [comment]
Sounds good. Can you send a PR?

**Comment by kamilsk** [comment]
@mtdowling, done (https://github.com/guzzle/guzzle/pull/1067)
@laurentj, thanks!

**Comment by mtdowling** [comment]
Thanks!

**Comment by Aliance** [comment]
Also that about `LICENSE` & `README.md` files? Do they need to be ignored too?

**Comment by sagikazarmark** [comment]
No, LICENSE must travel with the package and I think README is also a good idea to include as it tells you what that package is.

**Comment by Aliance** [comment]
> LICENSE must travel with the package

May be, but do you have any proofs?

> I think README is also a good idea to include as it tells you what that package is

Documentation does the same, but it excludes. I don't think that someone requires a package he didn't know and wishes to open the README.

**Comment by sagikazarmark** [comment]
> May be, but do you have any proofs?

Yes: law.

**Comment by lichunqiang** [comment]
Hi @sagikazarmark ,

Now, empty folder will be download, so, i suggest change this lines 

https://github.com/guzzle/guzzle/blob/master/.gitattributes#L1-L3

to

```
/build          export-ignore
/docs          export-ignore
/tests          export-ignore
```

**Comment by Aliance** [comment]
@lichunqiang also done in https://github.com/guzzle/guzzle/pull/1649
But still waiting for a review :(
