### ISSUE TITLE
Better v5 Branch Name

### ISSUE THREAD

**Issue by GrahamCampbell** [guzzle/guzzle#1073]
Better to name the `v5` branch `5.3`, then you don't need a branch alias for it.

**Comment by mtdowling** [comment]
But I don't want to keep making new branch for minor versions (e.g., 5.4, 5.5, etc)

**Comment by GrahamCampbell** [comment]
No, because `5` is the same as `v5`. Also, I don't see any issues with you just renaming the branch if you want to do a 5.4 release?

**Comment by mtdowling** [comment]
Ok. I'm open to it then. So I just remove the alias from the composer.json in the master branch?

**Comment by mtdowling** [comment]
I added a "5.3" branch and removed the branch alias from the master branch's composer.json. Look good?

**Comment by GrahamCampbell** [comment]
Yeh, looks good. :+1:

**Comment by mtdowling** [comment]
Cool thanks
