### ISSUE TITLE
Invalid response Content-Encoding and Content-Length headers when the body is decoded

### ISSUE THREAD

**Issue by ajgarlag** [guzzle/guzzle#1075]
If the `decode_content` option is set, and the upstream response body is decoded, the `Content-Length` header of the returned response must be fixed.

**Comment by mtdowling** [comment]
Why does it need to change?

You can use the `$response->getBody()->getSize()` to get the actual number of bytes you have available. The `Content-Length` header is the actual Content-Length header received over the wire.

**Comment by ajgarlag** [comment]
I'm writing a simple PSR-7 proxy script that listens for the user request, forwards the received request to the upstream server with guzzle, and returns the guzzle response to the client.

In this scenario, the guzzle response must be valid to be successfully rendered by the user-agent, so when the body content is decoded, I think that at least `Content-Length` and `Content-Encoding` must be fixed.

**Comment by mtdowling** [comment]
Can you provide some data as to what other popular HTTP clients do with regards to updating or removing the Content-Length header when the body is decoded?

**Comment by ajgarlag** [comment]
I've found this two middleware examples. Their mission is not to decode the upstream response, but to compress the downstream body, but the idea is the same. If a middleware modifies the body encoding or length, it is responsible for fixing the response headers to avoid returning an invalid response.

* [Django](https://github.com/django/django/blob/master/django/middleware/gzip.py#L30): Gzip Middleware
* [Compression](https://github.com/expressjs/compression/blob/master/index.js#L193): Node.js compression middleware.

**Comment by mtdowling** [comment]
Your PR has been merged. Thanks!
