### ISSUE TITLE
Guzzle 5 documentation

### ISSUE THREAD

**Issue by hasIan** [guzzle/guzzle#1080]
I'm trying to reference Guzzle 5 documentation, which we use in production, but the ReadTheDocs site has changed entirely, and changing the little version thing in the corner has no observable effect (e.g., it still claims that new-to-Guzzle6-PSR7 is the HTTP message interface). Links into the site now take me to dead pages. If there's a way to access the still-very-relevant Guzzle 5 docs, please help me find it, because it's not very obvious.

**Comment by hasIan** [comment]
Update: I've discovered that I can `make docs` after installing the sphinx documentation tool, so that should satisfy my immediate needs. But having the docs for previous major versions easily able to be referenced at the main site seems important enough to warrant this issue. Everyone who isn't using the release that debuted today now faces the challenge of locating or producing appropriate documentation.

**Comment by mtdowling** [comment]
The v5 docs are now built at http://guzzle.readthedocs.org/en/5.3/

I've updated the version guidance section of the readme to link to all of the versions and docs: https://github.com/guzzle/guzzle#version-guidance
