### ISSUE TITLE
[v6] Query string not build correctly

### ISSUE THREAD

**Issue by BostjanOb** [guzzle/guzzle#1082]
Hi

There seems to be bug in "applyOption" in Client class.
When you submit more query parameters they are not concatenated correctly.

I wrote simpl unit test which fails:
``` php
public function testQueryCanBeArrayMoreValues() {
        $mock = new MockHandler([new Response()]);
        $client = new Client(['handler' => $mock]);
        $request = new Request('PUT', 'http://foo.com');
        $client->send($request, ['query' => ['foo' => 'bar', 'john' => 'doe']]);
        $this->assertEquals('foo=bar&john=doe', $mock->getLastRequest()->getUri()->getQuery());
    }
```
Fail report:
``` bash
-'foo=bar&john=doe'
+'foo=barjohn=doe'
```

I found that problem is in "http_build_query" call (line: 339) which pass null as 3rd parameter. If you pass null then separator is ''.
One solution is to use ```ini_get('arg_separator.output')```

**Comment by mtdowling** [comment]
Doh. Thanks for the report. Fixed in https://github.com/guzzle/guzzle/commit/6f3db1618ef286e993db255b7a734f5cadb1f1a8
