### ISSUE TITLE
API docs error on POST fields param name

### ISSUE THREAD

**Issue by aurmil** [guzzle/guzzle#1084]
http://guzzle.readthedocs.org/en/latest/quickstart.html#sending-form-fields

```php
$response = $client->post('http://httpbin.org/post', [
    'form_fields' => [
        ...
    ]
]);
```

correct entry name is **form_params**, according to tests:
https://github.com/guzzle/guzzle/blob/master/tests/ClientTest.php#L382

**Comment by jeremeamia** [comment]
Fixed by #1085
