### ISSUE TITLE
Restore v4 docs on readthedocs

### ISSUE THREAD

**Issue by SergeyTsalkov** [guzzle/guzzle#1086]
I'm still using v4 in a project, and it'd be a pain to upgrade right now. Since those docs are no longer on the documentation site, I'm having to use archive.org to read them. Could you restore them please?

**Comment by kamilsk** [comment]
You can switch to tag 4.* (e.g. https://github.com/guzzle/guzzle/tree/4.2.3) and get the docs from the appropriate directory (e.g. https://github.com/guzzle/guzzle/tree/4.2.3/docs)

**Comment by SergeyTsalkov** [comment]
Oh, I didn't realize github would actually format the *.rst files!
