### ISSUE TITLE
[question] how can I get total, connection time et redirect count from guzzle

### ISSUE THREAD

**Issue by omansour** [guzzle/guzzle#1091]
typically CURLINFO_TOTAL_TIME, CURLINFO_CONNECT_TIME and CURLINFO_REDIRECT_COUNT ? 

thanks for all and thanks for the great lib !

**Comment by mtdowling** [comment]
I don't want to subclass ResponseInterface to add any new methods, but I was considering add a callback for handler specific context information, but haven't spec'd anything out yet.

I was thinking it would be a new request option that you provide a callback to and the callback is invoked with an associative array of custom transfer information (like this cURL stuff).

**Comment by omansour** [comment]
hey @mtdowling 

nice to read you, great fan of your work.

Having the infos in the response object will be easier for the user to deal with. But the callback option will work I guess, hydrating a sort of parameters bag with the cURL options in the keys. Sadly, I cant see in the new guzzle where this can be implemented.

**Comment by mtdowling** [comment]
One other reason why I like a callback more is that sending a single request using the client's send method could in fact trigger multiple HTTP requests to be sent (e.g., redirects, cache validations, etc.). By using a callback, you can receive all of the stats for each request and does not require consumers to rely on a specific concrete implementation of ResponseInterface that adds custom methods.

**Comment by puckbag** [comment]
I'm building an uptime tool and want to record connection and response times. Extending the CurlFactory and attaching the info to the response object worked for me. My first experience with Guzzle...very nice!

```php
<?php

require __DIR__ . '/vendor/autoload.php';

use GuzzleHttp\Client;
use GuzzleHttp\HandlerStack;
use GuzzleHttp\Handler\CurlFactory;
use GuzzleHttp\Handler\CurlHandler;
use GuzzleHttp\Handler\EasyHandle;

class MyCurlFactory extends CurlFactory {
    public function release(EasyHandle $easy)
    {
        if ($easy->response)
        {
            $easy->response->curl_info = curl_getinfo($easy->handle);
        }
        return parent::release($easy);
    }
}

$handler = new CurlHandler([
    'handle_factory' => new MyCurlFactory(3),
]);
$stack = HandlerStack::create($handler);
$client = new Client(['handler' => $stack]);

$res = $client->get('https://www.example.com/');
print_r($res->curl_info);
```

Here's a more complete example using a custom choose_handler for Multi as well:
https://gist.github.com/puckbag/c49f0cbe19574942dd17

**Comment by mtdowling** [comment]
@puckbag Nice work!

**Comment by omansour** [comment]
@puckbag excellent :) so nothing to do in guzzle itself regarding this specific need !

**Comment by mickgeek** [comment]
@puckbag :+1:

**Comment by dume2007** [comment]
You can use Event System. this is a example:
```php
$mySubscriber = new MySubscriber();
$HttpClient = new \GuzzleHttp\Client;
$HttpClient->getEmitter()->attach($mySubscriber);
$result = $HttpClient->get('http://www.github.com/');
$result = $result->getStatusCode();
```

AND MySubscriber Class:
```php
use GuzzleHttp\Event\EmitterInterface;
use GuzzleHttp\Event\SubscriberInterface;
use GuzzleHttp\Event\BeforeEvent;
use GuzzleHttp\Event\CompleteEvent;

class MySubscriber implements SubscriberInterface
{
    public function getEvents()
    {
        return [
            // Provide name and optional priority
            'before'   => ['onBefore', 100],
            'complete' => ['onComplete'],
            // You can pass a list of listeners with different priorities
            //'error'    => [['beforeError', 'first'], ['afterError', 'last']]
        ];
    }

    public function onBefore(BeforeEvent $event, $name)
    {
        $event->getRequest()->addHeaders(['sign'=>'xxx']);
    }

    public function onComplete(CompleteEvent $event, $name)
    {
        $curl_info = $event->getTransferInfo();
        print_r($curl_info);
    }
}
```

docs link: http://docs.guzzlephp.org/en/5.3/events.html#

**Comment by sagikazarmark** [comment]
Nice, worth noting that this is for Guzzle 5.x
