### ISSUE TITLE
Possible to drop minimum requirement in Guzzle 6 to PHP 5.4?

### ISSUE THREAD

**Issue by webchick** [guzzle/guzzle#1092]
Hi there, coming at you from Drupal 8! :)

Given the support for PSR-7, and your statement about not planning another major version (https://twitter.com/mtdowling/status/603415290802614272), we'd really love to ship Guzzle 6 in Drupal 8.0.0. In part because of Guzzle 6's PHP 5.5 requirement, we are having a big discussion at https://www.drupal.org/node/2296557 about whether not to require PHP 5.5 as a minimum in Drupal 8.0.0.

While we definitely are planning to require PHP 5.5 at some point during Drupal 8's release cycle, I'm concerned that the landscape at http://w3techs.com/technologies/details/pl-php/5/all shows PHP 5.5 at only 9.2% usage, and so this requirement could severely hamper Drupal 8's adoption, at least in the short term. Unlike developer-centric tools such as Symfony, ZF, and Guzzle, the majority of Drupal's target audience are site builders and other non-developers who are much more beholden to whatever PHP version their host provides by default.

Is there any chance of Guzzle 6 adding some wrapper functions or similar to allow it to be used with PHP 5.4 as well?

**Comment by GrahamCampbell** [comment]
:-1: from me

**Comment by GrahamCampbell** [comment]
I thought the entire point of guzzle 5 was to accommodate drupal 8?

**Comment by webchick** [comment]
Hm. I can't really speak to that. Only that this request is not really D8-specific. It's more about wide-scale adoption of Guzzle on web hosts, only 9.2% of which it looks like are running PHP 5.5. :)

**Comment by GrahamCampbell** [comment]
> It's more about wide-scale adoption of Guzzle on web hosts, only 9.2% of which it looks like are running PHP 5.5. :)

Well, they'll have to upgrade. It's about time. And guzzle isn't really targeting the bottom end anyway, I don't think?

**Comment by mtdowling** [comment]
I think it's technically possible, but would require some work.

1. This would need to be refactored: https://github.com/guzzle/guzzle/blob/29afd334ba7617dfe6bba30dc2fda25471365138/src/Pool.php#L57
2. This function is fine to have in a PHP 5.4 app, but the tests for this would need to be refactored into a separate test runner or filter: https://github.com/guzzle/promises/blob/master/src/functions.php#L478

> While we definitely are planning to require PHP 5.5 at some point during Drupal 8's release cycle

Do you have an estimate on Drupal's timeline for PHP 5.5 adoption? Have you seen this: http://php.net/supported-versions.php

**Comment by webchick** [comment]
Yep, we're definitely aware of http://php.net/supported-versions.php, and the EOL of 5.4 in September was the main onus for this discussion.

As far as when we'd make the switch, I can't really say atm because it's still under very active discussion. This fact-finding is part of that discussion.

On the *very* conservative side, it could be as late as May 2017 when Symfony 3 LTS version ships. However, I would certainly hope that host PHP 5.5 adoption has vastly increased well in advance of then, and we'd probably move once PHP 5.5 usage hit 30%+ or something. (Though with 41.6% still on PHP 5.3 which was EOLed almost a year ago, that might be giving hosts a bit too much credit. :\)

Also not sure that it's fair to say that all of these are "bottom end" hosts. For example, research in the Drupal 8 issue states that Ubuntu 12.04 LTS ships with PHP 5.3 and will be supported until 2017.

**Comment by mtdowling** [comment]
Please keep me posted on any updates as to whether or not Drupal is hard set on PHP 5.4, and if you can get an estimate on 5.5 support if 5.4 is out for now. If Drupal *must* support 5.4, then pull requests from the Drupal community to make Guzzle 5.4 compatible would be awesome :)

**Comment by Mech7** [comment]
Could you add the php constraint in composer.json then atleast you get a message when it's not supported :)

**Comment by GrahamCampbell** [comment]
?

**Comment by AndyWendt** [comment]
:-1: 5.4 is going to lose security support mid september.  See [PHP supported versions](http://php.net/supported-versions.php)

**Comment by GrahamCampbell** [comment]
I totally agree with @AndyWendt.

**Comment by dawehner** [comment]
I agree in a nice world, we could use PHP 5.5, this is true. On the other hand the Drupal project has hosting environment requirements, even we argue hard to move to 5.5

@mtdowling 
Do if someone steps up and changes those bits,how likely would you accept it?

**Comment by GrahamCampbell** [comment]
Guzzle 5 still supports php 5.4 and will be maintained for a good amount of time.

**Comment by dawehner** [comment]
Sure, but we, as the Drupal project, want to support the new version of
Drupal for quite a long time, let's say 6 years for example.
I guess there is no way beside follow guzzle along

**Comment by GrahamCampbell** [comment]
Guzzle 6 won't be supported that long either. I think both guzzle 5 and 6 have the same support time?

**Comment by AndyWendt** [comment]
Large projects like Drupal and Wordpress have been fairly bad about slow PHP upgrades in the past.  They need to move off of 5.4 in the best interest of their users.  Who wants to stick around on an unsupported version of PHP that is **not even getting security fixes**? 

That's insane.

**Comment by Crell** [comment]
@AndyWendt I can't speak for Wordpress, but that's an open topic of conversation in Drupal right now: https://www.drupal.org/node/2296557. Several of us are pushing for 5.5 but it's not universal.

As for it being "insane", it's actually the standard for the vast majority of PHP projects and always has been.  Hosts *do not upgrade*.  We've been fighting that problem for a decade.  Remember GoPHP5?  The mass boycott of PHP 4 that forced hosts to finally upgrade, 3 years after PHP 5 came out?  This chicken-and-egg war is not new, and the overwhelming majority of PHP projects support out-dated PHP versions.  Note we're talking here about 5.5... which is already the legacy version.  PHP 5.6 is barely a statistical blip.

I would dearly love to be relying on 5.6 right now and PHP 7 in 10 months. Ain't gonna happen, though.

**Comment by AndyWendt** [comment]
@Crell  Poor choice of words on my part :smile:.  I know it is difficult for most organizations to upgrade quickly.  I tend to be an idealist but reality comes and smacks me upside the head often, as in this case.

**Comment by dawehner** [comment]
> It is my opinion that Drupal's major version release cycle is too long and out of sync with modern fast iterating techniques.

Yeah I think we really want to release, I mean REALLLLLY and then switch to a more fluent semantic version style with minor release flow

**Comment by mtdowling** [comment]
I'm not a big fan of lowering to PHP 5.4, but I'm willing to do so if Drupal will not make their minimum version 5.5. That said, there are a couple things in Guzzle and the promises library that need work to lower the version constraint: https://github.com/guzzle/guzzle/issues/1092#issuecomment-106587123

**Comment by dawehner** [comment]
Drupal is going with 5.5 now, so feel free to close this issue

**Comment by AndyWendt** [comment]
That's awesome for Drupal!

**Comment by GrahamCampbell** [comment]
:+1: :rocket: :ship:

**Comment by EAnushan** [comment]
Awesome Drupal! Excellent choice.

**Comment by mtdowling** [comment]
Awesome!

**Comment by benjy** [comment]
We were all hoping for 5.5, great result! But thanks @mtdowling for being so accommodating to Drupal!
