### ISSUE TITLE
multipart form request with PUT

### ISSUE THREAD

**Issue by warroyo** [guzzle/guzzle#1093]
Is there a way to do a multi part form  request using the PUT method?  I cannot find a way in the docs and it does not seem to be making the proper request.

**Comment by mtdowling** [comment]
Sure. Just send a PUT request and use the `multipart` request option.

```php
$client->put('/', [
    'multipart' => [
        [
            'name'     => 'foo',
            'contents' => 'data',
            'headers'  => ['X-Baz' => 'bar']
        ],
        [
            'name'     => 'baz',
            'contents' => fopen('/path/to/file', 'r')
        ],
        [
            'name'     => 'qux',
            'contents' => fopen('/path/to/file', 'r'),
            'filename' => 'custom_filename.txt'
        ],
    ]
]);
```

**Comment by warroyo** [comment]
thank you. I think I may be using an older version, I am getting the following error.
```No method can handle the multipart config key```

also is there a way to dump the request body to be sure it is formatting properly?

**Comment by mtdowling** [comment]
Ah yes, that's an older version. For v5, you'll need to manually create a MultipartBody: https://github.com/guzzle/guzzle/blob/5.3/src/Post/MultipartBody.php

**Comment by warroyo** [comment]
will this method still work with PUT requests?

**Comment by mtdowling** [comment]
Yes. Just use the `body` request option and pass in a MultipartBody stream.
