### ISSUE TITLE
React promise error inside ringphp for Guzzle 5

### ISSUE THREAD

**Issue by maknz** [guzzle/guzzle#1099]
I'm the maintainer of [maknz/slack](https://github.com/maknz/slack), we use Guzzle 4 or 5 internally to make a basic HTTP POST request with a JSON body.

A user reported an issue today with an exception being thrown when this call is being executed.

```
Catchable fatal error: Argument 1 passed to React\Promise\Promise::__construct() must be callable, null given, called in /home/yakir/slack-app/vendor/react/promise/src/Deferred.php on line 25 and defined in /home/yakir/slack-app/vendor/react/promise/src/Promise.php on line 16
```

A brief look over the [full trace](https://gist.github.com/KingYes/979c7889795b191e7807) makes it seem to come from RingPHP.

The user is using `Guzzle/5.3.0 curl/7.19.7 PHP/5.4.37`.

The userland call to Guzzle is darn simple, located at https://github.com/maknz/slack/blob/master/src/Client.php#L351

```php
  public function sendMessage(Message $message)
  {
    $payload = $this->preparePayload($message);
    $encoded = json_encode($payload, JSON_UNESCAPED_UNICODE);
    $this->guzzle->post($this->endpoint, ['body' => $encoded]);
  }
```

and according to the trace, the URL and data seem to be properly getting into the Guzzle request.

The user has indicated that Guzzle 4 works fine, but anything above 5.0.0 does not. I haven't had any other complaints, so I'm fairly certain this is something environmental with the user. They are using the package inside Wordpress, and they are running PHP 5.4, I would have thought neither of those factors would matter. Is this kind of error something that has been seen before?

**Comment by mtdowling** [comment]
I've never seen this before. Are you able to reproduce this?

> A brief look over the full trace makes it seem to come from RingPHP.

The trace is *enormous*. Can you link to the line that makes you think it's RingPHP? Is there any chance to get an exception stack trace rather than a debug backtrace?

**Comment by maknz** [comment]
Sorry, I had thought I'd linked to a relevant line. Here's what made me assume the trouble involves RingPHP. https://gist.github.com/KingYes/979c7889795b191e7807#file-ll-log-L94

I can't reproduce it unfortunately :( My initial reaction was that there could be some kind of environment thing (it's being used inside Wordpress by the looks). The package gets several hundred installs per day, and most will get pushed to Guzzle 5, and nobody has complained.

If that log isn't useful, I'll go back to the user and attempt to get a proper stack trace.

**Comment by maknz** [comment]
Fairly happy to close this as it's not something I've been able to reproduce, nor seems like it would be easy to.

**Comment by hornetalcala** [comment]
I had this same problem, but finally I solved myself. The problem is the eccelerator php module.

Adding this line at the beginning of the script, it is solved.

ini_set('eaccelerator.enable', 0);
