### ISSUE TITLE
Missing request factory function

### ISSUE THREAD

**Issue by shadowhand** [guzzle/guzzle#1100]
I would really like a way to create an instance of `RequestInterface` using the form:

```php
$request = $guzzle->request($method, $uri, $options);
```

Right now this call will create a request __and__ send it. I want all the functionality of the current `request` without the sending part, so that I can later do:

```php
$response = $guzzle->send($request);
```

This is exacerbated by the fact that `GuzzleHttp\Psr7\modify_request` does not have the same functionality as `GuzzleHttp\Client::applyOptions`, which does several more transformations (eg: converting `form_params` to `body`) than just calling `modify_request`.

**Comment by GrahamCampbell** [comment]
I don't think this can happen given we're implementing psr7, so all the other methods were removed, like "json" went from the response interface.

**Comment by mtdowling** [comment]
Can you describe your use case? Is using the middleware system not sufficient here?

You can't really prepare a request for sending using options and then expect to be able to send a prepared request later without the same options. This is because not all options modify the request itself, but rather just let other middlewares know what configuration to use when sending the request. There are only a few built-in options that modify the HTTP request (e.g., body, headers, query). Many other options modify the behavior of how a request is sent rather than what request is sent.

> This is exacerbated by the fact that GuzzleHttp\Psr7\modify_request does not have the same functionality as GuzzleHttp\Client::applyOptions

Yeah, `modify_request` is just about PSR-7 messages whereas sending a request with a client is about transferring a PSR-7 request with Guzzle specific options.

I'm not very keen on adding a "request factory" or anything like that simply because a request can be modified in various ways based on the middlewares associated with a client's handler. If you need the request that is being sent, then you can add a middleware to the handler your client uses and get a reference to the request. For example, the `tap` middleware can do this.

Alternatively, you can create a helper function that sends a request using a mock handler. You can then get the request that would have been sent by calling `getLastRequest` on the mock handler.

Something like this should work.

```php
use GuzzleHttp\Handler\MockHandler;
use GuzzleHttp\Psr7\Response;
$mock = new MockHandler();
$mock->append(new Response(200));
$options['handler'] = $mock;
$client->request($method, $uri, $options);
$request = $mock->getLastRequest();
```

**Comment by shadowhand** [comment]
@mtdowling the use case is quite simple and follows what used to be possible with Guzzle:

```php
$request = $guzzle->getRequest($method, $url, $options);
// apply custom headers, or conditional changes
// the important part is that i can type hint against Psr\Http\Message\RequestInterface in these methods
$response = $guzzle->send($request);
```

What this code allows for is agnostic type hinting against PSR-7 interfaces, without having to implicitly use the Guzzle PSR-7 implementation. Everything in between the first and last step can be hinted against the PSR interfaces. The explicit dependency against Guzzle is kept within a single layer and can be swapped or upgraded later without much trouble.

As it stands right now, a person can work around these limitations, but there is significant convenience being lost:

1. no way to apply `form_params` without juggling the headers/body manually
2. no way to apply `query` without several calls to modify the URI
3. no way to apply `headers` without manually applying them directly
4. etc

**Comment by shadowhand** [comment]
@mtdowling as for using middleware, that makes the Guzzle dependency more explicit and does not allow for the flexibility I desire.

**Comment by mtdowling** [comment]
You're not really abstracting Guzzle though if you still use `form_params`, `query`,` headers`, etc as request options to create a request (those aren't part of PSR-7) and then exposing that to your end users.

If you wanna just send a request with Guzzle, then just create a PSR-7 request object and use the client's send() method without any request options. This allows you to use whatever process you want to build up a request, and then give it to Guzzle to send it as-is.

> // apply custom headers, or conditional changes
> // the important part is that i can type hint against Psr\Http\Message\RequestInterface in these methods

Your use case is exactly what Guzzle middleware is meant to solve. More on that below.

> What this code allows for is agnostic type hinting against PSR-7 interfaces, without having to implicitly use the Guzzle PSR-7 implementation. Everything in between the first and last step can be hinted against the PSR interfaces.

Note: You do not need to pass in Guzzle PSR-7 classes to anything -- everything works directly on the PSR-7 interfaces.

You can use any PSR-7 functions you'd like with the Guzzle middleware system by adapting the function to a middleware. For example, you can use any function that accepts a PSR-7 request and returns a PSR-7 request. You would then just need to wrap that function in a middleware function and add it to your client's handler. Take a look at the `mapRequest()` middleware: https://github.com/guzzle/guzzle/blob/master/src/Middleware.php#L228.

Can you provide a real example of why you cannot adapt what you're doing to use the middleware system? I don't want to expose these internal details of Guzzle unless there's a really good reason. If there is a good reason, then I would be willing to take a pull request, but it would need to be very clear about what options it supports.

**Comment by shadowhand** [comment]
> You're not really abstracting Guzzle though if you still use form_params, query,headers, etc as request options to create a request (those aren't part of PSR-7) and then exposing that to your end users.

We don't necessarily want to expose `$options` to the end user, we want to use `$options` internally within our single layer (class) as a helper to create the request, then give the request to the user to modify. And then there is a second entry point that takes a request (whether or not we created it) and passes it along to Guzzle to send.

> Your use case is exactly what Guzzle middleware is meant to solve. More on that below.

Using middleware is not possible within our workflow, without exposing an explicit dependency on Guzzle, which is exactly what we want to avoid.

> I don't want to expose these internal details of Guzzle unless there's a really good reason.

That's exactly why I created this issue... right now we have to "emulate" a lot of Guzzle to achieve the same functionality that request factory would solve. In effect, Guzzle's attempt to limit the interface is causing a leaky abstraction.

> Can you provide a real example of why you cannot adapt what you're doing to use the middleware system?

Sure thing. :) See the PR I just referenced.

**Comment by mtdowling** [comment]
I haven't really gotten a technical reason why you need this change. I'm wondering if there's a way I can help you to adapt your code to use the middleware system without needing to expose it externally. Can you tell me why specifically you cannot use the middleware system? Is there a link to the code you're integrating with?

**Comment by shadowhand** [comment]
@mtdowling see thephpleague/oauth2-client#315 that I just linked and commented on. :)

**Comment by shadowhand** [comment]
@mtdowling I think part of the misunderstanding comes from a thinking of Guzzle as an end-user library, rather than a dependency of other libraries. In the case of oauth2-client, what we want is:

- a simple way to get a `RequestInterface` instance
- a simple way to get an _authenticated_ `RequestInterface` instance
- a simple way to send those `RequestInterface` instances

While also having the ability to switch to a completely different HTTP client that also uses PSR-7.

**Comment by rtheunissen** [comment]
> (In the case of the authenticated request, we could use middleware.)

I don't think we can (thephpleague/oauth2-client), because we are allowing `setHttpClient`, and we can't push middleware to an instantiated client.

**Comment by rtheunissen** [comment]
Close?

**Comment by rtheunissen** [comment]
I think this issue can be closed as it was determined a wontfix in the PR discussion.
