### ISSUE TITLE
[6.0.1] Handler stack documentation

### ISSUE THREAD

**Issue by bmancone** [guzzle/guzzle#1102]
In the latest documention of `Handlers and Middleware`, the way to retrieve the handler stack is :

`$stack = $client->getHandlerStack();`

However, the method `getHandlerStack()` does not exist.

**Comment by eXtreme** [comment]
I think there should be a `$client->getConfig('handler')` call but.. will always `handler` be a "HandlerStack" instance? By default yes, but you can pass any callable s a client handler so you can't rely on that.

And of course in this doc these calls are on "client" object which is created later so I think it should be fixed just to `$stack = HandlerStack::create()`;

**Comment by bmancone** [comment]
Yes, the way to retrieve the stack is to call `getConfig('handler')`. 

Replacing `$stack = $client->getHandlerStack();` by `$stack = new \GuzzleHttp\HandlerStack();` in the doc should improve comprehension, thanks.
