### ISSUE TITLE
CURLOPT_PROTOCOLS is not supported by hhvm

### ISSUE THREAD

**Issue by stuartcarnie** [guzzle/guzzle#1107]
Guzzle 6.x
Requests fail when running via hhvm 3.8-dev due to its lack of support for this option.

**Comment by stuartcarnie** [comment]
Turns out, support for this [just landed](https://github.com/facebook/hhvm/commit/08a404b55eada5a8b6a7acbaaed6a1032be88e5e)

**Comment by mtdowling** [comment]
Cool. So this can be closed then?

**Comment by stuartcarnie** [comment]
Indeed @mtdowling – confirmed it works with the latest 3.8-dev nightly
