### ISSUE TITLE
Better support for crawling and dynamic pooling

### ISSUE THREAD

**Issue by storeman** [guzzle/guzzle#1108]
I want to create some kind of crawler with a dynamic pool size. It all starts with a single url, which is analyzed and more urls become available... Well, you get the point of crawling.

For this I use a generator function. Sometimes, the generator is unable to fill all the places in the pool and it returns null. On null, the pool decides the generator has ended and won't look for new urls anymore.

I've created a very dirty hack, which is working:
```
$urls = \ArrayObject(['http://test']);
$maxPoolSize = 8;
$self = $this;
$urlGenerator = function () use ($urls, $maxPoolSize, $self) {
	for ($i=0; $i<count($urls); $i++) {
		if ($maxPoolSize > count($urls) - $i) {
			$size = count($urls) - $i;
			if ($size > 1) {
				$size--; // Make sure not to set the pool smaller, so not all urls will be requested
			}
                        // getEach was hacked in by me, also set concurrency
			$self->pool->getEach()->setConcurrency($size);
		} else {
                        // getEach was hacked in by me, also set concurrency
			$self->pool->getEach()->setConcurrency($maxPoolSize);
		}
			
		yield new \GuzzleHttp\Psr7\Request('GET', $urls[$i]);
		// A hack to provide a request, null would be nicer, but stops the bool
		if ($i===0 && count($urls)-$i === 1) {
			yield new \GuzzleHttp\Psr7\Request('GET', $urls[$i]);
		}
	}
};

$this->pool = new \GuzzleHttp\Pool($client, $urlGenerator(), [
	'concurrency'=>$poolSize,
	'fulfilled' => function ($response, $index) use ($self) {
		$self->processResult($response);
	},
	'rejected' => function ($reason, $index) {
		
	}
]);

$this->pool->promise()->wait(false);

```

I have to add, the dynamic pool size should not be necessary if a null return value from a generator was accepted, but I think this is a nicer solution then returning null.

**Comment by mtdowling** [comment]
> On null, the pool decides the generator has ended and won't look for new urls anymore.

Kind of... Really the generator determines that null is not a request or callable, so it rejects the entire pool: https://github.com/guzzle/guzzle/blob/master/src/Pool.php#L58

> I have to add, the dynamic pool size should not be necessary if a null return value from a generator was accepted, but I think this is a nicer solution then returning null.

Can you make a concrete suggestion on what you'd like this to do? I think it works pretty well... I imagine you could implement a crawler as follows:

1. The pool size function returns 1 on the first call because it's the entry URI.
2. The pool fills up the list of concurrent requests, gets the response, and places all the URIs to crawl into a queue. This logic could be in the 'fulfilled' method of the pool.
3. The pool size function now returns the min of your max pool size and the size of the queue (this ensures that you are never sending more requests than your maximum pool size and you are not having to try to hack around the fact that you cannot yield `null` in the generator).
4. While there are items in the queue, go to step 2.

**Comment by storeman** [comment]
I'm trying to follow you, I think the example below illustrates what you mean, but it also illustrates my problem. If there is one item in the queue and this is yielded, the pool just stops. (if you add two urls to the start array, it will keep running, which is what we want.

Working snippiet:
```
$client = new \GuzzleHttp\Client();
        
$urls = ['http://google.com/'];
$urlGenerator = function () use (&$urls) {
    for ($i=0; $i<count($urls); $i++) {
        $url = $urls[$i];
        yield new \GuzzleHttp\Psr7\Request('GET', $url);
        echo 'Yielded ' . $url . PHP_EOL;
    }
};

$pool = new \GuzzleHttp\Pool($client, $urlGenerator(), [
    'concurrency' => function () {
        return 1;
    },
    'fulfilled' => function ($response, $index) use (&$urls) {
        $urls[] = 'http://nu.nl';
        $urls[] = 'http://tweakers.net';
    },
    'rejected' => function ($reason, $index) {}
]);
$pool->promise()->wait();
```

**Comment by storeman** [comment]
I just really dug into the generators in PHP. I wasn't sure if the code above should work as i expected. I did some more experimenting and I think it should work. I created some very similar structures on the command line, and those scripts kept running. I'll now dive into Guzzle to see what I can find out.

**Comment by mtdowling** [comment]
> I found out that the fulfilled function is called later than the next value is yielded from the generator.

You're right. I've been trying to find a way to update EachPromise to work around this, but I'm still not sure how to fix this. See https://github.com/guzzle/promises/blob/master/src/EachPromise.php

Basically the calls to valid on the iterator advance the iterator before new URLs can be added.

**Comment by mtdowling** [comment]
I may have a solution actually. Here's the pull request I opened: https://github.com/guzzle/promises/pull/5

And here's some code that works with it:

```php
<?php
require 'vendor/autoload.php';

use GuzzleHttp\Client;
use GuzzleHttp\Psr7\Request;

$client = new Client(['http_errors' => false]);

$urls = ['http://mtdowling.com/start'];

$urlGenerator = function () use (&$urls) {
    while ($url = array_pop($urls)) {
        echo "Yielding: $url\n";
        yield new Request('GET', $url);
    }
    echo "Exiting...\n";
};

$remaining = 20;

$pool = new \GuzzleHttp\Pool($client, $urlGenerator(), [
    'concurrency' => function () use (&$urls) {
        // Yield at most 3 URIs, and at minimum 1 URI.
        return max(1, min(count($urls), 3));
    },
    'fulfilled' => function ($response) use (&$urls, &$remaining) {
        // Parse the URIs and add them to the queue... Or fake it :)
        if ($remaining > 0) {
            $urls[] = 'http://mtdowling.com/' . $remaining--;
            $urls[] = 'http://mtdowling.com/' . $remaining--;
            $urls[] = 'http://mtdowling.com/' . $remaining--;
        }
    },
    'rejected' => function ($reason, $index) {
        echo "Error: {$reason}\n\n";
    }
]);

$pool->promise()->wait();
```

**Comment by mtdowling** [comment]
https://github.com/guzzle/promises/pull/5 was merged. Can you try this out and let me know if this solves your use case?

**Comment by storeman** [comment]
Great. This indeed solved my issue. Great work!

**Comment by mtdowling** [comment]
Awesome. I'll close this and get a release of the promises library tagged soon.
