### ISSUE TITLE
why changed so much,doesn't have detailed api change list?

### ISSUE THREAD

**Issue by argb** [guzzle/guzzle#1109]
$response = $client->post('http://httpbin.org/post', [
    'body' => [
        'field_name' => 'abc',
        'other_field' => '123'
    ]
]);

why can't post an array?

where is form_fields ?

why changed so much,but there is no detailed change log of api?

if I use guzzle put data to server,how can I get it ,$_GET,$_POST,$_REQUEST all don't work,what should I do and why?

**Comment by GrahamCampbell** [comment]
Body can't be an array anymore. Look at the docs.

**Comment by argb** [comment]
@GrahamCampbell why? It's convenient.

**Comment by GrahamCampbell** [comment]
@argb I don't know. I didn't do it. I'm just telling you why this isn't an issue.

**Comment by argb** [comment]
@GrahamCampbell Thank you haha good man!

**Comment by mtdowling** [comment]
Sending POST requests with an array as the body parameter has been removed. Using the body parameter to support both `application/x-www-form-urlencoded` and `multipart/form-data` resulted in a confusing API that did not support sending multipart/form-data requests that did not contain files, you had to specify the POST file name twice, and other issues. You should now use `form_params` and `multipart`.

This is in the upgrading guide here: https://github.com/guzzle/guzzle/blob/master/UPGRADING.md#post-requests

> if I use guzzle put data to server,how can I get it ,$_GET,$_POST,$_REQUEST all don't work,what should I do and why?

I think this question is better suited for stackoverflow.

**Comment by argb** [comment]
@mtdowling Thank you very much!
