### ISSUE TITLE
[Guzzle 6] The mock handler doesn’t cause an exception to be thrown for a 500 response

### ISSUE THREAD

**Issue by jonnybarnes** [guzzle/guzzle#1112]
Trying to write a unit test for a job in Laravel and this is the relevant code:
```
/**
 * @expectedException GuzzleHttp\Exception\ServerException
 */
public function testSendNotificationsFailure()
{
    $mock = new MockHandler([
        new Response(500, ['Content-Length' => 0])
    ]);
    $handler = HandlerStack::create($mock);
    $client = new Client(['handler' => $mock]);

    $job = new App\Jobs\SendTopicUpdateNotification($this->topicUrl, $this->callbackUrl, $client);
    $job->handle();
}
```
Am I missing something?

**Comment by mtdowling** [comment]
You need to change this line:

`$client = new Client(['handler' => $mock]);`

to

`$client = new Client(['handler' => $handler]);`

I just pushed a commit that makes creating a mock handler with the default list of middleware easier. So using dev-master, you can now do this:

```php
<?php
require 'vendor/autoload.php';

use GuzzleHttp\Handler\MockHandler;
use GuzzleHttp\Psr7\Response;
use GuzzleHttp\Client;

$mock = MockHandler::createWithMiddleware([
    new Response(500, ['Content-Length' => 0])
]);
$client = new Client(['handler' => $mock]);
$client->get('http://foo.com:1234')->getStatusCode();
```

**Comment by jonnybarnes** [comment]
All working now, thanks.

I thought `$client = new Client(['handler' => $mock]);` looked odd, though I copied that from http://guzzle.readthedocs.org/en/latest/testing.html#mock-handler, so maybe update the docs?

**Comment by mtdowling** [comment]
Ah, yes, that would be a good next step.
