### ISSUE TITLE
multipart and form_params together

### ISSUE THREAD

**Issue by LPMadness** [guzzle/guzzle#1113]
am trying to upload file and send post parameters at the same time like this:
```
$response = $client->post('http://example.com/api', [
    'form_params' => [
        'name' => 'Example name',
    ],
    'multipart' => [
        [
            'name'     => 'image',
            'contents' => fopen('/path/to/image', 'r')
        ]
    ]
]);
```
However my form_params fields are ignored and only the multipart fields are present in my post body. Can I send both at all with guzzle 6.0 ?

**Comment by mtdowling** [comment]
These parameters are exclusive. You should use multipart for multipart/form-data and form_params for application/x-www... Requests. You can send simple parts that are not files in the multipart option. The docs show examples of this.

**Comment by LPMadness** [comment]
I can't really do that because the other parts of my request are combination of strings and arrays, and the multipart handler throws an error because arrays are not allowed. I am currently using the query option to achieve what I want, but it is not the most elegant and nice solution.

**Comment by mtdowling** [comment]
I prefer to keep these options exclusive. Mixing these options would force us to assume how you want to serialize an array of values -- would you want to have repeated multipart parts or would you want a single part that has a content-type of application/x-www-form-urlencoded?

You'll need to take your mixed format array and create the appropriate `multipart` option value.
