### ISSUE TITLE
[v5] specificity of envato market

### ISSUE THREAD

**Issue by kamilsk** [guzzle/guzzle#1114]
Docs http://marketplace.envato.com/api/documentation
Example of response http://marketplace.envato.com/api/edge/categories:themeforest.json

Do:
```php
$client = new Client(['base_url' => 'http://marketplace.envato.com/api/edge/');
$response = $client->get('categories:themeforest.json')->json();
```
Expected:
```php
$response === [
    'categories' => [...],
]
```
Actual:
`cURL error 6: Could not resolve host: categories`

Because in `\GuzzleHttp\Url::fromString` (`parse_url`) parse `categories` as scheme.

**Comment by kamilsk** [comment]
Workaround is concatenate string:
```php
$client->get($client->getBaseUrl() . 'categories:themeforest.json')->json();
```
but it's not a very good decision.

**Comment by kamilsk** [comment]
The implementation of `parse_url` did not seem contrary to the specifications http://www.w3.org/Addressing/URL/url-spec.txt
```
php > var_dump(parse_url('false:protocol.com/and/url'));
array(2) {
  'scheme' =>
  string(5) "false"
  'path' =>
  string(20) "protocol.com/and/url"
}
```
Any idea how to get around this is a more elegant way? :)

**Comment by mtdowling** [comment]
Unless starting the relative URI with a / fixes it, then I don't see a way around this. It seems that this is just a limitation of base URLs.

**Comment by kamilsk** [comment]
Works with `urlencode`
```php
$client->get(urlencode('categories:themeforest.json'))->json();
```
Controversial, but still a compromise.
