### ISSUE TITLE
Support or plugin for JWT (Json Web Tokens)

### ISSUE THREAD

**Issue by markitosgv** [guzzle/guzzle#1120]
Hi, 

I didnt find any plugin or way to use guzzle with JWT, i mean, with renew token mechanism when JWT ttl expires. Is planned to support this in the future? or there are a simple way to do this?

thanks

**Comment by mtdowling** [comment]
Hi. Guzzle does not have any direct JWT support, but it could be done using a middleware to sign requests as needed. That said, this feature will not be added to Guzzle.
