### ISSUE TITLE
Disable path encoding

### ISSUE THREAD

**Issue by DraperStudio** [guzzle/guzzle#1121]
Hi,

I am working with an API that has round brackets () in the URL and Guzzle encodes these to %28 and %29 but the API doesn't decode these back to ( and ) which results in a 404.

Is there any way to disable path encoding in Guzzle 6?

**Comment by DraperStudio** [comment]
Would be kinda urgent I really find anything in the new documentation.

Is there even any way to prevent the encoding of the path part of a url or is this not possible because of some parts of PSR7 that force you to encode everything?

**Comment by mtdowling** [comment]
Yes, I see that these characters are being incorrectly encoded. It's a bug in the Guzzle PSR-7 package.

**Comment by mtdowling** [comment]
Fixed in https://github.com/guzzle/psr7/commit/962735c754f2a562a619b456a3aa4e614f0e5360

**Comment by DraperStudio** [comment]
Great, that fixed my issue. Thanks a lot!

Are you going to tag a release for that or should I just manually pull in dev-master like I do atm to get this fix?

**Comment by mtdowling** [comment]
There are PR's pending that will need to be reviewed and merged before the next release. I guess pull in dev-master for now.

**Comment by barryvdh** [comment]
Thanks, this also fixes my problems with LinkedIn :)
