### ISSUE TITLE
Possible wrong date format in MessageFormatter

### ISSUE THREAD

**Issue by rtheunissen** [guzzle/guzzle#1122]
In [MessageFormatter](https://github.com/guzzle/guzzle/blob/master/src/MessageFormatter.php#L111) you are using `gmdate('c')`, but the date format specified in the [Apache docs](http://httpd.apache.org/docs/2.4/logs.html#common) is defined as: 

```
[day/month/year:hour:minute:second zone]
day = 2*digit
month = 3*letter
year = 4*digit
hour = 2*digit
minute = 2*digit
second = 2*digit
zone = (`+' | `-') 4*digit
```

Was this intentional? The correct format is `gmdate("d/M/Y:H:i:s O")`, I believe.

**Comment by mtdowling** [comment]
Ah yeah, you're right. Looks like the date should be modified to match the common log format's date.
