### ISSUE TITLE
JSON POST request, docs error? 

### ISSUE THREAD

**Issue by mikeymike** [guzzle/guzzle#1123]
First off just want to say I'm completely new to Guzzle, never used any version before so this may well be  me just completely misinterpreting the docs. 

I've been trying to use Guzzle to make API calls to a application that only accepts POST requests with json content type. 

The [docs](http://guzzle.readthedocs.org/en/latest/request-options.html#json) has an example of

```php
$request = $client->createRequest('PUT', '/put', ['json' => ['foo' => 'bar']]);
echo $request->getHeader('Content-Type');
// application/json
echo $request->getBody();
// {"foo":"bar"}
```

which when I run just results in 
```
PHP Catchable fatal error: Argument 3 passed to GuzzleHttp\Client::request() must be of the type array, string given
```

Debugging through it seems there is no method `Client::createRequest` and it falls through to `__call` which does not find `Async` in the method call and passes it over to `Client::request` where the args  miss match occurs. 

I've also tried making the json request in many other methods but none of which worked as expected and the best result I got was from the following: 

```php
// For reference
$options = [
    'auth' => ['api_key' => 'xxx', 'api_secret' => 'xxx'],
    'dev' => true,
    'url' => 'http://some.url.im.passing'
];

$response = $client->post($apiEndpoint, [
                'headers' => ['Content-Type' => 'application/json'],
                'body'    => json_encode($options), 
                'debug'   => true
            ]);
```
which returned a seemingly empty `GuzzleHttp\Psr7\Stream` object

**Comment by mtdowling** [comment]
There's no createRequest method in version 6.

**Comment by mikeymike** [comment]
Thanks for the clarification, I did take this directly from the latest docs so I'm assuming the docs are out of date ? 

Could anyone update them to explain the correct method of making a json post request ? At the moment my best result is an empty stream object.

**Comment by mtdowling** [comment]
Sorry about that. The docs were off. I've pushed a [fix](https://github.com/guzzle/guzzle/commit/e812f17245f6b6678e39661fce8102101e392e6f).

> which returned a seemingly empty GuzzleHttp\Psr7\Stream object

The response is always an instance of `Psr\Http\Message\ResponseInterface`. How are you using the response object?

**Comment by rtheunissen** [comment]
@mikeymike You can use `(string) $response->getBody()`. Might be how you were using it but wanted to mention just in case.

**Comment by mtdowling** [comment]
Ah, right, @rtheunissen. That's likely the issue. Since I've pushed a fix for the docs, I'll go ahead and close. Let us know if you are still having issues.
