### ISSUE TITLE
Mocking guzzle is way too complicated

### ISSUE THREAD

**Issue by luispabon** [guzzle/guzzle#1126]
http://guzzle.readthedocs.org/en/latest/testing.html 

Although I appreciate this mock environment, it's way too verbose to set up. It really isn't necessary on most test situations and just adds noise to otherwise straightforward test cases.

There's also the fact Guzzle has code specifically geared towards unit testing. This is almost always bad practice, and a symptom of encapsulation breakdown somewhere. Using Guzzler's MockHandler means introducing an extra dependency on my tests as well as code extraneous to the unit being tested.

It doesn't help that all actual calls are done through a magic __call method.

Guzzle would be much more straightforward to mock if only it'd implement post(), get() et al as real methods rather than rely on __call. While __call being evil or not is up for discussion, it certainly has downsides on code clarity which surface on things like unit testing.

This would also help with type hinting on IDEs.

**Comment by mtdowling** [comment]
How is it too verbose?
What are you using to mock that does not allow magic methods?
Have you tried mocking send()? It's used on all blocking requests.

**Comment by luispabon** [comment]
I appreciate this, I'm just trying to find a way of mocking Guzzle in a way that tests don't need any actual knowledge of Guzzle itself by taking advantage of v6's PSR7ness. I'll see if I can do something a bit more constructive by actually going through the code. Might open a PR at some point with an RFC.

**Comment by adamkelso** [comment]
@luispabon I know this is years after you closed the issue, but if you still are looking for a nice way to work with Guzzle in tests, you might look into using [Guzzler](https://guzzler.dev). Just a thought.

**Comment by luispabon** [comment]
Thank you @adamkelso. Since then, I'm in fact using PSR-18 so not really an issue anymore
