### ISSUE TITLE
Invalid characters in cookie name

### ISSUE THREAD

**Issue by sagikazarmark** [guzzle/guzzle#1128]
According to [RFC6265](http://tools.ietf.org/search/rfc6265) cookie-name attribute is a token which is declared in [RFC2616](http://tools.ietf.org/search/rfc2616#section-2.2) which means that there is a much more wider set of characters which are invalid in the cookie name than it is [checked](https://github.com/guzzle/guzzle/blob/master/src/Cookie/SetCookie.php#L351).

I've put together a regex which matches all possible characters declared in the RFC:

`[\x00-\x20]|\x22|[\x28-\x29]|\x2c|\x2f|[\x3a-\x40]|[\x5b-\x5d]|\x7b|\x7d|\x7f`

What do you think?

**Comment by mtdowling** [comment]
Ah yeah. You're right. That looks good to me.

**Comment by sagikazarmark** [comment]
Would you like me to open a PR. FYI I am currently working on a general cookie implementation which tries to be as compatible with the RFC as possible:

https://github.com/php-http/cookie

**Comment by mtdowling** [comment]
> Would you like me to open a PR?

If you have the time, that would be awesome.

**Comment by sagikazarmark** [comment]
Done in #1131

I optimized the regex a bit: `[\x00-\x20\x22\x28-\x29\x2c\x2f\x3a-\x40\x5b-\x5d\x7b\x7d\x7f]`
