### ISSUE TITLE
Cookie path match possible RFC incompatibilities

### ISSUE THREAD

**Issue by sagikazarmark** [guzzle/guzzle#1129]
As per [RFC 6265](http://tools.ietf.org/html/rfc6265#section-5.1.4) I noticed the following incompatibilities in [path matching](https://github.com/guzzle/guzzle/blob/master/src/Cookie/SetCookie.php#L297):

1. Nothing indicates that the matching should be case-insensitive. In fact many sources suggest it is case-sensitive, even if the RFC does not say anything about this specifically. It makes perfect sense as *nix OSes are case-sensitive by default.

2. The matching part is wrong as it would give false result for the following paths:
    - Cookie path: /path/to/somewhere
    - Request path: /path/to/somewhereelse

According to the RFC it must be checked that the first character in the request path which is not in the cookie path is "/".

**Comment by mtdowling** [comment]
> In fact many sources suggest it is case-sensitive, even if the RFC does not say anything about this specifically.

Can you provide a source for that? I'm happy to change it, but I'd like to document the motivation.

> The matching part is wrong as it would give false result for the following paths:

Yep, that looks like a bug then.

**Comment by sagikazarmark** [comment]
> Can you provide a source for that?

Well, none of them can be taken as an official source. My particular opinion is that most webservers running *nix OS are case-sensitive by default.

Also, from the RFC:

> The most common form of Request-URI is that used to identify a  resource on an origin server or gateway

Hence the case-sensitivity on *nix servers same URIs with different cases point to different resources.

**Comment by mtdowling** [comment]
I think you're right. Let's make them case sensitive.

**Comment by mtdowling** [comment]
I've fixed both problems raised in this issue.
