### ISSUE TITLE
Requests made using Request object request the wrong URI

### ISSUE THREAD

**Issue by justincwatt** [guzzle/guzzle#1132]
Given the following Guzzle client, instantiated with a base URI including a path:

```php
$client = new GuzzleHttp\Client([
    'base_uri' => 'http://example.com/API/',
]);
```

These two styles of making requests, the first using a magic method and the second creating a `GuzzleHttp\Psr7\Request` object, should (I believe) request the same URI---however they do not.

```php
try {
    $response = $client->get('foobar');
} catch (Exception $e) {}
```

```php
try {
    $request = new \GuzzleHttp\Psr7\Request('GET', 'foobar');
    $response = $client->send($request);
} catch (Exception $e) {}
```

The first approach makes a request of `http://example.com/API/foobar`  (which we'd expect given the examples in the docs re: RFC 3986), while the second makes a request of `http://example.com/foobar` (note: the missing `API/` in the path). I'm guessing/hoping this divergent behavior is not expected.

The reason this is happening is that the path I'm passing into `GuzzleHttp\Psr7\Request`, in this case `foobar`, gets transformed into `/foobar` in `GuzzleHttp\Client::sendAsync()` when `$request->getUri()` gets called on line 97.

This is happening because the Request object is transforming the string URI I pass into a `GuzzleHttp\Psr7\Uri` object, and in the process, `GuzzleHttp\Psr7\Uri::filterPath()` is called, which automatically prepends the path with a slash (line 574). Now as far as why `filterPath()` needs to do this or what needs to change to fix this (without breaking something else) I don't know.

**Comment by mtdowling** [comment]
This will be fixed in the next tagged release of the PSR-7 package (planning on tagging in the next couple days). In the meantime, you could pull in the dev-master branch of the psr7 package.

**Comment by justincwatt** [comment]
:boom: Thanks.

**Comment by justincwatt** [comment]
Btw, the obvious workaround (for anyone else who might be reading) was to set the base_uri to `http://example.com/` and update my request uri to `/API/foobar` which I'll revert once the PSR-7 package is tagged.

**Comment by mtdowling** [comment]
The guzzlehttp/psr7 package has been updated and tagged with a fix.
