### ISSUE TITLE
'exceptions' request option is not documented

### ISSUE THREAD

**Issue by FractalizeR** [guzzle/guzzle#1133]
http://docs.guzzlephp.org/en/latest/quickstart.html#exceptions:

> A GuzzleHttp\Exception\ClientException is thrown for 400 level errors if the `exceptions` request option is set to true

But there is no `exceptions` option documented here: http://docs.guzzlephp.org/en/latest/request-options.html. Only `http_errors` is there.

**Comment by mtdowling** [comment]
exceptions still works but is deprecated. Where did you see it mentioned in the docs.

**Comment by FractalizeR** [comment]
Here: http://docs.guzzlephp.org/en/latest/quickstart.html#exceptions

```
A GuzzleHttp\Exception\ClientException is thrown for 400 level errors if the exceptions request option is set to true. This exception extends from GuzzleHttp\Exception\BadResponseException and GuzzleHttp\Exception\BadResponseException extends from GuzzleHttp\Exception\RequestException.
```
