### ISSUE TITLE
Issues with cokies in 6.0

### ISSUE THREAD

**Issue by nick4fake** [guzzle/guzzle#1134]
When request get 302 status, cookiejar extractCookies is called only once at last request (no intermediate requests are captured)

**Comment by nick4fake** [comment]
$stack->push(Middleware::cookies(), 'cookies');
        $stack->push(Middleware::redirect(), 'allow_redirects');

swapping these lines fixes the issue

**Comment by Briareos** [comment]
I see this is fixed in https://github.com/guzzle/guzzle/commit/6d2bab840c2e1fb0b6dd6ac9b72009c6b74ba36f, but not tagged

**Comment by mtdowling** [comment]
Yes, this is fixed and will be tagged soon.
