### ISSUE TITLE
Guzzle returning 404 on a URL that exists

### ISSUE THREAD

**Issue by sterichards** [guzzle/guzzle#1135]
I'm using Guzzle with CurlAuthPlugin to authenticate. When I run the code, I get

Client error response\ [status code] 404\ [reason phrase] Not Found\ [url] https:\/\/api.buto.tv\/v2\/video\/tag\/v2\/video\/tag\/
The code I'm using is:

$client = new Client('https://api.buto.tv');

    // Add the auth plugin to the client object
    $authPlugin = new CurlAuthPlugin(<APIKEY>, 'x');
    $client->addSubscriber($authPlugin);

    $response = $client->get('v2/video/tag/')->send();
But the URL is perfectly valid a I can paste that in to a browser and it works fine

I've also tried:

 $client = new Client('https://api.buto.tv');
    $request = $client->get('v2/video/tag/');
    $request->setAuth('user', 'pass');
    $response = $request->send();
But I get the same error. I have output the URL it's requesting with echo $request->getUrl(); and if I copy and paste the URL in to a browser, the URL is fine

**Comment by kamilsk** [comment]
> Client error response\ [status code] 404\ [reason phrase] Not Found\ [url] https:\/\/api.buto.tv\/v2\/video\/tag\/v2\/video\/tag\/

I open this url https://api.buto.tv/v2/video/tag/v2/video/tag/ and see
```json
{"status":"Not Found","message":"no video with that id found"}
```

```
Request URL:https://api.buto.tv/v2/video/tag/v2/video/tag/
Request Method:GET
Status Code:404 Not Found
```

> and if I copy and paste the URL in to a browser, the URL is fine

You pointed above https://api.buto.tv/v2/video/tag/v2/video/tag/, it's correct?

**Comment by kamilsk** [comment]
https://api.buto.tv/v2/video/tag/ the same

**Comment by sterichards** [comment]
Yes, you're right. Sorry I confused myself by thinking that because the service returned content, it wasn't a 404

**Comment by mtdowling** [comment]
I'll go ahead and close as it looks like the 404 is correct.
