### ISSUE TITLE
Guzzle removing JSON array from URL

### ISSUE THREAD

**Issue by sterichards** [guzzle/guzzle#1136]
Hi,

I'm dealing with a bit of a crazy API service and their docs state to run the following:

curl -u API_KEY:x --include https://api.buto.tv/v2/video/tag/"\{\"tags\":\[\"custom_tag_one\",\"custom_tag_two\"\]\}"

I have created the JSON array using json_encode from a PHP array and that's OK.

But when I pass that string in to Guzzles get() function, it strips the JSON array from the URL.

        $tags = json_encode(
            array(
                "tags" => array(
                    "tag1",
                    "tag2"
                )
            )
        );

        $client = new Client('https://api.buto.tv');
        $request = $client->get("v2/video/tag/".$tags);

        echo $request->getURL();

The above code returns https://api.buto.tv/v2/video/tag/

**Comment by kamilsk** [comment]
Try to use `urlencode` before, e.g. `$client->get("v2/video/tag/".urlencode($tags));`. API is really crazy :)

`$client->get("v2/video/tag/".$tags)` returns `$response`, not `$request` (compare `$request = $client->createRequest(...`)

And in this case that would return `getEffectiveUrl`?

**Comment by sterichards** [comment]
OK, urlencode() has helped but it hasn't gotten me to the finish line. Is your further responses regarding $request and $response only relating to variable names? I can't understand if you mean what I am doing is breaking the results?

I am still struggling to get the body. Adding urlencode() stopped any errors that I was receiving but $response->getBody() is returning blank.

I have ran the call within Postman and I get a response as follows:

[
"DmwPx",
"WkgzB",
"ZlhqV",
"v8RDL",
"yqGSr"
]

What could be causing this problem?

**Comment by kamilsk** [comment]
> Is your further responses regarding $request and $response only relating to variable names?
yes

**Comment by kamilsk** [comment]
> $response->getBody() is returning blank

`(string) $response->getBody()` is blank? What is the response status code? `var_dump($response->json())` prints `NULL`?

**Comment by sterichards** [comment]
var_dump($response->json()); returns:

<pre class='xdebug-var-dump' dir='ltr'>
<b>array</b> <i>(size=110)</i>
  0 <font color='#888a85'>=&gt;</font> <small>string</small> <font color='#cc0000'>'DmwPx'</font> <i>(length=5)</i>
  1 <font color='#888a85'>=&gt;</font> <small>string</small> <font color='#cc0000'>'WkgzB'</font> <i>(length=5)</i>
  2 <font color='#888a85'>=&gt;</font> <small>string</small> <font color='#cc0000'>'ZlhqV'</font> <i>(length=5)</i>

That's from the 'raw' tab in Postman so I guess that's the returned data. Strange why it's being returned as HTML. Is there a possibility that HTML isn't being returned and Guzzle is adding that?

**Comment by kamilsk** [comment]
`$response->json()` returns array (as you see), your xdebug extension wrap `var_dump` output by html tags in browser.

**Comment by kamilsk** [comment]
@sterichards, can use a reference to me in comments? This will help me to find issue that requires my response. Thx!

Like this: https://github.com/guzzle/guzzle/issues?utf8=✓&q=is%3Aissue+is%3Aclosed+kamilsk

**Comment by sterichards** [comment]
@kamilsk - I seem to be having trouble access the returned data.

I get the data with $data = `$response->json();`

If I `print_r($data)` I get blank
If I `var_dump($data);` I get `<pre class='xdebug-var-dump' dir='ltr'>
    <small>string</small>
    <font color='#cc0000'>'DmwPx'</font>
    <i>(length=5)</i>
</pre>`

If I `foreach ($data as $d) { print_r($d); }` I get blank
If I `foreach ($data as $d) { var_dump($d); }` I get `<pre class='xdebug-var-dump' dir='ltr'>
    <small>string</small>
    <font color='#cc0000'>'DmwPx'</font>
    <i>(length=5)</i>
</pre>`

I'm struggling to think how I get the data as it's returned from the web service

**Comment by kamilsk** [comment]
I see conflicting information (`$response->json()`):
```html
<pre class='xdebug-var-dump' dir='ltr'> <b>array</b> <i>(size=110)</i> 0 <font color='#888a85'>=&gt;</font> <small>string</small> <font color='#cc0000'>'DmwPx'</font> <i>(length=5)</i> 1 <font color='#888a85'>=&gt;</font> <small>string</small> <font color='#cc0000'>'WkgzB'</font> <i>(length=5)</i> 2 <font color='#888a85'>=&gt;</font> <small>string</small> <font color='#cc0000'>'ZlhqV'</font> <i>(length=5)</i>
```
-> `(array) ['DmwPx', 'WkgzB', 'ZlhqV', ... 110 elements]`

In your last example:
```html
<pre class='xdebug-var-dump' dir='ltr'> <small>string</small> <font color='#cc0000'>'DmwPx'</font> <i>(length=5)</i> </pre>
```
-> `(string) DmwPx`

The inquiry in these cases was not changed?

~~~

> If I `foreach ($data as $d) { print_r($d); }` I get blank

If data is `DmwPx`, then you get an error of level E_WARNING and see nothing.

```
php > $a = 'abc';
php > foreach ($a as $char) { print_r($char); }
PHP Warning:  Invalid argument supplied for foreach() in php shell code on line 1
```

> Do I need to run another Guzzle function after $response->json() ?

No, if the response is in json format, this function will return the deserialized value.

**Comment by sterichards** [comment]
Yes, the conflict is due to me shortening the data in my reply so it was less spam
