### ISSUE TITLE
Set default query string

### ISSUE THREAD

**Issue by websirnik** [guzzle/guzzle#1138]
In Guzzle 5 it was possible to set the default query string for the client. So every request would add the default query string to the query string provided in the request.

In Guzzle 6 I can't replicate this behaviour. With the following code, client query string get overwritten by the request query string.

```php
$client = new \GuzzleHttp\Client( [
    'base_uri' => 'http://api.example.org/',
    'query'   => ['key' => 'secretKey']
] );
$client->get( 'extract', ['query' => ['value' => 'cat']] );
```
Expected request url: `http://api.example.org/extract?key=secretKey&value=cat`
Actual  request url: `http://api.example.org/extract?value=cat`

**Comment by EAnushan** [comment]
The following should help you:
```
$handler->unshift(Middleware::mapRequest(function (RequestInterface $request) {
    return $request->withUri(Uri::withQueryValue($request->getUri(), 'key', 'secretKey'));
}));
```

**Comment by mtdowling** [comment]
Guzzle 6 does not merge default request options onto per/request options. You'll need to use something like @EAnushan awesome suggestion and create a middleware.

**Comment by Anahkiasen** [comment]
That should probably be mentioned in the UPGRADING guide, spent a good half hour trying to figure out what was wrong with what I was doing before inspecting a request and figuring it out

**Comment by Saeven** [comment]
Agreed.  Default parameters is a pretty plain concept.  That a library gets over-engineered to this point is a warning sign.  Step away from the dial! ;)

**Comment by cdekok** [comment]
Is there any particular reason this change was added? it seems a bit confusing to me i was expecting it to be merged by default to.

**Comment by davereid** [comment]
I just hit this as well, and did not see this covered in the https://github.com/guzzle/guzzle/blob/master/UPGRADING.md.
