### ISSUE TITLE
Using form_params with multipart

### ISSUE THREAD

**Issue by hussainweb** [guzzle/guzzle#1139]
It seems that we can no longer use form_params and multipart options together. I am not sure when it stopped but I am guessing that this changed in Guzzle 6. I found a [StackOverflow question](http://stackoverflow.com/q/30645996/124844) about this but no other issue, hence posting this.

There are two ways to approach this:

1. Document that they cannot be used together, if that is the case. The current documentation has no such indication.
2. Fix it so that it can work together again.

I am happy to work on this but I want to know which of the above is true.

## Background
I am trying to update minkphp/MinkGoutteDriver to use fabpot/goutte 3.0, which was upgraded to use Guzzle 6. Initially, I thought the error was with goutte but after debugging, I found the problem in Client.php at line 293, which overwrites the previous body built with form_params. This results in [test failures](https://travis-ci.org/minkphp/MinkGoutteDriver/jobs/67779664) in a file upload test in MinkGoutteDriver.

**Comment by mtdowling** [comment]
`form_params` and `multipart` cannot be used together. They both create different types of requests.

See: https://github.com/guzzle/guzzle/blob/master/src/Client.php#L286

I added a commit to document this: https://github.com/guzzle/guzzle/commit/e798cb4daa240985b33c51ca3588e36d45128036

**Comment by hussainweb** [comment]
Thanks! And great work with the exception. I was going to suggest that anyway.

Also, I wonder why not unify them and set the content type explicitly. I understand that would be a major change but I am wondering if you have considered that.

**Comment by csarrazi** [comment]
By the way, the documentation is actually wrong in the [getting started](http://guzzle.readthedocs.org/en/latest/quickstart.html#sending-form-files) page. This induced me in error when migrating Goutte to support Guzzle 6.0.

**Comment by mtdowling** [comment]
Whoops. That should be fixed.

**Comment by stof** [comment]
@mtdowling what about throwing an exception when both options are used together instead of silently ignoring one of them and spending lots of time debugging why we don't get the expected request ?

**Comment by hussainweb** [comment]
@stof, I think that is what will happen: https://github.com/guzzle/guzzle/blob/master/src/Client.php#L286

**Comment by stof** [comment]
hmm yeah. but not yet in stable versions :)
