### ISSUE TITLE
Allow modify handlers after of construction

### ISSUE THREAD

**Issue by desarrolla2** [guzzle/guzzle#1140]
In guzzle 5 i have a service to construct the client, and later depends of the environment the subscribers of onRequest and onResponse will be sets, depends of the environment.

Currently i can't the posibility to do this.

The solution could be change Client::$options property to protected or provide un Client::setOptions method.

**Comment by EAnushan** [comment]
The way I handle this is by lazy initializing the Client. Modify your options array separately. Then when you need it, initialize the Client with these options. Perhaps on the first request.

**Comment by mtdowling** [comment]
Clients are immutable after they are constructed. Modifying clients after they are constructed would need to happen at a different layer than a stock Guzzle client. This could be done with a middleware or maybe by decorating the client and lazily instantiating clients when options change and it would be necessary to create a new client.

You can get the handler associated with a client by calling `$client->getConfig('handler')`. If you check that the handler of a client is an instance of `HandlerStack`, then you can add or remove middleware from the handler stack after a client has been constructed. Keep in mind thought that some clients will use an immutable `callable` that you cannot modify.
