### ISSUE TITLE
Each value yielded by the iterator must be a Psr7\Http\Message\RequestInterface or a callable that returns a promise that fulfills with a Psr7\Message\Http\ResponseInterface object.

### ISSUE THREAD

**Issue by worp1900** [guzzle/guzzle#1142]
Hey guys,

I am creating two
`GuzzleHttp\Psr7\Response` objects

by calling
`guzzleClient->get('http://google.com');`

and save them in an array
`$guzzleRequests`

Then I send the array to be batch processed by GuzzleHttp\Pool:
`$results = Pool::batch($client, $guzzleRequests);`

Upon arrival in the Pool __constructor, the requests get analyzed:
```php
        $iterable = \GuzzleHttp\Promise\iter_for($requests);
        $requests = function () use ($iterable, $client, $opts) {
            foreach ($iterable as $rfn) {
                if ($rfn instanceof RequestInterface) {
                    yield $client->sendAsync($rfn, $opts);
                } elseif (is_callable($rfn)) {
                    yield $rfn($opts);
                } else {
                    throw new \InvalidArgumentException('Each value yielded by '
                        . 'the iterator must be a Psr7\Http\Message\RequestInterface '
                        . 'or a callable that returns a promise that fulfills '
                        . 'with a Psr7\Message\Http\ResponseInterface object.');
                }
            }
        };
```

When arriving at 
` if ($rfn instanceof RequestInterface) `
the invalid argument exception is thrown.

What am I doing wrong here? What should I have done with the responses before sending them to the pool?

**Comment by Briareos** [comment]
`Clinet::get` call is synchronous and it returns a `ResponseInterface`; just switch it to `Client::getAsync` and you will get a promise that resolves to a `ResponseInterface`.

**Comment by mtdowling** [comment]
@Briareos is right: you need to yield requests, promises, or functions. You're yielding responses, which triggers the InvalidArgumentException.
