### ISSUE TITLE
How to add authentication to GuzzleHTTP Request Objects for asynchronous processing

### ISSUE THREAD

**Issue by worp1900** [guzzle/guzzle#1145]
I am trying to create a GuzzleHttp\Psr7\Request with Basic HTTP authentication to query an API asynchronously utilizing a Pool.

Detailed:
http://stackoverflow.com/questions/31052003/how-to-add-authentication-to-guzzlehttp-request-objects-for-asynchronous-process

Is it even possible and what is the syntax for it? Sadly the only authentication topics covered by the documentation are only utilizing Client::get().

**Comment by mtdowling** [comment]
Use the `auth` request option or the `headers` request option. See http://docs.guzzlephp.org/en/latest/request-options.html#auth and http://docs.guzzlephp.org/en/latest/request-options.html#headers
