### ISSUE TITLE
$response in the example on the main page is not a string 

### ISSUE THREAD

**Issue by dbirchak** [guzzle/guzzle#1149]
It appears the $response in the example on the main page is not a string 

should it be 
$promise = $client->sendAsync($request)->then(function ($response) {
    echo $response->getBody();
    //or
    echo $response->getStatusCode().PHP_EOL;
});

**Comment by kamilsk** [comment]
+1
`PHP Catchable fatal error:  Object of class GuzzleHttp\Psr7\Response could not be converted to string in`
@mtdowling, how about `__toString` method?

**Comment by mtdowling** [comment]
Yeah, I think we should change the example to not cast the response to a string.
