### ISSUE TITLE
Cannot get connection time in middleware

### ISSUE THREAD

**Issue by pinkeen** [guzzle/guzzle#1152]
In previous versions it was easy to get the (curl) connection time via `$event->getTransferInfo()`.
In guzzle6 I can't find a good way to do this. It seems that this information is not even stored anywhere.

I am aware that including this additional information would break the elegance and purity of the code so I can live without it. But maybe I am missing sth and it would be possible to pass this information so it's accessible in a handler?

I am using guzzle with a [Symfony2] (https://github.com/pinkeen/ApiDebugBundle) bundle which simplifies API debugging  in a few projects. Having the connection time really helps with identifying network problems and slow API endpoints/calls.

**Comment by mtdowling** [comment]
This was also requested in https://github.com/guzzle/guzzle/issues/1091#issuecomment-106631626. I would love for there to be a new request option that accepts a callback and invokes the callback with transfer information. Maybe the request option is called "on_transfer_info" and it invokes a callback with a request, response, and array of HTTP handler specific transfer data (non-normalized across backends).

**Comment by Benoth** [comment]
+1 on this, that would be great !

**Comment by funivan** [comment]
:+1:
