### ISSUE TITLE
Problems with Guzzle and Composer

### ISSUE THREAD

**Issue by patrickse** [guzzle/guzzle#1158]
Hi,

I am trying to install guzzle 6.0.1 with composer. My servers are running php 5.5.10 and so the requirements should be fulfilled. But composer is giving me this message, when I try to install guzzle.

```bash
$ php composer.phar update --no-dev
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for guzzlehttp/guzzle 6.0.1 -> satisfiable by guzzleh                                                                                                                                ttp/guzzle[6.0.1].
    - guzzlehttp/guzzle 6.0.1 requires php >=5.5.0 -> your PHP version (5.5.10)                                                                                                                                 does not satisfy that requirement.

```

Have you seen this before? It looks like it detects my php version and it´s higher then the needed one...

**Comment by patrickse** [comment]
Tried the same procedure with php 5.5.9 on ubuntu 14.04.2 lts.

**Comment by kamilsk** [comment]
Hi! What shows `php -v` in cli on server?
In any case, I would recommend you to contact directly with the issue in the repository of the [Composer](https://github.com/composer/composer).

**Comment by GrahamCampbell** [comment]
Yeh, this isn't a bug with guzzle.

**Comment by patrickse** [comment]
Ok.. thanks guys. 

Btw: 

```
$ php -v
PHP 5.5.10 (cli) (built: Mar  5 2014 14:49:07)
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2014 Zend Technologies
```

**Comment by patrickse** [comment]
I´ll close this issue and the further discussion will be in 

composer/composer#4211
