### ISSUE TITLE
Guzzle6 Cookies not set during redirect cycle

### ISSUE THREAD

**Issue by yort** [guzzle/guzzle#1159]
Hi Guys,

Spent the last few hours trying to work out why a redirect (Location header) which sets some cookies are not being recorded and transferred to and from the CookieJar through a request cycle (POST to a page, then get redirected a few times and end up on a final page expecting the cookies set through the redirects to be present)

Turns out the fix is a simple changing in the ordering of how the Middleware is setup in HandlerStack.php's create() method.

Instead of having the following ...

```php
$stack->push(Middleware::cookies(), 'cookies');
$stack->push(Middleware::redirect(), 'allow_redirects');
```

They should be ...

```php
$stack->push(Middleware::redirect(), 'allow_redirects');
$stack->push(Middleware::cookies(), 'cookies');
```

I'm still trying to work out the technical reason why this change in ordering has such an effect, but I am still learning the lib so cant shed any light at present.

Anyway, thought I would let you guys know in case the lib should be changed or if someone else runs into the same issue and needs a fix.

Thanks
Troy/YorT

**Comment by mtdowling** [comment]
This is fixed in master and will be in the next release
