### ISSUE TITLE
Guzzle6 Extend response objects with additional methods

### ISSUE THREAD

**Issue by yort** [guzzle/guzzle#1160]
Hi Guys,

Not sure where to post this, but how would one go about adding additional methods to the response object or return another object which could be used to do this with?

I have been playing around with middleware to see if that would do the job but have not been successful, the other route I thought of was using the Handlers, but that does not seem to be the correct way either.

Looking through the AWS SDK code, I think it does something similar, but I seem to have hit my limit of my understanding on the new way Guzzle works.

Thanks
Troy/YorT

**Comment by mtdowling** [comment]
The way this is handled in the AWS SDK is that we actually use a Guzzle client inside of the SDK and do not extend from the Guzzle client. We only use the async methods and instead use the promise system to transform a response object into an AWS result object.

You could achieve what you want in a similar way, or you could use a middleware that you ensure is executed last in the stack when returning a response.

You might find more interactive help from other Guzzle users on the Gitter channel: https://gitter.im/guzzle/guzzle
