### ISSUE TITLE
Shim curl_version when on Google App Engine

### ISSUE THREAD

**Issue by atrauzzi** [guzzle/guzzle#1164]
I use `curl_version` to define a header my app uses when making outbound requests to 3rd party services:

```
	'user_agent' => sprintf('Project/%s Guzzle/%s curl/%s PHP/%s',
		env('APP_VERSION', 'development'),
		GuzzleVersion::VERSION,
		CurlVersion::getInstance()->get('version'),
		PHP_VERSION
	),
```

As we know, the `CurlVersion` class above is part of the Guzzle library and eventually ends up calling `curl_version`.  Unfortunately, for whatever reason, this function isn't available in the Google App Engine development server (and I assume by extension, their server environments).

As a convenience for people using this library, instead of triggering a fatal error, maybe a best effort could be made to try and detect Google App Engine.  Take a look here for an example of how you can sniff out the environment:

https://github.com/shpasser/GaeSupportL5/blob/master/src/Shpasser/GaeSupportL5/Foundation/Application.php#L164

At which point an explicit GAE string and optional version could be extracted and returned.

**Comment by atrauzzi** [comment]
Cross referencing a ticket I made for Google App Engine: https://code.google.com/p/googleappengine/issues/detail?id=12126

**Comment by mtdowling** [comment]
I think we could just change this line to use `function_exists('curl_version')`: https://github.com/guzzle/guzzle/blob/e63c583a936fa7304eab02aa7826d8df157d3330/src/functions.php#L134. Would that work? If so, can you send a PR?

**Comment by atrauzzi** [comment]
@mtdowling - This issue might go nicely with #1191?

**Comment by mtdowling** [comment]
I'm not sure what you mean. I think you pointed out a specific problem here: GAE says it supports curl but does not support curl_version. I think the logical solution here is just to check for both the extension and the function.
