### ISSUE TITLE
Sending request through sock5 proxy not working

### ISSUE THREAD

**Issue by jitendrar** [guzzle/guzzle#1165]
I am trying to send request through my local installed TOR proxy. It is working fine with my simple PHP CURL request with below two curl options setting. But through guzzle it is returning http status code 404 and also not got response properly.

$guzzle = new GuzzleClient(['base_url' => ['webtolife.com/ps.php', []],], 
					    			array('curl.options' => array(
									  'CURLOPT_PROXY' => $tor,
									  'CURLOPT_PROXYTYPE' => 'CURLPROXY_SOCKS5',
										)
								)
					    		);
$client->setClient($guzzle);

Can someone please help me to solve this problem. I am trying to solve this since last 3 days but not able to solve.

**Comment by mtdowling** [comment]
Which version of Guzzle are you using?

**Comment by jitendrar** [comment]
I am using Goutte. And basically Goutte using Guzzle for scraping.

**Comment by mtdowling** [comment]
I need to know specifically which version of Guzzle you are using. Maybe show me your composer.json or something.

**Comment by jitendrar** [comment]
My composer.json shows "guzzlehttp/guzzle": ">=4,<6"
-------------------------------{    "name": "fabpot/goutte",    "type": "application",    "description": "A simple PHP Web Scraper",    "keywords": ["scraper"],    "homepage": "https://github.com/FriendsOfPHP/Goutte",    "license": "MIT",    "authors": [        {            "name": "Fabien Potencier",            "email": "fabien@symfony.com"        }    ],    "require": {        "php": ">=5.4.0",        "symfony/browser-kit": "~2.1",        "symfony/css-selector": "~2.1",        "symfony/dom-crawler": "~2.1",        "guzzlehttp/guzzle": ">=4,<6"    },    "autoload": {        "psr-4": { "Goutte\\": "Goutte" }    },    "extra": {        "branch-alias": {            "dev-master": "2.0-dev"        }    }}--------------------------------------------------------

**Comment by jitendrar** [comment]
More Info in this.

I am getting this error when I try to overwrite the curl option using below code.

$guzzle = $client->getClient();
$client->getClient()->setDefaultOption('config/curl/'.CURLOPT_PROXY, $tor);
$client->getClient()->setDefaultOption('config/curl/'.CURLOPT_PROXYTYPE, CURLPROXY_SOCKS5);
$client->setClient($guzzle);

Error I am getting

Exception: cURL error 7: See http://curl.haxx.se/libcurl/c/libcurl-errors.html in [phar:///var/www/public_html/vendor/goutte/goutte.phar/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php, line 49]
2015-07-13 10:59:00 Error: [GuzzleHttp\Exception\ConnectException] cURL error 7: See http://curl.haxx.se/libcurl/c/libcurl-errors.html
Stack Trace:
#0 phar:///var/www/public_html/vendor/goutte/goutte.phar/vendor/guzzlehttp/guzzle/src/RequestFsm.php(104): GuzzleHttp\Exception\RequestException::wrapException(Object(GuzzleHttp\Message\Request), Object(GuzzleHttp\Ring\Exception\ConnectException))
#1 phar:///var/www/public_html/vendor/goutte/goutte.phar/vendor/guzzlehttp/guzzle/src/RequestFsm.php(132): GuzzleHttp\RequestFsm->__invoke(Object(GuzzleHttp\Transaction))
#2 phar:///var/www/public_html/vendor/goutte/goutte.phar/vendor/react/promise/src/FulfilledPromise.php(24): GuzzleHttp\RequestFsm->GuzzleHttp\{closure}(Array)
#3 phar:///var/www/public_html/vendor/goutte/goutte.phar/vendor/react/promise/src/Promise.php(114): React\Promise\FulfilledPromise->then(Object(Closure), NULL)
#4 phar:///var/www/public_html/vendor/goutte/goutte.phar/vendor/react/promise/src/Promise.php(156): React\Promise\Promise->React\Promise\{closure}(Object(React\Promise\FulfilledPromise))
#5 phar:///var/www/public_html/vendor/goutte/goutte.phar/vendor/react/promise/src/Promise.php(128): React\Promise\Promise->settle(Object(React\Promise\FulfilledPromise))
#6 phar:///var/www/public_html/vendor/goutte/goutte.phar/vendor/react/promise/src/Promise.php(169): React\Promise\Promise->resolve(Array)
#7 [internal function]: React\Promise\Promise->React\Promise\{closure}(Array)
#8 phar:///var/www/public_html/vendor/goutte/goutte.phar/vendor/react/promise/src/Deferred.php(35): call_user_func(Object(Closure), Array)
#9 phar:///var/www/public_html/vendor/goutte/goutte.phar/vendor/guzzlehttp/ringphp/src/Client/CurlMultiHandler.php(247): React\Promise\Deferred->resolve(Array)
#10 phar:///var/www/public_html/vendor/goutte/goutte.phar/vendor/guzzlehttp/ringphp/src/Client/CurlMultiHandler.php(136): GuzzleHttp\Ring\Client\CurlMultiHandler->processMessages()
#11 phar:///var/www/public_html/vendor/goutte/goutte.phar/vendor/guzzlehttp/ringphp/src/Future/BaseFutureTrait.php(118): GuzzleHttp\Ring\Client\CurlMultiHandler->execute()
#12 phar:///var/www/public_html/vendor/goutte/goutte.phar/vendor/guzzlehttp/ringphp/src/Future/BaseFutureTrait.php(55): GuzzleHttp\Ring\Future\FutureArray->invokeWait()
#13 phar:///var/www/public_html/vendor/goutte/goutte.phar/vendor/guzzlehttp/ringphp/src/Future/BaseFutureTrait.php(118): GuzzleHttp\Ring\Future\FutureArray->wait()
#14 phar:///var/www/public_html/vendor/goutte/goutte.phar/vendor/guzzlehttp/ringphp/src/Future/BaseFutureTrait.php(55): GuzzleHttp\Message\FutureResponse->invokeWait()
#15 phar:///var/www/public_html/vendor/goutte/goutte.phar/vendor/guzzlehttp/guzzle/src/Client.php(243): GuzzleHttp\Message\FutureResponse->wait()
#16 phar:///var/www/public_html/vendor/goutte/goutte.phar/Goutte/Client.php(130): GuzzleHttp\Client->send(Object(GuzzleHttp\Message\Request))
#17 phar:///var/www/public_html/vendor/goutte/goutte.phar/vendor/symfony/browser-kit/Symfony/Component/BrowserKit/Client.php(327): Goutte\Client->doRequest(Object(Symfony\Component\BrowserKit\Request))
#18 /var/www/public_html/src/Shell/ScrapShell.php(86): Symfony\Component\BrowserKit\Client->request('GET', '/p...', Array)
#19 [internal function]: App\Shell\ScrapShell->main()
#20 /var/www/public_html/vendor/cakephp/cakephp/src/Console/Shell.php(391): call_user_func_array(Array, Array)
#21 /var/www/public_html/vendor/cakephp/cakephp/src/Console/ShellDispatcher.php(204): Cake\Console\Shell->runCommand(Array, true)
#22 /var/www/public_html/vendor/cakephp/cakephp/src/Console/ShellDispatcher.php(175): Cake\Console\ShellDispatcher->_dispatch()
#23 /var/www/public_html/vendor/cakephp/cakephp/src/Console/ShellDispatcher.php(126): Cake\Console\ShellDispatcher->dispatch()
#24 /var/www/public_html/bin/cake.php(33): Cake\Console\ShellDispatcher::run(Array)
#25 {main}

**Comment by kamilsk** [comment]
I see that this is curl-level error.

> CURLE_COULDNT_CONNECT (7)
Failed to connect() to host or proxy.

**Comment by jitendrar** [comment]
Yes, But same is working if I use curl directly to send my request without fail.
<?php$url = 'xxx.com/ps.php';
$str        = getURLContentByCURL($url);
echo $str;
function getURLContentByCURL($url) {
 //Tor address & port $tor = '127.0.0.1:9050';
 //cURL $ch = curl_init();
 //Set proxy curl_setopt($ch, CURLOPT_PROXY, $tor);
 //Set proxy type curl_setopt($ch, CURLOPT_PROXYTYPE, CURLPROXY_SOCKS5); echo "====>".CURLOPT_PROXYTYPE."<============>".CURLPROXY_SOCKS5."<=====>".CURLOPT_PROXY."<====";
 //The URL to which to POST the data curl_setopt($ch, CURLOPT_URL, $url);
 //Execute $result = curl_exec($ch); curl_close($ch);    // Closing cURL return $result;   // Returning the data from the function}?>

**Comment by jitendrar** [comment]
I have did changes like below and now its working fine. :)

$guzzle = $client->getClient();        
$client->getClient()->setDefaultOption('config/curl/'.CURLOPT_PROXY, 'socks5://127.0.0.1:9050');
$client->setClient($guzzle);

thanks all for your help on this and also for nice library.

**Comment by kamilsk** [comment]
:+1:
