### ISSUE TITLE
[RuntimeException] Invalid cookie: Cookie name must not contain...

### ISSUE THREAD

**Issue by nezhelskoy** [guzzle/guzzle#1169]
In Codeception for acceptance test i getting error

```
[RuntimeException] Invalid cookie: Cookie name must not contain invalid characters: ASCII Control characters (0-31;127), space, tab and the following characters: ()<>@,;:\"/[]?={}
```

In my case, cookie name is  **IP[1436525061]** (for example).

I think this cookie name is valid, because it using the ability https://secure.php.net/manual/en/function.setcookie.php (see Example 3).

**Comment by mtdowling** [comment]
The ABNF in RFC 6265 shows that a cookie name does not allow [] characters: http://tools.ietf.org/html/rfc6265#section-4.1.1. If you follow the link to RFC 2616, you can see where the token rule is defined: http://tools.ietf.org/html/rfc2616#section-2.2. Cookie names must comply with the token rule.

I think you'll need to encode these characters when setting cookies.

**Comment by nezhelskoy** [comment]
> I think you'll need to encode these characters when setting cookies.

Thanks for the tip. Function `rawurlencode` helped to solve the problem
