### ISSUE TITLE
Monolog LogPlugin does not work

### ISSUE THREAD

**Issue by samsamm777** [guzzle/guzzle#1170]
Getting the following error when trying to add a MonoLog subscriber.

Warning: parse_url() expects parameter 1 to be string, object given
500 Internal Server Error - ContextErrorException

``` php
$adapter = new MonologLogAdapter($logger);
$logPlugin = new LogPlugin($adapter, MessageFormatter::DEBUG_FORMAT);

$this->httpClient = new Client([
    'base_uri' => $this->baseUri,
    'timeout'  => 2.0,
    'cookies'  => true
]);

// Attach the plugin to the client, which will in turn be attached to all
// requests generated by the client
$this->httpClient->addSubscriber($logPlugin);
```

**Comment by jeskew** [comment]
Hi @samsamm777,

What version of Guzzle are you using?

**Comment by samsamm777** [comment]
@jeskew  `6.0.*`

**Comment by jeskew** [comment]
The call to `addSubscriber` looks like Guzzle 3 code. It's getting caught by `__call` in a Guzzle 6 client, which assumes that the first argument passed in is a URI.

Guzzle 6 doesn't use an event emitter anymore, as PSR-7 messages are immutable (and most Guzzle events modified existing request or response objects). Instead, you can use [handlers and middleware](http://docs.guzzlephp.org/en/latest/handlers-and-middleware.html). Let me see if there's any kind of premade monolog middleware.

**Comment by samsamm777** [comment]
Ahh my mistake. Was reading the old docs it looks like! I've found the 'debug' option for now which may suffice for the time being. I'll look into finding/writing a monolog middleware in due course. Thanks

**Comment by mtdowling** [comment]
There is already a PSR-3 compatible logging middleware in Guzzle: https://github.com/guzzle/guzzle/blob/master/src/Middleware.php#L184
