### ISSUE TITLE
Duplicated Array Elements

### ISSUE THREAD

**Issue by bustarice** [guzzle/guzzle#1171]
I'm having some random issue where getting a json object response that some but not all array elements become duplicated. I used Fiddler to get the same response and it was not duplicated so definitely something to do with Guzzle.

After I get the response I convert it to a json array:

```
$json = $response->json();
```

Now here is a snippet of what was duplicated:

```
            [94] => Array
                (
                    [shipmentId] => 84122811
                    [orderId] => 118651714
                    [advancedOptions] => 
                    [shipmentItems] => Array
                        (
                            [0] => Array
                                (
                                    [orderItemId] => 167933564
                                    [sku] => CBE-ME95NT+HDS+HFC
                                    [name] => 4.5" MUFFLER TIP CATBACK/CAT BACK+HEADER+PIPING EXHAUST 95-99 MIT ECLIPSE/TALON
                                    [weight] => Array
                                        (
                                            [value] => 720
                                            [units] => ounces
                                        )

                                    [quantity] => 1
                                    [unitPrice] => 183.98
                                    [warehouseLocation] => 
                                    [options] => 
                                    [productId] => 7900049
                                    [fulfillmentSku] => 
                                    [adjustment] => 
                                )

                            [1] => Array
                                (
                                    [orderItemId] => 167933564
                                    [sku] => CBE-ME95NT+HDS+HFC
                                    [name] => 4.5" MUFFLER TIP CATBACK/CAT BACK+HEADER+PIPING EXHAUST 95-99 MIT ECLIPSE/TALON
                                    [weight] => Array
                                        (
                                            [value] => 720
                                            [units] => ounces
                                        )

                                    [quantity] => 1
                                    [unitPrice] => 183.98
                                    [warehouseLocation] => 
                                    [options] => 
                                    [productId] => 7900049
                                    [fulfillmentSku] => 
                                    [adjustment] => 
                                )

                        )
                )
```

Instead of pasting it again, the fiddler version (which is correct by the way) only shows 1 array. So not sure why Guzzle adding another duplicate array out of nowhere.

**Comment by mtdowling** [comment]
That's Guzzle 3, which is at https://github.com/guzzle/guzzle3. You can reopen this issue at https://github.com/guzzle/guzzle3 if necessary, but there's no way Guzzle is duplicating anything when calling the `json` method of a response. It simply uses PHP's json_decode function.

**Comment by bustarice** [comment]
Hello @mtdowling thanks didn't realize I was posting this on the wrong spot. I'll test the json_decode function directly and see what happens. I'll reopen on the correct area if I find anything other than what's stated already.

**Comment by bustarice** [comment]
Hello @mtdowling , I realized I was actually using Guzzle 5 but now I upgraded to the latest 6. I do notice the ->json command is no longer there so I am using the json_decode as a replacement which as you stated did the same thing.

I do notice the same issue is occurring and how certain array elements are still being duplicated. As previously stated when using Fiddler the raw response as well as the json both look perfect. I'm not sure what else I can do to debug. If you have any other insights I'd be happy to look into it.

Please reopen this if necessary.

Thank you.

**Comment by bustarice** [comment]
Actually nevermind the server was sending weird responses if I kept the page size at 500 but reducing it to 400 seemed to fix it so far.
