### ISSUE TITLE
Set-Cookie:fromString trims " from value.

### ISSUE THREAD

**Issue by jaskolek** [guzzle/guzzle#1172]
I was creating bot for polish website gumtree.pl. After logging in, it sets cookie with value like "rO0ABXNyAD1vcmcuc3Bya(...)W5nZnJhbWV3b3JrLnNlY3" (with " at ends) but Guzzle is parsing it as rO0ABXNyAD1vcmcuc3Bya(...)W5nZnJhbWV3b3JrLnNlY3 (without "). Due to this, I can't log in. I haven't found any reason why this is happening (RFC doesn't say anything about " signs)

Also, I have found that string is trimmed in SetCookie:fromString method (line 49 exactly).

I'm using V6

**Comment by mtdowling** [comment]
[RFC 2109](http://www.ietf.org/rfc/rfc2109.txt) allows for quoted strings in cookies, but it also goes on to talk about that you should really only use that if you are sure that you're working with a client that understand "new" cookies. I think removing the stripping of `"` is a good idea.
