### ISSUE TITLE
Can the OAuth Plugin still be used in this version?

### ISSUE THREAD

**Issue by jdgriffith** [guzzle/guzzle#1173]
I am using 6.*. I was using the OAuth Plugin before where you could add a subscriber. Is it possible to do this in the new version?

**Comment by mtdowling** [comment]
Not yet. The OAuth subscriber needs to be ported to a Guzzle middleware. There are OAuth implementations that use guzzle though.

**Comment by jdgriffith** [comment]
Ok thanks for response.

**Comment by kkopachev** [comment]
btw, pull request is open https://github.com/guzzle/oauth-subscriber/pull/36 
For now https://github.com/cbakker/guzzle-oauth seems usable
