### ISSUE TITLE
Multipart with an array form value?

### ISSUE THREAD

**Issue by Michal-sk** [guzzle/guzzle#1177]
Is it possible to send a multipart form with an array value? For example when using a multi-select list?

**Comment by Michal-sk** [comment]
foo[a]='123'
foo[b]='456'

**Comment by Michal-sk** [comment]
Above is actually not workable for multiselect lists. Any input on those?

**Comment by mtdowling** [comment]
There are examples in the documentation that show how to format the `multipart` request option: http://docs.guzzlephp.org/en/latest/request-options.html#multipart. Each part in the multipart option is a hash that contains a "name". You can provide the same name multiple times per field, or you can use a single part that uses a content-type of `application/x-www-form-urlencoded`. Guzzle is just an HTTP client -- it is not an HTML client. You might try a form builder and scraper like Goutte that use Guzzle.

**Comment by Michal-sk** [comment]
So both of the following should work and result in the same on the endpoint?
First suggestion: same name multieple times.

```
array (
  0 => 
  array (
    'name' => 'nummer',
    'contents' => '111111',
  ),
  1 => 
  array (
    'name' => 'naam',
    'contents' => 'Naam',
  ),
  2 => 
  array (
    'name' => 'plaats',
    'contents' => 'Plaats',
  ),
  3 => 
  array (
    'name' => 'website',
    'contents' => 'Web',
  ),
  4 => 
  array (
    'name' => 'email',
    'contents' => 'info@example.com',
  ),
  5 => 
  array (
    'name' => 'color',
    'contents' => '0',
  ),
  6 => 
  array (
    'name' => 'archivecode',
    'contents' => '',
  ),
  7 => 
  array (
    'name' => 'showroom-project',
    'contents' => '1',
  ),
  8 => 
  array (
    'name' => 'showroom-project',
    'contents' => '2',
  ),
  9 => 
  array (
    'name' => 'showroom-project',
    'contents' => '3',
  ),
  10 => 
  array (
    'name' => 'showroom-project',
    'contents' => '5',
  ),
  11 => 
  array (
    'name' => 'op',
    'contents' => 'insert',
  ),
)
```

and
Second suggestion, changing the content-type of the part which contains an array.

```
array (
  0 => 
  array (
    'name' => 'nummer',
    'contents' => '111111',
  ),
  1 => 
  array (
    'name' => 'naam',
    'contents' => 'Naam',
  ),
  2 => 
  array (
    'name' => 'plaats',
    'contents' => 'Plaats',
  ),
  3 => 
  array (
    'name' => 'website',
    'contents' => 'Web',
  ),
  4 => 
  array (
    'name' => 'email',
    'contents' => 'info@example.com',
  ),
  5 => 
  array (
    'name' => 'color',
    'contents' => '0',
  ),
  6 => 
  array (
    'name' => 'archivecode',
    'contents' => '',
  ),
  7 => 
  array (
    'name' => 'showroom-project',
    'headers' => 
    array (
      'content-type' => 'application/x-www-form-urlencoded',
    ),
    'contents' => 
    array (
      0 => '1',
      1 => '2',
      2 => '3',
      3 => '5',
    ),
  ),
  8 => 
  array (
    'name' => 'op',
    'contents' => 'insert',
  ),
)
```

The first example, on the endpoint only receives the last value: 5
The second example throws an error because contents is an array and Guzzle throws an exception for those.

What am i missing here?

**Comment by xmyno** [comment]
You can send form values as array values in the POST body like this:

```php
$multipart = [
  [
    'name' => 'showroom-project[first]',
    'contents' => '3',
  ],
  [
    'name' => 'showroom-project[second]',
    'contents' => '5',
  ],
...
];
```

On the receiving side this will make them accessible as ``` $_POST['showroom-project']['first'] ``` and so on.

**Comment by Michal-sk** [comment]
Thanks for this.

**Comment by taz77** [comment]
If someone else finds this. I would love to know if anyone has got the option to work by setting the Content-Type = application/x-www-form-urlencoded. So far all of my testing comes up as a failure with the error `Invalid resource type: array in GuzzleHttp\Psr7\stream_for()` being thrown.

**Comment by Jaggle** [comment]
the same here with 4years passed

**Comment by prince-vishal** [comment]
Same here

**Comment by AbdurRehman333** [comment]
Same here. 2 More years passed -_-
