### ISSUE TITLE
Sending form with file - how

### ISSUE THREAD

**Issue by danielczestki** [guzzle/guzzle#1178]
I have problem with sending form with post.
I have 3 elements:
login
password
file

I tried to use multipart option but it dosn't work.
When I try to use multipart along with form_params options Guzzle echo warnings that it is impossible.
Than how can I do this.

**Comment by jeskew** [comment]
Hi @danielczestki,

You can't use `multipart` and `form_params` together, but you can send fields like "login" and "password" along with a multipart form. There's [a short tutorial on doing so in the docs](http://docs.guzzlephp.org/en/latest/quickstart.html#sending-form-files) that should help get you started.
