### ISSUE TITLE
Comparision when use a POST body by default

### ISSUE THREAD

**Issue by teklakct** [guzzle/guzzle#1179]
I can't find in standard lib a const with HTTP method names, so i use strings. Sometimes a use lowercase methods name (last time from now). I've spent a few hours to figure out why it not work for me.

In `GuzzleHttp\Message\MessageFactory::createRequest($method, $url, array $options = [])` when we create a request with **POST** method without *body* or *json* option, then *body* is set as empty array. Later `addPostData($request, $value);` method adds to request an empty *PostBody*.

Everything is good, but the comparasion is a little confusing. 

```
        // Use a POST body by default
        if ($method == 'POST'
            && !isset($options['body'])
            && !isset($options['json'])
        ) {
            $options['body'] = [];
        }
```

My suggestion is to use uppercase a $method passed to `createRequest`. 

```
        // Use a POST body by default
        if (strtoupper($method) == 'POST'
            && !isset($options['body'])
            && !isset($options['json'])
        ) {
            $options['body'] = [];
        }
```

Now we could use:

```
$request = createRequest('post', 'my/url', []);
```

**Comment by kamilsk** [comment]
Hi, @teklakct! What you think about this:
```php
if (!strcasecmp($method, 'post') && !isset($options['body'], $options['json']))
```

**Comment by teklakct** [comment]
Hi @kamilsk, i've check it and one of my test fails, because `!isset($options['body'], $options['json'])`. 

Try check. when you have set **ONLY ONE** *body* or *json* key in $options array:
```
$method = 'POST';
$options['body'] = 'something';
```
For me it fail. **strcasecmp** is ok, but check of variable set in $options array fails.

Try this:
`if (!strcasecmp($method, 'post') && !isset($options['body']) && !isset($options['json']))`

Here my gist where a use PHPSpec to check this: https://gist.github.com/teklakct/35621464f4f1ab285d3b

**Comment by kamilsk** [comment]
Strangely. In a simple example, I got what I expected:
```php
php > $p = ['a' =>'', 'c' => ''];
php > var_dump(!isset($p['a']));
bool(false)
php > var_dump(!isset($p['a'], $p['b']));
bool(true)
php > var_dump(!isset($p['a'], $p['b'], $p['c']));
bool(true)
```

**Comment by kamilsk** [comment]
I mean that `!isset($p['a'], $p['b'])` is equivalent to `!isset($p['a']) && !isset($['b'])`

**Comment by kamilsk** [comment]
@teklakct, sorry, my mistake, you are right

`!isset($p['a'], $p['b'])` is equivalent to `!isset($p['a']) || !isset($['b'])`

**Comment by kamilsk** [comment]
Non-strict comparison is slower
```php
$start = microtime(true); for ($i = 0; $i < 1e7; $i++) { strtoupper('pOsT') == 'POST'; }; $end = microtime(true); echo $end - $start;
# ~ 1.49
```
than
```php
$start = microtime(true); for ($i = 0; $i < 1e7; $i++) { strtoupper('pOsT') === 'POST'; }; $end = microtime(true); echo $end - $start;
~ 1.35
```
but `strcasecmp`
```php
$start = microtime(true); for ($i = 0; $i < 1e7; $i++) { !strcasecmp('pOsT', 'POST'); }; $end = microtime(true); echo $end - $start;
# ~ 1.36
```
almost equivalent, so there is no reason to use `strcasecmp`, enough to use strict comparison.

**Comment by teklakct** [comment]
:+1:

**Comment by mtdowling** [comment]
What's the TLDR here? Can you send a PR?

**Comment by teklakct** [comment]
@mtdowling I'm sorry of the lack of response but i've been on holiday. Thank's for #1179
