### ISSUE TITLE
Guzzle documentation does not mention the version number

### ISSUE THREAD

**Issue by dirtside** [guzzle/guzzle#1180]
It might be buried somewhere deep (although I did search several times), but the Guzzle documentation at http://docs.guzzlephp.org/en/latest/ does not, at any point, mention which version of Guzzle the documentation is for. Other places (such as README.md) link v6 to the above URL, but the docs site itself does not actually say which version it's for. This can be confusing if a Google search leads you directly to the Guzzle documentation.

**Comment by jeskew** [comment]
@dirtside There's a version selector that floats in the lower right hand corner.

**Comment by dirtside** [comment]
I see that, but the version selector does not mention v6. Just "latest." It seems like version numbers should be explicit, to avoid confusion (with the latest one flagged as "latest" rather than that information being implicitly defined elsewhere). Otherwise, how does a user know that "latest" and "v6" are the same thing, without referencing something outside the docs site?

**Comment by dirtside** [comment]
Thanks!
