### ISSUE TITLE
How to read the response stream object GuzzleHttp? 

### ISSUE THREAD

**Issue by datnq201088** [guzzle/guzzle#1182]
I call API and response is `json` object. When I use GuzzleHttp , the response is `Stream` object. 
How can I read the expected response from response Guzzle? 
```
use GuzzleHttp\Client;
use GuzzleHttp\Message;
use GuzzleHttp\Middleware;
use GuzzleHttp\Stream\Stream;

$client = new Client(['base_uri' => 'http://api.com/);
$res = $client->get('getdata');
var_dump($res->getBody());die;
```

**Comment by kamilsk** [comment]
just try `(string) $res->getBody()`

**Comment by MichaelHuyPhan** [comment]
you could use `$res->getBody()->getContents();`
refer this: https://stackoverflow.com/questions/30549226/guzzlehttp-how-get-the-body-of-a-response-from-guzzle-6?answertab=votes#tab-top
