### ISSUE TITLE
StreamHandler testing for parallel request

### ISSUE THREAD

**Issue by danelsan** [guzzle/guzzle#1186]
I tested StreamHandler for parallel request because i have error into curl_reset(), but I have the impression than parallel request is only serial request.
It's possible?
I tested the time and it is the sum of all requests.
Thanks for reply.

**Comment by kamilsk** [comment]
Hi! Can we learn more about the testing process?

**Comment by danelsan** [comment]
I test more $requests. I done similar this:

$handler = new \GuzzleHttp\Handler\StreamHandler();
$stack = \GuzzleHttp\HandlerStack::create($handler); // Wrap w/ middleware
$client = new  \GuzzleHttp\Client(array('handler' => $stack));

// Create more client requests
foreach( $requests as $k => $request ) {
	$r[$k] = $client->requestAsync($request['method'], $request['url'], $options );		
	$r[$k]->then(function ( $response ) {
		}, 
          function (\Exception $error) {
			//	return $error;
			});
 }

// Getting the result
try {
	$result =  Promise\unwrap($r);
	$stop = microtime(TRUE);
	$this->bench_time = $stop-$start;
	return $result;
	
} catch (\Exception $e ) {
	}		



// Getting the result
try {
	$result =  Promise\unwrap($r);
	$stop = microtime(TRUE);
	$this->bench_time = $stop-$start;
	return $result;
	
} catch (\Exception $e ) {
	}

**Comment by mtdowling** [comment]
The StreamHandler cannot send requests concurrently. You'll need to use curl or a custom handler for that.

**Comment by danelsan** [comment]
Thank you very much. 
Sorry, but i not found anything for create a custom handler. You know some link for this.

**Comment by mtdowling** [comment]
> I tested StreamHandler for parallel request because i have error into curl_reset()

Yeah, this method requires PHP 5.5 or newer and the curl extension.

The stream handler does not support concurrent requests. The docs on creating a handler a basically non-existent, but they're here: http://docs.guzzlephp.org/en/latest/handlers-and-middleware.html#creating-a-handler You could try taking a look at the React handler to see how a handler is implemented: https://github.com/WyriHaximus/react-guzzle-http-client
