### ISSUE TITLE
JSON array responses with a single element are returned as the single element only

### ISSUE THREAD

**Issue by charles-rumley** [guzzle/guzzle#1188]
My target URI will respond with a JSON array containing a single element, like so:
```json
[
  {
    "subject": null
  }
]
```
However, calling ```$client->get($uri)->getBody()->getContents()``` returns the following:
```json
{
  "subject": null
}
```
Curiously, a JSON array containing multiple elements is parsed correctly. The issue only manifests itself when parsing a JSON array with a single element. Any thoughts? I'm using Guzzle 6.0.2.

**Comment by mtdowling** [comment]
That's weird. Guzzle does not parse the response body data in any way. Are you sure your API is responding like you think it is? Have you tried just accessing it from the command line to see what the body of the response is?

1. You might try using the debug option to see what headers are being sent over the wire.
2. If that looks correct, then try capturing a tcpdump while transferring a request to see if the body is transferred correctly.

**Comment by charles-rumley** [comment]
@mtdowling it ended up being my own fault! Thanks for asking!
