### ISSUE TITLE
Is it possible to mimic "stream_socket_client" using Guzzle?

### ISSUE THREAD

**Issue by Oliboy50** [guzzle/guzzle#1190]
Is it possible to do this kind of thing with guzzle:

```
    $ctx = stream_context_create(array(
        'ssl' => array(
            'local_cert' => $myLocalCert,
            'passphrase' => $myPassphrase,
        ),
    ));
    $stream = stream_socket_client(
        'tls://gateway.sandbox.push.apple.com:2195',
        $errno,
        $errstr,
        30,
        STREAM_CLIENT_CONNECT | STREAM_CLIENT_PERSISTENT,
        $ctx
    );

    fwrite($stream, $myMessage, strlen($myMessage));
```

Note the `tls` protocol instead of `http(s)`.

( I also asked this question on SO: http://stackoverflow.com/questions/31592717/is-it-possible-to-write-on-an-external-socket-using-guzzle )

**Comment by mtdowling** [comment]
Not really. Guzzle is an abstraction a layer higher than sockets. Guzzle can use sockets to expose it's API, but you cannot use Guzzle like a socket.
