### ISSUE TITLE
How do you get and modify default middleware stacks?

### ISSUE THREAD

**Issue by atrauzzi** [guzzle/guzzle#1192]
In reading through the documentation, lots is said about creating a custom stack, but what if I'm using a library that isn't going to use any stack I create?

How do I modify the global default stack that is used when I or anyone else goes `new Client()`?

It might be worthwhile to add this to the documentation somewhere with some keywords/phrases like "default global middleware stack" and "default global handler stack".

**Comment by mtdowling** [comment]
There is no global stack or anything, there's just a default stack configuration that is created each time `GuzzleHttp\HandlerStack::create` is called. I don't think this should be something that can be modified as modifying the default stack could cause issues for applications that do not realize the default stack is being modified from what Guzzle ships by default.
