### ISSUE TITLE
GuzzleHttp\Psr7\Response Abstract Error

### ISSUE THREAD

**Issue by danhanly** [guzzle/guzzle#1193]
I'm getting the below message when interacting with Guzzle:

```
[Symfony\Component\Debug\Exception\FatalErrorException]                                                                                                                                  
  Class GuzzleHttp\Psr7\Response contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (Psr\Http\Message\ResponseInterface::setPostField)
```

**Comment by 24unix** [comment]
Did you find a solution?

**Comment by GrahamCampbell** [comment]
Upgrade to the latest version.

**Comment by 24unix** [comment]
I’m on 7.4 but still get:
```
[255] % ./vendor/bin/phpunit tests/App/Controller/RequestControllerTest.php
PHPUnit 9.5.13 by Sebastian Bergmann and contributors.

PHP Fatal error:  Class GuzzleHttp\Psr7\Response contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (Psr\Http\Message\ResponseInterface::send) in /home/users/tfunix/www/vendor/guzzlehttp/psr7/src/Response.php on line 13

```

**Comment by GrahamCampbell** [comment]
What is in `/home/users/tfunix/www/vendor/composer.lock`? Can you paste it in a gist?

**Comment by 24unix** [comment]
I don’t know if Gitea support gists.

Is this OK?

https://y.24unix.net/hmes1

**Comment by GrahamCampbell** [comment]
The issue is you do not have the latest version of Guzzle 6 or it's dependencies.

<img width="453" alt="image" src="https://user-images.githubusercontent.com/2829600/152444514-750cd799-7ba9-41b4-b68a-f1034be5e399.png">

**Comment by GrahamCampbell** [comment]
Even better, you should upgrade to Guzzle 7. Guzzle 6 is EOL.

**Comment by GrahamCampbell** [comment]
Do you have old versions of Guzzle installed globally? What's the output of `composer global show`? Beyond this, I can only assume it's an issue with your app code. If you'd like to buy some consulting time, let me know.

**Comment by 24unix** [comment]
For me it’s look like I’m on 7.4?

Sorry, not very familiar with composer, already trie composer update, but it didn’t change anything.

**Comment by 24unix** [comment]
Regarding the consulting time: We can talk about that later, local time is 00:15, I’m away soon.

**Comment by GrahamCampbell** [comment]
Of course. Ping me at `hello at gjcampbell.co.uk`.

**Comment by 24unix** [comment]
```
Composer could not find a composer.json file in /home/users/tfunix/.config/composer
To initialize a project, please create a composer.json file. See https://getcomposer.org/basic-usage
```

However I gave up, built a curl wrapper, that at least works.
