### ISSUE TITLE
simultaneously multiple request generating CURL error 18

### ISSUE THREAD

**Issue by jitendrar** [guzzle/guzzle#1194]
I have created two scripts and when I tried to execute 2nd script when 1st is running then 1st gives CURL error 18 and stops working. It means two scripts are not simultaneously working using goutte and gazzle.

**Comment by mtdowling** [comment]
From http://curl.haxx.se/libcurl/c/libcurl-errors.html

```
CURLE_PARTIAL_FILE (18)

A file transfer was shorter or larger than expected. This happens when the server first reports an expected transfer size, and then delivers data that doesn't match the previously given size.
```

It sounds like your webserver is not sending the full amount of data when you connect to it with multiple connections. Please update this issue and I'll reopen if you can provide a reproducible test case that shows something that Guzzle is doing wrong.

**Comment by jitendrar** [comment]
I think, It is not my web server issue. Because simple curl script is working fine for simultaneous request. Only when I tried to send using goutte(gazzle) it returns Curl error 18. I have already read what curl error 18 means. I suspect that the way goutte(gazzle) send the curl request creating problem and might be some configuration required in Curl before sending request through gazzle.

**Comment by jitendrar** [comment]
Can someone please help on this?

**Comment by jdarrohn** [comment]
Not sure what it is -- but I can +1 as it works in Postman...
