### ISSUE TITLE
duplicateAggregator() functionality missing with update to Psr7

### ISSUE THREAD

**Issue by LKS90** [guzzle/guzzle#1196]
Hey there! I just had a problem when porting some code to the newer Guzzle version. With the removal of `GuzzleHttp\Query`, the `Query::duplicateAggregator()` functionality is now gone and it seems impossible to easily replace some queries now.

My query is an array, important is that 'q' is a non-associative array.

```
$request_query = [
  'key' => 'INSERT-YOUR-KEY',
  'source' => 'en',
  'target' => 'de',
  'q' => [
    'Hello World',
    'My name is Jeff',
  ],
];
```

 The code I am porting:

```
$query = $request->getQuery();
$query->merge($request_query);
$query->set('key', $translator->getSetting('api_key'));
$query->setAggregator($query::duplicateAggregator());
```

The result should be

```
?key=INSERT-YOUR-KEY&source=en&target=de&q=Hello%20world&q=My%20name%20is%20Jeff
```

My problem when porting the code: There seems to be no possibility to repeat a key for an non-associative array, the way it used to work with `setAggregator($query::duplicateAggregator())`.

I resorted to building the query string myself and attaching it when sending, but if there is some easy solution I overlooked, I'd be happy if you would hint me towards it.

If this is a regression, is it possible to reintroduce?

**Comment by mtdowling** [comment]
Removing the Query class was intentional and not a regression.

Guzzle now accepts an array or a string as the `query` request option. The big shift from Guzzle 5 to 6 is that PSR-7 represents query strings on request objects simply as strings. Including a Query class in Guzzle 6 would really just be a query string builder that creates a string of data (a request would not own the query object).

**Comment by Berdir** [comment]
Yes, such a builder is exactly what would be helpful if you have query strings that can't be represented/built by PHP from an array, for example the duplicate aggregator implementation.

See https://www.drupal.org/node/2539228#comment-10160842 for a before/after

**Comment by mtdowling** [comment]
Sure. We can add query string serialization into Guzzle 6. I don't know if we need a full on builder or just a couple convenience functions that can be used to convert an array into a query string.

for example:

- duplicate aggregation
- PHP style aggregation
- PHP style aggregation that does not use an incrementing index.

**Comment by Berdir** [comment]
Sure, I don't really care about if it's a builder class or a function.. whatever works for you.

**Comment by peec** [comment]
I'm in need for this. Guzzle should support this since it's library is very often used for 3rdparty API's.



```
'query' => [
    'product' => [342, 3211, 32212]
]
```

Which should be possible to get in this format also (which many REST services use) instead of `product[]=342`:

```
?product=342&product=3211&product=32212
```

**Comment by Tobion** [comment]
`build_query` does exactly that: https://github.com/guzzle/psr7/blob/master/src/functions.php#L572

So this issue can be closed.

**Comment by sagikazarmark** [comment]
@Tobion can you please confirm again that the link you provided resolves this issue?

**Comment by Tobion** [comment]
Yes.

> This function does not modify the provided keys when an array is encountered (like http_build_query would).

**Comment by sagikazarmark** [comment]
Thank you.

**Comment by jeromejaglale** [comment]
How to use that function:

```
// parameters to send
$params = [...]
 
$query_string = \GuzzleHttp\Psr7\build_query($params, PHP_QUERY_RFC1738);
 
$options = [];
$options['body'] = $query_string ;
$options['headers'] = ['Content-Type' => 'application/x-www-form-urlencoded'];
 
// send request
$response = $client->request('POST', $url, $options);
```

I added this (also from Guzzle) to remove empty parameters:

```
// remove null values
foreach ($params as $k => $v) {
    if ($v === null) {
        unset($params[$k]);
    }
}
```

**Comment by Flexo013** [comment]
> `build_query` does exactly that: https://github.com/guzzle/psr7/blob/master/src/functions.php#L572


This function is now deprecated, but you can easily do the same using `Query::build` from here: https://github.com/guzzle/psr7/blob/master/src/Query.php#L71
