### ISSUE TITLE
How can I get the final Request object?

### ISSUE THREAD

**Issue by justincy** [guzzle/guzzle#1198]
While testing, I want to make sure that I'm setting some headers properly. I can get access to the original Request object but it doesn't contain any headers added through default options or middleware. How can I get the final Request object?

**Comment by mtdowling** [comment]
You can add a middleware at the end of your handler stack. The `tap` middleware is a great way to peek into the state of a request at any given point in the stack: https://github.com/guzzle/guzzle/blob/master/src/Middleware.php#L124

```php
use Psr7\Http\Message\RequestInterface;
use GuzzleHttp\HandlerStack;
use GuzzleHttp\Handler\CurlHandler;
use GuzzleHttp\Client;
use GuzzleHttp\Middleware;

$stack = new HandlerStack();
$stack->setHandler(new CurlHandler());

$stack->push(Middleware::tap(function (RequestInterface $request, array $options) {
    echo "I have access to the request and options!";
}));

$client = new Client(['handler' => $stack]);
```

Note that the order in which middleware is added to a handler stack is significant. Pushing the tap middleware last will ensure that it is the last thing to see a request. Shifting it to the front of the list will ensure that it sees the request first.
