### ISSUE TITLE
Post body encoding being erroneously escaped?

### ISSUE THREAD

**Issue by chriskl** [guzzle/guzzle#1199]
Hi,

I have a problem using Guzzle 6.0.2 that's just driving me insane.

This snippet is submitting a pretty simple POST.
```
 $response = $this->client->post('/auth', [
            'form_params' => [
                'username' => 'foo',
                'password' => 'bar'
            ]
        ]);
```

However, on the receiving end if I dump out the raw POST body I am seeing:

```
username=foo&amp;password=bar
```

So that of course parses into two POST variable named like this:
```
username = foo
amp;password = bar
```
When I use Postman, or check how the spec says they should be encoded, they are like this:

```
username=foo&password=bar
```

Which is correct.

What's going on?  What on earth is escaping the ampersand in my post body!

**Comment by chriskl** [comment]
Here is is captured with Fiddler:

```
POST https://api.accord-dev.local/auth HTTP/1.1
Accept: application/xml
User-Agent: GuzzleHttp/6.0.2 curl/7.26.0 PHP/5.5.27-1~dotdeb+7.1
Content-Type: application/x-www-form-urlencoded
Host: api.accord-dev.local
Content-Length: 42

username=moodle&amp;password=holT31raya%3B
```

And here is the Postman version:

```
POST https://api.accord-dev.local/auth HTTP/1.1
Host: api.accord-dev.local
Connection: keep-alive
Content-Length: 38
Accept: application/xml
Cache-Control: no-cache
Origin: chrome-extension://aicmkgpgakddgnaphhhpliifpcfhicfo
Content-Type: application/x-www-form-urlencoded
User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.107 Safari/537.36
Postman-Token: e4ec2576-9baf-c980-bfd4-9c8760c87100
Accept-Encoding: gzip, deflate
Accept-Language: en-GB,en-US;q=0.8,en;q=0.6

username=moodle&password=holT31raya%3B
```

**Comment by mtdowling** [comment]
You're (arg_separator.output)[http://php.net/manual/en/ini.core.php#ini.arg-separator.output] ini setting is set to `&amp` which is causing Guzzle to write query strings the same way. You'll need to change this to `&` or pick the master branch so that you can pull in the fix from https://github.com/guzzle/guzzle/commit/8114c93801ec7efd1e5ee16c0c9f233ebbfd95b1.

**Comment by chriskl** [comment]
Ah, interesting.  Because I'm posting from one vagrant VM to another - the configs are different :/  Thanks.

**Comment by adambuczek** [comment]
Is there any other possible cause of this?
`$result = $client->request('GET', 'http://domain.com/api/product?c=US&id=' . $product->id);`
Returns an error. Logged URL is:
`http://domain.com/api/product?c=US&amp;id=123456`
I've got Guzzle 6.2.2 and PHP 7.0. I checked my `arg_separator.output` and it is `&`.
