### ISSUE TITLE
Always Receiving 400 Bad Request Response

### ISSUE THREAD

**Issue by mdavis1982** [guzzle/guzzle#1200]
When trying to connect to an API that uses both `verify` and an `ssl_key` parameter, I'm always getting a `400 Bad Request` response and it doesn't appear to send the data to the receiving URL. My code looks as follows:

```php
$client = new GuzzleHttp\Client([
    'verify'          => storage_path('app/cert.crt'),
    'ssl_key'         => storage_path('app/private.pem'),
    'allow_redirects' => true,
    'debug'           => true,
    'curl'            => [
        CURLOPT_SSLVERSION => CURL_SSLVERSION_TLSv1_2,
    ],
]);

$request = new Request(
    'POST',
    'https://example.com/sandbox/v1/list',
    [
        'Content-type' => 'application/json',
        'profile'      => 'http://example.com/list.json',
        'User-Agent'   => 'curl/7.24.0'
    ],
    '{"foo": "bar"}'
);

try {
    $response = $client->send($request);
} catch (RequestException $e) {
    dd($e);
}
```

It doesn't appear to send the request to the server, so the output shows no TLS handshake etc:

```
* Hostname was found in DNS cache
* Hostname in DNS cache was stale, zapped
*   Trying 1.1.1.1...
* Connected to example.com (1.1.1.1) port 443 (#14)
* successfully set certificate verify locations:
*   CAfile: /home/vagrant/example/storage/app/cert.crt
  CApath: /etc/ssl/certs
* SSL connection using ECDHE-RSA-AES128-GCM-SHA256
* Server certificate:
* 	 REDACTED
* 	 SSL certificate verify ok.
> POST /sandbox/v1/list HTTP/1.1
Host: example.com
Content-type: application/json
profile: http://example.com/list.json
User-Agent: curl/7.24.0
Content-Length: 28

* upload completely sent off: 28 out of 28 bytes
< HTTP/1.1 400 Bad Request
< Date: Wed, 29 Jul 2015 09:47:05 GMT
< Content-Type: application/json
< Content-Length: 517
< Connection: close
< ETag: "54f086d8-205"
< 
* Closing connection 14
```

Is this something that I'm doing wrong? It works in the terminal with the following command:

```
echo '{ "foo" : "bar" }' | curl --key private.pem --cert cert.crt --data @- --header "Content-type: application/json; profile=http://example.com/list.json" https://example.com/sandbox/v1/list
```

And I get the following output (when using the `--verbose` option):

```
* Hostname was NOT found in DNS cache
*   Trying 1.1.1.1...
* Connected to example.com (1.1.1.1) port 443 (#0)
* successfully set certificate verify locations:
*   CAfile: none
  CApath: /etc/ssl/certs
* SSLv3, TLS handshake, Client hello (1):
* SSLv3, TLS handshake, Server hello (2):
* SSLv3, TLS handshake, CERT (11):
* SSLv3, TLS handshake, Server key exchange (12):
* SSLv3, TLS handshake, Request CERT (13):
* SSLv3, TLS handshake, Server finished (14):
* SSLv3, TLS handshake, CERT (11):
* SSLv3, TLS handshake, Client key exchange (16):
* SSLv3, TLS handshake, CERT verify (15):
* SSLv3, TLS change cipher, Client hello (1):
* SSLv3, TLS handshake, Finished (20):
* SSLv3, TLS change cipher, Client hello (1):
* SSLv3, TLS handshake, Finished (20):
* SSL connection using ECDHE-RSA-AES128-GCM-SHA256
* Server certificate:
* 	 REDACTED
* 	 SSL certificate verify ok.
> POST /sandbox/v1/list HTTP/1.1
> User-Agent: curl/7.24.0
> Host: example.com
> Accept: */*
> Content-type: application/json; profile=http://example.com/list.json
> Content-Length: 31
> 
* upload completely sent off: 31 out of 31 bytes
< HTTP/1.1 200 OK
< Date: Wed, 29 Jul 2015 10:00:55 GMT
< Content-Type: application/json
< Content-Length: 75
< Connection: keep-alive
< Keep-Alive: timeout=240
< 
{
   "success": true
}
* Connection #0 to host example.com left intact
```

The error always points to `/home/vagrant/example/vendor/guzzlehttp/guzzle/src/Middleware.php` on `line 69`.

**Comment by mtdowling** [comment]
Based on our twitter conversation, you got this working. Should this issue be closed now?

**Comment by itsazzad** [comment]
I am also facing the similar error.
What was the twitter conversation?

**Comment by publiux** [comment]
Inquiring minds want to know how this was solved. I am having the problem and am racking my brain.

**Comment by mdavis1982** [comment]
I'm not at my machine right now but will update this issue tomorrow with what worked for me

**Comment by mdavis1982** [comment]
Okay, so here are the things that helped me to get this working.

The first thing to know is that the 400 Client Error is actually being returned from the server you are trying to connect to (in my case, at least). Initially I was under the impression that my request wasn't even hitting the destination server, but that wasn't the case. In order to see the actual response from the server, you need to do the following:

```php
try {
    $response = $client->send($request);
} catch (RequestException $e) {
    var_dump($e->getResponse()->getBody()->getContent());
}
```

This will show the actual error. For me, that was showing that the certificates and keys weren't being passed properly and that it was expecting a passphrase (that my private key didn't have). To rectify this bit, I added a passphrase to the private key, and specified it as follows:

```php
...
'ssl_key'  => [
    $config->get('private-key-path'),
    $config->get('private-key-pass'),
],
...
```

This got rid of the passphrase error. Even though it worked fine without a passphrase in the Terminal using cURL, it wouldn't work here without the key having a passphrase.

The next step I took was again guided by the error message I received. Essentially, it turned out that specifying the `verify` and `ssl_key` options alone wasn't enough, and I also needed to specify the `cert` key as well:

```php
$client = new \GuzzleHttp\Client([
    'base_uri' => $config->get('base-url'),
    'verify'   => $config->get('certificate-path'),
    'cert'     => $config->get('certificate-path'),
    'ssl_key'  => [
        $config->get('private-key-path'),
        $config->get('private-key-pass'),
    ],
    'headers'  => [
        'foo' => 'bar',
    ],
    'exceptions' => false
]);
```

As soon as I started doing this, the requests started to work and I could see that things were getting verified properly.

Hope this helps! Any more questions, just ask away!

**Comment by mdavis1982** [comment]
@mtdowling I'm happy for this issue to be closed now. I'm not sure why I had to specify a passphrase (is that a bug?) but regardless, this is all working fine now for me. Thanks for your help!

**Comment by mtdowling** [comment]
You would not have to specify a passphrase unless you actually have a passphrase... Here's the code for adding it via curl. I don't see any issue here: https://github.com/guzzle/guzzle/blob/master/src/Handler/CurlFactory.php#L385. I'll go ahead and close this.
