### ISSUE TITLE
Interface to classes to send them directly with guzzle

### ISSUE THREAD

**Issue by mikk150** [guzzle/guzzle#1204]
It would be nice if there exist some kind of interface, so that users could send objects directly through guzzle

so we would be able to do this
```php
class MyClass implements \GuzzleHttp\GuzzleSendable
{
	public function guzzleSend()
	{
		return [];
	}
}

$myVeryAwesomeObject=new MyClass;

$response = $client->post('http://httpbin.org/post', [
    'form_params' => $myVeryAwesomeObject
]);

```

**Comment by kkopachev** [comment]
You can pass any class, public properties will be used as form params.
Or you can make PSR-7 `Request` and send it through guzzle
