### ISSUE TITLE
Ability to use PHP_QUERY_RFC1738 for query params

### ISSUE THREAD

**Issue by kfuchs** [guzzle/guzzle#1208]
Currently the way the `query` params are url encoded is too opinionated (referring to [Client LN:351](https://github.com/guzzle/guzzle/blob/master/src/Client.php#L351)). 

There is no straight forward way to pass in query params utilizing `PHP_QUERY_RFC1738`.

One must `html_build_query()` them selves before hand, and then pass it in as a string instead of an array. This isn't extremely complicated, but it makes for guzzle a little clunkier to use, and when someone writes that line of code it will leave a future developer wondering why it is they build the query string instead of just passing it into guzzle as an array.

Perhaps instead there should be an option, like such:
`http_build_query($value, null, '&', $option['enc_type']);`

**Comment by kfuchs** [comment]
Made a pull request #1212 which fixes this.

It will still default to `PHP_QUERY_RFC3986` as the encode type. But now it can be changed via:

```php
$guzzle->get('...', [
			'enc_type' => PHP_QUERY_RFC1738
		]);
```

**Comment by mtdowling** [comment]
See https://github.com/guzzle/guzzle/issues/1196
