### ISSUE TITLE
Can't make pool requests

### ISSUE THREAD

**Issue by iamtommcc** [guzzle/guzzle#1209]
I'm attempting to make a big batch of async requests using Guzzle but I've been encountering some difficulties.

Here's my code below:
```php
$requests = [];
$results = [];

foreach ($options_response as $request_key => $request_block) {
  $requests[] = new Request('GET', 'contact-service' . $request_block);
}

$pool = new Pool($this->client, $requests, [
  'concurrency' => 20,
  'fulfilled' => function ($response, $index) use (&$results) {
  $results[] = $response;
  },
 ]);

$promise = $pool->promise();

$promise->wait();
```

Running this gives me this cryptic error:

```
Fatal error: Uncaught exception 'LogicException' with message 'The promise is already rejected.' in /var/www/public/wp-content/plugins/theplugin/vendor/guzzlehttp/promises/src/Promise.php:125
```

As this code hasn't been working & I've been struggling to figure out why, I've been using the below code, which works 100%... except for the fact that it doesn't seem to be working asynchronously (sometimes it takes 30+ seconds to execute if I'm making a lot of requests):

```php
    foreach ($options_response as $request_key => $request_block) {
      $promises[$request_key] = $this->client->getAsync('contact-service' . $request_block);
    }
    $results = Promise\unwrap($promises);
```
Any help or pointers would be greatly appreciated! I'm running this code on HHVM 5.6.99 if that's relevant.

**Comment by kamilsk** [comment]
Hi! Have you tried to run the same code on Zend Engine? I just see an open issue about support of HHVM (https://github.com/guzzle/guzzle/issues/538)

**Comment by mtdowling** [comment]
HHVM does not work correctly with coroutines in PHP. See https://github.com/facebook/hhvm/issues/1627.
