### ISSUE TITLE
Response containing string "0" behaves like an empty response

### ISSUE THREAD

**Issue by ciekawylogin** [guzzle/guzzle#1210]
If you create an instance of Response class (for example for testing purposes) and pass "0" (string containing only character "0") as $body parameter, it will behave as if you didn't pass this parameter (or passed just an empty string).

Example (using PHPUnit assertions):
````php
class GuzzleResponseTest extends \PHPUnit_Framework_TestCase
{
    public function test1() {

        $response = new Response(200, [], "0");

        $this->assertSame("",$response->getBody()->getContents()); // OK
        $this->assertSame("0", $response->getBody()->getContents()); // FAILS
    }
}
````

**Comment by Kevinrob** [comment]
This is because of the bad check in `GuzzleHttp\Psr7\Response`:
```php
if ($body) {
    $this->stream = stream_for($body);
}
```
And `(bool)"0" === false` .

If will do a pull request for fixing that.

**Comment by mtdowling** [comment]
Fixed in https://github.com/guzzle/psr7/pull/31
