### ISSUE TITLE
PHPUnit tests not working

### ISSUE THREAD

**Issue by mbbender** [guzzle/guzzle#1214]
A fresh clone of the project, then a composer install, then running phpunit results in:

PHP Fatal error:  Declaration of GuzzleHttp\Client::send() must be compatible with GuzzleHttp\ClientInterface::send(GuzzleHttp\Message\RequestInterface $request) in /Users/michael/Code/contrib/guzzle/src/Client.php on line 26

Fatal error: Declaration of GuzzleHttp\Client::send() must be compatible with GuzzleHttp\ClientInterface::send(GuzzleHttp\Message\RequestInterface $request) in /Users/michael/Code/contrib/guzzle/src/Client.php on line 26

Any additional information I can provide to help troubleshoot? Seems to only be a PHPUnit issue. If I create a client outside of PHPUnit seems to work fine.

**Comment by mbbender** [comment]
Closing as I don't believe this to be guzzle specific.

**Comment by mtdowling** [comment]
Maybe you have multiple versions of Guzzle somehow and they have different method signatures?

**Comment by mbbender** [comment]
@mtdowling Thanks, I updated the issue. As i found out more seems to be PHPUnit related?

**Comment by mbbender** [comment]
Hum.. seems to be a phpunit issue perhaps... I have 4.7.7 installed but when running with 4.8.3 (the one with your package) all works. Sorry to bother.

**Comment by poldixd** [comment]
@mbbender Hello, i have the same problem with **guzzlehttp/guzzle** and **phpunit/phpunit**... 

`Fatal error: Declaration of GuzzleHttp\Client::send() must be compatible with GuzzleHttp\ClientInterface::send(GuzzleHttp\Message\RequestInterface $request) in D:\WebDev\xampp\htdocs\is-client\system\modules\is-client\vendor\guzzlehttp\guzzle\src\Client.php on line 26`

I use `PHPUnit 5.2.9` and `guzzle 6.1.1`. I had tried different versions of the two packages, but i got still the same error. Do you have more informations about the problem? Or do you have a repo with the solution (Your last post of this topic)?

greetings
Nils

**Comment by mbbender** [comment]
@poldixd When I ensured the version of PHPUnit matched whatever was in the guzzle composer.json file it solved my issues. I didn't troubleshoot the issue any further as PHPUnit version change did not adversely affect my project. Sorry I couldn't be more help.
