### ISSUE TITLE
RetryMiddleware and Pool

### ISSUE THREAD

**Issue by ajacquelin** [guzzle/guzzle#1215]
Hello,
I have already implemented a pool with the help of "Concurrent requests" of http://docs.guzzlephp.org/en/latest/quickstart.html and it's working great!

Now I would like to use RetryMiddleware to retry automatically a failed request but I don't know how to do it. 
Can you give me some pointers  about how to do it ?

Great job! Cheers,

**Comment by mtdowling** [comment]
You need to create a "decider" function that returns true/false if a request should be retried. For example, you could return true if the HTTP response status code is 503: https://github.com/guzzle/guzzle/blob/master/src/RetryMiddleware.php#L22

After creating the decider, create the actual middleware: https://github.com/guzzle/guzzle/blob/master/src/Middleware.php#L167

You then attach the middleware to your handler stack before creating your client. See: http://docs.guzzlephp.org/en/latest/handlers-and-middleware.html#handlerstack

**Comment by ajacquelin** [comment]
Thanks you! I managed to do that and it's working :)
