### ISSUE TITLE
Can not upload file with data

### ISSUE THREAD

**Issue by iyourplus** [guzzle/guzzle#1222]
I want to upload a file with data parameter, but it do not work.

```php
$client->post('http://xxx/', [
    'json' => [
        'abc' => 'abc'
    ],
    'multipart' => [
        [
            'name'     => 'file',
            'contents' => fopen('xxx.sh', 'r')
        ]
    ],
]);
```
It only post `abc` parameter. And it only can post `file` when I delete json parameter.

**Comment by jeskew** [comment]
The json and multipart options are mutually incompatible. You can [send simple fields](http://docs.guzzlephp.org/en/latest/request-options.html#multipart) alongside the file in a multipart upload.

**Comment by iyourplus** [comment]
I want to upload file and post some data in one request, How can I do that?

**Comment by iyourplus** [comment]
I've solved this problem.Thanks so much.
