### ISSUE TITLE
Set default query param

### ISSUE THREAD

**Issue by gjuric** [guzzle/guzzle#1223]
In earlier versions it was possible to set a default query parameter and it looks like this options is gone from 6.

If I create a client by manually appeding the query param like this:

    $client = new Client([
        'base_uri' => 'http://example.com/api/?key=' . $apiKey,
    ];

The base_url, when converted to the UriInterface has an appropriate "query" set.

If I then want to do a request with a relative URI this query param gets overwritten here https://github.com/guzzle/psr7/blob/4ef919b0cf3b1989523138b60163bbcb7ba1ff7e/src/Uri.php#L154-L172 with this line:

    $parts['query'] = $relParts['query'];

**Comment by mtdowling** [comment]
You cannot do that any longer because we are strictly following the resolution rules of RFC 3986. However, you can provide default 'query' parameters that are added to every request.
