### ISSUE TITLE
Where has isSuccessful() gone?

### ISSUE THREAD

**Issue by mdavis1982** [guzzle/guzzle#1224]
It doesn't seem to be possible to now use `$response->isSuccessful()`. Why is that? And is there some other way to check for a successful response?

Thanks

**Comment by mtdowling** [comment]
Guzzle now uses PSR-7 messages directly which meant removing a few methods. You'll know if a request failed if an exception is thrown.

**Comment by mdavis1982** [comment]
@mtdowling Thanks for the clarification.
