### ISSUE TITLE
ClientInterface does not have shortcuts get(), post() etc.

### ISSUE THREAD

**Issue by Tobion** [guzzle/guzzle#1231]
The client implementation has the magic methods for `get` etc but the ClientInterface does not. So if you typehint against the interface, it's impossible to actually use them.
So I would propose to add them to the interface.

**Comment by jeskew** [comment]
By "impossible to actually use them," do you mean that IntelliJ autocomplete does not work as expected?

**Comment by Tobion** [comment]
it means you cannot rely on them being available. otherwise the whole interface makes no sense.

**Comment by mtdowling** [comment]
Those methods are really only there to make backwards compatibility easier for people who were already relying on a concrete class. Adding new methods to the interface right now would be a breaking change.

IMO, I don't really think the client needs that many methods. I think you should use other methods like `request` for creating and sending, and `send` to create a request that you already created.

**Comment by Tobion** [comment]
That's fine to me as well. But then the documentation needs to be updated to not use those methods. And they should be marked as deprecated, just for BC.
