### ISSUE TITLE
Change base URL of the client?

### ISSUE THREAD

**Issue by slavafomin** [guzzle/guzzle#1234]
Hello!

I'm injecting Guzzle client to one of my services and I want to set base URL from inside the service later on. However, it looks like base URL can only be specified when client is constructed. Is it intentional?

I would love to do `$client->setBaseUrl('...');`.

Otherwise I will have to construct all URLs manually inside my service, which is a bad thing, cause this functionality is already provided by Guzzle.

Thank you!

**Comment by mtdowling** [comment]
No this is not possible. The Client is immutable after creation. You'll need to create a new client if this behavior is desired.
