### ISSUE TITLE
form_params not accepting array

### ISSUE THREAD

**Issue by petyots** [guzzle/guzzle#1236]
I am using Guzzle 6 and I can't pass array with form_params in the body of the client

$postFields = 
[
form_params =>
[
'data[test]' => "TEST",
'data[whatever]' => "Whatever..."
]
];

$client = new GuzzleClient([
        'cookies' => $jar, // The cookie
        'allow_redirects' => true, // Max 5 Redirects
        'base_uri' => $this->navigateUrl, // Base Uri
        'headers' => $this->headers
    ]);
$response = $client->post('api',[$postFields]);
Finally, when i send the request my data is gone... But if I manually add the the data in the response it's working fine.

$response = $client->post('api',
[form_params => [
   'data[test]'=>"TEST",
   'data[wht]' => 'Whatever'
],
]
// It's working this way...
I hope I am clear enough if u need more info feel free to ask. Thanks in advance.

**Comment by mtdowling** [comment]
your'e not setting the parameters correctly. You have too many wrapping arrays.

```php
$client->post('/', [
    'form_params' => ['foo' => 'bar']
]);
```

See http://docs.guzzlephp.org/en/latest/request-options.html#form-params
