### ISSUE TITLE
Have the Response::json and Response::xml been removed

### ISSUE THREAD

**Issue by gmponos** [guzzle/guzzle#1238]
Are these two functions removed from Guzzle 6? If they are removed I can't find any reference to the Upgrading.md and to changelog.md. If they are not I can find any reference to the documentation.

**Comment by jeskew** [comment]
They were removed as part of the adoption of PSR-7.

**Comment by mtdowling** [comment]
These were removed, but you're right in that this was not called out in the upgrade guide. It should be documented there though.

**Comment by dragonwize** [comment]
The mention in the "upgrade" doc gives a reason for removal, which is nice but not required, but does not specify how to upgrade from the change.

Is the upgrade to now call getBody(), cast to a string, and pass to json_decode()?

**Comment by jeremeamia** [comment]
* json: `json_decode($response->getBody(), ...);`
* xml: `simplexml_load_string($response->getBody(), ...);`

**Comment by jeremeamia** [comment]
Full Guzzle 5 implementations of the `json` and `xml` functions: https://github.com/guzzle/guzzle/blob/f3c8c22471cb55475105c14769644a49c3262b93/src/Message/Response.php#L138-L183. These are a little more robust, but may handle more than what you actually need.

**Comment by kpcyrd** [comment]
I'd like to point out that this change might cause a regression to #418.
