### ISSUE TITLE
Pool throws misleading exception when the requests iterator doesn't give it anything

### ISSUE THREAD

**Issue by Thinkscape** [guzzle/guzzle#1239]
When the pool yielding function doesn't yield a single value, a misleading exception is thrown, i.e.:

````php
$doNothing = function() { 
  // trolololo
};
$pool = new Pool($client, $doNothing(), []);
$pool->promise()->wait();
````
Throws:

> GuzzleHttp\Promise\RejectionException
> The promise was rejected with reason: Invoking the wait callback did not resolve the promise

**Comment by mtdowling** [comment]
I think this is a bug in the promises library: https://github.com/guzzle/promises

**Comment by mtdowling** [comment]
Fixed in https://github.com/guzzle/promises/commit/4cdb3fb161cf740f3ff13aa9e3d1085e85b729a1
