### ISSUE TITLE
Next release date

### ISSUE THREAD

**Issue by jlestel** [guzzle/guzzle#1240]
Hi @mtdowling ,

When do you plan next release ?

I need your HHVM fixes in aws.phar :)

BR

**Comment by mtdowling** [comment]
From what I understand, the use of coroutines in the SDK means that the SDK cannot currently work on HHVM because HHVM does not support them.

**Comment by GrahamCampbell** [comment]
Do you need HHVM for hack, or for performance. PHP 7.0 is much faster than PHP 5.6 in most cases. I'd recommend checking that out once it's production ready.

**Comment by mtdowling** [comment]
I'd like the following PRs finished before the next release:

- https://github.com/guzzle/guzzle/pull/1183
- https://github.com/guzzle/guzzle/pull/1220
- https://github.com/guzzle/guzzle/pull/1202

**Comment by catch56** [comment]
We have about five issues blocking a release candidate of Drupal 8 at the moment, and one of them is blocked on getting onto a tagged release of Guzzle (we're currently pinned to https://github.com/guzzle/guzzle/commit/1879fbe853b0c64d109e369c7aeff09849e62d1e).

#1183 was opened by us, but for me personally I'd slightly prefer a new release without it if it ends up being the last blocker here.

**Comment by mtdowling** [comment]
#1202, but pending feedback. After it's merged, I'll tag 6.1.0.

**Comment by mtdowling** [comment]
6.1.0 will be released today, right after the Travis build passes: https://travis-ci.org/guzzle/guzzle/builds/79330099
