### ISSUE TITLE
Feature Request -- getContents function could be documented better. 

### ISSUE THREAD

**Issue by byustephen** [guzzle/guzzle#1241]
Michael, 

Thanks for building Guzzle. So far it's been great to use. 

My only difficulty so far is with the documentation. I had a hard time to get the real results from my post request. I could see that I could use the `getBody()` function, but had no idea how to get the real contents. Then I found a stackoverflow post, and it showed me that I have to chain the `getContents()` function. 

    print_r($response->getBody()->getContents());

I would expect the documentation would be a little more clear but to me it wasn't.

**Comment by mtdowling** [comment]
Yeah, there should probably be some mention of the body and how to use it in the quickstart: http://docs.guzzlephp.org/en/latest/quickstart.html#using-responses

You can just use the body of the response as a string-- e.g., `echo $response->getBody()` or `$body = (string) $response->getBody()`. Did you see the chapter on PSR-7? http://docs.guzzlephp.org/en/latest/psr7.html#streams

**Comment by byustephen** [comment]
Wow, you respond to posts quickly. 

I did see the streams section, but that section didn't exactly help. There is a 'stream' section under Request Options category, and it had this snippit of code:

    $body = $response->getBody(); 
    while (!$body->eof()) {
        echo $body->read(1024);
    }

Granted that works and is helpful, but it was hard to find and took a bit to figure out. 

Also, in the body section of the category titled 'Guzzle and PSR-7' there might be an issue. There is a code snippit that shows that if you run it, you'll get a json response. But i didn't get a json response when running it. Here's the snippit: 

    $response = GuzzleHttp\get('http://httpbin.org/get');
    echo $response->getBody();
    // JSON string: { ... }

Since this returns a stream object isn't this snippit technically wrong? I would think that either the comment line should say `// Stream object` or the echo line should say `echo $response->getBody()->getContents();`

What do you think?
