### ISSUE TITLE
PHP 7 Travis Issue

### ISSUE THREAD

**Issue by GrahamCampbell** [guzzle/guzzle#1248]
I've just noticed none of the tests are getting executed on php 7! Not sure what's going on here. https://travis-ci.org/guzzle/guzzle/jobs/79034820.

**Comment by mtdowling** [comment]
Weird. Maybe it's a travis bug.

**Comment by GrahamCampbell** [comment]
Yeh, I've seen it happening on lots of projects today. Just thought I'd let you know so you can keep an eye on it. I assume it'll be affecting the aws sdk too.

**Comment by GrahamCampbell** [comment]
I really wish phpunit would return non-zero status if no tests were executed.

**Comment by Kevinrob** [comment]
Same issue with my project too, I think is a travis bug.

**Comment by mtdowling** [comment]
Closing as this is not something we can fix here
