### ISSUE TITLE
Redirect loop fatal error

### ISSUE THREAD

**Issue by nsanden** [guzzle/guzzle#1251]
Hello! I'm using guzzle on many different URL's, some of which I don't know work or not.

This particular URL is producing a redirect loop
![untitled](https://cloud.githubusercontent.com/assets/2072064/9741404/304093e6-560f-11e5-80d9-f875cb3c38a2.png)

When using guzzle with it, im getting:
![infinite_loop](https://cloud.githubusercontent.com/assets/2072064/9741472/72794ca8-560f-11e5-94d0-3d922ce0fe0b.png)

Obviously I don't expect guzzle to be able to deal with a URL like that, but instead of a fatal error, can I try/catch it so my script can continue on to do work on the next URL?

**Comment by mtdowling** [comment]
I can't see the UR, I just see an image.

How do you know there is a redirect loop here? I see that your exception was that your script took longer than 120 seconds. If the error is just that your're doing too many things in a single request, then you need to increase your time limit: http://php.net/manual/en/function.set-time-limit.php

**Comment by nsanden** [comment]
Here is the URL: http://teespring.com/herolife

The timeout is definitely due to the redirect loop because if i switch out my script with a working url it finishes in just a couple seconds.

**Comment by nsanden** [comment]
Here are my curl settings
        $client->getClient()->setDefaultOption('config/curl/'.CURLOPT_TIMEOUT, 10);
        $client->http_client->getClient()->setDefaultOption('config/curl/'.CURLOPT_CONNECTTIMEOUT, 5);
        $client->http_client->getClient()->setDefaultOption('config/curl/'.CURLOPT_MAXREDIRS, 10);

I just now added the CURLOPT_MAXREDIRS just to see if that would fix it but it doesn't seem to.

**Comment by nsanden** [comment]
Reproducible example
```php
        $client = new \Goutte\Client();
        $client->getClient()->setDefaultOption('config/curl/'.CURLOPT_TIMEOUT, 10);
        $client->getClient()->setDefaultOption('config/curl/'.CURLOPT_CONNECTTIMEOUT, 5);
        $client->request('GET', 'http://teespring.com/herolife');
```

this however works fine
```php
        $client = new \Goutte\Client();
        $client->getClient()->setDefaultOption('config/curl/'.CURLOPT_TIMEOUT, 10);
        $client->getClient()->setDefaultOption('config/curl/'.CURLOPT_CONNECTTIMEOUT, 5);
        $client->request('GET', 'http://teespring.com/papa-the-man');
```

Need some way of catching that infinite loop :(

**Comment by mtdowling** [comment]
Ah I see. Goutte disables Guzzle redirects and handles redirects in it's library. You'll need to open this issue with Goutte to have it resolved.

See: https://github.com/FriendsOfPHP/Goutte/blob/master/Goutte/Client.php#L106

**Comment by nsanden** [comment]
Ah thanks. Confirmed:
```php
        $client = new \GuzzleHttp\Client();
        $res = $client->get('http://teespring.com/herolife');
```

GuzzleHttp\Exception\TooManyRedirectsException

Will not follow more than 6 redirects

**Comment by atefBB** [comment]
Hey @nsanden How did you solve this issue?

**Comment by nsanden** [comment]
@atefBB - https://github.com/FriendsOfPHP/Goutte/issues/237

**Comment by atefBB** [comment]
@nsanden thx !
