### ISSUE TITLE
Is trailing slash a must for base_uri?

### ISSUE THREAD

**Issue by g-p-c-s** [guzzle/guzzle#1254]
Is trailing slash a must for base_uri? All requests fail with a 404 whenever base_uri doesn't end with a '/'
Not sure if PSR7 specifies base_uri to be so.

**Comment by GrahamCampbell** [comment]
Yes, it is.

**Comment by GrahamCampbell** [comment]
See http://tools.ietf.org/html/rfc3986#section-5.2.

**Comment by g-p-c-s** [comment]
Client wouldn't  add one if a trailing slash is missing?

**Comment by GrahamCampbell** [comment]
Why should it?

**Comment by GrahamCampbell** [comment]
I don;t understand what you;re saying?

**Comment by GrahamCampbell** [comment]
If your base url is http://foo.bar/baz, then you request bar, then guzzle will hit http://foo.bar/bar.

**Comment by GrahamCampbell** [comment]
If it's http://foo.bar/baz/, then http://foo.bar/baz/bar.

**Comment by g-p-c-s** [comment]
Right. So, if `base_uri` is http://foo.bar/baz, then a request is made to bar1, I though guzzle would make it http://foo.bar/baz/bar1

**Comment by GrahamCampbell** [comment]
>  I though guzzle would make it http://foo.bar/baz/bar1

Not, it doesn't. I'll use http://foo.bar/bar1.

**Comment by g-p-c-s** [comment]
Thanks for the clarification.
