### ISSUE TITLE
getContents could seek pointer back

### ISSUE THREAD

**Issue by renatomefidf** [guzzle/guzzle#1255]
Hello,

I was into a issue trying to understand why I couldn't getContents multiple times, after checking its a stream I did a seek(0) and it was all fine.
But the code gets dirty and since I'm using getContents its expected for me to get the entire content of the body, it would be nice for this feature to set the pointer back to 0.

Is this a viable option or we do have limitations by PSR-7 or some compatibility?

Thanks

**Comment by mtdowling** [comment]
We have to follow PSR-7 compat here, so this is not something that we can do.

**Comment by coolhome** [comment]
@renatomefidf If you don't care about how the http body is transferred into memory you can simply just cast the StreamInterface to a string.

e.g.

```php
var_dump(strval($response->getBody())); // Explicit 
var_dump((string) $response->getBody()); // Implicit
```
