### ISSUE TITLE
verify = FALSE with StreamHandler still results in certificate verification. Probably, ['ssl']['verify_peer_name'] should be set to FALSE as well

### ISSUE THREAD

**Issue by drscre** [guzzle/guzzle#1256]
I am using StreamHandler to make an https request with `verify = FALSE` option.
But I still get "Peer certificate CN=... did not match expected CN=..." error.

I managed to fix this by adding `['stream_context']['ssl']['verify_peer_name'] = FALSE`

Probably, we should add 
`$options['ssl']['verify_peer_name'] = false;`
 to [StreamHandler::add_verify()](https://github.com/guzzle/guzzle/blob/master/src/Handler/StreamHandler.php#L361)

**Comment by mtdowling** [comment]
Sounds good. Could be added around here: https://github.com/guzzle/guzzle/blob/master/src/Handler/StreamHandler.php#L361
