### ISSUE TITLE
how to handle multiple json  strings ?

### ISSUE THREAD

**Issue by mortenko** [guzzle/guzzle#1264]
Hi Im sending multiple GET request using GuzzleHttp\Pool. The response is multiple json string. 
When I use 
$  'fulfilled' => function ($response, $index) {
        $body=$response->getBody();
.......
the variable $body contains mutliple json string in invalid format like this:
{
 "channel": {
    },
    "feeds": [   ]

}
{
 "channel": {
    },
    "feeds": [   ]
}
......
I know why is invalid because the  parentheses. How Can I handle this ?

 Thanks for answer

**Comment by mtdowling** [comment]
This is not an issue with Guzzle, so you should ask this on something like StackOverflow. What you are asking about is how to parse an invalid JSON document. You might need to write your own parser. I suggest contacting the API vendor to let them know their response contains invalid JSON.
