### ISSUE TITLE
'forward_headers' request option to forward headers when following redirects

### ISSUE THREAD

**Issue by insprintorob** [guzzle/guzzle#1272]
I think it would be useful to have a 'forward_headers' request option that would cause Guzzle to forward the request headers specified with the 'headers' option when following redirects.

The use case I have for this at the moment is making a request to a service that requires a secret header to allow me through, but then redirects guzzle to another url, doesn't see the header and then throws a 401 unauthorized error.

For now, i'll use a workaround by disabling redirects and handling the redirect myself manually.

**Comment by mtdowling** [comment]
I think this feature request is too specific, but I'll reconsider if this issue is upvoted.

Guzzle will pass along all headers when redirecting except for the Authorization header if the Host changes in the redirect. Are you trying to pass along an Authorization header?

**Comment by leonboot** [comment]
I'm running into this very issue right now. I'm sending an authenticated OAuth2 request to the Nest developer API (developer-api.nest.com). This URL responds with a 307 redirect to, for instance, firebase-apiserver01-tah01-iad01.dapi.production.nest.com. Since the `Authorization` header is not passed, this results in a '401 Unauthorized' response.

**Comment by peterfox** [comment]
It's happening to me the same as @leonboot, using the Nest API and it does a 307 redirect but fails because the auth headers don't get redirected when following the request. Kind of a pain there's not something for it.

**Comment by ondrej-bouda** [comment]
Although security concerns are relevant, I would really appreciate the possibility to either disable this feature, or at least pass a whitelist for exceptions.
