### ISSUE TITLE
Test server is not distributed via composer

### ISSUE THREAD

**Issue by pkruithof** [guzzle/guzzle#1274]
The gitattributes file removes the entire tests folder, which also contains the [test server](http://guzzle.readthedocs.org/en/latest/testing.html#test-web-server). This way only the Guzzle repo itself can use it. Can this be excluded from the attributes file?

**Comment by pkruithof** [comment]
ping @mtdowling

**Comment by jeskew** [comment]
Couldn't you get those assets by installing with `--prefer-source`?

Even if the tests are pulled down, they are not added to the autoloader of the project depending on Guzzle. The tests folder is part of Guzzle's [`autoload-dev`](https://github.com/guzzle/guzzle/blob/62cd40c2bbbd67dc04749e029355efccdc538d1c/composer.json#L31) declaration.

**Comment by mtdowling** [comment]
Yeah, it really wouldn't help considering the test server controller class would not be autoloaded or downloaded. My try giving `--prefer-source` ` a shot.

**Comment by mtdowling** [comment]
I think vendoring the test server makes sense if you're building a new HTTP handler or something that actually needs the networking layer tested. However, for libraries that are just using an existing handler, there's no need to use the test server.

**Comment by pkruithof** [comment]
I use it for functional tests in a library that uses Guzzle as the HTTP client. I find it very useful to write these tests with. It's not that far fetched for a HTTP client to ship a test client for incorporating libraries, in my opinion. Hope you'll reconsider.
