### ISSUE TITLE
When using pool, didn't get origin index from fulfilled/rejected callback

### ISSUE THREAD

**Issue by lessmind** [guzzle/guzzle#1275]
Hi, I made a generator to provide requests for my `GuzzleHttp\Pool`, and I used the `yield $key => $request` syntax, so I can tell which request I'm dealing with by the `$index` parameter in later callback.

But I can only get a numerical index from the `$index` parameter, is this a bug?

Or I supposed to use these numerical indexes to tell which request is it?
(If so, are these indexes strictly follow the order from the generator?)

I made a quick example below (altered from [here](http://docs.guzzlephp.org/en/latest/quickstart.html#concurrent-requests))

```php
use GuzzleHttp\Pool;
use GuzzleHttp\Client;
use GuzzleHttp\Psr7\Request;


$client = new Client();
$requests = function ($keys) {
    $uri = 'http://example.com/';
    foreach($keys as $k) {
        yield $k => new Request('GET', $uri);
    }
};

$pool = new Pool($client, $requests(['a', 'b', 'c', 'd', 'e', 'f', 'g']), [
    'concurrency' => 5,
    'fulfilled' => function ($response, $index) {
    	echo "fulfilled index:{$index}<br>";
    },
    'rejected' => function ($reason, $index) {
    	echo "rejected index:{$index}<br>";
        // this is delivered each failed request
    },
]);

// Initiate the transfers and create a promise
$promise = $pool->promise();

// Force the pool of requests to complete.
$promise->wait();
```
And here's my output:
```
fulfilled index:2
fulfilled index:1
fulfilled index:4
fulfilled index:3
fulfilled index:0
fulfilled index:5
fulfilled index:6
```

I was expected:
```
fulfilled index:c
fulfilled index:b
fulfilled index:e
fulfilled index:d
fulfilled index:a
fulfilled index:f
fulfilled index:g
```

**Comment by mtdowling** [comment]
Fixed by https://github.com/guzzle/guzzle/pull/1203
