### ISSUE TITLE
Is this a memory leak in Guzzle middleware?

### ISSUE THREAD

**Issue by suvozit** [guzzle/guzzle#1279]
Does the following output shows a memory leak?
My worker server is running out of memory. Although its a stable allocation but its not freeing up the memory after the execution.

Here is the issue https://github.com/guzzle/oauth-subscriber/issues/47#issuecomment-148480943

```php
use GuzzleHttp\HandlerStack;
use GuzzleHttp\Subscriber\Oauth\Oauth1;

function stack_it()
{
  $stack = HandlerStack::create();

  $middleware = new Oauth1([
    'consumer_key'    => NULL,
    'consumer_secret' => NULL,
    'token'           => NULL,
    'token_secret'    => NULL,
  ]);
  $stack->push($middleware, 'oauth_1');

  $stack->remove('oauth_1');
}

echo 'initial: '.memory_get_usage().PHP_EOL;
for ($i=0; $i < 20; $i++)
{
  $this->stack_it();

  gc_collect_cycles();
  echo memory_get_usage().PHP_EOL;
}

die();
```

**Output**
```
initial: 3818976
4282040
4282040
4282040
4282040
...
4282040
4282040
4282040
4282040
```

**Comment by jeskew** [comment]
A certain amount of memory will be consumed by the PHP runtime as it loads and parses class definitions. As the memory usage is stable after the first loop iteration in the example provided, that explanation would fit the data provided, though I would need to run a full profile to say that with certainty.

That said, it looks like the memory that can't be reclaimed is a stable ~400KB. Is that what's causing your server to crash?

**Comment by suvozit** [comment]
I am running a cronjob in CodeIgniter and killing it after 10mins to reset the memory but it still fills the memory and causing server to crash. How can I run a full profile?

**Comment by jeskew** [comment]
I like [blackfire.io](https://blackfire.io/) but other options include [XDebug](http://www.xdebug.org/docs/profiler) and [New Relic](http://newrelic.com/sp/php-monitoring).

**Comment by Tobion** [comment]
The above test script makes no sense to me and cannot show a memory leak in guzzle itself.
The `$stack` variable is local to the `stack_it` function. And you collect memory outside the function. So PHP should always be able to free the memory that is only used locally.

**Comment by mtdowling** [comment]
Agreed. This is not a memory leak or an issue in Guzzle.
