### ISSUE TITLE
cURL error 6: Could not resolve host

### ISSUE THREAD

**Issue by SharkIng** [guzzle/guzzle#1280]
One of the project using GuzzleHttp to handle the Http request but I do not know for whatever reason that cURL error jump out on certain environment.

Any idea how to test it and solve it?

**Comment by mtdowling** [comment]
It depends... If it happens consistently, then there's a networking problem with your server or with the remote server. If it happens periodically, then there's still a networking error somewhere, but you could try retrying the request to work around the issue. See https://github.com/guzzle/guzzle/blob/master/src/RetryMiddleware.php

**Comment by SharkIng** [comment]
I have found the issue.

It is because the cURL PHP library its not install currectly. Thanks anyway.

**Comment by torinaki** [comment]
@SharkIng can you please share the knowledge what exactly was incorrectly?
