### ISSUE TITLE
Proper way of posting an XML string?

### ISSUE THREAD

**Issue by panelo** [guzzle/guzzle#1283]
I'm using laravel 5 and guzzle 5.0. Can't seem to make XML work (POST). Am I doing it right?

    $xml = new \SimpleXMLElement('<?xml version="1.0" encoding="utf-8"?><request></request>');
    $xml->addChild('username', 'user');
    $xml->addChild('password', 'pass');
    $xml->addChild('field', 'test');
    $xml = $xml->asXML();

    $client = new Client(); 
    $request = $client->createRequest('POST','https://thisistheurl', array(
         'body' => array(
	         'file_filed' => $xml
         ),
         'cookies' => true
     ));
    $response = $client->send($request);

**Comment by mtdowling** [comment]
So if you're sending a POST request with an XML body, then there's no need to wrap the 'body' param in an array. Just pass it in as a string.
