### ISSUE TITLE
Limit HTTP Respose

### ISSUE THREAD

**Issue by code403** [guzzle/guzzle#1289]
Hello, I noticed that guzzle don't have any function that can limit the http request response body for a specific limit and after that limit terminate the request, even though that can be done with cURL so please add it

**Comment by mtdowling** [comment]
I'm not sure this is necessary. This could be achieved using a stream decorator on the response body to fail after a certain amount of data is written, or you could simply send a Range HTTP header with your request.

**Comment by code403** [comment]
It's necessary I need it, explain how to do it the stream decorator thing, and I tried the range header with the request I am making but it didn't work so I need the limit thing

**Comment by mtdowling** [comment]
What do you mean when you say the Range header didn't work? What header did you send and what was the response? Can you post the debug output? See: http://docs.guzzlephp.org/en/latest/request-options.html#debug

**Comment by mtdowling** [comment]
You could create an FnStream and provide it to the `sink` option of a request. When creating the FnStream, you would provide a function that decorates the `write` function. You would the throw if the size of data in the stream exceeds your limit.

See https://github.com/guzzle/psr7#fnstream for an example. You might also find the FnStream tests useful for reference https://github.com/guzzle/psr7/blob/master/tests/FnStreamTest.php
