### ISSUE TITLE
Release v6.1.1

### ISSUE THREAD

**Issue by shadowhand** [guzzle/guzzle#1291]
Can we have a 6.1.1 tag please? There are a [number of fixes](https://github.com/guzzle/guzzle/compare/6.1.0...master) that would be useful to have.

**Comment by shadowhand** [comment]
Ping?

**Comment by mtdowling** [comment]
I'll try to slice some time out this weekend for a release.

**Comment by mtdowling** [comment]
6.1.1 has been released... Sorry for the delay :person_frowning:
