### ISSUE TITLE
cURL error 6: Could not resolve host

### ISSUE THREAD

**Issue by newtonianb** [guzzle/guzzle#1293]
I have a PHP Application (using laravel) that I setup on homestead (vagrant) at ``my.app`` Within this laravel app I installed the ''guzzle client library'' https://github.com/guzzle/guzzle.

I now developed a laravel command script that uses guzzle to send API requests to various API endpoints at ``my.app``

The problem I keep getting error ``cURL error 6: Could not resolve host``

It looks like something is funky with the host through vagrant. I tried to debug through the library but didn't gain much. How can I debug this more?

I am on Windows 8.1

https://github.com/mitchellh/vagrant/issues/6465

**Comment by Kevinrob** [comment]
It's not related to Guzzle. (see #1280)
`cURL` is a full program on your system and apparently the DNS are misconfigured for it.

**Comment by mtdowling** [comment]
Closing as @Kevinrob is correct.
