### ISSUE TITLE
Passing a host header does not seem to work?

### ISSUE THREAD

**Issue by fruitl00p** [guzzle/guzzle#1297]
We hit an IP and pass a custom HOST header into the request:
```php
  $client = new \GuzzleHttp\Client([
            'base_uri' => 'http://127.0.0.1',
            'headers' => [
              'Host' => 'mycoolsite.com'
            ]
        ]);
```
But the HOST header doesnt seem to work? Am i doing it wrong? :)
(this used to work in Guzzle4)

**Comment by mtdowling** [comment]
Is this Guzzle 6? How are you creating and sending the request?

**Comment by fruitl00p** [comment]
We're using the latest release (as gotten from composer) and the request is as the following:
```php
$client = new \GuzzleHttp\Client([
    'base_uri' => 'http://127.0.0.1',
    'headers' => [
        'Host' => 'mycoolsite.com'
    ]
]);
$response = $client->get('/test');
```

This wil hit the correct URL but due to the fact that the HOST header seems to be missing, my virtualhost doesnt seem to get hit...?

**Comment by AubreyHewes** [comment]
In Guzzle6 you can do this by building your own Request: 
```php
$request = new \GuzzleHttp\Psr7\Request('GET', 'http:/127.0.0.1/', [
  'Host' => 'mycoolsite.com'
]);
$response = (new GuzzleHttp\Client())->send($request, ['debug' => true]);
```
In the debug output you will see the Host header has been set correctly... ;-)

**Comment by fruitl00p** [comment]
@AubreyHewes That would work, but I expected setting the extra header on a (shared) client so that all requests would have that new host header automatically.

**Comment by fruitl00p** [comment]
@mtdowling @AubreyHewes We've located the culprit / origin of the issue which should be able to be illustrated via the following:
```php
$ip = '127.0.0.1';
$host = 'mycoolhost.com';
$path = '/some/path/to/file.html';

$client = new \GuzzleHttp\Client([
	'base_uri' => 'http://'.$ip,
	'debug' => true,
	'headers' => [
		'Host' => $host,
	],
]);

$responseWhichDoesWork = $client->get($path, ['headers' => ['Host'=>$host]]);
/**
 * seems that the 'moving' of the headers into '_conditional' options, creating the request (with the wrong host) 
 * and later checking if the (host)header is already set, which it is, 
 * causes the (correct) host header to be skipped. This then results in a wrong request
 * (or atleaast a request with the IP host header and not the name)
 */
$responseDoesNotWork = $client->get($path);
```

Guzzle version 6.1.0

My thoughts are that the order of events between parsing the options into the `conditional`, creating the request object and actually executing it are clashing... (along with the check that the header might already be [set](https://github.com/guzzle/guzzle/blob/master/src/Client.php#L377)

Hope this helps!

**Comment by mtdowling** [comment]
Fixed

**Comment by amiri27** [comment]
@mtdowling We have the same problem after updating to 6.2.1. There's no problem with guzzle 6.2 at all but same problem exists after updating to 6.2.1

Regards,

**Comment by simonhamp** [comment]
I can confirm that this is *still* an issue in 6.3.0 👎

**Comment by sagikazarmark** [comment]
Regarding the default Host header see the issue linked above. If the explanations/solutions provided there don't work, please open an issue with some context about what you are trying to achieve. Thanks.

**Comment by Wythehard** [comment]
$client = new \GuzzleHttp\Client([
    'base_uri' => 'http://'.$ip,
    'debug' => true,
    'headers' => [
        'Host' => $host,
    ],
]);

Notice: Host is contained in headers array

**Comment by nolway** [comment]
Still reproduce in 2023

**Comment by MGDSoft** [comment]
@nolway it's solved using proxy

```php
new Client([
    'base_uri' => 'http://yourdomain.com',
    'proxy' => 'http://127.0.0.1:80',
]);
```
