### ISSUE TITLE
Error 501 - Method Not Implemented

### ISSUE THREAD

**Issue by danelsan** [guzzle/guzzle#1300]
Into one server, when I sent the request with guzzle I had this response
Error 501 - Method Not Implemented

I sent a GET request with posts variable and I saw that if I remove the header
Transfer-Encoding: chunked
the response is correct.

How I can remove this header or I can add some header for remove this problem?

**Comment by mtdowling** [comment]
A GET request should pretty much never send a body. Adding a body or Transfer-Encoding headers to a GET request is probably tripping up your server.
