### ISSUE TITLE
403 Error in Guzzle, Ok in Browser

### ISSUE THREAD

**Issue by ap4125** [guzzle/guzzle#1311]
Hi. I don't know what to make of this, but I've encountered a situation where I get a 403 in Guzzle but I can access it just fine in any browser. The url I'm trying to access is http://realpassiveincomeideas.com. I'm calling Guzzle with the simplest GET call and I keep getting 403. Any ideas? Thanks!

**Comment by jeskew** [comment]
The request is getting blocked by something called "Sucuri WebSite Firewall," which seems to intentionally block non-browser traffic. This is not an issue with Guzzle; I would recommend reaching out to the website owners for more information.

**Comment by mallardduck** [comment]
While this is totally an issue with Sucuri overall there are ways to fix the issue on PHP side. You can simply just set the following configs:

```
          'referer' => true,
          'headers' => [
            'User-Agent' => 'Liquid Web KB Footer Nav Sync Tool/v1.0',
            'Accept' => 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8',
            'Accept-Encoding' => 'gzip, deflate, br',
          ],
```

**Comment by mmuhd** [comment]
Thank you @mallardduck  you saved my day.

**Comment by matheusgontijo** [comment]
I had the very same issue with Sucuri.

In order to fix the issue I changed the `User-Agent` from default `GuzzleHttp/6.5.0 curl/7.65.3 PHP/7.3.11-0ubuntu0.19.10.4` to my current curl version: `curl/7.65.3`. Example:

```
$client = new \GuzzleHttp\Client([
    'headers' => [
        // ...
        'User-Agent'   => 'curl/7.65.3',
    ],
]);
```

**Comment by allanzi** [comment]
I've same error here, but `User-Agent` header doesn't work

#2832

**Comment by mallardduck** [comment]
@allanzi - in the example's from your issue you don't show that you set `User-Agent`.

As stated here this wasn't a Guzzle issue but a matter of how the web-server (in this case a web proxy) is configured to handle varying requests. you as the consumer of the API/HTTP/etc must be responsible for configuring your HTTP client in a manner compatible and compliant with the HTTP server's settings.

**Comment by allanzi** [comment]
Finally found solution. If had a body in the GET request the Cloudfront will return 403.

So in my case the problem is this if (always setting a body):
```php
       if ($isMultipart) {
            $params['multipart'] = [$body];
        } else {
            $params['json'] = $body;
        }
```

[Here link of Cloudfront docs](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/RequestAndResponseBehaviorCustomOrigin.html)
![image](https://user-images.githubusercontent.com/11529597/102903664-686cd480-444f-11eb-9ecf-39ceb697518a.png)

**Comment by allanzi** [comment]
Thanks a lot @mallardduck for your help

**Comment by syamsoul** [comment]
> I had the very same issue with Sucuri.
> 
> In order to fix the issue I changed the `User-Agent` from default `GuzzleHttp/6.5.0 curl/7.65.3 PHP/7.3.11-0ubuntu0.19.10.4` to my current curl version: `curl/7.65.3`. Example:
> 
> ```
> $client = new \GuzzleHttp\Client([
>     'headers' => [
>         // ...
>         'User-Agent'   => 'curl/7.65.3',
>     ],
> ]);
> ```

this solution is working....

but why??? is there any other solution to allow request from GuzzleHttp???

**Comment by elanclarkson** [comment]
Started getting the issue mentioned here, so have removed 'br' from the accepted encodings to fix it.

https://github.com/guzzle/guzzle/issues/2146
