### ISSUE TITLE
How to use curl_file_create in post body in guzzle 6

### ISSUE THREAD

**Issue by wppd** [guzzle/guzzle#1314]
Let me just show the code to you.

        $username = 'xxx';
        $password = 'xxx';
        $request_uri = "https://www.xxx.com";

        $upload_file = __DIR__.'/test.tar.gz';
        $destination_dir = "public_html";

        $cf = curl_file_create($upload_file);

        $payload = array(
            'dir'    => urlencode( $destination_dir ),
            'file-1' => $cf
        );
    
    
        //raw CURL working
        $ch = curl_init( $request_uri );
        curl_setopt( $ch, CURLOPT_HTTPAUTH, CURLAUTH_BASIC );
        curl_setopt( $ch, CURLOPT_USERPWD, $username . ':' . $password );
        curl_setopt( $ch, CURLOPT_SSL_VERIFYHOST, false );
        curl_setopt( $ch, CURLOPT_SSL_VERIFYPEER, false );
        curl_setopt( $ch, CURLOPT_POST, true );
        curl_setopt( $ch, CURLOPT_POSTFIELDS, $payload );
        curl_setopt( $ch, CURLOPT_RETURNTRANSFER, true );
        $curl_response = curl_exec( $ch );
        curl_close( $ch );

        //Not working
        $client = new GuzzleHttp\Client();
        $res = $client->request('POST', $request_uri, [
            'auth' => [$username, $password],
            'form_params' => $payload,
            'verify' => false,
        ]);

**Comment by mtdowling** [comment]
You need to use the multipart option: http://docs.guzzlephp.org/en/latest/request-options.html#multipart

**Comment by wppd** [comment]
@mtdowling thanks for your response.

`multipart cannot be used with the form_params option. You will need to use one or the other. `

but the thing is it requires an extra param: `dir` which has to be one of `form_params`

**Comment by mtdowling** [comment]
Take a look at the example I linked to. You use multipart for all of the files and fields of your form. You don't use form_params here.

**Comment by wppd** [comment]
@mtdowling 
sorry man, I think I wasn't being clear enough.  

two params: `file-1` and `dir`

The `file-1` is supposed to be a CURLFile instance while 'dir'  is just an ordinary `string`.

I've checked out `Psr7/MultipartStream`

`$element['contents'] = stream_for($element['contents'])`

but just as I said before, the `dir` is just an ordinary string. it's not a file.

here is what I'm trying to archive:

https://documentation.cpanel.net/display/SDK/Tutorial+-+Use+UAPI%27s+Fileman%3A%3Aupload_files+Function+in+Custom+Code
