### ISSUE TITLE
Promise onRejected replace response

### ISSUE THREAD

**Issue by EAnushan** [guzzle/guzzle#1322]
I'm trying to intercept 401 Unauthorized status codes so that I can perform an authentication request before retrying the request as shown below.

```
function sendMyRequest(RequestInterface $request, array $options = [])
{
    $promise = $this->client->sendAsync($request, $options);

    $promise->then(null, function (RequestException $e) use ($request, $options) {
        if ($e instanceof BadResponseException && $e->getResponse()->getStatusCode() == '401') {
            // Authentication error, authenticate again and retry, session may have expired.
            $this->authenticate();

            return $this->client->sendAsync($request, $options);
        }
    });

    return $promise;
}
```

The authenticate() method executes a separate request, which populates the cookie jar with the required session cookies. I then re-run the original request, which now succeeds as expected.

The problem I'm running into is that the caller of the function always receives the original 401 response, instead of the new 200 OK response that I'm returning inside the onRejected callback. Is there any way to replace the response returned when calling ```$promise->wait()```?

As far as I can tell, chained handlers work as expected, as shown on the docs at https://github.com/guzzle/promises#rejection-forwarding

**Comment by jeskew** [comment]
I think you want to return the promise generated by calling `->then()` rather than the original promise. Does everything work as expected if you return the result of the second line of the `sendMyRequest` function instead?

**Comment by EAnushan** [comment]
I didn't investigate further until today, but it looks like you're right. A new instance of Promise is returned, and that version should be sent back. Thank you!

**Comment by mtdowling** [comment]
Yeah, you'll need to chain the promises together and return the last promise in the chain in order to ultimately resolve to a different response. You can see an example of this in Guzzle's retry middleware: https://github.com/guzzle/guzzle/blob/master/src/RetryMiddleware.php
