### ISSUE TITLE
How to do session handling with middleware?

### ISSUE THREAD

**Issue by TravisCarden** [guzzle/guzzle#1323]
@mtdowling, in your SymfonyLive Portland 2013 session [Building web service clients with Guzzle](http://portland2013.live.symfony.com/speakers#session-761) you had [a slide](https://www.youtube.com/watch?v=LHDrhJktDoE&feature=youtu.be&t=17m14s) with an example of using event listeners to transparently manage token-based authentication. The example looks great, but my project uses Guzzle 6, which means I need to use middleware instead. I'm reading the [Migrating to Middleware Upgrade Guide instructions](https://github.com/guzzle/guzzle/blob/master/UPGRADING.md#migrating-to-middleware), but this is all very new territory to me (this being my very first use of Guzzle) and I can't quite put the pieces together. Could you explain how to intercept a response exception in the new paradigm or recommend a resource that could help me toward my goal of seamless token-based authentication management? Thanks so much!

**Comment by EAnushan** [comment]
Here's a short example. Use the mapRequest middleware to modify your requests before they go out. Here I'm adding a header, but you can just as well add it as a query parameter using a similar method call on ```$request```.

```
// Modify request.
$this->config['handler']->unshift(Middleware::mapRequest(function (RequestInterface $request) {
    // Add token parameter to all requests.
    $request = $request->withHeader('token', $this->token);

    return $request;
}), 'mapRequestMiddleware');
```

Where do you get $this->token? If it's an API token, then you'll have to provide it yourself.If your token is a CSRF token, you'll have to retrieve the CSRF token separately.
```
// Save token.
$this->config['handler']->unshift(Middleware::tap(null, function (RequestInterface $request, array $options, PromiseInterface $response) {
    if ($this->isAuthenticateRequest($request)) {
        $response->then(function (ResponseInterface $response) {
            // Save token from authenticate request.
            $this->token = $response->getBody()->getContents();
        });
    }

    return $response;
}), 'tapTokenMiddleware');
```

And there you have it. If you want to maintain session using something like a cookie jar, see https://github.com/guzzle/guzzle/tree/master/src/Cookie

**Comment by TravisCarden** [comment]
Thanks, @EAnushan! I'll give this a try.
