### ISSUE TITLE
Chunking file uploads in StreamHandler?

### ISSUE THREAD

**Issue by jamiehannaford** [guzzle/guzzle#1329]
For users without cURL installed and therefore rely on the `StreamHandler`, is there support for large objects? I'm getting memory limit problems because of [this line](https://github.com/guzzle/guzzle/blob/master/src/Handler/StreamHandler.php#L308) since it's loading the request body into memory. 

This is more of a general question, but can PHP's default HTTP stream context handle chunking? Something [like this](http://stackoverflow.com/a/12167426/427992) might work.

**Comment by mtdowling** [comment]
This is not possible with the PHP stream handler. It has to load the entire payload into memory unfortunately.

The link you provided uses raw sockets, which would work, but Guzzle does not have a built-in raw socket based adapter. Guzzle has built-in curl and PHP stream handlers. Writing an adapter using raw sockets and hooking it up to Guzzle is certainly possible, but not something that I think would end up in the core Guzzle library.
