### ISSUE TITLE
Sending requests with empty body ends up sending Transfer-Encoding: chunked

### ISSUE THREAD

**Issue by pdziok** [guzzle/guzzle#1330]
I found an issue while sending GET requests. Each one of them ends up sending `Transfer-Encoding: chunked` header even though it's not strictly defined in the headers list. This is caused by setting `CURLOPT_UPLOAD` for every request that have null (unknown) long body. This is set in there: https://github.com/guzzle/guzzle/blob/master/src/Handler/CurlFactory.php#L262

This is causing some varnish problems (https://www.varnish-cache.org/trac/ticket/909) and I'd like to minimise usage of that header if it is not necessary.

I'd like to send a PR for that but I'm not sure if adding this field should be determined by request method or something else.

Wrapping that with 
```php
if ($request->getMethod() != 'GET')
```
helps in my case, but there are other methods that supposedly shouldn't send request body. Adding additional condition before calling `\GuzzleHttp\Handler\CurlFactory::applyBody` also seems like an idea.

**Comment by mtdowling** [comment]
GET requests can technically be sent with a body. I don't want to remove this ability just in case there are strange use cases out there where sending a body is necessary.

You'll need to not add a body to requests that you don't want to have transfer-encoding headers.

**Comment by jjmontgo** [comment]
Hi pdziok:

I'm having the same or very similar issue with guzzle.  Some of the components I use rely on guzzle under the hood, and are resulting in Varnish 503 errors if called from apache and not the command line.

Would you please let me know how guzzle can be modified to avoid ticking off Varnish?

**Comment by pdziok** [comment]
@jjmontgo

In my case setting fixed body length on the stream passed as body request solved the issue. You may want to look also at `_ body_as_string` option (used in `if` couple lines above the line I pasted in the original post)

**Comment by jjmontgo** [comment]
Sorry, I'm a complete newbie.  

I tried setting it to true;
$request->getCurlOptions()->add('body_as_string', true);

But still a 503, and I'm not able to see logs for varnish.  Ah well. :(
