### ISSUE TITLE
Logging of response and processing of response

### ISSUE THREAD

**Issue by jim7112** [guzzle/guzzle#1331]
Hi,
I am doing a project which required API calls to some external server. 

For these API calls i would need to log the raw API response into the database and after that process the response to check if the the response is success or not.

But after i log into the database, i tried to process the response, it became NULL, thus i am unable to process the data. i saw a similar post on this issue where the stream can't be read twice. is there any work around for this?

**Comment by mtdowling** [comment]
Maybe you're stacking your promises incorrectly? Can you show some example code?

You could also try adding the `sink` option to your request and providing it a CachingStream decorator: https://github.com/guzzle/psr7#cachingstream / http://docs.guzzlephp.org/en/latest/request-options.html#sink

**Comment by mtdowling** [comment]
So the CachingStream will work if it's due to consuming the contents. Other than that, if this is promise related, then you need to make sure you are returning a value from a promise when you are chaining them. See https://github.com/guzzle/promises#rejection-forwarding
