### ISSUE TITLE
Interest in unzip middleware?

### ISSUE THREAD

**Issue by Tobion** [guzzle/guzzle#1334]
We are fetching a Zip file and need to process the contents. We solved this manually.
But maybe it would be a better fit as a middleware.

This middleware would transform the request body stream to a zip stream (using ZIP-Streamwrapper of PHP?) that would allow to work on the unzipped content. We probably need a specific StreamInterface implementation that also offers additional methods to get a specific file of the zip archive (in case there are multiple).

I didn't find a middleware for zip so far, neither in guzzle, nor in https://github.com/oscarotero/psr7-middlewares
So do you think it's a good idea? And would you accept such a middleware in guzzle?

**Comment by mtdowling** [comment]
That sounds really cool. I'd be interested in seeing the implementation you had in mind (especially the handling of multiple files). You're right that you'd nee a custom StreamInterface implementation to do the unzipping.

I think it would be a good idea. I think it would work as a generic middleware library that could be plugged into Guzzle, so it doesn't necessarily have to live in this repository.

**Comment by mtdowling** [comment]
I'll go ahead and close this issue. Let me know if you run into any problems.

**Comment by EnGlamdring** [comment]
@mtdowling Is there a way to unzip using Guzzle?
