### ISSUE TITLE
Should CurlHandler rewind request body before consuming?

### ISSUE THREAD

**Issue by kkopachev** [guzzle/guzzle#1335]
Here is a code describing a problem I got:
```php

$big_data = str_repeat('a', 1000000);

try {
    $body = stream_for($big_data);
    $signature = md5($body); // I have to read whole body to build signature...
    // $body->rewind();

    $client = new Client();

    $response = $client->post('http://httpbin.org/post', ["body" => $body]);

    echo json_decode($response->getBody())->data, PHP_EOL;
}
catch (Exception $e) {
    echo (string) $e->getMessage(), PHP_EOL;
}
```

This code results in curl timeout. Since I consumed body stream already and size of body more then 1000000, CurlHandler uses CURLOPT_READFUNCTION https://github.com/guzzle/guzzle/blob/2e5c595512de4885435eaff24b67066769b64b34/src/Handler/CurlFactory.php#L268 to read body. Since body is EOF currently, read returns empty string and curl just hangs until timeout reached.
I am ok with rewinding body myself, but in case when body length is less then 1000000, then stream will be casted to string which implicitly calls rewind on the stream making request magically work. 
StreamHandler also casting body to a string, so it works as well.

My guess here is that CurlHandler should rewind stream before consuming, since Content-length is calculated based on full stream length and in case we consumed chunk of the stream it would produce broken request.

**Comment by mtdowling** [comment]
Wouldn't this be a breaking change for users relying on the fact that curl will pick up sending data from where your last read in the stream left off. This works especially well for streams that are not read into memory before transferring and therefore have no pre-computed content-length. If such a stream was wrapped in a CachingStream but still did not know it's content-length, then a rewind would break current behavior.

For now, your safest bet is to call `rewind` manually if you've consumed any of the body.

**Comment by kkopachev** [comment]
From my prospective it's broken already and should not be the thing somebody relies on. It is an inconsistent behavior across handlers. `CurlHandler` won't rewind stream if it's too big or size is unknown. On the other hand `StreamHandler` will always cast body to string causing stream rewind (in most cases, depends on implementation).

**Comment by mtdowling** [comment]
@jeskew What do you think?

**Comment by jeskew** [comment]
If I passed in a partially consumed stream, I wouldn't expect the handler to rewind it. If the `StreamHandler` is rewinding all streams and the `CurlHandler` is not, that sounds like a bug in the `StreamHandler`.

**Comment by mtdowling** [comment]
I agree that the handlers are inconsistent. I guess people that don't want it to rewind could wrap their stream in a NoSeekStream: https://github.com/guzzle/psr7/blob/master/src/NoSeekStream.php.

@jeskew Would updating the curl handler to rewind the stream break the AWS SDK for PHP?

**Comment by jeskew** [comment]
I don't believe many users would be impacted by such a change. The only operation that I would be worried about is S3::PutObject, but it's currently very difficult to send a partially consumed stream (users need to supply a custom ContentLength and ContentSHA256, which isn't documented anywhere). Anyone who needs to send a partial stream is probably already using LimitStreams (as the SDK does with multipart uploads).

**Comment by mtdowling** [comment]
Cool. I'm on board with making curl rewind before sending then.
