### ISSUE TITLE
"final" class TransferStats is not mockable in unit tests

### ISSUE THREAD

**Issue by downsider** [guzzle/guzzle#1336]
I was writing a unit test for a method used as the callable for the "on_stats" option, but found that I could not mock the TransferStats object to inject into the method because it is a "final" class and can't be extended. 
The only workaround I can find is to instantiate a TransferStats object and use it directly, meaning that my test is no longer a unit test as it then also depends on the workings of the TransferStats class

I can't see any obvious reason why the class is final or think of any potential issues with removing the keyword. Would it be possible to remove it in order to allow for clean unit testing?

**Comment by mtdowling** [comment]
You don't really need to mock TransferStats. It's just a value object. Simply create one and inject the required arguments in the constructor.

**Comment by downsider** [comment]
All the same, I'd prefer not to break best practice if possible. Is there a reason why the TransferStats class is final?

**Comment by mtdowling** [comment]
Actually, TransferStats is a value object, so the best practice here is to not mock it. It's final because it's meant to be a value object that should not be extended.
