### ISSUE TITLE
fix your composer

### ISSUE THREAD

**Issue by onetigr** [guzzle/guzzle#1342]
Your instructions are not working. OSX 10.11, php 5.6

Pro:guzzle-master vladimir$ curl -sS https://getcomposer.org/installer | php
#!/usr/bin/env php
All settings correct for using Composer
Downloading...

Composer successfully installed to: /Users/vladimir/Work/php/composer/guzzle-master/composer.phar
Use it: php composer.phar
Pro:guzzle-master vladimir$ php composer.phar require guzzlehttp/guzzle
You are running composer with xdebug enabled. This has a major impact on runtime performance. See https://getcomposer.org/xdebug
Using version ^6.1 for guzzlehttp/guzzle
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package guzzlehttp/guzzle No version set (parsed as 1.0.0) could not be found.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

Installation failed, reverting ./composer.json to its original content.
Pro:guzzle-master vladimir$

**Comment by GrahamCampbell** [comment]
This is NOT the fault of guzzle. This is because your PHP version is too old.

**Comment by onetigr** [comment]
php is 5.6

**Comment by GrahamCampbell** [comment]
> - The requested package guzzlehttp/guzzle No version set (parsed as 1.0.0) could not be found.

Looks like you've ALREADY added guzzle.

**Comment by GrahamCampbell** [comment]
Please close this non-issue.

**Comment by onetigr** [comment]
Oh, that's funny. Sorry.

**Comment by SofHad** [comment]
Could we see composer.json please?

**Comment by onetigr** [comment]
{
    "name": "guzzlehttp/guzzle",
    "type": "library",
    "description": "Guzzle is a PHP HTTP client library",
    "keywords": ["framework", "http", "rest", "web service", "curl", "client", "HTTP client"],
    "homepage": "http://guzzlephp.org/",
    "license": "MIT",
    "authors": [
        {
            "name": "Michael Dowling",
            "email": "mtdowling@gmail.com",
            "homepage": "https://github.com/mtdowling"
        }
    ],
    "require": {
        "php": ">=5.5.0",
        "guzzlehttp/psr7": "~1.1",
        "guzzlehttp/promises": "~1.0"
    },
    "require-dev": {
        "ext-curl": "*",
        "phpunit/phpunit": "~4.0",
        "psr/log": "~1.0"
    },
    "autoload": {
        "files": ["src/functions_include.php"],
        "psr-4": {
            "GuzzleHttp\\": "src/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "GuzzleHttp\\Tests\\": "tests/"
        }
    },
    "extra": {
        "branch-alias": {
            "dev-master": "6.1-dev"
        }
    }
}



You are right, 'vendor' folder is here after 'composer update guzzlehttp/guzzle', but autoloader doesn't work, and 'composer require guzzlehttp/guzzle' constantly displays error.
