### ISSUE TITLE
Wait for all asynchronous requests to finish before exiting

### ISSUE THREAD

**Issue by hubgit** [guzzle/guzzle#1345]
This may not be possible, but is there a way to keep a PHP script running until all the asynchronous requests have returned and been handled? 

I can think of a workaround involving adding all the requests to an array and then calling `Promise\all($requests)->wait()` (perhaps in a shutdown function?), but it would be nice if the queue could be handled automatically.

**Comment by mtdowling** [comment]
This is not something built-in to Guzzle. You'll either need to tick the event loop associated with your client that has outstanding requests, or you need to call wait on the outstanding promises. For a shutdown style approach, you'd need to implement that yourself, likely by wrapping an adapter function in a function that tracks each promise that passed through it. When shutdown is called, the outstanding promises would be waited upon.

**Comment by piotr-cz** [comment]
Look for [GuzzleHttp\Promise\all](https://github.com/guzzle/promises/blob/v1.3.1/src/functions.php#L219)
