### ISSUE TITLE
Error when opening the file from S3 bucket. 

### ISSUE THREAD

**Issue by shankarnbcuni** [guzzle/guzzle#1346]
Hi , 

I am getting below error when i try to open the file from S3 bucket. I am connecting from corporate network . I set the proxy url as well. Please find the below Context object. 

Error:
WD node: Guzzle\Common\Exception\RuntimeException: Error creating resource. [message] fopen(https://hermes-development.s3.amazonaws.com/Lighthouse_2.jpg): failed to open stream: Unable to find the socket      [error]
transport "http" - did you forget to enable it when you configured PHP?
[file] xxxxxxxxxxxxxxxxx/sites/all/vendor/guzzle/guzzle/src/Guzzle/Stream/PhpStreamRequestFactory.php

Context Object - With proxy 
 [this] => Guzzle\Stream\PhpStreamRequestFactory Object
        (
            [context:protected] => Resource id #1358
            [contextOptions:protected] => Array
                (
                    [https] => Array
                        (
                            [method] => GET
                            [header] => Array
                                (
                                    [0] => Host: {Mybucket-name}.s3.amazonaws.com
                                    [1] => User-Agent: aws-sdk-php2/2.8.5 Guzzle/3.9.3 curl/7.19.7 PHP/5.5.28
                                    [2] => Date: Wed, 23 Dec 2015 15:03:29 +0000
                                    [3] => Authorization: AWS {{Mybucket-authkey}}
                                    [4] => Connection: close
                                )

                            [protocol_version] => 1.1
                            [ignore_errors] => 1
                            [proxy] =>{proxy-ipaddress}
                        )

                    [ssl] => Array
                        (
                            [verify_peer] => 1
                            [cafile] => xxxxxxx/sites/all/vendor/guzzle/guzzle/src/Guzzle/Http/Resources/cacert.pem
                        )

                )

**Comment by mtdowling** [comment]
Can you open this on the AWS SDK for PHP, please? https://github.com/aws/aws-sdk-php/issues/new
