### ISSUE TITLE
Slow response time - 5 seconds average

### ISSUE THREAD

**Issue by BentCoder** [guzzle/guzzle#1348]
Hi,

I'm using `"guzzlehttp/guzzle": "6.1.1"` and finding it really slow. Receiving a response takes about 5 seconds. Is there any known reason for it? I'm on Symfony2.

Note: `"guzzlehttp/guzzle": "4.2.3"` is way way faster than `6.1.1` though.

Thanks

**6.1.1 Code example**

            use GuzzleHttp\Client;
            use GuzzleHttp\Psr7\Response;
            use GuzzleHttp\Psr7\Stream;

            $client = new Client();
            /** @var Response $response */
            $response = $client->request(
                'POST',
                'http://www.whatever.com/api/student',
                [
                    'headers' => [
                        'Content-Type' => 'application/json',
                        'Authorization' => 'Basic 23erfgh678iED6tyuh'
                    ],
                    'body' => $postData
                ]
            );

**4.2.3 Code example**

            use GuzzleHttp\Client;
            use GuzzleHttp\Exception\BadResponseException;
            use GuzzleHttp\Stream\Stream;

            $client = new Client();
            $request = $client->createRequest('POST', 'http://www.whatever.com/api/student',);
            $request->addHeader('Authorization', 'Basic 23erfgh678iED6tyuh);
            $request->addHeader('Content-Type', 'application/json');
            $request->setBody(Stream::factory($postData));
            $result = $client->send($request);

**Comment by Comrade42** [comment]
The reason might be that the newest version of Guzzle uses HTTP 1.1 instead of HTTP 1.0.

In HTTP 1.1, all connections are considered persistent unless declared otherwise:

> Connection: keep-alive

So the connection has to be explicitly closed or else the connection waits until it is timed-out. I think this can explain why the request is taking so long to complete.

To fix this, you can add a "Connection: close" header into your HTTP response:

> $headers = array('Connection' => 'close');

**Comment by mtdowling** [comment]
That could definitely be the case, @Comrade42. Another possibility is that the request is being sent with an `Expect: 100-Continue` header, which is not being handled properly by the server. You can probably pinpoint the cause by looking at the `debug` output. See http://docs.guzzlephp.org/en/latest/request-options.html#debug for information on `debug`.

**Comment by BentCoder** [comment]
Hi @Comrade42 and @mtdowling ,

Based on your suggestions, I updated my code as below but unfortunately no joy.

Thanks

```
use GuzzleHttp\Client;

$client = new Client();

$headers['Authorization'] = 'Basic c3R1ZGVudDpzdHVkZW50';
$headers['Content-Type'] = 'application/json';
$headers['Connection'] = 'close';
$headers['Expect100Continue'] = false;

$client->request(
    'POST',
    'http://symfony.local/app_test.php/student',
    [
        'headers' => $headers,
        'body' => '{"name":"bentcoder"}'
    ]
);
```

**Comment by SofHad** [comment]
Try to use this bundle with debug mode ?https://github.com/csarrazi/CsaGuzzleBundle/blob/master/src/Resources/doc/available_middleware.md

**Comment by BentCoder** [comment]
Apparently slowness is caused by `.local` tld which is reserved for Bonjour service in Mac OS. I changed mine from `http://symfony.local` to `http://symfony.dev` and problem solved. Response time is less than a second now.

**Comment by nczepa** [comment]
slow guzzle depends, but keep attention to your environment! we had the same issue with a slow guzzle/6.2.1 and the problem was an special curl/7.29 version which caused the super slow performance

**Comment by gyaan** [comment]
@BentCoder Thanks!

I have same problem it's strange why domain with .local taking time I changed my domain name to .dev and working fine.

**Comment by vivekkumar159** [comment]
Can someone please tell me how to change .local tld to .dev ?

**Comment by mnr73** [comment]
related to this 

https://stackoverflow.com/questions/9304645/php-curl-slowness

CURL has some problems with DNS look-ups. Try using IP address instead of domain name.

this work for me ,but why? 😐
