### ISSUE TITLE
cURL error 35: Unknown SSL protocol error

### ISSUE THREAD

**Issue by codestic** [guzzle/guzzle#1349]
Hi guys,

I have problems connecting with Guzzle through a proxy to any SSL site. If I try it with standard cURL in PHP it works fine, however, with Guzzle the connection fails and returns:

    [GuzzleHttp\Exception\ConnectException]
    cURL error 35: Unknown SSL protocol error in connection to api.ipify.org:443

The cURL code that works well:

        $options = array(
            CURLOPT_RETURNTRANSFER => true,
            CURLOPT_PROXY => '1.2.3.4:1234',
            CURLOPT_PROXYUSERPWD => "proxy:auth",
        );

        $ch      = curl_init( 'https://api.ipify.org?format=json' );
        curl_setopt_array( $ch, $options );
        $content = curl_exec( $ch );
        $err     = curl_errno( $ch );
        $errmsg  = curl_error( $ch );
        $header  = curl_getinfo( $ch );
        curl_close( $ch );

        $header['errno']   = $err;
        $header['errmsg']  = $errmsg;
        $header['content'] = $content;

        print_r($header);

The Guzzle code that fails:

        // http client
        $this->client = $client = new Client([
            'cookies' => true
        ]);

        $res = $this->client->request('GET', 'https://api.ipify.org?format=json', [
            'proxy' => 'https://proxy:auth@1.2.3.4:1234',
            'verify' => false,
            'curl' => [
                //CURLOPT_SSLVERSION => 3
                //CURLOPT_SSLVERSION => CURL_SSLVERSION_DEFAULT,
                CURLOPT_SSL_VERIFYPEER => false
            ],
        ]);

    print_r($res);

Any ideas? I'm guessing it has something to do how Guzzle handles HTTP SSL requests, since it is also using cURL underlying, I am confused why this wouldn't work.

Thanks

**Comment by mtdowling** [comment]
Can you try passing the proxy without a scheme, or just providing `tcp` as the scheme instead of `https`?

**Comment by codestic** [comment]
Tried passing it with HTTP, tried passing it with HTTPS, tried passing it with TCP and tried passing it in the standard cURL format (IP:PORT). No luck, always the same. I tried debugging it myself, but I cannot find anything that would mess with it. Really frustrating :(

**Comment by mtdowling** [comment]
Can you provide debug output? http://docs.guzzlephp.org/en/latest/request-options.html#debug

**Comment by OAFCROB** [comment]
I've had a similar issue where I had to set the CURLOPT_SSLVERSION and it was only process of elimatination that I found the correct SSL protocol 

https://github.com/guzzle/guzzle/issues/1364

**Comment by mtdowling** [comment]
Sounds like CURLOPT_SSLVERSION might be the solution. Otherwise, I don't know what else Guzzle could do with regards to this issue.

**Comment by soubhagyabarik** [comment]
i also have same problem for me it's working fine in loca but in server it's not working

**Comment by smalleyes** [comment]
😂  ,how can i do...

* About to connect() to www.googleapis.com port 443 (#0)
*   Trying 172.217.27.138... * Timeout
*   Trying 172.217.160.74... * Timeout
*   Trying 172.217.24.10... * Timeout
*   Trying 172.217.160.106... * connected
* Connected to www.googleapis.com (172.217.160.106) port 443 (#0)
* Initializing NSS with certpath: sql:/etc/pki/nssdb
* warning: ignoring value of ssl.verifyhost
* NSS error -5961
* Closing connection #0
* SSL connect error
PHP Fatal error:  Uncaught GuzzleHttp\Exception\ConnectException: cURL error 35: SSL connect error (see http://curl.haxx.se/libcurl/c/libcurl-errors.html) in xxxx.

**Comment by jorwan** [comment]
This worked for me:
**`yum update nss`**

Source: https://serverfault.com/a/642203

**Comment by axejko** [comment]
`
                'guzzle' => [
                    'curl'  => [
                        CURLOPT_PROXY => 'ip:port',
                        CURLOPT_PROXYUSERPWD => 'login:password',
                        CURLOPT_SSL_VERIFYPEER => false,
                    ],
                ],
`
It works for me

**Comment by ngrcode** [comment]
I Have the same error but dont understand what to do

**Comment by tomavic** [comment]
We are at the end of 2019 and I still have this issue

**Comment by GrahamCampbell** [comment]
> We are at the end of 2019 and I still have this issue

This is NOT a bug with Guzzle itself.

**Comment by tomavic** [comment]
@GrahamCampbell Can you please help me out 

```
cURL error 35: OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to onesignal.com:443  (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)
```

**Comment by huzhonglan** [comment]
I encountered the same problem.

**Comment by RuanHerculano** [comment]
somehow it happens because he is making a request within a request, I called the request within the `Laravel Job` and it worked

**Comment by tomavic** [comment]
@RuanHerculano How did you do that? please explain more

**Comment by RuanHerculano** [comment]
@tomavic I was calling a soap request inside a laravel controller using Guzzle, as it wasn't working, I changed the code that made the request inside the controller and put it inside a Laravel Job and it ended up working, but soon after it stopped working again. So I don't know what else to do: /

**Comment by RuanHerculano** [comment]
try this into Dockerfile

```
RUN apt-get update -yqq \
 && apt-get install -y --no-install-recommends openssl \
 && sed -i 's,^\(MinProtocol[ ]*=\).*,\1'TLSv1.0',g' /etc/ssl/openssl.cnf \
 && sed -i 's,^\(CipherString[ ]*=\).*,\1'DEFAULT@SECLEVEL=1',g' /etc/ssl/openssl.cnf\
 && rm -rf /var/lib/apt/lists/*
```

**Comment by stonkeep** [comment]
> try this into Dockerfile
> 
> ```dockerfile
> RUN apt-get update -yqq \
>  && apt-get install -y --no-install-recommends openssl \
>  && sed -i 's,^\(MinProtocol[ ]*=\).*,\1'TLSv1.0',g' /etc/ssl/openssl.cnf \
>  && sed -i 's,^\(CipherString[ ]*=\).*,\1'DEFAULT@SECLEVEL=1',g' /etc/ssl/openssl.cnf\
>  && rm -rf /var/lib/apt/lists/*
> ```

Worked for me
