### ISSUE TITLE
Ability to create a new Response from a text or curl dump

### ISSUE THREAD

**Issue by weppos** [guzzle/guzzle#1351]
I'm currently working on an API client and I'm using the [mock handler](http://guzzle.readthedocs.org/en/latest/testing.html) to stub the HTTP requests and return a response I can use to properly test the API calls.

However, since the API client supports several different API calls, in my test suite I have a bunch of HTTP response fixtures (I created with curl) that I feed each time to the mock handler.

In order to do that, I created a simple class that initializes a `Response` object from a plain text file, rather than having to pass all the settings to the response initializer (which may be very unmaintainable for a large client). The idea is borrowed from a [similar feature I used in the Ruby version of the client](https://github.com/aetrion/dnsimple-ruby/blob/v2.1.0/spec/dnsimple/client/contacts_spec.rb#L10-L11).

Would you be interested in a patch? I can submit a PR with the feature to be merged into the main repository. The example usage will be something like:

```php
$response = new GuzzleHttp\Psr7\Response::newFromText(<<<EOT
HTTP/1.1 200 OK
Server: nginx

This is a response body.
EOT);
```

or

```php
$response = GuzzleHttp\Psr7\Response::newFromFile('path/to/file.http');
```

I can feed the response to the mock handler in this way

```php
$mock = new MockHandler([
    Response::newFromFile('path/to/fixture/success.http'),
    Response::newFromFile('path/to/fixture/error-not-authorized.http')
]);
```

What do you think?

**Comment by crucialwebstudio** [comment]
@weppos I was having a hard time with this too. I believe you can do this like so:

```
$mock = new MockHandler([
    GuzzleHttp\Psr7\parse_response(file_get_contents('path/to/fixture/success.http'))
]);
```

**Comment by mtdowling** [comment]
That's right, you can parse a response from a string using `GuzzleHttp\Psr7\parse_response`. See https://github.com/guzzle/psr7/blob/master/src/functions.php#L468

**Comment by weppos** [comment]
Oh, interesting. Thanks for pointing me to that.
