### ISSUE TITLE
while sending mail getting error like Passing in the "body" request option as an array to send a POST request has been deprecated.

### ISSUE THREAD

**Issue by jgojariya** [guzzle/guzzle#1353]
I'm using laravel 4.2 framwork and having guzzlehttp/guzzle 6.1.1 version.
I got bellow error when I send email.
'Passing in the "body" request option as an array to send a POST request has been deprecated. Please use the "form_params" request option to send a application/x-www-form-urlencoded request, or a the "multipart" request option to send a multipart/form-data request". 
Have any solution ?

**Comment by GrahamCampbell** [comment]
You can only use guzzle 5 with laravel 4.2.

**Comment by GrahamCampbell** [comment]
You will need tp upgrade to Laravel 5.1 or greater to be able to use either guzzle 5 or 6.

**Comment by GrahamCampbell** [comment]
This is not a bug, so please close this.

**Comment by jgojariya** [comment]
Thanks.. It's working. :)
