### ISSUE TITLE
how to use multipart upload file and  set filename is Chinese

### ISSUE THREAD

**Issue by xjdata** [guzzle/guzzle#1356]
hi  thank you  code . 

i used guzzle  send email with api.

when i use curl upload and set filename  Chinese eg"中文", is worked. 

but when i use guzzle  and set put "multipart"  filename lost.
here is my code, thank you again.

```php
//...
[
            'name'     => '中文',
            'contents' => fopen('/path/to/file', 'r')
            'filename' => '中文.pdf'
]
//...

$http = new \GuzzleHttp\Client();
$response = $http->post($url, ['multipart' => $data]);
$results = $response->getBody()->getContents();
return json_decode($results);

```

**Comment by mtdowling** [comment]
Can you provide the debug output? http://docs.guzzlephp.org/en/latest/request-options.html#debug

**Comment by xjdata** [comment]
I trace the source code and found that the php basename does not support Chinese.

so...
```php
//guzzlehttp/psr7/src/MultipartStream.php
// line 120
// basename ($ filename) change to
get_basename ($ filename)
....

function get_basename ($ filename) {
      return preg_replace ('/^.+[\\\\\\/]/', '', $ filename);
}
```

**Comment by mtdowling** [comment]
Is there anything Guzzle can do here then? This seems like a PHP issue.

**Comment by mtdowling** [comment]
Closing as this is a PHP bug AFAIU.

**Comment by taozuhong** [comment]
it is not a issue of PHP basename function, because basenae depend on locale, so you should set locale correctly:
$langLocal = setlocale(LC_CTYPE, 0);
setlocale(LC_ALL, "zh_CN.utf8");

echo basename($filename);

setlocale(LC_ALL, $langLocal);

**Comment by AllPDFfillersGoToHeaven** [comment]
Stumbled upon this problem and this should be looked at again, because this forces all files to be english letters and obviously that's not always the case. There's already a fix for this: https://github.com/guzzle/psr7/pull/181/commits/3e963d4a6cc6c1e2bfd93cb3b33111ea8787981a

but there doesn't seem to be much attention to it
