### ISSUE TITLE
Upgrade guide is a bit incomplete

### ISSUE THREAD

**Issue by FabioAntunes** [guzzle/guzzle#1358]
So on the upgrade guide from 5 to 6 there's this:
> Static functions in GuzzleHttp\Utils have been moved to namespaced functions under the GuzzleHttp namespace. This requires either a Composer based autoloader or you to include functions.php.

But that's not necessarily true, since some of the functions no longer exist. On our projects we use Guzzle jsonDecode() because it provides a nice error handler for parsing json.

**Comment by jeskew** [comment]
The JSON functions were brought back in #1389. They are now functions (`json_encode` and `json_decode`) in the `GuzzleHttp` namespace.
