### ISSUE TITLE
Guzzle 6 - Exceptions

### ISSUE THREAD

**Issue by lucianocn** [guzzle/guzzle#1359]
My application cannot return exception in any way.
I am using the Guzzle 6 and I already disabled the `http_errors`, unfortunately it can also throw exceptions that occur during the transfer. (http://docs.guzzlephp.org/en/latest/quickstart.html#exceptions)

So, there is an easy way to disable all possible Guzzle exceptions?

* I know that I can use `try catch`, but as theres a lot of possible exceptions I'm afraid to do this way.

```php
$client = new \GuzzleHttp\Client();
$response = $client->post('https://myurl.com.br', [
	'http_errors' => false,
]);
```

**Comment by jeskew** [comment]
Beyond the exceptions that are silenced by disabling `http_errors`, Guzzle can throw `InvalidArgumentException`s, `RuntimeException`s, `LogicException`s, `BadMethodCallException`s, `OutOfBoundsException`s, and `GuzzleHttp\Exception\GuzzleException`s. You can use try/catch to handle those.

It might be less verbose to simply catch `Exception`. If you application needs to be resilient against *any* failure when making HTTP requests, you can convert exceptions to PHP warnings:
```php
try {
    // make a request
} catch (\Exception $e) {
    trigger_error($e->getMessage(), E_USER_WARNING);
}
```

If an exception was throw, your request might not have succeeded or even been sent, so I wouldn't recommend doing this if successfully sending a request is critical.
