### ISSUE TITLE
Sink not drained in mocks - v5/v6 affected

### ISSUE THREAD

**Issue by jaymecd** [guzzle/guzzle#1360]
There is an issue with mocking responses:

v5:
- [RingPHP - Client/StreamHandler.php#L61](https://github.com/guzzle/RingPHP/blob/master/src/Client/StreamHandler.php#L61) drains save_to
- [Subscriber/Mock.php#L74](https://github.com/guzzle/guzzle/blob/5.3.0/src/Subscriber/Mock.php#L74) does NOT drain

``` php
$mock = new \GuzzleHttp\Subscriber\Mock();
$mock->addResponse("HTTP/1.1 201 Created\n\nCREATED");

$client = new \GuzzleHttp\Client();
$client->getEmitter()->attach($mock);

$sink = \GuzzleHttp\Stream\Stream::factory(fopen('php://temp', 'w+'));

$response = $client->send($client->createRequest('GET', 'http://what.ever/', ['save_to' => $sink]));

print_r([
    'r-tell' => $response->getBody()->tell(),
    'r-data' => $response->getBody()->getContents(),
    's-tell' => $sink->tell(),
    's-data' => $sink->getContents(),
]);
```

expected:

```
Array
(
    [r-tell] => 0
    [r-data] => CREATED
    [s-tell] => 0
    [s-data] => CREATED
)
```

actual:

```
Array
(
    [r-tell] => 7
    [r-data] =>
    [s-tell] => 7
    [s-data] =>
)
```

v6:
- [Handler/StreamHandler.php#L122](https://github.com/guzzle/guzzle/blob/6.1.1/src/Handler/StreamHandler.php#L122) drains sink
- [Handler/MockHandler.php#L99](https://github.com/guzzle/guzzle/blob/6.1.1/src/Handler/MockHandler.php#L99) does NOT drain

No code, but it's easy to follow the issue.

**Comment by mtdowling** [comment]
Thanks for reporting.
