### ISSUE TITLE
"Host" header is always taken from URI and overwrite the set one. 

### ISSUE THREAD

**Issue by lexakozakov** [guzzle/guzzle#1361]
```
GuzzleHttp\Client

    public function sendAsync(RequestInterface $request, array $options = [])
    {
        // Merge the base URI into the request URI if needed.
        $options = $this->prepareDefaults($options);

        return $this->transfer(
            $request->withUri($this->buildUri($request->getUri(), $options)),
            $options
        );
    }
```
There is no option to set the second parameter in $request-> withUri(..., <second param>).

Host header is always overwritten by previously set value! 

Is there any workaround? Thank you.

**Comment by mtdowling** [comment]
Yeah, sorry this is something that needs to be worked on. We're tracking this in https://github.com/guzzle/guzzle/issues/1297
