### ISSUE TITLE
Unable to create temporary file

### ISSUE THREAD

**Issue by lellogrini** [guzzle/guzzle#1363]
![schermata 2016-01-18 alle 12 03 16](https://cloud.githubusercontent.com/assets/3509643/12389839/b814786c-bddb-11e5-8649-da92e6b9b9bb.png)
Do you know which directory is? I'm on OSX with XAMPP

**Comment by jeskew** [comment]
That should be the system temp directory. You can query this by running `php -r 'echo sys_get_temp_dir() . "\n";'` at the command line.

**Comment by pengleelove** [comment]
you can set the sys_temp_dir = './tmp' in php.ini

**Comment by wisnetmark** [comment]
Laravel Project

getting similar error but not having to do with permissions:

curl_setopt_array(): Unable to create temporary file.

tmp file is created in my windows tmp dir.  

Windows Server 2008 R2 Standard, IIS7, PHP 7.2.6, Laravel 5.6

**Comment by afz204** [comment]
i can't find any reference..

**Comment by patelmm** [comment]
still getting error can you help me out?

**Comment by afz204** [comment]
i forgot to give permission by users

**Comment by kelvinthiongo** [comment]
I got such an error on my windows 10. I ran `php -r 'echo sys_get_temp_dir() . "\n";'` to get the Temp directory (Mine was C:\WINDOWS\TEMP). Using the file explorer, i opened the folder and accepted request to permanently have access to this folder. This worked for me.

**Comment by afz204** [comment]
I'm sorry, I don't understand what you talking about.

**Comment by biopowder** [comment]
I have same issue on MAC, and I cant change permissions to that temporary folder, that my webserver could write to it

**Comment by afz204** [comment]
Thanks for helping me.

**Comment by BahaaBakri** [comment]
First  the problem is when create a new laravel project for example you must detect a path to store files temporary and this path is not correct or it is not allowed accessing to it 
After one week working in this error finally I found this solution for windows users:

1. open php.ini from this path 'C:\xampp\php' (if you are using xampp)
2. inside php.ini search about 'sys_temp_dir' uncomment it, and set value to 'C:\Users\USER\AppData\Local\Temp'
3. finally it will work

**Comment by Miltak69** [comment]
dsa

> First, the problem is when create a new laravel project for example was happened because you must detect a path for storing files temporary and this path is not correct or it is not allow accessing to it After one week working in this error finally I found this solution for windows users:
> 
>     1. open php.ini from this path 'C:\xampp\php' (if you are using xampp)
> 
>     2. inside php.ini search about 'sys_temp_dir' uncomment it, and set value to 'C:\Users\USER\AppData\Local\Temp'
> 
>     3. finally it will work

Thanks my friend, that worked for me !!!
