### ISSUE TITLE
cURL error 35: error:14077102:SSL routines:SSL23_GET_SERVER_HELLO:unsupoorted protocol

### ISSUE THREAD

**Issue by OAFCROB** [guzzle/guzzle#1364]
I've been trying to resolve this issue for a few hours now, but I cannot seem to find an answer anywhere online. When I put guzzle not in debugging mode I get the following error;

cURL error 35: error:14077102:SSL routines:SSL23_GET_SERVER_HELLO:unsupoorted protocol

![guzzle-1](https://cloud.githubusercontent.com/assets/3277589/12393512/0db2a2b4-bdee-11e5-9b0e-573184ead030.PNG)

When in debugging mode I get; 

curl_setopt_array(): cannot represent a stream of type Output as a STDIO FILE*

![guzzle-2](https://cloud.githubusercontent.com/assets/3277589/12393509/0910ca42-bdee-11e5-9936-0230c2bea901.PNG)

I have cURL enabled in my php.ini, i've set curl.cainfo, opensll.cafile and openssl.capath. I've managed to call the API successfully via cURL in commandline, but I cannot seem to get it to work via Guzzle any ideas?

Composer installation of guzzle; "guzzlehttp/guzzle": "^6.1" 

I have also tried setting the SSL versions like in the commented out code snippet. 

![guzzle-3](https://cloud.githubusercontent.com/assets/3277589/12393546/4dcd18f2-bdee-11e5-850c-d32fb4129168.PNG)

Here's roughly the code I'm calling;

``` php 

$client = new \GuzzleHttp\Client(['debug' => true]);
$response = $client->request('GET', 'API_URL', ['verify' => 'D:\Certificate\cacert.pem']);

```
I have also tried writing a simple cURL call which seems to work, so really stuck on this one. 

![guzzle-4](https://cloud.githubusercontent.com/assets/3277589/12393753/a6c4cefe-bdef-11e5-84df-53a2f8c9f092.PNG)

**Comment by OAFCROB** [comment]
Okay, I've got to the bottom of this for my issue. It would appear the API i'm calling is only allowing SSLv3 which I thought wouldn't be sued due to the security flaws highlighted recently. It wasn't until I write it all out as cURL that I realised this when I got the same error message. 

So basically, I had to set the CURLOPT_SSLVERSION, as an optional parameter in Guzzle, see my example below. Also here is a link to the available definable SSL version for cURL http://curl.haxx.se/libcurl/c/CURLOPT_SSLVERSION.html

![guzzle-5](https://cloud.githubusercontent.com/assets/3277589/12416616/5692af40-be9a-11e5-8ec9-58d4ed5e0400.PNG)

I hope this helps others in the future.

**Comment by RuanHerculano** [comment]
try this in Dockerfile

``` dockerfile
RUN apt-get update -yqq \
&& apt-get install -y --no-install-recommends openssl \
&& sed -i 's,^\(MinProtocol[ ]*=\).*,\1'TLSv1.0',g' /etc/ssl/openssl.cnf \
&& sed -i 's,^\(CipherString[ ]*=\).*,\1'DEFAULT@SECLEVEL=1',g' /etc/ssl/openssl.cnf\
&& rm -rf /var/lib/apt/lists/*
```

**Comment by Panoptik** [comment]
In my case I changed base image for docker from **php:7.1-fpm** (debian based "Buster") to **php:7.1-fpm-stretch** and problem gone.
Probably the reason is in openssl configuration or openssl version.

Below is software info that brings this error:
```
# openssl version
OpenSSL 1.1.1d  10 Sep 2019


# curl -V
curl 7.64.0 (x86_64-pc-linux-gnu) libcurl/7.64.0 OpenSSL/1.1.1d zlib/1.2.11 libidn2/2.0.5 libpsl/0.20.2 (+libidn2/2.0.5) libssh2/1.8.0 nghttp2/1.36.0 librtmp/2.3
Release-Date: 2019-02-06
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp 

# cat /etc/os-release 
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

```

And this is stretch versions which work fine
```
# openssl version
OpenSSL 1.1.0l  10 Sep 2019

# curl -V
curl 7.52.1 (x86_64-pc-linux-gnu) libcurl/7.52.1 OpenSSL/1.0.2t zlib/1.2.8 libidn2/0.16 libpsl/0.17.0 (+libidn2/0.16) libssh2/1.7.0 nghttp2/1.18.1 librtmp/2.3
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP HTTP2 UnixSockets HTTPS-proxy PSL 

# cat /etc/os-release 
PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
NAME="Debian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
VERSION_CODENAME=stretch
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

```

**Comment by aditya-rewari-cb** [comment]
> Okay, I've got to the bottom of this for my issue. It would appear the API i'm calling is only allowing SSLv3 which I thought wouldn't be sued due to the security flaws highlighted recently. It wasn't until I write it all out as cURL that I realised this when I got the same error message.
> 
> So basically, I had to set the CURLOPT_SSLVERSION, as an optional parameter in Guzzle, see my example below. Also here is a link to the available definable SSL version for cURL http://curl.haxx.se/libcurl/c/CURLOPT_SSLVERSION.html
> 
> ![guzzle-5](https://cloud.githubusercontent.com/assets/3277589/12416616/5692af40-be9a-11e5-8ec9-58d4ed5e0400.PNG)
> 
> I hope this helps others in the future.

@OAFCROB Hi.. I get similar issue at a very low frequency. Majorly its a success with CURL. 
Do you think this solution could work for me ?
In your case, curl error out was for every request , or it used to error out for some ?

Here is my Guzzle code
 ```
               $client = new \GuzzleHttp\Client;
                $request = $client->request('POST', $config_data['base_url'], [
                    'headers' => [
                        'access_key' => $config_data['api_key'],
                        'access-key' => $config_data['api_key'],
                        'Accept' => 'application/json',
                        'Content-Type' => 'application/json',
                    ],
                    'json' => $sms_data,
                    'timeout' => 120,
                    'connect_timeout' => 120,
                ]);
```

**Comment by OAFCROB** [comment]
@aditya-rewari-cb sorry not logged into my GitHub account for a while as I'm currently working on a project in BitBucket. Yes, my issue was on all requests if my memory serves me correctly but this was a long time ago now. Did you manage to get it working? 

I would suggest just giving it ago if you haven't done so already.
