### ISSUE TITLE
Can't find unwrap function?

### ISSUE THREAD

**Issue by amit0rana** [guzzle/guzzle#1365]
Hi, I can't find unwrap function as described here: http://docs.guzzlephp.org/en/latest/quickstart.html#concurrent-requests
```
// Wait on all of the requests to complete.
$results = Promise\unwrap($promises);
```

 What am I missing?

I am looking here: https://github.com/guzzle/promises/blob/master/src/Promise.php

Thanks.

**Comment by jeremeamia** [comment]
The function that are in the `Promise` namespace, denoted by the blackslash (`\`), are located in the `functions.php` file, since they are not part of a specific class. Look [here](https://github.com/guzzle/promises/blob/master/src/functions.php#L188) for the the `unwrap` function.

**Comment by amit0rana** [comment]
Thanks @jeremeamia
