### ISSUE TITLE
[5.3] `hasResponse` question

### ISSUE THREAD

**Issue by s-chizhik** [guzzle/guzzle#1371]
Hi! I'm using `"guzzlehttp/guzzle" : "5.3.0"`. I have a question about method [`GuzzleHttp\Event\AbstractTransferEvent::hasResponse`](https://github.com/guzzle/guzzle/blob/5.3/src/Event/AbstractTransferEvent.php#L37). What goal does method works for? It current realization doesn't allow me to check is response available. In case, when response is `null`, `hasResponse` will return `true`.

```PHP
// Will pass condition, when response is null
if ($event->hasResponse()) {
    $event->getResponse()->getBody();   // getBody will be called on null
}
```

**Comment by jeskew** [comment]
It's meant to check if the response has already been resolved or if it's still an instance of `GuzzleHttp\Ring\Future\FutureInterface`. You can use it when making [asynchronous requests](http://docs.guzzlephp.org/en/5.3/clients.html#asynchronous-requests).

**Comment by s-chizhik** [comment]
So, you want to say, that it's normal case, when event has no response and method `hasResponse` returns true? Maybe I'm missing something, could you explain?

**Comment by s-chizhik** [comment]
@jeskew maybe you can say something about my question?

**Comment by jeskew** [comment]
@s-chizhik Right, `hasResponse` is meant to tell you whether a transfer is still an unresolved future.
