### ISSUE TITLE
Question about json

### ISSUE THREAD

**Issue by zebamba** [guzzle/guzzle#1383]
I have a code working as below:

        $data = array (
            'Key'    => 'Value',
            'Key'    => 'Value'
        );

            $response = $client->request('POST', $url, [
                            'headers' => ['content-type' => 'application/json'],
                            'json'    => $data
                        ]);

I would like to know if I can provide an Object not an array.

Something like:

$RequestObject = new RequestObject();

$RequestObject-> Key = 'Value';

            $response = $client->request('POST', $url, [
                            'headers' => ['content-type' => 'application/json'],
                            'json'    => $RequestObject
                        ]);

 Is it possible?

**Comment by jeskew** [comment]
Anything provided as a value for the 'json' key [will be passed to `json_encode`](https://github.com/guzzle/guzzle/blob/789bd2309e982eaabf3905f68c0a227b7f5a5cd3/src/Client.php#L359), so you can provide any type that can be converted to JSON by that method. Objects will work so long as they implement the [`JsonSerializable` interface](http://php.net/manual/en/class.jsonserializable.php).
