### ISSUE TITLE
curl error 6

### ISSUE THREAD

**Issue by collmomo** [guzzle/guzzle#1384]
I was using Guzzle 5

- Local machine was working
- Remote Machine was working

I upgraded to Guzzle 6
- Local machine is still working
- Remote machine spams me with curl error 6 on all my guzzle scripts
- Tested curl <url>, worked on remote

Its a 'https' url if that makes a difference or helps you. 

My conclusion, I don't think its my curl config. Must be something different in guzzle 6.

**Comment by mtdowling** [comment]
There's not enough to go on here. Can you provide debug output? What does your request look like.

**Comment by collmomo** [comment]
```php
$url = "www.kijiji.ca" //the url doesn't matter
$headers = array:4 [
  "Host" => "http://www.kijiji.ca"
  "HTTP_USER_AGENT" => "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:31.0) Gecko/20130401 Firefox/31.0"
  "User-Agent" => "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:31.0) Gecko/20130401 Firefox/31.0"
  "Referer" => "http://www.kijiji.ca"
]
self::$client->request("GET", $this->getUrl(), array(), array(), $this->getHeaders());

I reverted back to 5.*

```

**Comment by mtdowling** [comment]
The Host header you're providing looks invalid. You should not include `http://`.
