### ISSUE TITLE
Weird server response on StreamHandler

### ISSUE THREAD

**Issue by pcfreak30** [guzzle/guzzle#1385]
With the following code

```
             var_dump($this->client->get('http://www.aliexpress.com/api-shopping-guide.html',
                    [
                        'query' => [
                            'catId' => $categoryId,
                            'tagResult' => 1,
                            'page' => $pageNum
                        ]
                    ])->getBody()->getContents());exit;
```

the output has a leading `0000C000` and trailing `00000000`. If file_get_contents is used is doesnt. If curl is used it doesnt.

URL to test `http://www.aliexpress.com/api-shopping-guide.html?catId=3&tagResult=1&page=1`.
PHP version `PHP 5.5.9-1ubuntu4.14`

**Comment by kingjerod** [comment]
I'm having this same problem. I'm hitting a JSON endpoint and it has `00006000` before the start of the JSON, and some random numbers littered throughout the rest of the data making it impossible to json_decode. When I use `file_get_contents` it works fine on the exact same endpoint. I cannot share the URL but my code looks like this:

```
$client = new GuzzleHttp\Client();
$response = $client->get($url);
$body = $response->getBody();
```

**Comment by SkUrRiEr** [comment]
I'm getting the same issue with Debian testing's PHP 7.0.5 and the Steam API.

A diff between the same file obtained using `wget` and one obtained using Guzzle is full of:
```
@@ -178257,9 +177760,7 @@
                                                "name": "Posh"
                                        },
                                        {
-                                               "le
-00003746
-vel": 14,
+                                               "level": 14,
                                                "required_score": 2750,
                                                "name": "Fabulous"
                                        },
```

**Comment by kingjerod** [comment]
I think I ended up fixing this by installing php-curl. Whatever the default that Guzzle uses if curl is not installed seems to have this problem. I did not test this but I noticed it started working fine once php-curl was installed.

**Comment by SkUrRiEr** [comment]
@kingjerod That also solved my problem, however Guzzle is supposed to work identically if it uses the "built in" backend or Curl.

**Comment by kingjerod** [comment]
Yup, it should, seems to be a bug.

**Comment by lukepolo** [comment]
Solved it for me as well.

**Comment by sagikazarmark** [comment]
Hi guys,

I am not 100% what the problem is, but I was able to reproduce the issue: https://github.com/reproduce/guzzle/tree/issue1385

Setting the HTTP version to 1.0 temporarily solves the problem, since 1.0 does not support chunked transfer encoding.

I suspect that the server closes the connection before finishing the transfer.
