### ISSUE TITLE
$promise->wait(); callback?

### ISSUE THREAD

**Issue by x8core** [guzzle/guzzle#1387]
Here are example of using pool http://docs.guzzlephp.org/en/latest/quickstart.html#concurrent-requests

How can i set callback for event, when all pool requests are finished?

**Comment by jeskew** [comment]
Calling `promise` on the pool will return a promise that is fulfilled when all requests in the pool have finished executing. You can use the `then` method to provide a function to execute upon fulfillment as described [here](http://docs.guzzlephp.org/en/latest/faq.html?highlight=promise#can-guzzle-send-asynchronous-requests).
