### ISSUE TITLE
PHP Fatal error:  Uncaught Error: Cannot resume an already running generator

### ISSUE THREAD

**Issue by Zae** [guzzle/guzzle#1390]
Hi, maybe i'm doing something wrong but I was under the impression that a pool could work with an array of closures that returned a response, like this test: https://github.com/guzzle/guzzle/blob/master/tests/PoolTest.php#L75

However when I try to get more than one request this way I get this error from PHP:

`PHP Fatal error:  Uncaught Error: Cannot resume an already running generator in /var/www/guzzlepreload/vendor/guzzlehttp/promises/src/EachPromise.php:173`

I'm running PHP 7.0.0-2+deb.sury.org~trusty+1 (cli)

Did I misunderstand how to use the Pool?

~~~~php
$http = new \GuzzleHttp\Client();

$files = [];
for($i = 0; $i < 255; $i++){
	$files[] = function() use ($http) {
		return $http->request('GET', "http://google.com");
	};
}

$pool = new \GuzzleHttp\Pool($http, $files, [
	'concurrency' => 5,
]);

$pool->promise()->wait();
~~~

**Comment by mtdowling** [comment]
You'll need to return a promise from the closure. You are blocking on each closure, which causes the generator to recurse.

**Comment by Zae** [comment]
So changing 

`return $http->request('GET', "http://google.com");`

to

`return $http->getAsync("http://google.com");`

would be enough to fix it?

**Comment by mtdowling** [comment]
Yes, exactly.
