### ISSUE TITLE
Error trying to make a request to a https url: "cURL error 60: SSL certificate problem"

### ISSUE THREAD

**Issue by daniegarcia254** [guzzle/guzzle#1391]
Hi,

I'm trying to make a request to this url [https://www.whoscored.com/?t=Hart](url), but I'm getting the following error:

`Fatal error: Uncaught exception 'GuzzleHttp\Exception\RequestException' with message 'cURL error 60: SSL certificate problem: self signed certificate in certificate chain (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)' in C:\xampp5.6\htdocs\comuniazo-uk\api\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php:187 Stack trace: #0 C:\xampp5.6\htdocs\comuniazo-uk\api\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php(150): GuzzleHttp\Handler\CurlFactory::createRejection(Object(GuzzleHttp\Handler\EasyHandle), Array) #1 C:\xampp5.6\htdocs\comuniazo-uk\api\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php(103): GuzzleHttp\Handler\CurlFactory::finishError(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory)) #2 C:\xampp5.6\htdocs\comuniazo-uk\api\vendor\guzzlehttp\guzzle\src\Handler\CurlHandler.php(43): GuzzleHttp\Handler\CurlFactory::finish(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFa in C:\xampp5.6\htdocs\comuniazo-uk\api\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php on line 187`

I know of course is related with the SSL connection, but I'm kind of lost in this aspect. I've made some search over the internet, but I haven't found a solution for the problem.

Could you help me with this? Some guide on how to solve the problem...

This is the code that make the request:

```
$client = new Client();

$url = 'http://www.whoscored.com/Search/?t=' . $player["name"];

$crawler = $client->request('GET', $url);
```

Is there anyway to make the call without a cert?

**Comment by ssanders** [comment]
Try setting your client defaults for verify to false. Example in Guzzle 5:
```php
$client = new GuzzleHttp\Client(['defaults' => ['verify' => false]]);
```

**Comment by daniegarcia254** [comment]
@ssanders still getting the same error

My code would be like this right no, make sense?

```
    //Load Goutte Client (Web Scraping)
    use Goutte\Client;

    $client = new Client();
    $url = 'http://www.whoscored.com/Search/?t=' . $player["name"];

    $client = new GuzzleHttp\Client(['defaults' => ['verify' => false]]);

    $crawler = $client->request('GET', $url);
```

I mean you've told me to create a _GuzzleHttp\Client_ with the _verify_ option, but what I really need is a _Goutte\Client_ for the web scrapping.

**Comment by ssanders** [comment]
https://github.com/FriendsOfPHP/Goutte/issues/258

**Comment by mtdowling** [comment]
Looks like this issue was resolved in a duplicate posted to Goutte: https://github.com/FriendsOfPHP/Goutte/issues/258#issuecomment-178883238

Let me know if that is incorrect.
