### ISSUE TITLE
Caching in GuzzleHttp?

### ISSUE THREAD

**Issue by jayarjo** [guzzle/guzzle#1392]
How would one wire in the caching into current Guzzle?

**Comment by jeskew** [comment]
You can implement a [middleware](http://guzzle.readthedocs.org/en/latest/handlers-and-middleware.html#middleware) that checks requests for cached responses before sending them and then saves responses before returning them. You can take a look at https://github.com/Kevinrob/guzzle-cache-middleware as an example.
