### ISSUE TITLE
fifo concurrent requests?

### ISSUE THREAD

**Issue by natostanco** [guzzle/guzzle#1394]
As I understand it the current implementation only allows for a stack to run and wait for all the requests to complete. Is there a way to keep an `n` number of requests always open?

**Comment by jeskew** [comment]
You can configure how many requests should be in flight at the same time with a [`GuzzleHttp\Pool`](https://github.com/guzzle/guzzle/blob/master/src/Pool.php). This can be controlled with the `concurrency` option passed to the constructor. A usage example can be found [in the docs](http://guzzle.readthedocs.org/en/latest/quickstart.html#concurrent-requests).

**Comment by natostanco** [comment]
I already tried the pool implementation, and from my tests it seems to work in batches like I wrote. If a request of the current batch (concurrent number of requests set by `concurrency`) takes considerable longer than the others, a new batch cannot be initiated. Whereas it would be ideal to add and process requests as soon as old ones are completed. This can be done with the tick method in a troublesome inconsistent way. 

Also the pool does allow requests to have personal curl settings, not sure if intended and it is something that if someone wants to do has to use guzzle events or it is just a lack of feature?

**Comment by jeskew** [comment]
I've confirmed that a Guzzle 6 pool keeps X requests in flight, where X is the concurrency that has been configured on the pool.

Running this code:
```php
$client = new \GuzzleHttp\Client;
$request = new \GuzzleHttp\Psr7\Request('GET', 'https://aws.amazon.com/favicon.ico');
$requests = [
    'first' => $request,
    'second' => function () use ($client, $request) {
        return $client->sendAsync($request, ['delay' => 5000]);
    },
    'third' => function () use ($client, $request) {
        return $client->sendAsync($request, ['delay' => 5000]);
    },
    'fourth' => function () use ($client, $request) {
        return $client->sendAsync($request, ['delay' => 5000]);
    },
    'fifth' => function () use ($client, $request) {
        return $client->sendAsync($request, ['delay' => 5000]);
    },
    'sixth' => $request,
];

$pool = new \GuzzleHttp\Pool($client, $requests, [
    'concurrency' => 5,
    'fulfilled' => function ($response, $index) {
        echo "$index request completed\n";
    }
]);

$pool->promise()->wait();
```
will quickly print out:
```
first request completed
sixth request completed
```
followed by notifications for the other four requests 5 seconds later:
```
second request completed
third request completed
fourth request completed
fifth request completed
```

**Comment by natostanco** [comment]
thank you, yes your code works and it shows how to pass options for each requests, so maybe it should be in the docs. 
Even tough I did not find any significant improvements over my tick version which create requests and sends them 1by1 instead of creating an array of requests  and passing them in bulk to the pool.
