### ISSUE TITLE
How to get debug output in a variable?

### ISSUE THREAD

**Issue by shineability** [guzzle/guzzle#1395]
I know I can save the debug output to a file using a stream, but I actually want to collect the output of multiple requests, do some text manipulation and save it to the database. So, actually, I would like to have the debug output in a variable? Is this possible? Can I use a php://memory stream for this? Seems a bit hacky to me, though...

**Comment by jeskew** [comment]
You can use a `php://memory` stream or a `php://temp` stream, then extract its contents to a variable with `stream_get_contents`. Uniformly using streams means that Guzzle clients don't need to buffer debug output in memory.
