### ISSUE TITLE
Should not __toString() rewind the stream?

### ISSUE THREAD

**Issue by ivokund** [guzzle/guzzle#1396]
See the example:

```php
$response = $this->client->send($request, $options);

var_dump($response->getBody()->getContents()); // outputs normal response
var_dump((string)$response->getBody()); // outputs normal response
var_dump($response->getBody()->getContents()); // outputs empty string
```

Shoud not `\GuzzleHttp\Psr7\Stream::__toString` do a rewind after reading from the stream?
I ran into the problem while attaching Logging middleware, which caused  the response to be empty. 

`\GuzzleHttp\MessageFormatter::format` line 88 does this:

```php
$result = $response ? Psr7\str($response) : '';
```

And in `\GuzzleHttp\Psr7\str` there's a string cast on line 38 which causes the stream to be seeked to the end.

```php
return "{$msg}\r\n\r\n" . $message->getBody();
```

Using Guzzle 6.1.1

**Comment by darrenmothersele** [comment]
I think this also explains my issue. I found that when I used the log middleware with DEBUG log, then I couldn't access the body of the request. I had to do this in my own log middleware...

    $response->getBody()->rewind();

**Comment by ivokund** [comment]
Yes, the same workaround also worked for me. Nevertheless, I wouldn't say this is very intuitive.

**Comment by mtdowling** [comment]
Guzzle must adhere to PSR-7 here, which does not state that the stream is to be rewound after casting it to a string. You'll need to push for PSR-7 to be amended in order for us to be able to update Guzzle. Guzzle's implementation also matches Zend Diactoros.

http://www.php-fig.org/psr/psr-7/

**Comment by darrenmothersele** [comment]
PSR-7 says about `__toString()`...

> This method MUST attempt to seek to the beginning of the stream before
> reading data and read the stream until the end is reached.

That's not what currently happens. For example, if logging middleware is used to log the body of response then it is not available in __toString on the response afterwards.

**Comment by kkopachev** [comment]
It does seek https://github.com/guzzle/psr7/blob/master/src/Stream.php#L93

**Comment by ivokund** [comment]
More than a year later I came across this problem again. A simple rule of thumb for anyone having this issue:

Use `(string)$response->getBody()` instead of `$response->getBody()->getContents()`. The former returns always the full response, as the stream is rewound inside of `__toString()`. 

The latter may suddenly become empty, if someone decides to add some logging to your application and the stream has already been read before this line of code. For example using the built-in log format `\GuzzleHttp\MessageFormatter::DEBUG` causes this problem. 

As this is absolutely not intuitive in any sense, I would strongly suggest adding this little nuance to the manual to save future generations debugging time. :)

**Comment by NikitaObukhov** [comment]
5 years all php community struggles with this problem. I used rewind middleware (lol) with logging middle ware and it worked. For some reason on new project with new versions it does not work.

```
        $stack->push(
            Middleware::mapResponse(function (ResponseInterface $response) {
                $response->getBody()->rewind();
                return $response;
            })
        );

        $stack->push(
            Middleware::log($unilabApiLogger, new MessageFormatter(MessageFormatter::DEBUG))
        );
        
        $stack->push(
            Middleware::mapResponse(function (ResponseInterface $response) {
                $response->getBody()->rewind();
                return $response;
            })
        );
```

It is so annoying to get empty logs or empty response body so I simply added 2 rewind callbacks to make sure it would work. But now it does not. What a pity the whole PHP community cant make such a simple thing: http client that works.
