### ISSUE TITLE
How to use stored cookies for subsequent requests in the next request cycle?

### ISSUE THREAD

**Issue by adiachenko** [guzzle/guzzle#1400]
Consider the following code where I initialize Guzzle HTTP Client and perform 2 requests to external API. My first request provides the client with authentication cookie that is required to successfully perform second request (the one with `private/api/v2/json/contacts/list` route). This snippet works. The problem however, is that these steps must be repeated on each request cycle while ideally I want to use the old auth cookie that is valid for at least 15 minutes. 

Guzzle documentation states that you can use something like GuzzleHttp\Cookie\FileCookieJar to persist cookie (and it works) but there is no information on how to actually use this stored cookie in the next request cycle.

```
        $this->client = new HttpClient([
            'base_uri' => 'https://' . env('AMOCRM_SUBDOMAIN') . '.amocrm.com',
            // amoCRM API uses cookies to authenticate users
            'cookies' => true,
        ]);

        $this->client->post('private/api/auth.php', [
            'query' => [
                'type' => 'json'
            ],
            'form_params' => [
                'USER_LOGIN' => env('AMOCRM_USER_LOGIN'),
                'USER_HASH' => env('AMOCRM_USER_HASH'),
            ],
        ]);

        $response = $client->get('private/api/v2/json/contacts/list', [
            'query' => [
                'query' => $event['msg']['email'],
                'limit_rows' => 1,
            ],
        ]);

```

**Comment by jeskew** [comment]
You could pass the same cookie jar to multiple clients. Instead of simply passing `'cookies' => true` to a client constructor, [you can pass in an instance of `GuzzleHttp\Cookie\CookieJarInterface`](http://docs.guzzlephp.org/en/latest/quickstart.html#cookies). Depending on how the requests you describe are initiated, it sounds like you might want to use either the `GuzzleHttp\Cookie\FileCookieJar`, which stores cookies in a JSON file, or the `GuzzleHttp\Cookie\SessionCookieJar`, which stores cookies as a session parameter.

**Comment by adiachenko** [comment]
Can you provide me with more elaborate example? I've already tried CookieJar trick but nothing changes except for the fact that cookie is now persistent to disk. I still can't omit the first auth request in the example above. For practical purposes it works just like as bool value for me.

**Comment by jeskew** [comment]
The cookies you want persisted are probably session cookies, so you would need to configure your jar to persist those. The second parameter passed to either [the `FileCookieJar`'s constructor](https://github.com/guzzle/guzzle/blob/master/src/Cookie/FileCookieJar.php#L24) or [the `SessionCookieJar`'s constructor](https://github.com/guzzle/guzzle/blob/master/src/Cookie/SessionCookieJar.php#L23) is a boolean that indicates whether session cookies should be stored. It defaults to `false`.

**Comment by adiachenko** [comment]
I've tried all of those. Otherwise it would not create this issue. Cookie is indeed stored to disk/session with suggested solution but it works **only for subsequent requests in the same request cycle** where authentication request was performed. For example, when I hit this code the second time, I'll need to authenticate again. Otherwise, I'll get  `401 Unauthorized` response which means that cookie was not used

Although that API I communicate to is kinda weird (cookie authentication in REST API is by itself questionable) so I don't really think that Guzzle is at blame here. I am just trying to figure out whether I'm missing something essential here.

**Comment by adiachenko** [comment]
You were correct, it works fine. I think I've misplaced something while testing persisting cookies to disk previously which resulted in stored cookies not being used.

Sorry I've bothered you for nothing.

**Comment by jeskew** [comment]
The file cookie jar isn't really designed for concurrent access, so the behaviour you're describing could be caused by race conditions. The cookie file is loaded when the jar is instantiated, and the file is overwritten at the end of the request. You might want to use a custom jar that sources cookies from a shared store like Redis or APC as they are needed.

**Comment by Pezhvak** [comment]
thank you @jeskew you just helped me to solve this problem as well. documentation is not clear about it, here's what i've done and it's working for me:

```
$jar = new SessionCookieJar('PHPSESSID', true);
$client = new Client(['cookies' => $jar]);
```

**Comment by benjivm** [comment]
@Pezhvak I'm doing exactly as you are but the cookies are not being persisted. I can dump my `$client->getConfig('cookies')` and see them after a successful login request, however the browser does not see the cookies and no subsequent guzzle requests that require auth succeed (unless made in same request). I'm working in Lumen.
