### ISSUE TITLE
Documentation: Quickstart > Cookies section missing

### ISSUE THREAD

**Issue by vlakoff** [guzzle/guzzle#1401]
"Cookies" section is missing from the "Quickstart" page:
http://docs.guzzlephp.org/en/latest/quickstart.html#cookies

I don't understand why the Cookies link is present in the lateral ToC despite this.
Also, I've just built the documentation on my machine, there is no syntax error and Cookies section is present...

**Comment by Konafets** [comment]
It looks like this can be closed since the Cookie section is present in documentation. @sagikazarmark

**Comment by vlakoff** [comment]
I have just checked the link I posted, and the issue is still present.

**Comment by Konafets** [comment]
Just to make clear we talking about the same thing. Here is a screenshot of the page. I see a text about cookies.
<img width="1157" alt="screen shot 2016-12-15 at 18 09 50" src="https://cloud.githubusercontent.com/assets/363363/21234263/4baa5238-c2f2-11e6-9e86-7777f7dba286.png">

**Comment by vlakoff** [comment]
There is a "Cookies" link in the menu, but that's it.

The link doesn't work, because the actual content is missing.

**Comment by vlakoff** [comment]
Mmmmmm that's really strange, you actually have the content in your screenshot.

**Comment by vlakoff** [comment]
That's really fun, I do have the content in Chrome, but not in Firefox!

**Comment by vlakoff** [comment]
Found it. The culprit is my adblocker, the `#cookies` id triggered a rule `#cookies:not(body):not(html)`.

**Comment by vlakoff** [comment]
So, nothing wrong in the Guzzle documentation. I reported this issue to the addon author.

**Comment by kiboke** [comment]
Thank you for reporting to me. It will be fixed in the next version.
