### ISSUE TITLE
GuzzleHttp client is slow compared to file_get_contents

### ISSUE THREAD

**Issue by oliski** [guzzle/guzzle#1402]
Currently I am trying to start using GuzzleHttp client, however it is very slow, and often it won't be able to connect.
Everything is very fast with file_get_contents.

My configuration:
1. Apache with Windows 8, PHP 5.6.16 (cli) (built: Nov 25 2015 18:52:34)
2. Two hosts, when you open virtualhost A, it connects to virtual host B to fetch some information.
3. On host B - there are easy and simple PHP script: 
```
<?php
echo "OK";
```
4. On host A, there are following code:
```
$path = "http://local.server";
$url = 'a.php';

  $debugLog = fopen('php://temp', 'rw+');
        $client   = new \GuzzleHttp\Client([
                'base_uri' => $path,
                'debug'           => $debugLog,
                'http_errors'     => true,
                'connect_timeout' => 1,
                'timeout'         => 3,
            ]
        );

        try {
                $answer = $client->get($url);
       
            $response = $answer->getBody();

            $statusCode = $answer->getStatusCode();

        } catch (\GuzzleHttp\Exception\TransferException   $exception) {
            rewind($debugLog);
            $debug = stream_get_contents($debugLog);
        }
```

5. Inside debug variable, there are following information:
```
* Hostname local.server was found in DNS cache
*   Trying 127.0.0.1...
* Connected to local.server (127.0.0.1) port 80 (#0)
> GET /a.php HTTP/1.1
Host: local.server
User-Agent: GuzzleHttp/6.1.1 curl/7.42.1 PHP/5.6.16

* Operation timed out after 3000 milliseconds with 0 bytes received
* Closing connection 0
```

I also tried to increase limit to 10 seconds - sometimes it works OK, but often - does not work at all.

`echo file_get_contents($path.'/'.$url);` works like lighting.

Please, fix.

**Comment by mtdowling** [comment]
I'm pretty sure this is an environment specific issue and not something that needs to change in Guzzle. Maybe cURL is configured to run through a proxy through the HTTP_PROXY environment variable? Maybe you're hitting a different endpoint when you tried the same type of request with file_get_contents. Maybe you need to update curl? Maybe your server isn't responding properly to cURL? Maybe try taking a look at a tcpdump to see if any bytes are being transferred in the 3 seconds you're waiting on cURL to complete.

**Comment by oliski** [comment]
Hello, I was able to repeat problem with pure cURL - problem is not related to guzzle itself.

**Comment by nczepa** [comment]
slow guzzle depends, but keep attention to your environment! we had the same issue with a slow guzzle/6.2.1 and the problem was a special curl/7.29 version which caused the super slow performance, update the curl version was the solution
