### ISSUE TITLE
Possibility to turn of quoting of cookies

### ISSUE THREAD

**Issue by dvaeversted** [guzzle/guzzle#1405]
I am currently using Guzzle for interfacing with a webservice, where i need a session cookie that contains a "=" sign.
Unfortunately this webservice does not support quoted cookie values, which is done in the `CookieJar::getCookieValue()` method.

Possible solutions:
1. Don't escape because of a = sign
2. Allow overwriting the getCookieValue() method, by modifying the call in `CookieHeader::withCookieHeader()` to utilize late static binding.

For now i had to completely re-implement the CookieJarInterface, for my use case to work.

**Comment by mtdowling** [comment]
Hm... I'm open to changing the behavior here.

I wonder if we should be quoting at all. What does the cookie spec say? I wonder what other HTTP implementations do... For example, Firefox, Chrome, other PHP packages, etc.

**Comment by dvaeversted** [comment]
While using the webservice through either Firefox or Chrome, neither of them escapes the cookie data.

The RFC does allow escaping, but i think the correct way would be to only escape if the server also sends it escaped.

**Comment by mtdowling** [comment]
Thanks. I'm be open to changing it to match other prominent implementations.
