### ISSUE TITLE
[Question]: SessionCookieJar

### ISSUE THREAD

**Issue by debo** [guzzle/guzzle#1410]
I noticed that the SessionCookieJar plugin available in GuzzleHttp was abandoned in Guzzle. Is there a new viable alternative for it or nothing really? I still need the old SessionCookieJar behaviour because I am incrementally migrate from a legacy API and I can't lose that functionality straight away. Ideas?

**Comment by mtdowling** [comment]
It wasn't abandoned. It's in the master branch of Guzzle 6 and in the 5.3 branch.

**Comment by debo** [comment]
Yes but when I run composer install using Guzzle 6.x alias guzzlehttp it suggests me to use/install guzzle/guzzle because the former is abandoned/depracated. Am I getting this wrong?

**Comment by jeskew** [comment]
@debo I think you may have that backwards. [Guzzle 3 (`composer require guzzle/guzzle`)](https://packagist.org/packages/guzzle/guzzle) is deprecated and lists [Guzzle 6 (`composer require guzzlehttp/guzzle`)](https://packagist.org/packages/guzzlehttp/guzzle) as a suggestion.

**Comment by debo** [comment]
@jeskew not sure this is what I get for instance:
```bash
$ composer require guzzle/plugin-cookie
Using version ^3.9 for guzzle/plugin-cookie
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Installing guzzle/common (v3.9.2)
    Downloading: 100%

  - Installing guzzle/stream (v3.9.2)
    Downloading: 100%

  - Installing guzzle/parser (v3.9.2)
    Downloading: 100%

  - Installing guzzle/http (v3.9.2)
    Downloading: 100%

  - Installing guzzle/plugin-cookie (v3.9.2)
    Downloading: 100%

Package guzzle/common is abandoned, you should avoid using it. Use guzzle/guzzle instead.
Package guzzle/stream is abandoned, you should avoid using it. Use guzzle/guzzle instead.
Package guzzle/parser is abandoned, you should avoid using it. Use guzzle/guzzle instead.
Package guzzle/http is abandoned, you should avoid using it. Use guzzle/guzzle instead.
Package guzzle/plugin-cookie is abandoned, you should avoid using it. Use guzzle/guzzle instead.
Writing lock file
Generating autoload files
```
Anyway, what I'd like to know now is mainly what version should I use and what documentation should I read.

**Comment by jeskew** [comment]
Use [`guzzlehttp/guzzle`](https://packagist.org/packages/guzzlehttp/guzzle), which bundles cookie support.

**Comment by debo** [comment]
Okie dokie, thanks. What about response cache by the way?
