### ISSUE TITLE
[Question]: Cache response

### ISSUE THREAD

**Issue by debo** [guzzle/guzzle#1411]
I tried to follow Guzzle documentation about cache but it doesn't seem it's working; despite I added the subcriber to the client it looks like everytime I send a request, this gets actually performed intead of retrieve the response from cache. What am I missing? Thanks for your help.

**Comment by mtdowling** [comment]
What docs specifically? What's the HTTP request and response for a cache miss?

**Comment by debo** [comment]
I was reading this part http://guzzle3.readthedocs.org/plugins/cache-plugin.html

If I try two consequent calls to my API endpoint with debug enabled these are the response I get:

https://gist.github.com/debo/1e36a0db5168a8babb6c

**Comment by jeskew** [comment]
Both responses direct the cache not to store them. They have a `Cache-Control` header of 'no-cache, must-revalidate'

**Comment by debo** [comment]
Ok so pure API implementation; I thought guzzle could bypass those

**Comment by mtdowling** [comment]
The Guzzle cache plugin repo might be a better place for this issue if this issue is still unresolved: https://github.com/guzzle/cache-subscriber
