### ISSUE TITLE
[Question] Why am I triggering: Cannot change a rejected promise to fulfilled

### ISSUE THREAD

**Issue by alexsup** [guzzle/guzzle#1412]
I'm pooling a number of requests and I'm running into the error "Cannot change a rejected promise to fulfilled".

The slightly mystifying part is that it runs perfectly well locally AND when I run it remotely via the command line but when I try to run it via any sort of HTTP request I get the above error.

I'm using Laravel & Forge remotely and Homestead locally.

When I get rejected, the rejection reason is: "Generator is already finished".

It's at this point I'm stumped.

Any pointers would be hugely appreciated.

AB

**Comment by jeremeamia** [comment]
What version of PHP? And is it different between Homestead and Forge?

**Comment by jeremeamia** [comment]
Also, could you provide some code I can verify?

**Comment by GrahamCampbell** [comment]
> And is it different between Homestead and Forge?

Maybe one of them is older than the other so has different php versions?

**Comment by alexsup** [comment]
5.6.13 locally
5.6.15 remotely

**Comment by alexsup** [comment]
`$pool = new Pool($client, $poolRequests($ids), [

            'concurrency' => 100,

            // Callback on completion
            'fulfilled' => function ($response, $index) {

                $this->poolOutput[] = json_decode($response->getBody()->getContents());

            },

            // Callback on failed reponse
            'rejected' => function ($reason, $index) {
            },
        ]);

        $promise = $pool->promise();

        $promise->wait();

        return $this->poolOutput;
`

poolRequests() Simply yields a number of requests.

**Comment by alexsup** [comment]
As a further bit of information, if I set concurrency to 1, it succeeds. 

Anything above 1 triggers the above error.

**Comment by alexsup** [comment]
Finally, it seems that an extra Promise is triggered on the serve than locally.

**Comment by mtdowling** [comment]
Is `$poolRequests` a generator that also makes HTTP requests?

**Comment by alexsup** [comment]
`$poolRequests` looks like this:

```
private function poolRequests($ids)
{

    foreach ($ids as $id) 
    {
        $uri = "http://database-url/" . $id;
        
        yield new Request('GET',$uri);
    }

}
```

**Comment by alexsup** [comment]
For example. If I place the following code to run on the root domain address:

```
$client = new \GuzzleHttp\Client();

$requests = function ($total) {
    $uri = 'https://api.github.com';

    for ($i = 0; $i < $total; $i++) {
        yield new \GuzzleHttp\Psr7\Request('GET', $uri);
    }
};

$pool = new \GuzzleHttp\Pool($client, $requests(10), [
    'concurrency' => 5,
    'fulfilled' => function ($response, $index) {
        // this is delivered each successful response
    	var_dump("fulfilled");
    },
    'rejected' => function ($reason, $index) {
        // this is delivered each failed request
        var_dump("rejected");
    },
]);

// Initiate the transfers and create a promise
$promise = $pool->promise();

// Force the pool of requests to complete.
$promise->wait();
```
Locally, this is successful and "fulfilled is dumped 10 times.

Remotely on the server, however, it fails with `Exception in EachPromise.php line 172: Generator is already finished` and only dumps "fulfilled" 7 times.

Thanks!

**Comment by alexsup** [comment]
@mtdowling I'm afraid this doesn't solve the issue.

Here is the resulting error: 

<img width="1007" alt="screen shot 2016-02-29 at 11 21 46" src="https://cloud.githubusercontent.com/assets/13382954/13393055/f6610506-ded6-11e5-817b-5d38c3af88f5.png">
