### ISSUE TITLE
Debug request option causes fatal error.

### ISSUE THREAD

**Issue by PhaseCore** [guzzle/guzzle#1413]
When I do this.

```
$client = new GuzzleHttp\Client(['base_uri' => 'http://httpbin.org']);
$client->request('GET', '/get', ['debug' => true]);
```

I get

```
Warning: curl_setopt_array(): cannot represent a stream of type Output as a STDIO FILE* in C:\xampp\htdocs\xxx\lib\guzzle\GuzzleHttp\Handler\CurlFactory.php on line 57

Warning: curl_setopt_array(): cannot represent a stream of type Output as a STDIO FILE* in C:\xampp\htdocs\xxx\lib\guzzle\GuzzleHttp\Handler\CurlFactory.php on line 57

Warning: curl_setopt_array(): cannot represent a stream of type Output as a STDIO FILE* in C:\xampp\htdocs\xxx\lib\guzzle\GuzzleHttp\Handler\CurlFactory.php on line 57

Fatal error: Uncaught exception 'GuzzleHttp\Exception\RequestException' with message 'cURL error 0: The cURL request was retried 3 times and did not succeed. The most likely reason for the failure is that cURL was unable to rewind the body of the request and subsequent retries resulted in the same error. Turn on the debug option to see what went wrong. See https://bugs.php.net/bug.php?id=47204 for more information. (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)' in C:\xampp\htdocs\xxx\lib\guzzle\GuzzleHttp\Handler\CurlFactory.php:187 Stack trace: #0 C:\xampp\htdocs\xxx\lib\guzzle\GuzzleHttp\Handler\CurlFactory.php(485): GuzzleHttp\Handler\CurlFactory::createRejection(Object(GuzzleHttp\Handler\EasyHandle), Array) #1 C:\xampp\htdocs\xxx\lib\guzzle\GuzzleHttp\Handler\CurlFactory.php(147): GuzzleHttp\Handler\CurlFactory::retryFailedRewind(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Array) #2 C:\xampp\htdocs\xxx\lib\guzzle\GuzzleHttp\Handler\CurlFactor in C:\xampp\htdocs\xxx\lib\guzzle\GuzzleHttp\Handler\CurlFactory.php on line 187
```

**Comment by mtdowling** [comment]
It looks like Guzzle was not able to open a stream for curl to write to. The stream provided to curl has to be a STDIO stream, so custom streams are not supported. The logic for determining the default stream is in `debug_resource`: https://github.com/guzzle/guzzle/blob/master/src/functions.php#L85.

Has `STDOUT` been remapped to some custom stream in your script?

**Comment by mtdowling** [comment]
Does changing this line to use "rw" instead of "w" fix the issue?

https://github.com/guzzle/guzzle/blob/master/src/functions.php#L92

**Comment by DarkGhostHunter** [comment]
Hi [mtdowling](https://github.com/mtdowling), I'm having the same problem and changing `w` to `rw` on that line didn't fix the problem.

Some specs:

- Guzzle 6.2.0
- NGINX 1.9.4
- PHP 7.0.7 NTS x64
- Windows 10 x64

Changing `php://output` to `php://memory` only changes the "Output" debug string to "MEMORY".

The thing is, doing a `GET` to Google.com and getting the Body goes correctly as expected (minus the charset, of course), so it seems that could be a PHP Configuration thing. Need more info?

**Comment by DarkGhostHunter** [comment]
My hunch was right, it seems. **Guzzle won't work at all if the same instance of PHP is used to send the Request from Guzzle, and to respond that request**. Basically, one instance of PHP on the same server is a no go.

How to (temporally) fix this? I just elevated a second PHP-CGI listening in port :667, and in NGINX I used the `fastcgi_pass 127.0.0.1:667;` for the `http://game.dev/test`. Guzzle worked successfully with results.

May be from Guzzle this can be "fixed", but I doubt it.

Just a heads up for those who are running the same PHP instance for Request and Responses.

**Comment by JefferyHus** [comment]
@DarkGhostHunter solution isn't working for me, the issue comes and goes from time to time, it was working fine but fails today. If you can please provide any help.

OS: Win 7
Server: Apache
PHP: 7.0.10

**Comment by DarkGhostHunter** [comment]
@JefferyHus I think it won't work with Apache it self, as it will run in the same PHP thread or instance. Hence, why I migrated from Apache (PHP TS) to NGINX (PHP-FPM).

**Comment by JefferyHus** [comment]
@DarkGhostHunter Well I have just tested the script on an Nginx 1.10.0 server the same issue remains.

**Comment by karl-roberts** [comment]
If it helps at all, I'm encountering the same issue here without the use of Guzzle, just making a vanilla curl request. I've tried changing the mode parameter on the fopen function as suggested above and also ensured it's invoked only once in a script in case it didn't like being called multiple times, but with no luck.

Just my two pence here, thanks.

**Comment by akmua** [comment]
try, php://temp and w+

**Comment by progammer-rkt** [comment]
@akmua I tried your suggestion and it worked like a charm. Thank you.

**Comment by turtlegood** [comment]
So in my case I just set `debug` to false...

**Comment by CyanoFresh** [comment]
same on windows 10, php7.2. Headers are broken

**Comment by eteeselink** [comment]
When running on the PHP devserver, php 7.2.6 and windows 10, i was able to get it to work with 

    'debug' => fopen('php://stderr', 'w'),

**Comment by sagikazarmark** [comment]
This issue was automatically classified as stale because it lacks information or cannot be reproduced.

If you think the issue is still valid and/or misclassified, please comment on the issue thread
and provide additional information (if possible).

Also, since the time maintainers can spend on the project is limited, please provide
a possible solution if possible, especially if it involves a platform that we cannot
test ourselves (Windows, very old/specific PHP versions, etc).

Issues marked as stale with no further activity will be marked as `rotten`
at some point and will automatically be closed within 14 days.

We do this so that we can focus on high priority issues. Thank you for your understanding.

**Comment by subzerofx** [comment]
> When running on the PHP devserver, php 7.2.6 and windows 10, i was able to get it to work with
> 
> ```
> 'debug' => fopen('php://stderr', 'w'),
> ```

This helped. I had the same issue on Windows 10, XAMPP with PHP 7.

**Comment by StephanTie** [comment]
Thank you eteeselink and subzerofx
Your comment helped me on this problem on windows10, php 7 and apache 
changing statement in function debug_resource($value = null)
from:
  'debug' => fopen('php://output', 'w'),
to:
'debug' => fopen('php://stderr', 'w'),

**Comment by geosmart** [comment]
i resolve it by my incorrect Client constructor;
change 
```php
  $client = new Client(array('curl' => array('CURLOPT_SSL_VERIFYPEER' => false,),));
```
to
```php
        $client = new Client([
            'curl' => [CURLOPT_SSL_VERIFYPEER => false]
        ]);
```
and bingo

**Comment by sagikazarmark** [comment]
Hey guys!

Is this issue resolved then?

**Comment by MakerTim** [comment]
i get this problem when debug = true or when i set my curl options manually to debugging
on console it works, on web requests it doesn't
hope you will get the bug

**Comment by mihail-minkov** [comment]
Setting debug to false worked for me too.

**Comment by xbotkaj** [comment]
I got the same error -> CRITICAL - 2019-09-25 09:55:53 --> curl_setopt_array(): cannot represent a stream of type Output as a STDIO FILE*

After that uploaded on LINUX server and it works fine. Problem is with Windows version.
- PHP 7.3.9
- Apache 2.4.41
- Windows 8.1 x64

**Comment by chiragramjibhaipatel** [comment]
> When running on the PHP devserver, php 7.2.6 and windows 10, i was able to get it to work with
> 
> ```
> 'debug' => fopen('php://stderr', 'w'),
> ```

Thanks this fix works for me

**Comment by herecto** [comment]
guzzlehttp\guzzle\src\Utils.php;
/**
     * Returns a debug stream based on the provided variable.
     *
     * @param mixed $value Optional value
     *
     * @return resource
     */
    public static function debugResource($value = null)
    {
        if (\is_resource($value)) {
            return $value;
        }
        if (\defined('STDOUT')) {
            return \STDOUT;
        }
        dump($value);
	//return \GuzzleHttp\Psr7\Utils::tryFopen('php://output', 'w');
    }
