### ISSUE TITLE
Cookies not being set on (GET) request

### ISSUE THREAD

**Issue by MLoureiro** [guzzle/guzzle#1415]
Hi

I haven't found a doc for issue reporting, so I hope everything is ok.

I'm trying to send a request `GET mydomain.dev/some/path` **with a (new) cookie**.
After several tests I discovered the cookie wasn't being sent, and the reason is that `GET` is being skipped [here (PrepareBodyMiddleware.php#L18)](https://github.com/guzzle/guzzle/blob/master/src/PrepareBodyMiddleware.php#L18).

I don't know the implications of this, not sure if it is a bug.
Is there a way to achieve this?

**Comment by mtdowling** [comment]
The PrepareBodyMiddleware has nothing to do with Cookies. It only prepares the body before sending a request.

Can you share some code that isn't working? What version of Guzzle are you using?

**Comment by MLoureiro** [comment]
Hmm, it makes sense.

What I am doing is something like:
```php
$url = $this->getPlatformUrl();       // returns 'mydomain.dev'
$token = $this->getPlatformToken();   // returns an hash: 'ba5170067e4d5c1f75fffc1bc54913a0'

$jar = new \GuzzleHttp\Cookie\CookieJar();
$jar->setCookie(
  new \GuzzleHttp\Cookie\SetCookie([
    'Domain' => $url,
    'Name' => 'MyCookie',
    'Value' => $token,
  ])
);

$response = $this->getRestClient()->request(
  'GET',
  "{$url}/some/path",
  ['cookies' => $jar]
);

// ...
```
I've managed to make it work by forcing the cookie header (into options) as:
```php
'headers' => ['Cookie' => ["MyCookie={$token};"]]
```

But I would like to know if I'm doing something wrong.
I've confirmed that the cookie and the jar is made correctly, but could only track the execution till the [Middleware#36](https://github.com/guzzle/guzzle/blob/6.1.1/src/Middleware.php#L36), and dumping  the `$handler` it will output `GuzzleHttp\PrepareBodyMiddleware Object`. That's why I've tracked the cookies till [PrepareBodyMiddleware#L18](https://github.com/guzzle/guzzle/blob/6.1.1/src/PrepareBodyMiddleware.php#L18)

I'm using Guzzle 6.1.1.

**Comment by mtdowling** [comment]
The Domain is not a full URL. It's just the domain of the cookie and it's used when matching a host against available cookies in the jar. It should match the `$request->getUri()->getHost()` return value.

See https://github.com/guzzle/guzzle/blob/master/src/Cookie/SetCookie.php#L335
