### ISSUE TITLE
Url encoding breaks request

### ISSUE THREAD

**Issue by juresrpcic** [guzzle/guzzle#1417]
I'm sending a simple POST request that has a "not_before_date" among the query parameters. However I try to pass that to Guzzle, it encodes **&not_before_date** to **¬_before_date**

This is how it should look like:
`[query:GuzzleHttp\Psr7\Uri:private] => limit=300&before_date=2016-02-29&not_before_date=2016-02-28`

And this is how Guzzle forms the URL string:
`[query:GuzzleHttp\Psr7\Uri:private] => limit=300&before_date=2016-02-29¬_before_date=2016-02-28`

My request code looks like this:
```php
$response = $client->request('POST','/api/accounts/' . $mentionAccountIdLocal . '/alerts/999/mentions', [
    'query' => [
        'limit' => 300,
        'before_date' => $dateEnd, // return older than this date
        'not_before_date' => $dateStart // ignore older than this date
    ],
    'handler' => $tapMiddleware($clientHandler)
]);
```

Even if I try to manually build the request string, the encoding kicks in (also encodes my & characters in that case). Is there a way to hard-bypass this encoding?

Thanks.

**Comment by mtdowling** [comment]
Maybe you have some kind of special character in your query string?

All Guzzle does is pass the value to http_build_query: https://github.com/guzzle/guzzle/blob/master/src/Client.php#L350.

Try providing your array directly to http_build_query. If it still gives you weird output, then there are either special characters in your string, or there is a bug in your version of PHP.

**Comment by juresrpcic** [comment]
Turns out it was a mention.com api issue in the end (they disabled part of their documented api). Guzzle is working fine - I guess **¬_before_date** was just a display issue while the actual get command got through fine (but it was hard to figure out where the issue lies). Thanks for the **http_build_query** tip, could come in handy for debugging.

Guzzle remains undefeated :+1:
