### ISSUE TITLE
When New Version (6.1.2) Deployed

### ISSUE THREAD

**Issue by lexakozakov** [guzzle/guzzle#1418]
Does anybody know when a new version (6.1.2) is deployed? 

Guzzle has critical fixes in master branch, but they should be released in order to fetch these fixes in composer.

Thank you.

**Comment by mtdowling** [comment]
Me or @jeskew will tag next week.

**Comment by lexakozakov** [comment]
@mtdowling Great! :+1:

**Comment by lexakozakov** [comment]
@mtdowling 
Hello, do you have any update? 

Thank you.

**Comment by jeskew** [comment]
@lexakozakov Version 6.2.0 is now available.
