### ISSUE TITLE
HTTP Streaming connection

### ISSUE THREAD

**Issue by aali1** [guzzle/guzzle#1421]
I am trying to use Guzzle to create a http streaming connection (comet keep-alive) but I don't know how to keep the connection open and wait for the data streams to arrive. My current solution uses fsockopen which writes the data using POST and wait for the stream while(!ptr->eof).

Is there a way to achieve this using Guzzle?

**Comment by mtdowling** [comment]
What happens when you try to make the call right now with Guzzle? Does it timeout, or just not wait for any data at all?

**Comment by aali1** [comment]
The function did not get the buffer or body.

Is the below function correct to use for this purpose?

// Send an asynchronous request.
$request = new \GuzzleHttp\Psr7\Request('POST', 'http:/myurl.com');
$promise = $client->sendAsync($request)->then(function ($response) {
    echo 'Buffer:  ' . $response->getBody();
});
$promise->wait();

**Comment by mtdowling** [comment]
Guzzle doesn't have any explicit promise to support Comet connections. Other people have claimed that they have been able to use curl with Comet, so it's possible it's supported, but perhaps with some minor curl option tweaks.

I'll go ahead and close this issue, but please circle back and update this thread if you are able to figure it out.
