### ISSUE TITLE
Curl error #28

### ISSUE THREAD

**Issue by Sixuan** [guzzle/guzzle#1423]
Hi, we are using your library, and we're trying to catch curl error #28 specifically and then doing something for that. Is there a build-in method to check the curl error number in your library? Or we'd have to do stripos($e->getMessage, "cURL error 28") === 0 in our code? Please advice, thanks!

**Comment by GrahamCampbell** [comment]
Just read the source code?

https://github.com/guzzle/guzzle/blob/master/src/Handler/CurlFactory.php#L177

**Comment by GrahamCampbell** [comment]
https://github.com/guzzle/guzzle/blob/master/src/Exception/RequestException.php#L184

**Comment by GrahamCampbell** [comment]
the "error" key should set to 28 in that array - i've not tested it though - i just got their reading the code

**Comment by mtdowling** [comment]
@GrahamCampbell is correct (thanks Graham!)
