### ISSUE TITLE
curl_setopt_array(): cannot represent a stream of type Output as a STDIO FILE*

### ISSUE THREAD

**Issue by pritis** [guzzle/guzzle#1424]
Hi,

I have installed the guzzle with laravel 4 and while making a post request following error is been thrown.

curl_setopt_array(): cannot represent a stream of type Output as a STDIO FILE*

$client = new Client(['debug'=>true,'exceptions'=>false]);
  $res = $client->request('POST', 'url',  [
            'form_params' => [
               'auth' => 'yes'
             ]
        ]);

**Comment by mtdowling** [comment]
This looks like a duplicate of https://github.com/guzzle/guzzle/issues/1413. I'll close in favor of that issue. Can you let us know what OS you're using?

**Comment by APrakriti** [comment]
same error 
ErrorException in CurlFactory.php line 56:
curl_setopt_array(): cannot represent a stream of type Output as a STDIO FILE*



            $client =   new \GuzzleHttp\Client();
            
            $response = $client->post($endPoint, [
                    'debug' => true,
                    'cert' => storage_path('csr/'.$cerFile),
                    'body' => $requestPurchaseXml,
                ]
            );

            dd($response);

**Comment by nguyenduytan** [comment]
I got same error, Dont know how to fix :(

**Comment by renaudcollet** [comment]
If you set debug to false in your guzzle post method, you will see an http error 419, caused by missing csrf token.
See here : https://stackoverflow.com/questions/46266553/why-does-the-laravel-api-return-a-419-status-code-on-post-and-put-methods

**Comment by fangdashng** [comment]
l got the same error, my develop environment is  window and apache,  The sign is very helpless
