### ISSUE TITLE
How can I "fire and forget" request?

### ISSUE THREAD

**Issue by sc0rp10** [guzzle/guzzle#1425]
I need run request and don't wait its finish. How can I do it with guzzle 6?
I tried:
```php
$start = time();
$client = new Client();

$p = $client->getAsync('http://httpbin.org/delay/10');
$p->wait();

$end = time();

printf("elapsed: %d sec\n", $end - $start);
```
and got output "elapsed: 11 sec", but I want to see "elapsed: 1 sec" 😃

**Comment by shaunbramley** [comment]
```
$client = new GuzzleHttp\Client();

$start = time();
$p = $client->getAsync('http://httpbin.org/delay/10');
$p->wait();
$end = time();
printf("elapsed: %d sec\n", $end - $start);


$start = time();
$p = $client->getAsync('http://httpbin.org/delay/10');
$end = time();
printf("elapsed: %d sec\n", $end - $start);
```

will result in:
```
Shauns-MacBook-Air:guzzle-1425 shaunbramley$ php newfile.php
elapsed: 10 sec
elapsed: 0 sec
Shauns-MacBook-Air:guzzle-1425 shaunbramley$ 
```

Provided that your host OS has curl available.

One thing to note within your code example, calling  `$p->wait();` tells the application to sit and wait for the response before continuing.

**Comment by sc0rp10** [comment]
@shaunbramley your code actually doesn't made request. If you have own webserver, you can check it with access logs.

**Comment by gmponos** [comment]
Your issue seems to be similar with mine. https://github.com/guzzle/guzzle/issues/1429
I would love to have an answer for these.

**Comment by mtdowling** [comment]
See the comment in for an explanation of how Guzzle's async functionality works: https://github.com/guzzle/guzzle/issues/1429#issuecomment-197152914
