### ISSUE TITLE
Impossible to install as Composer detects wrong php version

### ISSUE THREAD

**Issue by JLBA** [guzzle/guzzle#1427]
Hello,

I'm developing a website with Contao 3.5.6 in MAMP PRO 3.2.1.
Composer ask me to replace discordier/httprequestextend by guzzlehttp/guzzle.
I would like to but get this message : 
```
$ /usr/bin/env php -d memory_limit=1G -d max_execution_time=3000 composer.phar update --no-ansi --no-interaction -v --profile
[9.7MB/0.12s] Loading composer repositories with package information
[10.1MB/1.41s] Updating dependencies (including require-dev)
[605.9MB/37.14s] Your requirements could not be resolved to an installable set of packages.
[605.9MB/37.14s] 
  Problem 1
    - Installation request for guzzlehttp/guzzle >=6.1.1.0,<6.2-dev -> satisfiable by guzzlehttp/guzzle[6.1.1].
    - guzzlehttp/guzzle 6.1.1 requires php >=5.5.0 -> your PHP version (5.4.45) does not satisfy that requirement.

[205.0MB/38.26s] Memory usage: 204.98MB (peak: 606.12MB), time: 38.26s
```
Or I'm not using php 5.4.45 but 5.6.7 in my MAMP Pro host. 
What to do ? Perhaps does Composer detect OS X php version instead of MAMP version ?
Thanks for help.

**Comment by jeskew** [comment]
Composer will detect the version of whatever PHP runtime is being used to execute it. You would need to upgrade the PHP version on OS X or run composer from the MAMP host to install Guzzle 6.

**Comment by JLBA** [comment]
I'm running composer installed in Contao so from within mamp host.
