### ISSUE TITLE
HTTP hostname and TLS SNI hostname mismatch

### ISSUE THREAD

**Issue by bradcornford** [guzzle/guzzle#1430]
When creating a Guzzle Client with a proxy, when the accessed website is behind CloudFlare, then an error is display:

```php

$client = new GuzzleClient([
    'base_url' => URL,
    'defaults' => [
        'proxy' => PROXY
     ]
]);

$client->getEmitter()->attach(new Cookie(new CookieJar()));

$response = $client->post('', [
    'body' => [
        'data' => 1
    ]
]);

```

Error 1013 - HTTP hostname and TLS SNI hostname mismatch

However, creating this request via PHP's in built curl functions works as expected:

```php

$ch = curl_init();

curl_setopt($ch, CURLOPT_URL, URL);
curl_setopt($ch, CURLOPT_POST, 1);
curl_setopt($ch, CURLOPT_POSTFIELDS, 'data=1');
curl_setopt($ch, CURLOPT_PROXY, PROXY);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
curl_setopt($ch, CURLOPT_FOLLOWLOCATION, true);
curl_setopt($ch, CURLOPT_HEADER, true);
curl_setopt($ch, CURLOPT_COOKIEJAR, 'cookies.txt');
curl_setopt($ch, CURLOPT_COOKIEFILE, 'cookies.txt');
curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);

$response = curl_exec($ch);

curl_close($ch);

```

Even the request from command line via curl works as expected:

``` bash
curl -v -b ~/cookiefile -L --proxy PROXY --data "data=1" URL
```

**Comment by ant-hill** [comment]
@bradcornford  
You can create GuzzleClient without "base_url" param and pass You url in $client->post(),
Ex.
```php
$client = new GuzzleClient([
    'defaults' => [
        'proxy' => PROXY
     ]
]);

$response $client->post(URL, [
    'body' => [
        'data' => 1
    ]
]);
```

**Comment by bradcornford** [comment]
@ant-hill Yeah i understand that, the code above is just an example of how i was calling the Guzzle Client vs base curl.

**Comment by mtdowling** [comment]
Can you provide debug output please?

**Comment by bradcornford** [comment]
@mtdowling I managed to resolve my issue by installing php-curl package. So it does seem that something is missing within the package to handle the different in hostnames.

**Comment by mtdowling** [comment]
Hm... That doesn't really make sense that you could use curl_* functions in PHP, but Guzzle was unable to use cURL. I'll go ahead and resolve, but let me know if you are able to identify the root cause.
