### ISSUE TITLE
on_stats and 301 redirects

### ISSUE THREAD

**Issue by natostanco** [guzzle/guzzle#1437]
I am having trouble accessing the body of a request through the `on_stats` callable function with 301 redirects. What I get is the nginx 301 moved permanently page instead of the actual page of the effective url. Can someone enlighten me on this? Shouldn't guzzle follow redirects by default?

**Comment by mtdowling** [comment]
Guzzle follows redirects by default. See: http://docs.guzzlephp.org/en/latest/request-options.html#allow-redirects.

Can you provide a reproducible test case or send a pull request with a failing test case?

**Comment by natostanco** [comment]
sorry, I think it is my mistake, `on_stats` gets called at every redirect, so when it its the 301 it retrieves the 301 message body, but on the last run, when it gets 200, it retrieves the correct body.
