### ISSUE TITLE
Guzzle 5 - Post Request Not Asynchronous?

### ISSUE THREAD

**Issue by pihish** [guzzle/guzzle#1439]
I have the following Guzzle 5 request:

```
$this->guzzle->post("http://endpoint/i/control", array(
    'body' => array(
        'keyone' => 'valueone',
        'keytwo' => 'valuetwo' 
    ),
    'future' => true
));
```

I am under the impression that the above is an async operation because the _future_ key is set to ```true```. I control the endpoint the above request hits, and when I put a 5 second sleep function in the script that serves the endpoint, my request takes 5 seconds longer.

How do I serve a true non-blocking asynchronous request using Guzzle 5?

**Comment by mtdowling** [comment]
You need to tick the curl event loop in order to actually perform the request.

You'd need to throw this request off to a thread or hook Guzzle up to React or some other async PHP library. See https://github.com/WyriHaximus/ReactGuzzleRing

**Comment by pihish** [comment]
Guzzle 5 doesn't support async requests out of the box?  I use the AWS PHP V3 SDK which internally use Guzzle 6 and I am able to do non-blocking S3 uploads / downloads without adding on a separate async library.  

Is this correct?

**Comment by mtdowling** [comment]
Can you be more clear about your expectation? Are you wanting the request to complete in the background somehow (like with threads)? Are you wanting the request to complete in some kind of async event loop like node.js? Are you wanting to initiate a bunch of requests and then block on them all concurrently?

**Comment by pihish** [comment]
I am looking for it to behave like in Node.  I want to run additional code without waiting for the POST response.

**Comment by mtdowling** [comment]
In that case you need to use the react bindings and wrote non blocking code in an event loop (which react provides).
