### ISSUE TITLE
Guzzle 5.3: Misleading docblock for body in Request-constructor

### ISSUE THREAD

**Issue by dbrumann** [guzzle/guzzle#1448]
The docblock for `Request::__construc()` currently says that the 4th argument `$body` is mixed (see: https://github.com/guzzle/guzzle/blob/5.3/src/Message/Request.php#L31). As far as I can tell it can either be a StreamInterface or null. It would be helpful, e.g. for IDEs like PHPStorm if this is more accurate.
I would like to propose to either change the docblock to:

```
    /**
     * [...]
     * @param StreamInterface|null $body    Body to send with the request
     * [...]
     */
```

or change the constructor itself to call `Stream::factory($body) before setting the value`:

```
        if ($body !== null) {
            if (!($body instanceof StreamInterface)) {
                $body = Stream::factory($body);
            }
            $this->setBody($body);
        }
```

I can open a PR, but I wanted to make sure this change is actually appreciated and which of these is preferred.

**Comment by mtdowling** [comment]
See PR for comments

**Comment by dbrumann** [comment]
How about the other proposed change then (changing param to `StreamInterface|null`)? It would be nice if IDE's like PHPStorm warned about string not being a valid argument here.
