### ISSUE TITLE
This cookie is not supported？

### ISSUE THREAD

**Issue by shijunti19** [guzzle/guzzle#1451]
guzzle 6.0
This cookie is not supported？

XSRF-TOKEN=eyJpdiI6InhicXdZTE95ajJ5ejUwNmp1VjNTMHc9PSIsInZhbHVlIjoiY0I3TDVXVUw2Mm9pZGpaOFhOME1OWHZoWFZlZXdvUWZ0bk5FQUh5Y3h1UVRkeWlFeTE4WVVwQStyaG9aREdDTE5pMnI5MXA3QVA0TGNhSElCemo2U2c9PSIsIm1hYyI6Ijk0Mzg1Mzg5OTJjMjYzODEyMWUwMzZlMTUyYWFkN2NiOGY3MjY2ZmUyYTI1OGRiYjczZWIyZTIxNjY0NDA3NDkifQ%3D%3D; laravel_session=eyJpdiI6Ijlha0R4QVg2RnZpbUtPekNtVGU1a1E9PSIsInZhbHVlIjoiUytmekdkQXZMSTdic0FvWFlHQjU5ZkZabTF1NldnU3Bka2hmdUcwT0VWdDVxcWpuQnVsclM0XC9GVEJSUUYwVHFzU3R6dGFqT0ZjQ1RBNmFVcVRHdHpRPT0iLCJtYWMiOiJiZGVkODI1OTMxNmFlMWFjZWZlYzg1Y2E1ODIxMGQ3NDMyNjI5NDE0YjMyZmNjMTM2NDFlODBiOWY5MTliZDViIn0%3D

Incoming how this

**Comment by mtdowling** [comment]
Can you elaborate please?

**Comment by mtdowling** [comment]
Let me know if you can provide more info.
