### ISSUE TITLE
Query in $options favored over query in $request

### ISSUE THREAD

**Issue by nikita2206** [guzzle/guzzle#1452]
If I call `$client->request("GET", "http://google.com/search?q=foo", ["query" => ["q" => "bar"]])`

The request that will be issued is `GET /search?q=bar`. Now that by itself is not a problem (one could argue on this one though), but the problem comes when my client was instantiated as `new Client(["query" => ["q" => "bar"]])`.

Now even code like `$client->request("GET", "http://google.com/search?q=foo")` will issue a request with `q=bar`.
What is even more troublesome is when I have `new Client(["query" => []])`, it will disregard any query I will put in the `$request` (but not in the `$options`).

Ideally I think there's no need for any kind of deep-merging too (which might come as a first solution to the problem), because request middleware feels as a much better solution for this scenario (when I need f.e. to add any kind of `query` information to every request).

In reality, having some weight of keeping BC, I think it would be better to give preference to the `$request` object always... or at least in this order `$options`, `$request`, `$this->config` (that would be more BC safe but would also add more code bloat and metal overhead)

**Comment by mtdowling** [comment]
I don't think this can change. `query` is really meant to be a string value that replaces the query string of a request. If you provide an array, Guzzle will simply call `http_build_query` to convert it to a string. It then takes that string value and [overwrites](https://github.com/guzzle/psr7/blob/master/src/functions.php#L237) any previously provided query string in the request (e.g., if you provided  a query string in the URI).

Providing a default `query` value in the client constructor tells Guzzle that you want to send all requests with the `query` string provided in the constructor regardless of the query string provided in the URI of a request. The only way to override this default setting is to provide a `query` request option when sending the request.

If you want to add query string parameters to a request in a different manner than what's provided by default, then you'd need to implement a custom middleware.

**Comment by nikita2206** [comment]
Well, it's all up to you.
I will reiterate though. I don't want to add a query string parameters to a request in a different manner. It's not a feature request.

I just wanted to point out that:

1. It's unnatural/misleading that part of the first argument is being discarded when there's some specific value passed in the second (optional) parameter.
2. It's weird/unnatural/unexpected that part of the first argument is being discarded when there's some specific value passed in the constructor of the Client earlier.

Imagine I had some kind of DB abstraction that would have this kind of logic:
```php
class Connection {
  ...
  public $predicate;
  ...
  function query(Query $q) {
    if ( ! empty($this->predicate)) {
      $q = $q->withWhere($this->predicate);
    }

    ...
  }
  ...
}
```

And someone could just initialize it like this: `$c = new Connection($predicate = "status = 'active'");` so that all queries would be overwritten to have `WHERE status = 'active'`... even the ones that already had some predicate. It doesn't really make sense for me.

So when I pass an instance of `Request` to `Client#request()` I expect exactly this request to be sent.
A feature of adding some query parameters to every request though may be highly demanded by the users, that's expected; but it also is very easily implemented in the userland code (outside of guzzle library), you (as a user of guzzle library) would just need a thin decorator for `Client` which would modify any incoming `Request` the way you'd like it to (there's even no need for middleware features of guzzle).

Granted that is a feature intended to *easily* add query parameters without needing to write another class or anything like that. But this feature is currently broken. If there's a need for a solution at the same time easy to use and powerful enough so that it wouldn't play badly with input arguments, perhaps it would be better to have a couple of already implemented middlewares one of which would be `AddQueryMiddleware`:

```php
class AddQueryMiddleware
{
    /** @var Query */
    public $query;

    public function __invoke(callable $handler)
    {
        return function (RequestInterface $r, array $options) use ($handler) {
            return $handler($this->applyQuery($r), $options);
        };
    }

    private function applyQuery(RequestInterface $r)
    {
        // $r->withQuery(...);
    }
}
```

This way there's no confusion between parameters of `request()` method, and middleware could have some extended functionality such as merging of queries.

**Comment by mtdowling** [comment]
The query component of a URI is not always a key value pair string. It can be anything that adheres to the query [ABNF](https://tools.ietf.org/html/rfc3986#section-3.4).

Even when it is a key value pair, the way in which multiple key value pairs are serialized into a string could vary based on the server you're sending the request to. For example, some servers accept multiple key value pairs of the same name (e.g., "foo=bar&foo=baz"), whereas others might require numerical indices to distinguish them (e.g., "foo[1]=bar&foo[2]=baz"), and some might just require "[]" after a variable name which means the value should be a list of named values.

Trying to take a previously serialized query string component of a URI, parse it (hoping it is a key value pair and that you can identify how to unmarshal it into an some kind of array data structure), then merge in the provided `query` array or string, and then re-serialize the query component back into the original form -- is a lot of added complexity. It might be convenient to have that functionality built-in to Guzzle, but I'm weary of the added complexity.

Perhaps there could be a robust library that abstracts query strings a bit more for PSR-7 requests and another library that plugs that abstraction into Guzzle.
