### ISSUE TITLE
CURL Error

### ISSUE THREAD

**Issue by bretanac93** [guzzle/guzzle#1454]
Please, could somebody tell me what is this?, I'd looking for it on stackoverflow, but the entries there are too old, and the only solution I'd found doesn't work for me, they told to use Guzzle v4, but that version is not maintained anymore, please, request your help, regards.

cURL error 77: error setting certificate verify locations:
CAfile: /Users/user/Projects/clinica/app/var/jwt/private-test.pem
CApath: none (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)

**Comment by mtdowling** [comment]
Looks like your cacert is invalid. I don't know why, but you might want to verify that you are able to read from the file and that the contents are correct.
