### ISSUE TITLE
Refactor applying request options.

### ISSUE THREAD

**Issue by WJRovers** [guzzle/guzzle#1455]
What I found out is there is **no realm** entered in the second request during digest, which obviously is essential to make digest work. I've tried to make this reproducible via the httpbin.org to test a digest.

The (first) request gets a first 401 response with a WWW-Authenticate header like:
`WWW-Authenticate: Digest nonce="03a62350e87c9e3b663d6da323ba51c1", opaque="7f73f2dd8565f92b13c44e0dc5cd9ca9", realm="me@kennethreitz.com", qop=auth`

The (second) request has a security header like:
`Authorization: Digest username="user",realm="",nonce="03a62350e87c9e3b663d6da323ba51c1",uri="/digest-auth/auth/user/passwd",cnonce="79a12dbdb0b81c12a38d2bf8a593b24b",nc=00000001,response="d92d576fa7f1efbf10333251167d4983",qop="auth",opaque="7f73f2dd8565f92b13c44e0dc5cd9ca9"` 

Here is information about the versions/software used:

``` bash
Composer show -i
guzzlehttp/guzzle                  dev-master 6a173dd Guzzle is a PHP HTTP client library
guzzlehttp/promises                1.1.0              Guzzle promises library
guzzlehttp/psr7                    1.2.3              PSR-7 message implementation

curl -V
curl 7.48.0 (x86_64-pc-win32) libcurl/7.48.0 OpenSSL/1.0.2g zlib/1.2.8 WinIDN libssh2/1.7.0 nghttp2/1.9.2
```

The simple php code that can be used for reproducing:

``` php
$url = "http://httpbin.org/digest-auth/auth/user/passwd";
$response = $client->get($url, [
                'auth' => [
                    'user',
                    'passwd',
                    'digest'
                ],
            ]);
echo $response->getStatusCode();
```

**Comment by mtdowling** [comment]
Thanks for the report. The auth handling for Digest is located here: https://github.com/guzzle/guzzle/blob/master/src/Client.php#L336. We are relying on cURL to handle challenge/response flow. Are we missing something that's needed for cURL to handle this properly?

**Comment by mtdowling** [comment]
If curl doesn't expose those headers through a callback, the it sounds really hacky to use write a curl cookie jar to disk and then read from it immediately in order to populate a Guzzle cookie jar. At that point, it would probably be better to just implement digest auth as a middleware so it can work with any HTTP handler.

Agreed on request creation. I'd really like to see a request factory abstraction. Maybe we should add an issue to track this feature request so there will be visibility on it.

**Comment by lucklo** [comment]
I think that in general we should have authentication strategies decoupled from basic HTTP request handling. 
All of them (Digest, Basic, OAuth) int the end are based on Headers modification that could be handled as middleware, that could allow developers to handle or custom auth systems in consistent way.

**Comment by powdermnky007** [comment]
yes, please also let response remind you if you need to enable cookies
spent most of a day debugging perfectly good code :(
figured it out by this previous issue, which redirected to here.
https://github.com/kennethreitz/httpbin/issues/124
