### ISSUE TITLE
cURL error 0: The cURL request was retried 3 times and did not succeed.

### ISSUE THREAD

**Issue by tysonjallen** [guzzle/guzzle#1456]
Receiving many `4xx` to `5xx` responses in a short timespan causes the following error.

```cURL error 0: The cURL request was retried 3 times and did not succeed. The most likely reason for the failure is that cURL was unable to rewind the body of the request and subsequent retries resulted in the same error. Turn on the debug option to see what went wrong. See https://bugs.php.net/bug.php?id=47204 for more information. (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)```

The same number of `2xx` to `3xx` responses works as expected

Easiest way to reproduce

```php
$client = new Client();
for ($i = 0; $i < 1000; $i++) {
	try {
		$client->get('http://httpstat.us/422');
	} catch (\Exception $exception) {
		if (is_null($exception->getResponse())) {
			die($exception->getMessage());
		}
	}
}
```

**Comment by mtdowling** [comment]
I wasn't able to reproduce. Can you enable debug output as suggested in the error message?

**Comment by tysonjallen** [comment]
**After digging deeper I can only get the error to occur when running the script with php installed on Windows.** (was able to replicate on 2 windows systems in the office running version 7.0.1 and 5.6.16)

I cannot replicate when running with php on Linux.

---

With debug output enabled I don't see anything related to the request that fails. This is the last request logged which is number 507 (`GET /422?507`).

```
* Found bundle for host httpstat.us: 0x6f10910
* Re-using existing connection! (#0) with host httpstat.us
* Connected to httpstat.us (23.99.0.12) port 80 (#0)
> GET /422?507 HTTP/1.1
Host: httpstat.us
User-Agent: GuzzleHttp/6.2.0 curl/7.43.0 PHP/7.0.1

< HTTP/1.1 422 Unprocessable Entity
< Cache-Control: private
< Content-Length: 24
< Content-Type: text/plain; charset=utf-8
< Server: Microsoft-IIS/8.0
< X-Powered-By: ASP.NET
< Access-Control-Allow-Origin: *
< Set-Cookie: ARRAffinity=2d2752e4834f8095fcc592cb8043d327dbcfb2f170fcfb2d3f5193bdce552f98;Path=/;Domain=httpstat.us
< Date: Thu, 21 Apr 2016 15:26:19 GMT
< 
* Connection #0 to host httpstat.us left intact
```

Script dies on failed request number 508

**Comment by mtdowling** [comment]
Hm... I wonder if there's anything we can do in Guzzle to address this or if it's just a cURL bug specific to Windows.

**Comment by mtdowling** [comment]
This is an environment specific issue that is at a lower level than Guzzle. I don't think there's anything we can do in Guzzle itself to address this.

**Comment by slince** [comment]
I have same problem, I run my script with window cli mode, This error is encountered when the request is made too many times

**Comment by kennethfan** [comment]
I have same problem, I run my script with window cli mode, This error is encountered when the request is made too many times

**Comment by erlangp** [comment]
i got same error. i just tried restart my apache server. error gone. :)

**Comment by coderzhuang** [comment]
i got this error too.
it set some curl option like  CURLOPT_TIMEOUT_MS and CURLOPT_CONNECTTIMEOUT_MS in my programe.
and my curl version is 7.15.5
when i turn off this options, the error gone.
