### ISSUE TITLE
Cannot get "Location" header from POST response

### ISSUE THREAD

**Issue by hajro92** [guzzle/guzzle#1458]
Hi, first thanks for amazing software.
After I create POST request on my website, it redirect to a new page with GET request using custom ID in query parameter. I read all documentation but cannot get it to work, unable to get "Location" header value as string.

Thanks!

**Comment by jeskew** [comment]
If you set the [`allow_redirects` request option](http://docs.guzzlephp.org/en/latest/request-options.html#allow-redirects) to `false`, then the original (redirecting) response will be returned to you rather than followed. You can then inspect the Location header directly.

**Comment by hajro92** [comment]
In fiddler it returns 302 response code with header "Location", but in guzzle it returns 200 response code without "Location"..

`$client4 = new Client();

try {
$body = 'fb_dtsg='.$dtsg.'&charset_test=%E2%82%AC%2C%C2%B4%2C%E2%82%AC%2C%C2%B4%2C%E6%B0%B4%2C%D0%94%2C%D0%84&r2a=1&xhpc_timeline=1&target='.$page_id.'&c_src=page_self&cwevent=composer_entry&referrer=pages_feed&ctype=inline&cver=amber&rst_icv=&xc_message=&view_photo=Add+Photo';

$response5 = $client4->request('POST', 'https://lm.facebook.com/composer/mbasic/?av='.$page_id.'&refid=17', ['body' => $body, 'allow_redirects' => false, 'cookies' => $jar, 'headers' => ['User-Agent' => $ua, 'Accept' => 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8', 'DNT' => '1',
	'Content-Type' => 'application/x-www-form-urlencoded', 'Origin' => 'https://lm.facebook.com',
	'Upgrade-Insecure-Requests' => '1']]);

echo $response5->getStatusCode();
}`
