### ISSUE TITLE
Guzzle 6: Is it possible to somehow "tag" Requests/Responses?

### ISSUE THREAD

**Issue by inkrement** [guzzle/guzzle#1460]
I have to handle different types (e.g. different URLs) of Request/Responses in an async manner using a Pool. But in the fulfilled-callback I have only access to PSR-7 Response attributes, and I was not able to find a way how I can tag a request with some id or something similar and access it within this callback. 

What would be the convenient way to work with different Request-Response pairs and allow to easily determine the "type"? I would like to provide different response-behaviours depending on the specific request.

**Comment by mtdowling** [comment]
At a really high level, you could associate extra metadata with a response using closures and middleware (e.g., provide a mapping of request to responses as a middleware that you can reference in promises, callbacks, etc).

Alternatively, you could just set arbitrary values on the request or response classes. I think this would work fine as these values should get carried from value object to value object when cloned.

**Comment by inkrement** [comment]
ok nice. So if a add some attribute to a Request, I can access it on a dedicated response object? Would be great if you can add some examples to the documentation.

**Comment by inkrement** [comment]
I tried the middleware approach, without success.

First I pushed the following middleware:
```
function propagate_metadata()
{
    return function (callable $handler) {
        return function (RequestInterface $request, array $options) use ($handler) {
          $promise = $handler($request, $options);

          return $promise->then(function (ResponseInterface $response) use ($request) {
                $response->metadata = $request->metadata;

                return $response;
              }
          );
        };
    };
}
```
and then I added the metadata like this and triggered it. 

```
$request = new Request('GET', 'https://url...', $params);
$request->metadata = [];
$request->metadata['test'] = 'dummy_var';
```

The initial-request contains the metadata field, but the same field is in the middleware's $request variable missing. Do you have any idea, why it is not propagated correctly? I disabled all other middlewares so there are no side effects or different influences, just guzzle.

**Comment by inkrement** [comment]
I was not able to do so, because Guzzle creates a new Request and does not copy custom attributes. So I  used headers to pass the values from the request to the middleware - not the best solution, but it works.
