### ISSUE TITLE
Bug in clients magic __call function

### ISSUE THREAD

**Issue by DaanBiesterbos** [guzzle/guzzle#1463]
The name of the PHP method is used as if it is a HTTP method.   The first argument is the name of the invoked function. The second argument are the actual parameters.  

```
public function __call($method, $args)
    {
        if (count($args) < 1) {
            throw new \InvalidArgumentException('Magic request methods require a URI and optional options array');
        }

        $uri = $args[0];
        $opts = isset($args[1]) ? $args[1] : [];

        return substr($method, -5) === 'Async'
            ? $this->requestAsync(substr($method, 0, -5), $uri, $opts)
            : $this->request($method, $uri, $opts);
    }
```

This is how it should be:
```
$method = $args[0];
$uri = $args[1];
$opts = $args[2];

```

**Comment by jeskew** [comment]
`$method` will be the method called on a client. If, for example, you call `$client->get('/', [])`, then `__call` will be invoked with `get` bound to `$method` and `['/', []]` bound to `$args`. Please see [the PHP manual](http://php.net/manual/en/language.oop5.overloading.php#object.call) for a more in-depth explanation.

**Comment by DaanBiesterbos** [comment]
Yes I know what __call does. But I do now understand what the intented purpose of the __call method is. If you upgrade from 5 to 6 the createRequest method os gone and will invoke the __call method. Perhaps it would be better to thrown an exception if the invoked method is not a http method. :-)
