### ISSUE TITLE
Retry middleware must be at beginning of the HandlerStack

### ISSUE THREAD

**Issue by Tobion** [guzzle/guzzle#1465]
I wrote a middleware that does a request before the actual request (to get some session information). This middleware calls the next handler with a different request. In this case AFAIK it is pretty important that this middleware is added to the beginning of the RequestStack, i.e. `HandlerStack::create()->unshift()`. If you add it to the end all the other default middlewares like http_errors and cookies would get lost on the additional request if I understand that correctly.

The same problem applies to the `retry` middleware. Basically you always want to add it to the beginning. Otherwise the retried requests might be broken. I think it might be helpful to clarify that, at least in the phpdoc of the `Middleware::retry`.

**Comment by sagikazarmark** [comment]
At PHP HTTP we solved this by adding an additional `$first` callable which allows any member of the chain to send a request through the whole chain. It removes the necessity to place Retry middleware on top.
