### ISSUE TITLE
Request body not rewinded for retry?

### ISSUE THREAD

**Issue by Tobion** [guzzle/guzzle#1466]
Normally Guzzle sends the whole body content as request using `(string) $request->getBody()`. But for big request curl uses `CURLOPT_READFUNCTION` in https://github.com/guzzle/guzzle/blob/master/src/Handler/CurlFactory.php#L271 that just calls `read()` on the stream. I didn't find where is rewinds the body in this case. So this seems

1. inconsistent that big payloads are read from the stream position but other payloads have the full stream content
2. if you have a retry middleware active, it would mean the second request would be missing the body as it has already been read and not rewinded? There seems to be some rewind going on in https://github.com/guzzle/guzzle/blob/master/src/Handler/CurlFactory.php#L147 but that would not trigger for other rejections like http_errors from what I can see.

**Comment by mtdowling** [comment]
I think this is a bug. It should try to rewind the body before retrying.

**Comment by kkopachev** [comment]
Related issue: https://github.com/guzzle/guzzle/issues/1335

**Comment by Tobion** [comment]
Seems to be fixed by #1422 since Guzzle 6.2. Thanks
