### ISSUE TITLE
Possible bug with base_uri and requesting URI segments with ports in

### ISSUE THREAD

**Issue by bbashy** [guzzle/guzzle#1472]
When splitting up the base URI and segments, it doesn't work when you have `:9987` or any port.

`vendor/guzzlehttp/psr7/src/Uri.php line 52: Unable to parse URI: /serverstatus/194.97.114.2:9987/`

Tried it with trailing slash in base_uri and I get this;
`vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php line 186: cURL error 6: Could not resolve host: serverstatus (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)`

Doesn't work
```php
require_once('vendor/autoload.php');
$client = new GuzzleHttp\Client([
    'base_uri' => 'https://api.planetteamspeak.com',
]);

$response = $client->request('GET', '/serverstatus/194.97.114.2:9987/');
```

Does work
```php
require_once('vendor/autoload.php');
$client = new GuzzleHttp\Client();

$response = $client->request('GET', 'https://api.planetteamspeak.com/serverstatus/194.97.114.2:9987/');
```

Using Guzzle 6.2 (composer.lock)
```
"name": "guzzlehttp/guzzle",
"version": "6.2.0",
"source": {
    "type": "git",
    "url": "https://github.com/guzzle/guzzle.git",
    "reference": "d094e337976dff9d8e2424e8485872194e768662"
},
```

Full API URL: https://api.planetteamspeak.com/serverstatus/194.97.114.2:9987/

**Comment by mtdowling** [comment]
This seems to be an issue in PHP's parse_url (used by Guzzle):

```
php > var_export(parse_url('/serverstatus/194.97.114.2:9987/'));
false
```

PHP couldn't parse the URL, probably due to the `:` though it is allowed.

```
php > var_export(parse_url('//serverstatus/194.97.114.2:9987/'));
array (
  'host' => 'serverstatus',
  'port' => 9987,
  'path' => '/194.97.114.2:9987/',
)
```

PHP was able to parse this, but only because the leading `//`, which makes `serverstatus` the authority, and `/194.97.114.2:9987/` the path.

Could you open this bug report on https://bugs.php.net/?

**Comment by bbashy** [comment]
Thanks for the reply.

I see, that makes sense. I wasn't sure where to look so thank you for looking into it.
I don't feel comfortable submitting a bug report myself.
