### ISSUE TITLE
Cannot use proxy without username:password

### ISSUE THREAD

**Issue by hajro92** [guzzle/guzzle#1473]
So if proxy have username:password it works (eg.  https://user:pass@IP:PORT), but if proxy is only IP:PORT, it return error 403. I have added my IP to whitelist on proxy provider website.

Using it like: `$response = $client->get(URL, ['proxy' => $this->proxy ,'cookies' => $this->cookie,'debug'=>DEBUG, 'headers' => ['User-Agent' => UA]]);`

**Comment by mtdowling** [comment]
What is the issue here? I'm not sure I understand what's being reported or asked.

**Comment by hajro92** [comment]
Problem is, if I use proxy as "user:pass@IP:PORT" then it works. But if I use proxy like IP:PORT, it returns 403 error, or sometimes it return 500 error (request timeout)

**Comment by mtdowling** [comment]
Is your proxy password protected?

**Comment by hajro92** [comment]
Nvm fixed it, it was problem with proxy provider.
