### ISSUE TITLE
XML Parse Server Issue

### ISSUE THREAD

**Issue by lukepolo** [guzzle/guzzle#1475]
I have two servers both using the guzzle version etc.

When I call to my endpoint one server returns the correct XML. But the other server insists of returning odd numbers right before (and at the end)  of the XML causing errors on parse.

```
00006000
<?xml version="1.0" encoding="UTF-8"?>
    ........ 
</SurveyDefinition>

00000000

```

Any idea?

**Comment by mtdowling** [comment]
Are these numbers/garbage actually coming over the wire? If so, then this would be something you'd need to either fix on the server, or account for when using responses from the server.

**Comment by lukepolo** [comment]
Yah they are, I just dont know where to "fix" them unless i just use PHP to rip them out , doesn't seem like a good idea

**Comment by jeskew** [comment]
This might be related to #1385. Is php-curl installed on the server where you're seeing the odd XML output?

**Comment by lukepolo** [comment]
yup that was it ><
