### ISSUE TITLE
String could not be parsed as XML

### ISSUE THREAD

**Issue by renanterebz** [guzzle/guzzle#1476]
I found a bug, because they are special characters with accent.

![screenshot_1](https://cloud.githubusercontent.com/assets/18082080/15203643/46ac9480-17cb-11e6-8a8c-3e673505cb24.png)

**Comment by mtdowling** [comment]
Guzzle 6 no longer does any XML parsing. When handling this yourself, or using older versions of Guzzle, you'll need to make sure the XML you are trying to parse is valid before attempting to parse it.
