### ISSUE TITLE
Guzzle 3.0 extra path is removed from base_url when using Client and ServiceDescription

### ISSUE THREAD

**Issue by darklow** [guzzle/guzzle#148]
There is no way i can specify extra path in base url when using ServiceDescription
Example:

File CustomClientConfig.php

``` php
<?php return array(
    'operations' => array(
        'test' => array(
            'httpMethod' => 'GET',
            'uri'        => '/test-cmd/{var}',
            'parameters' => array(
                'var' => array('location' => 'uri'),
            )
        )
    )
);
```

Code:

``` php
<?php

$client = Client::factory(array(
    'base_url'  => 'http://api.test.com/some/required/path/'
));

$description = ServiceDescription::factory(__DIR__.'/CustomClientConfig.php');
$client->setDescription($description);

$cmd = $client->getCommand('test', array('var' => 456));
$cmd->prepare();
echo $cmd->getRequest()->getUrl();
```

Output is: `http://api.test.com/test-cmd/456` 
Instead of `http://api.test.com/some/required/path/test-cmd/456`
Why there is required "**/some/required/path/**" missing?

**Comment by mtvbrianking** [comment]
I've been stuck with the same issue. But apparently the documentation (v6) is clean... 

![image](https://user-images.githubusercontent.com/5412360/46159109-2c566380-c288-11e8-8921-dc9a5a208939.png)

**Comment by zardilior** [comment]
How does this apply for https, also you have an https in the first example @mtvbrianking

**Comment by mtvbrianking** [comment]
@zardilior it works inconsiderate of the protocol (**http** || **https**)
