### ISSUE TITLE
Guzzle request got http 500 response code in Lumen 5.2

### ISSUE THREAD

**Issue by nmfzone** [guzzle/guzzle#1483]
I tried to make HTTP POST request through Guzzle, but got HTTP response code **500 Internal Server Error** in PHP and got **500 hphp_invoke** in HHVM.

PHP running on my local machine and HHVM running on my VPS. When using PHP, Lumen says : 

> cURL error 28: Operation timed out after 5000 milliseconds with 0 bytes received (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)

but when using HHVM, i got nothing.

This is an example of my implementation in Lumen 5.2 : 
```
$client = new \GuzzleHttp\Client();
$request = new \GuzzleHttp\Psr7\Request('POST', 'http://hello.api/oauth/access-token', [
      'form_params' => $data
]);
$guzzleResponse = $client->send($request, ['timeout' => 5]);
```

The 500 response code only occurs when using Guzzle, but when i try to access `http://hello.api/oauth/access-token` directly (I mean through Postman), the request success (HTTP Response code 200 OK).

Is there someone who has an idea to solve this?

**Comment by mtdowling** [comment]
It looks like Guzzle is unable to establish a connection to your host. You should try taking out other layers of the problem to isolate the issue (e.g., Guzzle does not return 500 errors, Lumen does). Can you ensure that your VPS can connect to the endpoint? Can you try writing a simple script that does nothing but connect to the endpoint from your VPS?

**Comment by nmfzone** [comment]
Yes my VPS doesn't have any issue i think, I don't know. I've tried it using Lumen 5.1, with the same implementation, and it works as expected. I don't know why, maybe it's Lumen 5.2 issue, or maybe i miss something in my implementation or anything else.

**Comment by mtdowling** [comment]
This seems like an application specific error. You might want to try posting to a Laravel forum or to StackOverflow. Please feel free to open an issue on Guzzle if you've found a reproducible bug.

**Comment by PriyangaRaju** [comment]
Hi even i am so  facing the same issue, i am trying to make http post request but i am getting internal server error 500,  how i can resolve this?. Below is my code
$url = 'https://www.example.com';
    $client = new \GuzzleHttp\Client();
    $post_array = array('Session_Username' =>'abc',
                        'Session_Password' =>'abc',
                        'Session_Remember_Password' => '1');
      $request = $client->request('POST', $lurl,$post_array);
    $response = $request->getBody()->getContents(); 

with the above code I am getting result for other urls  but for a specific url i am getting internal server error. I couldn't able to understand what went wrong.
 Thanks in advance.

**Comment by nmfzone** [comment]
@PriyangaRaju If I'm not mistaken, It's because I'm not enabling CORS.

**Comment by PriyangaRaju** [comment]
Thank you so much i try this.

**Comment by PriyangaRaju** [comment]
Hi, can you please tell me like how to install this cors, i am totally new to this , i searched and understood that cors is used to make request as same domain, but i am confused how to use this. can you please tell me how to use this. Thanks in advance
