### ISSUE TITLE
cURL error 60 with self signed certificate

### ISSUE THREAD

**Issue by julianhaines** [guzzle/guzzle#1490]
Hi,

To start I am not great on Linux and learning, I have just installed ownCloud and its working great but I am getting the GuzzleHttp error: 

GuzzleHttp\Exception\RequestException: cURL error 60: SSL certificate problem: self signed certificate at /var/www/owncloud/3rdparty/guzzlehttp/guzzle/src/Exception/RequestException.php#51 

I have been working on this for a week and still no progress, am not certain if this is a GuzzleHttp error of Curl error or if its the same thing but I am totally stuck.

I have a signed certificate from Comodo and have it working for https and cant see why/where GuzzleHttp or Curl is erroring?

I am running Ubuntu x64 15.\* fully updated clean server apart for ownCloud.

Thanks for any help

Julian

**Comment by ErichHartmann** [comment]
@julianhaines 

Take a look at this...

https://github.com/symfony/symfony-installer/issues/260
https://github.com/symfony/symfony-installer/issues/237

Frankly, downloading a cacert.pem from a non-responsible source is a poor security practice and opens up more holes than the protection afforded TLS. I recommend finding the public certificate(s) from Mozilla directly. Mozilla's reputation is more reliable.

**Comment by sagikazarmark** [comment]
You might want to install the common certificate bundle package:

`$ sudo apt-get install ca-certificates`

Also, alternatively you can turn off TLS verification by setting the `verify` option to `false`. (This is not a safe decision though, but should work for custom, local applications.

I believe it's not a cURL nor a Guzzle issue.

**Comment by tolsoft32** [comment]
as at today on windows 10, when i was trying to install symfony with php command,  i still got the same error, even after trying the method here, pls can you give a clear guide on how to disable  Curl verification

**Comment by torogos** [comment]
@sagikazarmark Where is the option to set the verify to false? I've read this a million times now but no one says in which file or where this must be done.

**Comment by ssanders** [comment]
```php
$guzzle = new GuzzleHttp\Client(array (
    'verify' => false
));
```

**Comment by jupripratama** [comment]
thanks  broo

**Comment by ogidimitrov** [comment]
copy self-signed to `/usr/local/share/ca-certificates/localhost.crt` and `update-ca-certificates`
