### ISSUE TITLE
on_redirect problem

### ISSUE THREAD

**Issue by braankoo** [guzzle/guzzle#1494]
Hi everbody,
im having troubles with on_redirect
I have basic sample here:
`$client = new Client([
                'handler'         => $stack,
                'allow_redirects' => [
                    'on_redirect'     => function () {echo '123';},
                    'track_redirects' => true,
                ],
            ]);`
and its not working.
redirect middleware is included.
Can somebody please explain me what am I doing wrong ?

**Comment by mtdowling** [comment]
If this is a general usage question, please post to stackoverflow. If you can provide more details so this is a bug report, then please update the issue and I'll reopen it.
