### ISSUE TITLE
Get response body when an error occured

### ISSUE THREAD

**Issue by bkielbasa** [guzzle/guzzle#1496]
My case:

When I send post request a server validates my data and returns validation errors with message code 400 and in it's body I get validation info.

The problem:
Because the response is truncated to 120 characters https://github.com/guzzle/guzzle/commit/0a966bbe9ce7382d5ef4adcc2593e53c27a7df93#diff-89fad5801387bb0ac38a7cbfd610f260R128 I am not able to get the JSON date with validations info to parse it.

Possible solution:
Add an option to read ALL the original response in some way.

**Comment by mtdowling** [comment]
Have you tried calling the getResponse() method on a caught exception?

**Comment by bkielbasa** [comment]
no, sorry... You can close the issue

**Comment by mtdowling** [comment]
No problem.
