### ISSUE TITLE
Suggestions for request with dynamic timestamp

### ISSUE THREAD

**Issue by ijerry** [guzzle/guzzle#1497]
I would like a time stamp in my guzzle request ?
In particular, I want the log output (behat) to show the updated data, and not a placeholder eg "time_stamp" ?

What are my options ?

Thanks for any help in advance ?

**Comment by mtdowling** [comment]
Do you actually want to send the time stamp (in a header for example), or just log it?

**Comment by ijerry** [comment]
Ideally,  I would like a "time_stamp" string in the feature file scenario outline. 
Then just before request is sent to generate the actual stamp. (Note i can do this with a transformation)
The behat log to reflect what is actually sent. (not the "time_stamp" string)
or something close to this.

**Comment by mtdowling** [comment]
You'd need to create Guzzle middleware to add the timestamp to a header before sending. You'd then need to update the log middleware to log that specific header.

http://docs.guzzlephp.org/en/latest/handlers-and-middleware.html
https://github.com/guzzle/guzzle/blob/master/src/MessageFormatter.php#L29
