### ISSUE TITLE
form_params not send when using custom http method.

### ISSUE THREAD

**Issue by IceReaper** [guzzle/guzzle#1498]
Example:
````php
$response = $client->request('CREATE', 'http://127.0.0.1/Gateway', ['form_params' => [
    'mac' => 'aa:bb:cc:dd:ee:ff'
], 'debug' => true]);
````

Request is made but $_POST and $_GET are empty. debug mode output:

````
*   Trying 127.0.0.1...
* Connected to 127.0.0.1 (127.0.0.1) port 80 (#0)
> CREATE /Gateway HTTP/1.1
Host: 127.0.0.1
User-Agent: GuzzleHttp/6.2.0 curl/7.47.1 PHP/7.0.6
Content-Type: application/x-www-form-urlencoded
Content-Length: 31

* upload completely sent off: 31 out of 31 bytes
````

EDIT: $_SERVER['HTTP_METHOD'] is correctly set, so the method itself is not the problem.
Also sending the same request with phpstorm RESTful client, the request is made including post values - so its not the server truncating them. They are simply not send correctly. The same problem occurs with PUT.

**Comment by kkopachev** [comment]
> * upload completely sent off: 31 out of 31 bytes

this is saying that 31 bytes were in the body, but not showing bytes itself.

```
echo strlen(http_build_query(['mac'=>'aa:bb:cc:dd:ee:ff']));
31
```
seems to be correct

**Comment by IceReaper** [comment]
Yeah, thats right. will investigate further if something goes wrong with the curl request or on the apache-side and either update this issue with more information or close it if it was another problem.

**Comment by IceReaper** [comment]
Okay, found the problem: PHP only fills $_POST for POST requests. However it is possible to submit post-data with every request. The trick is to manually fill the $_POST array with the postdata.
````
if (empty($_POST)) {
    parse_str(file_get_contents('php://input'), $_POST);
}
````
Might be usefull to know when working with custom http methods - wiki?
