### ISSUE TITLE
How use a template URL in request

### ISSUE THREAD

**Issue by Ducatel** [guzzle/guzzle#1500]
Hi all,

I'm trying to use a template URL in request like

```php
$req = new \GuzzleHttp\Psr7\Request('GET', '/{email}');
```

The only solution have found is not very beautiful .... 

```php
// $request == \GuzzleHttp\Psr7\Request
$request = $this->getRequest(self::GET_USER_BY_EMAIL);
$url = \GuzzleHttp\uri_template(urldecode($request->getUri()), ['email' => $email]);
$response = $this->clientAPI->send($request->withUri(new \GuzzleHttp\Psr7\Uri($url)));
```

Is it possible to do the same things but more easier ?
Thanks in advance for your help ;)

**Comment by mtdowling** [comment]
No, Guzzle does not provide any mechanism for doing this magically. What you've done is the correct way to handle this if you want to use a URI template.

**Comment by Ducatel** [comment]
arf, no plan to add this feature later ?
This should by great for calling REST API.
