### ISSUE TITLE
Any clean working examples of using logging monolog with guzzle6 ?

### ISSUE THREAD

**Issue by ijerry** [guzzle/guzzle#1501]
Any clean working examples of using logging monolog with guzzle6 ?

**Comment by Ducatel** [comment]
Hello,
you should check [this middleware](https://github.com/rtheunissen/guzzle-log-middleware) or this [thread in stackoverflow](https://stackoverflow.com/questions/32681165/how-do-you-log-all-api-calls-using-guzzle-6)

**Comment by ijerry** [comment]
Thanks that's after helping
