### ISSUE TITLE
using sink with a full file path don't fclose() resource

### ISSUE THREAD

**Issue by FredoVelcro** [guzzle/guzzle#1502]
When using sink option with a file path(instead of resource), it seems that the resource is not closed after request.
In this example (on Windows) i can't unlink the link if it fails : 

```php
$response = $httpClient->get($path, array(
    'sink' => $destFile,
    'http_errors' => false
));
                
if ($response->getStatusCode() == 404) {
    unlink($destFile); // ERROR "permission denied"
    echo '<error>' . $path . ' not found</error>';
}
```

this works : 

```php
$resource = fopen($destFile, 'w');
$response = $httpClient->get($path, array(
    'sink' => $resource,
    'http_errors' => false
));
fclose($resource);

if ($response->getStatusCode() == 404) {
    unlink($destFile);
    echo '<error>' . $path . ' not found</error>';
}
```

It seems like fclose() not called on the sink resource or something like that...

**Comment by mtdowling** [comment]
The response body in your example is still open because the response still has a reference to it, which means the response body has a reference, which means the underlying PHP stream is still open. As soon as the response body is garbage collected, the stream is closed and you can unlink it. Otherwise, you'll need to explicitly detach the stream from the response body and fclose it manually.

**Comment by FredoVelcro** [comment]
In Guzzle Client code (or else) there isn't any "fclose" call so it might be a problem..
If you open a stream, you should properly close it at the end, it lacks.

> Otherwise, you'll need to explicitly detach the stream from the response body and fclose it manually.

How do you do that ?

**Comment by conradfr** [comment]
Did you ever find out ?

**Comment by comanche** [comment]
This worked form me:

```php
try {
    $response = $httpClient->get($path, array(
        'sink' => $destFile,
        'http_errors' => false
    ));
} catch (GuzzleException $e) {
    if ($e->hasResponse()) {
        /** @var \GuzzleHttp\Psr7\Response $res */
        $response = $e->getResponse();

        /** @var \GuzzleHttp\Psr7\LazyOpenStream $body */
        $body = $res->getBody();

        if (property_exists($body, 'stream')) {
            /** @var \GuzzleHttp\Psr7\Stream $stream */
            $stream = $body->stream;
            $stream->close();
         }
    }
}

if ($response->getStatusCode() == 404) {
    unlink($destFile); // ERROR "permission denied"
    echo '<error>' . $path . ' not found</error>';
}
```
