### ISSUE TITLE
How to strip new lines from request message on send?

### ISSUE THREAD

**Issue by k0pernikus** [guzzle/guzzle#1507]
I am using guzzle 6.0 and I have a SOAP endpoint, that does not like new lines in the data message.

When I dump the guzzle request via cuzzle, I get a curl request with new lines that won't work:

```
curl 'http://the-soap-server' -H 'Content-Type: text/xml; charset=utf-8' \
-H 'SOAPAction: http://tempuri.org/Action' -X POST \
--data '<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:tem="http://tempuri.org/">
<soapenv:Header/>
<soapenv:Body>
    <tem:Booking>
    ...
    </soapenv:Body>
</soapenv:Envelope>'
```

If the request would behave like this curl request:

```
curl 'http://the-soap-server' -H 'Content-Type: text/xml; charset=utf-8' \
-H 'SOAPAction: http://tempuri.org/Action' -X POST \
--data '<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:tem="http://tempuri.org/"><soapenv:Header/><soapenv:Body><tem:Booking>.../soapenv:Body></soapenv:Envelope>'
```

it would work.

Is there a way to tell guzzle to strip new lines on send, independent on how the request body is set?

(I know I can strip the newlines manually while building the message, yet it would ease setting up the maintainable functional test if this could be handled on the guzzle layer.)

**Comment by mtdowling** [comment]
This is not something that Guzzle does for you. You will need to implement a middleware that trims the newlines or a stream decorator that trims newlines from a stream as it seems them.

http://docs.guzzlephp.org/en/latest/handlers-and-middleware.html
https://github.com/guzzle/psr7/blob/master/src/StreamDecoratorTrait.php

**Comment by k0pernikus** [comment]
I solved it via adding a `mapRequest` handler and by making it configurable via environment setting. ```
private function createGuzzleConfig() {
        $guzzleConfig = $this->baseGuzzleConfig();
        $handlerStack = HandlerStack::create(new CurlHandler());

        if ($this->isStrippingNewLines) {
            $handlerStack->push(Middleware::mapRequest($this->stripNewlines()));
        }

        if ($this->isStrippingNewLines) {
            $handlerStack->push(Middleware::mapRequest($this->stripNewlines()));
        }

        return array_merge($guzzleConfig, ['handler' => $handlerStack,]);
}

/**
 * @return \Closure|callable
 */
private function stripNewlines()
{
    return function (RequestInterface $request) {
	return new Request(
	    $request->getMethod(),
	    $request->getUri(),
	    $request->getHeaders(),
	    trim(str_replace(PHP_EOL, '', $request->getBody()))
	);
    };
}
```
 and instantiated the client via `new Client($guzzleConfig);`.
