### ISSUE TITLE
Curl_Multi_Exec is taking too much time

### ISSUE THREAD

**Issue by arpitx165** [guzzle/guzzle#1508]
I have tried too post data using curl_multi_exec but still i am unable to understand why its using loop while executing.

When i remove this loop then its unable too post the data even on single url  so why this loop runs so many times  ? 

I am talking about this loop. 
$running = null;
  do {
   curl_multi_exec($mh, $running); 
  } while($running > 0);

**Comment by mtdowling** [comment]
curl_multi_exec is a non-blocking call that continuously loops until all of the data is sent. You have to loop in order to execute the entire request.

**Comment by arpitx165** [comment]
okay but i am trying to post data asynchronously using curl_multi_exec .in this i am facing problem in loop because when i post data then on other end its waiting for response so i don't want that  Can you tell me any solution for that ?
