### ISSUE TITLE
curl error 52 with consecutive requests on PHP 5.4 (guzzle 5.3)

### ISSUE THREAD

**Issue by ppaulis** [guzzle/guzzle#1515]
Hello!

I have a strange problem with Guzzle 5.3 on PHP 5.4:
When doing a second GET request, I get a curl error 52 ("Got nothing"). The problem doesn't appear on PHP 5.5, 5.6 or 7.0. What I tried so far:
* Replacing the Guzzle client object
* Sending a "Connection: close" header
* Sending the curl fresh connect header:
```
$client->get(
            $url,
            [
                'headers'      => $headers,
                'verify'          => false,
                'exceptions'  => false,
                'query'           => $this->getQueryString(),
                'config' => [
                    'curl' => [
                        CURLOPT_FRESH_CONNECT => 1
                    ]
                ]
            ]
        );
```

Is there perhaps a known issue with PHP 5.4, that I missed?

Any help is appreciated!
Thanks!
Pascal

**Comment by GrahamCampbell** [comment]
Guzzle requires PHP 5.5. You cannot run it on PHP 5.4.

**Comment by GrahamCampbell** [comment]
Ah, right, I see. Guzzle 5. I'm not sure what the maintenance policy on that is @mtdowling?

**Comment by mtdowling** [comment]
Seems like a PHP specific issue. I'm not aware of anything related to this.
