### ISSUE TITLE
Reading on streamed body doesn't have a timeout

### ISSUE THREAD

**Issue by arnaud-lb** [guzzle/guzzle#1516]
When reading from a streamed body, it is not possible to timeout. As a result, the client can get stuck trying to read the body. It can happen in many occasions, for instance if the remote end crashes or just forgets about you, the client will try to read from the socket forever (c.f. half-open tcp).

Example:

```
$client = new Client([
    'timeout' => 300,
    'stream' => true,
]);

$response = $client->get('http://example.com/');

$body = $response->getBody()->detach();

while (!feof($body)) {
    // this can hang forever
    $line = fgets($body);
}
```

I would be great if Guzzle allowed to specify a read timeout. I didn't find a way to apply a timeout myself.

**Comment by mtdowling** [comment]
I think you need to check if fgets returns false to see if the read failed. See: http://php.net/manual/en/function.fgets.php

**Comment by arnaud-lb** [comment]
Hi @mtdowling,

The problem is that it happens that fgets never returns :) For instance, when you encounter a [TCP half-open](https://en.wikipedia.org/wiki/TCP_half-open) case. When this happens, a fgets() on a Guzzle's body stream never returns.

**Comment by arnaud-lb** [comment]
Up :)

It seems to be impossible to tell to Guzzle that a read on the body **should** timeout after some time.

As a result, it possible to get stuck on **fgets()** and related functions in case something goes wrong:

 - TCP half-open, causing the local host to never notice that the connection is closed
 - Malicious server
 - Mis-behaving server

Is it planned to implement reading timeout ? If not, any objection if I try to implement this ?
