### ISSUE TITLE
cURL error when sending request through Plurk API

### ISSUE THREAD

**Issue by peter279k** [guzzle/guzzle#1517]
Hi, can anyone use Plurk API ? I have some problems about this API.
I tried to use Plurk API to upload picture via Guzzle 5, but I always got 400 Bad Request.
I also got the message : 'error_text' => string '40104:incorrect signature'.
Can anyone know this problem ? Thanks.
Here is my sample code:
https://gist.github.com/peter279k/4bad7cb1a5457a1dd27f57a658956434

Plurk API reference:
https://www.plurk.com/API#/APP/Timeline/uploadPicture

**Comment by mtdowling** [comment]
Please feel free to open an issue on Guzzle if you are reporting a reproducible bug. For general usage questions and integration, I suggest posting to StackOverflow.
