### ISSUE TITLE
Several values for one parameters in Guzzle 6

### ISSUE THREAD

**Issue by savenko** [guzzle/guzzle#1520]
Hello!
I can not send several values for one parameters in Guzzle 6
For example i have parameter with name "param" and values for him "1,2". In post headers i need get:

```
param:1
param:2
```
I tryed:

```
$response = $client->post('http://test.com', [
                'form_params' => $dataPost
]);
```
Where $dataPost is was:

```
$dataPost=[
'param'=>[1,2]
]
```
or

```
$dataPost=[
0=>['param'=>1],
1=>['param'=>2]
]
```
It does not work

**Comment by mtdowling** [comment]
Are you looking to add headers or POST fields? It's not clear from your question.

**Comment by savenko** [comment]
add POST fields

**Comment by Tobion** [comment]
`form_params` uses http://php.net/manual/en/function.http-build-query.php
which will serialize array values as

```
param[]:1
param[]:2
```

and not

```
param:1
param:2
```

You can use `build_query` of https://github.com/guzzle/psr7/blob/master/src/functions.php#L571
to get the different behavior and then set the body manually of the request manually.

**Comment by mtdowling** [comment]
Thanks @Tobion!
