### ISSUE TITLE
how to use React HTTP handler(or other handler that use libevent)?

### ISSUE THREAD

**Issue by gouchaoer** [guzzle/guzzle#1521]
>Does Guzzle require cURL?
No. Guzzle can use any HTTP handler to send requests. This means that Guzzle can be used with cURL, PHP's stream wrapper, sockets, and non-blocking libraries like React. You just need to configure an HTTP handler to use a different method of sending requests.

But I search around the internet and find nothing about how to do that.
could you please offer a example?

**Comment by mtdowling** [comment]
This library is exactly what you need: https://github.com/WyriHaximus/react-guzzle-psr7
