### ISSUE TITLE
Pound/Hash not being encoded

### ISSUE THREAD

**Issue by sloan58** [guzzle/guzzle#1522]
I have a pound/hash symbol in a query string and while sending the get request with PHP Guzzle 6.2.0 it is not being encoded properly. A sample request:

https://10.1.10.1/vmrest/users?query=(alias%20is%20UserWithAPoundSign%2318)

is sent as:

https://10.1.10.1/vmrest/users?query=(alias%20is%20UserWithAPoundSign#18)

**Comment by sloan58** [comment]
I'm using rawurlencode() on the string prior to sending the request and it's working but it would be nice to have it encoded by Guzzle.

**Comment by mtdowling** [comment]
How would Guzzle know if you meant for the `#` to be the start of a URI fragment or part of the query string?

**Comment by sloan58** [comment]
That is a good point which I honestly didn't consider.  A slight case of tunnel vision....  I suppose you could have an option for the client like 'uri_contains_fragment'?

**Comment by mtdowling** [comment]
I feel like that would add confusion and bloat the docs for a seldom used feature. Closing as I don't want Guzzle to have to try to parse and infer things at this level.
