### ISSUE TITLE
Unable to compose a parameter array that an API requires

### ISSUE THREAD

**Issue by sterichards** [guzzle/guzzle#1523]
Using an online CuRL request maker, I can send the following request and an API accepts that fine.

![image](https://cloud.githubusercontent.com/assets/2899828/16795021/fe16e4da-48d2-11e6-831f-b4133ee914fc.png)

But trying to replicate that request within Guzzle is giving me problems:

`$formData = json_encode([
    'form_params' => [
        'data' => [
            'name' => 'test',
            'organisation_id' => 'abc123',
            'url' => 'http://sample-videos.com/video/mp4/720/big_buck_bunny_720p_1mb.mp4'
        ]
    ]
]);

$request = $this->buto->post('/v2/video/upload', $formData);

$response = $request->send();`

I assume my array structure, within Guzzle, is incorrect but I don't see how

**Comment by mtdowling** [comment]
What is the problem you're seeing?

**Comment by sterichards** [comment]
` [Symfony\Component\Debug\Exception\ContextErrorException]
  Warning: Invalid argument supplied for foreach()



Exception trace:
 () at /vagrant/vendor/guzzle/guzzle/src/Guzzle/Http/Message/Request.php:95
 Symfony\Component\Debug\ErrorHandler->handleError() at /vagrant/vendor/guzzle/guzzle/src/Guzzle/Http/Message/Request.php:95
 Guzzle\Http\Message\Request->__construct() at /vagrant/vendor/guzzle/guzzle/src/Guzzle/Http/Message/EntityEnclosingRequest.php:31
 Guzzle\Http\Message\EntityEnclosingRequest->__construct() at /vagrant/vendor/guzzle/guzzle/src/Guzzle/Http/Message/RequestFactory.php:99
 Guzzle\Http\Message\RequestFactory->create() at /vagrant/vendor/guzzle/guzzle/src/Guzzle/Http/Client.php:201
 Guzzle\Http\Client->createRequest() at /vagrant/vendor/guzzle/guzzle/src/Guzzle/Http/Client.php:268
 Guzzle\Http\Client->post() at /vagrant/src/IntegritBundle/Command/UploadEventVideosToButoCommand.php:59
 IntegritBundle\Command\UploadEventVideosToButoCommand->uploadVideoToButo() at /vagrant/src/IntegritBundle/Command/UploadEventVideosToButoCommand.php:41
 IntegritBundle\Command\UploadEventVideosToButoCommand->execute() at /vagrant/vendor/symfony/symfony/src/Symfony/Component/Console/Command/Command.php:259
 Symfony\Component\Console\Command\Command->run() at /vagrant/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:886
 Symfony\Component\Console\Application->doRunCommand() at /vagrant/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:195
 Symfony\Component\Console\Application->doRun() at /vagrant/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php:96
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at /vagrant/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:126
 Symfony\Component\Console\Application->run() at /vagrant/app/console:27`

**Comment by sterichards** [comment]
I can also send a successful CuRL request using:

curl -u {$this->butoAPIKey}:x --include --request POST --data-binary '{"name":"{$this->butoAPIParams['name']}","description":"{$this->butoAPIParams['Description']}","url":"{$videoURL}","organisation_id":"{$this->butoAPIParams['organisation_id']}","tags":[{$tags}]}' {$this->butoUploadAPIUrl}

**Comment by sagikazarmark** [comment]
Based on your vendor directory (`/vagrant/vendor/guzzle/guzzle/src/Guzzle/Http`) you use Guzzle 3 which is not maintained anymore.

Assuming `$this->buto` is a Guzzle client instance the passed parameters are wrong:


https://github.com/guzzle/guzzle3/blob/master/src/Guzzle/Http/Client.php#L266
