### ISSUE TITLE
Failed opening required 'vendor/autoload.php'

### ISSUE THREAD

**Issue by marianpavel** [guzzle/guzzle#1525]
Hi,
I have installed the library using composer

php composer.phar require guzzlehttp/guzzle

But when I try to use autoload ( require 'vendor/autoload.php'; ) I get this:

Warning: require(vendor/autoload.php): failed to open stream: No such file or directory in /var/www/.... on line 8

Fatal error: require(): Failed opening required 'vendor/autoload.php'

Any ideea how I can fix this ?

Thank you

**Comment by GrahamCampbell** [comment]
You probably ran the script from the wrong directory. Make sure you use the actual path to the vendor folder. You may want to use the `__DIR__` constant.

**Comment by marianpavel** [comment]
Can be closed, I managed to solve the problem.
