### ISSUE TITLE
NO_PROXY environment variable is ignored.

### ISSUE THREAD

**Issue by marxjohnson** [guzzle/guzzle#1537]
Currently, Guzzle uses the HTTP_PROXY and HTTPS_PROXY environment variables as the default values for $config['proxy']['http'] and $config['proxy']['https'], which are used to set the corresponding cURL options.

However, it does not use the NO_PROXY environment variable to set CURLOPT_NOPROXY, which causes a problem if, for example, you're behind a proxy and trying to request a local page.
It would be great if using NO_PROXY could be implemented.

**Comment by sagikazarmark** [comment]
As a temporary workaround, you can pass it as a [curl option](http://docs.guzzlephp.org/en/latest/faq.html?highlight=curl#how-can-i-add-custom-curl-options).

**Comment by sagikazarmark** [comment]
Looks like there is actually support for this, but not in the form of CURLOPT_NOPROXY.

**Comment by RopoMen** [comment]
If you set 
```php
putenv('no_proxy', '*');
```
https://github.com/curl/curl/blob/7408570bf04555b9e56ed1cb9ffba5621411b145/docs/libcurl/libcurl-tutorial.3#L844

and

https://github.com/curl/curl/blob/7f2a1df6f5fc598750b2c6f34465c8d924db28cc/lib/url.c#L2652

curl should detect 'no_proxy' option automatically.
