### ISSUE TITLE
Multiple redirects issue

### ISSUE THREAD

**Issue by PetarDambovaliev** [guzzle/guzzle#1540]
I need to download a pdf file  with guzzle.
There are 3 redirects on the way to the file url.
The last redirect is done after the url is generated via javascript.

The problem is, the guzzle request assumes html as the response and doesn't wait for the last redirect.

**Comment by mtdowling** [comment]
Guzzle is not a web browser. It doesn't parse HTML or embed a JavaScript interpreter, so it wont follow these types of redirects.
