### ISSUE TITLE
`x-encoded-content-encoding` and `x-encoded-content-length` showing wrong value

### ISSUE THREAD

**Issue by realityking** [guzzle/guzzle#1541]
I just had a use case to access `x-encoded-content-encoding` and discovered the following when `var_dump()`ing a response:

```
'x-encoded-content-encoding' => string(26) "x-encoded-content-encoding"
'x-encoded-content-length' => string(24) "x-encoded-content-length"
```

Using Guzzle 6.2.1, Guzzle PSR7 1.3.1 and psr/http-messages 1.0.

**Comment by jeskew** [comment]
I believe you're seeing an entry in the response's $normalized_headers
array, which maps strtolower'd header names to the header names provided by
the HTTP handler. (This is done to allow the getHeader and getHeaderLine
methods to provide case-insensitive access to headers.)

Do you see the correct value when using the getHeader or getHeaderLine
methods?

**Comment by realityking** [comment]
My bad. I have no idea how I missed that 😯 Thanks for helping me out 👍
