### ISSUE TITLE
GuzzleHttp how to add header?

### ISSUE THREAD

**Issue by shubaivan** [guzzle/guzzle#1548]
In Guzzle I use addHeader and all fine, hot to add header in http guzzle ? 

        $headers = [
            'Authorization' => 'Bearer ' . $arrayAccessTokenClient,
            'Content-type' => 'application/json'
        ];
        $guzzle = new \GuzzleHttp\Client();

        $request = $guzzle
            ->post('https://sheets.googleapis.com/v4/spreadsheets/' . $spreadsheetId . ':batchUpdate',
                $addProtectedRange
            )
            ->withAddedHeader('Authorization', 'Bearer ' . $arrayAccessTokenClient)
            ->withAddedHeader('Content-type', 'application/json')
        ;
        $response = $request->getBody()->getContents();

        return $response;

now I have 401, header dontw work or dont add I dont know how to correctly add header to my post request

**Comment by GrahamCampbell** [comment]
Calling post already sends the request. Pass a 2nd param which is an array when you call post.

```php
$response = $guzzle->post('foo', ['headers' => $headers]);
```

**Comment by shubaivan** [comment]
where is the body request ?

**Comment by GrahamCampbell** [comment]
All the docs are here: http://docs.guzzlephp.org/en/latest/quickstart.html.

**Comment by shubaivan** [comment]
I read and have question hot to interpretate my request body in json, because sen get two parameters \GuzzleHttp\Psr7\Request and array but I need json in request, not array and have error from resuorse 400 bad request because resourse need json bode

`        $headers = [
            'Authorization' => 'Bearer ' . $arrayAccessTokenClient,
            'Content-type' => 'application/json'
        ];
        $guzzle = new \GuzzleHttp\Client();
        $request = new \GuzzleHttp\Psr7\Request('POST', 'https://sheets.googleapis.com/v4/spreadsheets/' . $spreadsheetId . ':batchUpdate', $headers);
        $response = $guzzle
            ->send($request, $addProtectedRange);

        $answer = $response->getBody()->getContents();

        return $answer;`

**Comment by shubaivan** [comment]
I find solution

            $headers = [
            'Authorization' => 'Bearer ' . $arrayAccessTokenClient,
            'Content-type' => 'application/json'
        ];
        $guzzle = new \GuzzleHttp\Client();
        $request = new \GuzzleHttp\Psr7\Request('POST', 'https://sheets.googleapis.com/v4/spreadsheets/' . $spreadsheetId . ':batchUpdate', $headers);
        $response = $guzzle
            ->send($request, ['body' => $addProtectedRangeJson]);

        $answer = $response->getBody()->getContents();

        return $answer;
