### ISSUE TITLE
Equivalent to CURL_IPRESOLVE_V4 in Guzzle ?

### ISSUE THREAD

**Issue by udf2457** [guzzle/guzzle#1551]
Hi,

I've had a quick look through the docs and can't see anything there.

Is there an equivalent to curl's CURL_IPRESOLVE_V4 for Guzzle to force it straight to IPv4 for DNS resolution and server communication ?

**Comment by azusa0127** [comment]
I guess you may just need to add it as the custom curl option.
[](http://docs.guzzlephp.org/en/latest/faq.html?highlight=curl#how-can-i-add-custom-curl-options)

**Comment by mtdowling** [comment]
Yep, you'd need to use custom cURL options for something this cURL specific.
