### ISSUE TITLE
Unable to find the socket transport http

### ISSUE THREAD

**Issue by drtzack** [guzzle/guzzle#1555]
~~~
$api = new Client([
    'proxy' => 'http://my-proxy-server:8888',
]);

$stream = $api->get('http://guzzlephp.org', array('stream' => true));
while (!$stream->feof()) {
    echo $stream->readLine();
}
~~~

It gives error only if I use proxy option. If I remove stream option or proxy option works correct but I need it.

I installed php with brew to El Capitan.

Error creating resource: [message] fopen(http://guzzlephp.org): failed to open stream: Unable to find the socket transport &quot;http&quot; - did you forget to enable it when you configured PHP?

**Comment by alexeyshockov** [comment]
Replace `http://my-proxy-server:8888` with `tcp://my-proxy-server:8888`.

BTW, you can use [`sink`](http://docs.guzzlephp.org/en/latest/request-options.html#sink) option to proxy the body to another stream (`php://stdout` in your case).

**Comment by mtdowling** [comment]
Thanks, @alekseykuleshov!

**Comment by Stalinko** [comment]
Faced the same issue.
However in the docs (http://docs.guzzlephp.org/en/stable/request-options.html#proxy) it is noted:

> You can provide proxy URLs that contain a scheme, username, and password. For example, "http://username:password@192.168.16.1:10".

Looks like the docs don't match the reality?

**Comment by trbsi** [comment]
For anyone who comes here. I had to install curl for PHP `sudo apt-get install php-curl`

**Comment by caleblent** [comment]
For anyone who may come across this in the future, I have a CodeIgniter project on a live Apache web server. The following settings in my `.env` file finally got my email sending function to work:

```
email.SMTPHost = tcp://domain.com
email.SMTPUser = noreply@domain.com
email.SMTPPass = password123
email.SMTPPort = 587
```
