### ISSUE TITLE
Add the ability to forward headers

### ISSUE THREAD

**Issue by kamranahmedse** [guzzle/guzzle#1556]
I have been working in a service oriented architecture where there are many small APIs involved. And each of the API uses Guzzle to make requests to the external APIs. Here is how it looks like

```
---------,        ,-----------,        ,---------,
Client    | ----> | API - 1   | -----> | API - 2 |
---------'        '-----------'        '---------'
```

Now, as you can see the `API-1` is requesting the `API-2` on behalf of the client so for `API-2` to consider the actual client as the client instead of `API-1` as the client, what I want is to forward the client's headers on the request instead of the server's.

What I am doing right now is manually setting the required headers. However it would be beneficial to have some option e.g. `forward_headers` that would automatically forward the actual headers alongside the request.

**Comment by irfan-blackhawk** [comment]
+1

**Comment by Tobion** [comment]
So you mean to forward headers of an incoming PSR-7 `RequestInterface` to a Guzzle request that is sent to your `API -1/2`? That sounds like 5 lines of code.

Can you give a concrete usage example as I don't how you imagine this to work.

**Comment by kamranahmedse** [comment]
It may be *5 lines of code* but why not standardize it with a *one line of code* in Guzzle itself :-)

Here is what I mean:
For example the client requests `API-1` and sends the following:

```
[
    'x-host-ip' => 184.232.22.2,
    'x-forwarded-for' => 196.12.33.3,
    'x-some-custom-header' => 'some-value',
    'User-Agent' => '...',
    ....
]
```
Now `API-1` uses Guzzle to request `API-2`; by default, nothing out of these headers will be forwarded to `API-2`. Now while initializing the guzzle, if I add the option 
```
...
forward_headers => true
...
```
It would forward the same headers, given above, that the client sent; towards the `API-2` without writing any custom code.

**Comment by mtdowling** [comment]
I'm not sure that I like this proposal because it moves Guzzle more into the application/server space than I'd like. Guzzle shouldn't have to know anything about the headers sent from another client to a server in order to send a request.

In my opinion, this would be best left to third-party middleware libraries instead of in Guzzle core.

**Comment by Tobion** [comment]
> `forward_headers => true`

I don't see how this should work. Guzzle client in API-1 does not know the incoming headers. It would need to access the `RequestInterface` instance of the incoming request.

Isn't all you want `$newRequest = $newRequest->withHeaders($incomingRequest->getHeaders()); $guzzle->send($newRequest);`? That's only one line as well.

**Comment by kamranahmedse** [comment]
@Tobion this is exactly how, I am handling it now.

@mtdowling it really won't move it more into the app/server space than it already is. I mean, guzzle is already on the server side, where client has to send requests and it won't be rare that the client may send certain headers along the request regarding their application logic for certain stuff. I just mean to optionally include the headers, if it is required.

But anyways, I can understand if you disagree.
