### ISSUE TITLE
Tests Directory Empty?

### ISSUE THREAD

**Issue by aejnsn** [guzzle/guzzle#1558]
I am trying to test an API client I've written using Guzzle using the three methods documented here: http://docs.guzzlephp.org/en/latest/testing.html.

I am unable to use the testing web server (Server class), because my entire tests directory is empty. I've checked into previous releases of Guzzle 4 and 5 to see that the tests directory is not empty on those releases. However, Guzzle 6's tests directory is empty on all releases and thus when I install via Composer.

What am I missing?

**Comment by jeskew** [comment]
The tests, docs, and build directories are not included in the standard composer distribution. (This is done via `export-ignore` directives in the [.gitattributes file](https://github.com/guzzle/guzzle/blob/master/.gitattributes), which both Composer and GitHub use to determine what files and directories should be excluded from a release.)

You can direct composer to fetch the repository via `git pull` with the `--prefer-source` flag if you would prefer to install the entire repository.
