### ISSUE TITLE
Howto prevent composer autoloader to load => "vendor/guzzlehttp/.../src/functions[_include].php" without using (create instance of) guzzlehttp?

### ISSUE THREAD

**Issue by C0DE8** [guzzle/guzzle#1561]
How to prevent composer autoloader  to load the following files (just functions) without using (
create class instance of) guzzlehttp class:

```
vendor/guzzlehttp/promises/src/functions_include.php
vendor/guzzlehttp/promises/src/functions.php
vendor/guzzlehttp/psr7/src/functions_include.php
vendor/guzzlehttp/psr7/src/functions.php
vendor/guzzlehttp/guzzle/src/functions_include.php
vendor/guzzlehttp/guzzle/src/functions.php
```

These files use about 40kb Mem? (not very much, but if it can be avoided...)

I want to use guzzlehttp, but not in every request.

Is there any way to prevent autoloader or another way not to load files without creating an instance of guzzlehttp? (composer installation is required)

**Comment by GrahamCampbell** [comment]
Would have been better to make these static functions on a class tbh.

**Comment by GrahamCampbell** [comment]
Would have avoided needing to load them early.

**Comment by jeskew** [comment]
Composer will load those files whenever `composer/autoload.php` is required for the first time in any request. I do not believe there is any way to change this behavior short of writing a custom autoloader.

**Comment by C0DE8** [comment]
@jeskew : may it be possible to implement an manual loading of this 6 files (fabove), so that   guzzlehttp can be installed via composer, but no files will be loaded until:
1. functions are required
or
2. guzzlehttp class is created

**Comment by jeskew** [comment]
@C0DE8 You could make a custom autoloader that does that, though I wouldn't recommend doing so. It would need to be handled in your application, however, as composer packages can't modify composer's generated autoloader in the way you're describing.

**Comment by GrahamCampbell** [comment]
There's no way to autoload function as they're required. The only way to do that would be to define dummy functions, which kinda defeats the object somewhat.

**Comment by jeskew** [comment]
You could have an autoloader that uses composer's class map and requires
Guzzle's functions the first time a class in the GuzzleHttp namespace is
loaded. Definitely not something I'd recommend, but not impossible.

**Comment by mtdowling** [comment]
Closing as this isn't something that can be changed in Guzzle without a BC.

**Comment by vincent-guesnard** [comment]
What did you call a BC please ? (I'm french BC Business Continuity ? ^^)

This file is quite annoying for full PSR-4 compliant autoloader. I guess there is no plan to remove it.

**Comment by sagikazarmark** [comment]
Backwards Compatibility.

> I guess there is no plan to remove it

No

**Comment by ericnorris** [comment]
@mtdowling is this something that could be considered for the next major release then? Autoloading unused files on every request is not ideal when you are serving on the order of thousands of requests per second.

**Comment by sagikazarmark** [comment]
@mtdowling What if we move those functions to static classes and just use them in those functions? I think the memory footprint would be somewhat lower. Not sure if it worth the effort though.
