### ISSUE TITLE
InvalidArgumentException in Client.php line 402:

### ISSUE THREAD

**Issue by Raghava525** [guzzle/guzzle#1563]
Hi,
Am using laravel 5. The composer values are

"laravel/framework": "5.0.*",
"guzzlehttp/guzzle": "^6.2",

When I am trying to send the mail using swift mailer :
My code is:

$em_arr = Array();
$em_arr['to'] = $email;
$em_arr['name'] = $name;
$em_arr['subject'] = 'Forgot password';
$emailcontent = array('html'=> '');

$merg_vars = array();
$merg_vars['get_loan_offer'] = $get_loan_offer;
$merg_vars['reset_password_link'] = $reset_password_link;
$template_name = 'reset_password';

Mail::send('emails.emailsent', [], function($message) use ($em_arr, $merg_vars, $template_name)
{
$headers = $message->getHeaders();
$headers->addTextHeader('X-MC-Template', $template_name);
$headers->addTextHeader('X-MC-MergeVars', json_encode($merg_vars));
$message->to($em_arr['to'], $em_arr['name'])->subject($em_arr['subject']);
});

The issue I got :
InvalidArgumentException in Client.php line 402: Passing in the "body" request option as an array to send a POST request has been deprecated. Please use the "form_params" request option to send a application/x-www-form-urlencoded request, or a the "multipart" request option to send a multipart/form-data request.

Can you please what's went wrong in my code. Can you please provide solution to send an email.

**Comment by Raghava525** [comment]
It has worked fine when am using guzzlehttp 4  version

**Comment by mtdowling** [comment]
The error message describes exactly how to remedy the error. Did the two suggestions not work for you?

**Comment by Raghava525** [comment]
When I am trying to send the email using swift mailer api to send the mandrill template in laravel 5.0. 
When we sending the emails I have got the error like above.

**Comment by sagikazarmark** [comment]
Between Guzzle 4 and 6 there are two major versions which indicates that there might be BC breaks. Please check whether any of the suggested fixes work for you.

**Comment by Raghava525** [comment]
Thanks for giving response to my code issue.
I have upgraded my laravel 5.0 to 5.1. And the emails sending is working fine.
:).

Thanks.
