### ISSUE TITLE
form_params in POST with Pool ?

### ISSUE THREAD

**Issue by dann95** [guzzle/guzzle#1567]
hi there is a way to fill form_params in a pool?

i tried with body 
```php
\GuzzleHttp\Psr7\stream_for('foo=bar')
```` 
but the only way i see using the class GuzzleHttp\Psr7\Request is making a instance of GuzzleHttp\Client and than passing it as option like:

```php
$client = new Client();
$request = new Request('POST', 'http://localhost:9898', []);
$client->send($request,['form_params' => ['foo' => 'bar']]);
```

but i dont found way using GuzzleHttp\Pool and set the form_params option , is it possible send form_params in pool? 

thanks, Daniel
and sorry for bad english :disappointed:

**Comment by mtdowling** [comment]
A pool can send any type of request with any request options. Take a look at the docs at how you can yield closures from a Pool: http://docs.guzzlephp.org/en/latest/quickstart.html#concurrent-requests

**Comment by dann95** [comment]
ok i will look that, thanks!

**Comment by wj5346599** [comment]
must on 
`new Pool()` three params transfer ['options'=>['form_params'=>[]] can work?
