### ISSUE TITLE
Constantly getting the same Response

### ISSUE THREAD

**Issue by peric** [guzzle/guzzle#1571]
In our Laravel application, I'm fetching a data from a specific API that returns JSON. Thing is - even though I make different request to different methods/endpoints, I get the same Response every time.

For example, when I make a Request to `https://api.github.com/events` and `https://api.github.com/users/:username/events`, I will always get the same Response. If I change api endpoint to `https://api-wrong.github.com`, it will of course complain that url does not exist.

We are using latest (6.2.1) Guzzle and there is no some kind of hidden caching system that we don't know about. 

I'm testing this from Laravel command and it feels really weird because it looks like something has been cached, but there is no cache configured for that. But even if it is, it would return at least different responses for different methods.

Has anyone experienced anything similar recently? Hopefully it's just some stupid issue that I'll be able to solve by tomorrow and close the ticket :)

**Comment by alexeyshockov** [comment]
Could you check all intermediate caches? Recently [it was Varnish](https://github.com/guzzle/guzzle/issues/1564), maybe in your case it's a caching proxy too...

**Comment by peric** [comment]
Looks that api we were trying to fetch from was constantly returning some kind of cached response - but we're still not completely sure. Anyway, I'll close this.
