### ISSUE TITLE
Post multiple files with guzzle V5

### ISSUE THREAD

**Issue by JLGouwy** [guzzle/guzzle#1574]
Hello everyone, 

I'm using Guzzle v5. 
The API asks me to send an array of files with "files[]" name. 

So this is my code : 

```
       $body = [
            'contact_type' => $params['contactType'],
            'customer_text' => $params['message'],
            'email' => $params['email'],
            'firstname' => $params['firstname'],
            'lastname' => $params['lastname'],
            'member_id' => $params['memberId'],
            'order_id' => $params['orderId'],
            'phone' => $params['phone'],
            'to_shop' => $params['toShop'],
            'to_operator' => $params['toOperator'],
            'files' => $params['files']
        ];
        $response = $client->post($baseUrl . "/contact", [
            'body' => $body,
        ]);
```

where $params['files'] is an array of uploaded files.
But an error 500 is occured when i'm trying to send message with files.

How to fix that ? Any ideas ? 

thanks in advance.

**Comment by sagikazarmark** [comment]
If a response is returned and the code is 500 it means there is something wrong with the API.

If there is something wrong with the input data, the response code should be something like 4xx. 5xx indicates there is something wrong on the server side. This can be a bug, or just incorrectly returned validation error. Also, I wonder if files in this case should just be the contents of the file, or should be submitted as multipart data.

I would suggest trying different inputs, inspect the actually sent requests and if the problem persists, contact the API maintainers. I doubt this is a guzzle issue, and the returned response indicates that as well.

If the answer is acceptable for you, please close this issue.

**Comment by JLGouwy** [comment]
Yep. But with Postman, i've no error with the API. 
And files are correctly sent. 

The code above seems correctly for you ? 

where $params['files'] are an array of uploaded files. 
But i tried with one single file, there is no error, message is sent ... without file attached.

**Comment by sagikazarmark** [comment]
What does "uploaded files" mean? A list of files? I highly doubt Guzzle will recognize that and upload the files for you.

I still recommend you to inspect the sent HTTP request itself and compare it to what you did in Postman. Maybe a missing header somewhere?

**Comment by JLGouwy** [comment]
```
if(!empty($request->file())) {
            foreach($request->file() as $file) {
                if($file->getClientSize() > 5000000) {
                    $errors = ['type' => 'danger', 'title' => 'Le fichier ' . $file->getClientOriginalName() . ' est trop lourd. Maximum 5mo.'];
                    return redirect()->back()->withInput()->with(['messages' => $errors]);
                }

                if(!in_array($file->getMimeType(), getAcceptedMimeTypes())) {
                    $errors = ['type' => 'danger', 'title' => 'Le fichier ' . $file->getClientOriginalName() . ' n\'est pas au bon format.'];
                    return redirect()->back()->withInput()->with(['messages' => $errors]);
                }
                $files[] = new \GuzzleHttp\Post\PostFile('files', fopen($file->getPathname(), 'r'));
            }
        }
```

i sent to guzzle(V5) , where param['files'] is an array of $files in the above code.

**Comment by sagikazarmark** [comment]
It's still not obvious what `$request->file()` is. A list of file names, an array of file contents, what?

Please try to compare the two HTTP requests done by Guzzle and Postman.

Again, 500 error means there is something wrong with the API. If it's because of invalid data sent from the client, you should still contact the API provider, because in that case their return code is wrong and they might have some more details about the problem.

Even then, Guzzle is not responsible for the *content* that you send, so I doubt this is a Guzzle issue.
