### ISSUE TITLE
Progress downloaded in Guzzle 6

### ISSUE THREAD

**Issue by PheRum** [guzzle/guzzle#1576]
Hello.
In Guzzle 3 code can be used to form such load status tracking.
```php
$req = $this->client->createRequest('GET', 'http://...', [
    'save_to' => '/path/to/file',
]);

$req->getEmitter()->on('progress', function (ProgressEvent $e)
{
    printf("Downloaded: %s of %s", $e->downloaded, $e->downloadSize);
});
```
As will now look like the following code in Guzzle 6?

**Comment by shaunbramley** [comment]
Guzzle underwent significant architecture changes from v3 to v6.  I highly recommend the [documentation](http://guzzle.readthedocs.io/en/latest/).  Ironically, while i do recommend the documentation, the progress request option is not mentioned within; references to it can be found  [here](https://github.com/guzzle/guzzle/blob/master/src/RequestOptions.php)

```
$result = $client->request(
    'GET',
    $url,
    [
        'sink' => 'path/to/file',
        'progress' => function($dl_total_size, $dl_size_so_far, $ul_total_size, $ul_size_so_far) {
            //do something
        },
    ]
);
```
