### ISSUE TITLE
Empty body when debugging request with `Middleware::log`

### ISSUE THREAD

**Issue by pbuyle** [guzzle/guzzle#1582]
If you do something like

```
...
$stack = \GuzzleHttp\HandlerStack::create();
$stack->push(Middleware::log($logger, new MessageFormatter($message_template)));
...
```

Where `$message_formatter` include `{request}` or `{res_body}`, then the message formatter will consume the response's body. Because the body is a stream, any other piece of code consuming the body will have to rewind the stream (if possible, otherwise the response is lost to them).

As a consumer of the API, I would assume `Middleware::log` would take care to ensure the returned log middleware does not actually alter the logged objects.

This behavior is not documented, neither for `Middleware::log` or `MessageFormatter`. Someone with a good understanding of the behind the scene stream handling may guess it, but otherwise users are left to wonder what's going on and what they did wrong.

**Comment by pbuyle** [comment]
The following is a workaround this issue, but I've not been using Guzzle for long so I'm not sure of its robustness...
```php
$stack = \GuzzleHttp\HandlerStack::create();
$stack->push(
  function (callable $handler) use ($logger, $message_formatter, $logLevel) {
    return function ($request, array $options) use ($handler, $logger, $message_formatter, $logLevel) {
      return $handler($request, $options)->then(
        function (ResponseInterface $response) use ($logger, $request, $message_formatter, $logLevel) {
          if (!$response->getBody()->isSeekable()) {
            $response = $response->withBody(new CachingStream($response->getBody()));
          }
          $position = $response->getBody()->tell();
          $message = $message_formatter->format($request, $response);
          $response->getBody()->seek($position);
          $logger->log($logLevel, $message);
          return $response;
        },
        function ($reason) use ($logger, $request, $message_formatter) {
          $response = $reason instanceof RequestException
            ? $reason->getResponse()
            : null;
          if ($response) {
            if (!$response->getBody()->isSeekable()) {
              $response = $response->withBody(new CachingStream($response->getBody()));
            }
            $position = $response->getBody()->tell();
          }
          $message = $message_formatter->format($request, $response, $reason);
          if ($response) {
            $response->getBody()->seek($position);
          }
          $logger->notice($message);
          return \GuzzleHttp\Promise\rejection_for($reason);
        }
      );
    };
  }
);
``` 

Basically, this ensure the response has a seekable body stream. If it doesn't, it create a new one with a new `CachingStream` body stream. It can then safely rewind the response stream to it's initial position after logging it. I assume that when the logging does not consume the body, nothing get cached and the impact of the new response and body stream would then be minimal.

**Comment by mpdude** [comment]
*metoo*

**Comment by alexandrubau** [comment]
+1

**Comment by avido** [comment]
Too bad the solution is already provided and no action is taken. @pbuyle maybe you can create a PR?

**Comment by sagikazarmark** [comment]
Unfortunately this is a complex problem. There is already long discussion in #1262 and a proposed fix in #1842, but I am not 100% sure about that, because it only solves half of the problem.

We will probably either just go with that solution or try the buffered stream idea I meantioned in https://github.com/guzzle/guzzle/pull/1262#issuecomment-244891225 (and as far as I can see, the proposed solution in this issue is quite similar to that).

I have to ask a little bit more patience though: we are working hard to release 6.3 as it already includes more than one year of work. Once that's out we can concentrate on other pressing issues, like this one.

**Comment by topikito** [comment]
Hey guys - Any update on this?

**Comment by kgrosvenor** [comment]
Try rewinding the request

**Comment by tukataka** [comment]
Got it now on php 7.1, guzzle 6.3.3.
Pls, fix it )

**Comment by tukataka** [comment]
Resolve this problem with creating
`
$mapResponse = Middleware::mapResponse(
                function(ResponseInterface $response) {
                    $response->getBody()->rewind();
                    return $response;
                }
            );
`

And add
`
$stack->push($mapResponse);
`

**Comment by jboonstra** [comment]
[tukataka wrote](https://github.com/guzzle/guzzle/issues/1582#issuecomment-397583084)

> Resolve this problem with creating `$mapResponse = Middleware::mapResponse( function(ResponseInterface $response) { $response->getBody()->rewind(); return $response; } );`
> 
> And add
> `$stack->push($mapResponse);`

This worked well for me to solve this problem. Note that you need to push the mapResponse handler *before* you push the log handler, as the handlers seem to get executed in reverse order.

**Comment by pbuyle** [comment]
Wouldn't this (silently) fails if response is not seekable ?

**Comment by jboonstra** [comment]
Ah yes, I think you're right. My understanding of the problem was incomplete. I've adjusted my fix to match your solution (well, to match the PR in #1262, which is very similar to yours). Thanks, @pbuyle!

**Comment by zlodes** [comment]
Any updates?

**Comment by Nyholm** [comment]
General rule: If you get a `Stream` or a `resource` and you don't know where the cursor is, then you should put the cursor in a known position. You should not make assumptions where it is. 

Guzzle, PSR-18 nor PSR-7 define where the cursor should be. 

With a PSR-7 Stream, if you `__toString()` instead of `getContents()` you are always safe. 

I know this is both weird and tricky and you thing the PSR-7 naming is messed up, and I agree with you. But if you always move the cursor before you read/write stuff, then you are okey.

**Comment by juslintek** [comment]
This one is back in 7.8.1:
adding this middleware returns empty content when request is made via Command :-)
```php
            'middlewares' => [
                Middleware::log(
                    $this->logger,
                    new MessageFormatter("
                    Request: {request}\n\n
                    Request Headers: {req_headers}\n\n
                    Request Body: {req_body}\n\n
                    Response: {response}\n\
                    Response Headers: {res_headers}\n\n
                    Response Body: {res_body}\n\n
                    ----------------------------
                    "),
                )
            ],
```

$this->logger is default injected symfony logger that logs using monolog to dev.log. Request is logged, but defined Commands like getUsers, that point to appropriate endpoint reutrn `['content' => '']`
