### ISSUE TITLE
Guzzle reponse is different from others HTTP clients 

### ISSUE THREAD

**Issue by ludofleury** [guzzle/guzzle#1583]
Hi, I'm totally bugged since few hours...

I have a basic JSON API powered by Symfony 3 running under docker php:7.0.10-fpm
Everything is fine with the API, yet when I decided to use Guzzle 6.2 to crawl it, I noticed 2 strange behaviours.

First, POST request are fine, yet on some GET request the body content is not the one expected.
I have a json value which is a collection of object: 

```
{
    "myKey": "myValue",
    "myCollection": [{ ... }]
}
```

For a very strange reason, Guzzle body response always display an empty collection while curl, javascript, chrome, php curl are actually displaying the collection. 

For another strange reason, the GET request issued by Guzzle to the API doesn't show up in the Symfony Profiler (while, the POST request from Guzzle are collected).

I don't find any logic there. If someone has a clue...

**Comment by alexeyshockov** [comment]
You have to debug your system. 1) for a caching proxy, for example, or any other caches, 2) for additional headers/cookies, that you send from other client (Chrome/JS/...), but not from Guzzle. There is not enough information for any other advices.

Guzzle by default works in the same way as PHP's cURL, so it's strange that you have such issue. Try to find differences in your calls (missed headers, as I said before, other things).

**Comment by ludofleury** [comment]
Ok, It was extra late an I wasted few hours on that, but the base_uri got us. Nevermind, sorry for the noise and thank you @alekseykuleshov for the support.
