### ISSUE TITLE
Is there a way to get resolved ip address after a response is received

### ISSUE THREAD

**Issue by chrisyue** [guzzle/guzzle#1584]

**Comment by alexeyshockov** [comment]
Currently, out of the box — no.

But there is a cURL handler-specific to way to get it. Try to get inspiration from this [SO question](http://stackoverflow.com/questions/1369760/php-curl-retrieving-server-ip-address).

``` php
$verboseLogStream = fopen('php://temp', 'r+');

$response = $httpClient->get('/user', [
    'curl' => [
        CURLOPT_VERBOSE => true,
        CURLOPT_STDERR => $verboseLogStream,
    ]
]);

rewind($verboseLogStream);
$verboseLog = fread($verboseLogStream, 8192);

$ip = null;
if (preg_match('/Connected to \S+ \((\S+)\) port/', $verboseLog, $matches)) {
    $ip = $matches[1];
}
```

You can start with something like that and create a middleware, for example.

**Comment by Nyholm** [comment]
Thank you Alexy for an excellent answer

**Comment by chrisyue** [comment]
@alexeyshockov thank you

**Comment by zuozp8** [comment]
it can be done now like

**Comment by mattkolb** [comment]
I found the following helpful:
```php
$client->getAsync($url,
	array(
		'on_stats' => function ($stats) {
			if ($stats->hasResponse()) {
				$stats->getResponse()->stats = $stats;
			}
		}
	))
	->then(function ($response) {
		// now you can access $response->stats
	});
```

I'm also using some [middleware](https://github.com/Kevinrob/guzzle-cache-middleware) to cache responses. By storing the stats as part of the response, they are cached along with the response.

**Comment by heroyan** [comment]
> I found the following helpful:
> 
> ```
> $client->getAsync($url,
> 	array(
> 		'on_stats' => function ($stats) {
> 			if ($stats->hasResponse()) {
> 				$stats->getResponse()->stats = $stats;
> 			}
> 		}
> 	))
> 	->then(function ($response) {
> 		// now you can access $response->stats
> 		$handler_stats = $response->stats->getHandlerStats();
> 		$remote_ip = $handler_stats[primary_ip];
> 	});
> ```
> 
> I'm also using some [middleware](https://github.com/Kevinrob/guzzle-cache-middleware) to cache responses. By storing the stats as part of the response, they are cached along with the response.

thks
