### ISSUE TITLE
Is there any way to download Private transparent proxy cache files faster.

### ISSUE THREAD

**Issue by polupraneeth** [guzzle/guzzle#1587]
## ###  I am trying to download the file from the file sharing website but it really slow down the execution of the script and for the large file it is giving me the time out error. I tried every thing but still unable to download the file as fast as it can be.

`use GuzzleHttp\Client;
use GuzzleHttp\HandlerStack;

use Kevinrob\GuzzleCache\CacheMiddleware;
use Doctrine\Common\Cache\ChainCache;
use Doctrine\Common\Cache\ArrayCache;
use Doctrine\Common\Cache\FilesystemCache;
use Kevinrob\GuzzleCache\Strategy\PrivateCacheStrategy;
use Kevinrob\GuzzleCache\Storage\DoctrineCacheStorage;

use GuzzleHttp\Psr7;
use GuzzleHttp\Cookie\FileCookieJar;

$current_dir = getcwd();
$temp_dir = "/temp/"; 
$cache_dir = "/cache/";

$stack = HandlerStack::create();
$stack->push(new CacheMiddleware(
new PrivateCacheStrategy(
new DoctrineCacheStorage(
new ChainCache([
new ArrayCache(),
new FilesystemCache($current_dir . $cache_dir),
])
)
)
), 'cache');

// Guzzle init
$cookieJar = new FileCookieJar($current_dir . $temp_dir .'jar.txt', true);
$client = new Client([
'defaults' => ['debug' => true],
'verify' => $current_dir . $temp_dir ."cacert.pem",
'handler' => $stack,
'cookies' => $cookieJar
]);

$download_file = "http://affix.is/mp3embed-1cg17i8ptsc8.mp3";
$resource = fopen($current_dir . $temp_dir ."temp.ext", 'w');
$response = $client->request('GET', $download_file, ['sink' => $resource]);
$html .= html_status($response);

`

**Comment by sagikazarmark** [comment]
This guzzle cache library is not developed by the Guzzle team, so we can't provide support for it, sorry.

Large file downloads should not be a problem, although the server settings and the speed are not something that Guzzle can change.
