### ISSUE TITLE
GET request with array body returns an error

### ISSUE THREAD

**Issue by SolarBear** [guzzle/guzzle#1594]
Version : Composer package v. 6.1

I'm not very familiar with Guzzle yet but there seems to be a smal inconsistency within the Guzzle client. I'm making the following query:

``` php
$client = new GuzzleHttp\Client( .... );
$response = $client->request(
    'GET',
    'http://httpbin.org',
    [
        RequestOptions::BODY => [
            'hello' => 'world'
        ]
    ]
);
```

This code throws the following exception: 

> Passing in the "body" request option as an array to send a POST request has been deprecated. Please use the "form_params" request option to send a application/x-www-form-urlencoded request, or a the "multipart" request option to send a multipart/form-data request.

Now this is clearly not a POST request so either the exception message is wrong or an additional check is required to check for the client method being used before throwing the exception. I would make a PR but I'm not sure which one's right.

Thank you for your great work! :+1:

**Comment by gmponos** [comment]
I know it's been a long time.. Personally I would accept a PR about changing the message.. Let me know...
