### ISSUE TITLE
cURL error 56: Received HTTP code 417 from proxy after CONNECT

### ISSUE THREAD

**Issue by theovaldi** [guzzle/guzzle#1599]
Hey Guys,

I'm having problem here.. i got a message error : 

Fatal error: Uncaught exception 'GuzzleHttp\Exception\RequestException' with message 'cURL error 56: Received HTTP code 417 from proxy after CONNECT (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)' in C:\xampp\htdocs\TRELLO\trello\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php:188 Stack trace: #0 C:\xampp\htdocs\TRELLO\trello\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php(151): GuzzleHttp\Handler\CurlFactory::createRejection(Object(GuzzleHttp\Handler\EasyHandle), Array) #1 C:\xampp\htdocs\TRELLO\trello\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php(104): GuzzleHttp\Handler\CurlFactory::finishError(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory)) #2 C:\xampp\htdocs\TRELLO\trello\vendor\guzzlehttp\guzzle\src\Handler\CurlHandler.php(45): GuzzleHttp\Handler\CurlFactory::finish(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory)) #3 C:\xampp\htdocs\TRELLO\trello\vendo in C:\xampp\htdocs\TRELLO\trello\vendor\stevenmaguire\trello-php\src\Http.php on line 273

Can Anyone help me, why this error occured? and what should i do? 
Every Help will be appreciated.. Thanks Before,

Best Regards,
-Me

**Comment by Nyholm** [comment]
Hey. 
Thank you for this issue. 
When reading the exception message I see that you got error 56. The exception guides you to a page (http://curl.haxx.se/libcurl/c/libcurl-errors.html) that describes the what error 56 means. It says: 

> Failure with receiving network data.

Failing to receive network data could be because the server is not reachable. This is not caused by an issue with Guzzle.
