### ISSUE TITLE
fread length is zero

### ISSUE THREAD

**Issue by neshala** [guzzle/guzzle#1607]
I am downloading video files with size between 20 and 100 MB using Guzzle Client Get method. But from time to time I have this error:

`PHP Warning:  fread(): Length parameter must be greater than 0 in vendor/guzzlehttp/psr7/src/Stream.php on line 211`

As a result i receive invalid file with missing data.

Using it on PHP 7.0.8-0ubuntu0.16.04.2

Anyone have idea what could be wrong?

**Comment by michaelbutler** [comment]
this was fixed and merged in https://github.com/guzzle/guzzle/pull/1577

It should go away when you pull down the latest Guzzle version.

**Comment by neshala** [comment]
I just created new dir and executed:
composer require guzzlehttp/guzzle

Than I opened this file:

src/Handler/StreamHandler.php

But line 213 appears to not be updated.

`strlen($contentLength) > 0 ? (int) $contentLength : -1`
instead of 
`(strlen($contentLength) > 0 && (int) $contentLength > 0) ? (int) $contentLength : -1`

Is this some problem related to packigist, or something else? It appears that it does not deliver latest changes.

**Comment by michaelbutler** [comment]
Ah you are correct. The fix has not been made into a release yet, last release was 6.2.1 in July: https://github.com/guzzle/guzzle/releaseshttps://github.com/guzzle/guzzle/releases

This will get the change for now:

Set in composer.json:
`"guzzlehttp/guzzle": "dev-master"`
Run:
`composer update`

**Comment by neshala** [comment]
Thanks, using dev-master solved this issue, looking forward to see it integrated in the next release.
