### ISSUE TITLE
https fails due to missing (root) certificates (SLES 12)

### ISSUE THREAD

**Issue by zeromat** [guzzle/guzzle#1609]
Guzzle in drupal8 failed to connect under SLES 12
elsewhere not tested

function.php::default_ca_bundle() should add
    // SLES 12
         '/var/lib/ca-certificates/ca-bundle.pem',

 cf. https://www.suse.com/releasenotes/x86_64/SUSE-SLES/12/ 
3.1.3.7 Change of Default Locations for Root Certificates REPORT BUG #

**Comment by sagikazarmark** [comment]
The above link does not provide information about the actual file path. Can you please confirm that it is correct? Also, can you please tell me which package holds this file on Suse?

Thanks in advance
