### ISSUE TITLE
Response from server truncated

### ISSUE THREAD

**Issue by Servuc** [guzzle/guzzle#1610]
Hi,

Last week, I have implemented Guzzle into my project as Retry proxy request. I works fine, but a response from my API is bigger than 8192 characters, and Guzzle cut it approximately here.

I do that : 

```
return $myClient->get( $this->transformUri($request->getUri()) );
```

Should I use Stream ? And in that case, which Stream ?

I have try to add a `try catch` but it handle nothing (Logic because response is returned). 

My system : 

> bananapi@bananapi:/var/www/SPadPro_Replicator/benchmark$ php -v
> PHP 5.6.24-0+deb8u1 (cli) (built: Jul 26 2016 14:40:24) 
> Copyright (c) 1997-2016 The PHP Group
> Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
>     with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies
> 
> bananapi@bananapi:/var/www/SPadPro_Replicator/benchmark$ curl -V
> curl 7.38.0 (arm-unknown-linux-gnueabihf) libcurl/7.38.0 OpenSSL/1.0.1t zlib/1.2.8 libidn/1.29 libssh2/1.4.3 librtmp/2.3
> Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp scp sftp smtp smtps telnet tftp 
> Features: AsynchDNS IDN IPv6 Largefile GSS-API SPNEGO NTLM NTLM_WB SSL libz TLS-SRP

**Comment by sagikazarmark** [comment]
@Servuc I set up a basic reproduction environment, but I can't really reproduce your issue.

https://github.com/reproduce/guzzle/tree/issue1610

Can you please try to use this env, maybe provide a PR if the issue is not environmental.

**Comment by Servuc** [comment]
I've just to read the doc : 

http://docs.guzzlephp.org/en/latest/request-options.html#stream

```
$response = $client->request('GET', '/stream/20', ['stream' => true]);
// Read bytes off of the stream until the end of the stream is reached
$body = $response->getBody();
while (!$body->eof()) {
    echo $body->read(1024);
}
```

**Comment by Eugene-Melbourne** [comment]
I have just answered the same question on stackoverflow
https://stackoverflow.com/questions/53862823/error-logging-is-truncated-in-laravel-4-of-guzzle-http/54244350#54244350

you just need to cast it to string

\Log::debug((string) $ex->getResponse()->getBody());

**Comment by Servuc** [comment]
Hello @Eugene-Melbourne , 

That was not the solution because my request is longer than default response. I've not read source code but I supposed that cast body into string is the same as make read() of body with a defined default size (1024) in my case. So my JSON was truncated. The safest code is to make a complete reading while EOF.

Have a good coding day ;)

**Comment by Shardj** [comment]
Hey could you clarify what the 'default size' is in any given case? Where is it defined? This type casting to string / truncation issue has caused me a nightmare in the codeception project so it would help me if I understood exactly why the original implementation was failing.

**Comment by Servuc** [comment]
Hi,
I haven't find where that value was defined.
I think it's corresponding to default value in PHP (https://www.php.net/manual/en/function.fread.php)

Documentation say that length by default is 8192 bytes => 1024 chars :)

I hope I help you :)

**Comment by Shardj** [comment]
Thanks for the info
