### ISSUE TITLE
Can we get a 6.2.2 release please?

### ISSUE THREAD

**Issue by mpdude** [guzzle/guzzle#1615]
The fix for #1577 did not make it into any release yet and seems to have been reported and/or addressed by different people already. It would be helpful if we could get that out of the door with a 6.2.2 tag.

Thanks!

**Comment by michaelbutler** [comment]
+1 agreed as it seemed to be a breaking change. Would be great to get a small hot fix in.

**Comment by sagikazarmark** [comment]
There you go: https://github.com/guzzle/guzzle/releases/tag/6.2.2

**Comment by mpdude** [comment]
Wow, that was fast :) :tada:
