### ISSUE TITLE
Multiple sync requests

### ISSUE THREAD

**Issue by caiquecastro** [guzzle/guzzle#1616]
I have an app that makes a lot (100+) requests to an API. It's doing a good job until its 10th request, but then it starts getting very slow. Do you know about any issue or an alternative solution? Do you know if setting the Connection header differently should work?

**Comment by Nyholm** [comment]
Could you elaborate a bit? What is getting slow? Your PHP code? The server response? Is it a CPU/Memory issue on your host?

**Comment by hex7c0** [comment]
same problem with release 6.2.2

6.2.1 seems ok

**Comment by caiquecastro** [comment]
My issue was not related to Guzzle. It's now ok for me.

**Comment by Nyholm** [comment]
Okey. Closing the issue then.
