### ISSUE TITLE
Authentication without Username/Password

### ISSUE THREAD

**Issue by mavarazo** [guzzle/guzzle#1623]
Hello

Maybe I don't know, how I should make this.
I want to use https://api.thetvdb.com/swagger#!/Authentication/post_login and this requires instead of Username/Password the API-Key.

How can I pass the API-Key with Authentication?

Thanks...

**Comment by sagikazarmark** [comment]
According to that documentation, you need to send a request to the `/login` route with your API key, Username and Password which returns a JWT token for you. After that you can add that token as Bearer Authorization header to all your subsequent requests.

Hope that helps.
