### ISSUE TITLE
Retrieve a specific cookie by key

### ISSUE THREAD

**Issue by kirkegaard** [guzzle/guzzle#1624]
Im trying to interact with this website, but for the login i need a csrf token which is generated on the first request to the login page. The token is saved as csrftoken and i can see the token in my cookiejar.

Now, on the post request to the login service i need that token. The reason i need that token is because the login service expects the name to be csrfmiddlewaretoken and not csrftoken.

Is there any way to retrieve the cookie and set a new one, or would i have to iterate the cookies until i find the one with the name set to csrftoken?

If so, would it be possible to add a `getCookie($name)` method to the cookiejar? 

I really like how python requests handle [session objects](http://docs.python-requests.org/en/master/user/advanced/). A similar thing would be really useful!

**Comment by sagikazarmark** [comment]
@kirkegaard There is a PR for that: #1318

Are you willing to contribute and finish it?

**Comment by kirkegaard** [comment]
Sure I'll take a look at it :) Need to brush up my knowledge on contributing on a pull request first..

**Comment by kirkegaard** [comment]
Could you give me a hint on how to commit to the pull request? Ive added the changes from the PR thread here https://github.com/kirkegaard/guzzle/commit/90386e5d62616015fa7cca562b9d3d2b06c3b535

**Comment by sagikazarmark** [comment]
You can create a PR here: https://github.com/guzzle/guzzle/compare/master...kirkegaard:pr/1318

However, you should talk to the original author of the PR first. If he does not respond, let's say in a week then we can close his and accept yours instead.

**Comment by kirkegaard** [comment]
Looks like @dylan-mcdonald fixed it, so lets merge and close this :)
