### ISSUE TITLE
Cannot set custom exceptions on RequestException::create

### ISSUE THREAD

**Issue by gmponos** [guzzle/guzzle#1628]
Basically the need that led me to create the following PR https://github.com/guzzle/guzzle/pull/1626 was that in my projects I have removed the default `Middleware::httpErrors`  from the stack handler and replaced it with my own httpErrors middleware. The middleware that I pass depending on the Http Status Code returns the Exception that I need (like the ones on the PR).

The issue here is that I can't use the `RequestException::create` because this function returns only `RequestException`, `ServerException`, `ClientException`, and I need to use the create instead of the constructor because it contains, or it might contain in the future, some helpful logic (mainly for normalizing the messagem like obfuscate the URI).

So if someone like me has it's own custom exceptions that they always extend the `RequestException` then he needs either to use the constructor or copy paste the create function in each Exception and maintain it on every release.

I thought of some alternative solutions that I would like to point out.

1st solution 
Add more Exceptions to the package like the PR

2nd solution
Pass on the create function a class like an ExceptionResolver

``` php
RequestException::create(
    RequestInterface $request,
    ResponseInterface $response = null,
    \Exception $previous = null,
    array $ctx = [],
    ExceptionResolverInterface $exceptionResolver = null
)
```

This interface will resolve what class and label should the `create` factory function return. 

3rd solution 
Add function `normalizeMessage`

``` php
    public static function normalizeMessage(RequestInterface $request, ResponseInterface $response)
    {
        $uri = $request->getUri();
        $uri = static::obfuscateUri($uri);

        $level = (int)floor($response->getStatusCode() / 100);
        if ($level === 4) {
            $label = 'Client error';
        } elseif ($level === 5) {
            $label = 'Server error';
        } else {
            $label = 'Unsuccessful request';
        }

        // Server Error: `GET /` resulted in a `404 Not Found` response:
        // <html> ... (truncated)
        $message = sprintf(
            '%s: `%s` resulted in a `%s` response',
            $label,
            $request->getMethod() . ' ' . $uri,
            $response->getStatusCode() . ' ' . $response->getReasonPhrase()
        );

        $summary = static::getResponseBodySummary($response);

        if ($summary !== null) {
            $message .= ":\n{$summary}\n";
        }
        return $message;
    }
```

Mainly the create function is for creating an Exception with normalized message.

**Comment by sagikazarmark** [comment]
In my opinion injecting custom logic to Guzzle's domain is not a good idea. Guzzle should not even be used directly by your code, rather through some adapters/bridges. That way you can easily add your own behavior: catch exceptions and rethrow your own domain exceptions, etc.

This seems to be overengineering to me and as I said above, this should not even be necessary if you go with better designed solutions and don't rely on Guzzle directly in your code.

**Comment by gmponos** [comment]
@sagikazarmark Sorry but there are some things that I didn't get them on your response.

> This seems to be overengineering to me and as I said above, this should not even be necessary if you go with better designed solutions and don't rely on Guzzle directly in your code.

Even if my implementation might seem like overengineering if someone needs to extend the current Exceptions he can't. IMHO and correct me if I am wrong I think that the current version is violating a bit the Open/Closed principle.

**Comment by sagikazarmark** [comment]
I don't think it has anything to do with the open/closed principle. You are free to extend the exception or use it as you will. But the exceptions are part of Guzzle's public API too (I mean the Client itself). Strictly speaking your solution would not break the API as (hopefully) your custom exceptions would implement/extend the relevant exceptions.

However, the fact that you need to extend the API suggests a wrong design. According to the inversion of control principle you should not rely on Guzzle in your domain, instead you should apply the adapter pattern and create your own domain exceptions or error handling.
