### ISSUE TITLE
guzzle 6 AbstractClient not found

### ISSUE THREAD

**Issue by 2ndGAB** [guzzle/guzzle#1630]
Hello,
I've installed [guzzle-services](https://github.com/guzzle/guzzle-services/tree/guzzle6), [guzzle-command](https://github.com/guzzle/command/tree/guzzle6) and guzzle 6 and on execution, I get the following error.

```
Error: Class 'GuzzleHttp\Command\AbstractClient' not found
File /var/www/2ndGuide/vendor/guzzlehttp/guzzle-services/src/GuzzleClient.php
Line: 17
```

It seems this `AbstractClient` was defined in previous guzzle-command version but dosen't exists anymore in 0.9.0.
Maybe replaced by `ServiceClient` now ??

Any idea?

**Comment by 2ndGAB** [comment]
Sorry this problem seems to come from guzzle-services

**Comment by sagikazarmark** [comment]
Have you been able to solve them? I am not really into these packages for the moment. I you find something, can you please post your findings in the relevant repository. I will try to do some myself when I have the time.

**Comment by 2ndGAB** [comment]
@sagikazarmark globally yes, in fact it comes from a module not compatible with guzzle6 so it's not really an issue

**Comment by sagikazarmark** [comment]
If the issue is in another Guzzle software, can you please open an issue there?
