### ISSUE TITLE
Should the constructor method allow to create a BadResponseException without a response

### ISSUE THREAD

**Issue by gmponos** [guzzle/guzzle#1631]
At the moment the `BadResponseException` does not have a `__constructor` method. So it uses the parent __constructor which is:

``` php
    public function __construct(
        $message,
        RequestInterface $request,
        ResponseInterface $response = null,
        \Exception $previous = null,
        array $handlerContext = []
    ) {
    ...
    }
```

The above allows to create a `BadResponseException` with no response. All BadResponseExceptions are for 4xx and 5xx. I guess that you always have a response on these codes.

By allowing the response to be null, the programmer has to check if there is a response in order to be sure.

``` php
try{
    $client->get('/myurl');
} catch (BadResponseException $e) {
     if($e->hasResponse()){
         $e->getResponse()->getStatusCode();
     }
}
```

So what I suggest is that the BadResponseException to have a constructor disallowing someone to create an Exception like this without a response.

``` php
class BadResponseException extends RequestException
{

    public function __construct(
        $message,
        RequestInterface $request,
        ResponseInterface $response,
        \Exception $previous = null,
        array $handlerContext = []
    ) {
        parent::__construct($message, $request, $response, $previous, $handlerContext);
    }
}
```

If you agree I can make the PR.

**Comment by sagikazarmark** [comment]
This seems to be an obvious leak to me, I wonder why it hasn't been handled. Any reasons @mtdowling ?

Is this not a BC break?

**Comment by gmponos** [comment]
If you ask me then I would say that it is  BC break...
