### ISSUE TITLE
Is the UriTemplate used in Guzzle6?

### ISSUE THREAD

**Issue by gmponos** [guzzle/guzzle#1633]
I saw the UriTemplate and read the [tests ](https://github.com/guzzle/guzzle/blob/master/tests/UriTemplateTest.php#L33) about it and I was very surprised about it's capabilities but I can't seem to find a usage of it inside Guzzle Client

So I was wondering if there is a way I could do something like:
``` php
$client->get('www.test.com/v1/{user}', [
    'user' => 'gmponos'
]);
```
and the Request Target to be `www.test.com/v1/gmponos`.

**Comment by jeskew** [comment]
You would need to resolve the templated URI before passing it to the client, which can be done with the `\GuzzleHttp\uri_template` function. For example:

```php
$uri = \GuzzleHttp\uri_template('www.test.com/v1/{user}', [
    'user' => 'gmponos'
]);
$response = $client->get($uri);
```

**Comment by gmponos** [comment]
Can't this be added to Guzzle?

``` php
$client->get('www.test.com/v1/{user}', [
    'uri_template' => [
        'user' => 'gmponos'
    ]
]);
```
I am willing to work on PR like this.

**Comment by sagikazarmark** [comment]
I would say it's too much responsibility and not really obvious usage. The way @jeskew showed seems perfect to me.

**Comment by gmponos** [comment]
Hello,

I would like to bring this issue up again. The reason is that I tried to use the UriTemplate with a UriInterface and my tests where always failing.

What I did:

```php
$uriInterface = Psr7\uri_for('http://www.fetch.com/path/v1/{format}')

$request = new Request('get', $this->uriTemplate->expand((string)$uriInterface, [
    'format' => 'json',
]));

...
...

//in my tests

$request = $this->mockHandler->getLastRequest();
$this->assertEquals('/path/v1/json', $request->getUri()->getPath()); // This keeps failing
```


```
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'/path/v1/json'
+'/path/v1/%7Bformat%7D'
```

It seems that UriInterface encodes the path (as it should I think) but this makes the UriTemplate useless in a way. I see that there a lot of `magic` lost in here and I will need to do things manually.
