### ISSUE TITLE
 How to use Socks 5?

### ISSUE THREAD

**Issue by DenoBY** [guzzle/guzzle#1636]
Show an example of how to use please Socks5 in guzzle

**Comment by sagikazarmark** [comment]
Have you tried setting the proxy option to something like `socks5://localhost:2001`?

**Comment by DenoBY** [comment]
```
$this->client = new Client([
    'headers' => [
        'Host' => 'www.exemple.com',
         'User-Agent' => 'Mozilla/5.0 (Windows NT 6.1; rv:49.0) Gecko/20100101 Firefox/49.0',
    ],
    'base_uri' => 'https://www.exemple.com/',
    'cookies' => $this->cookie,
    'proxy' => 'socks5://66.253.232.246:45554'
]);
```

PHP Fatal error:  Uncaught exception 'RuntimeException' with message 'Error creating resource: [message] fopen(https://www.exemple.com/): failed to open stream: Unable to find the socket transport "socks5" - did you forget to enable it when you configured PHP?

**Comment by sagikazarmark** [comment]
I will take a look at it

**Comment by DenoBY** [comment]
@sagikazarmark  The problem was due to the fact that the socks had to call the above. 

$this->client = new Client([
    'headers' => [
        'Host' => 'www.exemple.com',
         'User-Agent' => 'Mozilla/5.0 (Windows NT 6.1; rv:49.0) Gecko/20100101 Firefox/49.0',
    ],
    'proxy' => 'socks5://exemple:45554'
    'base_uri' => 'https://www.exemple.com/',
    'cookies' => $this->cookie
]);

I have an anonymous socks and I can not get authorization. Maybe you know how? 'proxy' => 'socks5:/login:pass@exemple:45554' does not work

**Comment by nesttle** [comment]
Same here (auth to proxy not working)

**Comment by sagikazarmark** [comment]
Hm, is this a duplication of #1484?

**Comment by sagikazarmark** [comment]
Closing this in favor of #1484
