### ISSUE TITLE
Debug to syslog

### ISSUE THREAD

**Issue by garnold** [guzzle/guzzle#1637]
Hello,

We run all of our applications on Google App Engine which uses syslog for logging.  Is there a way to configure Guzzle to use `syslog` for the debug option?

Thanks,
Geoff.

**Comment by garnold** [comment]
I'm thinking I can register a custom stream wrapper to handle this... stay tuned.

**Comment by sagikazarmark** [comment]
As far as I know syslog can be configured to read from a file, can't it? A custom stream wrapper could also be a solution. Let me know if you figure this out.

**Comment by garnold** [comment]
Easy enough:

```php
in_array('syslog', stream_get_wrappers()) || stream_register_wrapper('syslog', '\SyslogStream');

$client = new GuzzleHttp\Client(['debug' => fopen('syslog://', 'w')]);
```

```php
class SyslogStream {

    function stream_open($path, $mode, $options, &$opened_path) {
        return strpos(strtolower($mode), 'w') === 0;
    }

    function stream_write($data) {
        foreach (explode("\n", $data) as $line) {
            syslog(LOG_DEBUG, $line);
        }
    }
}
```
