### ISSUE TITLE
Guzzle crashes Google App Engine

### ISSUE THREAD

**Issue by codemonkeynorth** [guzzle/guzzle#1640]
I am trying to use this firebase sdk on Google App Engine which uses google client 2.0 / guzzle 6.x on 
https://github.com/kreait/firebase-php/tree/1.x

currently it's crashing Google Cloud SDK environment's php (5.5.26) on this line
https://github.com/guzzle/guzzle/blob/113071af3b2b9eb96b05dab05472cbaed64a3df4/src/Handler/StreamHandler.php#L312

`$resource = fopen((string) $request->getUri()->withFragment(''), 'r', null, $context);`

does anyone know why this would crash php?
`ERROR:root:php failure (-1073740791)

I'm on Windows and i placed my cert at in c:\Windows\curl-ca-bundle.crt in order to allow guzzle's https calls to work (which I got from here https://raw.githubusercontent.com/bagder/ca-bundle/master/ca-bundle.crt)

I realise I'm using several libraries here, but again it's the fopen line in guzzle that's crashing the php, so that would be my first place to consider

if i try enabling curl (extension=php_curl.dll) on GAE instead (to use curl rather than StreamHandler I believe) I get this

```php
ErrorException in {...}\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php line 57:
curl_setopt_array(): cannot represent a stream of type MEMORY as a STDIO FILE*
```

thanks for any advice
J

**Comment by codemonkeynorth** [comment]
this is enough to demonstrate the problem without using the other library

```
<?php

namespace App\Http\Controllers;
class TestController extends Controller
{
    public function test() {
        $client = new \GuzzleHttp\Client();
        $res = $client->request('GET', 'https://api.github.com/user', [
        'auth' => ['user', 'pass']
        ]);
        echo $res->getBody();
    }
```

it will either:

a) crash if curl is disabled in GAE

b) report the following if  `extension = "php_curl.dll"` is enabled in php.ini
```ErrorException in {...}\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php line 57:

c)  report the following if using Curl Lite option .. 
```CurlLiteOptionNotSupportedException in C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\platform\google_appengine\php\sdk\google\appengine\runtime\CurlLite.php line 487:
Option 20056 is not supported by this curl implementation.```

obviously the latrer is a GAE issue, but the first 2 relate to guzzle code

thanks
J

**Comment by codemonkeynorth** [comment]
I did some tests for option (b) with curl enabled in php.ini

if i replace this line
https://github.com/guzzle/guzzle/blob/master/src/Handler/CurlFactory.php#L370

$conf[CURLOPT_FILE] = fopen('php://temp', 'w+');

with the following 

$conf[CURLOPT_FILE] = fopen('c://temp//test.txt', 'w+');

the code then works. 

obviously that only works with write access enabled locally (which I don't really want to do as it doesn;t work in the live environemt) and also means editing guzzle vendor files. would there be a way to make php://temp work within GAE sdk local shell?

thanks
j

**Comment by codemonkeynorth** [comment]
suggest something like this maybe for GAE Local Development Server until they fix the issue?

```php
$conf[CURLOPT_FILE] = fopen('php://temp', 'w+');
if(isset($_SERVER['SERVER_SOFTWARE']) 
    && 0 === strpos($_SERVER['SERVER_SOFTWARE'], 'Development/')) {
    $conf[CURLOPT_FILE] = fopen(getenv('temp').uniqid(), 'w+');
}
```

detect is taken from the symfony starter project
`public static function onDevAppServer()`
https://github.com/GoogleCloudPlatform/appengine-symfony-starter-project/blob/master/src/AppEngine/Environment.php#L31

this at least fixes the problem when cURL is enabled, but not the StreamHandler crash issue when cURL disabled

**Comment by sagikazarmark** [comment]
Have you tried googling the original error (ERROR:root:php failure)? I got a lot of SO results. Have you tried any of those?

Can you try this example?

``` php
$conf[CURLOPT_FILE] = fopen('php://temp', 'wb+');
```

**Comment by codemonkeynorth** [comment]
Hi @sagikazarmark ,

you've got 2 different issues slightly confused there. 

(i think it's actually just a problem with the Windows Google Cloud SDK Local Development server (LDS), since it works fine on OSX)

scenario (a) above: the crash is not related to curl. it's when curl is disabled in the LDS and it's using the StreamHandler instead when going through the authentication process.
`$resource = fopen((string) $request->getUri()->withFragment(''), 'r', null, $context);`

scenario (b) above: if curl is enabled in the LDS, then php://temp does not work for streaming data into 
`curl_setopt_array(): cannot represent a stream of type MEMORY as a STDIO FILE*`
(it's the same issue for a vfs:// protocol as well but the type is 'user-space' not 'MEMORY')

again my code in my comment above gives a simplified example not requiring libraries other than Guzzle 6
https://github.com/guzzle/guzzle/issues/1640#issuecomment-258653762

thanks
j

**Comment by sagikazarmark** [comment]
Hi @codemonkeynorth 

I think I get it right. You have two different problems with the stream handler and the curl handler.

scenario (a): with stream handler

You receive an error message: ERROR:root:php failure

Have you tried googling it? It gives you quite a few SO results with solutions. Have you tried those?


scenario (b): curl

There are some resources which suggest that streams doesn't play well on windows when not using the binary switch:

`$conf[CURLOPT_FILE] = fopen('php://temp', 'wb+');`

Note the `b`

`php://temp` actually creates a file in the temp folder, it does not write into memory. (Maybe you don't have write permission to the default system temp dir, so it creates a memory stream?)

Unfortunately I don't use Windows or GAE so I cannot reproduce your issue there. I hope that either the binary option will help (which I would happily add permanently if it does) or any of the SO answers for the streaming handler issue.

**Comment by codemonkeynorth** [comment]
Hi, thanks for the info. I tried those options for curl, but it doesn't help

it seems to be a bug in Windows version of GAE emulator shell.

I am enabling write access locally temporarily  with this php.ini flag
`google_app_engine.disable_readonly_filesystem=1`

but that does not fix their internal issue which is why i test for GAE & add the following to the Guzzle CurlFactory php file..
`fopen(getenv('temp').uniqid(), 'w+');` 

Since it works fine without these "fixes"  on both OSX and on the live appengine environement, I can only assume therefore it is a problem with their implementation of PHP/curl in their local software rather than in an issue in guzzle

I will see if I can find out what's causing the crash for non-curl, so please this open for now?

thanks
J

**Comment by sagikazarmark** [comment]
All right, let me know.

**Comment by karensg** [comment]
Hi @codemonkeynorth, @sagikazarmark!
The post is a bit old, but I have encountered the same issue.. Did you guys find a solution to fix the problem without editing the vendor file?

Thanks

**Comment by sagikazarmark** [comment]
This issue was automatically classified as stale because it lacks information or cannot be reproduced.

If you think the issue is still valid and/or misclassified, please comment on the issue thread
and provide additional information (if possible).

Also, since the time maintainers can spend on the project is limited, please provide
a possible solution if possible, especially if it involves a platform that we cannot
test ourselves (Windows, very old/specific PHP versions, etc).

Issues marked as stale with no further activity will be marked as `rotten`
at some point and will automatically be closed within 14 days.

We do this so that we can focus on high priority issues. Thank you for your understanding.

**Comment by jausions** [comment]
I had the same problem with Google Cloud Datastore on Windows local development environment (dev_appserver.py) so you might be able to adapt for Firebase.

It would seem that the following is helping. I didn't modify the core Guzzle class, but instead provided an option into my application.

```php
$guzzleClient = new Client([
	'verify' => false,
]);
$handler = function ($request, array $options = []) use ($guzzleClient) {
	if (isset($_SERVER['SERVER_SOFTWARE'])
		&& 0 === strpos($_SERVER['SERVER_SOFTWARE'], 'Development/')) {
		$options['sink'] = tmpfile();
	}
	return $guzzleClient->send($request, $options);
};

$datastore = new DatastoreClient([
	'projectId' => $project_id,
	'keyFilePath' => $key_file,
	'httpHandler' => $handler,
	'authHttpHandler' => $handler,
	'namespaceId' => $namespace,
]);
```
