### ISSUE TITLE
why i need to use  guzzle instead of file_get_contents 

### ISSUE THREAD

**Issue by imadsh** [guzzle/guzzle#1643]
Hi guys , 
I have question , i need to take a json content from url 
i can use file_get_contents to fetch this data 

but i need to know is there is any other feature or security available on guzzle ? ? 
if your are in my position what you will use  ? 
Notic : I have no idea about guzzle

**Comment by sagikazarmark** [comment]
Guzzle is an HTTP Client with quite a few features. I suggest you checking the README and the docs to see it's features and decide if you need it or not based on that.
