### ISSUE TITLE
Guzzle CURLOPT_POSTFIELDS Similar

### ISSUE THREAD

**Issue by guiajlopes** [guzzle/guzzle#1647]
Hello, I'm trying to do a request with guzzle 6.2 but it's not working. The similar code that I've tried to reproduce with guzzle is:

`$arr = array(`
 `'MediaPath' =>[path],`
`);`

`$headers = [`
        `'Authorization: [token]',`
     `   'Accept: application/json',`
      `  'Content-Type: application/json',`
`];`

`// Curl.`
`$ch = curl_init([url]);`
`curl_setopt($ch, CURLOPT_CUSTOMREQUEST, "PUT");`
`curl_setopt($ch, CURLOPT_POSTFIELDS, json_encode($arr));`
`curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);`

`// Guzzle`
`$client->request('PUT', [url], ['headers' => $headers, 'body' => json_encode($arr)]);`

`// I've tried this way as well.`
`$client->put([url], ['headers' => $headers, 'json' => $arr]);`

Anyone can help me?

**Comment by sagikazarmark** [comment]
What's not working? You didn't describe the issue itself.

**Comment by guiajlopes** [comment]
Basically my API is returning 500 to me and with CURL as described on the last commend or Postman it's returning 200. I don't know if Guzzle is doing the request properly, I think it's not passing the json as a body raw value. Do you know what it can be?

**Comment by sagikazarmark** [comment]
Your first Guzzle example seems to be correct, the second one should be `$client->put([url], ['headers' => $headers, 'body' => json_encode($arr)]);`

Can you debug the request on the server side to see the reason of the 500 error? If it's a validation issue, the API should return a 4xx code with a proper error message.

**Comment by guiajlopes** [comment]
I created an endpoint to test the result of CURL vs Guzzle request and basically the diferrences are:

Guzzle:
CONTENT_TYPE : ""
HTTP_0 : "Authorization: [token]"
HTTP_1 : "Accept: application/json"
HTTP_2 : "Content-Type: application/json"

CURL:
CONTENT_TYPE : "application/json"
HTTP_AUTHORIZATION : "[token]"
HTTP_ACCEPT : "application/json"
HTTP_CONTENT_TYPE : "application/json"

I don't know if HTTP_[number] is valid like the headers on CURL, could you comfirm that? In regards to the body it's the same.

**Comment by guiajlopes** [comment]
I figured it out, I was setting headers as json not as a array... Thanks for the help and sorry about it

**Comment by luckydonald** [comment]
So basically, instead of

```php
$headers = [
'Authorization: [token]',
'Accept: application/json',
'Content-Type: application/json',
];
```
do 
```php
$headers = [
'Authorization' => '[token]',
'Accept' => 'application/json',
'Content-Type' => 'application/json',
];
```
