### ISSUE TITLE
GuzzleHttp\Psr7\Response

### ISSUE THREAD

**Issue by undercloud** [guzzle/guzzle#1650]
`GuzzleHttp\Client::sendAsync` always return `GuzzleHttp\Psr7\Response` instance?
How can I get my own Psr7 instance? e.g. `Zend\Diactoros\Response`

**Comment by alexeyshockov** [comment]
You shouldn't want this. PRS-7 interfaces were created to define a base that is equal in all implementations. Inside this base you shouldn't care about the implementation. If you rely on the additional functionality of `Zend\Diactoros\Response`, then you have to create and adapter.

**Comment by Nyholm** [comment]
That is not all true. It is true for library authors but not for application authors. 

As an application author you may find that feature X in Zend is awesome and you see no reason why you should install two PSR 7 implementations. Guzzle has currently no support for changing PSR 7 implementations. But if you use the HTTPlug abstraction you could. 

Read more at:
http://docs.php-http.org/en/latest/httplug/users.html
http://docs.php-http.org/en/latest/clients/guzzle6-adapter.html

**Comment by undercloud** [comment]
Can You help me with promises?

```PHP
class Utils 
{
    public static function proxyResponse(RequestInterface $request)
    {
        return Zend\Diactoros\Response;
    }
}
```

```PHP
use Psr\Http\Message\RequestInterface;
use GuzzleHttp\Client as GuzzleClient;

class Client extends GuzzleClient
{
    public function __construct(array $config = [])
    {
        parent::__construct($config);
    }

    public function send(RequestInterface $request, array $options = [])
    {
        $response = parent::send($request, $options);

        return Utils::proxyResponse($response);
    }

    public function sendAsync(RequestInterface $request, array $options = [])
    {
         ...
    }
```

**Comment by alexeyshockov** [comment]
If you are building a wrapper class, then you can simply create a new promise with with Zend's response. Try something like:

```
    public function sendAsync(RequestInterface $request, array $options = [])
    {
        return parent::sendAsync($request, $options)->then(function(Response $response) {
            return Utils::proxyResponse($response);
        });
    }
```

**Comment by undercloud** [comment]
How about this? This is true way?

```PHP
<?php

public function sendAsync(RequestInterface $request, array $options = [])
{
	$thisis = $this;
	$promise = new Promise(function() use ($thisis, $promise, $request, $options) {
		$response = $thisis->send($request, $options);

		if ($response->getStatus() >= 400) {
			$promise->reject($response);
		} else {
			$promise->resolve($response);
		}
	});

	return $promise;
}
```

**Comment by alexeyshockov** [comment]
@undercloud, it works, but with that solution you destroy the idea of async requests. You return promise, but to resolve it you do synchronous request. So send() == sendAsync() if your solution, the difference is only that in the second method you additionally wrap response with a promise, but not actually execute request asynchronously.
