### ISSUE TITLE
No constants for the HTTP response codes

### ISSUE THREAD

**Issue by Keirua** [guzzle/guzzle#1651]
There are no constants for the HTTP response codes the Response object (despite a mapping of error codes). There already are such constants in project like symfony/httpfoundation, but wouldn't it be useful to have such data here ?

In my current usecase, it is semantically not correct to use symfony's constants (and would force me to add a vendor I do not need), and using the one's from Guzzle would make sense, because I'm 
checking the return code after some calls from a guzzle client.

The ideal situation would be to have such constants as part of PHP (through a PSR for instance), but it is not the case now and won't be anytime soon.

**Comment by Konafets** [comment]
You can use https://github.com/shrikeh/teapot

**Comment by sagikazarmark** [comment]
Would be nice to see some official PSR-util package for this (as in case of the cache PSR), but till then as @Konafets suggested, you can use teapot. Duplicating status code constants across HTTP Message implementations is not a good idea IMO.
