### ISSUE TITLE
LimitStream needs `seek()` before `getContents()` works

### ISSUE THREAD

**Issue by borekb** [guzzle/guzzle#1654]
Here's a code to demonstrate the issue:

```php
$stream = $response->getBody();
echo $stream->__toString(); // -> abcde12345
$stream->seek(0);
echo $stream->read(5); // -> 'abcde'

$limitStream = new LimitStream($stream, 3, $stream->tell());
echo $limitStream->getContents(); // -> '' ??

// this works:
echo $limitStream->__toString(); // -> '123'

// alternatively, this works as well:
$limitStream->seek($limitStream->tell());
echo $limitStream->getContents(); // -> '123'
```

As I debugged the code, it turned out that `$limitStream->eof()` returns true when `getContents()` is attempted. Seeking to the same position (which I don't think should have any effect) seems to fix the problem.

BTW, I'm quite new to PHP streams and also to Guzzle so maybe I'm doing something wrong. But the example above seems to me like it should work, shouldn't it?

**Comment by borekb** [comment]
One more comment: reading from LimitStream using its `read()` method works fine. The problem is when the stream is read using the `copy_to_string()` function, specifically, [this line](https://github.com/guzzle/psr7/blob/5f17a79615bd36d52d3b3ce44075aec02605d8bf/src/functions.php#L333) returns true for `eof()`.

**Comment by borekb** [comment]
There has been a similar issue in the past: https://github.com/guzzle/guzzle/issues/830. Its resolution was to add rewinding to internal adapters (which I don't think exist any longer in Guzzle v6). Maybe there's some hint.

**Comment by sagikazarmark** [comment]
I just quickly went through your issue, because didn't have much time at the moment, but one thing to note: `getContents` only returns the "remainder" of the stream (what's left between the current position and eof). So using `__toString` or casting the stream to string is actually the way to get the content of the stream regardless it's current position. If this does not help I will have a closer look, but even then I think this is an issue for the PSR-7 repo.

**Comment by borekb** [comment]
Thanks @sagikazarmark, I'm aware that `getContents()` reads only the remainder of the stream which I believe shouldn't be a problem in my case. Here is another example demonstrating the issue:

```php
// HTTP response returned a body containing text "abc"
$stream = $response->getBody();

$stream->eof();   // -> true (??)
$stream->tell();  // -> 0
$stream->seek(0); // just for fun
$stream->eof();   // -> false (!?!)
```

**Comment by GrahamCampbell** [comment]
Not a bug. `getContents` intentionally only gets the stuff after the pointer. You need `__toString()` to get the body.
