### ISSUE TITLE
force_ip_resolve request option

### ISSUE THREAD

**Issue by tuanalumi** [guzzle/guzzle#1655]
`force_ip_resolve` is documented but not available in the latest release (6.2.2). I took me time to find this out. So I think it's better if you remove this until the next release.

**Comment by sagikazarmark** [comment]
You can always switch to the stable branch of the documentation in the bottom left/right corner. Maybe we should make it the default one @mtdowling?

**Comment by errogaht** [comment]
++ same situation

**Comment by it-can** [comment]
force_ip_resolve seems not to be available in guzzle 6.2.3 :-(

**Comment by sagikazarmark** [comment]
It will be available in 6.3

You might want to switch to the stable documentation.

<img width="725" alt="screen shot 2017-03-28 at 07 52 40" src="https://cloud.githubusercontent.com/assets/1226384/24390839/9a0cf662-138b-11e7-9451-12ee8be9bf27.png">

**Comment by it-can** [comment]
It's also possible to set a curl option?

**Comment by a-komarev** [comment]
Any ETA on 6.3 release? Have issues with some of the servers which cannot connect via ipv6.

Solved it temporary by adding `'connect_timeout' => 1,` which fill fail ipv6 connect after 1 second and try to reconnect using ipv4. But want to make it in more proper way.

**Comment by a-komarev** [comment]
The more proper way:
```php
$response = (new Client())->request('GET', $uri, [
    //'force_ip_resolve' => 'v4',
    'curl' => [
        CURLOPT_IPRESOLVE => CURL_IPRESOLVE_V4,
    ],
])
```

**Comment by gmponos** [comment]
This is resolved now.
