### ISSUE TITLE
i want file filed

### ISSUE THREAD

**Issue by pouu69** [guzzle/guzzle#1660]
i want image upload

like this

```` php
curl -v -X POST https://kapi.kakao.com/v1/api/story/upload/multi \
  -H "Authorization: Bearer xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" \
  -F "file=@aws-s3-address1" \
  -F "file=@aws-s3-address2"
````

how can us file filed ?

**Comment by sagikazarmark** [comment]
Please use StackOverflow for questions like this as the answer is already there:
http://stackoverflow.com/questions/38133244/upload-file-using-guzzle-6-to-api-endpoint

BTW what you need is multipart body, which is documented here as well:
http://docs.guzzlephp.org/en/latest/request-options.html#multipart
