### ISSUE TITLE
Response body empty at error 500

### ISSUE THREAD

**Issue by Leondriel** [guzzle/guzzle#1663]
Hello there,
if the server answers with an error 500 the response body is not accessable. I want to use guzzle for different webService interfaces which transfer error codes and details in the body and my error handling needs to react differently depending on those. Here is a code sample:

try {
  // $requestOptions = ['some options, nothing fancy'];
  $handler = new GuzzleHttp\Handler\StreamHandler();
  $stack = \GuzzleHttp\HandlerStack::create($handler);
  $client = new GuzzleHttp\Client(['handler' => $stack]);
  $request = new Psr7\Request('POST', $someUrl, [], null, $requestOptions['version']??'1.1');
  $client->send($request, $requestOptions);
} catch (\GuzzleHttp\Exception\RequestException $E) { // gets caught
  if ($e->hasResponse()) {  //true
    $response = Psr7\str($e->getResponse());	//Should contain body but is empty
    $response = $e->getResponse()->getBody();  //Empty, too
  }
}

**Comment by Konafets** [comment]
Guzzle comes with dedicated Exceptions located in `src/Exception`, e.g. `\GuzzleHttp\Exception\ServerException` will be thrown when the server answers with a 5xx error code.

```php
try {
  // $requestOptions = ['some options, nothing fancy'];
  $handler = new GuzzleHttp\Handler\StreamHandler();
  $stack = \GuzzleHttp\HandlerStack::create($handler);
  $client = new GuzzleHttp\Client(['handler' => $stack]);
  $request = new Psr7\Request('POST', $someUrl, [], null, $requestOptions['version']??'1.1');
  $client->send($request, $requestOptions);
} catch (\GuzzleHttp\Exception\ServerException $e) {
  // your code when the server answers with 5xx
} 
```

**Comment by gmponos** [comment]
You have to rewind the body after this line:

    $response = Psr7\str($e->getResponse()); //Should contain body but is empty

**Comment by Leondriel** [comment]
> @Konafets: Guzzle comes with dedicated Exceptions located in src/Exception, e.g. \GuzzleHttp\Exception\ServerException will be thrown when the server answers with a 5xx error code.

ServerException is an extended RequestException. In my original code I handle multiple exception types in that catch. The thrown exception is a ServerException but it is caught by the Request exception, too.

> @gmponos: You have to rewind the body after this line[...]
I added both lines because both ways to get the body fail, no matter if you use
`$response = $e->getResponse()->getBody(); `
or
`$response = Psr7\str($e->getResponse());`
Sorry for the misleading example.

**Comment by Konafets** [comment]
`$response ≠ $body`. Your `$e->hasResponse()` doesn't tell you anything about if there is a body. From a server which sends a 5xx I would not expect a body within the response.

**Comment by Leondriel** [comment]
@Konafets Please focus on the scenario of the issue and not any possible scenario the code snippet would allow. The response IS an error 500 and there IS a body in the response, I verified that with building a little curl script to execute the request manually.

And in contrast to your expectations [RFC7231](https://tools.ietf.org/html/rfc7231#section-6.6) states that...
> Except when responding to a HEAD request, **the server SHOULD send a representation containing an explanation of the error situation**, and whether it is a temporary or permanent condition.  A user agent SHOULD display any included representation to the user.  These response codes are applicable to any request method.

**Comment by sagikazarmark** [comment]
@Leondriel both @Konafets and @gmponos had actually good points here.

I have created a reproduction environment for your issue here: https://github.com/reproduce/guzzle/tree/issue1663

As you can see the issue does not occur there, so 500 response bodies are not truncated.

Do you have any custom middlewares in the chain? Maybe a logger one?

As you can see this is not a bug, so there is a high chance that it is an environmental issue.

**Comment by Leondriel** [comment]
@sagikazarmark: Here's a dump of the requestOptions array, nothing else is set or configured:
```
array(8) {
    ["stream"]=> bool(true)
    ["http"]=> array(1) {
        ["timeout"]=> int(55)
    }
    ["ssl"]=> array(3) {
        ["verify_peer"]=> bool(false)
        ["allow_self_signed"]=> bool(true)
        ["verify_peer_name"]=> bool(false)
    }
    ["version"]=> string(3) "1.1"
    ["headers"]=> array(4) {
        ["Content-Type"]=> string(8) "text/xml"
        ["User-Agent"]=> string(21) "GateA HTTP WebService"
        ["Connection"]=> string(5) "close"
        ["Accept-Encoding"]=> string(4) "gzip"
    }
    ["body"]=> string(767) "[...]"
    ["timeout"]=> int(55)
    ["debug"]=> bool(false)
}

**Comment by sagikazarmark** [comment]
I meant a custom handler stack: http://docs.guzzlephp.org/en/latest/handlers-and-middleware.html

Also, do you use the curl or the stream handler?

**Comment by Leondriel** [comment]
No, the remaining code is like in the example at the beginning of the thread, and no custom middleware is used.

I'm use the stream handler.

**Comment by sagikazarmark** [comment]
Okay, after examining the request options: the problem is the stream option. Please see the documentation: http://docs.guzzlephp.org/en/latest/request-options.html#stream

I've also updated the reproduction environment.

**Comment by Leondriel** [comment]
@sagikazarmark Thank you, that was just the right hint. After replacing 
```
$response = Psr7\str($e->getResponse());
```
with 
```
$response = '';
$body = $E->getResponse()->getBody();
while(!$body->eof()) {
        $response.= $body->read(1024);
}
```
it works like a charm. 
If you don't intend to change Psr7\str to do the stream fetching on demand this issue can be closed.

**Comment by Mykola-Veriga** [comment]
`$body = $E->getResponse()->getBody();
$response = $body->getContents()`
