### ISSUE TITLE
Guzzle response encoding not UTF-8

### ISSUE THREAD

**Issue by theunreal** [guzzle/guzzle#1664]
I'm trying to make an HTTP POST call to an API and the response utf-8 characters are showing like this:

������

I'm usign simply:

```
$client = new Client;
		 $response = $client->post(AN_API, [
    'form_params' => [
        'name' => 'Hello',
    ]]);
		 return ($response->getBody()->getContents());
```

trying to utf8_encode returns letters like this: áãé÷

**Comment by Konafets** [comment]
Without any further informations about the response its difficult to give any hint. 
* Which format is the response? 
* What kind of data is the response

**Comment by gregmartyn** [comment]
$response = $guzzle->request('GET', $url);

        $type = $response->getHeader('content-type');
        $parsed = Psr7\parse_header($type);

        $original_body = (string)$response->getBody();
        $utf8_body = mb_convert_encoding($original_body, 'UTF-8', $parsed[0]['charset'] ?: 'UTF-8');

is working fine for me for servers sending both Content-type: text/html; charset=ISO-8859-1 and charset=UTF-8, so I don't think there's a bug here. I don't think it's Guzzle's job to do the encoding for you. Might be a nice feature to have though.

**Comment by sagikazarmark** [comment]
Closing as the issue doesn't seem to be Guzzle related and a solution is provided to the problem.

**Comment by areindl** [comment]
Hi!

I had a similar problem with encodings when interacting with a 3rd-Party API. My special characters (utf-8) where not shown correctly after POSTing the form to the API.

I managed to add a header in Guzzle in Content-Type:
` "Content-Type" => "application/x-www-form-urlencoded; charset=UTF-8;",`

Does it make sense to add that to Guzzle Docs?

**Comment by abbasimehdi** [comment]
'headers' => ['content-type' => 'application/json', 'Accept' => 'applicatipon/json', 'charset' => 'UTF-8'],

**Comment by zmofsx** [comment]
> its very easy
> $client = new Client([
> 'headers' => ['content-type' => 'application/json', 'Accept' => 'applicatipon/json', 'charset' => 'utf-8']
> ]);

'charset' => 'utf-8' don't work

**Comment by codeeshop-oc** [comment]
this work for me is 
`header('Content-Type: application/json; charset=windows-1253');`
[https://stackoverflow.com/a/73218630/16576505](url)
