### ISSUE TITLE
How to read and set headers in the initial http proxy tunnel connect method with guzzle?

### ISSUE THREAD

**Issue by Nettw** [guzzle/guzzle#1666]
I need to read and set headers in the initial connect method to the proxy server. I can see the response header from the proxy server when I turn on debug mode:

> Rebuilt URL to: https://api.ipify.org/?format=json
> ...
> Connected to ...
> Establish HTTP proxy tunnel to api.ipify.org:443
> Proxy auth ...
> CONNECT api.ipify.org:443 HTTP/1.1
> Proxy-Authorization: ..
> Proxy-Connection: Keep-Alive
> User-Agent: GuzzleHttp/6.2.1 curl/7.35.0 PHP/5.6.28-1+deb.sury.org~trusty+1
> Host: api.ipify.org
> HTTP/1.1 200 Connection established
> X-Foo: bar

How can I read the "X-Foo: bar" response header from the connect phase?
How can I set a "X-Bar: foo" request header in the connect phase? 

Edit: This is a question, not an issue.

**Comment by sabershahhoseini** [comment]
A bit late lol but did you find any solutions? @ghost
