### ISSUE TITLE
Promises library causing error after updating to 1.3.0

### ISSUE THREAD

**Issue by ArthurGuy** [guzzle/guzzle#1668]
The guzzlehttp/promises library was recently updated from 1.2.0 to 1.3.0 as part of the aws php sdk, this updated version is causing the following error.

> The promise was rejected with reason: Invoking the wait callback did not resolve the promise

I have raised the issue against the aws library but it is tied to the guzzle upgrade from 1.2.0 to 1.3.0.
https://github.com/aws/aws-sdk-php/issues/1125

Any advice would be appreciated.

**Comment by sagikazarmark** [comment]
Closed in guzzle/promises#55
