### ISSUE TITLE
Uncaught RuntimeException: Error creating resource

### ISSUE THREAD

**Issue by Phobie53** [guzzle/guzzle#1669]
Hello, I'm using a library but when I do a call :
`Fatal error: Uncaught RuntimeException: Error creating resource: [message] fopen(https://euw.api.pvp.net/api/lol/euw/v1.4/summoner/by-name/DcD%20Phobie?api_key=XXXX-XXXX-XXXX-XXXX): [file] C:\Program Files (x86)\EasyPHP-Devserver-16.1\eds-www\OptimalChampionSelect\vendor\guzzlehttp\guzzle\src\Handler\StreamHandler.php [line] 282 in C:\Program Files (x86)\EasyPHP-Devserver-16.1\eds-www\OptimalChampionSelect\vendor\guzzlehttp\guzzle\src\Handler\StreamHandler.php:222 Stack trace: #0 C:\Program Files (x86)\EasyPHP-Devserver-16.1\eds-www\OptimalChampionSelect\vendor\guzzlehttp\guzzle\src\Handler\StreamHandler.php(285): GuzzleHttp\Handler\StreamHandler->createResource(Object(Closure)) #1 C:\Program Files (x86)\EasyPHP-Devserver-16.1\eds-www\OptimalChampionSelect\vendor\guzzlehttp\guzzle\src\Handler\StreamHandler.php(52): GuzzleHttp\Handler\StreamHandler->createStream(Object(GuzzleHttp\Psr7\Request), Array) #2 C:\Program Files (x86)\EasyPHP-Devserver-16.1\eds-www\OptimalChampionSelect\vendor\guzzlehttp\guzzle in C:\Program Files (x86)\EasyPHP-Devserver-16.1\eds-www\OptimalChampionSelect\vendor\guzzlehttp\guzzle\src\Exception\RequestException.php on line 51`

**Comment by vyshkant** [comment]
@Phobie53 Any updates on this? Have you managed to solve this problem?

**Comment by borgogelli** [comment]
Try with:

```
$url = ….
$options['timeout'] = 5;
$response = $client->request('GET', $url, $options);
```
