### ISSUE TITLE
use proxy and retry middleware at the same time

### ISSUE THREAD

**Issue by inkrement** [guzzle/guzzle#1670]
How can I set a proxy and a retry middleware at the same time? AFAIK it's not possible to set 'handler' and 'proxy' on a Client at the same time, but what's the alternative?

```
$stack = new HandlerStack();
$stack->setHandler(new CurlHandler());
$stack->push(Middleware::retry($decider, $delay));

$client = new Client(['proxy'=> 'http://username:password@ip']);

$requests = function() {
      yield new Request('GET', $url,[
        'User-Agent' => 'useragent',
        'Accept' => 'text/html,application/xhtml+xml'
      ]);
};

$pool = new Pool($client, $requests(), [ 
// ...
```

**Comment by lesha888** [comment]
+1

**Comment by alexeyshockov** [comment]
I don't see any problems using them together:

``` php
$client = new Client([
    'handler' => $stack,
    'proxy'=> 'http://username:password@ip',
]);
```

**Comment by lesha888** [comment]
@inkrement Have you solved the problem?

**Comment by gadnis** [comment]
Hi @alexeyshockov, I think what @inkrement was saying or asking about is: 
- How to rotate proxy using middleware::retry 

Am I right. @inkrement ? 

Well at least I am looking for that 😁  Don't know why, but I was thinking that retry middleware was reconstructing `Guzzle/Client` on each retry and in this way proxy was rotating together (I am using my `Proxy::random()` helper for that) 😁  stupid me.. 😁 

So similar question is:

How to use Retry Middleware to rotate proxy value?

**Comment by inkrement** [comment]
@gadnis good question, I haven't used the library for years now and I also forgot about the actual use case :D
