### ISSUE TITLE
Not being able to catch an exception

### ISSUE THREAD

**Issue by denjaland** [guzzle/guzzle#1671]
Hi guys,

It's probably been asked before, but my search on the issues did not return an answer.  My apologies if I'm not getting it right here.

I have a simple helper class here which aim is very simple: get profile information from Gravatar, and if it's missing on there, just return an empty array.

This is the code:

`public function getGravatarProfile() {

        $md5 = md5(strtolower($this->emailaddress));

        try {
            $client = new Client(['base_uri' => 'https://www.gravatar.com/', 'synchronous' => true, 'timeout' => 1]);
            $response = $client->get($md5 . ".php");
            $profile = unserialize( $response->getBody() );
            //echo "str: $str <br/>";
        } catch(Exception $e) {
            $profile = array();
        }

        return $profile;
    }`

Even though I'm catching all errors, and instructed Guzzle to do the call synchronously, I'm still getting exceptions thrown to the browser.  
I've already played by adding the http_errors to false which does fix the problem when Gravatar is returning a 404 error on an email address which isn't listed with them, but this won't fix the issue with some of the other exceptions that can be thrown by Guzzle.

What's the advised way of dealing with this?  
Again, my apologies if it has been answered before - I did try and google as well as search on github, but didn't find what I was looking for.

Have a great day!

**Comment by sagikazarmark** [comment]
What is the namespace you use this code in? The Exception you catch has no namespace or special name.

**Comment by Konafets** [comment]
I may help if you post those exceptions here.

**Comment by denjaland** [comment]
Hi - it's probably the namespacing indeed.  Will test this once I get back and confirm.
Pitfall I'm not used to falling into :-)

**Comment by denjaland** [comment]
Hi,

YOu were right (good eye!) I forgot to escape from the namespace to catch the exception.
Changing the above to ... } catch(\Exception $e) { ... does indeed fix my issue.

Thank you very much for your assistance.   I'm closing this issue.

**Comment by sagikazarmark** [comment]
Although this fixed your problem, you might want to be more restrictive about the exceptions caught: you could catch RequestException of Guzzle (or any other Guzzle exceptions) to make sure that other fatal issues break your code where it should and handle it wherever it belongs. (I don't know your code, so I don't know if it helps or not)

**Comment by denjaland** [comment]
I agree with you there.
In this use case though, we don't need to be that restrictive, on the contrary.
This is the signup form for new users.
The use case is very simple; after entering email address, go check with gravatar.com whether they have a profile, and pre-fill the first and last name of the user.
So - whatever goes wrong there - we just want to return no values for first and last name so the user can continue on the front and enter them manually.

thanks very much for your feedback though.  I definitely agree, and always try and be as restrictive as possible.
