### ISSUE TITLE
Good practice?

### ISSUE THREAD

**Issue by Kwadz** [guzzle/guzzle#1672]
Hello,

To write an API client, do you think we should use our own Request classes as an extension of GuzzleHttp\Psr7\Request?
For example:

```php
use GuzzleHttp\Psr7\Request;

class BookingRequest extends Request {

}
```

**Comment by sagikazarmark** [comment]
No, this is not really a good idea. Instead you should have your own domain layer which transforms your domain objects (`Booking`) into whatever, in this case a PSR-7 request.

There is aa very initial boilerplate for writting API clients: https://github.com/api-php/boilerplate
It is NOT final, likely to change, but should give you the basic idea.
