### ISSUE TITLE
Documentation inconsistent on Test Web Server

### ISSUE THREAD

**Issue by MarcoVigna17** [guzzle/guzzle#1674]
Hy guys, I was trying to set up a integration test with Guzzle 6, but I found an issue on setting up a response queue on my fake server. 

I followed the documentation at this point: http://docs.guzzlephp.org/en/latest/testing.html#test-web-server

But the class `GuzzleHttp\Tests\Server` is not part of the guzzle folder loaded with the composer (I'm using guzzle 6.2) and so I wasn't able to proceed.

Thanks, 

Marco

-- Edit

Checking a little bit further for this issue, I found that this is not a problem and other people just reported that (ie #1535, #1558) but it's not clear to me how to fix this avoiding to do `git pull` the repository directly (considering that I have a CI server that is running all my tests and I don't want to add this command on that server).

**Comment by sagikazarmark** [comment]
For the moment you can use --prefer-source option when running composer install. That will use the repository instead of the archive.

**Comment by sagikazarmark** [comment]
Closing in favor of #1535, it will be addressed.
