### ISSUE TITLE
"@" (at) sybmol in proxy password

### ISSUE THREAD

**Issue by mikeevstropov** [guzzle/guzzle#1677]
**Example**

Login: login
Password: pass@gmail.com

Proxy: http://login:pass@gmail.com@001.001.001.001:80
```
cURL error 5: Could not resolve proxy: gmail.com@001.001.001.001 (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)
```

**Comment by mtdowling** [comment]
Have you tried percent encoding the `@`?

**Comment by mikeevstropov** [comment]
@mtdowling Thank you! It works! 
&#64;

**Comment by mikeevstropov** [comment]
No, it's not working
`407 Proxy Authentication Required`

**Comment by mikeevstropov** [comment]
Sorry, i need use `%40` instead of `&#64;`

**Comment by Triden** [comment]
@mikeevstropov Excuse me, could you give an example. Where exactly is it necessary to replace the symbol?
Example: 'http://user:pa%40ss@iporhost:port' or 'http://user:pass%40iporhost:port'

**Comment by mikeevstropov** [comment]
@Triden 
This is pattern to define [proxy](http://docs.guzzlephp.org/en/stable/request-options.html?highlight=proxy#proxy) uri: `port://username:password@ip`
So, if we have a login or password which contain "@" we need to encoding it to "%40".

For login `my@login` and password `my@password` uri will be look like:
`http://my%40login:my%40login@0.0.0.0:00`
