### ISSUE TITLE
Send files and multidimensional array with Guzzle 6

### ISSUE THREAD

**Issue by DeGraciaMathieu** [guzzle/guzzle#1679]
hello,
I have this query in a project with Guzzle 5.3
```
$request = $this->guzzleHttp->createRequest('POST', 'my_host', []);

$postBody = $request->getBody();
$postBody->setField('subject', $this->subject);
$postBody->setField('from', $this->from);
$postBody->setField('to', $this->to);

foreach ($this->attachments as $attachment) {
    $postBody->addFile(new PostFile('attachements[]', $attachment['file'], $attachment['name']));
}
```
I need to rewrite this to work with Guzzle 6, but GetBody and PostFile have been removed from this release..
form_params doesn't accept resource and multipart does not work if you have multidimensional array

How can I do?

**Comment by sagikazarmark** [comment]
I don't know why multipart doesn't work for you: http://docs.guzzlephp.org/en/latest/request-options.html#multipart

That's exactly how this can be solved.

**Comment by DeGraciaMathieu** [comment]
Thank you for your reply !
But how can I send this array ?
```
'multipart' => [
    [
        'name'     => 'to',
        'contents' => [
            'address' => '...',
            'name' => '...'
        ],
    ]
]
```

**Comment by kmuenkel** [comment]
This is untested, but I think this conversion may do the trick:

                $options = ['multipart' => []];
                $fields = explode('&', http_build_query($body));
                foreach ($fields as $field) {
                    list($name, $field) = explode('=', $field);
                    $options['multipart'][] = [
                        'name' => urldecode($name),
                        'contents' => urldecode($field)
                    ];
                }

Explained:
    $body = ["key1"=>["next1"=>"val1","next2"=>"val2"]];
    //Flatten the array
    $query = http_build_query($body); //    key1%5Bnext1%5D=val1&key1%5Bnext2%5D=val2
    //Leaving it encoded defends against the possibility of ampersands and equal signs that happen to exist in the key-name or value mucking up the expected behavior of 'explode()'
    $fields = explode('&', $query); //    ["key1%5Bnext1%5D=val1", "key1%5Bnext2%5D=val2"]
    //Inside the loop, obtain the key/value pairs, still holding on to the flattened keys, and still waiting till the last possible moment to decode the strings
    list($name, $field) = explode('=', $fields[0]); //    ["key1%5Bnext1%5D" => "val1"]
    //When you're ready to apply the value to the multipart array, that's the time to decode.  The format reflected in "key1[next1]" is what we're ultimately going for here to support complex arrays.
    $name = urldecode($name); //    "key1[next1]"
    $value = urldecode($value); //    "val1"

**Comment by sagikazarmark** [comment]
This issue was automatically classified as stale because it lacks information or cannot be reproduced.

If you think the issue is still valid and/or misclassified, please comment on the issue thread
and provide additional information (if possible).

Also, since the time maintainers can spend on the project is limited, please provide
a possible solution if possible, especially if it involves a platform that we cannot
test ourselves (Windows, very old/specific PHP versions, etc).

Issues marked as stale with no further activity will be marked as `rotten`
at some point and will automatically be closed within 14 days.

We do this so that we can focus on high priority issues. Thank you for your understanding.

**Comment by tomswinkels** [comment]
Same issue here, look at: https://stackoverflow.com/questions/41587134/guzzle-post-multipart-request-with-nested-array/41602399#41602399

**Comment by tomswinkels** [comment]
Why this issue is closed?

**Comment by tiagof** [comment]
Having this issue too. Please re-open..... ?
