### ISSUE TITLE
Exception not being thrown when mock response status code is 4XX/5XX

### ISSUE THREAD

**Issue by BenExile** [guzzle/guzzle#1680]
Guzzle does not seem to throw exceptions when using the MockHandler. The documentation [here](http://docs.guzzlephp.org/en/latest/request-options.html#http-errors-option) states that exceptions are thrown when HTTP protocol errors are encountered. PHP 7.0.13, OS X Sierra.

```php
$client = new GuzzleClient([
    'handler' => new MockHandler([
        new Response(500, [], 'ERROR'),
    ]),
]);

$response = $client->post('/foo/bar'); // I would expect an exception to be thrown here
var_dump($response);

class GuzzleHttp\Psr7\Response#194 (6) {
...
}
```

**Comment by BenExile** [comment]
Resolved. If you are trying to test exceptions being thrown by Guzzle on 4XX and 5XX errors, use the following:

```php
$queue = [new Response(500)];
$client = new GuzzleClient([
    'handler' => MockHandler::createWithMiddleware($queue),
]);

$response = $client->post('/foo/bar');
```

**Comment by damianprzygodzki** [comment]
Experienced the same, and it not helped now. Also can't find it documented.

**Comment by drakakisgeo** [comment]
Had the same problem, wanted to test a 410 Exception ( Using Laravel )
```
     $this->swap(Client::class, new Client([
            'handler' => MockHandler::createWithMiddleware([new Response(410)]),
        ]));
```
