### ISSUE TITLE
[Support] CURLOPT_INTERFACE support

### ISSUE THREAD

**Issue by quazardous** [guzzle/guzzle#1682]
I need to specify the eth/ip interface (CURLOPT_INTERFACE option) to use in a request.

How can I achieve this ?

**Comment by jeremeamia** [comment]
This is answered in the docs. Here you go: http://docs.guzzlephp.org/en/latest/faq.html?highlight=curlopt#how-can-i-add-custom-curl-options

**Comment by quazardous** [comment]
thx and sry I didn't look carefully enough in the doc...
