### ISSUE TITLE
Add support for CURLOPT_CAPATH

### ISSUE THREAD

**Issue by notxarb** [guzzle/guzzle#1683]
`CaBundle::getSystemCaRootBundlePath()` returns either a path to the bundle or the to a directory containing the certificates. This is assuming that what is returned is a bundled certificate file. cURL doesn't like it when CURLOPT_CAINFO is a folder, and it errors. CURLOPT_CAPATH should be set instead.

**Comment by sagikazarmark** [comment]
Fixed in #1684

**Comment by sagikazarmark** [comment]
Released in [6.3.0](https://github.com/guzzle/guzzle/releases/tag/6.3.0)
