### ISSUE TITLE
See Raw Request

### ISSUE THREAD

**Issue by Decadence** [guzzle/guzzle#1688]
Hello.
Is there any way to see raw request which Guzzle sends (headers, method, URL, body, form data, etc.) for debug?

**Comment by gmponos** [comment]
I think it is the the [debug option](http://docs.guzzlephp.org/en/latest/request-options.html#debug)

**Comment by Decadence** [comment]
@gmponos Thanks. It's almost what I wanted but I can't see request body which I set with `json` option (only headers). Am I doing something wrong?
By the way `"debug" => true` gives `curl_setopt_array(): cannot represent a stream of type Output as a STDIO FILE` (https://github.com/guzzle/guzzle/issues/1413), fopen works fine.

Here is output (domain and IP are changed):

* Found bundle for host domain.test: 0x193c4fb6ac0 [can pipeline]
* Re-using existing connection! (#0) with host domain.test
* Connected to domain.test (8.8.8.8) port 443 (#0)
> POST /init-bg/init-bg-process HTTP/1.1
Host: domain.test
User-Agent: GuzzleHttp/6.2.1 curl/7.47.1 PHP/5.6.19
Content-Type: application/json
Cookie: JSESSIONID=7DB88C145B4815A444624
Content-Length: 746

* upload completely sent off: 746 out of 746 bytes
< HTTP/1.1 500 
< Server: nginx/1.6.3
< Date: Thu, 15 Dec 2016 16:29:06 GMT
< Content-Type: application/json;charset=UTF-8
< Transfer-Encoding: chunked
< Connection: keep-alive
< X-Application-Context: application:48810
< 
* Connection #0 to host domain.test left intact

**Comment by Konafets** [comment]
Maybe the History middleware may help you. 
http://docs.guzzlephp.org/en/latest/testing.html#history-middleware

**Comment by Decadence** [comment]
@Konafets thanks, but there isn't full info about request too. Body is still missing.
Perfectly I want something like this in Google Chrome: 
![screenshot from 2016-12-15 21-50-56](https://cloud.githubusercontent.com/assets/1434668/21237573/9e7f69ee-c310-11e6-952e-bbf777507fb0.png)

**Comment by Konafets** [comment]
To get the body use this code as an example.

```php
use GuzzleHttp\Client;
use GuzzleHttp\HandlerStack;
use GuzzleHttp\Middleware;

$container = [];
$history = Middleware::history($container);

$stack = HandlerStack::create();
// Add the history middleware to the handler stack.
$stack->push($history);

$client = new Client(['handler' => $stack]);

$client->request('POST', 'http://httpbin.org/post',[
    'body' => 'Hello World'
]);

// Count the number of transactions
echo count($container);
//> 2

// Iterate over the requests and responses
foreach ($container as $transaction) {
    echo (string) $transaction['request']->getBody();
}
```

**Comment by Decadence** [comment]
Ok, I see. Thanks.

**Comment by sagikazarmark** [comment]
@Decadence you should proceed with caution though: getting the body content from a readonly stream might make you unable to get the body from the response in the end.

**Comment by Decadence** [comment]
@sagikazarmark Thanks for advice.
By the way why does `$request->getBody()->getContents()` return empty string, but `$response->getBody()->getContents()` returns normal text? strval($request->getBody()) returns desired value. Inconsistent behaviour.

**Comment by sagikazarmark** [comment]
Because `getContents` only reads the "remainder" on the stream, with other words: everything that's left between the current position and EOF.

Cast the body object to string to get the content, that's the official way to go.

**Comment by Decadence** [comment]
I get it, thanks.

**Comment by willy0275** [comment]
Hey folks, very late message in an old issue but I'm now doing some PUT requests and the History middleware doesn't record the request at all (the array is empty after the request). It works for all other methods like GET, POST and even DELETE, but not for PUT. We're on Guzzle version 6.3.3.
