### ISSUE TITLE
.git included when installing 6.0 through composer

### ISSUE THREAD

**Issue by samansmink** [guzzle/guzzle#1692]
After installing guzzle through composer in our laravel project, the .git folder is included. This leads to problems when trying to add the files to our own repository. I think this is not desired behaviour? If it is, do you know how to fix it? simply removing .git folder leads to "git pathspec is in submodule" errors.

Kind regards,

Sam Ansmink

**Comment by sagikazarmark** [comment]
First of all: you should never add the vendor directory to your repository.

You can install dependencies with the `--prefer-dist` flag, this will make composer install from archive instead of the git repo, thus the .git directory won't be there.

**Comment by samansmink** [comment]
Thanks for your quick reply
