### ISSUE TITLE
Finish handler should not be hard-coded

### ISSUE THREAD

**Issue by mpyw** [guzzle/guzzle#1693]
We can override the converter from PSR-7 Request to cURL.

- [src/Handler/CurlMultiHandler.php#L38-L39](https://github.com/guzzle/guzzle/blob/dfadff37efcfd42230eef1350009898b7b9af40a/src/Handler/CurlMultiHandler.php#L38-L39)

On the other hand, however, the converter from cURL to PSR-7 Response is hard-coded as `CurlFactory::finish` here.

- [src/Handler/CurlMultiHandler.php#L176-L179](https://github.com/guzzle/guzzle/blob/dfadff37efcfd42230eef1350009898b7b9af40a/src/Handler/CurlMultiHandler.php#L176-L179)

Would it be customizable?

**Comment by sagikazarmark** [comment]
If you take a closer look, you can see that the actual factory instance is passed to the finish method: 

https://github.com/guzzle/guzzle/blob/dfadff37efcfd42230eef1350009898b7b9af40a/src/Handler/CurlMultiHandler.php#L179

And it is called to release the easy handler or handle error:

https://github.com/guzzle/guzzle/blob/dfadff37efcfd42230eef1350009898b7b9af40a/src/Handler/CurlFactory.php#L102-L107

I admit that this seems to be a bit confusing that some wrapper logic is placed in the default implementation, but the desired functionality is there.

**Comment by mpyw** [comment]
Thanks I got it :D
