### ISSUE TITLE
how to set up ssl off in guzzle

### ISSUE THREAD

**Issue by ifourkuldeep** [guzzle/guzzle#1695]
I am using guzzlehttp  6.2.
in which i want to set following option 
```
curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, FALSE);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, TRUE);
```
How can i set those two?

Thanks

**Comment by sagikazarmark** [comment]
http://docs.guzzlephp.org/en/latest/request-options.html#verify
http://docs.guzzlephp.org/en/latest/quickstart.html#using-responses

Please check the documentation before asking, and use Stackoverflow for support requests.
