### ISSUE TITLE
Support for PSR-15 middlewares

### ISSUE THREAD

**Issue by veewee** [guzzle/guzzle#1702]
Hello,

I was wondering if there are plans to support [PSR-15 middlewares](https://github.com/php-fig/fig-standards/blob/master/proposed/http-middleware/middleware.md).
Currently the status of the document is still in draft. Looking at the voting results, I don't think it is going to change very drastically: https://groups.google.com/forum/#!topic/php-fig/v9AijALWJhI

I am willing to help out, but don't know how you guys see this.

Thanks!

**Comment by sagikazarmark** [comment]
We definitely want to support every PSR we can, but we have the following to consider:

- currently there is a subscriber/handler system which we would have to replace with PSR-15. We have to see if we can do it in a BC way in 6 or we need to break BC and put it in 7.
- regarding BC breaks: there are two other upcoming PSRs, namely message factory and http client ones which MIGHT require BC breaks as well.

If possible, we should avoid or limit the number of BC breaks. I would like to start looking at these options beginning next year, and find the optimal solution. Best case scenario would be to release a version 7 with all the new PSRs.

**Comment by mtdowling** [comment]
I'm not yet sold on supporting the middleware PSR. Guzzle uses an async promise based middleware system that I think is a better fit for a client than what's proposed.

**Comment by veewee** [comment]
@mtdowling, You are right!
I did a read-up on the topic and it looks like PSR-15 is heading for a server only middleware PSR: https://groups.google.com/forum/#!msg/php-fig/vBk0BRgDe2s/1do0ZIiuBwAJ

@sagikazarmark: I could not find a client PSR. The http message factory does not apply to guzzle, since it will always use its own request / response (I guess?)

For now, I guess it's best to wait some more. Too bad, since I'll have to create my own layer above middleware to make it cross-client compatible ...

**Comment by sagikazarmark** [comment]
I guess we can provide an experimental bridge between Guzzle and PSR-15 middlewares, but I am not sure if it's necessary. We use callables, so you can simply wrap your PSR-15 middleware stack in a callable compatible with our "delegate" interface.

As said we need to check our options and decide based on that.

**Comment by veewee** [comment]
Thanks for pointing me to that PSR @Nyholm!
@sagikazarmark: That was also what I was thinking. The problem with that wrapper is that it is not async.

**Comment by dimabory** [comment]
I just want to point out that PSR-15 is already ACCEPTED.
Any options to go further with a bridge between Guzzle and PSR?

**Comment by jeremeamia** [comment]
@dimabory [PSR-15](https://www.php-fig.org/psr/psr-15/) was created for _server_ middleware, not client middleware. If you look at the `MiddlewareInterface`, the contract is designed for the `ServerRequestInterface`, so I don't think PSR-15 would apply to Guzzle client.
