### ISSUE TITLE
cookies must be an instance of GuzzleHttp\Cookie\CookieJarInterface

### ISSUE THREAD

**Issue by Enelar** [guzzle/guzzle#1703]
```
    $client = new \GuzzleHttp\Client();

    // Set up a cookie - name, value AND domain.
    $cookie = new \Guzzle\Plugin\Cookie\Cookie();
    $cookie->setName('name');
    $cookie->setValue('value');
    $cookie->setDomain('example.com');

    // Set up a cookie jar and add the cookie to it.
    $jar = new \Guzzle\Plugin\Cookie\CookieJar\ArrayCookieJar();
    $jar->add($cookie);

    try {
        $res = $client->request('GET', "http://example.com",
            [
                'cookies' => $jar,
            ]);
    } catch (Exception $e) {
        var_dump($e);
        die();
    }

    echo $res->getStatusCode();
```

**Comment by sagikazarmark** [comment]
What is the issue exactly?

**Comment by Enelar** [comment]
Sorry. Well, expected results: request sends, no exception occures.
Actual result: `cookies must be an instance of GuzzleHttp\Cookie\CookieJarInterface`.

But they are instance of `ArrayCookieJar`. What did i wrong then?
Maybe we need clarify documentation? I used this:
http://docs.guzzlephp.org/en/latest/quickstart.html#cookies

**Comment by sagikazarmark** [comment]
Which version of Guzzle do you use? Where did you get `$jar = new \Guzzle\Plugin\Cookie\CookieJar\ArrayCookieJar();` from (as it is not bundled with Guzzle)?

**Comment by Enelar** [comment]
@sagikazarmark i using 7.0, and i found it here http://stackoverflow.com/a/25328483/1472668

I spend more than 40 minutes on hustle googling. Cause i wasn't able to make it work after reading the sources.

**Comment by Konafets** [comment]
@Enelar There is no version 7.0 of Guzzle. The link to SO is from 2014 and refers to an version of Guzzle < 6.x. You will get a lot of hints how to make the Cookies and the CookieJar working when you look in the tests/Cookie/ folder.

**Comment by sagikazarmark** [comment]
Exactly what I wanted to say: I guess your PHP VERSION is 7. The linked SO answer (or a comment bellow) mentions Guzzle 3.

You might find something actual and useful here: https://github.com/guzzle/guzzle/tree/master/src/Cookie

**Comment by Enelar** [comment]
@Konafets @sagikazarmark thanks! My guzzle version is `6.2.2` sorry for that.
I managed to fix this by using `CookieJar`, instead of `ArrayCookieJar`.

Thank you a lot for explanation!
