### ISSUE TITLE
Where is createRequest method in Client?

### ISSUE THREAD

**Issue by mikeevstropov** [guzzle/guzzle#1707]
Where is `createRequest` method in Client?
http://docs.guzzlephp.org/en/latest/psr7.html?highlight=createRequest#port
Why `createRequest` send `request` if we dont need it?
https://github.com/guzzle/guzzle/blob/master/src/Client.php#L87

Thank you

**Comment by sagikazarmark** [comment]
There is no createRequest as it's the responsibility of a RequestFactory (which we don't have at the moment).

The doc is wrong, it should be:

`$request = new Request('GET', 'http://httpbin.org:8080');`
