### ISSUE TITLE
 Warning: preg_match(): Unknown modifier '/' in SetCookie.php on line 352

### ISSUE THREAD

**Issue by turkelt0n** [guzzle/guzzle#1720]
Hi! I've got some Error using a simple Request 

```
$values["region"]` = "12345_DE";
$cookieJar = CookieJar::fromArray(
    $values,
    "https://www.allyouneedfresh.de"
);

$client = new \GuzzleHttp\Client(['cookies' => $cookieJar]);
$response = $client->get(
    "https://www.allyouneedfresh.de"
);
```
This results in

```
Warning: preg_match(): Unknown modifier '/'
() at /home/alex/foodle/vendor/guzzlehttp/guzzle/src/Cookie/SetCookie.php:352
 GuzzleHttp\Cookie\SetCookie->matchesDomain() at /home/foodle/vendor/guzzlehttp/guzzle/src/Cookie/CookieJar.php:234
...
```
The Error is thrown for every URL i tried.  Any Suggestions? Did I miss something?

Thank you!

**Comment by sagikazarmark** [comment]
The cookie jar domain must be without the schema part, so:

```
$cookieJar = CookieJar::fromArray(
    $values,
    "www.allyouneedfresh.de"
);
```

**Comment by turkelt0n** [comment]
Thank you for that!

**Comment by curtisdf** [comment]
I know this is from a year ago, but the discussion above does not address the underlying bug in the code.  There are servers on the Interwebs that are sending invalid `domain` strings, which wreaks havoc with Guzzle when trying to parse those  cookies.

I have submitted a pull request which fixes the bug in `SetCookie::matchesDomain()`. See https://github.com/guzzle/guzzle/pull/1999.
