### ISSUE TITLE
cURL error 35: Unknown SSL protocol error in connection

### ISSUE THREAD

**Issue by wassimhattab** [guzzle/guzzle#1728]
Hello i'm trying to send post to external https url using guzzle and i'm getting the following error
ConnectException in CurlFactory.php line 186:
cURL error 35: Unknown SSL protocol error in connection to www.netcommercepay.com:443 (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)

and this is my request:

```
$client = new Client();
$response = $client->post('https://www.netcommercepay.com/iPAY/', [
	'form_params' => [
			'payment_mode' => $payment_mode,
			'txtAmount' => $txtAmount,
			'txtCurrency' => $txtCurrency,
			'txtIndex' => $txtIndex,
			'txtMerchNum' => $txtMerchNum,
			'txthttp' => $txthttp,
			'signature' => $signature,
		]				
]);
```

i tried to add CURLOPT_SSLVERSION and CURLOPT_PROTOCOLS and still returning error

any solution?

**Comment by sagikazarmark** [comment]
Can you try sending a request from cli as well? I had this issue in the past, but there was something with the cURL build in my case.

**Comment by its-tas** [comment]
I think this is a problem with netcommercepay.com and not Guzzle; Their DNS doesn't seem to be resolving at all, I've tried ping'ing, scanning, tracert, DNS/Reverse DNS look ups etc. and the server doesn't give any response.

http://downforeveryoneorjustme.com/netcommercepay.com also showing that it's down.

Try contacting their support and see what's going on?

**Comment by sagikazarmark** [comment]
Probably?

**Comment by wassimhattab** [comment]
yes the reason was from netcommerce i tried another url and it worked fine i think netcommerce does not support curl or something
