### ISSUE TITLE
'URL is invalid' with some URL

### ISSUE THREAD

**Issue by atefBB** [guzzle/guzzle#1730]
Hi, I'm using guzzle 5.3 ('guzzlehttp/guzzle' v5.3.x-dev, 'guzzlehttp/ringphp' v1.1.0, 'guzzlehttp/streams' v 3.0.0) with laravel 4.2 and  I got this error while trying to get HTML stream of some website  (getbootstrap.com in this case and with other website too):
`Error creating resource: [message] URL is invalid: getbootstrap.com
[file] /.../vendor/guzzlehttp/ringphp/src/Client/StreamHandler.php`.
How can I solve this error? is that a 'bug' or just a 'normal behavior' with such URL?
Thanks !

**Comment by Nyholm** [comment]
What URL are you using?

**Comment by atefBB** [comment]
this URL : `getbootstrap.com` ! (without http(s) prefix)

**Comment by sagikazarmark** [comment]
Can you try with http(s)://? Not sure if the stream handler can guess the protocol for you.

**Comment by atefBB** [comment]
Yes, this is the prob: the stream handler can't guess the protocol!
I try it with 'http' prefix and it's work.

**Comment by sagikazarmark** [comment]
So is your issue resolved then? :smile:

**Comment by atefBB** [comment]
You can say ! ^___^ 
Thanks !
