### ISSUE TITLE
Response body overwrites request body

### ISSUE THREAD

**Issue by mieszkomalawski** [guzzle/guzzle#1731]
$message->getBody()->getContents() read from temp stream, when response comes in it overrides request body in stream. Example:

$httpClient = new GuzzleHttp\Client();

$request = new \GuzzleHttp\Psr7\Request('post', new \GuzzleHttp\Psr7\Uri('https://httpbin.org/post'), [], json_encode(['foo' => 'bar']));
var_dump($request->getBody()->getContents());
$httpClient->send($request);

var_dump($request->getBody()->getContents());

Will result in:

string(13) "{"foo":"bar"}"
string(0) ""

Solution:
After sending request but before response guzzle should create immutable SentRequest object

**Comment by sagikazarmark** [comment]
This has already been answered countless times: getContents reads the remainder of the stream from the current position. If you want to read the whole stream, cast the stream object to string, it will read the whole stream into the memory.

**Comment by emmetog** [comment]
This one had me confused for a while too, just from misunderstanding `->getContents()` (I had assumed that it got the full body string always).

I know renaming is hard but would it be worth considering renaming `->getContents()` to something like `->readToEndOfStream()` or `->getRemainingContents()` or something along those lines to avoid similar confusion in future releases?

**Comment by sagikazarmark** [comment]
We can't: it's coming from the PSR-7 spec. I can't recommend anything, but to read the spec to avoid the confusion.

**Comment by emmetog** [comment]
Ah I see now. Ok, thanks @sagikazarmark

**Comment by emmetog** [comment]
I've submitted https://github.com/guzzle/psr7/pull/291 as a potential way to make things clearer.
