### ISSUE TITLE
Explain getContents in FAQ

### ISSUE THREAD

**Issue by sagikazarmark** [guzzle/guzzle#1732]

**Comment by sagikazarmark** [comment]
To avoid tickets like #1731

**Comment by emmetog** [comment]
This is not an issue with Guzzle, at least in my case it's actually the definition of `getContents()` from the PSR-7 spec that is confusing (by the current definition of the PSR-7 spec it should return the remainder of the stream, but still be called the (misleading?) name `getContents()`).

More discussion [here](https://github.com/guzzle/psr7/pull/291).
