### ISSUE TITLE
Segfault Issue when trying to write to php://temp when it is not writable

### ISSUE THREAD

**Issue by Luciam91** [guzzle/guzzle#1735]
When trying to use a system where the location of `php://temp` is either read-only or not writable, the default Guzzle setup with php-fpm causes a Segmentation Fault, and in turn a 502 error from nginx.

Adding the directory with writable permissions solves this issue, but it would be better to throw a usable exception
`guzzlehttp/guzzle/src/Handler/CurlFactory.php : 370`

**Comment by sagikazarmark** [comment]
I think we already had this issue in the past. The problem is that writting to `php://temp` is handled internally by PHP and I am not sure we can prevent that segfault. An alternative would be adding a permission check prior to writing, but this rather seems to be an edge case, not sure if it worth the effort.

**Comment by Luciam91** [comment]
Forgive me if I'm wrong about how it's handled internally, but does `sys_get_temp_dir` not return the same as what using `php://temp` does?

If so a simple writable check could solve this (happy to submit the PR for this if that is the case)

**Comment by sagikazarmark** [comment]
I meant the stream writing (and the created temporary file). I think there is/was a bug report about this on PHP's bug tracker: when opening the stream and there is no write access, opening the stream should fail, apparently it causes a segfault.

> a simple writable check could solve this

I am not quite sure that it is a good idea to do filesystem checks in Guzzle. Also, as far as I know this temp directory thing doesn't work quite well with virtualhost specific settings, there is also an open ticket involving GCE, etc

As I said this is an edge case, we had about 3 reported cases. Let me think about it.
