### ISSUE TITLE
curl_setopt_array not working on PHP Version 7.0.8-0ubuntu0.16.04.3

### ISSUE THREAD

**Issue by DmitryBezik** [guzzle/guzzle#1736]
"name": "guzzlehttp/guzzle",
"version": "6.2.2",

file CurlFactory.php line 57
curl_setopt_array($easy->handle, $conf);

not working, i need to change it on something like this

		foreach($conf as $const => $val) {
			curl_setopt($easy->handle, $const, $val); 
		}

**Comment by mattrummler** [comment]
I'm seeing the same on "PHP Version 7.0.22-0ubuntu0.16.04.1".
When I attempt to use curl_setopt_array() what I get back is no settings set at all.
