### ISSUE TITLE
[PROXY] Add ProxyConnectException

### ISSUE THREAD

**Issue by KTP95** [guzzle/guzzle#1737]
As the title, this for handling better proxy-Connect Exception

LIke this:

     Uncaught exception 'GuzzleHttp\Exception\ConnectException' with message 
     'cURL error 7: User was rejected by the SOCKS5

**Comment by sagikazarmark** [comment]
Not sure if you propose adding a new exception or making the exception message better.

**Comment by KTP95** [comment]
I propose new Exception,

**Comment by mtdowling** [comment]
Guzzle utilizes "handlers" to abstract the underlying HTTP connection. Right now, there's curl and the stream handler built-in to the library. I wonder if we can reliably know across handlers that the error is a proxy error? A proxy error *is* a ConnectException, and you would still need to know the exact error from cURL even with a new subclassed exception.

**Comment by KTP95** [comment]
My proposal was a "practical", not "technical"

In the fact can by hard implement it cause cURL return always error 7 - proxy and connection Error.

```
$proxy = 'socks5://sockd:sockd@123.123.123.123:2016';

$client = new \GuzzleHttp\Client();
$res = $client->request('GET', 'http://321.321.321.321/some-url.html',
	[ 
		'proxy' => $proxy
	]
);
echo $res->getStatusCode()."\n";
```
So, If Proxy NOT work
Proxy Error - code (7) - ConnectException 

So, If Proxy WORK + Url Request NOT work
Final Request\Connection Error - code (7) - ConnectException 

I know exactly that curl hit always same error-code, and only change error message.
But sometimes Dev. need detect the differences.

So, for response you.

> I wonder if we can reliably know across handlers that the error is a proxy error? 

No, Only ways is parse The error messages By curl_error() php function/ , and sincerally i don't think it is 'perfect' or that this is a good idea  also Because... I not can find a complete list of curl-error-messages.

can You find a list of all possible messages for Error7 ?

Maybe you have other suggest for detect what is dead on connection [proxy or final resourse]
