### ISSUE TITLE
Getting ClientException with 200-Status-Code

### ISSUE THREAD

**Issue by turkelt0n** [guzzle/guzzle#1738]
Hi,
while executing the following code 

$this->client = new GuzzleHttp\Client();
```
$this->client->request(
                'GET',
                'http://onlinelibrary.wiley.com/doi/10.2903/j.efsa.2017.4684/full',
                [
                    'headers' =>  [
                        'User-Agent' => 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0'
  ]
            );
```

there are occasions on which it throws a ClientException with a 200-Status-Code. The Exception carries a response. I cant tell if its a server issue or an issue with this framework.

Help would be appreciated :)

**Comment by mtdowling** [comment]
Can you post a stack trace?

**Comment by turkelt0n** [comment]
I cant provide a Stack-Trace right now as it wasnt logged properly. I'm closing this Issue for now. Logging is fixed now so i should be abled to provide the trace next time, if this occurs again.
