### ISSUE TITLE
Error Guzzlehttp

### ISSUE THREAD

**Issue by whmcsred** [guzzle/guzzle#1739]
Catchable fatal error: Argument 2 passed to GuzzleHttp\Exception\RequestException::__construct() must implement interface GuzzleHttp\Message\RequestInterface, integer given, called in /home/whmcsred/public_html/devs/vendor/whmcs/whmcs-foundation/lib/Terminus.php on line 0 and defined in /home/whmcsred/public_html/devs/modules/addons/valid_account/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php on line 23

Would anyone know the cause of this error?

**Comment by sagikazarmark** [comment]
Which Guzzle version do you use? It looks like 5.x. Can you do some debugging? What value is passed there? What is your client configuration? How do you use the client?

**Comment by sagikazarmark** [comment]
Did you have any chance to investigate this?

**Comment by gmponos** [comment]
Closing as no feedback has been provided. Feel free to submit more info and we can investigate this further.
