### ISSUE TITLE
Automatically refreshing access token 

### ISSUE THREAD

**Issue by smaira** [guzzle/guzzle#1740]
I have an external oauth api that I get an access token from and use it in the X-Auth-Token header for other endpoints. When the access token expires I get a 400 error and I need to get a new one using the refresh_token - standard oauth api. 

I want to check for the exception and refresh the access token implicitly for all client requests i make using Guzzle. I thought the best way to do this would be to override the Response object maybe? 

I'm following this issue but I'm not sure I have the code setup correctly. 
https://github.com/guzzle/guzzle/issues/694

Is there a better way of doing this? Can I leverage the middleware somehow ? http://docs.guzzlephp.org/en/latest/handlers-and-middleware.html

Here's a pseudocode of what I'm thinking. Not sure if this looks correct.

```
use GuzzleHttp\Client;

$client = new Client([
    'base_uri' => 'adadasdg',
    'timeout'  => 2,
	// NOTE: Overriding the createResponse method as per instructions 
    // here https://github.com/guzzle/guzzle/issues/694
	'message_factory'=> createResponse()
]);

function createResponse(params,params){
         //Call the parent method first so you don't lose any of the base          //functionality.
         try {
			  responseObject = parent::createResponse();
			}
		 catch (ClientException $e)
		   {
            //Make sure the exact error code is returned
			 if ($e->(error code attribute))
			 { 
			    //Make the refresh token call now
				//Store new access token
			 } 
           }
     }

```

**Comment by sagikazarmark** [comment]
Note that you are not overriding anything here:

> 'message_factory'=> createResponse()

You should pass a callable here, which could be `'createResponse'`.

However this only applies if you use Guzzle 4. Do you?

You can use handlers too (which IMO is better), but for that you need to use Guzzle 6

**Comment by umar** [comment]
@sagikazarmark we are using Guzzle 6 and trying the retryMiddleware. What I am blocked on right now is how to update request object so that a particular header value in the request object is updated before the next retry callback happens. The header attribute is supposed to contain a valid token which we are trying to update if the response fails on first try with status >= 400.

```
private function createRetryHandler()
{
  return function (
    $retries,
    RequestInterface $request,
    ResponseInterface $response = null,
    RequestException $exception = null
    ) {
    if ($retries >= MAX_RETRIES) {
      return false;
    }
    if(in_array($response->getStatusCode(), array(400, 401)) {
      $request = $this->stack->push(
        Middleware::mapRequest(
          function (RequestInterface $request) {
             // How to update the request object that gets used in next try?
             return $request->withHeader('X-Auth-Token', 'abcd'); // This doesn't update the request object.  
          }
        )
      );
      return true;
    }

    if (!($this->isServerError($response) || $this->isConnectError($exception))) {
      return false;
    }

    return true;
  };
}

$this->stack = HandlerStack::create(new CurlHandler());
$this->stack->push(\GuzzleHttp\Middleware::retry($this->createRetryHandler()));
$config = [
    'handler' => $this->stack,
];
$this->client = new Client($config);

```
I understand this is retry decider function and the above stated code for updating request might not be right approach. Please advise.

**Comment by judgej** [comment]
@umar I'm in the same situation as you. Did you get a solution to this? I have retry middleware that is able to recognise the token has expired (the Response tells us this), and so it able to fetch a new token. Then several things need to happen:

* The OAuth middleware that injects the OAuth headers (i.e. signs the request) is updated with the new token.
* The `Request` needs to be pushed though that `OAuth1` middleware again to regenerate new `OAuth1` headers (the request needs resigning). Exposing the signing method of the middleware allows that easily enough.
* Finally that *new, updated* `Request` needs to be used in the next retry. Stuck here also. The Guzzle retry just has the old `Request` to try sending again, while I actually want to use an updated `Request`.

The new token needs to be passed back to the application for saving, which again, is easily dealt with. Here I have two middlewares: the `OAuth1` signing handler, and the `RefreshToken` retry handler.

**Comment by jbidzik** [comment]
@judgej @umar hi guys, i'm want to retry guzzle request on 401 error with modified authorization header. Did you find a solution to do that?

**Comment by judgej** [comment]
@jbidzik IIRC I used a decorator to wrap the main Guzzle functions (send, post etc) and that was able to check the result of every request. If it got an authentication error, then the decorator was able to renew oauth tokens, try again etc.

The decorator used a service to get the Guzzle client, all configured and ready to go, and cached it. If any of the underlying data that feeds into the authentication of the request changed, then it discarded the cache, and the next time it requested a Guzzle client (on the retry) it was given a fresh one, rebuilt from whatever details have changed (usually an OAuth token, that needs renewing every half an hour).

To me it is key that the application does not need to get involved in handling HTTP errors in requests. It';s got its own business logic go handle, and API protocols are not in its domain. The decorator class is the middle layer that handles all that.

**Comment by christianseel** [comment]
This is what worked for me:
```
$stack = new HandlerStack();
$stack->setHandler(\GuzzleHttp\choose_handler());
$stack->push(\GuzzleHttp\Middleware::retry(
    function (
        $retries,
        \GuzzleHttp\Psr7\Request $request,
        \GuzzleHttp\Psr7\Response $response = null,
        RequestException $exception = null
    ) use ($logger) {
        $maxRetries = 1;

        if ($retries >= $maxRetries) {
            return false;
        }

        if ($response && $response->getStatusCode() === 401) {
            // received 401, so we need to refresh the token
            // this should call your custom function that requests a new token and stores it somewhere (cache)
            $this->refreshClientAccessToken();
            return true;
        }

        return false;
    }
));

// mapRequest ALWAYS adds a Authentication header (if Request contains a "X-Token: Add" header
// getClientAccessToken() should get the current token from the storage/cache and add it
$stack->push(Middleware::mapRequest(function (\GuzzleHttp\Psr7\Request $request) {
    if ($request->hasHeader('X-Token', 'Add')) {
        return $request->withHeader('Authorization', 'Bearer ' . $this->getClientAccessToken());
    }
    return $request;
}));

$this->client = new Client([
    'handler' => $stack,
]);

// sample GET
$response = $this->client->get('my/path/to/something', [
    'headers' => [
        'X-Token' => 'Add',
    ],
]);
```

**Comment by thanhquang1988** [comment]
RequestException $exception = null
This line should be \GuzzleHttp\Exception\RequestException $exception = null

**Comment by jenschude** [comment]
Just an addition to the last example this is my code for reauthentication. I didn't used the retry middleware cause it's not capable of modifying the request itself:

```php
     * Middleware that reauthenticates on invalid token error
     *
     * @param OAuth2Handler $oauthHandler
     * @param int $maxRetries
     * @return callable Returns a function that accepts the next handler.
     */
    public static function reauthenticate(OAuth2Handler $oauthHandler, $maxRetries = 1)
    {
        return function (callable $handler) use ($oauthHandler, $maxRetries) {
            return function (RequestInterface $request, array $options) use ($handler, $oauthHandler, $maxRetries) {
                return $handler($request, $options)->then(
                    function (ResponseInterface $response) use (
                        $request,
                        $handler,
                        $oauthHandler,
                        $options,
                        $maxRetries
                    ) {
                        if ($response->getStatusCode() == 401) {
                            if (!isset($options['reauth'])) {
                                $options['reauth'] = 0;
                            }
                            $exception = ApiException::create($request, $response);
                            if ($options['reauth'] < $maxRetries && $exception instanceof InvalidTokenException) {
                                $options['reauth']++;
                                $token = $oauthHandler->refreshToken();
                                $request = $request->withHeader(
                                    'Authorization',
                                    'Bearer ' . $token->getToken()
                                );
                                return $handler($request, $options);
                            }
                        }
                        return $response;
                    }
                );
            };
        };
    }
```

**Comment by judgej** [comment]
@jenschude for other APIs I have found the decorator pattern around the HTTP client (especially a PSR-18 client, because its interface is so simple) is a great place to put the renewal logic. That's the point where the expiry response is known, the *full* original request is known so can be tried again, and the renewed authentication token can be saved in the current client *and* saved to a persistent storage.

So I understand, here you have a stack of middleware (kind of) handlers that each wrap the request and pass back the response. On an expired token response you try renewing the token, then bounce the same request back down the chain again? The retry count allows you to give up after a number of bounces.

You could inject a closure in this middleware here to handle the persisting of the new token to storage.

**Comment by jenschude** [comment]
The retry is more likely to be used for 503s.

This reauth middleware is used to serve the single purpose of trying to fetch a new token from the auth endpoint and retry the original request with the new token. My OAuthHandler injected to the middleware is also responsible for caching the requested token, so subsequent requests doesn't have to fetch them again:

```php
$handler->push(
    Middleware::mapRequest($oauthHandler),
    'oauth_2_0'
);
$handler->push(
    self::reauthenticate($oauthHandler),
    'reauthenticate'
);
```

For better understanding the class signatures:

```php
class OAuth2Handler
{
    /**
     * OAuth2Handler constructor.
     * @param TokenProvider $provider
     * @param CacheItemPoolInterface|CacheInterface $cache
     * @param string $cacheKey
     */
    public function __construct(
        TokenProvider $provider,
        $cache = null,
        $cacheKey = null
    ) {
    }

    /**
     * @param RequestInterface $request
     * @param array $options
     * @return RequestInterface
     */
    public function __invoke(RequestInterface $request, array $options = [])
    {
        return $request->withHeader('Authorization', $this->getAuthorizationHeader());
    }

    /**
     * @return string
     */
    public function getAuthorizationHeader()
    {
        return 'Bearer ' . $this->getBearerToken();
    }

    public function refreshToken()
    {
        $token = $this->provider->getToken();
        // ensure token to be invalidated in cache before TTL
        $ttl = $token->getTtl() - 300;

        $this->cache($token, $ttl);

        return $token;
    }

    /**
     * @return string
     */
    private function getBearerToken()
    {
    }

    private function getCacheToken()
    {
    }

    private function cache(Token $token, $ttl)
    {
    }
}

interface TokenProvider
{
    /**
     * @return Token
     */
    public function getToken();
}
```

**Comment by jenschude** [comment]
Also wrapping the GuzzleClient inside a PSR-18 client means that you loose the whole capabilities of asynchronous request processing.

**Comment by judgej** [comment]
Yes, the asynchronous requests is something I'm battling with. Thanks for the detailed explanation.

**Comment by 55953** [comment]
How bad can be to use a while loop that fires a refresh to get a new token if it has expired right before making a request call 
` while($this->accessToken->hasExpired()){
            $options = json_decode($this->client->fetchAccessTokenWithReflesh('x','y','z'),true);
        }       `

**Comment by jenschude** [comment]
Cause there are more failure conditions for invalid tokens, e.g. like invalidated

**Comment by andreweifill** [comment]
I was not totally sure on how it works. Is there someone that can assist me
in navigating this your site so I able to effective with my potential
client, please?
*Let us take your business to the next level*
256 258 8696 <2562588696>



*FOCUSED TARGETED PRECISE *

[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
10/10/20,
05:40:22 PM

**Comment by GrahamCampbell** [comment]
@andreweifill Yes, my rates start at $50/hour. Email me if you are interested in purchasing paid support. This issue on Guzzle is now closed, because there is not a bug in Guzzle, and refreshing of oauth tokens falls outside the scope of what Guzzle should be able to do (or know about).
