### ISSUE TITLE
Post always returns a curl timeout error, even though the call succeeded

### ISSUE THREAD

**Issue by thereverendtom** [guzzle/guzzle#1743]
I am trying to introduce Guzzle 6.2 into my project, but I'm running into odd issue whereby I always get the following error:

cURL error 28: Operation timed out after 10001 milliseconds with 0 out of -1 bytes received (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)

However, the request does, in fact, complete, as I can see that the API I am calling successfully executed. I have tried extending the timeout option, but I will always get the curl error regardless of the amount of time I let the process wait (all that changes is the timeout displayed in the error message). I have stripped my code down to something extremely basic, so I'm unsure why I keep running into this issue. My code is listed below. $url is the full URL to my endpoint, $headers is an associative array of header key/value pairs, and $data is an associative array of key/value pairs to pass in as JSON. I'm running PHP 7.0 on CentOS 7. I'm running this as a command line process which attempts to hit an endpoint running in Apache on the same host.

$client = new Client();
try {
    $result = $client->post($url, [
        'headers' => $headers,
        'json' => $data,
        'connect_timeout' => 5,
        'timeout' => 10
    ]);
    var_dump($result->getBody()->getContents());
} catch (RequestException $e) {
    var_dump($e->getMessage());
}

**Comment by heitorri** [comment]
'exceptions' => false
'timeout' => 5.0

Try increasing the timeout gradually or set 0 to be infinite
'timeout' => 0

link:
http://docs.guzzlephp.org/en/latest/request-options.html#timeout

**Comment by sagikazarmark** [comment]
Fixed in #1718

**Comment by sagikazarmark** [comment]
Released in [6.3.0](https://github.com/guzzle/guzzle/releases/tag/6.3.0)

**Comment by pheaborey** [comment]
> 'exceptions' => false
> 'timeout' => 5.0
> 
> Try increasing the timeout gradually or set 0 to be infinite
> 'timeout' => 0
> 
> link:
> http://docs.guzzlephp.org/en/latest/request-options.html#timeout

Good job
Thanks it's worked for me.
