### ISSUE TITLE
https request with cert option throws an exception

### ISSUE THREAD

**Issue by banveerad** [guzzle/guzzle#1752]
I am trying to get a info from a server with self signed certificate and I am providing the client.pem while making the get guzzle call.  But the curl works fine.
`curl -k --cert /etc/octavia/certs/client.pem https://192.168.0.7:9443/0.5/info  | python -m json.tool`

not workign code.
```
<?php
require 'vendor/autoload.php';
use GuzzleHttp\Client;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Exception;

        $url = "https://192.168.0.7:9443/0.5/info";
        $client = new Client();

        // set content
        $content = '';
        $contentType = 'text/plain';
        $contentLength = strlen($content);

        // set request options
        $requestOptions = [
            'headers' => [
                "Content-Type" => $contentType,
                "Content-Length" => $contentLength
            ],
            'body' => $content
        ];
        $request = $client->get($url, array(), array(
            'cert' => '/etc/octavia/certs/client.pem'
        ));


        $response = $client->send($request);
        return [
                'statusCode' => $response->getStatusCode(),
                'body' => $response->getBody()
        ];
```

I am getting the following exception 
`PHP Fatal error:  Uncaught exception 'RuntimeException' with message 'Error creating resource: [message] fopen(): SSL operation failed with code 1. OpenSSL Error messages:
error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed
[file] /home/vagrant/vendor/guzzlehttp/guzzle/src/Handler/StreamHandler.php
[line] 312
[message] fopen(): Failed to enable crypto
[file] /home/vagrant/vendor/guzzlehttp/guzzle/src/Handler/StreamHandler.php
[line] 312
[message] fopen(https://192.168.0.7:9443/0.5/info): failed to open stream: operation failed
[file] /home/vagrant/vendor/guzzlehttp/guzzle/src/Handler/StreamHandler.php
[line] 312' in /home/vagrant/vendor/guzzlehttp/guzzle/src/Handler/StreamHandler.php:252
Stack trace:
#0 /home/vagrant/vendor/guzzlehttp/guzzle/src/Handler/StreamHandler.php(316): GuzzleHttp\Handler\StreamHandler->createResource(Object(Closure))
#1 /home/vagrant/vendor/guzzlehttp/guzzle/src/Handler/StreamHandler.php(52): GuzzleHttp\Handler\StreamHandler->createStream(Object(GuzzleHttp\Psr7\Request), A in /home/vagrant/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php on line 52`

**Comment by sagikazarmark** [comment]
You know that with `-k` in the `curl` command you turn off verification, so essentially it's not the same as your Guzzle code.

I think it won't work without the CA properly placed.

Anyway, this is not a Guzzle issue from what I can see.

**Comment by banveerad** [comment]
Sorry, thats true. I ll close the issue.
