### ISSUE TITLE
Authorization Bearer doesn't work well

### ISSUE THREAD

**Issue by tommoholmes** [guzzle/guzzle#1754]
I create use guzzle 
here my code for guzzle header
```
$client = new \GuzzleHttp\Client(['base_uri' => 'http://localhost:1323/']);
$newresponse = $client->request(
		    'GET',
		    'tags?tag='.$tags.'page=21', 
		    ['debug' => true], 
		    ['headers' => 
		        [
		            'Authorization' => "Bearer {$jwt}"
		        ]
		    ]
		)->getBody()->getContents();
$datas = json_decode($newresponse,true);
		echo "<pre>";
		print_r($datas);
```
when I run my code I getting error like this
`{"message":"Missing or invalid jwt in the request header"}` from my API
this error display because my Bearer not sending
when I checking use curl I can connect my API
```$ curl http://localhost:1323/tags?tag=kecantikanpage=21 -H "Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0YWciOiJrZWNhbnRpa2FuIn0.rOR8DfuPPnwZnlEGcdzSjc2Va6EsA9brppifmunW2-A"
{"message":"Not Found"
```

**Comment by sagikazarmark** [comment]
That's because you send the headers in the fourth parameter. You should send them in the third array parameter:

https://github.com/guzzle/guzzle/blob/master/src/Client.php#L128

**Comment by tommoholmes** [comment]
```
$client = new \GuzzleHttp\Client(['base_uri' => 'http://localhost:1323/']);
$newresponse = $client->request(
		    'GET',
		    'tags?tag='.$tags.'page=21',
		    ['headers' => 
		        [
		            'Authorization' => "Bearer {$jwt}"
		        ]
		    ]
		)->getBody()->getContents();
```
hmmm if I change my code it still error

**Comment by sagikazarmark** [comment]
Can you please debug what actually gets sent to the server? It's a bit hard to debug your code without actual access to it.

**Comment by tommoholmes** [comment]
```
* Trying ::1... * TCP_NODELAY set * Connected to localhost (::1) port 1323 (#0) > GET /tags?tag=kecantikan&page=21 HTTP/1.1 Host: localhost:1323 User-Agent: GuzzleHttp/6.2.1 curl/7.53.0 PHP/5.6.29 < HTTP/1.1 400 Bad Request < Content-Security-Policy: default-src 'self' < Content-Type: application/json; charset=UTF-8 < Vary: Accept-Encoding < Date: Sun, 26 Feb 2017 03:49:37 GMT < Content-Length: 58 < * Connection #0 to host localhost left intact
```
this result like this

**Comment by muhammetakkus** [comment]
@tommoholmes I have a similar problem. I can not send the token via header. Did you solve it?

**Comment by sagikazarmark** [comment]
@tommoholmes I cannot reproduce your issue with the following code:

```php
$client = new GuzzleHttp\Client([
	'base_uri' => 'http://requestbin.fullcontact.com'
]);

$response = $client->request(
	'GET',
	'/t3qjx8t3?tag=mytags&page=21',
	['headers' =>
		[
			'Authorization' => "Bearer asd123"
		]
	]
)->getBody()->getContents();
```

As you can see in the first request here (the second was me accidentally from the browser) the header is there: https://requestbin.fullcontact.com/t3qjx8t3?inspect

Also, in your last response there is a 400 error, so you probably have something else there.

**Comment by sagikazarmark** [comment]
@muhammetakkus  please note that there was a regression introduced in 6.3.2 which has just been fixed in 6.3.3. See details here: #2061

**Comment by muhammetakkus** [comment]
okey i handled like this
`$guzzle = new GuzzleHttp\Client(['base_uri' => 'localhost:80']);
$response = $guzzle->get('users', [
        'headers' => [ 'Authorization' => 'my_token' ]
 ])->getBody();

$data = json_decode($response);`

**Comment by dany0792** [comment]
Hi, 
On ubuntu 18.04 cannot set bearer authorization header:
My code:

use GuzzleHttp\Client;
$client = new Client();
$response = $client->get( $url, 
[
      'headers' => [ 'Authorization' => "Bearer {$my_token}" ]
]);
echo '<pre>';
print_r(json_decode($response->getBody(), true));
echo '</pre>';

And answer is:

Array {
   [headers] => Array {
         [host] => Array{...}
         [user-agent] => Array {
               [0] => GuzzleHttp/6.2.0 curl/7.58.0 PHP/7.1.22-1+ubuntu18.04.1+deb.sury.org+1
         }
   }
}

So, "Authorization" is not setted. Can anyone help me with that problem?
Thank you!

**Comment by sagikazarmark** [comment]
What do you use for returning the headers? RequestBin?

**Comment by dany0792** [comment]
The server returns all the headers from the request. Here in this function, the authorization header is no onger present. Also, this currently works on Ubuntu 14.04, with curl 7.35.0.

`return $this->handleView($this->view([
    'headers' => $request->headers->all()
], 200));`

**Comment by iponk15** [comment]
uh

**Comment by flowl** [comment]
> okey i handled like this
> 
> ```
> $guzzle = new GuzzleHttp\Client(['base_uri' => 'localhost:80']);
> $response = $guzzle->get('users', [
>         'headers' => [ 'Authorization' => 'my_token' ]
>  ])->getBody();
> 
> $data = json_decode($response);
> ```

You are missing the protocol in `base_uri`: `http://localhost:80`
