### ISSUE TITLE
Works with Request object -> Upload multiple files. I can't do it... 

### ISSUE THREAD

**Issue by david-vde** [guzzle/guzzle#1755]
Hello

I use Guzzle 6

Due to a design conception I'm working by building Request objects before sending it.

So here is how I proceed to build my request. (Maybe you have a better method to suggest) ?

```
$request = new Request(
                $method,
                $fullUrl,
                $headers,
                http_build_query($formData, '', '&')
            );
```

The $client->send() method will send my request using the built Request object.

All works fine except that now I have to deal with multiple files upload. ANd I have absolutely no idea about how to do it with my method...

Ok the Guzzle doc says:

http://docs.guzzlephp.org/en/latest/quickstart.html#sending-form-files

But I can't find any documentation about the correct method to do the same thing when working directly with Request object.

The old version of guzzle worked like this. And for a reason I don't understand, the request is now directly sent (in recent version of guzzle) if we use normal flow explained in your doc.

If you can help me about that I will really appreciate.

Please dont tell my I have to use the method on the link above. To do that I have to completely rethink the basis of my application and I have no time for that.

Thank you very much

**Comment by sagikazarmark** [comment]
Sorry for the late response. Try using [MultipartStream](https://github.com/guzzle/psr7/blob/master/src/MultipartStream.php) as the body of your request. You need to pass the exact same array to it as described in the link above, but you can pass the resulting stream directly to your request object.

Hope that helps.
