### ISSUE TITLE
Laravel 5.3 Guzzle and asynchronous request

### ISSUE THREAD

**Issue by mediaceh** [guzzle/guzzle#1756]
I try to handle asynchronous request with Guzzle and write the result of the request in my model:

      $promise = $client->getAsync($url);

      $promise->then(
            function (ResponseInterface $res) {

                $body = $res->getBody();    

                $MyModel = new  \App\Model\MyModel([
                        'data' => $body,
                        ]);

                $MyModel->save();

            },
            function (RequestException $e) {
                Log::error($e->getMessage());
            }
        );

But it doesn't work.

I also try to create a model outside of promise and pass it there:

     $MyModel = new  \App\Model\MyModel();

     $promise = $client->getAsync($url);

    $promise->then(
            function (ResponseInterface $res) use($MyModel) {

                $body = $res->getBody();    

                $MyModel->data = $body;

                $MyModel->save();

            },
            function (RequestException $e) {
                Log::error($e->getMessage());
            }
        );

I don't have any error anywhere. But it does not work.

Is it possible or not?

**Comment by sagikazarmark** [comment]
I guess your callbacks are not called at all. Can you try `$promise->wait();`?

**Comment by sokoslee** [comment]
I try to handle asynchronous request with Guzzle and write the result of the request in Laravel Queues(Laravel version: 5.4)  ,and have the same problem, 
and $promise->wait(); works for me. 
Thanks @sagikazarmark .
But, WHY?

**Comment by sagikazarmark** [comment]
Same question popped up somewhere else, here is the answer:

https://github.com/guzzle/promises/issues/68#issuecomment-306054620

**Comment by jeromejaglale** [comment]
The Guzzle doc is not very clear, here's a working example

```
$client = new \GuzzleHttp\Client();
 
// start request
$promise = $client->getAsync('http://loripsum.net/api')->then(
    function ($response) {
        return $response->getBody();
    }, function ($exception) {
        return $exception->getMessage();
    }
);
 
// do other things
echo '<b>This will not wait for the previous request to finish to be displayed!</b>';
 
// wait for request to finish and display its response
$response = $promise->wait();
echo $response;
```

**Comment by maala** [comment]
delete ResponseInterface and RequestException types from the functions arguments and take a try, I think
it'll works fine!
