### ISSUE TITLE
guzzle\Psr7 1.4.1 deprecated method usage

### ISSUE THREAD

**Issue by fustundag** [guzzle/guzzle#1759]
When **base_uri** config set, Guzzlehttp Client uses "Psr7\Uri::resolve" method. But this method is deprecated and triggers error at Psr7 1.4.1 version.

This fails request at Guzzlehttp Client

```
ErrorException: GuzzleHttp\Psr7\Uri::resolve is deprecated since version 1.4. Use GuzzleHttp\Psr7\UriResolver::resolve instead. in vendor/guzzlehttp/psr7/src/Uri.php:292 
Stack trace:
#0 [internal function]: 
#1 vendor/guzzlehttp/psr7/src/Uri.php(292): trigger_error('GuzzleHttp\\Psr7...', 16384) 
#2 vendor/guzzlehttp/guzzle/src/Client.php(145): GuzzleHttp\Psr7\Uri::resolve(Object(GuzzleHttp\Psr7\Uri), Object(GuzzleHttp\Psr7\Uri)) 
#3 vendor/guzzlehttp/guzzle/src/Client.php(115): GuzzleHttp\Client->buildUri(Object(GuzzleHttp\Psr7\Uri), Array) 
#4 vendor/guzzlehttp/guzzle/src/Client.php(129): GuzzleHttp\Client->requestAsync('GET', 'uri', Array)
```

**Comment by visiover** [comment]
There is already a pull request regarding this issue.
https://github.com/guzzle/guzzle/pull/1753

Let's just hope that they merge it soon.

**Comment by fustundag** [comment]
For workaround, we added line **"guzzlehttp/psr7":"1.4.0"** to composer.json temporarily

**Comment by sagikazarmark** [comment]
I don't see though why a deprecation error triggers an error exception.

**Comment by Tobion** [comment]
And I even silenced the deprecation trigger ^^

**Comment by sagikazarmark** [comment]
6.2.3 has been released with the aformentioned patch from @Tobion
