### ISSUE TITLE
HTTPS Proxy Problem "--proxy-insecure"

### ISSUE THREAD

**Issue by beshoo1** [guzzle/guzzle#1761]
Dear all , i use to use https proxy via CURL command line : 

`/usr/local/bin/curl -V`

```
curl 7.52.1 (x86_64-pc-linux-gnu) libcurl/7.52.1 OpenSSL/1.0.1e zlib/1.2.3 c-ares/1.11.0
Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp
Features: AsynchDNS IPv6 Largefile NTLM NTLM_WB SSL libz UnixSockets HTTPS-proxy
```

`/usr/local/bin/curl --proxy https://38ab6bab3ee10a17df7272fd0f5c3a469ff2b312:D32CC998147689418ED01C3706C5676B625B6B4BCF86D4BBF66B9335A51276B1@162.253.130.147:443 --proxy-insecure https://ipecho.net/plain`

This proxy 162.253.130.147 is related to opera 

`*  subject: OU=Domain Control Validated; OU=PositiveSSL Wildcard; CN=*.opera-proxy.net`

opra use **de.opera-proxy.net**  but Opera always chooses a random route for its output so your IP changes every request. and that what i am trying to address by using the CURL command line with  "--proxy-insecure" and static IP Address 162.253.130.147:443

Now How can i set this scenario with guzzle? 
as far as i know --proxy-insecure doesn't exist in PHP's cURL. It only accepts valid proxies.
i have to provide "de.opera-proxy.net". but Opera always chooses a random route for its output .

You can see the list of verify-related options in PHP's cURL here: http://php.net/curl_setopt.

So , is there a CURL command line Handler use shell_exec('curl ........'); 
if not how can i solve this problem

Regards

**Comment by sagikazarmark** [comment]
Sorry, but a cURL command line handler is not implemented at the moment, and probably won't be in the future either.

I don't think this is possible at the moment.

**Comment by beshoo1** [comment]
Dear @sagikazarmark, thank you in advance for your kindly reply, well i like to take the chance and create this handler, but i did review curl handler, it is a bit complicated, i mean it is not straightforward. 

It there a more simple handler, maybe howTo, to create curlCommandline handler, then after teast i will share it. 

Regards.

**Comment by SteveJobzniak** [comment]
@beshoo1 It's not going to be that simple. The "curl" binary differs on various platforms and versions installed on the user's system. For example, curl on Mac OS X does not even have "--proxy-insecure". Literally doesn't exist.

**Comment by beshoo1** [comment]
@SteveJobzniak you made my day , THANK YOU

**Comment by sagikazarmark** [comment]
Closing as there is not much we can do on guzzle's side.
