### ISSUE TITLE
What is the private function add_timeout of StreamHandler for?

### ISSUE THREAD

**Issue by fiboknacky** [guzzle/guzzle#1765]
Hello,

I have a question about the [add_timeout](https://github.com/guzzle/guzzle/blob/master/src/Handler/StreamHandler.php#L380) function.
It's a private one but I can't find the location where this function is called in the class.

Does anybody please tell me what's for?
It looks like we might be able to leverage this to set http timeout.

Thanks in advance.
Knack

**Comment by sagikazarmark** [comment]
[add_](https://github.com/guzzle/guzzle/blob/a1c4a74bf31d4e41d783fafb635c806cc19c2e9b/src/Handler/StreamHandler.php#L287) methods are used for adding the request options to the stream context.

See http://docs.guzzlephp.org/en/latest/request-options.html#timeout
