### ISSUE TITLE
Guzzle 6.2 deperecated warning

### ISSUE THREAD

**Issue by jantajov** [guzzle/guzzle#1766]
The following code:

```
$client = new Client(['base_uri' => 'http://api.geonames.org/countryCodeXML']);
$options = ['query' => ['lat' => 50, 'lng' => 14, 'username' => 'demo']];
echo $client->get('countryCodeXML', $options)->getBody()->getContents();
```
Gives me:

```
GuzzleHttp\Psr7\Uri::resolve is deprecated since version 1.4. Use GuzzleHttp\Psr7\UriResolver::resolve instead.
```

Am I doing something wrong?

**Comment by vanloc0301** [comment]
I think you should update to latest version.

or:

For workaround, we added line "guzzlehttp/psr7":"1.4.0" to composer.json temporarily

**Comment by jantajov** [comment]
Updating to version 6.2.3 resolves the problem.
I'm closing this issue.
/close

**Comment by vanloc0301** [comment]
👍 if that library has issues. It can be a bug so that you can create issues. Or find in issues before creating new.
