### ISSUE TITLE
Retry middleware per request

### ISSUE THREAD

**Issue by gmponos** [guzzle/guzzle#1768]
The retry middleware as it is now can't accept retry option per request.

For instance I can't do this:

``` php
        $handler->push(Middleware::retry(
            function ($retries, $request, $response, $exception) {
                if ($response) {
                    if (($response->getStatusCode() >= 500) && ($retries < 1)) {
                        return true;
                    }
                }
                return false;
            },
            function ($delay) {
                return $delay * 1000;
            }
        ));
 
       // Initialize the client with the above handler here

        // I need this request to make a retry
        $client->get('www.test.com', [
            'retry' => [
                'attempts' => 3,
                'delay' => 1000,
            ],
        ]);

        // I need this not to make a retry.
        $client->get('www.test.com');
```

Would you accept a MR about this?

**Comment by Konafets** [comment]
I would push a custom retry middleware to the stack. `GetTestDotComRetry` with a retry decider as follow:

```php
if ($request->getMethod() === 'GET' && $request->getUri()->getHost() === 'www.test.com') {

}

```

This can stay there besides the global retry middelware.

**Comment by gmponos** [comment]
IMO this has a lot of disadvantages in cases where you use the same client for lot's of APIs

``` php
class MyClass
{
    /**
     * @var ClientInterface
     */
    private $client;

    public function __construct(Client $client)
    {
        $this->client = $client;
    }
    
    // First example
    public function myApi1(){
        /** @var HandlerStack $handler */
        $handler = $this->client->getConfig('handler');
        $handler->push(Middleware::retry(
            function ($retries, $request, $response, $exception) {
                if ($request->getMethod() === 'GET' && $request->getUri()->getHost() === 'www.test.com') {
                    //put code here.
                }
            },
            function ($delay) {
                return $delay * 1000;
            }
        ));

        return $this->client->get('www.test.com');
    }

    // Second example
    public function myApi2(){
        /** @var HandlerStack $handler */
        $handler = clone $this->client->getConfig('handler');
        $handler->push(Middleware::retry(
            function ($retries, $request, $response, $exception) {
                if ($request->getMethod() === 'GET' && $request->getUri()->getHost() === 'www.test1.com') {
                    //put code here.
                }
            },
            function ($delay) {
                return $delay * 1000;
            }
        ));

        return $this->client->get('www.test.com', [
            'handler' => $handler,
        ]);
    }
}
```

1. As you can see in the first example I push a middleware into the stack and the stack will be filled with middlewares that are not actually doing nothing and I think it is an overkill.
2. In the second example please notice the clone of the handler. This makes it easy to make a handler only for one time use. But as the example shows above if I have a lot of functions inside my class in most of the cases it will just lead to duplicating the code.

**Comment by Konafets** [comment]
You can extract the retry decider and the retry delay to own methods:

```php
protected function retryDeciderForDomain($domain)
{
    return function (
        $retries,
        Request $request,
        Response $response = null,
        \Exception $exception = null
    ) use ($domain){
        if ($request->getMethod() === 'GET' && $request->getUri()
                    ->getHost() === $domain
        ) {
            // your code       
        }
    };
}

protected function retryDelay() 
{
    return function ($numberOfRetries) {
        return 1000 * $numberOfRetries;
    };
}

$handler->push(Middleware::retry(
    $this->retryDeciderForDomain('www.test1.com'), 
    $this->retryDelay()
);

```

**Comment by gmponos** [comment]
If I combine my example and yours I would still need to get the handler from the client and clone it. Then pass it again as options.

Anyway both ways can work, I just think it's simple and clear.

Why do you prefer one way over the other?

**Comment by sagikazarmark** [comment]
> IMO this has a lot of disadvantages in cases where you use the same client for lot's of APIs

I think this is generally a bad idea. By using the same client you will keep facing these issues, and the solution for them always increases complexity. On the other hand, configuring multiple clients increases the configuration overhead, but leaves the code itself simple.

Not to mention that in some cases you simply cannot use the same client (eg. when you need to add authentication details).

Furthermore, if we ever choose to use a PSR for HTTP clients, request scope configuration will disappear, at least we won't be able to support them within the abstraction boundaries. We can still expose a Guzzle-specific API for that, but it won't be an encouraged way of using Guzzle.

**Comment by sagikazarmark** [comment]
I've been thinking about this. I don't think adding support for middleware specific configuration in the request context is a good idea, sorry.

**Comment by mfn** [comment]
Sorry to jump in here, not sure if this is the proper forum to ask for this.

Twitter currently provides endpoints using different authentication schemes. Most are using OAuth1 and they work together perfectly with https://github.com/guzzle/oauth-subscriber .

However there are some rare OAuth2 endpoints (as in: the just want a bearer token [1]). You cannot have the OAuth1 Middleware enabled _and_ provide your own `Authorization` for selected requests.

What is the "guzzle-way" with such a requirement? Do I need to create two different kind of client instances, one with the OAuth1-middleware and one without and use them appropriately?

I found this issue because I was thinking about adding the OAuth1-middleware per request could be a solution, but alas it doesn't seem to be possible (or I couldn't find it).

[1] https://developer.twitter.com/en/docs/accounts-and-users/subscribe-account-activity/api-reference/aaa-standard-dm#get-account-activity-webhooks-webhook-id-subscriptions-list
