### ISSUE TITLE
Best approach to hide some parameters in logs

### ISSUE THREAD

**Issue by whyte624** [guzzle/guzzle#1770]
What is the best approach to hide some data in logs?
For example, I have request, where user entered his or her password, and response where new password arrives back.
I'm using Log middleware and MessageFormatter::DEBUG format to log request data. 
But I would prefer to replace data in request and response.
By default it logs `password=123456` for request and `new_password=654321` from response.
Currently I've extended MessageFormatter::format method and replaced such entrances with a regular expressions.
Anyway I wonder if there is other approach for this issue?

**Comment by sagikazarmark** [comment]
I would say MessageFormatter is the best approach that you can currently do.
