### ISSUE TITLE
Guzzle Pool - Wait for requests?

### ISSUE THREAD

**Issue by ghost** [guzzle/guzzle#1774]
Is it possible to make the Guzzle pool wait for requests? 

Right now I can add requests to the pool dynamically, but as soon as the pool is empty, guzzle will stop (obviously).

This is a problem when I'm doing 10 or so pages concurrently, because my requests array will be empty until the resulting HTML pages have been processed and new links added. 

This is my generator:

    $generator = function () {
      while ($request = array_shift($this->requests)) {
        if (isset($request['page'])) {
          $key = 'page_' . $request['page'];
        } else {
          $key = 'listing_' . $request['listing'];
        }

        yield $key => new Request('GET', $request['url']);                                          
      }
      echo "Exiting...\n";
      flush();
    };

And my pool: 

    $pool = new Pool($this->client, $generator(), [
      'concurrency' => function() {
        return max(1, min(count($this->requests), 10));
      },
      'fulfilled' => function ($response, $index) {
          // new requests may be added to the $this->requests array here
      }
      //...
    ]);

    $promise = $pool->promise();
    $promise->wait();

I tried to change the generator as follows, but now only 2 or 3 requests about of 10 seem to be fulfilled..

    $generator = function () {
      echo 'In generator<br>';
      $since_last = 0;

      do {
        if (!empty($this->requests)) {
          $since_last = time();
          $request = array_shift($this->requests);
          if (isset($request['page'])) {
            $key = 'page_' . $request['page'];
          } else {
            $key = 'listing_' . $request['listing'];
          }

         yield $key => new Request('GET', $request['url']);                                          
        } else {
          if (time() - $since_last > 10) {
            echo 'More than 10 seconds, quitting!<br>';
            exit();
          }
        }
      } while (true);
    };

What am I doing wrong?

**Comment by matheusfaustino** [comment]
I'm having the same issue.

**Comment by ivan-pomortsev** [comment]
Just try:
```
$generator = function () {
  echo 'In generator<br>';
  $since_last = 0;
  if (!empty($this->requests)) {
    $since_last = time();
    $request = array_shift($this->requests);
    if (isset($request['page'])) {
      $key = 'page_' . $request['page'];
    } else {
      $key = 'listing_' . $request['listing'];
    }

    yield $key => new Request('GET', $request['url']);
  } else {
    if (time() - $since_last > 10) {
      echo 'More than 10 seconds, quitting!<br>';
      exit();
    }
    
    return function() {
      return true;
    };
  }
};
```
Guzzle will create simple FullfilledPromise with returned value "true" (actually no matter which value will be there) but that ticks will allow your main request to be fullfilled too.
