### ISSUE TITLE
Pool skips requests

### ISSUE THREAD

**Issue by ghost** [guzzle/guzzle#1775]
I fetch 1 URL, then add 10 more URLs to fetch. When I set concurrency to 1, all 10 are fetched. If I set concurrency to 2, 1 is not fetched. If I set concurrency to 3, 2 are not fetched. Not sure if this is random or not. 

When set to 3, index 8 and 9 are not fetched, but 10 is. So I don't understand what is wrong?

This is my generator:
```

$generator = function () {
  while ($request = array_shift($this->requests)) {
    if (isset($request['page'])) {
      $key = 'page_' . $request['page'];
    } else {
      $key = 'listing_' . $request['listing'];
    }

    yield $key => new Request('GET', $request['url']);                                          
  }
  echo "Exiting...\n";
  flush();
};
And my pool:

$pool = new Pool($this->client, $generator(), [
  'concurrency' => function() {
    return max(1, min(count($this->requests), 3));
  },
  'fulfilled' => function ($response, $index) {
      // new requests may be added to the $this->requests array here
  }
  //...
]);

$promise = $pool->promise();
$promise->wait();

```

**Comment by matheusfaustino** [comment]
@gayathriw did you find out why it is doing that or how to fix it? I'm having the same problem :/ 
It's very strange...
