### ISSUE TITLE
Option query silently overrides url query

### ISSUE THREAD

**Issue by asvae** [guzzle/guzzle#1776]
## Given
I have a function like this:
```php
protected function getPage($url, $query = []){
    // `$this->client` is `\GuzzleHttp\Client` instance.
    return $this->client->get($url, [
        'query' => $query,
    ])->getBody()->getContents();
}
```
I call it: `$this->getPage('image?event=2');`

## Expectation
I expect the request url to be `http://my-site.com/image?event=2`.

## Reality
Request url is `http://my-site.com/image`.

## Details
What, happens is, when you provide 'query' in options, it will silently override query from url. If `query` is not provided, query from url will be used.
As guzzle/php doesn't provide means to easily see/debug resulting url, this little thing might result in nice hourly debug session.

## Possible solutions
1) Merge query from url and `query`.
2) Throw exception when both are provided.
3) Trigger notice when both are provided.

---------------
Thanks for your attention.

**Comment by mtdowling** [comment]
This behavior is by design. Instead of using a default query request option, you need a middleware that will add to the query string rather than replace it, and the middleware needs context as to how the query string is serialized.

**Comment by asvae** [comment]
Thanks.
Understood. Can't say it doesn't make sense.

I'll split method signature on my side:
```php
// from
getPage($url, $query = []);
// to 
getPageWithQuery($url, $query);
getPage($url, $query);
```
This should quell any kind of confusion.
