### ISSUE TITLE
Multiple client object collision?

### ISSUE THREAD

**Issue by arderyp** [guzzle/guzzle#1777]
I am using a custom GuzzleClientProvider class to build and return new Client() objects.  Something like this:

```
$provider = new GuzzleClientProvider();
$one = $provider
    ->setBaseUrl('https://www.example.com')
    ->setAuthHeaders(['id' = '123', 'key' => 'abc'])
    ->getClient() #this returns a new Client() object using options above
$two = $provider
    ->setBaseUrl('https://www.somethignelse.com')
    ->setAuthHeaders(['id' = '456', 'key' => 'def'])
    ->getClient()
```

Despite the fact that I am creating a fresh object for `$two`, when I dump the headers for that `$two` instance, I see `['id' = '123', 'key' => 'abc']`.  Is this a bug, or might my logic be overlooking some internal workings of Guzzle that make my approach impossible?

**Comment by arderyp** [comment]
This issue may be premature.  Will do more testing and provide more concrete details if I can replicate this issue.

**Comment by sagikazarmark** [comment]
I guess it's your own code, it has nothing to do with Guzzle.

**Comment by arderyp** [comment]
You guessed right, my bad.  I should have done more thorough testing before opening the issue.  Thanks for the quick response, and the awesome package.
