### ISSUE TITLE
setResponseBody not releasing file lock on windows

### ISSUE THREAD

**Issue by SublymeRick** [guzzle/guzzle#1782]
I'm working with a Craft2 plugin which uses Guzzle v3 which i know is EOL, however I was hoping someone here might know what the issue is, if anything for my own curiosity. 

The original plugin developer set it up so that when linking a social account it downloads the profile picture with guzzle, then uses php's rename function to move the file.  His code, when running on my windows (php7.1) box fails at the rename call because apparently the file is "open by another process". 

After a bunch of pulling my hair out I changed the guzzle code to:
```
		$extension = "jpg";
		$photoData = file_get_contents($photoUrl);
		file_put_contents($tempPath.$filename, $photoData);
```

And now it works flawlessly.

This is the original guzzle code I replaced:

```
		$tempFilepath = $tempPath.$filename;
		$client = new \Guzzle\Http\Client();
		$response = $client->get($photoUrl)
			->setResponseBody($tempPath.$filename)
			->send();
		$extension = substr($response->getContentType(), strpos($response->getContentType(), "/") + 1);
```

Does anyone have any idea why guzzle is not writing and closing the file before the rename is called directly after this block?

**Comment by sagikazarmark** [comment]
Have you tried closing it manually?

After a quick look: `$request->getResponseBody()->close()` should do it where request is the object returned by `Client::get`. Haven't checked, but I guess that stream object is available in the response as well.

**Comment by SublymeRick** [comment]
@sagikazarmark thanks! Your insight helped a bunch. I had to add `$response->getBody()->close();` after `$extension` was set before the file rename command and it worked perfectly!
