### ISSUE TITLE
Empty arrays removed during request using form_params

### ISSUE THREAD

**Issue by fridde** [guzzle/guzzle#1783]
I am sending a multidimensional array as a POST form parameter to my own url endpoint. My request looks like this:

```
$client->post($url, ["form_params" => 
    ["groups" => ["new"=> [2,5,7], "removed" => [], "others" => [3,8]]
];
```
Upon arrival all empty arrays within the array have been removed:

`$groups = ["new"=> [2,5,7], "others" => [3,8]];` 

Changing the request option from "form_params" to "json" (and using `json_decode()`) upon arrival keeps the empty array intact.

Is that expected behaviour? Or am I doing something wrong?

**Comment by sagikazarmark** [comment]
This is a known behaviour of [http_build_query](http://php.net/manual/en/function.http-build-query.php#109466) which is used internally to create the form.

Although the [RFC](http://stackoverflow.com/questions/4557387/is-a-url-query-parameter-valid-if-it-has-no-value) says nothing about empty values (which mean they are not forbidden => should be valid), I cannot say that similar libraries out there have obvious support for empty values.
