### ISSUE TITLE
Cannot accessing database(On Live Server) after composer update guzzle 6.0 from guzzle 4.0

### ISSUE THREAD

**Issue by OwlGreenApple** [guzzle/guzzle#1785]
Hi

I cant access data from database after composer update to guzzle 6.0
The database server is on other server, no firewall issue and i was set up that server database can read data from some host(using remote sql)

<pre>
	$user = User::all();
	dd($user);
</pre>

It just give me a blank space. It can give me data if guzzle on 4.0

any ideas ?

**Comment by Konafets** [comment]
This looks like code from a Laravel controller where you get your users from a database. How is Guzzle involved here?

**Comment by OwlGreenApple** [comment]
@Konafets Hi I think because i got error after composer update to guzzle 6.0.
My database is from another server(not local), if it is local it works.
And if i change to guzzle 4.0 it can be access database from other server (vps, not local) and show some data.

So im pretty sure it is about guzzle. what do you think ?

**Comment by Konafets** [comment]
I think you should attach the stack trace and/or error message here and there happened a lot between 4.0 and 6.0. I doubt that just switching from one version to another is sufficient here. But this depends on your usage of Guzzle.

**Comment by OwlGreenApple** [comment]
Hmm. the problem is there are no error message(blank space) or stack trace like logs in file. 
Im 99% sure thats because change from guzzle 4.0 to 6.0. I test it many times recently.
Thats just example simple code, to test and try. i am not set up anything about guzzle on my test function.
Just need guzzle 6.0 for other plugins.

**Comment by Konafets** [comment]
I would:
- debug the database connection part, where it tries connecting to the other server. This seems a good starting point. With `debug` I mean debugging with break points in an IDE. In a lot of cases you end up an an lowlevel exception handler and are able to see the actual exception message. 
- take care of the dependencies (which plugin needs which version of Guzzle, are all plugins up-to-date, etc. ...)

Without knowing any details of your application and no error message its hard to help you here. Especially `dd()` has nothing todo with Guzzle.

**Comment by OwlGreenApple** [comment]
@Konafets you right man. thats because server setting, not a guzzle. Error show up when i put try catch on that code. thanks for your concern

**Comment by Konafets** [comment]
I am glad you found your problem.
