### ISSUE TITLE
POST Request magically turns to GET request giving me "Method Not Allowed" 

### ISSUE THREAD

**Issue by flexpeace** [guzzle/guzzle#1788]
I have a PHP file example.php and inside this file l have entered the code below 

$client->request('POST', $postURL, ['headers' => ['content-type' => 'application/json', 'Authorization'=>'Token t6wdjjd7787sjjhd87954frr']],  ['json' => $post_data] );

when l visit my web browser to test the request  localhost:8000/example.php

I get the error 405 GET not allowed, meanwhile the request am making is a POST request

What am l doing wrongly here?

**Comment by Konafets** [comment]
Your browser sends a GET request, but you need to send a POST request. You can use [Postman](https://www.getpostman.com/) or [Paw](https://paw.cloud/).

**Comment by flexpeace** [comment]
@Konafets Thanks for your quick response

With PostMan it works perfectly. I am writing a cronjob to call this example.php file every 1 hour. So l want the GuzzleHttp request to work in this case for me. 

Do you mean, l cannot call the example.php with the browser, as it will turn the request to GET? How do l test example.php file?

Thank you

**Comment by flexpeace** [comment]
By looking at the Access log at the API's end, it receives GET instead of POST. I think $client->post must call the API using the POST, why is the browser taking control of GuzzleHttp POST Request?

 at=info method=GET path="/app/study/create/" host=www.example.com request_id=731be894-76ce-4561-b060-228b54cc20ca

**Comment by Konafets** [comment]
Unless you have `<form method="POST">`, every request of the browser is done via GET. But a form is in your case not applicable anyway, since a cron job is never executed by the browser but via CLI. So, you need to write a Command Line Script which gets called by the cron job. You can execute the CLI script also manually. 

If you are using a Framework like Laravel or Symfony the best way to this is to write a command.

**Comment by sagikazarmark** [comment]
I think there is a misunderstanding here: in your case there are actually two requests: one Madrid by Guzzle, which is a POST request, the other is the request to your webserver. I assume the 405 response was not a Guzzle error and was returned by your webserver. The Guzzle method is not being overwritten by your webserver.

As @Konafets pointed, you'd probably better run this script from CLI. Even for testing purposes you can use cURL from CLI (or Postman), but your browser will always send GET to your webserver.

**Comment by flexpeace** [comment]
Thank you guys for the explanations. It does make sense to me now.

**Comment by tomazartack** [comment]
It could be that a redirect is happening in your code, this is where you can lose the POST request method, that turns into a GET methods in the end.
