### ISSUE TITLE
Test failure with 7.1.4RC1

### ISSUE THREAD

**Issue by remicollet** [guzzle/guzzle#1790]
FYI, detected by Fedora QA
https://apps.fedoraproject.org/koschei/package/php-guzzlehttp-guzzle6?collection=f27

The "Failed to parse address "127.0.0.1:8126/" error seems ugly...

Can you please have a look, so we can try to avoid BC break in upcoming 7.1.4.

**Comment by remicollet** [comment]
This looks to be related to fix for https://bugs.php.net/74216

**Comment by sagikazarmark** [comment]
Closed in favor of the new issue.
