### ISSUE TITLE
Issues with inputs during POST

### ISSUE THREAD

**Issue by m33ts4k0z** [guzzle/guzzle#1791]
It looks like that when I'm sending a json string to an API, all inputs are being sent correctly except 2. These inputs are "enabled" and "comments". The first one is a checkbox and the other one is a text input. 

For some reason these values aren't getting updated through my API while all others are. 

Calling the API url with the same request through a browser, does update all the fields.

I'm using Laravel 5.3

**Comment by m33ts4k0z** [comment]
Calling the API url with the same request through a browser, does update all the fields.

**Comment by sagikazarmark** [comment]
I am guessing from "json string" that you use POST requests. How do you send it from the browser?

Guzzle does not touch the request body, not to mention decidong a JSON body, removing fields and encoding again. I highly doubt this is a Guzzle issue.

**Comment by sagikazarmark** [comment]
Did you have a chance to investigate this issue?

**Comment by m33ts4k0z** [comment]
Hello and sorry for the late answer. The problem was on my end and it was stupid. After I executed the desired code, I had code that was undoing what my first code did so it seemed that it wasnt working. All its sorted now. Thanks

**Comment by sagikazarmark** [comment]
Great, glad you sorted it out.
