### ISSUE TITLE
Missing custom header in Response. Size/length limit?

### ISSUE THREAD

**Issue by zprisk** [guzzle/guzzle#1796]
Hello,

My API returns a custom header (named x-test-receipt) and contains a JWT (JSON Web Token) for it's value which is > 1600 characters long (see below for example).

The issue that I am having is that this header is completely missing or excluded.

Example Pseduo Code:
`$this->client = new Client(['base_uri' => $baseUri, 'auth' => [$authUsername, $authPassword]]);`

`$response = $this->client->request('GET', '/event', ['debug' => true]);`

When calling `$response->getHeaders()`, the x-test-receipt header with the value below is completely gone or missing. Is there a character length limit on a header's value length? All of my other custom headers with short values show up just fine.

`eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzcXNfcmVjZWlwdF9oYW5kbGUiOiJBUUVCWmhvRHBSM3ZNdmd5MnZkTDQ0M1ZaL204d3NBQ3dyZnNSVEQ1OFI2Z1N0STFKRVBEQkN0a21RYjhHVWZwcnpJS1hKVmxyQ25MbHAwWGxwd1VGWk9HL092cWEycWhHWm9DcUlKSnlnSWNQMHpwMmtSd2NiWjFld0tlc1ZkcS9TKzFOeGFhcFBkVkh2eVpHai9Vd2Zka01hNzBHaXJTWFNSdldXMnI5cDVZYXZoMXhmS1dON1lNK3Rwck9CSHJzV215a0hsczA2bDNJWE9Lb1pIVUgxa2g2dGl1bko4QThmTnNIZ3lrS2ZjN1o5RG1SMmdNMHFNaDZWTkxORU5tT3lDM2FVQzBpbXY1a3BCRllUbWtCeXUvYjQ4aE5yMXEzTmJyRm9Zc2svNWhyaldkUlNiZVd6bVkvU3RBZG44aTQwZWI2UTJ6dnpJb253dzJTVWJUUG11TVpBSFN2VTVnWDVaSE1IUm5OS2ZpMTkwTzQwMlJMU1E4bjh4bEd3MlQrN0x5OW1JY3Rkc3BCMlBTcTlMcVdjaXlsNzhkSHpxSHBPenFHRDIrcEFZb2VIQUZ5YVBBaTdLWEVFRTdxWks4cUxSVSIsImRlbGl2ZXJ5X2lkIjoiMTVmNzg0YzktMTQxOC00MjNmLWI5NDMtYzA5MjcyN2JjYWRkIiwiY29uc3VtZXJfaWQiOiIwMDAwMDBiMS0xMTExLTIyMjItMzMzMy0wMDAwMDAwMDAwMDAiLCJjb25zdW1lcl9kaXNwbGF5IjoiVEVTVCBTZXJ2aWNlIiwiY29uc3VtZXJfd2ViaG9vayI6ZmFsc2UsImludGVncmF0aW9uX2lkIjoiMDAwMDAwZDMtMTExMS0yMjIyLTMzMzMtMDAwMDAwMDAwMDAwIiwiaW50ZWdyYXRpb25fZGlzcGxheSI6IlRFU1QgU2FtZSBTZXJ2aWNlIHRvIFNlcnZpY2UiLCJpbnRlZ3JhdGlvbl92YXJzIjpbXSwiZXZlbnRfaWQiOiJmZjdmMGQzYi04ZDcwLTRkNTktYjU3Mi05YjJiNDhjMWVkZGQiLCJldmVudF90eXBlIjoiYnV6emkuZWNvbW1lcmNlLnRlc3QiLCJldmVudF92ZXJzaW9uIjoidjEuMCIsImV2ZW50X2Rpc3BsYXkiOiJFY29tbWVyY2UgVGVzdCBFdmVudCIsInByb2R1Y2VyX2lkIjoiMDAwMDAwYjEtMTExMS0yMjIyLTMzMzMtMDAwMDAwMDAwMDAwIiwicHJvZHVjZXJfZGlzcGxheSI6IlRFU1QgU2VydmljZSIsImFjY291bnRfaWQiOiIwMDAwMDAwMC0xMTExLTIyMjItMzMzMy0wMDAwMDAwMDAwMDAiLCJhY2NvdW50X2Rpc3BsYXkiOiJURVNUIEFjY291bnQiLCJ0aW1lc3RhbXAiOiIyMDE3LTAzLTMxVDE5OjExOjM3LjYzNFoiLCJpYXQiOjE0OTA5ODc3MDR9._yUBYRlO6fWo7WQPG8VlV2_jsYk_Qmdtei7Yll8UiP8`

**Comment by zahlprish** [comment]
Update:

It appears that because I did not have cURL installed on my machine that Guzzle was falling back to `url_fopen`, which appears to be the culprit in not grabbing or seeing the header with the long value. I am unsure if this expected behavior or not.

On a side note: an alternative package (rmccue/Requests) seems to fallback to utilizing `fsockopen`

**Comment by zprisk** [comment]
Update:

It appears that because I did not have cURL installed on my machine that Guzzle was falling back to url_fopen, which appears to be the culprit in not grabbing or seeing the header with the long value. I am unsure if this expected behavior or not.

On a side note: an alternative package (rmccue/Requests) seems to fallback to utilizing fsockopen, which does seem to grab the header + long value.

**Comment by sagikazarmark** [comment]
Hm, not sure yet if this is a bug in Guzzle or PHP.
