### ISSUE TITLE
Client certificates shared between clients

### ISSUE THREAD

**Issue by Skinner927** [guzzle/guzzle#1797]
Hello,

I'm having trouble using Guzzle when switching between using and not using client certificates.

I'm not asking for help with my unit tests, I'm using Guzzle for unit tests and Guzzle is not operating as I would expect. Here's my scenario: 

For each test, I create a `new Client`. Each Client has a `new CurlHandler` with a `new CurlFactory`. I'm only creating a handler and factory because I've just been trying everything. The `CurlFactory` creates more handles than I will ever make clients. 

Here's essentially my create function:
```
function makeClient($useCert=false) {
    $handler = new CurlHandler(['handle_factory' => new CurlFactory(10)]);
    $stack = HandlerStack::create($handler);
    
    $guzzleCfg = [
        'base_uri' => 'https://server.com',
        'verify' => false,
        'handler' => $stack,
    ];
    
    if ($useCert) {
        $guzzleCfg['cert'] = [$absCertPath, $certPass];
    }
    
    return new Client($guzzleCfg);
}
```
Case 1:
If I create a client **without** a cert and make a request and it is the first created client (first test), I correctly get an SSL error. This is expected as there is no client certificate.

Case 2:
If I make a client **with** a certificate and make a request I get no error. This is expected. 

Case 3:
If I make a client **with** a certificate, make a request (no error), then create a new client **without** a certificate, and make a request, I get no error. This is incorrect. The second client should have no certificate and therefore throw an error similar to case 1. 

Am I doing something wrong? Should I be destroying the instance? I'm not sure how to go about solving this issue. 

Thank you.

**Comment by sagikazarmark** [comment]
I wonder why you get an error in your first scenario, since verification is turned off (`'verify' => false,`).

What kind of error do you get?

**Comment by Skinner927** [comment]
I'm getting a `cURL error 35: SSL peer handshake failed, the server most likely requires a client certificate to connect (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)` error, which I would suppose is because the Apache server is requiring a client certificate, but none is presented.

**Comment by Skinner927** [comment]
This problem seems to be isolated to OS X. I just ran the tests on ubuntu without issue.

**Comment by Skinner927** [comment]
I've fixed it with following the steps here: https://coderwall.com/p/h3zzrw/using-client-ssl-certificates-for-php-curl-requests-on-osx

Basically, OS X's curl doesn't use OpenSSL, you have to install a version that does and then compile php to use that version of OpenSSL. 

`brew install curl --with-openssl`
`brew install php71 --with-homebrew-curl`

It would still be nice to have a solution or workaround for OS X.

**Comment by sagikazarmark** [comment]
Hm, since macOS is rather used for development and not production hosting, I would rather place some instructions in the documentation. But if we can find a nice way to solve the problem on macOS, I am not against it, but I would like to avoid adding massive platform dependent logic into the code base.

**Comment by sagikazarmark** [comment]
@Skinner927 do you want to add a FAQ entry suggesting the installation of cURL with SSL on macOS? I think we cannot provide a solution which handles the problem on the code level at this point.

**Comment by joshbrw** [comment]
Thanks @Skinner927 - came across this issue when trying to figure this out, didn't know it was OSX related.
