### ISSUE TITLE
How can I get array|data like in curl_getinfo ?

### ISSUE THREAD

**Issue by maxlen** [guzzle/guzzle#1798]

**Comment by maxlen** [comment]
I mean I don't need exception if code not 200 (forexample 503 ...)

**Comment by sagikazarmark** [comment]
Do you mean you would like to parse the body and load the data into an array?

Guzzle does not provide that anymore, you have to take care of it. If you receive a json response for example, you can get the data from the Response's body and parse it with `json_decode`.

Since Guzzle uses PSR-7, the Guzzle doc site and the PSR-7 spec should provide enough info about how to do that.

**Comment by Konafets** [comment]
> Do you mean you would like to parse the body and load the data into an array?

> Guzzle does not provide that anymore, you have to take care of it. If you receive a json response for example, you can get the data from the Response's body and parse it with json_decode.

I like to add, that this functionality was extracted into a different package called [Guzzle Services](https://github.com/guzzle/guzzle-services). The documentation can be found [here](http://guzzle3.readthedocs.io/webservice-client/guzzle-service-descriptions.html)

**Comment by maxlen** [comment]
no. I mean that if I get http code not equal 200 - I don't want to get exception. Has you code include it? (without try+catch)

**Comment by maxlen** [comment]
and if it's possible - how can I get curl_getinfo (it's not nesesary to be an array)

**Comment by Konafets** [comment]
I think you looking for `http_errors` option which is described [here].(http://guzzle.readthedocs.io/en/latest/request-options.html#http-errors)

**Comment by maxlen** [comment]
thanks, but can I get all info by one function like curl_getinfo ?
like code, redirect_url etc...

**Comment by sagikazarmark** [comment]
Well, you can get some information from headers (see the redirect option config), but I think you want to use the [on_stats](http://docs.guzzlephp.org/en/latest/request-options.html#on-stats) request option. In case of curl it relies on [curl_getinfo](https://github.com/guzzle/guzzle/blob/375c01b636cbbe967d4b180628abdf94c0b9070f/src/Handler/CurlFactory.php#L120).

**Comment by sagikazarmark** [comment]
Did it solve your problem?
