### ISSUE TITLE
Laravel: Invalid resource type: unknown type

### ISSUE THREAD

**Issue by jorenvh1** [guzzle/guzzle#1799]
Hey

I never had problems with uploading files but my laravel project started throwing this error everytime I upload a file: Invalid resource type: unknown type
The thing is, the actual file DOES get uploaded without any problems, but the error is still thrown.
The function throwing the error is: 'stream_for'.
When I dump the resources in the function, I get this:
![image](https://cloud.githubusercontent.com/assets/14889143/24705434/3448ed72-1a0c-11e7-8ed1-37511cee15ae.png)

The error is thrown at the last one (obviously), which is a closed resource.
What I suspect is that the resource is being closed too soon (or before the request is being made).
If I dump the types of these resources:
![image](https://cloud.githubusercontent.com/assets/14889143/24705497/8c58ee2c-1a0c-11e7-983f-d6adf4700516.png)

hence the 'unknown type' error.

Any idea on how to fix this?

ps: I never had this issue before, it worked without a problem for weeks...

**Comment by jorenvh1** [comment]
Seems like a Guzzle update caused this problem... reverted back to older version to get rid of this error

**Comment by GrahamCampbell** [comment]
What versions. If this is within the same major version, this is a bug, and should remain open.

**Comment by sagikazarmark** [comment]
Wonder if it's guzzle or PSR-7 issue though. I recall seeing some similar issues related to `php://temp`.

**Comment by jorenvh1** [comment]
No worries, it was a mistake on my part... I change some of the code of 1 method and forgot about it.
I should always overwrite methods instead of changing the original ones... :D my bad, sorry for false positive issue!
