### ISSUE TITLE
HandlerStack does not comply with a stack data-structure interface (in principle)

### ISSUE THREAD

**Issue by ndobromirov** [guzzle/guzzle#1800]
The structure is used internally as an ordered list of middlewares, and the API it exposes is not stack one, but more like a list. Either limit the API to only stack or rename the class to list  - HandlerList / MiddlewaresList / HandlerManager.

As it is, it's a bit confusing having it named a Stack with methods like _unshift_, _splice_, etc.

This can happen in backwards compatible way, by Having the new class as the base and recommended concrete implementation for this. The HandlerStack will extend it and serve as a backwards compatible layer, exposing the exact same API.

Update the documentation on the change and at some point remove the HandlerStack layer.

**Comment by sagikazarmark** [comment]
As far as I know, the term "Middleware Stack" is widely used nowadays for this kind of collection regardless of what the object itself is capable of, so I am not convinced that the name is inappropriate. I don't think changing it is necessary and I am pretty sure it would cause more confusion then it does now (no complains so far). The current API is pretty solid changing it would be quite painful, so I would like to avoid it.

Thanks for the suggestion though.
