### ISSUE TITLE
save_to doesn't work properly with redirects

### ISSUE THREAD

**Issue by mogzol** [guzzle/guzzle#1802]
I should start of by saying I am using Guzzle 5, not sure if this issue also exists in v6.

The problem I am having is that the `save_to` request option does not work properly when the page you are requesting is a redirect. It also behaves differently depending on what type of value you pass to it.

For instance, say I have my web server set up to redirect `/hello.html` to `/world.html`. Now if I use Guzzle to download that page to a file by passing a file resource like so:
```
$test = fopen('C:\dev\test.html', 'w');
$client->get('http://127.0.0.1/hello.html', ['save_to' => $test]);
```
Then the `get` call will throw an exception saying `save_to must be a GuzzleHttp\Stream\StreamInterface or resource`. This only happens when there is a redirect, the exact same code works fine if there is no redirect.

If, instead of a file resource, I pass a Guzzle `Stream`, like this:
```
$test = fopen('C:\dev\test.html', 'w');
$stream = Stream::factory($test);
$client->get('http://127.0.0.1/hello.html', ['save_to' => $stream]);
```
Then I don't get an exception, and it almost all works properly, but it writes the redirect body to the output file before writing the actual response body. So if the response has a shorter body then the redirect, some of the redirect's body will be left over. For example, here is my `test.html` file when my original `world.html` file contained only `<html><body>world</body></html>`. As you can see, the proper response was written to the beginning, but there is leftover garbage from when the redirect body was written to it:
```
<html><body>world</body></html>/DTD HTML 2.0//EN">
<html><head>
<title>301 Moved Permanently</title>
</head><body>
<h1>Moved Permanently</h1>
<p>The document has moved <a href="http://127.0.0.1/world.html">here</a>.</p>
<hr>
<address>Apache/2.4.17 (Win32) OpenSSL/1.0.2d PHP/5.6.23 Server at 127.0.0.1 Port 80</address>
</body></html>
```

Finally, if I pass just the path to the file as a string, like so:
```
$client->get('http://127.0.0.1/hello.html', ['save_to' => 'C:\dev\test.html']);
```
Then it behaves properly, only writing the contents of `world.html` to `test.html`.

**Comment by sagikazarmark** [comment]
Well, the exception seems to be weird.

About redirection: have you enabled following redirection?

**Comment by mogzol** [comment]
Doesn't Guzzle follow redirects automatically? And it is following the redirects, if I debug it I can see it get the first response, process it as a redirect, then try to follow the redirect, which is where it crashes in the first scenario. It looks like something causes the file resource to become an unknown resource type rather than a stream after the redirect response is processed, which causes the exception.

**Comment by aoboturov** [comment]
Same with me

**Comment by martinsbalodis** [comment]
After some debugging I found out that when guzzle uses fopen for request execution it doesn't find `Location` header. Installing cURL resolved the issue.
