### ISSUE TITLE
Issue Using Guzzle for SMS sending using third party api

### ISSUE THREAD

**Issue by Suvathiii** [guzzle/guzzle#1804]
Hi,

Can you please anyone guide me to use the Guzzle to send sms using third party url?

Please provide me the steps to pass the url and send the request and get the response?

**Comment by jeremeamia** [comment]
Here is the guide: http://docs.guzzlephp.org/en/latest/quickstart.html

You might also searching for Guzzle on StackOverflow if you run into any problems.
