### ISSUE TITLE
What's the best way to retry after request timeout or get some other error code when I use the newest guzzle?

### ISSUE THREAD

**Issue by luzhongyang** [guzzle/guzzle#1806]
I found [retry-subscriber](https://github.com/guzzle/retry-subscriber) which the newest guzzle can not use.

**Comment by luzhongyang** [comment]
I got it, and this is demo. You need replace 'https://500-error-code-url' with a real url when testing.
```php
require './vendor/autoload.php';

use GuzzleHttp\Client;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Handler\CurlHandler;
use GuzzleHttp\HandlerStack;
use GuzzleHttp\Middleware;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\Psr7\Response;

class TestRetry {

    public function test()
    {
        $handlerStack = HandlerStack::create(new CurlHandler());
        $handlerStack->push(Middleware::retry($this->retryDecider(), $this->retryDelay()));
        $client = new Client(array('handler' => $handlerStack));

        $response = $client->request(
            'GET',
            // @todo replace to a real url!!!
            'https://500-error-code-url'
        )->getBody()->getContents();

        return \GuzzleHttp\json_decode($response, true);
    }


    public function retryDecider()
    {
        return function (
            $retries,
            Request $request,
            Response $response = null,
            RequestException $exception = null
        ) {
            // Limit the number of retries to 5
            if ($retries >= 5) {
                return false;
            }

            // Retry connection exceptions
            if ($exception instanceof ConnectException) {
                return true;
            }

            if ($response) {
                // Retry on server errors
                if ($response->getStatusCode() >= 500 ) {
                    return true;
                }
            }

            return false;
        };
    }

    /**
     * delay 1s 2s 3s 4s 5s
     *
     * @return Closure
     */
    public function retryDelay()
    {
        return function ($numberOfRetries) {
            return 1000 * $numberOfRetries;
        };
    }
}

$TestRetry = new TestRetry();
$TestRetry->test();
```

**Comment by fuzzy76** [comment]
I guess https://github.com/caseyamcl/guzzle_retry_middleware is the way to do this now?

**Comment by mfn** [comment]
I can vouch this, I'm also using this package in multiple projects 👍

**Comment by fuzzy76** [comment]
After I wrote that comment, I noticed there is a [Retry middleware](https://github.com/guzzle/guzzle/blob/master/src/RetryMiddleware.php) built into Guzzle, but it is not mentioned in the documentation.

**Comment by fuzzy76** [comment]
Example here:
https://addshore.com/2015/12/guzzle-6-retry-middleware/

**Comment by hywak** [comment]
I'm wondering if it's safe to use `new CurlHandler()` as it depends on your php configuration, see https://github.com/guzzle/guzzle/blob/master/src/Utils.php#L81 . Additionaly you are overwritting default handlers like `http_errors`, or `allow_redirects`. If you don't pass any handler to `create` method handler based on your configuration will be created. https://github.com/guzzle/guzzle/blob/master/src/HandlerStack.php#L38 and you can still push your middleware. If I'm not missing anything it's much safer approach.

**Comment by jbruni** [comment]
Just trigger the an identical request with same parameters again, but also providing a [`delay` option](http://docs.guzzlephp.org/en/stable/request-options.html#delay).

This is, after all, [the "secret" of the RetryMiddleware](https://github.com/guzzle/guzzle/blob/master/src/RetryMiddleware.php#L107).

**Comment by zgjimgjonbalaj** [comment]
Are the func args correct here? It seems it is explicitly requiring a RequestException but then we check if $exception is an instance of ConnectionException?
