### ISSUE TITLE
SSL CA bundle not found: 

### ISSUE THREAD

**Issue by AdriWild** [guzzle/guzzle#1807]
Hello, I´ve tried to connect with an API, but I got always this error, I also tried with `  'verify' => false` but then I got error: "Unknown SSL Protocol". I´m not sure what I´m doing wrong, or it is the api server.

> InvalidArgumentException in CurlFactory.php line 331:
> SSL CA bundle not found: 

```
        $client = new Client([
            'base_uri' => 'https://api-addres:8081',
            'verify' => url('certificates/api-certificate.pem')
        ]);
        $response = $client->request('POST', '/serverhttpapi/v1/auth/login', [
            'UserName' => 'user',
            'Password' => 'pass',
        ]);
```

**Comment by sagikazarmark** [comment]
What does your `url` function call return? Can you verify that it's a file path which PHP can read?

**Comment by AdriWild** [comment]
> 
> RequestException in CurlFactory.php line 187:
> cURL error 60: SSL certificate problem: unable to get local issuer certificate (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)

It is a "login" function, it should return a Token-Session.

Yes, php path is able to read.

Thanks

**Comment by sagikazarmark** [comment]
> > RequestException in CurlFactory.php line 187:
> > cURL error 60: SSL certificate problem: unable to get local issuer certificate (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)

Is this what the `url` call returns? If so, it happens before the guzzle call.

Also `SSL certificate problem: unable to get local issuer certificate` means you don't have an up to date CA database on your server.
