### ISSUE TITLE
Escaped unicode JSON probem with API

### ISSUE THREAD

**Issue by Nomadzy** [guzzle/guzzle#1815]
Will trying to POST some non ascii text in json to an api (elasticsearch-langdetect), the text got unicode escaped, I guess via json_encode, witch is cosing trouble with the language detection.

Is there a way to specify JSON_UNESCAPED_UNICODE, like in the json_encode function ?

>		$url		= 'http://localhost:9200/_langdetect';
>		$response 	= $this->client->post($url, ['json' => ['text' => $text]]);

**Comment by sagikazarmark** [comment]
I would suggest manual encoding. You can pass the encoded string in the `body` request option. Of course in this case you have to configure the Content-Type header as well.
