### ISSUE TITLE
How to get downloaded filename inside fulfilled of Pool ?

### ISSUE THREAD

**Issue by UmbrellaCoders** [guzzle/guzzle#1816]
`$requests = function ($total) use ($client) {
            foreach($this->downloadLinks as $key => $link) {

                preg_match('/([0-9]*)\.mp4/', $link, $matches);
                $resource = getcwd().'/videos/'.$this->downloadPath.'/'.$matches[0];

                yield function () use ($client, $link, $resource) {
                    return $client->getAsync($link, [
                        'sink' => $resource,
                        'proxy' => 'tcp://'.$this->proxies[ mt_rand(0, count($this->proxies)-1)]
                    ]);
                };
            }
        };

        $pool = new Pool($this->browser, $requests(count($requests)), [
            'concurrency' => $concurrency,
            'fulfilled' => function ($response, $index) {
               
               HOW TO GET DOWNLOADED FILENAME HERE?

            },
            'rejected' => function ($reason, $index) {
              echo 'rejcted';
            },
        ]);

        $promise = $pool->promise();
        $promise->wait();`

Thanks

**Comment by sagikazarmark** [comment]
Not sure you can, unless you save it somewhere in in your generator and refer to it by it's index.

**Comment by UmbrellaCoders** [comment]
middlewears helped me with this

**Comment by sagikazarmark** [comment]
Great!

**Comment by weiqiangxu** [comment]
@UmbrellaCoders how to solve this problem, can you post your code to me ???
`$pool = new Pool($this->browser, $requests(count($requests)), [
        'concurrency' => $concurrency,
        'fulfilled' => function ($response, $index) {
           
           HOW TO GET DOWNLOADED FILENAME HERE?

        },
        'rejected' => function ($reason, $index) {
          echo 'rejcted';
        },
    ]);`

i also  need the Request.url of this successful callback.

**Comment by weiqiangxu** [comment]
`







	// 并发处理多个-协程就是用户态的线程-运用协程实现
	public function poolRequest($step,$datas,$status='completed')
	{

		// 当前发送的请求的最小ID
		$minId = $datas[0]->id;

		$client = new Client();
		// 并发处理请求对象
		$config = array(
			'verify' => false,
			// 'proxy'=>'https://110.82.102.109:34098'
		);
        $requests = function ($total) use ($client,$datas,$config) {
            foreach ($datas as $data) {
            	$url = html_entity_decode($data->url);
                yield function() use ($client,$url,$config) {
                    return $client->getAsync($url,$config);
                };
            }
        };

		$pool = new Pool($client, $requests(count($datas)), [
			// 每发5个请求
		    'concurrency' => 5,
		    'fulfilled' => function ($response, $index ) use($step,$minId,$status) {
		        // this is delivered each successful response "url"
		        
		        // 当前处理的发送请求的ID
		        $id = $index+(int)$minId;
		        // 文件保存路径
		        $file = PROJECT_APP_DOWN.$step.'/'.$id.'.html';
		        // 校验回调成功
		        if($response->getStatusCode()==200)
		        {
		        	// 保存文件
		            file_put_contents($file,$response->getBody());
		            // 命令行执行时候不需要经过apache直接输出在窗口
		            echo $step.' '.$id.'.html'." download successful!".PHP_EOL;
		        }
		        if(file_exists($file))
		    	{
		            // 更改SQL语句
		            Capsule::table($step)
				            ->where('id', $id)
				            ->update(['status' =>$status]);
		    	}		    	
		    },
		    'rejected' => function ($reason, $index) {
		        // this is delivered each failed request
		        echo "rejected reason: " . $reason.PHP_EOL;
		    },
		]);

		// Initiate the transfers and create a promise
		$promise = $pool->promise();

		// Force the pool of requests to complete.
		$promise->wait();
	}`



i have solve this problem use index . thanks
