### ISSUE TITLE
authenticate with login form

### ISSUE THREAD

**Issue by masihfathi** [guzzle/guzzle#1817]
thanks for your great extension. is it possible to authenticate a user with a login form for example login into GitHub via "https://github.com/login" and then go to a page that needs login for example "https://github.com/settings/profile"? I see the package like "https://github.com/FriendsOfPHP/Goutte" but they use "symfony/browser-kit" package. I want to know is it possible to do this work with guzzle only?

**Comment by sagikazarmark** [comment]
Guzzle is an HTTP client, does not provide anything like that out of the box. You may use it's Oauth plugin, but that won't let you do browser authentication.
