### ISSUE TITLE
JSON data is never sent as part of the PUT request

### ISSUE THREAD

**Issue by flexpeace** [guzzle/guzzle#1819]
The JSON data is never sent as part of the PUT request.

$arr = array("rmAction" => "dfdfdfdf");
$jsondata=json_encode($arr);
 $response = $client->put('/api/re/notification/,
   ['headers'  => [ 'content-type' => 'application/json','authorization' => 'JWT dsdeww73387' ]], 
   ['json' => $jsondata]);

What could possibly be the issue?

**Comment by BVisagie** [comment]
I had problems with this in the past, take a look at the example I had working, note "JSON_FORCE_OBJECT":

//THE WEBSERVICE UPDATE BASE URL 
$baseServiceURL = (string)('http://127.0.0.1:8080/service/v1/ws//something/update'); 

$updateRequestClient = new Client(['timeout'  => 10000.0,]);

//ASSIGN json name/value pairs to body
$updateBody['name1'] = $varNum1;
$updateBody['name2'] = $varNum2;
$updateBody['name3'] = $varNum3;
$updateBody['name4'] = $varNum4;
$updateBody['name5'] = $varNum5;
$updateBody['name6'] = $varNum6;
$updateBody['name7'] = $varNum7;

//SEND AND SAVE RESULT TO updateRequestResponse //TAKE NOTE OF: JSON_FORCE_OBJECT //
$updateRequestResponse = $updateRequestClient->post($baseServiceURL, ['headers' => ['Content-Type' => 'application/json', 'Accept' => 'application/json', 'token' => 'test-token'], 'body' => json_encode($updateBody, JSON_FORCE_OBJECT) ]);

$requestResponseCode = $updateRequestResponse->getStatusCode(); // 200?? 

if ($requestResponseCode == "200") {                                                  

echo ("SUCCESS");

}

**Comment by Fuco1** [comment]
@flexpeace @BVisagie You should pass an array (or something json-encodable) to the `json` option, not a string.  That's all.

**Comment by sagikazarmark** [comment]
Exactly, the `json` option awaits an array or an object. In the above code all you need to do is pass your JSON data to the `body` request option. Since you already configured the Content-Type header, you don't need to do anything else.

**Comment by sagikazarmark** [comment]
Does it solve your problem?

**Comment by hanwenbo** [comment]
i find a new bug ,requestAsync Can't spread json

**Comment by sagikazarmark** [comment]
I'm sorry, what bug did you find? Can you show an example?
