### ISSUE TITLE
Slow requests using curl_multi_exec and tick()

### ISSUE THREAD

**Issue by dtirer** [guzzle/guzzle#1820]
I have a Laravel application which sends data to SQS on nearly every request.  However, every so often, one of these requests takes several seconds to execute.  Attached is a stack trace from New Relic.  It seems that the tick() method gets called many times and the seconds just pile up.  It also seems to be making several attempts to connect to the same endpoint, though they are AWS services so I can't imagine they'd unresponsive this often.  Any idea why this might occur?

stack trace: https://ibb.co/f05gLk

**Comment by sagikazarmark** [comment]
This indeed shows that `tick` is called, but it does not show how much of that time is network traffic. Not sure if NewRelic can provide that information, AFAIK Blackfire can.
