### ISSUE TITLE
Missing support for *_proxy environment variables

### ISSUE THREAD

**Issue by fbourigault** [guzzle/guzzle#1821]
Guzzle is missing lowercased version of proxy variables. According to https://unix.stackexchange.com/a/212972, the `*_proxy` variables used to be named in lowercase.

Is this intentional from guzzle?

If no, I will submit a PR to add support for lowercased `*_proxy` variables.

**Comment by sagikazarmark** [comment]
Good question, I have no idea if it's intentional. I will have to check, but currently I am more focused on releasing 6.3.
