### ISSUE TITLE
Custom Header Missing

### ISSUE THREAD

**Issue by lib-hub** [guzzle/guzzle#1835]
Hi, I am facing problem on sending custom HTTP header as Boolean value
 
use GuzzleHttp\Client;
$client = new Client()
$client->request('POST', '/http-request.php', [
    'headers' => ['custom-header' => true],
    'debug' => true
]);

OUTPUT:
>Trying localhost...
TCP_NODELAY set
Connected to localhost (localhost) port 80 (#0)
POST /http-request.php HTTP/1.1
Host: localhost
Content-Length: 0
User-Agent: GuzzleHttp/6.2.1 curl/7.52.1 PHP/7.0.16
Content-Type: application/json
**custom-header**: 1
< HTTP/1.1 200 OK
< Date: Mon, 15 May 2017 06:00:44 GMT
< Server: Apache/2.4.7 (Ubuntu)
< X-Powered-By: PHP/5.5.9-1ubuntu4.21
< Content-Length: 1
< Content-Type: text/html 
Curl_http_done: called premature == 0
Connection #0 to host localhost left intact

When we doing same scenario with header option set as below we can't able to retrieve header details

 use GuzzleHttp\Client;
$client = new Client()
$client->request('POST', '/http-request.php ', [
    'headers' => ['custom-header' => false],
    'debug' => false
]);

>Trying localhost...
TCP_NODELAY set
Connected to localhost (localhost) port 80 (#0)
POST /http-request.php HTTP/1.1
Host: localhost
Content-Length: 0
User-Agent: GuzzleHttp/6.2.1 curl/7.52.1 PHP/7.0.16
Content-Type: application/json
< HTTP/1.1 200 OK
< Date: Mon, 15 May 2017 06:00:44 GMT
< Server: Apache/2.4.7 (Ubuntu)
< X-Powered-By: PHP/5.5.9-1ubuntu4.21
< Content-Length: 1
< Content-Type: text/html 
Curl_http_done: called premature == 0
Connection #0 to host localhost left intact

Custom header is missing, Please assist us if we are doing any thing wrong

--
Regards
Krishna

**Comment by sagikazarmark** [comment]
The problem is you cannot send boolean values this way. As you can see they are always casted to integer/string.

If you specifically want to send the values true and false, you need to send them as string: 'true' or 'false'. Or you should be able to send 1 or 0 as well.

It's still a mystery why false is missing, even with a zero value.

Try using the above, if 0 (empty) value is still missing we can look into it.

**Comment by decadence** [comment]
Maybe Guzzle filters empty headers. false becomes empty string when it is casted to string by PHP.

**Comment by sagikazarmark** [comment]
> Maybe Guzzle filters empty headers. false becomes empty string when it is casted to string by PHP.

That's what I suspect as well. Let's see if the above solves the problem.

**Comment by lib-hub** [comment]
Thanks @sagikazarmark , @decadence 

@sagikazarmark  as you mentioned we have checked with 0 its working, is't only way to getting result for this problem

var_dump(0==false); // bool(true)
var_dump(0===false); // bool(false)  //different types

**Comment by sagikazarmark** [comment]
Great.
