### ISSUE TITLE
No way to detect timeouts

### ISSUE THREAD

**Issue by Thijs-Riezebeek** [guzzle/guzzle#1837]
It does not seem possible to detect whether or not a timeout occurred. I would have expected some sort of `TimeOutException` to be thrown, but it just throws a `RequestException`.

```
$response = $this->http_client->send($request, $options);
// RequestException
```

How can I check for this in a reliable manner? Checking `RequestException::getMessage()` for the `'timed out'` string does not seem very reliable.

**Comment by tomzx** [comment]
Hello,

Could you specify which version of Guzzle you are using, as well as the timeout options?

For Guzzle 6.3.0 with the following request, I get a `GuzzleHttp\Exception\ConnectException` exception.

```php
$client = new Client();
$response = $client->request('POST', 'http://localhost/test-guzzle/upload.php', [
    'connect_timeout' => 1,
]);
```

**Comment by Nyholm** [comment]
You should catch the `ConnectException`, see the class docs: 

> Exception thrown when a connection cannot be established.

Thank you @tomzx

**Comment by hamidjavadi** [comment]
I have the timeout error but the **ConnectException** exception did not works for me !!!

**Comment by fxedel** [comment]
Please note that a `ConnectException` is also thrown for errors like `Failed to connect to localhost port 9020: Connection refused`, which is not a timeout.

**Comment by EdgarSedov** [comment]
So, what's the proper way to detect timeouts when? Not connection timeouts, but request timeouts?
