### ISSUE TITLE
guzzle cURL error 28 - How to config timeout ?

### ISSUE THREAD

**Issue by Lujidev** [guzzle/guzzle#1847]
Hi guys,

I've got this error very often. I make research, most of people resolved this error by changing the default timeout.
Where can i change this value ?
Thank you

`Fatal error: Uncaught exception 'GuzzleHttp\Exception\ConnectException' with message 'cURL error 28: Operation timed out after 0 milliseconds with 0 out of 0 bytes received (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)`

**Comment by Gems** [comment]
http://docs.guzzlephp.org/en/latest/request-options.html#timeout

**Comment by abdialeh** [comment]
just add path to cacert.pem file
**openssl.cafile=path/to/cacert.pem**
and 
**openssl.capath=path/to/folder of cacert.pem file**
and you can get the file from this link [](http://curl.haxx.se/ca/cacert.pem)

then restart Apache/nginx & php-fpm

**Comment by rethdaro** [comment]
Hi abdialeh, I have the same problem, but I hosted laravel 5.5 on shared web hosting. how can I edit openssl.cafile=path/to/cacert.pem ?

**Comment by gmponos** [comment]
closing @Gems is correct here.

**Comment by amine-betari** [comment]
@Gems 

Thank you

we use Guzzle on a Sf 3.4 project with a timeout of 30 seconds so we can wait 30 seconds for the server to respond

sometimes we have this error :
`Error calling api B2C: cURL error 28: Operation timed out after 30001 milliseconds with 0 bytes received (see http://curl.haxx.se/libcurl/c/libcurl-errors.html) [] []
`
We wonder are there other actions we can do or is everything based on timeout ?

Many Thanks

**Comment by Gems** [comment]
Hello @amine-betari, 

Not sure if it helps but you could take a look at the [connect timeout](https://docs.guzzlephp.org/en/latest/request-options.html#connect-timeout) setting.
