### ISSUE TITLE
Guzzle breaks auto loading

### ISSUE THREAD

**Issue by cdesewell** [guzzle/guzzle#1853]
From: https://stackoverflow.com/questions/44353842/adding-league-s3-filesystem-breaks-auto-loading

I receive the following auto loading error on my EBS system after having installed a component that requires guzzle.

composor.json:

```
  "require": {
    "php": ">=5.5.0",
    "slim/slim": "2.3.2",
    "slim/extras": "dev-develop",
    "twig/twig":  "1.*",
    "directus/migrations": "dev-master",
    "directus/permissions": "0.9.*@dev",
    "directus/database": "~0.1.3",
    "league/flysystem": "^1.0",
    "league/flysystem-aws-s3-v3": "^1.0", <<<< Requires Guzzle
    "swiftmailer/swiftmailer": "^5.4"   },
```
Error:

> Failed opening required '/var/app/current/vendor/composer/../guzzlehttp/psr7/src/functions_include.php' (include_path='/var/app/current/vendor/phpunit/php-token-stream:/var/app/current/vendor/phpunit/phpunit-mock-objects:/var/app/current/vendor/phpunit/php-code-coverage:/var/app/current/vendor/phpunit/phpunit:/var/app/current/vendor/symfony/yaml:.:/usr/share/pear7:/usr/share/php7') in /var/app/current/vendor/composer/autoload_real.php on line 70

**Comment by sagikazarmark** [comment]
Are you sure that Guzzle and all of it's components are properly installed (is that file present)? What versions are in your lock file?
