### ISSUE TITLE
Cast returned JSON to specific class with json_decode($body, Foo::class)

### ISSUE THREAD

**Issue by lathspell** [guzzle/guzzle#1854]
The result of $client->get(...)->getBody() is StreamInterface and a json_decode() on it always returns a stdClass.
It would be nice if I could tell Guzzle that I want the JSON to be deserialized into an object of a specific class.

E.g.:

      $person = json_decode($body, Person::class);
      or 
      $person = $client->get(...)->getBodyAs(Person::class);

As Guzzle provides it's own version of json_decode() it could maybe enhance it a bit more. Or provide an additional   "json_decode_to_class($body, Person::class)".

**Comment by sagikazarmark** [comment]
Thanks for the suggestion, but it's unlikely that this feature will ever land in Guzzle.

For one, Guzzle implements the PSR-7 HTTP Message standard, so adding a method like `getBodyAs` is not an option.

Also, the custom json_decode method is present mostly for error handling reasons.

Data serialization is completely out of scope for Guzzle, I would try a library specifically made for this, like the [Symfony Serializer](http://symfony.com/doc/current/components/serializer.html) component.
