### ISSUE TITLE
cURL error 60:SSL certificate problem when using guzzle but not when using cURL original

### ISSUE THREAD

**Issue by skyhee** [guzzle/guzzle#1855]
my cURL orginal code below:

    $curl = curl_init();
    curl_setopt($curl, CURLOPT_RETURNTRANSFER, true);
    curl_setopt($curl, CURLOPT_TIMEOUT, 500);
    curl_setopt($curl, CURLOPT_SSL_VERIFYPEER, true);
    curl_setopt($curl, CURLOPT_SSL_VERIFYHOST, true);
    curl_setopt($curl, CURLOPT_URL, $url);

    $res = curl_exec($curl);
    
    curl_close($curl);

that runs right, but when using guzzle:

    $options = [
      'handler'=>HandlerStack::create(),
      'query' => [ 'a' =>'b']
    ];
    (new Client())->request($method, $url, $options);

then got error like this:

    cURL error 60: SSL certificate problem, verify that the CA cert is OK. Details: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)

**Comment by sagikazarmark** [comment]
Thanks for reporting this issue.

Do you have any special CA settings in your php.ini?

**Comment by ningskyer** [comment]
no,i didn't set CA.  when calling curl_version() i got this:
`
{
    "version_number": 466176,
    "age": 3,
    "features": 34493,
    "ssl_version_number": 0,
    "version": "7.29.0",
    "host": "x86_64-redhat-linux-gnu",
    "ssl_version": "OpenSSL/0.9.8b",
    "libz_version": "1.2.3",
    "protocols": [
        "dict",
        "file",
        "ftp",
        "ftps",
        "gopher",
        "http",
        "https",
        "imap",
        "imaps",
        "ldap",
        "ldaps",
        "pop3",
        "pop3s",
        "rtsp",
        "scp",
        "sftp",
        "smtp",
        "smtps",
        "telnet",
        "tftp"
    ]
}
`

**Comment by ningskyer** [comment]
how can i fix this?thks

**Comment by michimawan** [comment]
can you use this @ningskyer  ??

(new Client(['verify' => false]))->request($method, $url);

**Comment by cannect** [comment]
Having the same issue,

WHen using: 

```
$guzzleClient = new Client( array(
			'curl'            => array( CURLOPT_SSL_VERIFYPEER => false, CURLOPT_SSL_VERIFYHOST => false ),
			'allow_redirects' => false,
			'cookies'         => true,
			'verify'          => false
		) );
```

The verify part and curl parts are not respected. I keep getting this error:

```
Fatal error: Uncaught GuzzleHttp\Exception\RequestException: cURL error 60: SSL certificate problem: unable to get local issuer certificate (see http://curl.haxx.se/libcurl/c/libcurl-errors.html) 
```

**Comment by bjoernffm** [comment]
Is there any chance to get the real URI you wanted to request? Some CA chains may not be correct?

Another idea: Try to use `CURLOPT_SSL_VERIFYHOST` with value `2` instead of `true`. `true` is not a valid value anyway and `1` is deprecated since cURL 7.28.1 
Check out http://php.net/manual/de/function.curl-setopt.php

**Comment by TwanoO67** [comment]
Old topic... But I encouter the same issue. (Tested In Guzzle 6.2 )

I have a self-signed wildcard certificate that I enabled on my server.

My test procedure is: 
- CURL BASH : "curl https://myurl.local.network" in bash
- CURL PHP DEFAULT: a php scripts with curl without options
- CURL PHP FORCED: a php scripts with curl with options CURLOPT_SSL_VERIFYPEER=true and CURLOPT_SSL_VERIFYHOST=2
- GUZZLE DEFAULT: a php script with guzzle client without options
- GUZZLE VERIFY FALSE: a php script with guzzle Client(['verify' =>  false])
- GUZZLE VERIFY CACERT: a php script with guzzle Client(['verify' =>  'my-cacert-file-path'])

Step 1) I created a self signed certificat for my apache vhost
at this step all test failed (except GUZZLE VERIFY FALSE, which is always OK of course )

Step 2) I updated my ca-cert bundle with my own ca-cert.
Then tests CURL BASH, CURL PHP DEFAULT and CURL PHP FORCED passes
but the GUZZLE DEFAULT and GUZZLE VERIFY CACERT are still failing with error "curl error 60 etc...)

Step 3) I updated my php.ini file to force "openssl.cafile" and "curl.cainfo" to my ca-cert bundle file.
No changes, the CURL tests are still good, but the GUZZLE DEFAULT and GUZZLE VERIFY CACERT are still failing

So I think that by default Guzzle is not following the same rule as libcurl.
And I don't know what I can change in my php installation or server, to make this work (without having to change all my code and dependencies to insert option in Guzzle Client creation... )

**Comment by ElijahLynn** [comment]
> Old topic... But I encouter the same issue. (Tested In Guzzle 6.2 )
> 
> I have a self-signed wildcard certificate that I enabled on my server.
> 
> My test procedure is:
> 
> * CURL BASH : "curl https://myurl.local.network" in bash
> * CURL PHP DEFAULT: a php scripts with curl without options
> * CURL PHP FORCED: a php scripts with curl with options CURLOPT_SSL_VERIFYPEER=true and CURLOPT_SSL_VERIFYHOST=2
> * GUZZLE DEFAULT: a php script with guzzle client without options
> * GUZZLE VERIFY FALSE: a php script with guzzle Client(['verify' =>  false])
> * GUZZLE VERIFY CACERT: a php script with guzzle Client(['verify' =>  'my-cacert-file-path'])
> 
> Step 1) I created a self signed certificat for my apache vhost
> at this step all test failed (except GUZZLE VERIFY FALSE, which is always OK of course )
> 
> Step 2) I updated my ca-cert bundle with my own ca-cert.
> Then tests CURL BASH, CURL PHP DEFAULT and CURL PHP FORCED passes
> but the GUZZLE DEFAULT and GUZZLE VERIFY CACERT are still failing with error "curl error 60 etc...)
> 
> Step 3) I updated my php.ini file to force "openssl.cafile" and "curl.cainfo" to my ca-cert bundle file.
> No changes, the CURL tests are still good, but the GUZZLE DEFAULT and GUZZLE VERIFY CACERT are still failing
> 
> So I think that by default Guzzle is not following the same rule as libcurl.
> And I don't know what I can change in my php installation or server, to make this work (without having to change all my code and dependencies to insert option in Guzzle Client creation... )

Also having issues with Guzzle not honoring curl.cainfo even though a test.php script honors it fine. I am in a firewalled network that rewrites the SSL/TLS certificate and I get a self signed certificate in certificate chain error. Only the Guzzle client gets this though, it is like it doesn't see the php.ini settings.
