### ISSUE TITLE
Guzzle Hang when trying to access my url

### ISSUE THREAD

**Issue by jeimz143** [guzzle/guzzle#1857]
Hi sir, 
   im not sure if this is a bug but, it hangs my app whenever i try to access my local url using guzzle

as you can see to the attach image it stuck into pending whenever i hit my button to my app:

![untitled](https://user-images.githubusercontent.com/13939947/27177161-f65cf412-51f7-11e7-8d10-2c88a8a040cd.png)

and here is the backend controller code im not sure if i did it right or its bug:
```
class LoginApiController extends Controller{
public function authenticate(Client $http,Request $request)
    {
        $email = $request->email;
        $password = $request->password;

        $response = $http->post('http://localhost:8000/oauth/token/', [
              'form_params' => [
                'username' => $email,
                'password' => $password,
                'grant_type' => 'password',
                'client_id' => env('API_CLIENT_ID'),
                'client_secret' => env('API_CLIENT_SECRET'),
                'scope' => '*'
              ],

          ]);

        dd(json_decode((string) $response->getBody(), true));
    }
}
```
i use laravel for my backend and trying to make a login authentication  using laravel passport
 please check thank you

**Comment by sagikazarmark** [comment]
Hi there,

The fact that your AJAX call hangs can be a consequence of quite a few things.

What's the URL of the AJAX call? Since it ends with token, it looks like you are trying to call the same URL from Guzzle which would mean an endless loop.

**Comment by jeimz143** [comment]
here is my ajax: 
```
api.post('/api/auth/token', state.credentials).then((response) => {
          //anything else
        });
```
im not sure if did it right.. 

i tried to change my url from `/api/auth/token` to `/api/authenticate`  still it hangs my ajax call..

**Comment by carlkroeger** [comment]
I have exactly the same problem, what causes this?

**Comment by Nyholm** [comment]
This issue seams unrelated to Guzzle. You should investigate why `http://localhost:8000/oauth/token/` does not reply. 

Consider asking for help on StackOverflow or similar forums.

**Comment by jeimz143** [comment]
Hi sir @Nyholm, whenever i use guzzle such as this code:
```

$response = $http->post('http://localhost:8000/oauth/token/', [
              'form_params' => [
                'username' => $email,
                'password' => $password,
                'grant_type' => 'password',
                'client_id' => env('API_CLIENT_ID'),
                'client_secret' => env('API_CLIENT_SECRET'),
                'scope' => '*'
              ],

          ]);
```
it hangs my ajax call but i found some code such as Route::dispatch it work perfectly!
here is my code to my back end:
```
$email = $request->email;
        $password = $request->password;
        $request->request->add([
            'username' => $email,
            'password' => $password,
            'grant_type' => 'password',
            'client_id' => env('API_CLIENT_ID'),
            'client_secret' => env('API_CLIENT_SECRET'),
            'scope' => '*'
        ]);

        $tokenRequest = Request::create(
            env('APP_URL').'/oauth/token',
            'post'
        );
        $response = Route::dispatch($tokenRequest);

        if($response->getStatusCode() == 200){
            $this->storeAccessToken($response->getContent());
        }

        return $response;
```
im not sure why it hangs my ajax whenever i make a call with localhost though it works in postman i am getting a respond it just that it hangs in my browser.

**Comment by carlkroeger** [comment]
I ended up solving it by using wamp virtualhost instead of php artisan serve. No idea why it doesn't work with localhost though.

**Comment by bionets** [comment]
I think this is a Guzzle related issue cause I have been stuck on this error too and using @jeimz143 suggestion helped.

**Comment by leptoquark1** [comment]
This problem seems to be related with the php internal Webserver.
If you do "php -S 127.0.0.1:8000" in your public folder it wont work too. Seems like those kind of operations are stricted with the default config for php internal webserver.

**Comment by danqulogy** [comment]
> I ended up solving it by using wamp virtualhost instead of php artisan serve. No idea why it doesn't work with localhost though.

Please how did you do it. Paster the code here

**Comment by leptoquark1** [comment]
> 
> 
> > I ended up solving it by using wamp virtualhost instead of php artisan serve. No idea why it doesn't work with localhost though.
> 
> Please how did you do it. Paster the code here

There is no code to provide. Just set up your own virtual host for your project folder.
Easy way to do that is using something like MAMP, WampServer, XAMPP or LAMP

**Comment by danganhvu1998** [comment]
The reason for this is php artisan serve is a single thread application. So when we use guzzle to request from it to itself, it basically just tries to finish guzzle request (as a client) first then come to finish that request (as a server), which is impossible. 
I have a way to work around it still using php artisan

```
// Import
use Laravel\Passport\Http\Controllers\AccessTokenController;
use Laravel\Passport\TokenRepository;
use Lcobucci\JWT\Parser as JwtParser;
use League\OAuth2\Server\AuthorizationServer;
use Psr\Http\Message\ServerRequestInterface;
```

`
// login-authen function
protected $server;
    protected $tokens;
    protected $jwt;


    public function __construct(AuthorizationServer $server,
                                TokenRepository $tokens,
                                JwtParser $jwt)
    {
        $this->jwt = $jwt;
        $this->server = $server;
        $this->tokens = $tokens;
    }


    public function login(ServerRequestInterface $request)
    {
        $controller = new AccessTokenController($this->server, $this->tokens, $this->jwt);

        $request = $request->withParsedBody($request->getParsedBody() +
        [
            'grant_type' => 'password',
            'client_id' => config('services.passport.client_id'),
            'client_secret' => config('services.passport.client_secret'),
        ]);


        return with(new AccessTokenController($this->server, $this->tokens, $this->jwt))
            ->issueToken($request);
    }
`

**Comment by AtillaPehlivan** [comment]
@danganhvu1998 , Thank you , save my time :)

**Comment by manishadhikari241** [comment]
Make Virutal host and try!! localhost::8000 does not work
