### ISSUE TITLE
use Middleware::log with debug level

### ISSUE THREAD

**Issue by lhfeng** [guzzle/guzzle#1859]
hi:

i use Middleware::log with debug level into file ,what tools to pretty format the log ?

**Comment by sagikazarmark** [comment]
Not sure what you are asking: is there a way to dump formatted messages to the log file or is there a way to view the logs with a software which can format it.

Question 1: We have a MessageFormatter interface.
Question 2: http://lnav.org/

Hope this helps.

**Comment by lhfeng** [comment]
That helped me， thanks.
