### ISSUE TITLE
Guzzle curl error 23

### ISSUE THREAD

**Issue by ghost** [guzzle/guzzle#1863]
![image](https://user-images.githubusercontent.com/25544960/27476470-7bebcd1c-583b-11e7-915d-49516c8ce9bd.png)
![image](https://user-images.githubusercontent.com/25544960/27476513-a1214058-583b-11e7-9bac-439643afc93e.png)
![image](https://user-images.githubusercontent.com/25544960/27476539-b5fdd7f2-583b-11e7-95e4-ac29263f3a4e.png)

This is the cron job that crawls data from website.
But it occurs error as below when I call request method.
![image](https://user-images.githubusercontent.com/25544960/27476598-f167741a-583b-11e7-8aa7-7e3be902c428.png)

I have no clue what the main reason is....
Please help me.
PS. This works well on my localhost but not on AWS Ubuntu server.
      And 'SJIS' encoded.

**Comment by GabrielDelepine** [comment]
Hi @ghost

Log output in plain text would be very useful to help search engines to index your issue. Like this other person who experiences this potential bug can find this page easier and help to solve it ;)
