### ISSUE TITLE
Call to undefined method GuzzleHttp\Psr7\Request::withParentHeader()

### ISSUE THREAD

**Issue by M-Shahbaz** [guzzle/guzzle#1865]
![image](https://user-images.githubusercontent.com/3539612/27505133-c6a364c0-58b1-11e7-883b-68b8a29ee7cd.png)
Working fine on localhost, not on live server running PHP 5.5.38

**Comment by alexeyshockov** [comment]
Just update to the latest version of `guzzlehttp/guzzle` & `guzzlehttp/psr7`.

**Comment by gmponos** [comment]
Would like to help here.. but I see no feedback provided after the comment of @alexeyshockov 

Also no version of guzzle/guzzle guzzle/psr7 or php is provided..

I am closing the issue.. If you are still having issues feel free to provide more info and we can reopen it.
