### ISSUE TITLE
hi, Ask for help, Async how to make it no wait time？ 

### ISSUE THREAD

**Issue by hanwenbo** [guzzle/guzzle#1868]
Why do they still "requestAsync" waiting time?I want to asynchronous to save the log, but I tried with official "Async" method of words, will be waiting time, may name is asynchronous, I don't understand these "Async" is needs to have a waiting time。
I was submitted to elk log server to log

**Comment by Nader-Zubaid** [comment]
https://g.co/kgs/AioCpL

**Comment by sagikazarmark** [comment]
Hi,

Not sure what your exact problem is. Async means there is no guarantee about the when, it only guarantees it will happen in the future. If you want to force the request to be synchronous, you can manually call `wait`.

**Comment by pekhota** [comment]
Hi, php can't be asynchronous. So, the idea here is to your save time in case you run 2 and more requests in paralel. Guzzle do them async but you will wait for the time of longest one. Notice, you will wait for the longest call if you do 2 calls async. But for one call no profit.

**Comment by gmponos** [comment]
Please check these:

https://stackoverflow.com/questions/35956516/send-asynchronous-request-without-waiting-the-response-using-guzzle
https://github.com/guzzle/guzzle/issues/1429#issuecomment-197119452

For any further questions or support you can use the channels that are listed here: https://github.com/guzzle/.github/blob/master/.github/SUPPORT.md
