### ISSUE TITLE
on_stats callback ignored when request times out

### ISSUE THREAD

**Issue by berarma** [guzzle/guzzle#1869]
The ```on_stats``` option defines a callback that is called after a request with low level information about the transaction or an error. In case the request times out this callback doesn't get called and an exception is thrown, as if some error or fatality happened.

This is made worse by the fact that there's no simple way to identify the time out exception other than parsing the exception message. This is already reported at #1837.

Time out errors should be reported like the other request errors.

Tested using the CURL handler.

**Comment by sagikazarmark** [comment]
Thanks for reporting this issue. I agree that timeout handling in Guzzle is somewhat controversial. I will try to give it a few thoughts soon and see what I can come up with.

**Comment by oneword** [comment]
So now? I encountered the same problem.

**Comment by gmponos** [comment]
Hello here..

I am not sure which Guzzle version you were using but this seems to do the work using guzzle 6.3.3

```
<?php

use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\RequestOptions;
use GuzzleHttp\TransferStats;

require_once 'vendor/autoload.php';

$client = new GuzzleHttp\Client();
try {
    $response = $client->request(
        'get',
        'www.notexistingwebsite.com',
        [
            RequestOptions::TIMEOUT => 0.1,
            RequestOptions::ON_STATS => function (TransferStats $stats) {
                var_dump($stats->getTransferTime());
            }
        ]
    );
} catch (ConnectException $e) {
    echo 'Message:' . $e->getMessage();
}
```

output:

```
float(40.042305)
Message:cURL error 28: Resolving timed out after 100 milliseconds
```

So is your issue resolved with the latest version?

**Comment by aidenko** [comment]
it might work with curl error 28, but definitely not working with curl error 7
