### ISSUE TITLE
Leading spaces in request headers are not handled correctly.

### ISSUE THREAD

**Issue by katmsft** [guzzle/guzzle#1870]
| Q            | A
| ------------ | ---
| Bug?         | yes
| New Feature? | no
| Version      | 6.2.1

#### Actual Behavior

If there are leading spaces in request headers, Guzzle will merge the header into previous header, causing an error. Also Guzzle does not trim or throw exception for trailing spaces in header's field name.

#### Expected Behavior

In [HTTP Spec 3.2.4](http://greenbytes.de/tech/webdav/draft-ietf-httpbis-p1-messaging-22.html#rfc.section.3.2.4.p.3), it is stated that, 

> No whitespace is allowed between the header field-name and colon.

So trailing spaces in header's field name should cause Guzzle to trim it, or better throw an exception, and leading spaces in field name should not cause header to be merged into previous header.

#### Steps to Reproduce

Code:
```
$headers0 = ['   doublespace   ' => '   doublespace   '];
$headers1 = ['nonspace' => 'nonspace'];
$headers2 = ['   frontspace' => '   frontspace'];
$headers3 = ['trailspace   ' => 'trailspace   '];
$request0 = new Request('GET', 'http://www.google.com', $headers0);
$request1 = new Request('GET', 'http://www.google.com', $headers1);
$request2 = new Request('GET', 'http://www.google.com', $headers2);
$request3 = new Request('GET', 'http://www.google.com', $headers3);
$client = new Client();

$result = $client->send($request0);
$result = $client->send($request1);
$result = $client->send($request2);
$result = $client->send($request3);
```

Result:
```
GET http://www.google.com/ HTTP/1.1
Host: www.google.com
User-Agent: GuzzleHttp/6.2.1 curl/7.49.1 PHP/5.5.38 doublespace   : doublespace

GET http://www.google.com/ HTTP/1.1
Host: www.google.com
User-Agent: GuzzleHttp/6.2.1 curl/7.49.1 PHP/5.5.38
nonspace: nonspace

GET http://www.google.com/ HTTP/1.1
Host: www.google.com
User-Agent: GuzzleHttp/6.2.1 curl/7.49.1 PHP/5.5.38 frontspace: frontspace

GET http://www.google.com/ HTTP/1.1
Host: www.google.com
User-Agent: GuzzleHttp/6.2.1 curl/7.49.1 PHP/5.5.38
trailspace   : trailspace
```

**Comment by katmsft** [comment]
After some debugging, this seems to be a cURL behavior. I do encourage Guzzle to throw exception when a leading/trailing white space is found in header.

**Comment by sagikazarmark** [comment]
Nice catch, thanks.

What do you think about simply trimming the values?

**Comment by katmsft** [comment]
IMHO we should not alter user's data without explicitly telling the user so, but it seems to be a huge breaking change because cURL is already secretly trimming the values. I would suggest Guzzle throw exceptions for leading/trailing white spaces in the field name, resolving the bug in cURL and violation of HTTP spec, while leaving the field value as is, letting cURL to handle the white spaces in them.

**Comment by adrianosferreira** [comment]
@sagikazarmark @gmponos I've added two PR for this, can you take a look?
https://github.com/guzzle/psr7/pull/307
https://github.com/guzzle/guzzle/pull/2540
