### ISSUE TITLE
Responses mixed up when using proxy, streams and cURL

### ISSUE THREAD

**Issue by willemstuursma** [guzzle/guzzle#1871]
| Q            | A
| ------------ | ---
| Bug?         | yes
| New Feature? | no
| Version      | 6.3

#### Actual Behavior

We are using Guzzle in production to call dozens of different domains from a queue. 

Our setup uses:

* One Guzzle client
* cURL (PHP 5.6.30 on Ubuntu)
* an HTTP proxy to proxy HTTP and HTTPS traffic
* Streams (specifically: `LimitStream`), as we limit the amount of bytes from responses we are interested in. We use streams only on a part of the requests. 

We don't use any async features. 

We've observed that the response retrieved from Guzzle in some cases contains many actual HTTP responses from different requests. 

So there would be a body, HTTP headers, another body, more HTTP headers, etc cetera and then finally the responses end with weird strings such as `HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 405HTTP/1.0 405HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 405HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.1 200HTTP/1.0 200HTTP/1.0 405HTTP/1.0 405HTTP/1.0 204HTTP/1.0 200HTTP/1.0 405HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 405HTTP/1.0 200HTTP/1.0 500HTTP/1.0 200HTTP/1.0 500HTTP/1.0 200HTTP/1.0 405HTTP/1.0 500HTTP/1.0 500HTTP/1.0 200HTTP/1.0 500HTTP/1.1 302HTTP/1.1 302HTTP/1.1 302HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 500HTTP/1.0 500HTTP/1.0 200HTTP/1.0 405HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 500HTTP/1.0 500HTTP/1.0 200HTTP/1.0 405HTTP/1.0 405HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.1 200HTTP/1.0 500HTTP/1.1 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.1 302HTTP/1.0 200HTTP/1.1 500HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 405HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.1 200HTTP/1.0 200HTTP/1.0 405HTTP/1.1 200HTTP/1.0 200HTTP/1.0 204HTTP/1.1 200HTTP/1.0 200HTTP/1.1 200HTTP/1.0 200HTTP/1.1 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.1 200HTTP/1.1 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.1 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 405HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.1 302HTTP/1.1 302HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.1 302HTTP/1.1 302HTTP/1.1 302HTTP/1.1 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 500HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 405HTTP/1.0 200HTTP/1.0 405HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 405HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 500HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 405HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.1 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.1 200HTTP/1.1 200HTTP/1.0 200HTTP/1.0 200HTTP/1.1 301HTTP/1.0 200HTTP/1.0 405HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 405HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 500HTTP/1.0 500HTTP/1.0 200HTTP/1.0 200HTTP/1.0 500HTTP/1.0 500HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 405HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 405HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 405HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 405HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 405HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 405HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 503HTTP/1.1 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 405HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.1 502HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 405HTTP/1.0 405HTTP/1.0 200HTTP/1.0 405HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 405HTTP/1.1 404HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 405HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 405HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 405HTTP/1.1 302HTTP/1.1 302HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200HTTP/1.0 200`

Some other responses we get from Guzzle just end with dozens of `H`, as if only a single byte could be written to the stream dozens of times.

#### Expected Behavior

We expect Guzzle not to mix up responses. 

#### Steps to Reproduce

We can't really reproduce it locally, so we expect that it has some high concurrency component.

I am sorry I don't have any actual steps to reproduce, but I can provide more information if you let me know what you need. 

We had been using a pure cURL solution without reusing cURL handles before, which worked perfectly. 

#### Possible Solutions

We are thinking there might be a problem with reusing cURL handles combined with using streams. I guess streaming from cURL is accomplished by using a write callback so maybe there is a lack of cleanup there?

**Comment by sagikazarmark** [comment]
Thanks for reporting this issue and being the first filling out the questionnaire 😉 

Can you give me a dummy example of your code (without sensitive data of course) so that I can (at least try to) reproduce the exact same problem?

Nevertheless I will check the cleanup stuff.

**Comment by willemstuursma** [comment]
This should be about it. 

```php
<?php

$guzzle_config = [
    \GuzzleHttp\RequestOptions::DECODE_CONTENT => 'deflate, gzip',
    \GuzzleHttp\RequestOptions::HEADERS        => [
        'User-Agent' => 'My Custom User Agent',
    ],
];

$guzzle_config[\GuzzleHttp\RequestOptions::PROXY] = [
    'http'  => "tcp://{$this->http_proxy_config->proxy_host}:{$this->http_proxy_config->proxy_port}",
    'https' => "tcp://{$this->http_proxy_config->proxy_host}:{$this->http_proxy_config->proxy_port}",
];

$client = new \GuzzleHttp\Client($guzzle_config);

while ($request = get_request_from_queue()) {

    /*
     * We use streams when we want to limit the body, so not on every request but on ±50%.
     */
    $needs_stream = mt_rand(0, 1);

    $options = [];
    $options[\GuzzleHttp\RequestOptions::STREAM] = $needs_stream;

    try {
        $response = $client->send(
            $request,
            $options
        );
    } catch (\GuzzleHttp\Exception\RequestException $e) {
        $response = $e->getResponse();
    } catch (\GuzzleHttp\Exception\GuzzleException $e) {
    }

    if ($needs_stream) {
        $body_stream = $response->getBody();
        $response_to_handle = (new \GuzzleHttp\Psr7\LimitStream($body_stream, 8192))->getContents();
    } else {
        $response_to_handle = $response->getContents();
    }
    // Further handle response
}

```

**Comment by sagikazarmark** [comment]
Thanks, I will try to give it a shot soon.

**Comment by alexeyshockov** [comment]
@willemstuursma, have you tried setting `CURLOPT_FRESH_CONNECT` to `true`? It disables connection caching in cURL and might help to get rid of such strange things...

**Comment by willemstuursma** [comment]
We haven't tried that yet, actually we _want_ to re-use connections. Will give it a try.

**Comment by alexeyshockov** [comment]
@willemstuursma, understand that. It's more for debugging: if works, then we know that the problem is in connections reusing.

Also a question: do you use secure (HTTPS) connections?

**Comment by willemstuursma** [comment]
> Also a question: do you use secure (HTTPS) connections?

We are using a mix, 80% HTTPS.

**Comment by alexeyshockov** [comment]
Then maybe [this note](http://www.sitecrafting.com/blog/php-curl-ssl-connection-timeout/) will help a bit. Anyway, looking forward to updates.
