### ISSUE TITLE
no namespace \GuzzleHttp\Client

### ISSUE THREAD

**Issue by vityapro** [guzzle/guzzle#1873]
| Q            | A
| ------------ | ---
| Bug?         | yes
| New Feature? | no
| Version      | Specific version or SHA of a commit
#### Actual Behavior

After install from composer cound find in package file Client.php

#### Steps to Reproduce

Just install from composer by command composer require guzzlehttp/guzzle:~6.0

#### Possible Solutions

Prabably update composer package

**Comment by kfreiman** [comment]
Show your code please

**Comment by vityapro** [comment]
What code you whant to see ?

**Comment by vityapro** [comment]
Sorry, I forgot to specify that the File Client.php is also missing

**Comment by Konafets** [comment]
Can you show your code which causes the error. How do you create the Guzzle client?

**Comment by vityapro** [comment]
As i see from this repo Guzzle Client.php is exist by default in guzzle/src/Client.php but when i install it from composer the are no such file in vendor/guzzlehttp/psr7/src also the are no ClientInterface.php for create Client.php This is my problem

**Comment by Konafets** [comment]
Why do you care about where it is located? Composer autoloads the lib into the `\GuzzleHttp\` namespace.

All you have to do is:
`$client = new \GuzzleHttp\Client();`

**Comment by vityapro** [comment]
Ok but i have exception when i try `new \GuzzleHttp\Client()` like no such namespace and zen i findout thet theare no such files as `ClientInterface.php` and `Client.php` witch use this namespace in Guzzle composer pakage at all!

**Comment by Konafets** [comment]
I cant nowhere found a dependency declaration to Guzzle in https://github.com/yiisoft/yii2-app-advanced nor in https://github.com/yiisoft/yii2. To me it looks like your mentioned framework uses an own HTTP Client implementation. https://github.com/yiisoft/yii2-httpclient/tree/2.0.4

**Comment by lestatmiao** [comment]
try `use Guzzle\Http\Client;`
and `$client = new Client([
        'timeout'  => 5.0,
    ]);`

**Comment by vityapro** [comment]
@Konafets  thanks i vill try to use it
