### ISSUE TITLE
How to get Request instance?

### ISSUE THREAD

**Issue by mikeevstropov** [guzzle/guzzle#1874]
| Q            | A
| ------------ | ---
| Bug?         | no
| New Feature? | no
| Version      | 6.3.0

#### What i do?

```php
$client = new GuzzleHttp\Client();

$response = $client->request('GET', 'https://github.com');

typeof($response); // GuzzleHttp\Psr7\Response
```
#### Question

How to get `GuzzleHttp\Psr7\Requset` if i'm using `request` method without creating it manual?

**Comment by alexeyshockov** [comment]
There is no way to get the request object in the code example you provided (`$response` doesn't contain a reference to the request).

You create a middleware and inject if to the stack (it has access to request and response).

**Comment by slince** [comment]
+1； may be we can add a method to get this;

```php
$request = $client->getLastRequest();
```

**Comment by gmponos** [comment]
@slince and @mikeevstropov you can get the last request by passing a History middleware inside the Handler, http://docs.guzzlephp.org/en/stable/testing.html#history-middleware

Note that History Middleware is mainly created for testing purposes.

Or another alternative would be to pass your own custom middleware.

http://docs.guzzlephp.org/en/stable/handlers-and-middleware.html#middleware

I don't think that having a function like `getLastRequest`  fits a the moment in guzzle. Thanks for your suggestion anyway.

**Comment by bdelamatre** [comment]
Can someone explain why this doesn't fit with Guzzle? I.e. What is the practical purpose of not having a connection between a request and response?

**Comment by bdelamatre** [comment]
In case anyone needs this functionality, here is an example trait that you can apply to a Guzzle Client to add this functionality.

```
use GuzzleHttp\Client;
use GuzzleHttp\Handler\CurlHandler;
use GuzzleHttp\HandlerStack;
use GuzzleHttp\Middleware;
use Psr\Http\Message\RequestInterface;

/**
 * @mixin Client
 */
trait LastRequestTrait
{
    /**
     * @var RequestInterface|null
     */
    public static $lastRequest;

    /**
     * @param array $config
     */
    public function __construct(array $config = [])
    {
        // make sure a handle stack exists
        if (! isset($config['handler'])) {
            $config['handler'] = HandlerStack::create(new CurlHandler());
        }

        // push our tap onto the handler
        $config['handler']->push(Middleware::tap(null, function (RequestInterface $request, array $options) {
            static::$lastRequest = $request;
        }));

        parent::__construct($config);
    }

    /**
     * @return RequestInterface|null
     */
    public function getLastRequest(): ?RequestInterface
    {
        return static::$lastRequest;
    }

    /**
     * @return string
     */
    public function getLastRequestUrl(): ?string
    {
        return (string)$this->getLastRequest()?->getUri();
    }
}
```
