### ISSUE TITLE
503 on get request

### ISSUE THREAD

**Issue by Kleinast** [guzzle/guzzle#1876]
| Q            | A
| ------------ | ---
| Bug?         | yes
| New Feature? | no
| Version      | v5.3.0

I use https://github.com/8p/GuzzleBundle with symfony, the guzzle client used is  v5.3.0 on my composer

#### Actual Behavior

My website crash, I've got 503 on my page, no exception catchable.

#### Expected Behavior

To have a response or at least a catchable exception.

#### Steps to Reproduce
```php
try {
    $response = $this->client->get($url);
} catch (\Exception $e) {
    $this->logger->error('Error on Api: ' . $e->getMessage());

    return null;
}
```

the same url on postman give me that:

StatusCode:
400 bad request

Headers:
Content-Type →text/html
Date →Mon, 17 Jul 2017 08:30:26 GMT
Server →Microsoft-IIS/8.5
TKEY →52313
TVALUE →Le contrat 52313 n'existe pas
Transfer-Encoding →chunked
Vary →Accept-Encoding

Body:
Requête incorrecte

**Comment by gmponos** [comment]
Out of the context of the issue this does not seem as a bug or possible bug in guzzle. It seems as a question more suitable for stackoverflow.

For support questions please use the channels that are listed here: https://github.com/guzzle/.github/blob/master/.github/SUPPORT.md
