### ISSUE TITLE
How can a wrap an exception into a BadResponseException?

### ISSUE THREAD

**Issue by gmponos** [guzzle/guzzle#1877]
| Q            | A
| ------------ | ---
| Bug?         | no
| New Feature? | no

#### Actual Behavior

Let's say that I have this code:

        try {
            $data = \GuzzleHttp\json_decode($response->getBody()->getContents(), true);
        } catch (\Exception $e) {
            throw BadResponseException::wrapException($request, $e);
        }

#### Expected Behavior

Need to return a BadResponseException but the above example will return a RequestException without the response.

Do you have any suggestion?

**Comment by Nyholm** [comment]
The `wrapException` belongs to the `RequestException`. You should use the constructor if you really want to throw a `BadResponseException`.
