### ISSUE TITLE
use Guzzle 6 to request Ruckus public API, but get Argument 3 passed to GuzzleHttp\Client::request() must be of the type array, boolean given

### ISSUE THREAD

**Issue by YanweiJiang** [guzzle/guzzle#1878]
| Q            | A
| ------------ | ---
| Bug?                  |yes
| New Feature?   |no
| Version             |6.3

#### Actual Behavior

I am using Guzzle 6 to retrieve data from Ruckus public API, but keeps getting 'Argument 3 passed to GuzzleHttp\Client::request() must be of the type array, boolean given' error.

#### Expected Behavior

Should be no error, because I passed the correct request data and it is working fine in Guzzle 5

#### Steps to Reproduce

```
use Illuminate\Console\Command;
use GuzzleHttp\Exception\GuzzleException;
use GuzzleHttp\Client;

/**
 * Execute the console command.
 *
 * @return mixed
 */
public function handle()
{
    $client = new Client();
    //to bypass local ssl certificate issuer
    $client->setDefaultOption('verify', false);
    $res = $client->request(
        'POST',
        $this->baseUrl . '/v4_0/session',
        [
            "headers" => [
                "Content-Type" => "application/json;charset=UTF-8"
            ],
            "json" => [
                "username" => "admin",
                "password" => "admin"
            ]
        ]
    );

    $headers = explode(';', $res->getHeader('Set-Cookie'));
    return current($headers);
}
```

#### Possible Solutions

Downgrade Guzzle to version 5. Since I am not using any packages, I don't think the Guzzle version could be the culprit here

**Comment by Nyholm** [comment]
Thank you for this issue. 
I think you made a small misstake. Try to remove `$client->setDefaultOption('verify', false);`. That is not a supported function call. 

Refer to the request options in the docs: http://docs.guzzlephp.org/en/stable/request-options.html#verify

**Comment by YanweiJiang** [comment]
It solved my problem. Thank you very much
