### ISSUE TITLE
Invalid JSON in FileCookieJar

### ISSUE THREAD

**Issue by greg0ire** [guzzle/guzzle#1883]
| Q            | A
| ------------ | ---
| Bug?         | yes
| New Feature? | no
| Version      | 5.3.1

#### Actual Behavior

Invalid json is saved in the file used as backend for `FileCookieJar`. I have had this issue in the past with what might be another version, I remember there were 2 extra brackets at the end of the file. I experienced the issue today again, but I arrived too late to see the invalid contents, which had already been replaced (which kind of makes me think that there might have been many concurrent writes). I know it was invalid because I got: Unable to parse JSON data: JSON_ERROR_SYNTAX - Syntax error, malformed JSON and it came from [here](https://github.com/guzzle/guzzle/blob/5.3/src/Cookie/FileCookieJar.php#L77).

#### Expected Behavior

A cookie jar containing valid JSON

#### Steps to Reproduce

I'm not sure how to reproduce this, I think it might happen with many concurrent writes.

#### Possible Solutions

Just prevent concurrent writes:

```diff
-        if (false === file_put_contents($filename, json_encode($json))) {
+        if (false === file_put_contents($filename, json_encode($json), LOCK_EX)) {
```

**Comment by jbilbo** [comment]
This exact same thing happened to me too. Also the extra `]` at the end. 
@greg0ire did your patch fix it for you?

**Comment by greg0ire** [comment]
I'm not sure I tried it on a production system, maybe you can try it?

**Comment by jbilbo** [comment]
I'm monitoring if it happens again (only happened once so far) and will try it if that's the case.

**Comment by sagikazarmark** [comment]
I think #2335 should fix this issue.

**Comment by greg0ire** [comment]
It's a backport of #1884 that I wrote a long time ago, so I think the issue is fixed. Let's close this and see if people reopen.
