### ISSUE TITLE
Extact applyOptions out of the client class

### ISSUE THREAD

**Issue by gmponos** [guzzle/guzzle#1886]
| Q            | A
| ------------ | ---
| Bug?         | no
| New Feature? | yes
| Version      | Specific version or SHA of a commit

#### Actual Behavior

Hello,

I would like to have a way of converting the RequestOptions of guzzle into a RequestInterface class. At the momemt the function that provides this kind of functionallity is [applyOptions](https://github.com/guzzle/guzzle/blob/master/src/Client.php#L291) which is inside Client class and it's private.

Would you consider extracting this function somewhere else and making it public. Either to a factory class or put it inside functions.php file?

The reason I am making this request is that I need to create a factory that will accept the guzzle options and return a RequestInterface.

So I need

```
Class GuzzleRequestFactory{

    public function createRequest($method, $uri, $options)
    {
         //return RequestInterface here;
    }
}
```

**Comment by mtdowling** [comment]
Yeah, a factory interface would be great. There was a similar issue here: https://github.com/guzzle/guzzle/issues/1455

An interesting consideration would also be if the implementation for this interface could potentially allow for customizable handling of each request option with the ability to add custom options.
