### ISSUE TITLE
Issues with guzzle when tmp size is limited

### ISSUE THREAD

**Issue by dhampik** [guzzle/guzzle#1887]
| Q            | A
| ------------ | ---
| Bug?         | yes
| New Feature? | no
| Version      | 6.x

#### Actual Behavior
We had a system with a limited size of tmp (was limited to several megabytes actually)
When requests via guzzle were performed and response body size was bigger than that limit, issue occurred.

If StreamHandler was used then response was just cut with no exception or error indication.
If CurlHandler was used then we received `cUrl error 23: Failed writing body (x != y)`.
Since we didn't know that we had a limited size of tmp it actually took several hours to debug it.

The issue is caused by CURLOPT_HEADERFUNCTION that handles the response. One thing that is also confusing, that I haven't found any documentation of how guzzle works with CURLOPT_HEADERFUNCTION, I had to debug guzzle code to figure that out. Another confusing thing was that simple curl_exec worked fine with the same conditions, since it did not use CURLOPT_HEADERFUNCTION and php://temp to capture the response.

#### Expected Behavior

In case if StreamHandler is used, exception should be raised.
In case if CurlHandler is used then maybe it's better raise more informative exceptions, rather then the standard one that we get from curl.

#### Steps to Reproduce

Well, basically problem is described above, I guess it could be reproduced with creation of small-sized tmp partion or something like that, can't say for sure how to reproduce it on a typical system. Unfortunately I can't reproduce it at the moment by myself, since the issue was observed on a remote server with a complex configuration and I don't currently have access to that server.

#### Possible Solutions

What I'd like to see as a solution is more verbose exceptions (especially for the StreamHandler case where were no exception at all) and more detailed documentation on how guzzle request handling is different from curl_exec.

I understand that this issue is a pretty rare thing, so if it's not worth fixing then at least I hope that this bug report will help someone who eventually face the same issue, so please at least do not remove it.

**Comment by sagikazarmark** [comment]
Thanks for reporting the issue. We already had some issues reported related to tmp where Guzzle writes it's streams to.

I will try to review this part of the code, and see if we have any other options when such limitation is applied to temp, but can't guarantee it's priority right now.

**Comment by mtdowling** [comment]
Agreed that the error messaging could be improved here.

To help with your immediate problem, an alternative to using temp streams is to use a memory stream (by setting the sink of the request).

**Comment by willemstuursma** [comment]
Could this be related to #1871?
