### ISSUE TITLE
Poor documentation re: status codes

### ISSUE THREAD

**Issue by udf2457** [guzzle/guzzle#1889]
"guzzlehttp/guzzle": "~6.0"

According to the almighty docs http://docs.guzzlephp.org/en/stable/quickstart.html

> You can get the status code and reason phrase of the response:
> $code = $response->getStatusCode(); // 200
> $reason = $response->getReasonPhrase(); // OK

But this is not exactly true is it ?

This:

```
$response = $client->request('POST',$tokenURL,$fields);
        if ($response->getStatusCode !=200) {
                return false;
        }
```

Yields:

> Undefined property: GuzzleHttp\Psr7\Response::$getStatusCode

If I print_r() the $response, the status code is there:

> GuzzleHttp\Psr7\Response Object ( [reasonPhrase:GuzzleHttp\Psr7\Response:private] => OK [statusCode:GuzzleHttp\Psr7\Response:private] => 200  etc.

**Comment by sagikazarmark** [comment]
`'$response->getStatusCode' !== '$response->getStatusCode()'`

`getStatusCode` is a method, not a property.
