### ISSUE TITLE
Error install package

### ISSUE THREAD

**Issue by guilherme90** [guzzle/guzzle#1891]
When i try install this package in command line "composer require guzzlehttp/guzzle", return the error:

> guzzlehttp/guzzle 6.3.0 requires guzzlehttp/psr7 ^1.4 -> no matching package found.

**Comment by githubgobi** [comment]
First You Have install Composer Follow the Url [(**https://medium.com/laravel-5-the-right-way/using-guzzlehttp-with-laravel-1dbea1f633da**)]  @guilherme90

**Comment by guilherme90** [comment]
Solved. Thanks
