### ISSUE TITLE
In order to call another application url , GET method working but Post method not working 

### ISSUE THREAD

**Issue by githubgobi** [guzzle/guzzle#1892]
$http = new GuzzleHttp\Client;

$response = $http->get('http://localhost/lab/new/api/user3');
    echo $response->getBody();
**-- Working Good--**
$request = $http->post('http://localhost/lab/ppa/api/user', [
        'form_params' => [
            'test' => 'test',
            'test1' => '11',
            'test4' => '3',
            'new' => '',
        ],
    ]);
** Its Not working **
It will call same application and shows the database error but corresponding database  used another **(ppa)** application.

ServerException in RequestException.php line 113:
Server error: `POST http://localhost/lab/ppa/api/use` resulted in a `500 Internal Server Error` response:
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'app2.users' doesn't exist (SQL: select * from (truncated...)

Database - app2 was current application database
post method database was app3 but its call app2 only.

**Comment by alexeyshockov** [comment]
IMO there is nothing to do with Guzzle, you need to check you application configs. Guzzle only takes care of HTTP responses, and it seems to be fine.

**Comment by githubgobi** [comment]
Okay thanks for your Help
