### ISSUE TITLE
[Bug?] Connection timeout settings do not work

### ISSUE THREAD

**Issue by inkrement** [guzzle/guzzle#1893]
#### Actual Behavior
I get several connection timeout messages like this one:

> Failed to connect to xxx port 443: Connection timed out [] []

#### Expected Behavior
But I tried to adjust the timeout (I even set it to "infinity"):

```php 
$client->getAsync('https://example.com/my/url', [
          'connect_timeout' => 0, // wait forever
          'read_timeout' => 50,
          'timeout' => 0, // wait forever
      ]);
```

Seems like the settings get ignored... are there any other options? (I use PHP7 and the default client - should be curl)

**Comment by tomzx** [comment]
This would need a little bit more information:
* Operating system
* PHP version
* Guzzle version

Thanks!

**Comment by inkrement** [comment]
For this specific problem, I do not use this lib anymore, but the OS was ubuntu 16.04 and the PHP version 7.0.

**Comment by feiffy** [comment]
+ Ubuntu 16.04
+ PHP7.0.30
+ guzzle 6.3 

Meet the same problem
