### ISSUE TITLE
Support cookies with ':' in name

### ISSUE THREAD

**Issue by poma** [guzzle/guzzle#1896]
I know that per RFC colon is not allowed in cookie names but most browsers correctly process them so some website use them. Such websites are unusable with Guzzle because it throws all cookies away.

In short, we need some way to override validation regex in `SetCookie->validate()`

**Comment by gmponos** [comment]
Duplicate of https://github.com/guzzle/guzzle/issues/1834 will close this and keep track on the other issue.
