### ISSUE TITLE
A way to get the body of a response straight into its original endpoint format

### ISSUE THREAD

**Issue by jasonsaayman** [guzzle/guzzle#1900]
| Q            | A
| ------------ | ---
| Bug?         | no
| New Feature? | yes
| Version      | 6.3.0

### Current issue

Currently, there seems to be no way to cast a response straight to Json, for example in the doc's it reads as below 

`$response = GuzzleHttp\get('http://httpbin.org/get');`
`echo $response->getBody();`
`// JSON string: { ... }`

The response is in Json format at this time, all I would like to do is push this to an array, however, I end up having to do something like below due to the way the `->getBody()` function works.

`$body = (string) $response->getBody();`
`json_decode($body)`

Would it therefore not just be easier to create a function where one could either get the Raw body (`->raw()`) of the response or call `->toJson()`?

**Comment by alexeyshockov** [comment]
See #1106 (it was discussed a few times already).

@sagikazarmark, maybe it's a good idea to add this info to [FAQ section](http://docs.guzzlephp.org/en/stable/faq.html)?

**Comment by jasonsaayman** [comment]
@alexeyshockov cool sorry didn't realize. Thanks

**Comment by sagikazarmark** [comment]
Sorry for late reply.

@alekseykuleshov Sure, sounds like a great idea. Would you like to give it a shot?

**Comment by alekseykuleshov** [comment]
@alexeyshockov Looks like the answer above is for you.

cc: @sagikazarmark

**Comment by typoworx-de** [comment]
Just for notice the ->toJson() method has been marked deprecated for Guzzle6 in favor of using PSR7 Response interface (loss of ::json() discussed here: https://github.com/guzzle/guzzle/issues/1106).

Surely it's just a workaround and not a final solid solution, but to avoid massive code-rewriting one could use this "hack" at least in Laravel which converts the Guzzle PSR7-Response back to the "old" Illuminate-Response supporting ::json() method!
https://gist.github.com/typoworx-de/248e63eb61df9ee2e09747c6873bd7f0

I'm shure the Guzzle team is working hard to find a better solution on this and therefore deleted my comment in #1106 pointing this "semi-solution" out. I had to do massive code rewriting just for a maybe temporary solution while the json()-method is re-implemented in Guzzle6.
