### ISSUE TITLE
cURL error 6: Could not resolv  http://curl.haxx.se/libcurl/c/libcurl-errors.html)

### ISSUE THREAD

**Issue by mohammad-69** [guzzle/guzzle#1901]
| Q            
| ------------ 
| Bug?    yes

| Version     6.2.3

#### Actual Behavior
Getting this error message when trying to work with passport in my project on my local server.

CurlFactory.php line 186:
`cURL error 6: Could not resolve host: api.project.local (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)`

#### Expected Behavior
Get oauth authentication tokens after calling post url to project/oauth/token
```

{
    "token_type": "Bearer",
    "expires_in": 518399,
    "access_token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImp0aSI6Ijk0MWU3Y2Q2Y2I1ZTEyYmYyYzAzYTIzY2I1YWM5YjY3YjI0MmU2NTUwOWRhODVlZTMxNzc3MjIwODA3ZTA2ZGY1YWIwYjMzNDg2MDA2MTZlIn0.eyJhdWQiOiIxIiwianRpIjoiOTQxZTdjZDZjYjVlMTJiZjJjMDNhMjNjYjVhYzliNjdiMjQyZTY1NTA5ZGE4NWVlMzE3NzcyMjA-rkLpvJhuju4Qlo0QNjsXUUHXq6GyqqiQTNa2d0IUsWdAOSLsy1bMu4Z2ga_Jj1L1ThwbDOfy7kE4_5SDfKKIyKXO_-iw",
    "refresh_token": "L8p2NAqRZfi1fP1XyO3NW36dCqa6HZJWgNKkuR8IMz2LJe5711nRHPMP734caln1+8m+GC6K79yTjRjru01iR7LKP1CCseixQ8mkzXWZb+roQv32qdkXVSeCzObecOI2ZWq+l1KNs12NA3KIZJ4bS0N2rOYxlw3KTNx55uydH13vmanbeXIpym0ha8op0M9s9HvwPc+dJUhjL20JzDGCcyuhciGIe6CTKyBuqi4dNA8tIeALLPSSqtvd0QsRWCWTVBL72RVeEeIq/4kFppE="
}

```

#### Steps to Reproduce
install laravel 5.3 
install passport package 
extract laravel auth scaffold to app directory.
put this line of code inside of authentication controller when user is logged in : 
path = Project/app/Foundation/Auth/AuthenticatesUsers.php

```
 $http = new Client;

            $response = $http->post('Project.local/oauth/token', [
                'form_params' => [
                    'grant_type' => 'password',
                    'client_id' => 1,
                    'client_secret' => 'xKqNbzcXyjySg20nVuVLw5nk5PAMhFQOQwRTeTjd',
                    'username' => $userobject['email'],
                    'password' => $userobject['password'],
                    'scope' => '',
                ],
            ]);


```

On some servers it works, on some it doesn't and I don't know what is the cause. the server I'm facing problem right now is ubuntu14.04 server with php5.6 and apache2 and mysql5.5

**Comment by mohammad-69** [comment]
I've found the solution for this problem, This problem happens when you have defined a host name for your project, and in laravel config file app name is host name like : 

`'APP_PATH' =>'http://api.project.local',`

To solve this problem you need to define this host name on any server you have in hosts file like : 

> sudo nano /etc/hosts : 

`192.168.1.136     api.project.local`

**Comment by ultrasamad** [comment]
@mohammad-69 I'm also currently facing the same problem using laravel with guzzle. It works fine on one of my Machines which has homestead installed, but another one I'm XAMPP it is not working and giving the exact error message as above.

**Comment by ultrasamad** [comment]
It was actually due to a invalid reference to my `base_url` in my `.env` file.

**Comment by ultrasamad** [comment]
@jatin222 As I said, mine was an invalid reference to my `base_url` in my `.env` file. You can try that to see if you issue is resolved.

**Comment by eduardocruz** [comment]
I just had a similar error in Laravel 5.7, trying to connect to Mailgun. I just needed to remove the `https`:// from the endpoint url.

**Comment by erroronfire** [comment]
> [Solved]
> I've found the solution for this problem, This problem happens when you have defined a host name for your project, and in laravel config file app name is host name like :
> 
> `'APP_PATH' =>'http://api.project.local',`
> 
> To solve this problem you need to define this host name on any server you have in hosts file like :
> 
> > sudo nano /etc/hosts :
> 
> `192.168.1.136 api.project.local`

This Solved.

This error appears when you get BASE_URL from some file, and that variable does not exist in that file.

**Comment by elamigosam** [comment]
I am using phrets (https://github.com/troydavisson/PHRETS) with PHP 7.2.19-0ubuntu0.18.04.2 
I keep getting the same error: Fatal error: Uncaught GuzzleHttp\Exception\ConnectException: cURL error 6: Could not resolve host: config 
I tried:
static entry on /etc/hosts
remove https:// from url, 
nothing seems to work, any ideas?

**Comment by steve-kouna** [comment]
j'utilise symfony 3.4

`{
    "code": 500,
    "message": "cURL error 6: Could not resolve host: preprod.ap.api.koona.biz (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)"
}`
une idée?
Merci

**Comment by Prince-254** [comment]
> [Solved]
> I've found the solution for this problem, This problem happens when you have defined a host name for your project, and in laravel config file app name is host name like :
> 
> `'APP_PATH' =>'http://api.project.local',`
> 
> To solve this problem you need to define this host name on any server you have in hosts file like :
> 
> > sudo nano /etc/hosts :
> 
> `192.168.1.136 api.project.local`

As pointed out change your `APP_URL=` .env entry. It did work for me on Laravel 7.2

**Comment by Prince-254** [comment]
> I am using phrets (https://github.com/troydavisson/PHRETS) with PHP 7.2.19-0ubuntu0.18.04.2
> I keep getting the same error: Fatal error: Uncaught GuzzleHttp\Exception\ConnectException: cURL error 6: Could not resolve host: config
> I tried:
> static entry on /etc/hosts
> remove https:// from url,
> nothing seems to work, any ideas?

As pointed out change your APP_URL= .env entry. It did work for me on Laravel 7.2

**Comment by chiptu** [comment]
Looks dumb but in my case i just forgot to restart the worker on the distant server . If you didn't restart the queu worker with `php artisan queu:restart` , the job can't reach your new .env.

**Comment by willenrocha** [comment]
php artisan route:clear
php artisan config:clear
php artisan cache:clear
