### ISSUE TITLE
 ErrorException: stream_get_contents

### ISSUE THREAD

**Issue by mojtabakhani** [guzzle/guzzle#1902]
| Q            | A
| ------------ | ---
| Bug?        yes
| New Feature? | no
| Version      | 6.3

#### Actual Behavior

crash  service when visit a link and show this:
[2017-08-27 04:19:09] local.ERROR: ErrorException: stream_get_contents(): supplied resource is not a valid stream resource in /var/www/topco/vendor/guzzlehttp/psr7/src/Stream.php:102

#### Expected Behavior

my app actually is a service that visit some link in long time, until don,t stop must be work.
some time possible no visit because no anything in visit queue , but service is ran.
since a visit coming in queue must be visited .

my problem is
when queue is empty for long time (for exp: 10h or more ) , and coming new visit service crashed and show above error.

tanx.

**Comment by Nyholm** [comment]
It seams like you are trying to open a resource that has been closed since you waited a long time. 

I think it would be better to save that stream temporarily in a cache when you receive it and then read if from cache after 10h.
