### ISSUE TITLE
How to handle the promise? and How to return it? can you explain clearly?

### ISSUE THREAD

**Issue by venkatsamuthiram** [guzzle/guzzle#1906]
guzzlehttp/guzzle

$promise = $client->sendAsync($request);
//You can force an asynchronous response to complete using the wait() method of the returned promise
$response = $promise->wait();
$promiseResult = $promise->then(function ($response) {
$responseArray = [];
$responseArray += ['statusCode' => $response->getStatusCode()];
$responseArray += ['reasonPhrase' => $response->getReasonPhrase()];
$responseArray += ['body' => json_decode($response->getBody())];
$result = json_encode($responseArray);
var_dump($result);
return $result;
});
This is my Code, How? I return my Response data?

**Comment by Kvizer** [comment]
```
$client = new GuzzleHttp\Client;

$request = new Request('GET', 'www.github.com');

$promise = $client->sendAsync($request);

$promiseResult = $promise->then(function ($response) {
    $responseArray = [];
    $responseArray []= ['statusCode' => $response->getStatusCode()];
    $responseArray []= ['reasonPhrase' => $response->getReasonPhrase()];
    $responseArray []= ['body' => ($response->getBody()->getContents())];
    $result = json_encode($responseArray);
    dump($result);
    return $result;
});

$response = $promise->wait();
```

> [{"statusCode":200},{"reasonPhrase":"OK"},{"body":"\n\n\n\n\n<!DOCTYPE html>\n<html lang=\"en\">\n .....

**Comment by venkatsamuthiram** [comment]
Thanks @Kvizer
