### ISSUE TITLE
Undefined Offset: 1 in /guzzle/src/Handler/EasyHandle.php

### ISSUE THREAD

**Issue by Vladnev** [guzzle/guzzle#1909]
**Bug**
**Version:** 6.3.0

When I try to take headers from one of urls(I think it can be repeat) has error:
>Undefined offset: 1 in file: vendor/guzzlehttp/guzzle/src/Handler/EasyHandle.php line: 77

**Call example with url:**
```php
$client->head('http://orennahum.dyndns.org/');
```
**Debug:**
```php
$this->headers = [
  0 => "HTTP/1.0"
  1 => "Server: Quick 'n Easy Web Server"
  2 => "Connection: Keep-Alive"
  3 => "Content-Length: 0"
  4 => "Set-Cookie: SESSIONID=00000230; path=/;version=1"
  5 => "Date: Wed, 06 Sep 2017 08:06:42 GMT"
]
```

**After explode ofcourse we have only one header with zero offset code:**
```php
$startLine = explode(' ', array_shift($this->headers), 3);
```

**So we need to add checking for this code: **
```php
$this->response = new Response(
            $startLine[1],
            $headers,
            $this->sink,
            substr($startLine[0], 5),
            isset($startLine[2]) ? (string) $startLine[2] : null
        );
```

**Comment by alexeyshockov** [comment]
Seems like your server doesn't follow [HTTP protocol](https://www.w3.org/Protocols/rfc2616/rfc2616-sec6.html), because the status line must include status code.

> 6.1 Status-Line
>
>The first line of a Response message is the Status-Line, consisting of the protocol version followed by a numeric status code and its associated textual phrase, with each element separated by SP characters. No CR or LF is allowed except in the final CRLF sequence.
>
>     Status-Line = HTTP-Version SP Status-Code SP Reason-Phrase CRLF

Because of that it doesn't look like a bug.

**Comment by Vladnev** [comment]
I agree - that server doesn`t follow HTTP protocol.
And first line is invalid.
But this isn`t a occasion for package fall, is it?

**Comment by alexeyshockov** [comment]
It is. There are a lot of variants where a server is able not to follow the spec, so consider all of them in the code is a bad idea, IMO. I mean that you cannot assume that a status line without a code always means `200 OK`.

BTW, the error itself can be improved (throwing a parsing exception instead of PHP's notice).

**Comment by Vladnev** [comment]
About responses not following specification - yes we doesn`t need consider all of troubles - but in api do you check what you recive or you say - it`s ok we agreed.

I think code should not breaks if someone not follows spec :)

I agree about that we cannot be sure that status code is 200, and exception good option.

What you think about have a choise: get exception or response with zero code?
