### ISSUE TITLE
ServerException raised on 503 error

### ISSUE THREAD

**Issue by Carmageddon** [guzzle/guzzle#1912]
| Q            | A
| ------------ | ---
| Bug?         | yes
| New Feature? | no
| Version      | 6.3.0

#### Actual Behavior

Guzzle throws exception:
GuzzleHttp\Exception\ServerException: Server error: 'GET .....'
 resulted in a `503 Service Unavailable` response:
{"errors":[{"message":"Runtime failure","detailedMessage":"main.js:37 ReferenceError: \"resString\" is not defined in ma (truncated...)

#### Expected Behavior

No exception to be raised, so that I can perform:
$resCode = $this->httpResult->getStatusCode();
and $resText = (string) $this->httpResult->getBody();

And then handle the code and response as I see fit.

#### Steps to Reproduce

Generate API mock that returns 503 error with some text whatever, execute and try to getStatusCode - you cant because exception is raised before that

#### Possible Solutions

I looked at the docs, and there is no toggle, flag or something to prevent this behaviour, at the very least there should be a flag to prevent such exceptions.

**Comment by alexeyshockov** [comment]
Please, look at [`http_errors` option](http://docs.guzzlephp.org/en/stable/request-options.html#http-errors). You can get the desired behaviour using it.

**Comment by Carmageddon** [comment]
You are right, thank you! I didnt understand the docs structure at the late hour. Not used for docs having a separate page only for single method parameters, was looking for something more in style of PHP docs, where parameters are all layed out in the method's doc page and not separately.
