### ISSUE TITLE
Multipart `Content-Type` vs. `content-type`

### ISSUE THREAD

**Issue by borekb** [guzzle/guzzle#1913]
Our code creates a client like this:

```php
$client = new Client([
    'base_uri' => $this->serverUrl,
    'headers' => [
        'content-type' => 'text/plain',
        'x-internal-header' => $value,
    ]
]);
```

Note the lower-case HTTP headers – this shouldn't matter in HTTP/1.1 and is necessary in HTTP/2 (admittedly, we're future-proofing a bit).

It causes this code:

https://github.com/guzzle/guzzle/blob/dfd01d60a38cf7e16b3456d4b1d7c10033b929c0/src/Client.php#L383-L387

to store into `$options['_conditional']` both `content-type` and `Content-Type`:

```
Array
(
    [content-type] => text/plain
    [Content-Type] => multipart/form-data; ...
)
```

This than causes problem here:

https://github.com/guzzle/guzzle/blob/dfd01d60a38cf7e16b3456d4b1d7c10033b929c0/src/Client.php#L393-L397

where only `content-type` (`text/plain`) makes is to the final headers array, breaking the app.

**Comment by alexeyshockov** [comment]
Looks like a bug. IMO Guzzle should normalize headers inside to eliminate such kind of problems.
