### ISSUE TITLE
RuntimeException when providing Google Cloud Storage stream wrapper resource as sink option

### ISSUE THREAD

**Issue by anaspk** [guzzle/guzzle#1917]
My PHP project is deployed on Google App Engine PHP Standard Environment. I am trying to download remote files and store them in Google Cloud Storage buckets. In order to support potentially very large files, I am providing a writable file stream resource to Guzzle in the 'sink' request option so that I don't have to keep the full file in memory before writing it to Google Cloud Storage. Local filesystem is not writable on Google App Engine Standard Environment. So I can't write the downloaded file to a temporary local file before copying it to Google Cloud Storage.

| Q            | A
| ------------ | ---
| Bug?         | yes
| New Feature? | no
| Version      | 6.3.0

#### Actual Behavior

RuntimeException: Unable to seek to stream position 0 with whence 0

![image](https://user-images.githubusercontent.com/1071973/30536559-b5391a92-9c7f-11e7-836a-f77711972f50.png)

![image](https://user-images.githubusercontent.com/1071973/30536581-cb3366ea-9c7f-11e7-8225-f0d53fac70f0.png)

#### Expected Behavior

Downloaded file should be successfully written to Google Cloud Storage bucket without raising any exception.

#### Steps to Reproduce

* Create a new composer project and add guzzle as dependency.
* Create a new project on Google Cloud Platform.
* Create a new Google Cloud Storage bucket in this project.
* Paste the following code snippet in one of your PHP files, after replacing the <placeholders> with actual values.
```php
use GuzzleHttp\Client;

$filePath = 'gs://<bucket name>/<object name to write>';
$resource = fopen($filePath, 'w');
$client->request('GET', '<URL of a publicly accessible file>', ['sink' => $resource]);
```
* Deploy your project on a Google App Engine (PHP Standard Environment) instance in the same project so that it has access to the Cloud Storage bucket.
* Access a URL in your deployment that will trigger the above provided code snippet.

#### Possible Cause and Solution

Here are my findings so far. The "gs://" stream wrapper provided by Google on App Engine to access Cloud Storage supports the "fseek" function only on files opened in read mode, as noted [here](https://cloud.google.com/appengine/docs/standard/php/googlestorage/advanced#php_filesystem_functions_support_on_google_cloud_storage). In my use case, I have to open the file in write mode so that Guzzle can write the downloaded file to it. That's why exception occurs at [this line](https://github.com/guzzle/guzzle/blob/dfd01d60a38cf7e16b3456d4b1d7c10033b929c0/src/Handler/StreamHandler.php#L216) 

Can someone please provide more insight into why we are seeking to position 0 of sink resource? What would be the best approach to achieve my desired behavior i.e. stream a remote file directly to a Google Cloud Storage object?

Also, if I check on the Cloud Storage console, the file is successfully stored there. File size is same as the source. So, while a more "correct" solution is figured out, is it safe for me to just comment out the problematic seek() call on line 216 of StreamHandler.php to avoid this exception?

**Comment by alexeyshockov** [comment]
Looks like not as a bug, but as a feature "to rewind the destination stream to the beginning after copying". In the old code I see [a proof of this](https://github.com/guzzle/guzzle/commit/1a9ad6b55368283aaf73672a519e5177530991fb#diff-1ec0793e916ece24b0b0c18df5ebb223R120).

BTW, I haven't found anything about this in the docs ([web](http://docs.guzzlephp.org/en/stable/request-options.html#sink) and phpDoc).

@mtdowling, @sagikazarmark, do you know why this `->seek(0)` is there?

**Comment by alexeyshockov** [comment]
IMO I would deprecate this feature and remove it in 7.0.

**Comment by dbu** [comment]
ran into this as well, doing a simple POST to a web service and having `RequestOptions::SINK => STDOUT`. i am not sure what changed as it worked at some point and now does not, even though we did not update guzzle in between. maybe php versions?

anyways, rewrote to 
```php
$stream = $response->getBody();
while (!$stream->eof()) {
    $output->write($stream->read(100000));
}
```

which seems to work fine.
