### ISSUE TITLE
Create a FileCookieJar from CookieJar

### ISSUE THREAD

**Issue by ciis0** [guzzle/guzzle#1918]
| Q            | A
| ------------ | ---
| Bug?         | no
| New Feature? | yes
| Version      |  dfd01d6 (master)

#### Actual Behavior

`GuzzleHttp\Cookies\CookieJar` has `fromArray(...)` while `GuzzleHttp\CookieFileCookieJar` has not.

#### Expected Behavior / Possible Solutions

Either extend `FileCookieJar` to also support `fromArray(...)` or be able to create a `FileCookieJar` from a `CookieJar`.

#### Steps to Reproduce

Try to create an `FileCookieJar` with cookies from an array w/o re-implementing `CookieJar.fromArray(...)`.

Thx!

**Comment by milsanore** [comment]
+1
