### ISSUE TITLE
Add `bearer` as an auth option

### ISSUE THREAD

**Issue by ghost** [guzzle/guzzle#1919]
Is there any reason why this is still not an option for the auth config options?

**Comment by piotr-cz** [comment]
Can be done as adding new case [in Client](https://github.com/guzzle/guzzle/blob/6.3.0/src/Client.php#L346-L358):

```php
case 'bearer':
    $modify['set_headers']['Authorization'] = 'Bearer ' . $value[0];
    break;
```

usage:
```php
$response = $this->httpClient->request('GET', 'http://www.google.com', [
    GuzzleHttp\RequestOptions::AUTH => ['<token>', null, 'Bearer']
]);
```

**Comment by gmponos** [comment]
closing https://github.com/guzzle/guzzle/pull/2568#issuecomment-650544967
