### ISSUE TITLE
json issue

### ISSUE THREAD

**Issue by artickc** [guzzle/guzzle#1921]
> Case 1:

```
$array = json_decode($response1->getBody()->getContents(), true);
echo $response1->getBody()->getContents();//
var_dump($array); // NULL
echo json_last_error_msg();//Syntax error
```

> Case 2:

```
$array = json_decode($response1->getBody(), true);
echo $response1->getBody();//{"status":"false","message":"Site not found"}
var_dump($array); // NULL
echo json_last_error_msg();//Syntax error
```
--------------------------------------------------------------------------------------------------

> php version 7.1
> Guzlle version 6.x installed with composer 
> Server centos 7 x64

**Comment by artickc** [comment]
the same problem in guzzle 5
`Uncaught GuzzleHttp\Exception\ParseException: Unable to parse JSON data: JSON_ERROR_SYNTAX - Syntax error, malformed JSON  `

**Comment by sagikazarmark** [comment]
First of all: This is unlikely a Guzzle error. Try the following:

``` php
$body = (string)$response1->getBody();
$array = json_decode($body, true);
echo $body;//{"status":"false","message":"Site not found"}
var_dump($array); // NULL
echo json_last_error_msg();//Syntax error
```

Secondly: don't use `getContents` subsequently. I really have to write a blog post about it: it only reads the remainder of the stream, once you read it, it won't return anything.

**Comment by artickc** [comment]
Sorry the problem isn't in guzzle, the site that i was parsed haved the hiden symbol for security reasons xD.
After changing the encode with iconv , she was appear :D 
п»ї{"status":false,"message":"Site not found"}. For first time i see something like this, but i remember this for long time, sorry for post and for your wasted time.
