### ISSUE TITLE
handle the error of cURL error 6: Could not resolve host

### ISSUE THREAD

**Issue by aminyazdanpanah** [guzzle/guzzle#1925]
Hi there,
I'm trying to run the flowing code:

>         try{
>             if($client->request('GET',$url, ['sink' => public_path('videos/test.mp4')])){
>                 var_dump('ok');
>             }else{
>                 var_dump('error');
>             }
>         }catch (BadResponseException $e){
>            var_dump(throwException($e));
>         }

This code works when the $url is valid but when $url is not valid I get the following error:
`cURL error 6: Could not resolve host: "WRONG_URL" (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)`

However, I use try catch to avoid this error but it's not working for me!
what should I do? any suggestion?

**Comment by sagikazarmark** [comment]
Try catching `GuzzleHttp\Exception\GuzzleException`.

**Comment by aminyazdanpanah** [comment]
It works!
Thanks 👍

**Comment by MPParsley** [comment]
GuzzleException is now an interface, you can catch it using `GuzzleHttp\Exception\RequestException`.

**Comment by sagikazarmark** [comment]
@MPParsley you can catch the interface itself as well.

**Comment by fgagneten** [comment]
The error for me was related to Laravel (my config cache). Just doing 

    php artisan config:clear
was the solution

**Comment by kaviyarasansadasivam** [comment]
> GuzzleException is now an interface, you can catch it using `GuzzleHttp\Exception\RequestException`.
Can I able to catch through ConnectException ?
