### ISSUE TITLE
When guzzle run from Laravel's "artisan tinker", Tinker exits with no message

### ISSUE THREAD

**Issue by dsandber** [guzzle/guzzle#1926]
| Q            | A
| ------------ | ---
| Bug?         |  Yes
| New Feature? | No
| Version      | 6.3.0

#### Actual Behavior

What is the actual behavior?

Tinker exits with no message

#### Expected Behavior

Guzzle should run properly

#### Steps to Reproduce

What are the steps to reproduce this bug? Please add code examples,
screenshots or links to GitHub repositories that reproduce the problem.

My code is calling GuzzleHttp\Client __call with arguments:

method: "post"
args: ["https:\/\/hooks.slack.com\/services\/PRIVATE\/PRIVATE\/PRIVATE",{"json":{"text":"MESSAGE","attachments":[]}}]

Tinker then exits with no message.  I'm not sure how to debug further.   The code works fine if not run from Tinker.  Maybe an issue with STDIN or STDOUT being redirected?  I'm running on a Mac with Laravel 5.4.

#### Possible Solutions

Any debugging help would be appreciated -- for example, how do I see the curl command-line being run, or where should I put a breakpoint to see what is happening?

**Comment by alexeyshockov** [comment]
Have you tried running tinker with `-vvv` option? Is `error_reporting` is configured to show errors (in PHP/Laravel)?

**Comment by dsandber** [comment]
tmp.php is file that looks like this:

```
<?php

error_reporting(E_ALL);

$client = new GuzzleHttp\Client(['base_uri' => 'https://www.google.com/']);
$response = $client->request('GET', '/');
print "Finished\n";
```

If I run it from the command line like this:

```
screen:lms dsandber$ ./artisan script tmp.php
```

I get the output "Finished" and the request is made. 

If I run it from tinker like this:

```
screen:lms dsandber$ php artisan tinker -vvvv
```

I get these results:

```
Psy Shell v0.8.11 (PHP 7.1.1 — cli) by Justin Hileman
>>> $client = new GuzzleHttp\Client(['base_uri' => 'https://www.google.com/']);
=> GuzzleHttp\Client {#893}
>>> $response = $client->request('GET', '/');
screen:lms dsandber$
```

No request is made and tinker has exited.

**Comment by alfonsobries** [comment]
same issue here

**Comment by dsandber** [comment]
Confirmed -- only happens w/HTTPS

**Comment by TheDeadCode** [comment]
Just saying this is still an issue

**Comment by kejwmen** [comment]
sounds like laravel/psysh issue, not guzzle's.

**Comment by hassanazimi** [comment]
If you are using PHP 7.3 installed by homebrew on Mojave, try creating a config file at ~/.config/psysh/config.php if not already there:
```
<?php
return [
  'usePcntl' => false,
]; 
```
Source: https://github.com/bobthecow/psysh/issues/540#issuecomment-446480753
