### ISSUE TITLE
[Question] Does Guzzle cache responses?

### ISSUE THREAD

**Issue by TKafassis** [guzzle/guzzle#1928]
Subsequent requests (5500+) respond way too fast, in 15 seconds, after the first time, which took 1 minute, so I was wondering if this is Guzzle's doing?

**Comment by sagikazarmark** [comment]
Nope, definitely not (by default), it might be some kind of proxy on your network, or some kind of lag for the first time.

**Comment by Nokim** [comment]
That should be caching on server side. I definitely would implement the one if processing request takes 1 minute and more.

**Comment by sagikazarmark** [comment]
@Nokim Client side caching is also an accepted thing to do. In this case caching in Guzzle would be client side caching from the requests point of view, no matter it's also happening on server side.

But I don't think it's related to this issue.

Do you have any more information @TKafassis ? Can this issue be closed?
