### ISSUE TITLE
Wrong topic on github

### ISSUE THREAD

**Issue by insign** [guzzle/guzzle#1929]
| Q            | A
| ------------ | ---
| Bug?         | no
| New Feature? | no

On github page, the topic used are wrong... Search for 'http clients', I used the topic (tag) 'http-client' and found many alternatives, but Guzzle not in. Guzzle is the one that are using 'httpclient' (without dash).

Check the links: 
https://github.com/search?utf8=✓&q=topic%3Ahttpclient&type=Repositories (104 results)
https://github.com/search?utf8=%E2%9C%93&q=topic%3Ahttp-client&type=Repositories (444 results)

**Comment by Tobion** [comment]
Added http-client to the topics.
