### ISSUE TITLE
Weird issues with an https request that breaks

### ISSUE THREAD

**Issue by TNAJanssen** [guzzle/guzzle#1930]
| Q            | A
| ------------ | ---
| Bug?         |yes
| New Feature? | no
| Version      | 6.3.0

#### Actual Behavior

Makes an request to https://us16.api.mailchimp.com/3.0/batches but somehow using http/1.1, HTTPS and cURL brakes the request and the server responds with 400 bad request with the message Your browser sent a request that this server could not understand.

It works when doing one of the following things:

- send request using HTTP/1.0 is works
- using HTTP instead of HTTPS
- Sending the same request two times directly after each other
- Using StreamHandler instead of CurlHandler

#### Expected Behavior

Make a request to https://us16.api.mailchimp.com/3.0/batches and get a correct response back

#### Steps to Reproduce

Creating a request to the above url using default http version (1.1), HTTPS, (Method doesn't matter) and using the curl handler. 

The body content of the request is send using a stream from httplug (www.httplug.io), when I switch within httplug to their curl handler instead of guzzle it also works.

**Comment by ingberrio** [comment]
> Q	A
> Bug?	yes
> New Feature?	no
> Version	6.3.0
> #### Actual Behavior
> Makes an request to https://us16.api.mailchimp.com/3.0/batches but somehow using http/1.1, HTTPS and cURL brakes the request and the server responds with 400 bad request with the message Your browser sent a request that this server could not understand.
> 
> It works when doing one of the following things:
> 
> * send request using HTTP/1.0 is works
> * using HTTP instead of HTTPS
> * Sending the same request two times directly after each other
> * Using StreamHandler instead of CurlHandler
> 
> #### Expected Behavior
> Make a request to https://us16.api.mailchimp.com/3.0/batches and get a correct response back
> 
> #### Steps to Reproduce
> Creating a request to the above url using default http version (1.1), HTTPS, (Method doesn't matter) and using the curl handler.
> 
> The body content of the request is send using a stream from httplug ([www.httplug.io](http://www.httplug.io)), when I switch within httplug to their curl handler instead of guzzle it also works.

I get some error with cURL, when godaddy configurate my SSL CA mi connection broken and  im Using StreamHandler instead of CurlHandler, thats works for me!
