### ISSUE TITLE
Debug option returns strange data

### ISSUE THREAD

**Issue by LastDragon-ru** [guzzle/guzzle#1931]
Hello. I'm trying use guzzle 6.3 with `debug=true` 

```php
        $fp = fopen('php://temp', 'r+');

        /** @var \GuzzleHttp\Message\ResponseInterface $response */
        $response = (new HttpClient())->get('http://127.0.0.1', [
            'debug' => $fp,
        ]);

        fseek($fp, 0);
        var_dump(stream_get_contents($fp));
```

but I see only
```
<GET http://127.0.0.1> [CONNECT] 
<GET http://127.0.0.1> [FILE_SIZE_IS] message: "Content-Length: 46" bytes_max: "46" 
<GET http://127.0.0.1> [MIME_TYPE_IS] message: "text/html" 
<GET http://127.0.0.1> [PROGRESS] bytes_max: "46" 
```

I'm doing something wrong or this is a bug?

**Comment by alexeyshockov** [comment]
Seems OK. What do you expect?

BTW, it also seems that you don't have cURL extension installed, so Guzzle uses PHP's stream wrappers as the handler. In case you expect cURL style output...

**Comment by LastDragon-ru** [comment]
> BTW, it also seems that you don't have cURL extension installed,

Yes, you are right. I've installed it and see the info now. Thank you. 

As I know the streams also allow receive response headers and body, I think will be great dump this data in debug mode (IMHO it will be more useful than `[PROGRESS] bytes_transferred: "8192" bytes_max: "92984"`).

**Comment by alexeyshockov** [comment]
Well, cURL doesn't print the body in debug either.

But agree, more details would be better, of course. You can add them for the PHP's streams handler and send a PR ;)
