### ISSUE TITLE
Content length for body options.

### ISSUE THREAD

**Issue by shulcsm** [guzzle/guzzle#1934]
| Q            | A
| ------------ | ---
| Bug?         | yes
| New Feature? | no
| Version      | head

#### Actual Behavior
Sending `json` as body option results in chunked  request. Probably true for other body options.

#### Expected Behavior

What is the behavior you expect?
Buffered request

#### Possible Solutions
Set content length header here
https://github.com/guzzle/guzzle/blob/master/src/Client.php#L313

**Comment by LiXunGuan** [comment]
``json`` option value is null,but content length is not zero
https://github.com/guzzle/guzzle/blob/master/src/Client.php#L313
