### ISSUE TITLE
Question: How long will PHP5 be supported`?

### ISSUE THREAD

**Issue by GBeushausen** [guzzle/guzzle#1936]

**Comment by alexeyshockov** [comment]
The next major release is more likely to support PHP versions starting from 7. But there are no plans for this release (no plans that I'm aware of).

For 6.x versions of Guzzle the minimal required PHP version is 5.5.

**Comment by sagikazarmark** [comment]
There were plans to drop 5.5 support and use 5.6. I don't think the 6.x release line will lose support for PHP 5.x

**Comment by alexeyshockov** [comment]
@sagikazarmark, but isn't it a BC break? Maybe better to release 7.0 with new requirements then?

**Comment by sagikazarmark** [comment]
No, I don't think it is or at least it's a bit subjective. Composer will simply not resolve a version if you don't have the required PHP version installed.

But honestly, I don't think it will happen any time soon.

**Comment by alexeyshockov** [comment]
@sagikazarmark, it's not always about Composer. Many PHP projects are built once (into DEB, RPM or whatever) and then distributed on different machines. And it's not always true, that PHP version on the build server is the same on other machines.

**Comment by sagikazarmark** [comment]
As I said, it's highly subjective. From your point of view, it might be. If you think of Guzzle as a dependency, probably Composer is involved in most of the cases.

One could argue that having different versions for a build and production environment is a rookie mistake. (Fortunately Composer got you covered, you can manually configure the target PHP version in composer.json)

I don't there is anything to be afraid from at this point, there are bigger things coming up (PSR for HTTP client for instance) which will end up in a major version change anyway.

**Comment by gmponos** [comment]
We have dropped support of php5 on master and we are planning to release version 7 very soon..

There are related issues and pr about it: https://github.com/guzzle/guzzle/issues/2510

I guess this issue does not offer something more and we can close this.. :)

**Comment by arianitu** [comment]
@gmponos do all current releases support PHP5, including promises atm?

We want to use Guzzle in a CMS plugin that will have ranges of PHP versions from 5.x to 7.x, can we use the latest release or do we need to target the releases based on the version?

**Comment by gmponos** [comment]
> do all current releases support PHP5,

All current **STABLE** released versions of packages that are under Guzzle namespace support PHP5. 

For instance Guzzle 6 supports PHP5. Guzzle 7.0-beta1 is out which does not support PHP5.

Every package under Guzzle namespace that will drop support of PHP5 will tag a new major release...
