### ISSUE TITLE
Catchable fatal error: Argument 2 passed to Illuminate\Routing\UrlGenerator::__construct() must be an instance of Illuminate\Http\Request

### ISSUE THREAD

**Issue by matthewrichter** [guzzle/guzzle#1937]
When trying to install this via my terminal i get the following error. Laravel 5.0

`Using version ^6.3 for guzzlehttp/guzzle
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Package phpexcel/phpexcel is abandoned, you should avoid using it. Use phpoffice/phpexcel instead.
Writing lock file
Generating autoload files
> Illuminate\Foundation\ComposerScripts::postUpdate
> php artisan optimize

Catchable fatal error: Argument 2 passed to Illuminate\Routing\UrlGenerator::__construct() must be an instance of Illuminate\Http\Request, null given, called in /home/domain/public_html/admin/vendor/laravel/framework/src/Illuminate/Routing/RoutingServiceProvider.php on line 62 and defined in /home/domain/public_html/admin/vendor/laravel/framework/src/Illuminate/Routing/UrlGenerator.php on line 103
Script php artisan optimize handling the post-update-cmd event returned with an error

Installation failed, reverting ./composer.json to its original content.

                      
  [RuntimeException]  
  Error Output:      `

**Comment by sagikazarmark** [comment]
Sorry, I just don't see how this is a Guzzle issue. It clearly is some laravel problem. (at least based on the information above)

**Comment by Konafets** [comment]
@matthewrichter Please wrap your console output in code tags, that makes it better readable
