### ISSUE TITLE
Refactor json_encode and json_decode

### ISSUE THREAD

**Issue by zanderwar** [guzzle/guzzle#1942]
Needless to say, this is annoying, can you please refactor these methods that only exist to throw exceptions to something else, it's quite intrusive.

![image](https://user-images.githubusercontent.com/13566916/31803827-6a19577e-b5b2-11e7-9c4b-6cc38b73388b.png)

**Comment by Nyholm** [comment]
I have the same issue, sure. It is quite annoying. But the methods are properly namespaced and this is more an issue with the IDE. 

Also, releasing a version with these functions renamed is a BC break and will require a new major version.
