### ISSUE TITLE
微信退款异常 ，返回微信返回错误提示:订单金额或退款金额与之前请求不一致，请核实后再试

### ISSUE THREAD

**Issue by HDLSmile** [guzzle/guzzle#1944]
| Q            | A
| ------------ | ---
| Bug?         | no|yes
| New Feature? | no|yes
| Version      | Specific version or SHA of a commit

#### Actual Behavior

What is the actual behavior?

#### Expected Behavior

What is the behavior you expect?

#### Steps to Reproduce

What are the steps to reproduce this bug? Please add code examples,
screenshots or links to GitHub repositories that reproduce the problem.

#### Possible Solutions

If you have already ideas how to solve the issue, add them here.
(remove this section if not needed)

**Comment by HDLSmile** [comment]
以前都没问题，突然不可以了

**Comment by alexeyshockov** [comment]
It would be better if you use English to describe your issue, it's the most common language among the maintainers and experienced users here.

**Comment by sagikazarmark** [comment]
Sorry, we can't really help you this way. Please open a new issue in English.
