### ISSUE TITLE
CURLOPT_RESOLVE

### ISSUE THREAD

**Issue by coudenysj** [guzzle/guzzle#1945]
| Q            | A
| ------------ | ---
| Bug?         | no
| New Feature? | yes
| Version      | 6.3.0

I would like to pass a RESOLVE option to the curl getopt function (https://curl.haxx.se/libcurl/c/CURLOPT_RESOLVE.html).

Should this be added in the request constant list, or is this something I could add to a "generic" opt list when constructing the client?

If you think this would be a nice addition to the library, I could help out to add it.

**Comment by coudenysj** [comment]
I think I should have a look at: https://github.com/guzzle/guzzle/blob/master/src/Handler/CurlFactory.php#L48-L50.

**Comment by alexeyshockov** [comment]
You can just pass this option to a request, as [any other cURL-specific option](http://docs.guzzlephp.org/en/stable/faq.html#how-can-i-add-custom-curl-options):

```
$client->request('GET', '/', [
    'curl' => [
        CURLOPT_RESOLVE => 'www.google.com:443:173.194.72.112'
    ]
]);
```

Does it solve the problem, or you are talking about something different?

**Comment by coudenysj** [comment]
That was indeed the solution. Thanks!

**Comment by simonhamp** [comment]
Thanks @alexeyshockov! I didn't know this was possible and it took me a while to find this... it's not super clear in the docs and it took me many searches to turn this up.

I'd just like to add one little addendum - `CURLOPT_RESOLVE` requires an array of strings, i.e.:

```
$client->request('GET', '/', [
    'curl' => [
        CURLOPT_RESOLVE => [
            'www.google.com:443:173.194.72.112',
        ],
    ],
]);
```

**Comment by alexeyshockov** [comment]
@simonhamp, thanks for your comment!

About the docs: there is an FAQ section about custom cURL options. I think it's enough, but many people still ask questions on the topic. If you have any thought on how to improve the docs, feel free to comment/PR :)
