### ISSUE TITLE
Guzzle allow_redirect => false does not work

### ISSUE THREAD

**Issue by 6mayjiten** [guzzle/guzzle#1949]
// this always show status 200 while in postman it show 302 when i stop redirect

			$client     = new GuzzleHttp\Client();
			$Url = 'some url';
			try {
                             $response = $client->request('GET',$Url,['query' => $body],['headers' => ['Content-
                              Type'  => 'application/x-www-form-urlencoded']],['allow_redirects' => false]);
		              $responseHomeNetworkAPI = $response;
			      echo $response->getStatusCode();
                       }

**Comment by alexeyshockov** [comment]
Probably because you use `request()` method in a wrong way. All your three arrays should be combined into one:

```
$response = $client->request(
    'GET',
    $Url,
    [
        'query' => $body,
        'headers' => ['Content-Type'  => 'application/x-www-form-urlencoded'],
        'allow_redirects' => false
    ]
);
```

BTW, `'Content-Type: application/x-www-form-urlencoded` makes no sense in a GET request.

**Comment by sagikazarmark** [comment]
Sounds right (BTW this is why we ask those questions in the issue template)

@6mayjiten please reopen if the above does not fix your problem.
