### ISSUE TITLE
$options as an object

### ISSUE THREAD

**Issue by joshuaadickerson** [guzzle/guzzle#1950]
| Q            | A
| ------------ | ---
| Bug?         | no
| New Feature? | yes
| Version      |6

#### Actual Behavior

Client::transfer() expects an array of options

#### Expected Behavior

A class that will allow the developer to see all of the getters and setters for options. This will make it easier for a developer to know what options are available and what the signature for those options should be.

#### Steps to Reproduce

```php
$client = new Client();
$client->send($request, ['query' => ['foo' => 'bar']);
```

#### Possible Solutions

Create a class named Options that will contains methods for:

* form_params
* multipart
* json
* body
* set_headers
* decode_content
* auth
* and more (no use in listing it all out)

**Comment by gmponos** [comment]
FYI using middlewares someone might have his own custom options.

**Comment by sagikazarmark** [comment]
I'm pretty sure the current signature won't change in the near future. I agree that an array option is not necessarily ideal, but worked fine so far.

**Comment by bjoernffm** [comment]
I would like to implement such an object, I think it's necessary to keep backwards compability so the options parameter should accept the array as well as the new object.

@sagikazarmark what do you think?

**Comment by bjoernffm** [comment]
We could suggest the users something like that:

```php
$options = Options(); // already instantiated with all defaults set -> "ready to go"
$options
    ->setAuth('username', 'password') // validating happens within the Options class
    ->setBody('Some body')
    ->setHeaders(['Accept-Encoding' => 'gzip']);

$res = $client->request('GET', '/redirect/3', $options);
```

instead of

```php
$res = $client->request('GET', '/redirect/3', [
    'auth' => ['username', 'password'],
    'body' => 'Some body',
    'headers' => [
        'Accept-Encoding' => 'gzip'
    ]
]);
```
