### ISSUE TITLE
Json_encode does not encode numbers properly

### ISSUE THREAD

**Issue by anantaramdas** [guzzle/guzzle#1960]
| Q            | A
| ------------ | ---
| Bug?         | yes
| New Feature? | no
| Version      | 6.3

#### Actual Behavior

```
$amount = 26000;
\Log::info("A: " . $amount);
$json = \GuzzleHttp\json_encode([
    'amount' => $amount,
]);
\Log::info("J: " . $json);
```

Gives following output:
```
info log [13:26:42] LOG.info: A: 26000
info log [13:26:42] LOG.info: J: {"amount":25999.999999999996}
```

#### Expected Behavior

Gives following output:
```
info log [13:26:42] LOG.info: A: 26000
info log [13:26:42] LOG.info: J: {"amount":26000}
```

#### Steps to Reproduce
Added code above. Using Laravel 5.5 with GuzzleHttp 6.3

**Comment by alexeyshockov** [comment]
It has nothing to do with Guzzle. [`\GuzzleHttp\json_encode`](https://github.com/guzzle/guzzle/blob/master/src/functions.php#L322-L331) only wraps errors into exceptions, the behaviour is identical to the original [`json_encode`](http://php.net/manual/en/function.json-encode.php). So the bug should be reported as a bug in PHP.

**Comment by anantaramdas** [comment]
@alexeyshockov thanks! Posted to PHP https://bugs.php.net/bug.php?id=75561 - just for reference.

**Comment by gmponos** [comment]
Just for reference you can as an alternative use the body option and encode the json string manually.
