### ISSUE TITLE
CURLOPT_UNIX_SOCKET_PATH

### ISSUE THREAD

**Issue by eckelarsson** [guzzle/guzzle#1962]
| Q            | A
| ------------ | ---
| Bug?        | no
| New Feature? | yes
| Version      | 6.3.0

Add the feature to connect and send request via unix socket.

Here is a live example to communicate to the docker api via sockets locally,
`curl --unix-socket /var/run/docker.sock http:/v1.24/containers/json`

`curl --unix-socket /var/run/docker.sock -H "Content-Type: application/json" \
  -d '{"Image": "bfirsh/reticulate-splines"}' \
  -X POST http:/v1.24/containers/create
{"Id":"1c6594faf5","Warnings":null}`

Examples found here
[https://docs.docker.com/develop/sdk/examples/](url)

**Comment by alexeyshockov** [comment]
From what I see, it can be solved with [a custom cURL option](http://docs.guzzlephp.org/en/stable/faq.html#how-can-i-add-custom-curl-options):

``` php
$client->request('GET', 'http:/v1.24/containers/json', [
    'curl' => [
        CURLOPT_UNIX_SOCKET_PATH => '/var/run/docker.sock'
    ]
]);
```

**Comment by eckelarsson** [comment]
Thank you, that worked great!
