### ISSUE TITLE
Warning: A non-numeric value encountered in .../vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php on line 384

### ISSUE THREAD

**Issue by mauriciogior** [guzzle/guzzle#1965]
| Q            | A
| ------------ | ---
| Bug?         | no|**yes**
| New Feature? | **no**|yes
| Version      | 6.2.1

PHP 7.2

#### Actual Behavior

What is the actual behavior?
Throws warning on `$conf[CURLOPT_TIMEOUT_MS] = $options['timeout'] * 1000` as non-numeric value encountered.

#### Expected Behavior

What is the behavior you expect?
Not show that warning

#### Steps to Reproduce

What are the steps to reproduce this bug? Please add code examples,
screenshots or links to GitHub repositories that reproduce the problem.
Just run a simple request

#### Possible Solutions

If you have already ideas how to solve the issue, add them here.
(remove this section if not needed)
Just wrap `$options['timeout']` with `intval`.

**Comment by tomzx** [comment]
The line you are referring to is https://github.com/guzzle/guzzle/blob/b245bc5/src/Handler/CurlFactory.php#L383. To trigger it, one needs to configure their request with a timeout as such:

```php
$res = $client->request('GET', 'https://www.google.com', [
    'timeout' => 5, // here
]);
```

If you are receiving this error, it is likely that the setting you used for `timeout` cannot be implicit cast into a string. Please provide/check your code.

**Comment by fcroce** [comment]
I'm not sure it's related, but I had a similar problem and I fixed it like this:

https://github.com/guzzle/guzzle/blob/master/src/Handler/CurlFactory.php#L66

Cast "$this->handles" to array:
`if (count((array) $this->handles) >= $this->maxHandles) {`
