### ISSUE TITLE
What does the set-cookie containing dkoc=1;max-age=1;dkkp=1; mean?

### ISSUE THREAD

**Issue by shanezhiu** [guzzle/guzzle#1966]
my code:
         

> $arr = [
> 			// Base URI is used with relative requests
> 			'base_uri' => 'https://tongji.baidu.com/web/welcome',
> 			// You can set any number of default request options.
> 			'timeout'  => 2.0,
> 		];
> 		$curl = new Client($arr);
> 		$cookie_instant = new CookieJar();
> 		$cookie = $curl->request("GET", "/ico", [
> 			"verify" => false,
> 			"s" => "12043aa801f7335c7f5326c7536b2b9d",
> 			"cookie" => $cookie_instant,
> 		]);
> 		$cookie = $cookie->getHeaders();
> 		var_dump($cookie);

and when I excuted it at the first time ,it could gain an exact cookie likes 

`BAIDUID=3575E1CA8C4837ADD84CBE42F0C6931A:FG=1; expires=Sat, 01-Dec-18 06:44:34 GMT; max-age=31536000; path=/; domain=.baidu.com; version=1`,

and when I excuted it again ,the cookie changed to  

` "dkkp=1;dkoc=1;max-age=1"`

I wonder know that what did happen and it is an individual case or a universal.

**Comment by shanezhiu** [comment]
Is there any more detail manuals?

**Comment by alexeyshockov** [comment]
The issue is not connected with Guzzle, these additional cookie parameters come from the server.

Personally I don't know what they are about. Better to ask on [StackOverflow](https://stackoverflow.com/).

**Comment by shanezhiu** [comment]
@alexeyshockov Thanks a lot.

**Comment by shanezhiu** [comment]
@alexeyshockov additional cookie? Okay,thanks a lot.
