### ISSUE TITLE
phpstan analysis error when using GuzzleException

### ISSUE THREAD

**Issue by babaorum** [guzzle/guzzle#1971]
| Q            | A
| ------------ | ---
| Bug?         | no
| New Feature? | no
| Version      | actual

#### Actual Behavior

Experiencing error with phpstan like those with level analysis >= 5

```
$exception of class My\Namespace\Exception\MyCustomException constructor expects Exception, GuzzleHttp\Exception\GuzzleException given.
```

#### Expected Behavior

No error found.

#### Steps to Reproduce

I am catching `GuzzleException` like this.
```php
try {
    // use guzzle for an http call
} catch (GuzzleException $exception) {
    throw new MyCustomException($exception);
}
```

with a custom exception like this : 
```php
class MyCustomException extends \Exception
{
    public function __construct(\Exception $exception)
    {
    }
}
```

#### Possible Solutions

The problem seems to be that `GuzzleException` does not extends \Exception directly. And there is no guarantee that every class that will implement `GuzzleException` will extend `\Exception`.

For me, the problem could be solved by changing GuzzleException into an abstract class which will extends `\RuntimeException` since it is the actual extended exception.

**Comment by ondrejmirtes** [comment]
Hi, author of PHPStan here. You should:

1) Require \Throwable and not \Exception in your constructor.
2) Use the latest version of PHPStan (0.9) that understands that even interfaces caught in a catch block can be accepted as Throwable.

**Comment by ondrejmirtes** [comment]
Maintainers of Guzzle can feel free to close this issue 😊

**Comment by babaorum** [comment]
Thank you @ondrejmirtes ! I saw there was some stuff done for Guzzle, but did not saw this problematic.
Sorry everyone for the time lost. Love your projects :)

I am closing the issue.

**Comment by rvanlaak** [comment]
@ondrejmirtes just as a follow-up on this. Since `0.10` was released (🎉) the phpstan error now thrown is:

> PHPDoc tag @throws with type GuzzleHttp\Exception\GuzzleException is not subtype of Throwable

Should the `GuzzleException` interface extend `\Throwable`? It does solve above error.

**Comment by babaorum** [comment]
@rvanlaak Throwable interface can not be extended by userland interfaces. neither can it be implemented by userland classes.

**Comment by ondrejmirtes** [comment]
@babaorum This definitely isn’t true, you can define interface X extends \Throwable.

**Comment by babaorum** [comment]
[this](https://3v4l.org/rZMo8) won't work. 

But it is true that we won't see any error because [this](https://3v4l.org/0Thid) works.
