### ISSUE TITLE
Wrong doc info

### ISSUE THREAD

**Issue by akimsir** [guzzle/guzzle#1972]
| Q            | A
| ------------ | ---
| Bug?         | yes
| New Feature? | no
| Version      | 6.3.0

On page http://docs.guzzlephp.org/en/stable/ (http://joxi.ru/krDJ9yBU06l8W2)
echo $res->getHeader('content-type'); // error - array to string conversion

**Comment by tomzx** [comment]
@akimsir, can you provide an example of the request you made? Was it the exact same request as in the documentation?

**Comment by akimsir** [comment]
Yes? exact as in the documentation
