### ISSUE TITLE
Empty cookie value is not handled

### ISSUE THREAD

**Issue by HanXHX** [guzzle/guzzle#1975]
| Q            | A
| ------------ | ---
| Bug?         | yes
| New Feature? | no
| Version      | 6.3.0

#### Actual Behavior

Many websites (ex: github.com) set cookie without value on sign out. With cookiejar strict mode set to true you have an RuntimeException. With strict mode set to false, the cookie is ignored.

#### Expected Behavior

Cookie value should be an empty string.

#### Steps to Reproduce

```php
$header = 'user_session=; path=/; max-age=0; expires=Thu, 01 Jan 1970 00:00:00 -0000';

$req = new \GuzzleHttp\Psr7\Request('GET', new Uri('https://github.com'));
$res = new \GuzzleHttp\Psr7\Response(200, ['Set-Cookie' => $header]);

$cj = new \GuzzleHttp\Cookie\CookieJar(true); 
$cj->extractCookies($req, $res);  // RuntimeException: Invalid cookie: The cookie value must not be empty

var_dump($cj->getCookieByName('user_session'));
```

**Comment by HanXHX** [comment]
In PHP doc: [setcookie function](http://php.net/manual/en/function.setcookie.php) allow setting cookie without a value (empty string).

**Comment by andycaramba** [comment]
Please, react this issue. I also ran into this problem and I do not really want to rewrite all my project to the Curl.

**Comment by HanXHX** [comment]
See PR #1991

**Comment by sagikazarmark** [comment]
Sorry for the delay, I will review it shortly.

**Comment by HanXHX** [comment]
@sagikazarmark did you have a look on my PR?

**Comment by HanXHX** [comment]
ping @sagikazarmark

**Comment by HanXHX** [comment]
ping @sagikazarmark ?

**Comment by gmponos** [comment]
I think this can be closed with https://github.com/guzzle/guzzle/pull/2691

**Comment by GrahamCampbell** [comment]
Yep, I think so too.
