### ISSUE TITLE
The `auth` item doesn't work when I test on Github API with Guzzle6

### ISSUE THREAD

**Issue by shanezhiu** [guzzle/guzzle#1978]
I am using Guzzle6 to test Github API. 
But there is a problem with using `auth` configuration when I tested `https://api.github.com/user` interface which needs Authentication . 

mycode:

```
$arr = [
    'base_uri' => 'https://api.github.com/',
    'timeout' => 2.0,
];
$client = new Client($arr);
$res = $client->request(
    'POST',
    '/user',
    [
	'verify' => false,
	'debug' => true,
	'auth' => [
		'shanezhiu@gmail.com',
		'xdssdfxdf',
	],
]);
dump($res->getBody()->read(4600000),true);
```

I run this, and then I got a fatal error:

> Fatal error: Uncaught GuzzleHttp\Exception\ClientException: Client error: `POST https://api.github.com/user` resulted in a `400 Bad Request` response: { "message": "Problems parsing JSON", "documentation_url": "https://developer.github.com/v3/users/#update-the-authen (truncated...) in D:\AMP\www\dc\vendor\guzzlehttp\guzzle\src\Exception\RequestException.php on line 113

I checked the ```400 Bad Request` response: { "message": "Problems parsing JSON``` on github API document. 

It means that 

> Sending invalid JSON will result in a 400 Bad Request response.

I try to solve it with myself, but failed. I confused when and where the problem happened.

**Comment by sagikazarmark** [comment]
Have you tried dumping the request body?

As far as I can see there is a syntax error as well (check the number of opening and closing square brackets), but maybe that's just the example code.

Last, but not least: you send a POST request to an endpoint, but there is no body in your request. Are you sure you want POST and not GET?

**Comment by shanezhiu** [comment]
@sagikazarmark Thank you for your help. I edited it again. Did you mean that I had better send a POST request with body, such as replacing the `auth` with `form-data`?

**Comment by sagikazarmark** [comment]
No, I meant I guess you are trying to retrieve data, in which case you should send a GET request, not POST.

See https://developer.github.com/v3/users/#get-the-authenticated-user

**Comment by shanezhiu** [comment]
@sagikazarmark  Thank your for your help again, I tried it again according to your suggestion, and succeeded.
