### ISSUE TITLE
Next exception 'GuzzleHttp\Exception\RequestException' with message 'cURL error 56: TCP connection reset by peer' in /usr/share/nginx/html/project/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:51

### ISSUE THREAD

**Issue by taryono** [guzzle/guzzle#1980]
Hi, 

I am using laravel 5.2 version and using mandrilla to send email to user by guzzle lib 

 "guzzlehttp/guzzle": "5.3.0",

and it's show an error like this in my log file

Next exception 'GuzzleHttp\Exception\RequestException' with message 'cURL error 56: TCP connection reset by peer' in /usr/share/nginx/html/project/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:51 
 
is this a bug of this lib or in my mechine how to fix this error, help me please!!! Thanks..

**Comment by tomzx** [comment]
See https://stackoverflow.com/questions/1434451/what-does-connection-reset-by-peer-mean. This generally means there was a problem with the connection between your machine and the target machine. 

It has nothing to do with this library.

**Comment by sagikazarmark** [comment]
I'm afraid we can't offer much help here.

**Comment by taryono** [comment]
Thanks for the answer guys.... @tomzx , @sagikazarmark ...
