### ISSUE TITLE
Bad query string formating 

### ISSUE THREAD

**Issue by informagenie** [guzzle/guzzle#1982]
| Q            | A
| ------------ | ---
| Bug?       | yes
| New Feature? | no|
| Version      | 6.0-dev

With this code
```php
$client = new \GuzzleHttp\Client(['base_uri'=> 'http://example.com']);
try{
     $data = ['params1'=>'value1', 'params2'=> 'value2'];
     $res = $client->request('GET', '/', ['query'=> $data]);
}catch(\GuzzleHttp\Exception\RequestException $e)
{
      echo $e->getRequest()->getUri();
     //Show somethings like http://example.com/?params1=value1params2=value2
}
```
I see the absence of ampersand in the request uri !

How resolve this problem ?

**Comment by bjoernffm** [comment]
Hi, I'm using version 6.3.0 released on 2017-06-22 and it seems to work fine. Have you tried using this version?

**Comment by informagenie** [comment]
With this version, all is right !

**Comment by sagikazarmark** [comment]
So is this issue resolved then?

**Comment by informagenie** [comment]
Yes, by using the 6.3 version
