### ISSUE TITLE
Error Composer

### ISSUE THREAD

**Issue by joaovelozo** [guzzle/guzzle#1984]
Can someone tell me how to solve this error?

 [Seld\JsonLint\ParsingException]
  "./composer.json" does not contain valid JSON
  Parse error on line 3:
  ...o": "1.5.*"        "guzzlehttp/guzzle"
  ---------------------^
  Expected one of: 'EOF', '}', ':', ',', ']'

**Comment by sagikazarmark** [comment]
Hard to tell without more details, but it looks like there is a comma missing before `"guzzlehttp/guzzle"`.

Try this tool to find the issue: https://jsonlint.com/

This is hardly guzzle related, so I'm closing it for now.
