### ISSUE TITLE
How to urldecode query params ?

### ISSUE THREAD

**Issue by informagenie** [guzzle/guzzle#1987]
| Q            | A
| ------------ | ---
| Bug?         | no
| New Feature? | no
| Version      | 6.3

#### Actual Behavior

```
$customer = \GuzzleHttp\Client(['base_uri'=>'https://example.com']);
$response = $customer->request('GET', '/', ['query'=> ['name'=>'Dolce| Gabana']]);
```

All is correct except the parameter of the query is urlencoded

> https://example.com/?name=Dolce%7CGabana

I want exactly this request uri

> https://example.com/?name=Dolce|Gabana

**Comment by alexeyshockov** [comment]
IMO you should not want to do that. The remote server must decode the query string, so it will receive the original string in the end. BTW, it's better to use [`query`][1] option to manage query string parameters.

If you want to do it anyway, try to construct an instance of [Uri class][2] manually.


  [1]: http://docs.guzzlephp.org/en/stable/request-options.html#query
  [2]: https://github.com/guzzle/psr7/blob/master/src/Uri.php

**Comment by sagikazarmark** [comment]
@alexeyshockov is right, URL encoding should not be a problem. I'm afraid manual instantiation won't help either.

**Comment by chris97pl** [comment]
Actually I'm dealing with a broken Java API at the other end. I cannot urlencode as the target API does not urldecode. Is that possible to force not to encode UTF characters in the URL? Ie:

```
https://server/2019/JUL2019七月号/Print/document.pdf
```

Which becomes:

```
https://server/2019/JUL2019%E4%B8_%E6__%E5_%B7/Print/document.pdf
```
