### ISSUE TITLE
unable to install

### ISSUE THREAD

**Issue by flik** [guzzle/guzzle#1989]
| Q            | A
| ------------ | ---
| Bug?         |  yes
| New Feature? | no|yes
| Version      | Specific version or SHA of a commit

#### Actual Behavior

I want to install guzzle according to instructions on http://docs.guzzlephp.org/en/stable/overview.html#installation but getting nothing.
```
Jan2018@adminxA MINGW32 /d/xampp/htdocs/zf-tutorial
$ composer require guzzlehttp/guzzle:~6.0
Content-Length mismatch, received 1847255 bytes out of the expected 1913396
http://packagist.org could not be fully loaded, package information was loaded from the local cache and may be out of date
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Writing lock file
```

#### Expected Behavior

It should install.

#### Steps to Reproduce

composer require guzzlehttp/guzzle:~6.0

**Comment by sagikazarmark** [comment]
This is hardly a Guzzle issue. Please report the issue to the composer/packagist team.

**Comment by flik** [comment]
ok. thanks. I have reported on composer repo.
