### ISSUE TITLE
Guzzle 6.3 setPath() implementation

### ISSUE THREAD

**Issue by clairemariko** [guzzle/guzzle#1990]
| Q            | A
| ------------ | ---
| Bug?         | no|
| New Feature? | no|
| Version      | 6.3

#### Actual Behavior

Before the upgrade the setPath was being implement like this -
`$client->getConfig()-setPath('auth', array('user', 'pass', 'Basic|Digest|NTLM|Any'))`

However I now get this response after upgrading the bundle -

> PHP Fatal error:  Call to a member function setPath() on array

I have seen in the changelog setPath has been moved
GuzzleHttp\Utils::setPath -> GuzzleHttp\set_path

However when searching for this in the bundle I cannot find setPath or set_path

How should I be implementing setPath() with Guzzle 6.3?

**Comment by alexeyshockov** [comment]
You should use [`auth`](http://docs.guzzlephp.org/en/stable/request-options.html#auth) option instead.

**Comment by gmponos** [comment]
Closing as a solution has been provided by @alexeyshockov and no feedback there was no feedback
