### ISSUE TITLE
 Magic request methods require a URI and optional options array 

### ISSUE THREAD

**Issue by dsvvimal** [guzzle/guzzle#1993]
Hi, i am getting an issue " Magic request methods require a URI and optional options array" when i tried to set "verify" and certificate path .I am using guzzle 6.0. Below is the sample code.

$https = $client->getHttpClient()->setDefaultOption('verify', 'C:/xampp/php/extras/ssl/cacert.pem');
$client->setHttpClient($https);
$request = new \GuzzleHttp\Psr7\Request('GET', 'https://services.groupkt.com/state/get/IND/all');
$promise = $client->sendAsync($request)->then(function ($response) {
echo $response->getBody();
});

**Comment by sagikazarmark** [comment]
`setDefaultOption` has been removed in Guzzle 6, that's what the call is dispatched to the magic call function. The client is immutable, you have to pass that parameter in the constructor.

**Comment by sushil173** [comment]
I got the same magic error, How to pass parameter in the constructor?

**Comment by sagikazarmark** [comment]
Please see the documentation:

http://docs.guzzlephp.org/en/stable/quickstart.html#creating-a-client
http://docs.guzzlephp.org/en/stable/request-options.html
