### ISSUE TITLE
Type error: Argument 3 passed to GuzzleHttp\Client::request() must be of the type array, string given, called in /srv/share/vendor/guzzlehttp/guzzle/src/Client.php on line 89

### ISSUE THREAD

**Issue by klausbreyer** [guzzle/guzzle#1994]
| Q            | A
| ------------ | ---
| Bug?         | yes
| New Feature? | no
| Version      | 6.3.0)

#### Error

![screen shot 2018-01-25 at 11 52 44](https://user-images.githubusercontent.com/32771/35384697-771c0eca-01c6-11e8-9a42-fa8781883495.png)

Type error: Argument 3 passed to GuzzleHttp\Client::request() must be of the type array, string given, called in /srv/share/vendor/guzzlehttp/guzzle/src/Client.php on line 89

#### Steps to Reproduce

```
 $response = $this->guzzleClient->send($this->guzzleClient->createRequest($method, $url, ['body' => 'changedthisrightnow.']));
```

For completeness:
```
$this->guzzleClient = new \GuzzleHttp\Client(
            [
                'base_url' => [
                    'https://api.easybill.de/rest/{version}/',
                    ['version' => 'v1'],
                ],
                'defaults' => [
                    'headers' => [
                        'Accept' => 'application/json',
                        'Authorization' => sprintf('Bearer %s', $apiKey),
                    ],
                ],
            ]
        );```

**Comment by sagikazarmark** [comment]
There is no such method as `createRequest` and the magic `__call` function gets called, which in turn calls `request` with wrong parameters. Leave the call to that method entirely and just call send, it should work.

**Comment by crazytonyi** [comment]
`createRequest` is a 5.3 method.

**Comment by gmponos** [comment]
We haven't received any feedback about this issue and it does not seem like a bug of guzzle.

For support please use other channels that are listed here: https://github.com/guzzle/.github/blob/master/.github/SUPPORT.md
