### ISSUE TITLE
GuzzleHttp\Exception\ConnectException: cURL error 6: Could not resolve host

### ISSUE THREAD

**Issue by usman84** [guzzle/guzzle#1996]
I'm beginner to learn it. I'm facing issue below:
#### Error in DB Logs
`GuzzleHttp\Exception\ConnectException: cURL error 6: Could not resolve host: www-dev.drupalsite.com (see http://curl.haxx.se/libcurl/c/libcurl-errors.html ) in GuzzleHttp\Handler\CurlFactory::createRejection() (line 186 of /var/www/html/site-d8/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php ).`

#### Error while accessing site
The website encountered an unexpected error. Please try again later.
Note that this is local dev-site using **vagrant on ubuntu (VM Virtual Box)**.

I have spent 2 days (googling, asking friends etc.) on that but no luck.

**Comment by sagikazarmark** [comment]
The error clearly states that this is probably a DNS issue: the given domain name cannot be resolved to an IP address in your environment. You either have to check your DNS settings, or you have to add an entry to your host file within your box.

Also, this has clearly nothing to do with Guzzle, so please use StackOverflow instead: https://stackoverflow.com/questions/tagged/guzzle

There is a chance that others suffered from the same issue. You can probably find more related to Vagrant and PHP as this is not a Guzzle issue.

**Comment by usman84** [comment]
@sagikazarmark , thanks for the response. Now, I have configure DNS in Ubuntu **by adding hostname in /etc/hosts file.**

Thanks again

**Comment by serenaMahmoud** [comment]
how you did that ? how you changed the DSN config ?

**Comment by sagikazarmark** [comment]
He added an entry to his `/etc/hosts`.

**Comment by usman84** [comment]
@serenaMahmoud, I just added entry of my IP and set URL, [see screen short](https://snag.gy/6oXL0t.jpg). Thanks

**Comment by kingrgdev** [comment]
I added to my /etc/hosts still getting the same error. :(

**Comment by elamigosam** [comment]
I am using phrets (https://github.com/troydavisson/PHRETS) with PHP 7.2.19-0ubuntu0.18.04.2
I keep getting the same error: Fatal error: Uncaught GuzzleHttp\Exception\ConnectException: cURL error 6: Could not resolve host: config
I tried:
static entry on /etc/hosts
remove https:// from url,
nothing seems to work, any ideas?

**Comment by ellisio** [comment]
Landed here because I use Laravel Valet for local development. Valet uses dnsmasq for host names. Trying to send a Guzzle request to my `core.test`, which clearly exists, is failing.

```
   GuzzleHttp\Exception\ConnectException  : cURL error 6: Could not resolve: core.test (Domain name not found) (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)

  at /Users/andrew/Developer/salesmessage/core/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:200
    196|         }
    197| 
    198|         // Create a connection exception if it was a specific error code.
    199|         $error = isset($connectionErrors[$easy->errno])
  > 200|             ? new ConnectException($message, $easy->request, null, $ctx)
    201|             : new RequestException($message, $easy->request, $easy->response, null, $ctx);
    202| 
    203|         return \GuzzleHttp\Promise\rejection_for($error);
    204|     }

  Exception trace:

  1   GuzzleHttp\Handler\CurlFactory::createRejection(Object(GuzzleHttp\Handler\EasyHandle))
      /Users/andrew/Developer/salesmessage/core/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:155

  2   GuzzleHttp\Handler\CurlFactory::finishError(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))
      /Users/andrew/Developer/salesmessage/core/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:105

  Please use the argument -v to see more details.
                                                                                                                                                                                                                                                                                                              
❯ ping -c1 core.test         
PING core.test (127.0.0.1): 56 data bytes
64 bytes from 127.0.0.1: icmp_seq=0 ttl=64 time=0.025 ms

--- core.test ping statistics ---
1 packets transmitted, 1 packets received, 0.0% packet loss
round-trip min/avg/max/stddev = 0.025/0.025/0.025/0.000 ms
```

**Comment by penyaskito** [comment]
Same issue here, in my case just updated to php 7.4 and everything started failing. I can connect from any browser, ping, but guzzle/curl fails somehow.

**Comment by santoshdangol** [comment]
> Landed here because I use Laravel Valet for local development. Valet uses dnsmasq for host names. Trying to send a Guzzle request to my `core.test`, which clearly exists, is failing.
> 
> ```
>    GuzzleHttp\Exception\ConnectException  : cURL error 6: Could not resolve: core.test (Domain name not found) (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)
> 
>   at /Users/andrew/Developer/salesmessage/core/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:200
>     196|         }
>     197| 
>     198|         // Create a connection exception if it was a specific error code.
>     199|         $error = isset($connectionErrors[$easy->errno])
>   > 200|             ? new ConnectException($message, $easy->request, null, $ctx)
>     201|             : new RequestException($message, $easy->request, $easy->response, null, $ctx);
>     202| 
>     203|         return \GuzzleHttp\Promise\rejection_for($error);
>     204|     }
> 
>   Exception trace:
> 
>   1   GuzzleHttp\Handler\CurlFactory::createRejection(Object(GuzzleHttp\Handler\EasyHandle))
>       /Users/andrew/Developer/salesmessage/core/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:155
> 
>   2   GuzzleHttp\Handler\CurlFactory::finishError(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))
>       /Users/andrew/Developer/salesmessage/core/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:105
> 
>   Please use the argument -v to see more details.
>                                                                                                                                                                                                                                                                                                               
> ❯ ping -c1 core.test         
> PING core.test (127.0.0.1): 56 data bytes
> 64 bytes from 127.0.0.1: icmp_seq=0 ttl=64 time=0.025 ms
> 
> --- core.test ping statistics ---
> 1 packets transmitted, 1 packets received, 0.0% packet loss
> round-trip min/avg/max/stddev = 0.025/0.025/0.025/0.000 ms
> ```

I've solved this issue by simply mapping the domain with ip address. 
\etc\hosts
127.0.0.1 web.test

**Comment by willenrocha** [comment]
php artisan route:clear
php artisan config:clear
php artisan cache:clear

**Comment by Dakalo-Tshifura** [comment]
Am experiencing the same problem.

  cURL error 5: Could not resolve proxy: htf-cobbler.fnb.co.za (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://appslist.heimdall.site/list.json

  at /app/www/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:211

    207▕ 

    208▕         // Create a connection exception if it was a specific error code.

    209▕         $error = isset($connectionErrors[$easy->errno])

    210▕             ? new ConnectException($message, $easy->request, null, $ctx)

  ➜ 211▕             : new RequestException($message, $easy->request, $easy->response, null, $ctx);

    212▕ 

    213▕         return P\Create::rejectionFor($error);

    214▕     }

    215▕

      +13 vendor frames 

  14  /app/www/app/SupportedApps.php:157

      GuzzleHttp\Client::request()

  15  /app/www/app/Jobs/ProcessApps.php:41

      App\SupportedApps::getList()


when i check under etc/host this is what i get:
127.0.0.1       localhost
::1     localhost ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
10.15.0.15      heimdall.f.co.za heimdall

**Comment by Dakalo-Tshifura** [comment]
cURL error 5: Could not resolve proxy: htf- (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://appslist.heimdall.site/list.json

  at /app/www/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:211

    207▕ 

    208▕         // Create a connection exception if it was a specific error code.

    209▕         $error = isset($connectionErrors[$easy->errno])

    210▕             ? new ConnectException($message, $easy->request, null, $ctx)

  ➜ 211▕             : new RequestException($message, $easy->request, $easy->response, null, $ctx);

    212▕ 

    213▕         return P\Create::rejectionFor($error);

    214▕     }

    215▕

      +13 vendor frames 

  14  /app/www/app/SupportedApps.php:157

      GuzzleHttp\Client::request()

  15  /app/www/app/Jobs/ProcessApps.php:41

      App\SupportedApps::getList()




This is what i get on etc/host:
127.0.0.1       localhost
::1     localhost ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
10.15.0.15      heimdall.f.co.za heimdall
