### ISSUE TITLE
Promise\any doesn't work for CurlMultiHandler

### ISSUE THREAD

**Issue by RobberPhex** [guzzle/guzzle#2000]
| Q            | A
| ------------ | ---
| Bug?         | yes
| Version      | `guzzlehttp/guzzle` 6.3.0, `guzzlehttp/promises` v1.3.1

#### Actual Behavior

for php code:
```php
<?php
use GuzzleHttp\Psr7\Uri;
use GuzzleHttp\Promise;

$client = new \GuzzleHttp\Client();

$promises = [];

$baseUri = new Uri('http://httpbin.org/');

$uri = $baseUri->withPath('/user-agent');
$request = new \GuzzleHttp\Psr7\Request('GET', $uri);
$promises[] = $client->sendAsync($request);

$uri = $baseUri->withPath('/delay/5');
$request = new \GuzzleHttp\Psr7\Request('GET', $uri);
$promises[] = $client->sendAsync($request);

$x = Promise\any($promises);

$x->wait();
```
it's costs **5~6s**.

#### Expected Behavior

The `/user-agent` request is very fast, so it should cast **less than 1s**.

#### Steps to Reproduce

run those code

#### Possible Solutions

N/A

**Comment by tillkruss** [comment]
Same here. This is either broken or very unintuitive.
