### ISSUE TITLE
Change the proxy in some point!

### ISSUE THREAD

**Issue by beshoo** [guzzle/guzzle#2002]
Dear Support , i am using guzzlephp to connect via proxy.
But in the middle of the script i want to call with a new proxy , so i reset the proxy , but some how i can see guzzlephp keep using the old connection

* Connection #0 to host zproxy.proxyserver.io left intact
* Found bundle for host i.web.com: 0x25f99c0 [can pipeline]
*** Re-using existing connection! (#0) with proxy zproxy.proxyserver.io // <============ There is no new connection to the new proxy**
* Connected to zproxy.proxyserver.io (192.241.138.37) port 22225 (#0)

and here is my client setup 

```
        $criticalOptions = [
            'cookies' => ($this->_cookieJar instanceof CookieJar ? $this->_cookieJar : false),
            'verify'  => $this->_verifySSL,
            'debug' => true,
                'Connection' => 'close',
                CURLOPT_FORBID_REUSE => true,
                CURLOPT_FRESH_CONNECT => true,
            'proxy'   => ($this->_proxy !== null ? $this->_proxy : null),
        ];

```
I need to change the proxy and use the new proxy

**Comment by tomzx** [comment]
Hello,

I think you'll have to provide more context (code) to make your explanation clearer.

**Comment by dzentota** [comment]
I faces the same problem;
the problem is that guzzle reuses old curl handler. Code responsible for this located in CurlFactory:

```php
 $easy->handle = $this->handles
            ? array_pop($this->handles)
            : curl_init();
        curl_setopt_array($easy->handle, $conf);
```
so if you send several requests providing proxy address as a param, like:

```php
$httpClient->send($request, ['proxy' => '<proxy_endpoint1>');
$httpClient->send($request2, ['proxy' => '<proxy_endpoint2>');
$httpClient->send($request3, ['proxy' => '<proxy_endpoint3>');
```

All three requests will be made via <proxy_endpoint1>

**Comment by dzentota** [comment]
Steps to reproduce:

```php
$client = new GuzzleHttp\Client();
$res1 = $client->request('GET', 'https://httpbin.org/ip', ['proxy' => '182.253.123.9:3128']);
$res2 = $client->request('GET', 'https://httpbin.org/ip', ['proxy' => '217.219.20.136:8080']);
$res3 = $client->request('GET', 'https://httpbin.org/ip', ['proxy' => '178.128.115.98:8080']);
echo $res1->getBody();
echo $res2->getBody();
echo $res3->getBody();
```
Expected output:
```
{
"origin": "182.253.123.9"
}
{
"origin": "217.219.20.136"
}
{
"origin": "178.128.115.98"
}
```
Actual:
```
{
"origin": "182.253.123.9"
}
{
"origin": "182.253.123.9"
}
{
"origin": "182.253.123.9"
}
```

**Comment by dzentota** [comment]
Faced with the same problem. Details are here https://github.com/guzzle/guzzle/issues/2257
