### ISSUE TITLE
Why eval in test server

### ISSUE THREAD

**Issue by ChiChou** [guzzle/guzzle#2004]
I did a little search in my repo to find security issue, then I found this backdoor-like code:

https://github.com/guzzle/guzzle/blob/master/tests/server.js#L178

```
that.responses = eval('(' + request.body + ')');
```

Why eval here? To parse JSON format in node.js server side, just use `JSON.parse` instead.

Since it's in test code and will not be shipped into production, I directly report it as a bug here.

**Comment by sagikazarmark** [comment]
Nice catch! I have no idea why that thing is in the code. We will have to check.
