### ISSUE TITLE
Connection not getting reused

### ISSUE THREAD

**Issue by kushubham9** [guzzle/guzzle#2006]
| Q            | A
| ------------ | ---
| Bug?         | no
| New Feature? | no
| Version      | 6.3

#### Actual Behavior

Too many TCP IP connections are getting created. Active connections are not getting reused even a single guzzle client instance is being used. 

#### Expected Behavior

Connections should be reused and not created for each request.

#### Steps to Reproduce

I have built a wrapper on top of Guzzle Client. Through this, I set the required headers and request body param. The wrapper holds an instance of Guzzle\Client which is a singleton instance and instantiated once.

```
$this->httpClient->setupClientInstance();

        $this->httpClient->setRequestBody(
                $data,
                $method == 'get' ? HttpClient::QUERY_TYPE : HttpClient::JSON_TYPE
            );


        return $this->request($url, $method, $options);
```

```
public function setupClientInstance() { 
       if (isset(self::$instances[$clientKey])) {
            $this->client = self::$instances[$clientKey];
        } else {
            $this->client = new Client($this->options);
            self::$instances[$clientKey] = $this->client;
        }
  }
```

   ```
 public function request($url, $method = 'GET', $options = [])
    {
        $options = array_merge($this->options, $options);

        /** Merge the headers */
        $options = array_merge($options, ['headers' => $this->headers]);


        try {
            $this->response = $this->client->request($method, $url, $options);
        } catch (Exception $e) {
            if ($this->withExceptions) {
                throw $e;
            }
        }

        return $this;
    }
```

When I see the number of open TCP ports it is equal to the number of requests sent.

In the response, I am getting 'Connection: keep-alive'

Am I missing something? How can I reduce the connection count and make persistent connections work in this case?

**Comment by kushubham9** [comment]
I find that when I do not set any handler with the client, my connections are getting reused. 
//        $this->httpClient->setHandler(RetryHandler::getMiddleware(3, 1000));

Any workaround here? How to reuse connection along with handler?

**Comment by gmponos** [comment]
You simply need to use the same handler in all your guzzle instances.

Closing.. This does not seem to be a bug or a possible bug. For support questions please use the channels listed here https://github.com/guzzle/.github/blob/master/.github/SUPPORT.md
