### ISSUE TITLE
Authentication library option fails when return value from DB but works when its a variable

### ISSUE THREAD

**Issue by jkkenzie** [guzzle/guzzle#2009]
| Q            | A
| ------------ | ---
| Bug?         |yes
| New Feature? | no
| Version      | 6

#### Actual Behavior

using $config['auth_source'] = 'library';

my function when i return as follows:
return '1e957ebc35631ab22d5bd6526bd14ea2'; works (authentication success)
But
return $this->auth_model->getApiToken($email, $password); does not work

I used a different method to print $this->auth_model->getApiToken($email, $password); to page and the result was 1e957ebc35631ab22d5bd6526bd14ea2

#### Expected Behavior

I expect authentication to be successful when i return from db 

#### Steps to Reproduce

1. create table
`CREATE TABLE `api_users` (
  `id` int(11) NOT NULL,
  `username` varchar(255) NOT NULL,
  `password` varchar(64) NOT NULL,
  `token` varchar(50) NOT NULL,
  `firstname` varchar(32) NOT NULL,
  `lastname` varchar(32) NOT NULL,
  `created_at` datetime NOT NULL
) ENGINE=MyISAM DEFAULT CHARSET=utf8;`

`INSERT INTO `api_users` (`id`, `email`, `password`, `token`, `firstname`, `lastname`, `created_at`) VALUES
(1, 'admin', '1234', '1e957ebc35631ab22d5bd6526bd14ea2', 'mike', 'clever', '2018-02-06 00:00:00');`

2. set rest config settings
`$config['auth_source'] = 'library';
$config['auth_library_class'] = 'Apiauth';
$config['auth_library_function'] = 'login';`

3. Apiauth Class and its function login
`<?php if (!defined('BASEPATH')) exit('No direct script access allowed');
class Apiauth extends Auth_model {
    public function login($email, $password) {
                return $this->auth_model->getApiToken($email, $password);
    }
}`
4. The Controller class to call the Rest server:
`require('/vendor/autoload.php');
use \GuzzleHttp\Client as Client;
use \GuzzleHttp\HandlerStack as Stack;
use \GuzzleHttp\Handler\CurlHandler as Handler;
class testcontroller extends CI_controller(){
public function index(){
        $handler = new Handler();
        $stack = Stack::create($handler);         
        $client = new Client(['handler' => $stack, 'http_errors' => false]); 
       $response = $client->request('GET', 'http://localhost/api/TESTRESULT', [
            'auth' => ['admin', '1234', 'digest'],
            'query' => ['X-API-KEY' => 12345]
        ]);
        print_r( $response->getBody() ) ;
 }
}`
5. The Responding GET url function TESTRESULT
`<?php if (!defined('BASEPATH')) exit('No direct script access allowed');
require(APPPATH.'libraries/REST_Controller.php');
class TESTRESULT extends REST_Controller {    
    public function index_get()
    {
      $test = array('foo' => 'bar');
      $this->response($test, 200);
    }   
}`

**Comment by sagikazarmark** [comment]
I'm sorry, what is the error that indicates its a guzzle issue? To me it looks unrelated.

**Comment by jkkenzie** [comment]
I don't even know what to blame:

Guzzle is sending the request, but this request can only attend to 'x' but not 'fromdb->x' . yet both come have same result. So do i blame PHP, codeigniter, Codeigniter-restserver, curl or guzzle?

**Comment by jkkenzie** [comment]
This is not Guzzle issue. Sorry.
I found issue here https://github.com/chriskacerguis/codeigniter-restserver/issues/283
You may delete this issue
