### ISSUE TITLE
Multipart Form Header problems 

### ISSUE THREAD

**Issue by leonelvsc** [guzzle/guzzle#2010]
| Q            | A
| ------------ | ---
| Bug?         | yes
| New Feature? | no
| Version | 6.3

#### Actual Behavior

When you create a multipart form and get the body the class automatically appends the “Content-Length” header to each field of the form 

#### Expected Behavior

The same but without the “Content-Length” header as stated here https://tools.ietf.org/html/rfc7578#section-4.8

The problem with that header is that in my case the server rejects the request if that header is present 
#### Steps to Reproduce

Create any multipart form.

**Comment by Nyholm** [comment]
As you noticed Guzzle adds this automatically. It seams super strange that your server rejects the request if that header is present. 

I cannot not see an easy way around this. And Im afraid it would be a feature marked as "wont fix"... Hm.... I think your best way forward is to do your own implementation of a MultipartStreamRequest...

FYI: Here is a resource that might be interesting: https://github.com/php-http/multipart-stream-builder
I see though that this library also tries to add `Content-Length` header.
