### ISSUE TITLE
Guzzle as proxy

### ISSUE THREAD

**Issue by sm2017** [guzzle/guzzle#2011]
| Q            | A
| ------------ | ---
| Bug?         | no
| New Feature? | no
| Version      | 6.3.0

How can I use guzzle as a proxy? I want to hide url of remote files

Assume I have a 1GB file at **http://a.com/file.zip** and my script tun at **http://b.com/hidden** this script GET the **file.zip** in a $body=`\GuzzleHttp\Psr7\Stream` object

```php
while (!$body->eof()) {
 echo $body->read(1024); 
 flush(); 
}
```

I expect that download started immediately without too long delay

Can you please show me how can I do this with guzzle?

**Comment by sagikazarmark** [comment]
I'm not sure you can. You would have to wait for the HTTP request to finish first.
