### ISSUE TITLE
[Question]Slow response time - 5 seconds average

### ISSUE THREAD

**Issue by msaus** [guzzle/guzzle#2013]
curl 7.47.0 (x86_64-pc-linux-gnu)
guzzlehttp/guzzle: ^6.3

It takes average 5 seconds to crawl.
Do you know why it is very slow?

Of course, I set header like following.
array(
"Connection" => "close"
)

If I use curl command, it is super fast....

The target URL is following.

https://search.rakuten.co.jp/search/mall/baby/?p=1

**Comment by tomzx** [comment]
This doesn't seem to be related to guzzle. It takes me on average 5 seconds as well either through the browser or using curl.

**Comment by msaus** [comment]
By using curl, it dose not take 5 seconds.

**Comment by msaus** [comment]
That was mistake. It takes more than 5 seconds from my laptop.
Sorry for that.
