### ISSUE TITLE
How to send duplicate keys in post data?

### ISSUE THREAD

**Issue by enumag** [guzzle/guzzle#2015]
I need to send a slightly unusual request with some repeating keys in the post data - like `foo=1&foo=2`. The target server requires it like this and normal `foo[]=1&foo[]=2` won't work.

While googling for a solution using guzzle I found this [documentation](https://github.com/guzzle/guzzle3/blob/master/docs/http-client/request.rst#query-string-parameters) for old guzzle. Clearly such request was easy to make in the old version using the `Guzzle\Http\QueryAggregator\DuplicateAggregator`.

How can I do this in the new guzzle? My search was unsuccessful.

**Comment by msaus** [comment]
I guess you can just post like this array data.
foo[0]=1
foo[2]=2
foo[3]=1

**Comment by enumag** [comment]
No I can't. And I already said so in the first post.

**Comment by alexeyshockov** [comment]
Guzzle internally just passes `form_params` array to PHP's `http_build_query()` function. So no way.

IMO the only option now is to do it manually, something like that:
``` php
$params = [
    ['foo' => 'bar'],
    ['foo' => 'baz'],
];

$body = [];
foreach ($params as $param) {
    $body[] = http_build_query($param);
}

$body = implode('&', $body); // string(15) "foo=bar&foo=baz" 
```

**Comment by enumag** [comment]
@alekseykuleshov So this feature was removed without replacement when upgrading guzzle? Good to know. RIP Guzzle then.

**Comment by neuquen** [comment]
FYI - [This thread](https://github.com/guzzle/guzzle/issues/1196#issuecomment-222035704) shows an alternative function which can be used called `build_query`.  Someone also showed [example usage](https://github.com/guzzle/guzzle/issues/1196) in the same thread.

**Comment by firewall004** [comment]
```
$response = $client->request('POST', $url, [
    'multipart' => [
        [
            'name'     => 'text',
            'contents' => 'Hello'
        ],
        [
            'name'     => 'text',
            'contents' => 'Hi'
        ],
        [
            'name'     => 'text',
            'contents' => 'How are you'
        ]
    ]
]);
```

Use `name` and `contents` when you want to send duplicate keys in form data
