### ISSUE TITLE
json_decode() return null with valid json

### ISSUE THREAD

**Issue by webnao** [guzzle/guzzle#2018]
Hi,

 json structure: {"id": "1234", "name": "bar \\"for\\" baz " }.

json valid, checked in the program "PostMan".

example:
```php
$response = $client->request('GET', $uri, [
     'query' => $query
]);

$body = $response->getBody();   //return  {"id": "1234", "name": "baz "for" baz"}
$json = json_decode($body, true); //return null
```
why method getBody remove "\\"?
on server, quotes are escaped.

guzzle v.6.3, php 5.6.3
or I'm doing something wrong?(((((

Thanks!)

**Comment by sagikazarmark** [comment]
First: Congratulations! You won the 2018 issue number. 😄 

Second: I'm pretty sure Guzzle does nothing like that. See the following gist: https://gist.github.com/sagikazarmark/9dd52450aa8746dec5a1499df8570600

**Comment by webnao** [comment]
Nice man!)))) Thanks!
I'm wrong.
