### ISSUE TITLE
CURL Exceptions slips through try/catch block

### ISSUE THREAD

**Issue by peku33** [guzzle/guzzle#2019]
| Q            | A
| ------------ | ---
| Bug?         | yes
| New Feature? | no
| Version      | 6.3.0 from composer, php 7.2.0

#### Actual Behavior

When CURL wrapper throws exception, it somehow slips through try/catch block.
This happens often when using proxy, via `proxy` option passed to the `request()` method.
Wrapping whole request in try/catch, catching `\GuzzleHttp\Exception\RequestException $E`, curl exception always terminates the program.

Stack trace is also getting truncated to ~1024 characters:
```
PHP Fatal error:  Uncaught GuzzleHttp\Exception\RequestException: cURL error 18: transfer closed with outstanding read data remaining (see http://curl.haxx.se/libcurl/c/libcurl-errors.html) in /home/<path>/public_html/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:187
Stack trace:
#0 /home/<path>/public_html/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(150): GuzzleHttp\Handler\CurlFactory::createRejection(Object(GuzzleHttp\Handler\EasyHandle), Array)
#1 /home/<path>/public_html/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(103): GuzzleHttp\Handler\CurlFactory::finishError(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))
#2 /home/<path>/public_html/vendor/guzzlehttp/guzzle/src/Handler/CurlHandler.php(43): GuzzleHttp\Handler\CurlFactory::finish(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))
#3 /home/<path>/public_html/vendor/guzz in /home/<path>/public_html/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php on line 187
```

#### Expected Behavior

Exception does not terminate the program, throws exception to place where `request()` was called.

#### Steps to Reproduce

This occurs only for direct CURL exceptions.
Handling for example http 404, 500 errors works correctly

Somebody created example for similar problem:
#2003 

#### Possible Solutions

This is certainly curl, possibly proxy related.
I'm not sure how curl problems are handled, but it looks like 'rejection' is not properly handled and terminates the program.

**Comment by sagikazarmark** [comment]
The stack trace says that a `GuzzleHttp\Exception\RequestException` is thrown.

Can you please share the code snippet where the problem occurs?

**Comment by peku33** [comment]
@sagikazarmark there would be no problem if whole request wasn't surrounded by try/catch block.

Everything looks like:
```
		private static function GetGuzzleHttpClient()
		{
			static $Instance = null;
			if($Instance === null)
				$Instance = new \GuzzleHttp\Client();
			return $Instance;
		}
		public function Request($Method, $Uri, array $RequestOptions = [])
		{
			$RequestOptions = $this->GetRequestOptions($RequestOptions);

			// There are no special request options, its array, containing only proxy settings
			return self::GetGuzzleHttpClient()->request(
				$Method,
				$Uri,
				$RequestOptions
			);
		}
		public function RequestAutoRetry($Method, $Uri, $RetryNum, array $RequestOptions = [], $PrintToConsole = false)
		{
			for($I = 0; $I < $RetryNum; $I++)
			{
				try
				{
					return $this->Request($Method, $Uri, $RequestOptions);
				}
				catch(\GuzzleHttp\Exception\RequestException $E)
				{
					// do some handling, this is not being called
				}
			}
		}
```

**Comment by alanhartless** [comment]
Also experiencing this. @peku33 did you come up with a solution?

**Comment by ipontt** [comment]
Same problem here. I tried to debug it but the pseudo Promises just obfuscate everything.

**Comment by mjordan** [comment]
I'm using Guzzle within Drupal and am getting the following errors in apache's error log when my external service (Riprap) is not running:

`[Sun Oct 13 18:19:11.554191 2019] [php7:notice] [pid 3379] [client 10.0.2.2:56426] Uncaught PHP Exception GuzzleHttp\\Exception\\ConnectException: "cURL error 7: Failed to connect to 10.0.2.2 port 8888: Connection refused (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)" at /var/www/html/drupal/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php line 185, referer: http://localhost:8000/admin/reports/dblog`

Here's my Guzzle code:

```php
    try {
      $client = \Drupal::httpClient();
      // Assumes Riprap requires no authentication (e.g., it's behind the Symfony or other firewall).
      $options = [
        'headers' => ['Resource-ID' => 'placeholder_resource_id'],
      ];
      $response = $client->request('GET', $riprap_endpoint, $options);
      $riprap_response_code = $response->getStatusCode();
    }
    catch (ConnectException $e) {
      \Drupal::logger('islandora_riprap')->error($e->getMessage());
    }
```

Shouldn't the ConnectException be caught?
