### ISSUE TITLE
Header Client Default

### ISSUE THREAD

**Issue by elvispdosreis** [guzzle/guzzle#2020]
| Q            | A
| ------------ | ---
| Bug?         | yes
| New Feature? | no
| Version      | 6.3.0 from composer, php 7.2.0

#### Actual Behavior

What is the actual behavior?
When you send a resquest header  " 'Content-Type'=>'application/json; charset=utf-8' " default it is changed by the call

#### Expected Behavior

What is the behavior you expect?
Must keep the Content-Type when called the POST, the remaining header it has just changed the Content-Type

#### Steps to Reproduce

```
$client = new Client([
            'base_uri' => 'xxxxxx.xxx',
            'headers' => [
                'Content-Type' => 'application/json; charset=utf-8',
                'Accept' => 'application/json; charset=utf-8',
                'Authorization' => 'xxxxxx'
            ]
]);

$categories = [];

$response = $client->request('POST', '/catalog/categories', [
     'json' => $categories
]);
```

```
POST /catalog/categories HTTP/1.1
Content-Type: application/json
Accept: application/json; charset=utf-8
Authorization: xxxxxx
User-Agent: GuzzleHttp/6.2.1 curl/7.54.0 PHP/7.1.6
```

**Comment by sagikazarmark** [comment]
I don't consider this a bug. When asking Guzzle to take care of the serialization it's a natural expectation that it will send the appropriate headers as well. If you want to set your own Content-Type header, you should take care of the serialization yourself.

```php
$client = new Client([
            'base_uri' => 'xxxxxx.xxx',
            'headers' => [
                'Content-Type' => 'application/json; charset=utf-8',
                'Accept' => 'application/json; charset=utf-8',
                'Authorization' => 'xxxxxx'
            ]
]);

$categories = [];

$response = $client->request('POST', '/catalog/categories', [
     'body' => json_encode($categories)
]);
```

[Here](https://github.com/guzzle/guzzle/blob/748d67e23a984e7a2562847994fd133fd4e629a6/src/Client.php#L313-L317) is the relevant code by the way.
