### ISSUE TITLE
Strange behaviour on POST 

### ISSUE THREAD

**Issue by marcoooo** [guzzle/guzzle#2025]
| Q            | A
| ------------ | ---
| Bug?         | dont know
| New Feature? | no
| Version      |  6.0

#### Actual Behavior

I am using last version of PGP Guzzle HTTP... Very simple test done :

    use GuzzleHttp\Client;
    $client = new Client();
        $res = $client->post('https://MYAPI/cards/XXX/credit',[
            'headers' => ['Authorization' => 'Token MYTOKEN'],
            'json' => [
                "amount" => 10,
                "reason" => "Because"
            ]
        ]);
        var_dump($res);
returned a Exception:

    GuzzleHttp\Exception\ClientException : Client error: `POST 
    https://MYAPI/cards/XXX/credit` resulted in a `405 Method Not Allowed` 
    response: {"detail":"Méthode \"GET\" non autorisée."}

#### Expected Behavior

Reveive a POST on server side....

#### Steps to Reproduce

Well, don't know.

**Comment by Nyholm** [comment]
Your server does not allow POST actions on this endpoint. This is not an issue with Guzzle. Refer to StackOverflow if you need help.

**Comment by marcoooo** [comment]
Well I might not have been clear enough, the question was not about the server response in fact, but : I use a post request on PHP side and receive a GET header on DRF side. The error message is clear : GET not allowed, but I use a POST method ... so, where is the trick ?

**Comment by sagikazarmark** [comment]
Do you have any middleboxes that might improperly turn POST requests to GET?

Also, I have to assume as well that this is not a Guzzle issue, because we would probably receive thousands of other reports like this as well.

Can you try sending a POST request to somewhere else? Maybe some files became corrupted? If POST works to other hosts then most probably something is wrong with the one you are trying.

But without deeper insights, it's not possible to determine what causes the issue.

**Comment by marcoooo** [comment]
Thank you for your response. I was wondering if you have already received this kind of error in the past, thinking it was related to any configuration or something. As it is not, the problem may reside elsewhere in the middle. I'll give a try to another api (or implement one quickly). 

I'll let you know. 

Thanks for your time anyway :-)

**Comment by marcoooo** [comment]
For information, bug not related neither to  DRF server sources (I started test server locally tested, and this is a POST request received) neither to your library configuration.... Still don't know what I am missing on production server... anyway thanks for your time. Sorry for inconvenience.

**Comment by Gunzhin** [comment]
I catch this error (405) if send request to `http` instead `https`. Probably problem in configuration server, but it works for me.
