### ISSUE TITLE
Message language

### ISSUE THREAD

**Issue by etesan** [guzzle/guzzle#2030]
Hello!

How can i translate the guzzle information and errors messages?. I need to display them in Spanish, but i can't find the file with texts. I don't care if i've got to make it manually.

Thanks!!!

**Comment by alexeyshockov** [comment]
There is no dedicated file, unfortunately. All messages are hardcoded. Guzzle is a low level library (I mean that the messages are not intended to be shown to the end user directly), that why it is like it is.

So I would advice to build a small subset of your own messages, based on Guzzle's exception classes.

**Comment by etesan** [comment]
So,  i can stop now..jejejej

Muchisimas gracias por tu respuesta!

**Comment by Nyholm** [comment]
Thank you Alexey
