### ISSUE TITLE
ResponseClassInterface

### ISSUE THREAD

**Issue by marcoooo** [guzzle/guzzle#2033]
| Q            | A
| ------------ | ---
| Bug?         | no
| New Feature? | no
| Version      | 6

#### Actual Behavior

I am trying desperately to create a custom Object from my API results. I saw in docs some information about a responseType and a responseClass element in client description. But I can't manage to use actually objects. 

#### Expected Behavior

Define a custom class as result object. In order to encapsulate api calls in a kine of "Models" function

#### Possible Solutions

The reference to Guzzle\service\Command\ResponseClassInterface is no longer available in repo, is this features abandoned? Is there another way to register my own objects as results for my services ? 

Kind regards.
Marc

**Comment by sagikazarmark** [comment]
Guzzle is an HTTP client which will always return HTTP responses. You have to write your own layer which transforms it into your own models.

I think maybe you are looking for these libraries:

https://github.com/guzzle/command
https://github.com/guzzle/guzzle-services

**Comment by marcoooo** [comment]
Thanks for your response, finally I did excatly what you mentionned. Initialize my models 'Objects' with received GuzzleResponse Object.
