### ISSUE TITLE
Problems with Guzzle6 and Laravel 5.5

### ISSUE THREAD

**Issue by wanderrojasb** [guzzle/guzzle#2034]
Hi, I have this problem
When I run my project with php artisan serve (http://127.0.0.1:8000), I can consume the api, but when I access the application without artisan (http://127.0.0.1/myapp) I can no longer consume the api shows me a message of "Server error:` GET http: //127.0.0.1/test/myapi/r/12345678` resulted in a `500 Internal Server Error`

I have the following code

      `$client=new Client([
			'base_uri'=>'http://127.0.0.1/myapi/api/r/',
		]);
		$response=$client->request('GET',"{$pval}");
		$person=json_decode($response->getBody()->getContents());`

I thank their help

**Comment by sagikazarmark** [comment]
You have to check your server logs to find out what the problem is.

You receive a response, it even states it's a server side issue (5xx status code), that rules Guzzle out as a suspect with 99% probability.
