### ISSUE TITLE
confusing documentation

### ISSUE THREAD

**Issue by asadijabar** [guzzle/guzzle#2037]
| Q            | A
| ------------ | ---
| Bug?         | no 
| New Feature? | no 
| Version      | 6 

it is mentioned at the document of this version (check the link) that Guzzle is no longer depend on cURL, but there are many classes which use cURL functions. may you please update the document ? 

link : [here](http://docs.guzzlephp.org/en/stable/overview.html#requirements)

**Comment by sagikazarmark** [comment]
Just one line above the referenced sentence (and the rest of the referenced note) explains the situation perfectly: Guzzle no longer requires cURL (meaning: it's not a hard dependency) to run (compared to past versions) as it has a stream handler now.

When cURL is not available, Guzzle silently falls back to the stream handler. The fact that there is cURL related code doesn't mean that Guzzle won't work without it.

I'm sorry, but there is no wrong information here and honestly I don't find this part confusing. I hope my answer cleared the confusion for you.
