### ISSUE TITLE
Post of GuzzleHttp\Client  request online Domain Name is ok,  but local is not ok, why??

### ISSUE THREAD

**Issue by huaiguoguo** [guzzle/guzzle#2041]
| Q            | A
| ------------ | ---
| Bug?         | no|yes   i don't know
| New Feature? | no|yes  no
| Version      | Specific version or SHA of a commit  ^6.3

#### Actual Behavior

What is the actual behavior?
i am use version 7.2.3 of php;
i am use version 1.13.10 of nginx;
i am use vesion is 5.6 of laravel 
i  am use passport ^5.0 , it's a  plugin of laravel 

i am test at local  and  i use post function of GuzzleHttp\Client   request local http://xxxx.com/oauth/token
and it still stuck ,  then still  nginx error
![image](https://user-images.githubusercontent.com/1888094/38365268-37d21cbc-390e-11e8-86a0-1141711b6c95.png)

then  i  tried to test request other Domain Name of local  ,  and so did the results.
![image](https://user-images.githubusercontent.com/1888094/38365359-9880b65e-390e-11e8-9c9f-3df3c311e3fb.png)

but  i  try  use post function of GuzzleHttp\Client  request  online Domain Name ,  it succesfully
example:  www.baidu.com,   www.qq.com,  as soon  it response result (successufully)

why  ,  why ,,why , why ,why ...........
why  domain name of local   is not ok???
why  ????

i  have spend one day  still now , I have forgotten to eat lunch 。。。。。
it's time to dinner  now , i will to eat !!!

i want to have a manito,  help me .......
master shifu,  

#### Expected Behavior

What is the behavior you expect?

#### Steps to Reproduce

What are the steps to reproduce this bug? Please add code examples,
screenshots or links to GitHub repositories that reproduce the problem.

#### Possible Solutions

If you have already ideas how to solve the issue, add them here.
(remove this section if not needed)

**Comment by huaiguoguo** [comment]
i look this  laravel.log

![image](https://user-images.githubusercontent.com/1888094/38368769-c3114230-3918-11e8-975b-3099887ea569.png)

i don't the reason,,,,,

**Comment by jesseyofferenvan** [comment]
It seems like your execution time might not be set high enough in nginx, do you happen to use docker? Or have some knowledge of nginx? If so, check the max_execution_time in your php.ini and fastcgi_read_timeout 300; in your virtualhost of nginx.

**Comment by gmponos** [comment]
This is neither a feature request neither a bug. It seems more of a support question. For support questions please refer to other channels that can be found here: https://github.com/guzzle/.github/blob/master/SUPPORT.md

If you feel that we missed something feel free to provide more context.
