### ISSUE TITLE
Why we can't update CURLOPT_RETURNTRANSFER for GuzzleHttp\Client?

### ISSUE THREAD

**Issue by vuongggggg** [guzzle/guzzle#2048]
| Q            | A
| ------------ | ---
| Bug?         | no
| New Feature? | no
| Version      | Current

I want to set a new value for CUROPT_RETURNTRANSFER for `GuzzleHttp\Client`, I saw it only supports default value and no way to set. Maybe I'm wrong, can anyone help me to solve it or explain why?

Thanks.

**Comment by tomzx** [comment]
Does http://docs.guzzlephp.org/en/stable/faq.html#how-can-i-add-custom-curl-options answer your question?

**Comment by vuongggggg** [comment]
Yes, thank you!

**Comment by vuongggggg** [comment]
@simpo
I'm not sure by above answer, coz I've used the old library at the time I asked this question.
So I provide my way to modify `CURLOPT_RETURNTRANSFER`. Hope it can help you.
```php
$httpClient = new Guzzle\Http\Client(['http_errors' => true]);
$request = $httpClient->delete();
$request->getCurlOptions()->set(CURLOPT_RETURNTRANSFER, true);
```

**Comment by simPod** [comment]
Found the answer, posted here https://stackoverflow.com/a/52930054/519333
