### ISSUE TITLE
Suggestion: withQueryValues

### ISSUE THREAD

**Issue by dnyg** [guzzle/guzzle#2049]
Adding default query string(s) changed in Guzzle 6 and now requires adding middleware like the one mentioned by @EAnushan in issue #1138:

```
$handler->unshift(Middleware::mapRequest(function (RequestInterface $request) {
    return $request->withUri(Uri::withQueryValue($request->getUri(), 'key', 'secretKey'));
}));
```

When you need to work with multiple default query strings you either have to do nested calls to `->withUri()` (which becomes unmanageable at already 2 parameters), or create a loop/recursive function to generate an Uri to pass into `withUri()`. Something like

**Nested**
```
$handler->unshift(Middleware::mapRequest(function (RequestInterface $request) {
    return $request->withUri(Uri::withQueryValue(Uri::withQueryValue($request->getUri(), 'key1', 'value1'), 'key2', 'value2'));
}));
```

**Loop**
```
$handler->unshift(Middleware::mapRequest(function (RequestInterface $request) {
    $uri = $request->getUri();

    $defaults = [
        'key1' => 'value1',
        'key2' => 'value2'
    ];

    foreach ($defaults as $key => $value) {
        $uri = Uri::withQueryValue($uri, $key, $value);
    }

    return $request->withUri($uri);
}));
```

**Feature Request: `withQueryValues()`**

It would be nice if the `GuzzleHttp\Psr7\Uri` class had a `withQueryValues(UriInterface $uri, $valueArray)` function, so you could do something like

```
return $request->withUri(Uri::withQueryValues($request->getUri(), [
    'key1' => 'value1',
    'key2' => 'value2'
]);
```

**Comment by sagikazarmark** [comment]
Thanks for the detailed feature request, I believe it indeed sounds useful, but this is the wrong repo. Can you open a new issue at https://github.com/guzzle/psr7 ?

**Comment by dnyg** [comment]
Sorry about that. I have opened an issue at the correct repo https://github.com/guzzle/psr7/issues/196
