### ISSUE TITLE
I can't send POST Cookie and Post request form

### ISSUE THREAD

**Issue by congchien1st** [guzzle/guzzle#2051]
Cookies were sent and $ _POST['answer'] was not sent

  	Guzzle\Http\StaticClient::mount();
	
	$response = Guzzle::post('http://congchien.tk/', array(
    'cookies' => array('__cfduid'=>'daa7fb0df476d2559710d9adfbcd654d51522697194'),
    'body'    => array('answer' => '123'),
    'timeout' => 10
	));
	echo $response;

**Comment by BeschtaBrandon** [comment]
What version are you on? Same happens for me

**Comment by sagikazarmark** [comment]
Please note that you are still using Guzzle 3 which is not supported anymore. Please upgrade to a newer version.
