### ISSUE TITLE
[docs] Make Exceptions paragraph more clear

### ISSUE THREAD

**Issue by frzsombor** [guzzle/guzzle#2055]
When I have to deal with Guzzle's exceptions, I always find it confusing to read the [Exception docs](http://docs.guzzlephp.org/en/stable/quickstart.html#exceptions) with all those "_this_ extends _that_" sentences. I think it would be really useful and helpful for everyone (I mean not everyday users) to see the exceptions in a "tree view" in that paragraph. Something like this:

```
\Exception
    \RuntimeException
        SeekException
        TransferException
            RequestException
                ConnectException
                TooManyRedirectsException
                BadResponseException
                    ClientException
                    ServerException
```

**Comment by sagikazarmark** [comment]
Would you mind opening a PR?

**Comment by frzsombor** [comment]
Thank you very much for adding this improvement and sorry for not answering, I forgot this issue :(
