### ISSUE TITLE
Option to keep Authorization headers in cross-domain redirects

### ISSUE THREAD

**Issue by barryvdh** [guzzle/guzzle#2056]
| Q            | A
| ------------ | ---
| Bug?         | perhaps?
| New Feature? | no
| Version      | 6.3.2

#### Actual Behavior

When a redirect happens between a different domain, the Authorization header is stripped. See https://github.com/guzzle/guzzle/blob/73bf0937061461ca45292a93aa3b7e9010f2e753/src/RedirectMiddleware.php#L197
This is by design (see https://github.com/guzzle/guzzle/pull/1207), so probably for good reason.

But in some cases, this leads to 401 errors as the Authorization is stripped.

#### Expected Behavior

It should be possible to keep the Authorization headers, even when redirecting to other domains.

#### Steps to Reproduce

The Google Nest API is affected by this: https://developers.nest.com/documentation/cloud/how-to-read-data
The curl example is working

```
curl -v -L \
  -H "Content-Type: application/json" \
  -H "Authorization: Bearer c.<my token>" \
  -X GET "https://developer-api.nest.com/"
```

The same example in Guzzle is failing with a 401. When viewing in curl, the first result is:

```
< HTTP/1.1 307 Temporary Redirect
< Location: https://firebase-apiserver25-tah01-iad01.dapi.production.nest.com:9553/
```

curl then includes the same header to the redirect, and 200 OK is returned. Guzzle will strip the header and fail with a 401.

#### Possible Solutions

Add a new option to `allow_redirects`, eg. `strip_authorization` with a default to true, but can be overridden.

Also, Google is not a small party, so are they doing something really weird, or is Guzzle being extra strict? The Python example do extra checks themselves, so I guess it is not super common.

Workaround in this case would be to just create 2 requests without allowing redirects. (Like the Python examples)

**Comment by JoshKisb** [comment]
yes I also would like this very much. Give us the option.

**Comment by sagikazarmark** [comment]
Yeah, this is a security measure to make sure that (unencrypted) credentials won't leak. I'm reluctant to add this to the Guzzle core at the moment, but the RedirectMiddleware is less than 300LOC. What's wrong with just copying it and modifying to your needs?

**Comment by JoshKisb** [comment]
Yes i have modified it and contacted the api developers. 
But the issue with changing code from library as always is what happens when upgrade, or if i want to make a wrapper for the api and share it with others.
Currently experimenting with creating a middleware that simply adds it back. 

Honestly i think its okay to just add an option to let users do insecure actions. OSS philosophy. put a warning. the default will remain secure

**Comment by str** [comment]
Has anyone found a workaround?
