### ISSUE TITLE
Guzzle 6.3.2 update breaks custom HTTP headers

### ISSUE THREAD

**Issue by seanhamlin** [guzzle/guzzle#2061]
| Q            | A
| ------------ | ---
| Bug?         |yes
| New Feature? | no
| Version      | 6.3.2 (upgrade from 6.3.0)

#### Actual Behavior

HTTP 403, notice no custom headers are sent. This is current Guzzle 6.3.2 behaviour:

```
> GET /client/v4/zones?page=1&name=example.com&per_page=20 HTTP/1.1
Host: api.cloudflare.com
Accept-Encoding: gzip

< HTTP/1.1 403 Forbidden
```

#### Expected Behavior

HTTP 200, and notice the custom HTTP headers are sent. This is what happened in Guzzle 6.3.0:

```
> GET /client/v4/zones?page=1&name=example.com&per_page=20 HTTP/1.1
Host: api.cloudflare.com
X-Auth-Email: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
X-Auth-Key: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
User-Agent: cfcli/1.0
Accept: application/json
Accept-Encoding: gzip

< HTTP/1.1 200 OK
```

#### Steps to Reproduce

I am created a Guzzle client with:

```
    $client = new Client([
      'debug' => TRUE,
      'base_uri' => self::API_BASE,
      'headers' => [
        'X-Auth-Email' => $this->credentials->getEmail(),
        'X-Auth-Key' => $this->credentials->getKey(),
        'User-Agent' => 'cfcli/1.0',
        'Accept' => 'application/json',
        'Accept-Encoding' => 'gzip',
      ],
      'decode_content' => 'gzip',
      'allow_redirects' => FALSE,
      'connect_timeout' => 10,
      'timeout' => 300,
      'on_stats' => function(TransferStats $stats) use (&$url, &$time) {
        $url = $stats->getEffectiveUri();
        $time = $stats->getTransferTime();
      }
    ]);

  $response = $client->request($method, $endpoint);
```

This code worked fine in Guzzle 6.3.0.

#### Possible Solutions

I have no idea, but either Guzzle fixed an issue which caused another issue (I noticed several HTTP header related commits in 6.3.1), or I am doing something wrong. At the moment I am thinking the prior.

**Comment by sagikazarmark** [comment]
Thanks for submitting this report. Looks like a fix is already submitted as well: #2052

**Comment by sagikazarmark** [comment]
Tagged https://github.com/guzzle/guzzle/releases/tag/6.3.3

**Comment by sagikazarmark** [comment]
As far as I can tell the issue is fixed. Feel free to reopen it if it's not.

**Comment by seanhamlin** [comment]
Confirmed 6.3.3 does indeed fix the regression. Thanks @sagikazarmark
