### ISSUE TITLE
Async request super slow

### ISSUE THREAD

**Issue by bDango** [guzzle/guzzle#2062]
I used guzzle to send 100 async requests. Each of then has a 5s delay (response time). It takes 50s to fulfill all the requests.

Is that normal or it was indeed slow?

version 6.3.2

**Comment by alexeyshockov** [comment]
It depends on how you do the requests. Without seeing the code it's hard to say something.

**Comment by gmponos** [comment]
Since there was no feedback on this I am closing the issue.. Feel free to provide more info and we will reopen it..
