### ISSUE TITLE
SOCKS5 proxy not working doing POST request

### ISSUE THREAD

**Issue by ja-heller** [guzzle/guzzle#2067]
| Q            | A
| ------------ | ---
| Bug?         |yes
| New Feature? | no
| Version      | 6.3.0

detailed versions: 

guzzlehttp/guzzle                     6.3.0              Guzzle is a PHP HT...
guzzlehttp/promises                   v1.3.1             Guzzle promises li...
guzzlehttp/psr7                       1.4.2

#### Actual Behavior

Trying to do a POST request using guzzle and a SOCKS5 proxy.

#### Expected Behavior

IP of SOCKS5 proxy is used, but this doesn't work. The IP of the machine I'm running the code is used to make the request.

#### Steps to Reproduce

What are the steps to reproduce this bug? Please add code examples,
screenshots or links to GitHub repositories that reproduce the problem.

Code:

```
$client = new Client([
    'http_errors' => false,
    ]);

$res = $client->post("some.website.com", [
    'form_params' => [
        "lala" => "laa",
    ],
    'headers' => [
        'User-Agent' => my own useragent',
    ],
    'proxy' =>  [
        'socks5'   => "tcp://username:pass@IP:PORT",
        'timeout'   => 4,
    ],
]);
```

**Comment by sagikazarmark** [comment]
Can you please try the solutions mentioned in this comment? https://github.com/guzzle/guzzle/issues/1484#issuecomment-259104628

**Comment by sagikazarmark** [comment]
ping @ja-heller

**Comment by sagikazarmark** [comment]
Closing as no response is received from the issue opener for almost two months.
