### ISSUE TITLE
Promise never resolve or reject

### ISSUE THREAD

**Issue by zim32** [guzzle/guzzle#2070]
| Q            | A
| ------------ | ---
| Bug?         | yes
| New Feature? | no
| Version      | 6.3.3

#### Actual Behavior

```
      $client = new Client([
            'timeout'  => 5.0,
        ]);
        var_dump('HERE');
        $client->getAsync('https://google.com', [
            'http_errors' => false,
            'verify'      => false,
        ])->then(
            function(ResponseInterface $response)  {
                die('1');
            },
            function(RequestException $e) use ($deferred) {
                die('2');
            }
        );
```

#### Expected Behavior
I see only "HERE". But promise callbacks never called and promise never resolves.
Expect to get result in resolved promise.

I am using ReactPHP. Request is made inside running loop.

**Comment by zim32** [comment]
Running without ReactLoop is fine.

**Comment by tomzx** [comment]
I believe you need to call `wait()` on your promise, as the call to `then()` is non-blocking, therefore the PHP script terminates before the request completes and executes the `then()`.

```php
<?php

use GuzzleHttp\Client;
use Psr\Http\Message\ResponseInterface;
use GuzzleHttp\Exception\RequestException;

require_once 'vendor/autoload.php';

$client = new Client([
	'timeout'  => 5.0,
]);
var_dump('HERE');
$client->getAsync('https://google.com', [
	'http_errors' => false,
	'verify'      => false,
])->then(
    function (ResponseInterface $res) {
        echo $res->getStatusCode() . "\n";
    },
    function (RequestException $e) {
        echo $e->getMessage() . "\n";
        echo $e->getRequest()->getMethod();
    }
)->wait();
```

**Comment by sagikazarmark** [comment]
It depends on how you use Guzzle. If you use the cURL handler, you can tick the promise queue (or just wait for shutdown to happen):

```
<?php

require_once __DIR__ . '/vendor/autoload.php';


$client = new GuzzleHttp\Client([
	'handler' => new \GuzzleHttp\Handler\CurlHandler(),
]);

$promise = $client->requestAsync('GET', 'http://httpbin.org/get');

$promise->then(function ($response) {
	echo 'I completed! ' . $response->getBody();
});

// Kinda eventloop
//for ($i = 0; $i < 10; $i++) {
//	GuzzleHttp\Promise\queue()->run();
//
//	sleep(1);
//}
```

If you use the CurlMultiHandler (which is the default if curl_multi_* functions are present), you will have to call tick: https://github.com/aws/aws-sdk-php/issues/621#issuecomment-111232418

**Comment by gmponos** [comment]
Is the answer of @sagikazarmark working for you? Shall we close this issue?
