### ISSUE TITLE
$response->getBody()  Does not support jsonSerialize

### ISSUE THREAD

**Issue by woodongwong** [guzzle/guzzle#2073]
| Q            | A
| ------------ | ---
| Bug?         | no
| New Feature? | yes
| Version      | future

#### Expected Behavior

$response->getBody()  , Hope to support json_encode in the future.

#### Possible Solutions

https://stackoverflow.com/questions/401908/php-tostring-and-json-encode-not-playing-well-together

**Comment by sagikazarmark** [comment]
Sorry, but this won't land in Guzzle. Serialization is a higher level concern.
