### ISSUE TITLE
Use lsapp.dev URL for laravel appilcation on localhost for localhost:8080 instead of localhost

### ISSUE THREAD

**Issue by VeoGarg** [guzzle/guzzle#2076]
I am learning laravel using youtube and other learning tutorials. I am running my localhost on 8080 port, i.e., localhost:8080 works instead of localhost only. I am using xampp and want to change the url localhost:8080/lsapp/public to lsapp.dev
Please guide me how to do that...

**Comment by sagikazarmark** [comment]
This is definitely not a guzzle issue, so please next time try to ask help in other channels (Laravel forums, StackOverflow, etc).

A few keywords for you:

- hosts file: it allows you to configure the lsapp.dev domain to point to your loopback interface (127.0.0.1)
- apache virtualhost: allows you to listen on port 80 and process requests for a domain name

**Comment by AMS-JR** [comment]
just change lsapp.dev to lsapp.test in both the httpd-vhosts.conf file and the hosts file. It will work fine. The new chrome redirects all .dev -Domains to https
