### ISSUE TITLE
StreamHandler use fopen

### ISSUE THREAD

**Issue by cclehui** [guzzle/guzzle#2078]
| Q            | A
| ------------ | ---
| Bug?         | no
| New Feature? | yes
| Version      | 6.2.3

#### Actual Behavior

StreamHandler use fopen. this is not work on php safe mode.

 $context = $this->createResource(
            function () use ($context, $params) {
                return stream_context_create($context, $params);
            }
        );

return $this->createResource(
            function () use ($request, &$http_response_header, $context) {
                $resource = **fopen**((string) $request->getUri()->withFragment(''), 'r', null, $context);
                $this->lastHeaders = $http_response_header;
                return $resource;
            }
        );
    }

#### Expected Behavior

why not use **stream_socket_client** ?!!!

**Comment by sagikazarmark** [comment]
I believe the decision behind not using `stream_socket_client` was that it required more maintenance to get it right.

For now I don't see the efforts available required for a socket based handler (although it would perfectly be possible to write your own).

Alternatively you could take a look at this project which uses `stream_socket_client`:

https://github.com/php-http/socket-client
