### ISSUE TITLE
statusCode

### ISSUE THREAD

**Issue by dupengshenyang** [guzzle/guzzle#2080]
$client = new \GuzzleHttp\Client();
$url = 'https://www.toutiao.com/i655557862281563150/';
try{
    $response = $client->get($url);
    $a = $response->getBody()->getContents();
    var_dump($a);
} catch (\GuzzleHttp\Exception\ClientException $exception) {
    $responseBody = $exception->getResponse()->getBody()->getContents();
    //$responseBody = $exception->getResponse()->getBody(true);
    $code = $exception->getCode();
    var_dump($responseBody);
}

The status code returned by the open page is 404, but the status code returned by the code is 200? How do I get the 404 status code?

**Comment by sagikazarmark** [comment]
Guzzle doesn't support HTTP2:

`$ curl -i https://www.toutiao.com/i655557862281563150/`

```
HTTP/2 404
server: Tengine
content-type: text/html; charset=utf-8
content-length: 1146
date: Mon, 28 May 2018 16:47:39 GMT
vary: Accept-Encoding
vary: Accept-Encoding
x-tt-timestamp: 1527526059.893
via: cache37.l2ot7[157,0], cache1.us1[200,0]
timing-allow-origin: *
eagleid: 4266ff0115275260597314323e
```


`$ curl --http1.1 -i https://www.toutiao.com/i655557862281563150/`

```
HTTP/1.1 200 OK
Server: Tengine
Content-Type: text/html; charset=utf-8
Content-Length: 361
Connection: keep-alive
Date: Mon, 28 May 2018 16:48:17 GMT
Vary: Accept-Encoding
Vary: Accept-Encoding
Vary: Accept-Encoding
Vary: Accept-Encoding
X-TT-TIMESTAMP: 1527526097.426
Via: cache19.l2ot7[170,0], cache1.us1[181,0]
Timing-Allow-Origin: *
EagleId: 4266ff0115275260972842521e
```

**Comment by dupengshenyang** [comment]
think you

**Comment by dupengshenyang** [comment]
thanks
