### ISSUE TITLE
[Quertion][How to add retry function to pool?]

### ISSUE THREAD

**Issue by msaus** [guzzle/guzzle#2082]
Guzzelhttp: 6.3
PHP: 7.1

Hello there,

I would like to know how to add retry function in Guzzle client.

I just refer to following and made concurrent request.
http://docs.guzzlephp.org/en/stable/quickstart.html#concurrent-requests

Now, I need to add wait and retry the request when it is failed.

Could you tell me how to add to it?

thanks.

**Comment by gmponos** [comment]
> I manage it myself.

Thank you.. closing..
