### ISSUE TITLE
How to write log?

### ISSUE THREAD

**Issue by oneword** [guzzle/guzzle#2085]
| Q            | A
| ------------ | ---
| Bug?         | no
| New Feature? | no
| Version      | Specific version or SHA of a commit

#### Actual Behavior

What is the actual behavior?

write log for request and response.

#### Expected Behavior

What is the behavior you expect?

How to write log for request and response?

**Comment by sagikazarmark** [comment]
You could use the log middleware with a PSR-3 implementation or write your own if you have special needs:

https://github.com/guzzle/guzzle/blob/master/src/Middleware.php#L186
