### ISSUE TITLE
Promise::settle() with multidimensional array

### ISSUE THREAD

**Issue by roubenz** [guzzle/guzzle#2088]
| Q            | A
| ------------ | ---
| Bug?         | yes
| New Feature? | no
| Version      | 6.3.3

#### Given the code
```php
$promises = [
  'foo' => [
    'bar' => $client->getAsync('example.com')->then(function($response) { 
      printf('bar is fullfilled');
      return 'bar_value'; 
    })
  ]
];

$results = Promise\settle($promises)->wait();
var_dump($results);

```
#### Actual Behavior
Outputs:
```
bar is fullfilled
array(1) {
  'foo' => array(2) {
    'state' => "fullfilled"
    'value' => array(1) {
       'bar' => class GuzzleHttp\Promise\Promise#82 (6) { ...  }
    }
}
```

#### Expected Behavior
Should be:

```
bar is fullfilled
array(2) {
  'foo' => array(1) {  
    'bar' => array(2) {
      'state' => 'fullfilled',
      'value' => "bar_value"
    }
  }
}
```

It looks like its not handling multi-dimensional arrays correctly. The promise is successfully fullfilled, but the value is incorrect.

#### Steps to Reproduce

see above code

**Comment by Tobion** [comment]
Multidimensional arrays are not supported like you want. The nested array is treated as the fulfilled value as you can see. And I also don't think we need to make multidimensional arrays behave like this. Otherwise people wonder why they cannot have an arrays as promise fulfilled value.
