### ISSUE TITLE
cacert.pem is out of date

### ISSUE THREAD

**Issue by williamtwomey** [guzzle/guzzle#2089]
| Q            | A
| ------------ | ---
| Bug?         | yes
| New Feature? | no
| Version      | 3.9.3

#### Actual Behavior

PHP errors similar to:

Got error 'PHP message: PHP Fatal error: Uncaught exception 'Guzzle\\Http\\Exception\\CurlException' with message '[curl] 60: Peer's Certificate issuer is not recognized. [url] https://identity.api.rackspacecloud.com/v2.0/tokens' 

It appears the cacert.pem file in guzzle/guzzle/src/Guzzle/Http/Resources/ is very out of date. Replacing it with https://curl.haxx.se/ca/cacert.pem fixes this issue

#### Expected Behavior

No SSL errors for a valid cert

#### Steps to Reproduce

Accessing any page that uses guzzle results in a HTTP 500 

#### Possible Solutions

Replace cacert.pem with a new version

**Comment by sagikazarmark** [comment]
Guzzle 3 is not supported anymore, please upgrade to a newer version.

Alternatively you can configure `CURLOPT_CAINFO` to a custom cacert.pem file as seen in https://github.com/guzzle/guzzle3/blob/b3f5050cb6270c7a728a0b74ac2de50a262b3e02/src/Guzzle/Http/Client.php#L140
