### ISSUE TITLE
Guzzle return `502 Bad Gateway` error on some urls

### ISSUE THREAD

**Issue by arc92** [guzzle/guzzle#2090]
I have try this api url to get response but Guzzle return me 502 status code:

```
$url = https://www.aparat.com//etc/api/mostviewedvideos;
$guzzle = new Client;
$response = $guzzle->get($url)->getBody();
```

This code works find  with other urls

**Comment by sagikazarmark** [comment]
5xx errors indicate server side errors.

Besides, quotes are missing: `$url = 'https://www.aparat.com//etc/api/mostviewedvideos';`

**Comment by amir9480** [comment]
I had same problem with aparat API.
I solved problem by removing `User-Agent` from request.

```php
$client = new \GuzzleHttp\Client();
$res = $client->request('GET', 'https://www.aparat.com/etc/api/video/videohash/rzKus', [
    headers' => ['User-Agent' => null]
]);
```

**Comment by ggzomato** [comment]
$client = new GuzzleClient();
$response = $client->request('GET', 'http://httpbin.org/get');

Above is giving 502 Bad Gateway always. Can't seem to resolve this. Please help.
