### ISSUE TITLE
update doc about middleware

### ISSUE THREAD

**Issue by Cyrille37** [guzzle/guzzle#2094]
| Q            | A
| ------------ | ---
| Bug?         | no
| New Feature? | no
| Version      | 6.2

#### Actual Behavior

In the documentation at [Handlers and Middleware](http://docs.guzzlephp.org/en/stable/handlers-and-middleware.html#handlerstack) it's written : 
```
$stack = new HandlerStack();
$stack->setHandler(new CurlHandler());
```

#### Expected Behavior

If it was written : 
```
$stack = HandlerStack::create();
```
I did not spent hours to find why my POST call failed.

I find that GuzzleHttp [already add several middlewares](https://github.com/guzzle/guzzle/blob/master/src/HandlerStack.php#L41) that my code removed...

#### Possible Solutions

Add a sentence in documentation that alert about already existed middleware.

And thanks you very very much for this very great library !

Cheers, Cyrille.

**Comment by sagikazarmark** [comment]
The beginning of the documentation says:

```php

$handler = new CurlHandler();
$stack = HandlerStack::create($handler); // Wrap w/ middleware
```

It also mentions that `The create method adds default handlers to the HandlerStack`.

Later on the handler stack is used only to demonstrate certain middlewares or how the middleware chain works.

So I believe that the documentation actually covers everything that's necessary in a logical way. Your proposed change would defeat the purpose of explaining specific features in the specific sections of the documentation.

I'm sorry it took you so much time to find the problem, but I believe the proposed change wouldn't make things better.

**Comment by Cyrille37** [comment]
Ok, thanks.
