### ISSUE TITLE
nodejs DeprecationWarning: Buffer() is deprecated due to security and usability issues

### ISSUE THREAD

**Issue by Majkl578** [guzzle/guzzle#2097]
| Q            | A
| ------------ | ---
| Bug?         | yes
| Version      | master

#### Actual Behavior

```
(node:11819) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
```

#### Expected Behavior

No warning.

#### Steps to Reproduce

`make test`

#### Possible Solutions

~

**Comment by okdewit** [comment]
### Temporary solution: 
Use a very old nodejs version. Travis seems to use v0.6.14, but I found that `nvm install lts/argon` (using v4.9.1) also works.

### Better solution: 
Rewrite `server.js` to work on modern node versions.

**Comment by gmponos** [comment]
Resolved by https://github.com/guzzle/guzzle/pull/2517/files
