### ISSUE TITLE
Request parameters names containing dots get converted to underscores

### ISSUE THREAD

**Issue by jhigman** [guzzle/guzzle#21]
Request parameter names can legally contain dots - but they get converted to underscores by the query string processing.

Example: 

```
    $client = new \Guzzle\Http\Client();
    $request = $client->get("http://example.com/search?q=blah&facet.field=class");
```

will actually send a request like this:

```
            GET http://example.com/search?q=blah&facet_field=class
```

where "facet_field" should be "facet.field".

The problem may be caused by the use of the "parse_str" function in Url.php, which will convert spaces and dots into underscores.

**Comment by khuongphp** [comment]
You must use POST method and form_params key to send params have dots inside
following this link 
`https://stackoverflow.com/a/34411797/6407487`
