### ISSUE TITLE
Not working on PHP versions other than 5.4

### ISSUE THREAD

**Issue by Damirkhan** [guzzle/guzzle#2101]
When changing PHP to 5.6 , or to any newer version like 7.1, getting error:

[26-Jul-2018 06:51:49 UTC] PHP Fatal error:  Uncaught exception 'GuzzleHttp\Exception\ClientException' with message 'Client error: `POST http://ABC.net/wp-admin/admin-ajax.php` resulted in a `404 Not Found` response:
<!DOCTYPE html>

/api/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:111
Stack trace:
#0 /home/api/vendor/guzzlehttp/guzzle/src/Middleware.php(65): GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Psr7\Request), Object(GuzzleHttp\Psr7\Response))
#1 /home/api/vendor/guzzlehttp/promises/src/Promise.php(203): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Response))
#2 /home/api/vendor/guzzlehttp/promises/src/Promise.php(156): GuzzleHttp\Promise\Promise::callHandler(1, Object(GuzzleHttp\Psr7\Response), Array)
#3 /ho in /home/api/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php on line 111

What to do???????????????

**Comment by Nyholm** [comment]
Thank you for this issue. 
This has nothing to do with Guzzle. It is your server that answer with 404.
