### ISSUE TITLE
SeekException not used in Guzzle or any dependency

### ISSUE THREAD

**Issue by dol** [guzzle/guzzle#2102]
| Q            | A
| ------------ | ---
| Bug?         | no
| New Feature? | no
| Version      | 6.0.0

#### Actual Behavior
The class `GuzzleHttp\Exception\SeekException` is not used in any stream implemenations since 6.0.0.
It's also missing in the documentation.

#### Expected Behavior
Could it be removed.

#### Steps to Reproduce
```
composer require guzzlehttp/guzzle
fgrep -r SeekException .
```

#### Possible Solutions
Remove the class and tests of the class.

**Comment by sagikazarmark** [comment]
Thanks, indeed it looks like unnecessary.

**Comment by webignition** [comment]
I was just looking for any possible uses of `SeekException` to verify that I shouldn't need to catch such exceptions, came to the conclusion that `SeekException` is no longer used and was about to open an issue  to see if I was wrong.

Glad to see I wasn't wrong :smile:
