### ISSUE TITLE
json_encode options vs sending full json with body

### ISSUE THREAD

**Issue by tom76dc** [guzzle/guzzle#2105]
| Q            | A
| ------------ | ---
| Bug?         | no|yes
| New Feature? | no|yes
| Version      | Specific version or SHA of a commit

#### Actual Behavior

Hello,
I have a specific json value thats need to be send to a Odata2 server.  Dates must be formatted with slashes like this  
`date": "/Date(1354665600000)/",`

Unfortunatly the  function json_encode in functions.php will add  backslashes like this:
`date": "\/Date(1354665600000)\/",`

Then my json is invalid for the odata2 server.
In the Guzzle Documentation there is a [note](http://docs.guzzlephp.org/en/stable/request-options.html#json) on this. 

> This request option does not support customizing the Content-Type header or any of the options from PHP's json_encode() function. If you need to customize these settings, then you must pass the JSON encoded data into the request yourself using the body request option and you must specify the correct Content-Type header using the headers request option.

Unfortunatly when i try to use the body request option wiht the related content-type header it says, this is deprecated

`PHP Fatal error:  Uncaught InvalidArgumentException: Passing in the "body" request option as an array to send a POST request has been deprecated. Please use the "form_params" request option to send a application/x-www-form-urlencoded request, or the "multipart" request option to send a multipart/form-data request. `

#### Expected Behavior

Is the manual wrong that it tells me to use body instead of json? But then why doesnt it throws a deprecated error when i do. I just thought i could produce the Json myself with json_encode($postdata,JSON_UNESCAPED_SLASHES);

Thank you for looking. Be kind i'm new to OOP :)

**Comment by sagikazarmark** [comment]
> Passing in the "body" request option as an array to send a POST request has been deprecated

Why don't you just pass your encoded JSON string in the body option?

**Comment by tom76dc** [comment]
Hi @sagikazarmark ,

it must have been too late yesterday.. I did not send the string, but still the array.. my mistake ! :(

It does work as documented !

Thanks a lot, success with the project
KR
