### ISSUE TITLE
Allow nested query parameters to be parsed with build_query

### ISSUE THREAD

**Issue by morloderex** [guzzle/guzzle#2106]
| Q            | A
| ------------ | ---
| Bug?         | no
| New Feature? | yes
| Version      | 6.3.0

#### Actual Behavior

Tyring to build a query string with nested array's fails.

rawurlencode() expects parameter 1 to be string, array given (with encoding on)

without encoding 
Array to string conversion

#### Expected Behavior

I would expect the that the trying to parse a nested array to build_query actually builds the query.

The expected query string should be something like the fallowing (not escaped):

`filters[errors.status][][type]=eq&filters[errors.status][][value]=new&filters[error.assigned_to][][type]=ne&filters[error.assigned_to][][value]=12345&auth_token=xxx`

#### Steps to Reproduce

Pass in an array to params array that looks something like the fallowing.

$params parameter
```
"filters" => array:2 [
    "error.status" => array:1 [
      0 => [
        "type" => "eq"
        "value" => "new"
      ]
    ]
    "error.assigned_to" => [
      0 => [
        "type" => "ne"
        "value" => "12345"
      ]
    ]
  ]
  "auth_token" => "xxx" (removed for security reasons)
```
#### Possible Solutions

Use recoursion to build a query like this. But i don't have any implemmentation or pr that i can share just yet.

**Comment by morloderex** [comment]
anyone? No?

**Comment by sagikazarmark** [comment]
You should probably encode the query yourself and pass in a string.
