### ISSUE TITLE
Guzzle 5.3 and PHP 7.3

### ISSUE THREAD

**Issue by jenschude** [guzzle/guzzle#2111]
| Q            | A
| ------------ | ---
| Bug?         | yes
| New Feature? | no
| Version      | 5.3

#### Actual Behavior

Guzzle 5.3 errors when using PHP 7.3 (nightly on Travis) with following message:

```
"continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"?
guzzlehttp/guzzle/src/Message/MessageFactory.php:197
guzzlehttp/guzzle/src/Client.php:78
```

#### Expected Behavior

No error

#### Steps to Reproduce

Create a MessageFactory instance running on a PHP 7.3 runtime

**Comment by sagikazarmark** [comment]
Fixed in #2112
