### ISSUE TITLE
Guzzle hangs when executed under FastCGI on IIS 8.5

### ISSUE THREAD

**Issue by andybee** [guzzle/guzzle#2116]
| Q            | A
| ------------ | ---
| Bug?         | yes
| New Feature? | no
| Version      | 6.3.3

#### Actual Behavior

Guzzle hangs when performing the request. Script eventually times out, no error is thrown. Setting a timeout has no impact (and time elapses past timeout).

Tested on PHP 7.1.1 and PHP 7.2.8.

#### Expected Behavior

The request to complete.

#### Steps to Reproduce

This script causes the issue for us.

```<?php
error_reporting(E_ALL);

include "../vendor/autoload.php";

$client = new GuzzleHttp\Client([
    'timeout' => 5,
    'connect_timeout' => 5
]);

$response = $client->request('GET', 'http://example.com');
$body = $response->getBody();
echo $body;

echo ' END';
```

If we replace Guzzle with a boilerplate PHP cURL example it works as expected.

**Comment by sagikazarmark** [comment]
Can you try to trace the request (eg. with blackfire) to see where it hangs?

**Comment by andybee** [comment]
We've found out the root cause of the problem in our environment, cURL was unable to create a temporary files and errors cascaded down from there.

If anyone stumbles across this post 3 years from now and is wondering why their unusual combination of IIS, Windows Server, FastCGI and PHP is causing Guzzle to not work - try clearing C:\Windows\temp

🤦‍♂️

**Comment by sagikazarmark** [comment]
Great, glad you could find it.
