### ISSUE TITLE
Dont silently remove invalid Cookies in none-strict mode

### ISSUE THREAD

**Issue by leberknecht** [guzzle/guzzle#2126]
| Q            | A
| ------------ | ---
| Bug?         | no
| New Feature? | maybe
| Version      |  6.3.0

#### Actual Behavior

If we set a cookie with an invalid name, we silently ignore it if strict-mode is off

#### Expected Behavior

We should throw an exception, i dont see a use-case where it makes sense to silently ignore cookies which were explicitly set by the user but are malformed

#### Steps to Reproduce
```php
$cookieJar = new CookieJar(false, [
    './invalid' => 'cookie names must not start with .'
]);
$client = new Client();
$client->request('GET', 'http://needcookie.local', ['cookies' => $cookieJar]);
```
We will execute the request but cookies will be empty. 

#### Possible Solutions

Either we throw an exception so the user knows that something is not ok, or, as `strict` mode is off, maybe we just allow it..? (I actually have a real-world case, my current workaround is to set the cookie-data via `headers` on the request-options array.. that is ok'ish for me, but it took a bit to find the problem)

**Comment by gmponos** [comment]
The only place where we use the strict mode variable inside the `CookieJar` class is to throw an exception if the cookie is invalid.

https://github.com/guzzle/guzzle/blob/6.3.3/src/Cookie/CookieJar.php#L169

```
        // Only allow cookies with set and valid domain, name, value
        $result = $cookie->validate();
        if ($result !== true) {
            if ($this->strictMode) {
                throw new \RuntimeException('Invalid cookie: ' . $result);
            } else {
                $this->removeCookieIfEmpty($cookie);
                return false;
            }
        }
```

So I would like more info as why we need to throw an exception when a developer has specifically set the strict option to false.. Why not setting strict mode to true is not enough?

**Comment by leberknecht** [comment]
The behaviour of `strict` is very confusing here: If set, and the user specifies an invalid cookie-name, we run into an exception. Thats totally fine and exactly what a user would expect. But if we have `strict=false` and we use a malformed cookie-name, the cookie is silently ignored. That is unexpected and sub-optimal, as the only way to find out what is wrong is to debug/dig-into-vendor. In my case, a third party app required a cookie with a name that started with `.` to be present. Finding out that the cookie wasnt sent even though i specified it took some time. So if we could either tell the user "Hey, what you just tried wont happen", or (my fav) simply allow to send cookies with rfc-incompliant names when not in strict mode, would be much better here imho.

**Comment by gmponos** [comment]
Ah.. so the your request here is to send the cookie although it is invalid... got it but not sure if this is something we want :/

**Comment by leberknecht** [comment]
I think my problem is more the silent-ignore part. OK, its not completely silent, we _do_ have return `false`, but the user cant know if this means "Cookie with that name already exists" or "invalid name", so the user has to dig into the method to find out.
Also, if im not mistaken, we only drop the cookie with the invalid name if the cookie has no content. If it does have content, we allow it, no? That seems inconsistent to me. We should either: 
A) Not allow invalid names at all and raise the exception, no matter if strict or not or empty or not
Or B) allow invalid names if not-strict, no matter if the cookie is empty or not

So we are at least consistent.

**Comment by perice** [comment]
I just ran into the same issue.

The cookie with invalid name (OAMAuthnCookie_www.spar.si:443) was silently removed without any warnings or errors (when using the default $strict = false).

I agree with @leberknecht  that there should be a way to know that your cookies are getting removed.
Also, I'm not sure if it makes sense to remove cookies with invalid names at all, especially if the major browsers (Chrome, Firefox) support them.
