### ISSUE TITLE
How to send base64 encoded image data using POST request?

### ISSUE THREAD

**Issue by Dhavalptel** [guzzle/guzzle#2129]
Hi Guys, How can any one let me know how to send base64 encode image data using post request?
I am using this I am not sure this is the correct way to use it or not.
```
$response = $this->client->post('URL',[
            'multipart' => [
                'name'     => 'image',
                'contents' => ['image'=>$base64]
            ]
      ]);
```
This throws exception of `Type error: Argument 2 passed to GuzzleHttp\Psr7\MultipartStream::addElement() must be of the type array, string given`

Or Do I need to use form_params?
```
$response = $this->client->post('URL',[
            'form_params'=>['image' => $base64]
      ]);
```

**Comment by Dhavalptel** [comment]
@SebTM  That is throwing an error of  `Invalid resource type: array`

**Comment by SebTM** [comment]
Can you give us some more information what you are trying to do? What software/url are you calling? Can you link to documentation?

**Comment by Dhavalptel** [comment]
@SebTM  Any idea how I can achieve this?

**Comment by SebTM** [comment]
Hey @Dhavalptel,

sorry didn't had time before to check it again. Here is a working example:

`
<?php

// Loaded guzzlehttp/guzzle - v6.3 by composer
require_once __DIR__.'/vendor/autoload.php';

$uriBase = 'https://bws.bioid.com/extension/upload';
$path = 'https://upload.wikimedia.org/wikipedia/commons/3/37/Dagestani_man_and_woman.jpg';
$type = pathinfo($path, PATHINFO_EXTENSION);
$data = file_get_contents($path);
$base64 = 'data:image/' . $type . ';base64,' . base64_encode($data);
$token = 'YOUR TOKEN';

$client = new GuzzleHttp\Client();
$response = $client->post($uriBase,[
    'headers'=>['Authorization' => 'Bearer '.$token],
    'multipart' => [
        [
            'content-type' => 'test/plain',
            'contents' => $base64,
            'name' => 'file',
        ],
    ],
]);
echo $response->getBody()->getContents();
`

> Result: {"Accepted":false,"Error":"NoFaceFound"}

**Comment by Dhavalptel** [comment]
@SebTM  Thanks Man, That is working I was wondering, I have already converted the image to base64 then why do I need to multipart it again?

**Comment by SebTM** [comment]
Seems wired for me, too - also that file as name is just random picked and working. The documentation is really not that good here.

**Comment by Dhavalptel** [comment]
Yes that sucks, Anyway thanks man, I am closing this

**Comment by SebTM** [comment]
You are welcome! :)
