### ISSUE TITLE
How can I require composer autoloader?

### ISSUE THREAD

**Issue by moschel26** [guzzle/guzzle#2133]
I want to install guzzle https://github.com/guzzle/guzzle

I read the reference, but I'm confused this section :

[![enter image description here][1]][1]

From that tutorial, asking for require composer autoloader. So seems needed to add `require 'vendor/autoload.php';`
Where I add the script?

I using laravel 5.6

  [1]: https://i.stack.imgur.com/BkOO4.png

**Comment by sagikazarmark** [comment]
Chances are composer is already loaded by the framework if you use laravel.

**Comment by moschel26** [comment]
@sagikazarmark Okay thanks. I just made sure
