### ISSUE TITLE
Deal with token authentification

### ISSUE THREAD

**Issue by fabienlem** [guzzle/guzzle#2140]
| Q            | A
| ------------ | ---
| Bug?         | ?
| New Feature? | ?
| Version      | 6.3.3

I use guzzle to call an API with token authentification. First I have to call an endpoint with  login/password to get a token, then I can call other endpoints with the provided token.

My idea is to use an event subscriber to dynamically add the token to every guzzle transaction but it seems that it is not possible. Is there a way to achieve this?

Thank your for your help!

Fabien

**Comment by xZeroMCPE** [comment]
That's a bad practice for an API. Requests should be as-is, not 2.

**Comment by sagikazarmark** [comment]
If I were you I would separate the login call from the rest because it can get really hard to debug HTTP requests otherwise.

But if you still want to implement it that way, you can take a look at the middleware system in Guzzle.
