### ISSUE TITLE
POI Gadget Chain Path Traversal 

### ISSUE THREAD

**Issue by moggybaer** [guzzle/guzzle#2144]
| Q            | A
| ------------ | ---
| Bug?         | ??
| New Feature? | no
| Version      | 6.3.3 

#### Actual Behavior

RIPS Code Analysis Tool detects potential security issue.

Please read the attached PDF. We want to know if this is a false positif or not.

Thanks

**Comment by sagikazarmark** [comment]
@moggybaer can you please contact me privately with potential security issues? Disclosing them publicly before having the chance to examine the details is not responsible, please don't do that.

I saved the PDF and will take a look at it.

**Comment by moggybaer** [comment]
I am sorry. Did not find the right contact. Apologize for that.

**Comment by sagikazarmark** [comment]
No problem, as far as I can tell, this is a false positive report.

Note to self: update the readme with security contact.
