### ISSUE TITLE
Redirect not sending to external URL, sends post to internal app view

### ISSUE THREAD

**Issue by ThistleApps** [guzzle/guzzle#2148]
| Q            | A
| ------------ | ---
| Bug?         | Unknown
| New Feature? | No
| Version      | 5.3

#### Actual Behavior

I am using Laravel 5.6 with Guzzle 5.3 and am not being redirected to an external URL as specified in the post call.  Instead, I am being redirected to view within my own app.

#### Expected Behavior

Based on the documentation I would expect Guzzle to redirect me to the external URL and passing in the variable values from my array.

#### Steps to Reproduce

Dev project is located here.  https://github.com/ThistleApps/donate  

The key views are curchlist & churchpay.  The routes are in web.php and the key controller is ChurchController.

Essentially what I need to do is have the user successfully redirected to the external URL. However, the Guzzle ```REDIRECT_URL``` is pointing to an internal blade view of /churchpay/{id}.  It won't redirect the user to the external URL despite that URL being specified in the ```$response = $client ->post('https://demo.globalgatewaye4.firstdata.com/pay',```...

I am getting a 200 status code from the FirstData site (which means I passed in the right credentials) and the external site hosted payment page is returned inside my view without any kind of iframe.

**Comment by sagikazarmark** [comment]
Not sure if I understand your problem, but it looks like Guzzle is not the right tool in your case.

Guzzle is an HTTP client, it fetches the data from the URL and returns it to you. If you want the browser to be redirected to a URL, you don't need Guzzle, you need to use the framework's tools.

**Comment by ThistleApps** [comment]
But Guzzle performs an external post to forms?  No?

**Comment by sagikazarmark** [comment]
Guzzle can send POST requests to HTTP endpoints, but it's not the same as "filling in and posting a form" in a browser.

Guzzle itself can follow redirects, but you won't see that in the browser. Guzzle is an HTTP client, so as the browser. If you want the browser to be redirected to a different page, you don't need Guzzle.

**Comment by ThistleApps** [comment]
@sagikazarmark thanks for the confirmation.  I am getting the post data to work properly so I will continue to investigate on Laravel.
