### ISSUE TITLE
Query request option not merged with default value

### ISSUE THREAD

**Issue by wouterj** [guzzle/guzzle#2149]
| Q            | A
| ------------ | ---
| Bug?         | yes
| New Feature? | no
| Version      | 6.3.3

#### Steps to Reproduce

```php
<?php

$client = new \GuzzleHttp\Client([
    'base_uri' => 'https://maps.googleapis.com',
    'query' => [
        'key' => '...google api key...'
    ],
]);

$response = $client->get('/maps/api/distancematrix/json', [
    'query' => [
        'origins' => implode('|', $origins),
       // ...
    ],
]);
```

#### Actual Behavior

A request to:
```
GET https://maps.googleapis.com/maps/api/distancematrix/json?origins=some|cities
```

#### Expected Behavior

A request to:
```
GET https://maps.googleapis.com/maps/api/distancematrix/json?key=googleKey&origins=some|cities
```

#### Possible Solutions

https://github.com/guzzle/guzzle/blob/c7faf23816251ca3f35463c55f3178a9b60128fc/src/Client.php#L235-L236

I understand that most options are shallow merged and fully deep merging of query parameters is also unwanted (i.e. #1452 ).

I think what should be done is shallow merging the query option on it's own, i.e.:

```diff
+ if (isset($defaults['query']) && isset($options['query'])) {
+     $options['query'] = $options['query'] + $defaults['query'];
+ }
 
  $result = $options + $defaults;
```

**Comment by sagikazarmark** [comment]
I'm not sure that's the expected behavior with query parameters. With your proposal it would be impossible to not send certain query parameters without overriding it.

If you need this kind of behavior, I would suggest implementing a custom middleware which adds the query parameter to each request. That way you can even enforce accidental overwrites of the parameter by always setting it to a specific value in the middleware.

**Comment by projct1** [comment]
Still actual...

**Comment by OL1salisbury** [comment]
I agree with the original poster, if I am setting query params in the client I would expect these to get merged with any further params added in the request.

Here's a good use case:

````
$client = new Client([
    'base_uri' => $base_uri,
    'query' => [
        'api_key' => $api_key,
    ]
]);

$response = $client->request('GET', $uri, [
    'query' => [
        'all' => 'true'
    ]
]);
````

If I wanted to unset a param for a specific request, perhaps I could just nullify it:

````
$response = $client->request('GET', $uri, [
    'query' => [
        'api_key' => null
    ]
]);
````
