### ISSUE TITLE
Minor issue with default User Agent with cURL naming

### ISSUE THREAD

**Issue by Geolim4** [guzzle/guzzle#2152]
| Q            | A
| ------------ | ---
| Bug?         | yes
| New Feature? | no
| Version      | ^6.0

#### Actual Behavior

Default user-agent is set to `GuzzleHttp/x.x.x curl/x.x.x PHP/x.x.x`

#### Expected Behavior

Well-named 'cURL' word: `GuzzleHttp/x.x.x cURL/x.x.x PHP/x.x.x`

Or at least upper-cased (like PHP does, actually):
Well-named 'cURL' word: `GuzzleHttp/x.x.x CURL/x.x.x PHP/x.x.x`

#### Steps to Reproduce

N/A

#### Possible Solutions

I can provide a PR if needed & issue is accepted.

**Comment by sagikazarmark** [comment]
I don't think there is anything wrong here. cURL's default user agent is formed that way:

<img width="1312" alt="screen shot 2018-09-28 at 14 00 05" src="https://user-images.githubusercontent.com/1226384/46207245-fc11d200-c326-11e8-9207-a01f1f1a9c73.png">
