### ISSUE TITLE
Feature Request | Retrieve certificate of peer

### ISSUE THREAD

**Issue by kloentje2** [guzzle/guzzle#2153]
| Q            | A
| ------------ | ---
| Bug?         | no
| New Feature? | yes
| Version      | N/A

Currently I'm using a build in PHP function (with a lot of lines of code) to get the certificate the peer is sending to me over HTTPS. Can you guys include that in Guzzle? 

So we can use it like this:

```php
<?php
echo $client->peerCertificate();
/*-----BEGIN CERTIFICATE----- 
a lot of
charachters
-----END CERTIFICATE----- 
*/
?>
```

**Comment by sagikazarmark** [comment]
Transport level security is out of the HTTP scope, so I doubt it should be added here.
