### ISSUE TITLE
Curl error 7 Connection refused on non standard ports

### ISSUE THREAD

**Issue by maximl337** [guzzle/guzzle#2154]
| Q            | A
| ------------ | ---
| Bug?         | yes
| New Feature? | no|yes
| Version      | 6.3

#### Actual Behavior

What is the actual behavior?
When I try to make a request to a resource with a non standard port I get the following error:
cURL error 7: Failed to connect to service-stub port 3000: Connection refused (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)

#### Expected Behavior

What is the behavior you expect?
Should complete request without throwing an error

#### Steps to Reproduce

What are the steps to reproduce this bug? Please add code examples,
screenshots or links to GitHub repositories that reproduce the problem.
`cURL error 7: Failed to connect to service-stub port 3000: Connection refused (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)`
`$resp = $this->client->get('localhost:3000');`

#### Possible Solutions

If you have already ideas how to solve the issue, add them here.
(remove this section if not needed)

**Comment by cpass78** [comment]
@maximl337 use Request instead

**Comment by maximl337** [comment]
> @maximl337 use Request instead

@cpass78 You mean like this:

`$res = $client->request('GET', '/redirect/3', ['allow_redirects' => false]);`

**Comment by marvingitau** [comment]
I to have a similar issue!
