### ISSUE TITLE
Client exception is missing when passed sink|save_to option

### ISSUE THREAD

**Issue by Koc** [guzzle/guzzle#2160]
| Q            | A
| ------------ | ---
| Bug?         | yes
| New Feature? | no
| Version      | 6.3.3

#### Actual Behavior

When I pass `sink` option to request and target url returns 404 client throws `\RuntimeException` with message "Cannot read from non-readable stream". Without this option we got expected exception  `GuzzleHttp\Exception\ClientException` with response body.

#### Expected Behavior

Expecting get `GuzzleHttp\Exception\ClientException` in both cases.

#### Steps to Reproduce
```php
$options = [
    RequestOptions::SINK => stream_for(fopen($path, 'wb')),
];

try {
    $response = $this->httpClient->request('GET', $url, $options);
} catch (\Throwable $e) {
    dump(get_class($e));
}

```

Next code can be used as workaround, but IMHO better to be consistent and always throw same exception.
```php
copy_to_stream($response->getBody(), stream_for(fopen($path, 'wb')));
```

**Comment by mfrsousa** [comment]
I also have the same problem

**Comment by gmponos** [comment]
I tried a simple reproducer on a local machine and it works fine:

```
<?php

use GuzzleHttp\Client;
use GuzzleHttp\RequestOptions;
use function GuzzleHttp\Psr7\stream_for;

require_once 'vendor/autoload.php';

try {
    $client = new Client();
    $response = $client->request('GET', 'https://httpbin.org/status/404', [
        RequestOptions::SINK => stream_for(fopen(__DIR__ . '/log.txt', 'wb')),
    ]);
} catch (\Throwable $e) {
    var_dump(get_class($e));die;
}

var_dump($response->getStatusCode());
```

outputs:

```
> php index.php 
string(36) "GuzzleHttp\Exception\ClientException"
```

I see that you use `dump` so I guess this code lives inside a framework (laravel/symfony). could it be any access rights issue.. Can you try a simple reproducer as the above?

**Comment by Koc** [comment]
Indeed, seems that it caused by framework integration. TBH I haven't anymore access to code that could reproduce issue (using framework integration). Not a Guzzle issue
