### ISSUE TITLE
Problem with proxy

### ISSUE THREAD

**Issue by M0H314-hasani** [guzzle/guzzle#2169]
| Q            | A
| ------------ | ---
| Bug?         | yes
| New Feature? | yes
| Version      | Specific version or SHA of a commit

#### Actual Behavior

I am getting error for proxies that contain  `@` in username or password by default pattern : 
    
     $client->request('GET', '/', [
      'proxy' =>"http://username:password@192.168.16.1:10",
      ]);

#### Expected Behavior

This is for `@` as special character in default pattern.

#### Steps to Reproduce

just use a proxy that contain `@` 

#### Possible Solutions

I send it as a pull request.

**Comment by M0H314-hasani** [comment]
pull request sent.[#2170](https://github.com/guzzle/guzzle/pull/2170)

**Comment by gmponos** [comment]
Closing as commented here: https://github.com/guzzle/guzzle/pull/2170#issuecomment-562980690
