### ISSUE TITLE
problem with google API

### ISSUE THREAD

**Issue by joefreire** [guzzle/guzzle#2175]
I try send a google place api search with this command

>         $client = new Client();
>         $res = $client->request('GET', $url,[
>             'query' => [
>                 'type' => 'gas_station',
>                 'query' => 'Uberlandia,MG',
>                 'key' => 'MYKEY',
>             ],
>         ]);

And this return a wrong result
{"html_attributions":[],"results":[],"status":"ZERO_RESULTS"}

but this query is ok, if i try in postman or in browser this return results

https://maps.googleapis.com/maps/api/place/textsearch/json?type=gas_station&query=Uberlandia%2CMG&key=MYKEY

I have see a diference between the results using guzzle and the query from google

how i can solve this issue? or i'm doing something wrong?

best regards

**Comment by joefreire** [comment]
I try use 

>         $client = new Client();
>         $res = $client->request('GET', $url,[
>             'headers' => [
>                 'User-Agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36',
>                 'Accept'     => 'application/json',
>                 'cache-control'      => 'no-cache'
>             ],
>             'query' => [
>                 'type' => 'gas_station',
>                 'query' => 'Uberlandia,MG',
>                 'key' => 'MYKEY',
>             ],
>             'on_stats' => function (TransferStats $stats) use (&$url) {
>                 $url = $stats->getEffectiveUri();
>             }
>         ]);

to see url and is like i put on postman or browse

**Comment by gmponos** [comment]
This issue seems more of a support question rather than a bug or a feature request. 

For support questions it is preferable to use other channels like the ones mentioned here: https://github.com/guzzle/.github/blob/master/SUPPORT.md
