### ISSUE TITLE
timeout delay 1s which I set custom config timeout is 2.1s

### ISSUE THREAD

**Issue by ElephantWhite** [guzzle/guzzle#2181]
# description:
```
cURL error 28:Operation timed out after 3100 milliseconds with 0 out of -1 bytes received(see http://curl.haxx.se/libcurl/c/libcurl-errors.html)
```
# env:
   - os : centos 7.5
   - php version : 7.1
   - guzzlehttp version : 6.2.1
   - network : no ipv6, LAN

**Comment by CocoaJerry** [comment]
同问，也遇到这个问题了

**Comment by gmponos** [comment]
The issue misses code context. Please refer to https://github.com/guzzle/.github/blob/master/SUPPORT.md for more support.
