### ISSUE TITLE
Future of guzzle with PSR-17 and PSR-18

### ISSUE THREAD

**Issue by gmponos** [guzzle/guzzle#2186]
Hello,

I just saw the [tweet](https://twitter.com/TobiasNyholm/status/1057562838217179136) of @Nyholm about the first tag of psr/http-client. I am super excited about this. Great job you guys.

I am starting this issue in order to share some thoughts about guzzle and PSRs

1. First of all will there be a new package of guzzle implementing PSR-17?
2. Will you continue supporting options? I know that PSR-18 does not allow options. So what I am asking is if guzzle will continue supporting or if you would consider supporting something like this:

```
$request = $factory->createRequest('get', 'http://www.test.com');
$request = GuzzleHttp\function\apply_options($request, $options);
$client->send($request);
```

if not... what will be the main advantage of someone using guzzle instead of httplug?

3. Would you consider starting a new branch accepting contributions? I am willing to help here.
4. Also what will happen with async functions? Will you continue supporting them without options?

**Comment by sagikazarmark** [comment]
> First of all will there be a new package of guzzle implementing PSR-17?

Implementing PSR-17 is already in progress and the code will be part of the PSR-7 package. The naming is a little bit unfortunate, but it provides the most flexibility in our opinion.

> Will you continue supporting options?

Guzzle will eventually implement PSR-18 directly. We will try to limit the number of breaks to as small as possible. Also, we will keep Guzzle's rich API.

> if not... what will be the main advantage of someone using guzzle instead of httplug?

HTTPlug consists of a number of different components:

1. HTTP Client contract which will mainly be replaced by PSR-18
2. Adapter packages which provide a thin layer between clients limited to the standard (compared to Guzzle's rich API)
3. A number of HTTP related components relying on HTTPlug/PSR-18

With the standard out adapter packages will probably become obsolete eventually, once clients themselves implement the standard, but the rest of the ecosystem will remain (plugins, message tools, etc).

> Would you consider starting a new branch accepting contributions? I am willing to help here.

We are still evaluating options and concentrate on PSR-17 first, but we will certainly accept contributions. I'll let you know once we start working on PSR-18/PHP 7.x implementation.

> Also what will happen with async functions? Will you continue supporting them without options?

As mentioned earlier, Guzzle's API will remain as it is for most of it's part and we will keep all the features, so I don't expect major changes here.

**Comment by gmponos** [comment]
Let me see if I understood correctly.

Judging by [this PR](https://github.com/guzzle/guzzle/pull/2122/files) and your answer the goal is to keep all the current functions of guzzle as they are and only add the new function `sendRequest` that must be implemented by the interface.

If the above is correct don't you believe that it will keep the developers depending on Guzzle instead of PSR?



Let me show you my case in order to explain a little better. In most of my code what I would like to do is this:

```
class MyWhateverClass {

    private $client;

    public function __construct(\Psr\Http\Client\ClientInterface $client) {
        $this->client = $client;
    }

    public function consumeAnApi(string $username) {
        $request = new Request('get', "www.dummyapi.com/api?username=$username");
        $this->client->sendRequest($request);
    }
}
```

The above is a simple scenario. When it comes to more complex scenarios like sending a request with a json body or using authentication headers etc etc. you have to manually build the request. Most of this work was already done by guzzle inside the function `applyOptions` ([here](https://github.com/guzzle/guzzle/blob/master/src/Client.php#L291)) when you pass the `options`. 

If we could extract `applyOptions` function and instead of manually building the request as above do this:

```
    public function consumeAnApi(string $username) {
        $request = new Request('get', "www.dummyapi.com/api");
        $request = \GuzzleHttp\apply_options($request, ['query' => ['username' => $username]]);
        $this->client->sendRequest($request);
    }
```

I know that the example above is still coupled with Guzzle package. What I can do to remove this dependency is to create another class and inject in the constructor of `MyWhateverClass` a `RequestModifierInterface`

```
class GuzzleRequestModifier implements RequestModifierInterface {
   public function modifyRequest($request){
		\GuzzleHttp\apply_options($request, ['query' => ['username' => $username]]);
   }
}
```

Let me know what you think...

**Comment by dambrogia** [comment]
Are there any updates on this? I have taken a look at guzzle/guzzle and guzzle/psr7 today and haven't seen anything related to a PSR-18 ClientInterface or PSR-17 factories in their master branches. If this has been implemented or is in progress can you please point me in the right direction for more information?

**Comment by gnumoksha** [comment]
@dambrogia you can use https://github.com/php-http/guzzle6-adapter.

The bad thing I'm experiencing with my team is the more verbose way to create an HTTP request. They seem to find it complicated. So @gmponos's suggestion is very welcome.
