### ISSUE TITLE
Default header is overridden with json option

### ISSUE THREAD

**Issue by tomasfejfar** [guzzle/guzzle#2190]
| Q            | A
| ------------ | ---
| Bug?         | yes
| New Feature? | no
| Version      | v. 6.3.3

#### Actual Behavior

Content type is `application/json`. 

#### Expected Behavior

Content type is `application/json; charset=utf-8`. Because

> The json option is used to easily upload JSON encoded data as the body of a request. A Content-Type header of application/json will be added if no Content-Type header is already present on the message.
> http://docs.guzzlephp.org/en/stable/request-options.html#json

#### Steps to Reproduce

```
<?php
require_once 'vendor/autoload.php';
$client = new GuzzleHttp\Client([
    'debug' => true,
    'headers' => [
        'Content-type' =>  'application/json; charset=utf-8', // <---- set here as default
    ],
]);

$response = $client->post('http://example.com/', [
    'json' => ['any' => 'data'] // <-------- overridden although another default is set
]);
```

#### Possible Solutions
<img src="https://user-images.githubusercontent.com/642928/47995339-41c77480-e0f5-11e8-82e9-760d0ed0cf37.png" width="100">

**Comment by gmponos** [comment]
> Note
> This request option does not support customizing the Content-Type header or any of the options from PHP's json_encode() function. If you need to customize these settings, then you must pass the JSON encoded data into the request yourself using the body request option and you must specify the correct Content-Type header using the headers request option.
> This option cannot be used with body, form_params, or multipart

Are the docs answering your question?

http://docs.guzzlephp.org/en/stable/request-options.html#json

**Comment by agungtri222** [comment]
Is there any solution for this issue? I've faced this issue and have no idea how to solves it.

**Comment by tomasfejfar** [comment]
The docs do answer my question. 

I don't think that the behavior is cool though. It should ensure that the Content-Type is correct (check and set if wrong) instead of plain overwriting it.

**Comment by axklim** [comment]
@gmponos 
The docs is really ambiguous :( May be I@ can fix it ? Or change this behaviour  ?
