### ISSUE TITLE
PHP 7.2 Parameter must be an array or an object that implements Countable

### ISSUE THREAD

**Issue by phpclub** [guzzle/guzzle#2191]
| Q            | A
| ------------ | ---
| Bug?         | yes
| New Feature? | no
| Version      | Specific version or SHA of a commit

#### Actual Behavior

What is the actual behavior?

#### Expected Behavior
ErrorException: count(): Parameter must be an array or an object that implements Countable in bvrs.holder.ru/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:67

hat is the behavior you expect?

#### Steps to Reproduce

What are the steps to reproduce this bug? Please add code examples,
screenshots or links to GitHub repositories that reproduce the problem.

#### Possible Solutions

If you have already ideas how to solve the issue, add them here.
(remove this section if not needed)

**Comment by gmponos** [comment]
You are not mentioning your guzzle version. I guess you need to update.

https://github.com/guzzle/guzzle/blob/master/CHANGELOG.md#630---2017-06-22

> Bug fix: PHP 7.x fixes #1686

**Comment by manoshatzi** [comment]
Unfortunately this is an issue with count and php7. I have the version 6 of Guzzle and version 7.2 of php and i have the same issue
