### ISSUE TITLE
polish letters encoding failed for http get address

### ISSUE THREAD

**Issue by gileneusz** [guzzle/guzzle#2193]
| Q            | A
| ------------ | ---
| Bug?         |yes
| New Feature? | no|
| Version      | Specific version or SHA of a commit

#### Actual Behavior

What is the actual behavior?
I'm trying to access google maps api:

https://maps.googleapis.com/maps/api/geocode/json?address=ul.%20Rzgowska%20281/289,+93-338+%C5_%C3%B3d%C5%BA,+Poland&key=

and this gives google response:  "Invalid request. One of the input parameters contains a non-UTF-8 string."

part:
%C5_%C3%B3d%C5%BA
is encoded from polish word "Łódź"

and the letter "Ł" causing this error, if I remove "Ł" letter it passes. Please check decoding for polish letters

#### Expected Behavior

What is the behavior you expect?
Should accept any properly converted utf-8

#### Steps to Reproduce

What are the steps to reproduce this bug? Please add code examples,
screenshots or links to GitHub repositories that reproduce the problem.
Try make a call
$result = $client->request('GET', 'https://maps.googleapis.com/maps/api/geocode/json?address='Łódź,+Poland&key=YOUR_API_KEY');

#### Possible Solutions

If you have already ideas how to solve the issue, add them here.
(remove this section if not needed)

**Comment by sabat24** [comment]
It's not strict a Guzzle. Response comes from Google geocoding service. 

You may have got some non-printable characters, so you could use:  ```preg_replace('/[^\PC\s]/u', '', $input);``` to remove it from requested url. I checked your example and it works fine.
