### ISSUE TITLE
GuzzleException should extend Throwable

### ISSUE THREAD

**Issue by maikelsalazar** [guzzle/guzzle#2196]
Working with IDEs (i.e PHPStorm) will always mark a warning because you don't catch a `GuzzleException`. But, you can't catch anything that doesn't extend `Throwable`. `GuzzleException` should extend `Throwable`.

**Comment by gmponos** [comment]
duplicate of https://github.com/guzzle/guzzle/issues/2184 ???

**Comment by maikelsalazar** [comment]
Oh, yes, thank you @gmponos!
