### ISSUE TITLE
Guzzle FileCookieJar failed to open stream: Permission denied

### ISSUE THREAD

**Issue by phamquangbaoplus** [guzzle/guzzle#2198]
I try to run file_put_contents('cookie.txt', 'content'); stand alone, it OK

The cookie.txt file is 777 chmod

But with guzzle FileCookieJar:

Warning: file_put_contents(cookie.txt): failed to open stream: Permission denied in /home/domain/public_html/includes/guzzle/vendor/guzzlehttp/guzzle/src/Cookie/FileCookieJar.php on line 59

Fatal error: Uncaught RuntimeException: Unable to save file cookie.txt in /home/domain/public_html/includes/guzzle/vendor/guzzlehttp/guzzle/src/Cookie/FileCookieJar.php:60 Stack trace: #0 /home/domain/public_html/includes/guzzle/vendor/guzzlehttp/guzzle/src/Cookie/FileCookieJar.php(39): GuzzleHttp\Cookie\FileCookieJar->save('cookie.txt') #1 [internal function]: GuzzleHttp\Cookie\FileCookieJar->__destruct() #2 {main} thrown in /home/domain/public_html/includes/guzzle/vendor/guzzlehttp/guzzle/src/Cookie/FileCookieJar.php on line 60

Please help.

![2018-11-15 10_00_57-apkmody c__users_user_phpstormprojects_apkmody - _2bac16a6-75e1-44f0-bc87-5060](https://user-images.githubusercontent.com/23471646/48527336-68d43200-e8bd-11e8-9b33-3a4dabf75d11.png)

**Comment by Nyholm** [comment]
Every help you need is in the exception message. 

You cannot write to "cookie.txt" because of your filesystem's permissions.

**Comment by derDeno** [comment]
I got the same problem and same as phamquangbaoplus my filesystem has chmod 777, so there shouldn't be any problem.

file_put_contents alone works in a separate file but not in combination with guzzle for some reason. Some more help would be really nice because i cant figure it out why it throws this error message.

regards

**Comment by Nyholm** [comment]
It is about *where* the file is stored. 

Please refer to Stackoverflow or similar to get help.
