### ISSUE TITLE
PHP 7.2 - Request with no hearders - error on _caseless_remove()

### ISSUE THREAD

**Issue by ruicampos** [guzzle/guzzle#2199]
| Q            | A
| ------------ | ---
| Bug?         | yes
| New Feature? | no
| Version      | 6.3.3

#### Actual Behavior

What is the actual behavior?

Sending a request without header will result in a error in the call to the method  `Psr7\_caseless_remove()`

This is caused by passing a `null` to the function that expects an `array` - which raises an error in PHP 7.2

Error: 
```
Argument 2 passed to GuzzleHttp\Psr7\_caseless_remove() must be of the type array, null given, called in .../vendor/guzzlehttp/guzzle/src/Client.php on line 313" {"exception":"[object] (TypeError(code: 0): Argument 2 passed to GuzzleHttp\\Psr7\\_caseless_remove() must be of the type array, null given, called in .../vendor/guzzl
ehttp/guzzle/src/Client.php on line 313 
```

#### Expected Behavior

What is the behavior you expect?

No error to be thrown.

#### Steps to Reproduce

What are the steps to reproduce this bug? Please add code examples,
screenshots or links to GitHub repositories that reproduce the problem.

- Install PHP 7.2.12
- Invoke a new request (POST, GET) without headers - headers set as null

#### Possible Solutions

If you have already ideas how to solve the issue, add them here.
(remove this section if not needed)

1. Change `Psr7\caseless_remove()` to not force second argument as array and in case it is not array return `[]``
2. Update all calls to `Psr7\caseless_remove()` to check if second argument passed is an array and pass an empty array instead.

**Comment by Highvolt** [comment]
Fixed by this pull request https://github.com/guzzle/guzzle/pull/2201

**Comment by Prizephitah** [comment]
+1

**Comment by gmponos** [comment]
Fixed by https://github.com/guzzle/guzzle/pull/2259
