### ISSUE TITLE
Request parameters with same names get overwritten

### ISSUE THREAD

**Issue by jhigman** [guzzle/guzzle#22]
The same request parameter name can appear more than once in an http query string - but the processing of the request string means that all but the last occurrence are lost.

Example:

```
    $client = new \Guzzle\Http\Client();
    $request = $client->get("http://example.com/search?q=blah&facet=class&facet=property");
```

will result in a request like this being sent:

```
           http://example.com/search?q=blah&facet=property
```

but should be:

```
           http://example.com/search?q=blah&facet=class&facet=property
```

**Comment by natostanco** [comment]
what about posting parameters with same name?

**Comment by kevinohashi** [comment]
Was this removed at some point? How would one do it in Guzzle 7?
