### ISSUE TITLE
Is this correct approche to  async processes and why I am getting this error?

### ISSUE THREAD

**Issue by beshoo** [guzzle/guzzle#2206]
Dear all, I am trying to make async processes 
I need to pass a different proxy with each Request, so I found this example, but it has an output error. please advice
```
<?php

include './vendor/autoload.php';


use GuzzleHttp\Client;
use GuzzleHttp\Psr7\Request;


$handler = \GuzzleHttp\HandlerStack::create();

$iterator = function () use ($handler) {
    $index = 0;
    while (true) {
        if ($index === 30) {
            break;
        }

        $client = new Client(['timeout' => 20, 'handler' => $handler]);
        $url = "https://www.url.com/ip.php";
        $request = new Request('GET', $url, []);
        yield $client
            ->sendAsync($request)
            ->then(function (Response $response) use ($request) {
                return [$request, $response];
            });

    }
};

$promise = \GuzzleHttp\Promise\each_limit(
    $iterator(),
    30,  /// concurrency,
    function ($result, $index) {
        /** @var GuzzleHttp\Psr7\Request $request */
        list($request, $response) = $result;
        echo (string)$request->getUri() . ' completed ' . PHP_EOL;
    }
);
$promise->wait();

```

But I am getting this error 
`
Catchable fatal error: Argument 1 passed to {closure}() must be an instance of Response, instance of GuzzleHttp\Psr7\Response given, called in /vendor/guzzlehttp/promises/src/Promise.php on line 203 and defined in http4.php on line 27`

What I am missing here?

**Comment by jeremeamia** [comment]
On the line that looks like
```php
    ->then(function (Response $response) use ($request) {
```
You are referencing the `Response` class, but you haven't imported it with a `use` statement. PHP thinks it is some `\Response` class at the root namespace, so when Guzzle returns the correctly namespaced response class, it doesn't match.

You need to put
```php
use GuzzleHttp\Psr7\Response;
```
at the top

**Comment by beshoo** [comment]
Thank you so much, how dumb I am :)

**Comment by beshoo** [comment]
@jeremeamia , it works but I like to ask you , I set this to change the proxy on each request 
```
$proxy = 'https://user@pass:proxy.com:3444';
$request = new Request('GET', $url, [
    'proxy' => [
        'https' => $proxy
    ]
);
```

but when I run the script it show my server ip 
NOTE: I called URL content

`print $_SERVER['REMOTE_ADDR'];`

why it does not pass my proxy to the request?
