### ISSUE TITLE
403 Forbidden Help Me !

### ISSUE THREAD

**Issue by rapcrown** [guzzle/guzzle#2208]
Plase help me php 7.0 client error log.

`
use GuzzleHttp\Client;
use Tuna\CloudflareMiddleware;
use GuzzleHttp\Cookie\FileCookieJar;

$client = new Client(['cookies' => new FileCookieJar('testt.txt')]);

$test  = $client->getConfig('handler')->push(CloudflareMiddleware::create());

$res = $client->request('GET', 'https://www.koreanturk.com/');
echo $res->getBody();

`

`[17-Nov-2018 10:30:56 Europe/Istanbul] PHP Fatal error:  Uncaught GuzzleHttp\Exception\ClientException: Client error: `GET https://www.koreanturk.com/` resulted in a `403 Forbidden` response:
 in /home/botmerkezi/public_html/ff/guzzle-master/src/Exception/RequestException.php:113
Stack trace:
#0 /home/botmerkezi/public_html/ff/guzzle-master/src/Middleware.php(66): GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Psr7\Request), Object(GuzzleHttp\Psr7\Response))
#1 /home/botmerkezi/public_html/ff/guzzle-master/vendor/guzzlehttp/promises/src/Promise.php(203): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Response))
#2 /home/botmerkezi/public_html/ff/guzzle-master/vendor/guzzlehttp/promises/src/Promise.php(156): GuzzleHttp\Promise\Promise::callHandler(1, Object(GuzzleHttp\Psr7\Response), Array)
#3 /home/botmerkezi/public_html/ff/guzzle-master/vendor/guzzlehttp/promises/src/TaskQueue.php(47): GuzzleHt in /home/botmerkezi/public_html/ff/guzzle-master/src/Exception/RequestException.php on line 113
`

**Comment by rapcrown** [comment]
[17-Nov-2018 10:30:56 Europe/Istanbul] PHP Fatal error:  Uncaught GuzzleHttp\Exception\ClientException: Client error: `GET https://www.koreanturk.com/` resulted in a `403 Forbidden` response:
<!DOCTYPE html>

<!--[if IE 7]>    <html class (truncated...)
 in /home/botmerkezi/public_html/ff/guzzle-master/src/Exception/RequestException.php:113
Stack trace:
#0 /home/botmerkezi/public_html/ff/guzzle-master/src/Middleware.php(66): GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Psr7\Request), Object(GuzzleHttp\Psr7\Response))
#1 /home/botmerkezi/public_html/ff/guzzle-master/vendor/guzzlehttp/promises/src/Promise.php(203): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Response))
#2 /home/botmerkezi/public_html/ff/guzzle-master/vendor/guzzlehttp/promises/src/Promise.php(156): GuzzleHttp\Promise\Promise::callHandler(1, Object(GuzzleHttp\Psr7\Response), Array)
#3 /home/botmerkezi/public_html/ff/guzzle-master/vendor/guzzlehttp/promises/src/TaskQueue.php(47): GuzzleHt in /home/botmerkezi/public_html/ff/guzzle-master/src/Exception/RequestException.php on line 113

**Comment by alexeyshockov** [comment]
You receive `403 Forbidden` response, that's clear from the exception. Please, specify the expected results, otherwise it's not possible to help you.

**Comment by Nyholm** [comment]
Please ask on Stackoverflow or similar. This is not related to Guzzle.

**Comment by minhhieu08** [comment]
But when i call it in postman, it return excatly result i expected. So what is wrong here?

**Comment by kacperplacha** [comment]
@minhhieu08 Try with different 'User-Agent', maybe your server has some filters.

**Comment by FabianKoestring** [comment]
I had the same Problem. `Accept` Header for the rescue ... 👌
