### ISSUE TITLE
Mockhandler: OutOfBoundsException: Mock queue is empty

### ISSUE THREAD

**Issue by GagaMen** [guzzle/guzzle#2209]
| Q            | A
| ------------ | ---
| Bug?         | yes
| New Feature? | no
| Version      | 6.3

#### Actual Behavior

I try to test my service class, which sends a get request to an external REST-API. I follow these quidelines:

- http://www.inanzzz.com/index.php/post/7cwp/mocking-guzzle-and-testing-external-api-with-phpunit
- https://wellingguzman.com/notes/guzzle-http-upgrade-mocking-from-version-5-to-6

and read also the documentation, but i get always a OutOfBoundsException if I run the test.

Here is my class:
```
class PaladinsApiService
{
    protected const API_ENTRY_POINT = 'http://api.paladins.com/paladinsapi.svc/';
    protected $devId = '';
    protected $authKey = '';
    protected $requestClient;

    public function __construct($devId, $authKey, $requestClient = null)
    {
        $this->devId = $devId;
        $this->authKey = $authKey;
        $this->requestClient = $requestClient;
    }

    public function calculateSignature($method): string
    {
        $date_utc = new \DateTime("now", new \DateTimeZone("UTC"));
        $timestamp = $date_utc->format('YmdHis');

        return md5($this->devId . $method . $this->authKey . $timestamp);
    }

    public function getSessionFromApi(): string
    {
        $response = null;
        try {
            $signature = $this->calculateSignature('createsession');
            $date_utc = new \DateTime("now", new \DateTimeZone("UTC"));
            $timestamp = $date_utc->format('YmdHis');

            // this line throws the error because there is no response in the queue
            $response = $this->requestClient->get(self::API_ENTRY_POINT . "createsessionJson/{$this->devId}/$signature/$timestamp");
        } catch (\Exception $exception) {
            echo $exception;
        }

        return $response->getBody()->getContents();
    }

    // Getter and setter
    ...
}
```

My test:
```
class PaladinsApiServiceTest extends TestCase
{
    protected $cut;
    protected $mockHandler;
    protected $devId = '1234';
    protected $authKey = '23FDA345DAF523FSDAF32341DAFDSDA3';

    public function setUp()
    {
        $this->mockHandler = new MockHandler();

        $requestClient = new Client([
            'handler' => $this->mockHandler,
        ]);

        $this->cut = new PaladinsApiService($this->devId, $this->authKey, $requestClient);
    }

    public function tearDown()
    {
        $this->cut = null;
    }

    public function testCreatedSessionByGivenDevIdAndAuthKey(): void
    {
        $response = file_get_contents(__DIR__.'/../Mock/Service/responseTestCreatedSessionByGivenDevIdAndAuthkey.json');
        $this->mockHandler->append(new Response(200, [], $response));

        $this->assertJson($this->cut->getSessionFromApi());
        $this->assertJsonStringEqualsJsonString($response, $this->cut->getSessionFromApi());
    }
}
```
And the fixture:
```
{
  "ret_msg": "Approved",
  "session_id": "0ECDF26BC1F04EE4BA4AF10EC3604E04",
  "timestamp": "2/14/2013 7:50:20 PM"
}
```
What do I wrong? 
If I dump the count of mockhandler I get right back the value one.
Why is the queue of mock handler empty in my class?

If I execute the get method directly in my test class, it works as expected.

#### Expected Behavior

No empty queue in the tested class.

#### Steps to Reproduce

| PHP        | 7.1
| PHPUnit | 6.5
| Symfony| 4.1 (That should not be relevant)

**Comment by GagaMen** [comment]
All works right.
I call the method 'getSessionFromApi' twice, but add only one response to the queue.
So the second call don't have a response and fails.

I close this issue.

Thanks for attention.

**Comment by isaacdarcilla** [comment]
@GagaMen how did you solved this?

**Comment by GagaMen** [comment]
@isaacdarcilla 

Mocking works like a queue (First In First Out) and every defined mock response is used once.

So I defined the mock response only one time with this line:

```
$this->mockHandler->append(new Response(200, [], $response));
```

But in the assert action I called the function I want to test twice:

```
$this->assertJson($this->cut->getSessionFromApi());
 $this->assertJsonStringEqualsJsonString($response, $this->cut->getSessionFromApi());
```

So the second call of the function `getSessionFromApi` doesn't get a response from the mock handler.

There are two possible solutions:

- You can register the mock response for each necessary function call (in this case twice)
- You can save the return value of the function `getSessionFromApi` in a variable and use this in the assert calls

In my opinion, the last solution is the best because it matches the AAA (Arrange, Act, Assert) test pattern.

I hope this helps.
