### ISSUE TITLE
Not working on Laravel Controller, Working on Tinker

### ISSUE THREAD

**Issue by PrafullaKumarSahu** [guzzle/guzzle#2213]
**Guzzle version(s) affected**: 6.3
**Laravel**:  5.6.3
**PHP**: 7.2.10

**Description**  
If I am trying to get response in tinker

```
$client = new \GuzzleHttp\Client();
$response = $client->get($url);
json_decode($response->getBody())
```

I am getting response as expected.

but in my controller

` $object_res = $client->get($url);`

I am getting error 

`"cURL error 3: <url> malformed (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)",…}`

Which means, the url is incorrect, but as I have described, this working perfectly in tinker.

**Note**
I am getting everything working perfectly in my localhost, this is occurring only on my test server.

**Comment by jwwb681232** [comment]
I have the same problem

**Comment by atymic** [comment]
What URL are you using? Can you dump it and post it?

**Comment by jwwb681232** [comment]
> What URL are you using? Can you dump it and post it?

I found that the problem was not caused by url, because I was doing the queue job in a scheduled task, and after I updated my code, I forgot to restart the queue to cause the problem.
