### ISSUE TITLE
Guzzle Suddenly Not Working

### ISSUE THREAD

**Issue by jtalbot77** [guzzle/guzzle#2225]
I have a number of forms running this code, all was working fine for months and suddenly it is not working. I am getting the follow error: "I hid the url and some of the directories for security. But the GET URL is working fine when I copy and paste is separately with a success result"

Fatal error: Uncaught exception 'GuzzleHttp\Exception\ClientException' with message 'Client error: `GET hidden url here` resulted in a `404 Not Found` response: <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd" (truncated...) ' in /vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:107 Stack trace: #0 /vendor/guzzlehttp/guzzle/src/Middleware.php(65): GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Psr7\Request), Object(GuzzleHttp\Psr7\Response)) #1 /vendor/guzzlehttp/guzzle/src/Exception/RequestException.php on line 107

here is partial of the code I am using, it was previously working fine and nothing has changed: 
`<?php	
				
							if (isset($_POST) && !empty($_POST)) {
								// http://docs.guzzlephp.org/en/latest/
										require_once($_SERVER['DOCUMENT_ROOT'].'/wp-content/themes/bridge-child/vendor/autoload.php'); 
								
								

								$client = new GuzzleHttp\Client();
								$res = $client->request('GET', $url);

								if ($res->getBody() == 'Success') {
									echo 'Your request was received successfully! We also invite you to new home by completing an online application.';
									header("Location: https://urlhere");

								} else {
									echo 'There was an error while trying to submit your request.' .$res->getBody();
								}
							} else {
								echo $intro[0]['content'];
							}`

**Comment by jtalbot77** [comment]
This is my guzzle debug log:  
--
  | *   Trying 45.60.121.170...
  | * TCP_NODELAY set
  | * Connected to api.rentcafe.com (45.60.121.170) port 443 (#0)
  | * ALPN, offering http/1.1
  | * successfully set certificate verify locations:
  | *   CAfile: /etc/ssl/certs/ca-certificates.crt
  | CApath: /etc/ssl/certs
  | * NPN, negotiated HTTP1.1
  | * SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
  | * ALPN, server did not agree to a protocol
  | * Server certificate:
  | *  subject: C=US; ST=Delaware; L=Dover; O=Incapsula Inc; CN=incapsula.com
  | *  start date: Nov 17 14:09:41 2018 GMT
  | *  expire date: Nov 18 14:09:41 2019 GMT
  | *  subjectAltName: host "api.rentcafe.com" matched cert's "*.rentcafe.com"
  | *  issuer: C=BE; O=GlobalSign nv-sa; CN=GlobalSign CloudSSL CA - SHA256 - G3
  | *  SSL certificate verify ok.
  | > GET /rentcafeapi.aspx?requestType=lead&firstName=test&lastName=test&email=test@testing.com&phone=1234567890&message=test&propertyCode=p0876157&APIToken=4bab4a92-2c87-4743-87e6-853a377f90bc&username=apileadsalliance@allresco.com&password=leads1234&source=Internet-Property%20Website-LAA&addr1=%22&addr2=%22&city=%22&state=%22&ZIPCode=%22 HTTP/1.1
  | Host: api.rentcafe.com
  | User-Agent: GuzzleHttp/6.2.1 curl/7.58.0 PHP/5.6.38-3+ubuntu18.04.1+deb.sury.org+1
  |  
  | < HTTP/1.1 404 Not Found
  | < Content-Type: text/html; charset=UTF-8
  | < Cache-Control: no-cache
  | < Pragma: no-cache
  | < Expires: 0
  | < Connection: close
  | < Set-Cookie: visid_incap_1583653=MPiSaoMhRcuAVmis7KzUqW4F/lsAAAAAQUIPAAAAAACHFIzceRzn6K+3uSGFEO+X; expires=Wed, 27 Nov 2019 13:51:02 GMT; path=/; Domain=.rentcafe.com
  | < Set-Cookie: incap_ses_262_1583653=yqRrUCCc3Wqykz9h0tCiA24F/lsAAAAAohIwrtQdN91C2epyqZ1PBA==; path=/; Domain=.rentcafe.com
  | < X-Iinfo: 1-56571795-56571798 NNNN CT(0 0 0) RT(1543374190216 29) q(0 0 0 -1) r(0 0) U5
  | < X-CDN: Incapsula
  | <
  | * Closing connection 0

**Comment by jtalbot77** [comment]
Debug Log:
 | * Trying 45.60.121.170...
  | * TCP_NODELAY set
  | * Connected to api.rentcafe.com (45.60.121.170) port 443 (#0)
  | * ALPN, offering http/1.1
  | * successfully set certificate verify locations:
  | * CAfile: /etc/ssl/certs/ca-certificates.crt
  | CApath: /etc/ssl/certs
  | * NPN, negotiated HTTP1.1
  | * SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
  | * ALPN, server did not agree to a protocol
  | * Server certificate:
  | * subject: C=US; ST=Delaware; L=Dover; O=Incapsula Inc; CN=incapsula.com
  | * start date: Nov 17 14:09:41 2018 GMT
  | * expire date: Nov 18 14:09:41 2019 GMT
  | * subjectAltName: host "api.rentcafe.com" matched cert's "*.rentcafe.com"
  | * issuer: C=BE; O=GlobalSign nv-sa; CN=GlobalSign CloudSSL CA - SHA256 - G3
  | * SSL certificate verify ok.
  | > GET /rentcafeapi.aspx?requestType=lead&firstName=test&lastName=test&email=test@testing.com&phone=1234567890&message=test&propertyCode=000000&APIToken=000000&username=hidden@hidden.com&password=hidden&source=hidden&addr1=%22&addr2=%22&city=%22&state=%22&ZIPCode=%22 HTTP/1.1
  | Host: api.rentcafe.com
  | User-Agent: GuzzleHttp/6.2.1 curl/7.58.0 PHP/5.6.38-3+ubuntu18.04.1+deb.sury.org+1
  |  
  | < HTTP/1.1 404 Not Found
  | < Content-Type: text/html; charset=UTF-8
  | < Cache-Control: no-cache
  | < Pragma: no-cache
  | < Expires: 0
  | < Connection: close
  | < Set-Cookie: visid_incap_1583653=MPiSaoMhRcuAVmis7KzUqW4F/lsAAAAAQUIPAAAAAACHFIzceRzn6K+3uSGFEO+X; expires=Wed, 27 Nov 2019 13:51:02 GMT; path=/; Domain=.rentcafe.com
  | < Set-Cookie: incap_ses_262_1583653=yqRrUCCc3Wqykz9h0tCiA24F/lsAAAAAohIwrtQdN91C2epyqZ1PBA==; path=/; Domain=.rentcafe.com
  | < X-Iinfo: 1-56571795-56571798 NNNN CT(0 0 0) RT(1543374190216 29) q(0 0 0 -1) r(0 0) U5
  | < X-CDN: Incapsula
  | <
  | * Closing connection 0

**Comment by xZero707** [comment]
Guzzle uses cURL library when available. cURL is known to cache some stuff internally, and that could cause serious issues which are extremely hard to debug. 

In my case, PHP SoapClient library was somehow reaching wrong environment even though URL was correct. 
After hours of debugging, issue was that our provider changed DNS A records, but cURL, which is used by SoapClient, was connecting to old IP (cached internally)
Solution is a flag which is supplied to cURL upon initialization and disables caching.  To do that, though, you need to extend implementation class (in my case SoapClient).

**Comment by gmponos** [comment]
- https://github.com/guzzle/guzzle/blob/master/.github/ISSUE_TEMPLATE/support_question.md
- https://github.com/guzzle/guzzle/blob/master/.github/SUPPORT.md

**Comment by sagikazarmark** [comment]
@xZero707 yeah, cURL has a DNS cache, but AFAIK it is only preserved within a single cURL handle, the global cache is deprecated. It could be some sort of DNS cache on your network and cURL can be forced to go to the original name servers for name resolution, but that usually takes time, that's why there is a DNS cache.

@jtalbot77 The error says `404 not found` which means your code is trying to connect to the wrong URL. Since the server responded with a valid response, I highly doubt this has anything to do with Guzzle, especially if you haven't upgraded it.
