### ISSUE TITLE
Client certificate does not work with NSS (curl)

### ISSUE THREAD

**Issue by cvuorinen** [guzzle/guzzle#2226]
**Guzzle version(s) affected**: 6.x

**Description**  

On RHEL/CentOS where curl is built with NSS instead of OpenSSL curl does not support passing client certificate as a file, instead you have to use NSS database and pass the certificate nickname in as the cert param. PHP curl supports this also by just setting the certificate nickname with the `CURLOPT_SSLCERT` option.

**How to reproduce**  

Using the `cert` option on a machine where curl is built with NSS instead of OpenSSL.

**Possible Solution**  

In Guzzle there is a `file_exist` check when using the `cert` option here: https://github.com/guzzle/guzzle/blob/6.3.3/src/Handler/CurlFactory.php#L433
This obviously will fail when passing in just the certificate nickname as it is not a file.

I have tested and just commenting out the check makes it work.

So is this check actually needed, or could we remove it? Or could add some other option to disable the check so that it could be used on a CentOS server?

**Additional context**  

For example I have imported the client certificate to the NSS database with nickname "clientssl", and just using plain PHP curl functions and setting `CURLOPT_SSLCERT` to `"clientssl"` works fine, but Guzzle fails with error `PHP Fatal error:  Uncaught InvalidArgumentException: SSL certificate not found: clientssl in .../vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php`

**Comment by sagikazarmark** [comment]
I have to check what's going on, but as a quick workaround you can easily pass curl options directly to guzzle via `$options['curl']`.
