### ISSUE TITLE
Class 'GuzzleHttp\Tests\Server' not found

### ISSUE THREAD

**Issue by williamdes** [guzzle/guzzle#2228]
**Guzzle version(s) affected**: 6.3

**Description**  
No test files in vendor package

**How to reproduce**  
http://docs.guzzlephp.org/en/stable/testing.html

**Possible Solution**  
Add to https://github.com/guzzle/guzzle/blob/master/build/packager.php the tests directory

**Additional context**  
Duplicate of: #775

**Comment by williamdes** [comment]
cc @mtdowling

**Comment by williamdes** [comment]
```
$ ls -lahR vendor/guzzlehttp/guzzle/src/
vendor/guzzlehttp/guzzle/src/:
total 136K
drwxrwxr-x 5 william william 4,0K avril 22  2018 .
drwxrwxr-x 3 william william 4,0K déc.   3 14:14 ..
-rw-rw-r-- 1 william william 2,8K avril 22  2018 ClientInterface.php
-rw-rw-r-- 1 william william  17K avril 22  2018 Client.php
drwxrwxr-x 2 william william 4,0K avril 22  2018 Cookie
drwxrwxr-x 2 william william 4,0K avril 22  2018 Exception
-rw-rw-r-- 1 william william  160 avril 22  2018 functions_include.php
-rw-rw-r-- 1 william william 9,7K avril 22  2018 functions.php
drwxrwxr-x 2 william william 4,0K avril 22  2018 Handler
-rw-rw-r-- 1 william william 7,5K avril 22  2018 HandlerStack.php
-rw-rw-r-- 1 william william 7,1K avril 22  2018 MessageFormatter.php
-rw-rw-r-- 1 william william 9,7K avril 22  2018 Middleware.php
-rw-rw-r-- 1 william william 4,6K avril 22  2018 Pool.php
-rw-rw-r-- 1 william william 3,1K avril 22  2018 PrepareBodyMiddleware.php
-rw-rw-r-- 1 william william 7,7K avril 22  2018 RedirectMiddleware.php
-rw-rw-r-- 1 william william 9,8K avril 22  2018 RequestOptions.php
-rw-rw-r-- 1 william william 3,2K avril 22  2018 RetryMiddleware.php
-rw-rw-r-- 1 william william 3,1K avril 22  2018 TransferStats.php
-rw-rw-r-- 1 william william 8,0K avril 22  2018 UriTemplate.php

vendor/guzzlehttp/guzzle/src/Cookie:
total 44K
drwxrwxr-x 2 william william 4,0K avril 22  2018 .
drwxrwxr-x 5 william william 4,0K avril 22  2018 ..
-rw-rw-r-- 1 william william 2,8K avril 22  2018 CookieJarInterface.php
-rw-rw-r-- 1 william william 9,1K avril 22  2018 CookieJar.php
-rw-rw-r-- 1 william william 2,6K avril 22  2018 FileCookieJar.php
-rw-rw-r-- 1 william william 1,9K avril 22  2018 SessionCookieJar.php
-rw-rw-r-- 1 william william  11K avril 22  2018 SetCookie.php

vendor/guzzlehttp/guzzle/src/Exception:
total 48K
drwxrwxr-x 2 william william 4,0K avril 22  2018 .
drwxrwxr-x 5 william william 4,0K avril 22  2018 ..
-rw-rw-r-- 1 william william  806 avril 22  2018 BadResponseException.php
-rw-rw-r-- 1 william william  161 avril 22  2018 ClientException.php
-rw-rw-r-- 1 william william  726 avril 22  2018 ConnectException.php
-rw-rw-r-- 1 william william  293 avril 22  2018 GuzzleException.php
-rw-rw-r-- 1 william william 5,6K avril 22  2018 RequestException.php
-rw-rw-r-- 1 william william  588 avril 22  2018 SeekException.php
-rw-rw-r-- 1 william william  161 avril 22  2018 ServerException.php
-rw-rw-r-- 1 william william   99 avril 22  2018 TooManyRedirectsException.php
-rw-rw-r-- 1 william william  119 avril 22  2018 TransferException.php

vendor/guzzlehttp/guzzle/src/Handler:
total 84K
drwxrwxr-x 2 william william 4,0K avril 22  2018 .
drwxrwxr-x 5 william william 4,0K avril 22  2018 ..
-rw-rw-r-- 1 william william  702 avril 22  2018 CurlFactoryInterface.php
-rw-rw-r-- 1 william william  21K avril 22  2018 CurlFactory.php
-rw-rw-r-- 1 william william 1,3K avril 22  2018 CurlHandler.php
-rw-rw-r-- 1 william william 5,5K avril 22  2018 CurlMultiHandler.php
-rw-rw-r-- 1 william william 2,8K avril 22  2018 EasyHandle.php
-rw-rw-r-- 1 william william 5,8K avril 22  2018 MockHandler.php
-rw-rw-r-- 1 william william 1,8K avril 22  2018 Proxy.php
-rw-rw-r-- 1 william william  18K avril 22  2018 StreamHandler.php
```

**Comment by tag** [comment]
Having a similar issue.

The mock server is useful, as I'm testing a non-Guzzle client, but need to be able to mock the Response, and Guzzle is an easy(-ish) way to handle that.

**Comment by williamdes** [comment]
Time passed, if you find this issue feel-free to fix it.

**Comment by rhzs** [comment]
@williamdes I use Guzzle ^7.0 in PHP 7.3, but I can't find the `GuzzleHttp\Tests\Server` class. Any idea how to fix?

<img width="377" alt="Screen Shot 2020-09-26 at 15 04 54" src="https://user-images.githubusercontent.com/5300674/94335974-a81b5000-0009-11eb-993d-b33c11c11571.png">

**Comment by williamdes** [comment]
Maybe https://github.com/guzzle/guzzle/blob/2890bde08eb42ec57b3fbc9bc6b7f332d3a7b877/.gitattributes#L12 is the culprit

Hi @Nyholm  
Is it possible to close this old issue with a fix?

**Comment by GrahamCampbell** [comment]
That file is not part of the public API, and it is not a breaking change to not include it in the zips any more.

**Comment by Nyholm** [comment]
Correct. That is the line that caused this issue. 

Yes, it is possible to close an issue without a fix. 

I agree with Graham, that file is for running tests on guzzle itself, it is not part of the BC promise. 

I think this issue should be closed.

**Comment by Nyholm** [comment]
Sorry @williamdes 
I misread your comment. 

I'm not sure we need a fix. Why do you need that file outside of Guzzle?

**Comment by williamdes** [comment]
Actually I do not remember why I needed it but I linked the documentation that uses it
http://docs.guzzlephp.org/en/stable/testing.html

Feel free to do any action you want, but maybe fix the documentation :)

**Comment by rhzs** [comment]
> Actually I do not remember why I needed it but I linked the documentation that uses it
> http://docs.guzzlephp.org/en/stable/testing.html
> 
> Feel free to do any action you want, but maybe fix the documentation :)

It's true that the docs misled me to be able to import `GuzzleHttp\Tests\Server`

**Comment by marc-mabe** [comment]
@Nyholm

I also come here after noticing that the test server is not part of the installed dependency.
As I understand it you are using the test server for testing guzzle itself and that's why it's not part of (composer) install.
That's fine!

But I also want to try to explain in which situations is would be a very useful tool to for testing other projects as well:
1. You are proxying requests to another service
  * Sometimes you need to proxy a request to somewhere else even with PHP instead of webserver (e.g. to perform user permission checks before or transform the request with something)
  * In this case it's not always suitable to run your tests against a real existing service and it would be very helpful to instead be able to send requests against a local controlled testing server
2. Testing request against external services
  * You could run your tests against the external service directly but this comes with some downsides as well
    * unreliability
    * test complexity (e.g. How do you trigger servers to test such responses?)
    * ops complexity (your CI is not allowed to access this external service)
    * costs (you probably get charged for the requests)

In my case I'm trying to test user authorization against an external IdP provider using OIDC which is not fun using the real provider because the users are managed by a different department and they don't allow fake users for security reasons - which makes sense but does not help testing this.

It would be just great if this testing server would be available for other projects as well. From my point of view it would be most suitable to be available as separate package so you and others are would be able to use this as dev dependency.

**Comment by GrahamCampbell** [comment]
See https://github.com/guzzle/guzzle/issues/2295.
