### ISSUE TITLE
trailing slash

### ISSUE THREAD

**Issue by FabrizioReitano** [guzzle/guzzle#2232]
**Guzzle version(s) affected**: 6.3.3

Hi,
making a GET request on this URL http://localhost/bpws2/app_dev.php/api/qrp/CFI/02493870188, Guzzle adds a trailing slash transforming the URL in http://localhost/bpws2/app_dev.php/api/cerved/qrp/CFI/02493870188/. If I add a character to the final path (http://localhost/bpws2/app_dev.php/api/cerved/qrp/CFI/a02493870188) then the URL is not modified.

**Comment by gmponos** [comment]
There is a test [here](https://github.com/guzzle/guzzle/blob/master/tests/ClientTest.php#L655) that proves that this is not happening. 🤔 

Can you investigate further and elaborate?

**Comment by FabrizioReitano** [comment]
In this thest the path is not ending with a numeric value, but with 'test'. In my scenario the path ends with only numeric characters '02493870188'. If the last element of the path contains an alphabetic character, then the we get the expected behaviour.

**Comment by Dzhuneyt** [comment]
I am not able to reproduce your issue. Following a minimalistic example locally:
```
require "../vendor/autoload.php";

use GuzzleHttp\Client;
use GuzzleHttp\Psr7\Request;

$client = new Client([
    // Base URI is used with relative requests
    'base_uri' => 'http://httpbin.org',
    // You can set any number of default request options.
    'timeout' => 2.0,
]);
$request = new Request('GET', 'http://localhost:8081/bpws2/app_dev.php/api/qrp/CFI/02493870188');
$response = $client->send($request, [
    'timeout' => 2,
    'debug'=>true,
]);

```

Checking the server logs on my machine I notice that a request has been made to `127.0.0.1:39090 [404]: /bpws2/app_dev.php/api/qrp/CFI/02493870188 - No such file or directory`

No trailing slash is being added.

**Comment by GrahamCampbell** [comment]
It looks more like your server is redirecting your request to one with a slash?

**Comment by sagikazarmark** [comment]
Thanks guys for jumping in to help! This is great! 

@FabrizioReitano I tend to agree with the above explanations about your issue. Can you try executing the above script locally, maybe with 'debug' option true? Then you can see the final outgoing request.

**Comment by westonwatson** [comment]
we recently tried to upgrade from 6.3 and now we can't get Guzzle to request URL's with a trailing slash (trailing slash is required). Seems like Guzzle is removing the slash (6.4/6.5/etc)... any way to get around this?

**Comment by Nyholm** [comment]
Please create a new with some code to reproduce your issue.
