### ISSUE TITLE
is any other to upload base_decode code 

### ISSUE THREAD

**Issue by DHCMediWay** [guzzle/guzzle#2233]
i have a code by base64_decode, how can i upload this via multipart.
the only way i have 
save the code to temp file 
then open file use resource to upload

is any other way? thank

**Comment by kkopachev** [comment]
```php
$stream_to_upload = \GuzzleHttp\Psr7\stream_for($string_of_data);
```
then use `$stream_to_upload` as a resource.

**Comment by DHCMediWay** [comment]
> ```
> $stream_to_upload = \GuzzleHttp\Psr7\stream_for($string_of_data);
> ```
> 
> then use `$stream_to_upload` as a resource.

Thanks for this.
