### ISSUE TITLE
Guzzle with laravel passport Oauth causing trouble - Is it guzzle client or passport problem?

### ISSUE THREAD

**Issue by Albyzai** [guzzle/guzzle#2236]
Hi,

As the title states, I am having a problem, but i am a bit unsure whether it is the Guzzle client or passport causing it.

I have followed the documentation found here: https://laravel.com/docs/5.7/passport as you can see in the code below.

`    $http = new Client();

    $response = $http->post('http://rankup.dinmor/oauth/token', [
      'form_params' => [
        'grant_type' => 'password',
        'client_id' => '2',
        'client_secret' => '5n053udMlMksA1AyVmLUxoxTVr2Algnm4aTRjkQk',
        'username' => $request->email,
        'password' => $request->password,
        'scope' => '',
      ],
    ]);

    return json_decode((string) $response->getBody(), true);`

And i am getting the following error:

Client error: `POST http://rankup.dinmor/oauth/token` resulted in a `401 Unauthorized` response: {"error":"invalid_credentials","message":"The user credentials were incorrect."}

Do you have any idea if is an issue on your side or passports? I have seen a lot of people mentioning this problem.

**Comment by hardcoderrsl** [comment]
I have been facing the same problem. did you find your solution? please help me if you did. thank you in advance.. @Albyzai

**Comment by sunnerdev** [comment]
> I have been facing the same problem. did you find your solution? please help me if you did. thank you in advance.. @Albyzai



I change
`$http = new Client();`
are
`$http= new \GuzzleHttp\Client();`

Code :

        $http= new \GuzzleHttp\Client();
        $response = $http->request('POST', 'http://api.mydomain.com/oauth/token', [
            'headers' => [
                'cache-control' => 'no-cache',
                'Content-Type' => 'application/x-www-form-urlencoded'
          ],
            'form_params' => [
                'client_id' => '9',
                'client_secret' => 'i03Ua2gDlnHCgI4GWu2MAPEM1jkdXjsBHrHU6bYU',
                'grant_type' => 'password',
                'username' => 'sunnerdev@gmail.com',
                'password' => 'xxxxxx',
                'scope' => '',
            ],
          ]);
        return json_decode((string) $response->getBody(), true);


It work for me

Response :
`{
"token_type":"Bearer",
"expires_in":864000,
"access_token":"eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImp0aSI6IjNkMzgyNzk1ZTQ4NjFkMzVhMDEzODE4ZWQ4NmM1N2E3MzkzMWQzZWVlYTdhZDA2M2Y2ODNlZjNmOTg..............................."}`

**Comment by hardcoderrsl** [comment]
@Albyzai I have found the solution for me. it's not guzzle nor passport. there is a architectural and conceptual mistake. I don't know your case- if you are facing this problem during unit testing- we are on the same page. and I've solved it without using guzzle. because - it is impossible to test with guzzle.

**Comment by markryandelarmente** [comment]
@hardcoderrsl  what is the solution? I'm facing the same problem right now.

**Comment by ionia3** [comment]
I am facing the same issue too.

**Comment by palla451** [comment]
I have the same problem , please help

**Comment by meshack007** [comment]
@ionia3 @palla451 @markryandelarmente @Nyholm or anyone else that this might help.

Using php artisan serve will not work because 'php artisan serve' uses php inbuilt server which is a single threaded application, and while the first request is still being processed the second one cant be handled.

Hence you will need to setup a webserver i.e nginx, apache, etc; or you can use alternatives like xampp to do this.

Going further what your attempting could be preferably done using method below:
`
if (Auth::attempt($credentials)) {
            // Authentication passed...
             $user = Auth::user();
             $token = $user->createToken('Token Name')->accessToken;

            return response()->json($token);
        }
`
Instead of sending a request to your own application, you can authenticate the request and provide a token, removing even the need to store client_id and token in your application.

**Comment by meshack007** [comment]
Another Alternative [here](https://github.com/guzzle/guzzle/issues/1857#issuecomment-312617494)

**Comment by Nyholm** [comment]
@meshack007 

Could you please open a new issue with a reproducible script?

**Comment by ghost** [comment]
I am implementing SSO for multiple Laravel and PHP applications.
So, I am also facing the same problem when send the request to Authorization Server in the client, please thank you for help me.

```
Client error: 'POST http://localhost:8000/api/register' resulted in a '404 Not Found' response: <!DOCTYPE html> <html lang="en"> <head> <meta charset="utf-8"> <meta name="viewport" content="wi (truncated...)

public function register(Request $request)
{
    $request->validate([
        'name' => 'required|string|max:255',
        'email' => 'required|string|email|max:255|unique:users',
        'password' => 'required|string|min:8|confirmed',
    ]);

    $http = new Client;
    $response = $http->post('http://localhost:8000/api/register', [
        'headers' => [
            'cache-control' => 'no-cache',
            'Content-Type' => 'application/x-www-form-urlencoded'
        ],
        'form_params' => [
            'client_id' => config('services.passport.client_id'),
            'secret' => config('services.passport.client_secret'),
            'name' => $request->name,
            'email' => $request->email,
            'password' => $request->password,
        ],
    ]);
    
    $data = json_decode((string) $response->getBody(), true);
    session(['token' => $data['access_token']]);
    return redirect('/dashboard');
}
```
