### ISSUE TITLE
Send POST request in RAW mode.

### ISSUE THREAD

**Issue by alighasemzadeh** [guzzle/guzzle#2240]
**Description**  
Hello,
I want to make post request with raw data for url but form data not work.
but when I use PostMan It works.

**Example**  
Please check Image:
![working_raw](https://user-images.githubusercontent.com/26847446/50515392-aaa9e800-0ab9-11e9-8ba6-b377aad17bef.jpg)

**Additional context**
![working_raw](https://user-images.githubusercontent.com/26847446/50515392-aaa9e800-0ab9-11e9-8ba6-b377aad17bef.jpg)

**Comment by Dzhuneyt** [comment]
Try using the shorthand parameter ["json"](http://docs.guzzlephp.org/en/stable/request-options.html#json). My guess is that you are using the "body" parameter or "form_params".

**Comment by sagikazarmark** [comment]
See the above answer.
