### ISSUE TITLE
"https:/" to "https://"

### ISSUE THREAD

**Issue by wangyuanhui** [guzzle/guzzle#2241]
**Description**  

when I use guzzle, I write url "http:/xxx" by mistake, and magically everything works well. I tried http:/some-website on postman, and it failed. Then I guess guzzle automatically correct the url to "http://". But it seems guzzle can not deal with "https:/".

**Example**  

here is my code:

$req = new Request(
                $method,
                $url,
                ["Authorization" => $authType . ' ' . $authToken, "Content-Type" => "application/json;charset=utf-8"],
                $body
            );

if $url = "http:/some-website", everything is ok.
but if $url = "https:/some-website", error.

**Additional context**

of course, this is my mistake of typing incorrect url. however I think if guzzle accepts "http:/" why not "https:/"?

Or all my guess is wrong?

**Comment by GrahamCampbell** [comment]
> of course, this is my mistake of typing incorrect url. however I think if guzzle accepts "http:/" why not "https:/"?

I just tried `http:/example.com` and `https:/example.com` and **both** worked.

**Comment by GrahamCampbell** [comment]
```php
>>> GrahamCampbell\GuzzleFactory\GuzzleFactory::make()->get('https:/example.com')->getStatusCode();
=> 200
>>> GrahamCampbell\GuzzleFactory\GuzzleFactory::make()->get('http:/example.com')->getStatusCode();
=> 200
```

**Comment by sagikazarmark** [comment]
Thanks @GrahamCampbell , I can do too.

@wangyuanhui can you please provide some example code that reproduces the problem?

**Comment by Nyholm** [comment]
Closing due inactivity.
