### ISSUE TITLE
[Feature] automating add ['Content-Type' => 'application/x-www-form-urlencoded'] for new Request('post')

### ISSUE THREAD

**Issue by 4n70w4** [guzzle/guzzle#2243]
**Description**  

If I use

`$Request = new Request('post', $url, [],  http_build_query([]) );`

Guzzle dont add header to request:

`'Content-Type' => 'application/x-www-form-urlencoded'`

Manually add `['Content-Type' => 'application/x-www-form-urlencoded']` to Request constructor no user friendly way.

But this code add this header automatic:

>         $Response = $this->Client->post($url, [
>             'form_params' => [],
>         ]);

**Comment by sagikazarmark** [comment]
Guzzle adds the header when you tell it to send a form request. Why would it add the header in other cases?

**Comment by 4n70w4** [comment]
@sagikazarmark Is there a convenient and user-friendly way to add this header through new Request('post')?

**Comment by Nyholm** [comment]
No, it is not. The value `application/x-www-form-urlencoded` is arbitrary.
