### ISSUE TITLE
json string data post request

### ISSUE THREAD

**Issue by AhsanAbrar** [guzzle/guzzle#2244]
**Guzzle version(s) affected**: 6.3

**Description**  

how to convert this curl into guzzle

curl -u 'username:token' 'https://api.dev.name.com/v4/domains:checkAvailability' -X POST --data '{"domainNames":["example.org"]}'

i tried a lot but failed

here is my solution

```
$client = new Client([
    'base_uri' => 'https://api.dev.name.com/v4/',
    'headers' => ['Content-Type' => 'application/json'],
    'auth' => ['username', 'token']
]);


$response = $client->request('POST', 'domains:checkAvailability', [
    'form_params' => [
        'domainNames' => ['abc.com']
    ]
]);
```
i'm getting this error:

cURL error 3: Port number ended with 'c' (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)

any guide?

**Comment by sagikazarmark** [comment]
Use `/domains:checkAvailability`
