### ISSUE TITLE
Get paramters, how to strip indexes

### ISSUE THREAD

**Issue by andrconstruction** [guzzle/guzzle#2252]
Please advise how could I strip indexes in get paramters?
At this moment my query string look like ?attrs[0]='sss'&attrs[1]='222sss'
but should be like ?attrs='sss'&attrs='222sss', can I achieve that with some options?

**Comment by andrconstruction** [comment]
Thanks for your answer, but it need for an outgoing request, not for incoming.

**Comment by sagikazarmark** [comment]
The above code will generate a query with indexes, that's the standard form if there are multiple values for the same key. Why do you want to get rid of them?

**Comment by andrconstruction** [comment]
Exist the monitoring system named Icinga, which  expect only this format of values, and this is not first case, I faced with this fromat many time

**Comment by andrconstruction** [comment]
Found on this form, an elegant solution if somebody will looking for.
https://github.com/guzzle/guzzle/pull/1875

**Comment by silence44** [comment]
@sandacn 
What standard were you refering to?

When I'm sending ajax request via js or submitting form with arrays it goes without indexes. PHP programs may interface with many other systems and languages which accepts only array without indexes (otherwise it may be recognized as map structure, not array).

I think it is good idea to make indexes optional for somebody who really need this.

**Comment by kanonji** [comment]
I am in the situation to be required to strip indexes from query string for some web API.
I think it is not standard over the world to append array indexes in query string.

Common URL parsers of Golang and Python3 does not expect array indexes in query string.
I need to generate query string like `https://example.org/?values=zero&values=one&values=two` to 
communicate with some web API made with Golang or Python3.

Is there any reason not to make array indexes optional?


## Golang

> ```
> package main
> 
> import (
>     "fmt"
>     "log"
>     "net/url"
> )
> 
> func main() {
>     u, err := url.Parse("https://example.org/?values%5B0%5D=zero&values%5B1%5D=one&values%5B2%5D=two")
>     if err != nil {
>         log.Fatal(err)
>     }
>     q := u.Query()
>     fmt.Println(q["values[0]"])
> }
> ```
> https://shinkufencer.hateblo.jp/entry/2019/05/18/163912

## Python3

> ```
> import urllib.parse
> 
> convertd_dictionary = urllib.parse.parse_qs("values%5B0%5D=zero&values%5B1%5D=one&values%5B2%5D=two")
> print(convertd_dictionary)
> # {'values[0]': ['zero'], 'values[1]': ['one'], 'values[2]': ['two']}
> ```
> https://shinkufencer.hateblo.jp/entry/2019/05/18/163912

**Comment by intellent** [comment]
Probably related:? #22
