### ISSUE TITLE
Should the connectionException Message add info with the host?

### ISSUE THREAD

**Issue by sandacn** [guzzle/guzzle#2256]
**Description**  
Now with curl to send a http request, when there is ConnectionErrors(), including (            CURLE_OPERATION_TIMEOUTED ,CURLE_COULDNT_RESOLVE_HOST, CURLE_COULDNT_CONNECT, CURLE_SSL_CONNECT_ERROR, CURLE_GOT_NOTHING)

but the exception with error does not has host info, when we see the default exception we can not clearly know which host is wrong.

**Example**  
for example, the error 7's error message:
```
error: cURL error 7: couldn't connect to host (see http:\/\/curl.haxx.se\/libcurl\/c\/libcurl-errors.html)
```

**Additional context**
now the format is 
```php
$message = sprintf(
            'cURL error %s: %s (%s)',
            $ctx['errno'],
            $ctx['error'],
            'see http://curl.haxx.se/libcurl/c/libcurl-errors.html'
        );
```
I suggest whether we can add info in the (), like this:
```php
$message = sprintf(
            'cURL error %s: %s (%s)',
            $ctx['errno'],
            $ctx['error'],
            'see http://curl.haxx.se/libcurl/c/libcurl-errors.html, while request host is xxxxx'
        );
```
when we the error, we know the host and we can quickly deal with it.

If the RFC is OK, I can implement this feature. 

Thanks .

**Comment by phansys** [comment]
You should take care that some error messages returned by `curl_error()` (which is used to fill `$ctx['error']`) already include the host name, by instance:
>Could not resolve host: nonexistent.tld

**Comment by gmponos** [comment]
@sandacn most probably your example will throw a `ConnectException` which contains the request object.

Why don't you simply get the info from there?

**Comment by sandacn** [comment]
> You should take care that some error messages returned by `curl_error()` (which is used to fill `$ctx['error']`) already include the host name, by instance:
> 
> > Could not resolve host: nonexistent.tld

In my test case, the host does not on the error arrray

**Comment by sandacn** [comment]
> @sandacn most probably your example will throw a `ConnectException` which contains the request object.
> 
> Why don't you simply get the info from there?

I just use error, not exception to catch like this.

**Comment by gmponos** [comment]
> I just use error, not exception to catch like this.

I am not sure what this means...

**Comment by phansys** [comment]
> > You should take care that some error messages returned by `curl_error()` (which is used to fill `$ctx['error']`) already include the host name, by instance:
> > > Could not resolve host: nonexistent.tld
> 
> In my test case, the host does not on the error arrray

Which PHP version are you using? Could you please confirm if your issue is related to https://bugs.php.net/bug.php?id=77946?

**Comment by guilliamxavier** [comment]
@phansys: https://bugs.php.net/bug.php?id=77946 is about no error message at all, while this is about no host info in the error message

**Comment by sandacn** [comment]
> @phansys: https://bugs.php.net/bug.php?id=77946 is about no error message at all, while this is about no host info in the error message

Yes，you are right. 
Can you reproduce my error message ?

**Comment by sandacn** [comment]
> > > You should take care that some error messages returned by `curl_error()` (which is used to fill `$ctx['error']`) already include the host name, by instance:
> > > > Could not resolve host: nonexistent.tld
> > 
> > 
> > In my test case, the host does not on the error arrray
> 
> Which PHP version are you using? Could you please confirm if your issue is related to https://bugs.php.net/bug.php?id=77946?

 I use 7.2.x  version.  This bug does not match my error message. 
And the error code is not match, the issue code is 6, but mine is 7.

**Comment by guilliamxavier** [comment]
With #2661 (which will be part of Guzzle 7.1.0), your error message should look like (emphasis mine):

> cURL error 7: couldn't connect to host (see https:\/\/curl.haxx.se\/libcurl\/c\/libcurl-errors.html) **for https:\/\/example.test\/foo/bar**

**Comment by sandacn** [comment]
> With #2661 (which will be part of Guzzle 7.1.0), your error message should look like (emphasis mine):
> 
> > cURL error 7: couldn't connect to host (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) **for https://example.test/foo/bar**

This is nice.  I'll close the issue.
