### ISSUE TITLE
No ability to change proxy on per request basis

### ISSUE THREAD

**Issue by dzentota** [guzzle/guzzle#2257]
**Guzzle version(s) affected**: 
6.3.0

**Description**  
Guzzle reuses old curl handler. Code responsible for this located in CurlFactory.

So if you send several requests providing proxy address as a param, like:

```php
$httpClient->send($request, ['proxy' => '<proxy_endpoint1>');
$httpClient->send($request2, ['proxy' => '<proxy_endpoint2>');
$httpClient->send($request3, ['proxy' => '<proxy_endpoint3>');
All three requests will be made via <proxy_endpoint1>
```

**How to reproduce**  
```php
$client = new GuzzleHttp\Client();
$res1 = $client->request('GET', 'https://httpbin.org/ip', ['proxy' => '182.253.123.9:3128']);
$res2 = $client->request('GET', 'https://httpbin.org/ip', ['proxy' => '217.219.20.136:8080']);
$res3 = $client->request('GET', 'https://httpbin.org/ip', ['proxy' => '178.128.115.98:8080']);
echo $res1->getBody();
echo $res2->getBody();
echo $res3->getBody();

```

Expected output:
```
{
"origin": "182.253.123.9"
}
{
"origin": "217.219.20.136"
}
{
"origin": "178.128.115.98"
}
```
Actual:
```
{
"origin": "182.253.123.9"
}
{
"origin": "182.253.123.9"
}
{
"origin": "182.253.123.9"
}
```

**Possible Solution**  
Dirty hack to force it works:
in CurlFactory::create replace
```php
        $easy->handle = $this->handles
            ? array_pop($this->handles)
            : curl_init();
```
with
```php
        $easy->handle = curl_init();
```

**Additional**
Probably this is curl bug, something similar was described here https://github.com/curl/curl/issues/648
So if this issue is caused by curl bug then I think as work around you can compare current proxy with the last one and if they are equal then use new connection $easy->handle = curl_init();

**Comment by alexeyshockov** [comment]
@dzentota, could you tell your PHP and cURL versions?

Because for me your example works just fine, I get different results for each proxy, as expected (PHP 7.2.12, cURL 7.63.0).

**Comment by dzentota** [comment]
```
PHP 7.1.22 (cli) (built: Sep 15 2018 03:54:08) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.1.22, Copyright (c) 1999-2018, by Zend Technologies
    with blackfire v1.23.0~linux-x64-non_zts71, https://blackfire.io, by Blackfire
```

```
curl 7.38.0 (x86_64-pc-linux-gnu) libcurl/7.38.0 OpenSSL/1.0.1t zlib/1.2.8 libidn/1.29 libssh2/1.4.3 librtmp/2.3
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp scp sftp smtp smtps telnet tftp 
Features: AsynchDNS IDN IPv6 Largefile GSS-API SPNEGO NTLM NTLM_WB SSL libz TLS-SRP 
```
I think you can reproduce my env by using Docker.

In `docker-compose.yml` I have:

> 
> web:
>     **image: thecodingmachine/php:7.1-v1-apache-node8**
>     hostname: 'sugarcrm'
>     environment:
>       PHP_INI_ERROR_REPORTING: E_ERROR
>       MYSQL_NAME: 'mysql'
>       MYSQL_PORT: 'tcp://mysql:3306'
>       APACHE_EXTENSION_REWRITE: 1
>       APACHE_EXTENSION_HEADERS: 1
>       APACHE_EXTENSION_EXPIRES: 1
>       APACHE_LOG_DIR: '/var/log/apache2'
> PHP_EXTENSIONS: bcmath blackfire calendar dba exif gd gettext gmp imap intl ldap mcrypt memcached mongodb sockets sysvmsg sysvsem sysvshm pcntl tidy xmlrpc xsl
>       PHP_IDE_CONFIG: "serverName=Docker"
>     depends_on:
>     - mongo
>     ports:
>     - 8585:80
>     volumes:
>     - .:/var/www/html:rw
