### ISSUE TITLE
Documentation site lagging behind the GitHub repo doc files?

### ISSUE THREAD

**Issue by ncla** [guzzle/guzzle#2258]
There seems to be some discrepancy between live docs (browsing "latest" docs) and GitHub repository docs.

On [doc site](http://docs.guzzlephp.org/en/latest/quickstart.html#async-requests):

![image](https://user-images.githubusercontent.com/5507083/52049205-de16e100-2555-11e9-8ea0-0c79a05e74b9.png)

GitHub repo:

![image](https://user-images.githubusercontent.com/5507083/52049224-ea9b3980-2555-11e9-8d16-64b432ad6b0c.png)

The doc site is missing `$promise` variable.

**Comment by sagikazarmark** [comment]
Looks like doc builds were failing. Fixed, thanks @ncla

**Comment by ncla** [comment]
Unfortunately I do not see any change on the site, it's still the same for me. @sagikazarmark

**Comment by ncla** [comment]
Oh, yeah, I see it now. Probably because the .html is static and it gets cached client side. All is good, thanks!
