### ISSUE TITLE
StreamHandler calls `stream_set_timeout(false, ...)`  when 'read_timeout` is set and `fopen()` fails

### ISSUE THREAD

**Issue by zdenek-crha** [guzzle/guzzle#2265]
**Guzzle version(s) affected**: 6.3.3

**Description**  
StreamHandler::createStream() function does not handle 'read_timeout' optional configuration on `fopen()` call failure. It attempts to call `stream_set_timeout()` on `false` (boolean) value and triggers an error

**How to reproduce**  

Try to access api on port where nothing is listening.

**Possible solution**  

[fix_set_timeout_on_fopen_failure.txt](https://github.com/guzzle/guzzle/files/2835512/fix_set_timeout_on_fopen_failure.txt)

**Additional context**  

Error message:
```
Error creating resource: [message] fopen(http://example.com:/path/to/endpoint): failed to open stream: Connection refused
stream_set_timeout() expects parameter 1 to be resource, boolean given
```

Environmnent:
```
$ php --version
PHP 7.1.26-1+0~20190113101810.12+stretch~1.gbp7077bb (cli) (built: Jan 13 2019 10:18:10) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.1.26-1+0~20190113101810.12+stretch~1.gbp7077bb, Copyright (c) 1999-2018, by Zend Technologies
    with Xdebug v2.6.1, Copyright (c) 2002-2018, by Derick Rethans

$ composer show | grep guzzle
guzzlehttp/guzzle                     6.3.3  Guzzle is a PHP HTTP client library
guzzlehttp/promises                   v1.3.1 Guzzle promises library
guzzlehttp/psr7                       1.4.2  PSR-7 message implementation that also provides common utility methods
```

**Comment by gmponos** [comment]
This is also mentioned by PHPStan https://github.com/guzzle/guzzle/blob/master/phpstan-baseline.neon#L544

I would accept a PR about this..
