### ISSUE TITLE
Guzzle pool request total time question.

### ISSUE THREAD

**Issue by pkoscisz** [guzzle/guzzle#2267]
I am trying to get total curl time for request inside the pool. However my pages are using redirects and that seems to be causing some issues. I tried to use 'on_stats' but that one works separately for every request, meaning, if curl goes to A-> and is redirected to B we get two separate evens in stats for redirect and initial url with different total time etc.

I tried to use below handle to fetch curl_getinfo but it returns exactly the same total time as last redirect on_stats and it is way too low to be total time. 

```
class MyCurlFactory extends CurlFactory {
    public function release(EasyHandle $easy)
    {
        if ($easy->response)
        {
            $easy->response->curl_info = curl_getinfo($easy->handle);
        }
        return parent::release($easy);
    }
}
```

```
$this->client = new Client(array(
            'connect_timeout' => $this->connectionTimeout,
            'timeout' => $this->connectionTimeout,
            'allow_redirects' => ['track_redirects' => true],
            'handler' => $stack,
            'verify' => true,
            'headers' => array(
                'Accept' => 'text/html',
                'Content-Type' => 'text/html',
            )
        ));`
```

Do you guys know how i can fetch total time in pool for async requests including all time required for redirects to the final url. 

Thanks.

**Comment by alexeyshockov** [comment]
You are correct, Guzzle handles redirects as separate requests with `RedirectMiddleware`, because of that you cannot get full stats from cURL.

But nothing stops you to just sum stats from all the requests in a redirect row. Take a look at the code below and note that `'on_stats'` handler is called as many time as you are redirected.

```

$client = new Client(['allow_redirects' => true]);

$statsHandler = new class
{
    public $totalTime = 0;

    public function __invoke(TransferStats $stats)
    {
        $this->totalTime += $stats->getHandlerStat('total_time');
    }
};

$finalResponse = $client->get('http://goo.gl', ['on_stats' => $statsHandler]);

echo $statsHandler->totalTime;
```

The same approach works for async requests without any changes.

**Comment by pkoscisz** [comment]
Wow, thank you very much, will test that solution :)

**Comment by gmponos** [comment]
Any feedback? can we close this?
