### ISSUE TITLE
unable to set `CURLOPT_ENCODING` to empty string to send all supported encoding by curl

### ISSUE THREAD

**Issue by deepika-maj** [guzzle/guzzle#2270]
**Guzzle version(s) affected**: 5.3.3

**Description**  
How can I set CURLOPT_ENCODING to empty string as following config is not working:

```
$httpClient = new Client([
    'curl' => [
        CURLOPT_ENCODING => ''
    ]
]);
```

**Comment by gmponos** [comment]
> Guzzle version(s) affected: 5.3.3

Are you using guzzle v5?

if not.. and you are using v6.. how did you validated that the curl option is not working?

We will need a reproducing example that clearly displays a bug.
