### ISSUE TITLE
Guzzle is not able to send a valid request when `php-curl` extension is not installed and request body is a stream of `php://input`

### ISSUE THREAD

**Issue by ihorsamusenko** [guzzle/guzzle#2276]
**Guzzle version(s) affected**: 6.3.0

**Description**  
Guzzle is not able to send a valid request when `php-curl` extension is not installed and request body is a stream of `php://input`

**How to reproduce**  
Make a POST request with body to a php app. In the app put the following code:
```
// client needs to send this request to NGINX
$client = new Client(
            [
                'base_uri' => 'http://some-nginx-server',
            ]
        );

$request = new \GuzzleHttp\Psr7\Request(
            'POST',
            '/path',
            [
                'Accept' => 'application/json',
                'Content-Type' => 'application/json'
            ],
            fopen('php://input', 'rb')

        );
$response = $client->send($request);
```
nginx will log an error: 
`[error] 10#10: *6 client sent invalid chunked body`

**Possible Solution**  
installing php-curl extension fixes it. But this _is not that obvious_ :)

**Additional context**  
I had this issue in docker alpine container.

**Comment by fanuch** [comment]
Installed and got rid of my error too:
```
Error creating resource: [message] fopen(): Filename cannot be empty
```

Thanks for the suggestion!

**Comment by ihorsamusenko** [comment]
This bug is quite nasty, please don't close the issue, as this is not resolved.

**Comment by Nyholm** [comment]
Somehow the StreamHandler does not like when you using `php://input` as request body. 

I think this is a super edge case and you can simply rewrite the code to something like: 

```php
$input = fopen('php://input', 'rb');
$resource = fopen('php://temp', 'w+');
fwrite($resource, stream_get_contents($input));
fclose($input);
```

I vote for this to be closed.

**Comment by ihorsamusenko** [comment]
Well, I spent the whole day figuring the issue out - quite critical in my opinion.
Especially, when we talk about the defacto standard library for HTTP in PHP. 

@Nyholm if StreamHandler "doesn't like", it would a nice thing to see a warning or even an exception.

**Comment by GrahamCampbell** [comment]
It would be cool if the stream handler automatically did this.

**Comment by GrahamCampbell** [comment]
Is there a way for PHP to tell if a resource is the input stream?

**Comment by ihorsamusenko** [comment]
https://www.php.net/manual/en/function.stream-get-meta-data.php should work

**Comment by GrahamCampbell** [comment]
I was actually unable to replicate this in Guzzle master with:

```
<?php

require_once __DIR__.'/vendor/autoload.php';

$client = new GuzzleHttp\Client(
    [
        'base_uri' => 'https://example.com/',
        'handler' => new GuzzleHttp\Handler\StreamHandler(),
    ]
);

$request = new GuzzleHttp\Psr7\Request(
    'POST',
    '/path',
    [
        'Accept' => 'application/json',
        'Content-Type' => 'application/json'
    ],
    fopen('php://input', 'rb')
);

$response = $client->send($request);

echo GuzzleHttp\Psr7\Message::toString($response);
```

The script completed without error, echoing:

```
HTTP/1.1 411 Length Required
Content-Type: application/json
Content-Length: 61
Connection: close
Date: Mon, 05 Oct 2020 16:08:47 GMT
Server: ECSF (nyb/1D27)

{"success": false, "errors": [{ "message": "", "code": 411}]}
```

**Comment by ihorsamusenko** [comment]
@GrahamCampbell try to uninstall php-curl extension

**Comment by GrahamCampbell** [comment]
Does https://github.com/guzzle/psr7/pull/354 fix your issue?
