### ISSUE TITLE
Question about asynchronous requests

### ISSUE THREAD

**Issue by msaus** [guzzle/guzzle#2281]
At the time of asynchronous communication, do you have registration process inside fulfilled or after the pool of requests completed?

$client = new Client();

$requests = function ($total) {
    $uri = 'http://127.0.0.1:8126/guzzle-server/perf';
    for ($i = 0; $i < $total; $i++) {
        yield new Request('GET', $uri);
    }
};

$pool = new Pool($client, $requests(100), [
    'concurrency' => 5,
    'fulfilled' => function ($response, $index) {
        **// Is it better to have registration process here?**
    },
    'rejected' => function ($reason, $index) {
        // this is delivered each failed request
    },
]);

// Initiate the transfers and create a promise
$promise = $pool->promise();

// Force the pool of requests to complete.
$promise->wait();
**// Is it better to have registration process here?**

**Comment by alexeyshockov** [comment]
It's not clear from the description, what "registration process" stands for.

If you need to do something with the responses, you have only one place to do that: in the `'fulfilled'` callback. If you don't rely on the response data and want to do something in the end, after the pool is over, do it after `->wait()`.

P.S. IMO StackOverflow is suited better for such type of questions.

**Comment by gmponos** [comment]
> StackOverflow is suited better for such type of questions.
