### ISSUE TITLE
StreamHandler garbles deflated content

### ISSUE THREAD

**Issue by ranvis** [guzzle/guzzle#2282]
**Guzzle version(s) affected**: 6.3.3

**Description**  
StreamHandler actually supports gzip encoding only.
If deflate encoded response is fed, it skips nonexistent gzip header and try to decode from the middle of the compressed data, resulting decode error.

**How to reproduce**  
client.php:
```
<?php
use GuzzleHttp\Client;
use GuzzleHttp\HandlerStack;
use GuzzleHttp\Handler\StreamHandler;
$client = new Client(['handler' => HandlerStack::create(new StreamHandler())]);
$response = $client->request('GET', 'http://127.0.0.1:8000/server.php?ce=deflate');
var_dump((string)$response->getBody());
```
http://127.0.0.1:8000/server.php:
```
<?php
$content = str_repeat("Hello, world!", 10);
$ce = $_GET['ce'] ?? '';
if ($ce == 'gzip') {
    $content = gzencode($content);
} elseif ($ce == 'deflate') {
    $content = gzcompress($content);
} elseif ($ce == 'deflatems') {
    $content = gzdeflate($content);
} elseif ($ce == 'br') {
    $content = brotli_compress($content);
}
header('Content-Encoding: ' . $ce);
header('Content-Length: ' . strlen($content));
echo $content;
```

output: string(0) ""

**Possible Solution**  
Stop supporting deflate Content-Encoding.

**Comment by kkopachev** [comment]
Related: https://github.com/guzzle/psr7/pull/215

**Comment by kkopachev** [comment]
Fixed by https://github.com/guzzle/psr7/pull/215

**Comment by Nyholm** [comment]
Thank you
