### ISSUE TITLE
Request to cyrillic domain fails

### ISSUE THREAD

**Issue by Jekis** [guzzle/guzzle#2285]
**Guzzle version(s) affected**: 6.3.3

**Description**  

Request to cyrillic domain fails.

**How to reproduce**  

```
$httpClient = new \GuzzleHttp\Client();
$response = $httpClient->get('https://русские-домены.рф');
echo (string)$response->getBody();
```
**Possible Solution**  

It fails due to *Host* header in `GuzzleHttp\Psr7\Request::updateHostFromUri()`
Header must be converted using `idn_to_ascii()` function.

**Additional context**  

But it works using `curl`

```
$ch = curl_init('https://русские-домены.рф');
curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
$html = curl_exec($ch);
curl_close($ch);
echo $html;
```

**Comment by alexeyshockov** [comment]
Nice catch.

Please, take a look at #2286, it should fix your issue.

**Comment by ThomasLandauer** [comment]
Just dropping a few search keywords for better discoverability of this issue:
* IDNA
* punycode
* International Domain Names
* Umlaut
