### ISSUE TITLE
JSON POST always returns HTTP 200?

### ISSUE THREAD

**Issue by Binternet** [guzzle/guzzle#2290]
**Guzzle version(s) affected**: 6.3.3

**Description**  
Guzzle ignores the HTTP response code from the server and returns HTTP 200 when I pass the `json` option

**How to reproduce**  
```
            $headers = ['Accept' => 'application/json']
            $body = [];
            $response = $client->request('POST', 'http://localhost/test.php', [
                'json' => $body,
                'headers' => $headers
            ]);
  var_dump($response);
```

Response is:
```
Response {#588 ▼
  -reasonPhrase: "OK"
  -statusCode: 200
  -headers: array:4 [▶]
  -headerNames: array:4 [▶]
  -protocol: "1.1"
  -stream: Stream {#591 ▶}
}

```
While the contents of `test.php` is only to return 401 using `http_response_code(401);`
Postman returns 401, guzzle returns 200.

Its important to mention that in the json body I have a base64 encoded file.

**Possible Solution**  

**Additional context**

**Comment by Binternet** [comment]
It appears that the server returns:
```
<br />
<b>Deprecated</b>:  Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php://input stream instead. in <b>Unknown</b> on line <b>0</b><br />
<br />
<b>Warning</b>:  Cannot modify header information - headers already sent in <b>Unknown</b> on line <b>0</b><br />
```

With HTTP 200, so I assume its a server issue and not Guzzle's.

**Comment by marcus2vinicius** [comment]
@Binternet do you fixed this problem?

**Comment by GrahamCampbell** [comment]
I don't see how this is a bug with Guzzle?

**Comment by gmponos** [comment]
I am locking this discussion. As it seems that the problem was in the server and adding noise to this kind of issues does not help.

Please be advised that there are also other channels for support like stackoverflow or https://github.com/guzzle/.github/blob/master/.github/SUPPORT.md

Thank you.
