### ISSUE TITLE
Extract GuzzleHttp\Tests\Server into standalone composer package.

### ISSUE THREAD

**Issue by martinssipenko** [guzzle/guzzle#2295]
**Description**  
Guzzle has a great mock server tooling that is used for testing http requests. I would like to propose to extract the tooling into standalone composer package so that other projects that need similar tooling could benefit from it.

The "mock-server" then could be installed as `dev-dependancy` and used in tests that need to make http requests.

Currently the only option is to copy/paste the `GuzzleHttp\Tests\Server` class and `server.js` files into project, which is not ideal.

I'd be more than happy to contribute, but given this would require a new project setup (repository, composer, ci), I'd like to discuss how this could be achieved. If it's decided to do this, should this be done as part of guzzle organisation? Or if not, is it ok to copy code into different project?

Looking forward to your thoughts.

**Comment by Nyholm** [comment]
Let’s consider this for 7.0

**Comment by sagikazarmark** [comment]
@martinssipenko the code is open source, so as long as you retain the original license, you are free to copy the code.

Personally, I think the mock server is a great way to test Guzzle itself, but depending code should rather be covered by integration tests, not unit tests. Also, ideally your HTTP dependencies are abstracted away with some sort of intermediate interface, so your business logic does not actually depend on anything HTTP.

**Comment by gmponos** [comment]
I guess this is related with https://github.com/guzzle/guzzle/issues/2228

**Comment by rhzs** [comment]
This issue is still relevant, I am using Guzzle ^7.0 but I can't find `GuzzleHttp\Tests\Server` as the doc mentioned. Why is this issue becoming stale and not relevant??

<img width="1295" alt="Screen Shot 2020-09-26 at 15 05 51" src="https://user-images.githubusercontent.com/5300674/94336039-22e46b00-000a-11eb-9d8a-27d0a88eb382.png">

**Comment by Nyholm** [comment]
It issue was incorrectly marked as stale. Sorry for that. 

I see that your issue is because you installed the package with composer. Try cloning the repository instead.

**Comment by martinssipenko** [comment]
I'm closing this issue.

**Comment by silverjason** [comment]
IF anyone is looking for a solution without having to use the test server:

While trying to test a middleware, I used a different way to test it without the test server.
Basically I was able to assign a dummy handler which just returns a fulfilled promise. This replaces the CurlHandler which means it doesn't execute any actual curl request.

      //Assign dummy mock handler to replace CurlHandler
        $mockHandler = function ()  {
            return new FulfilledPromise(new Psr7Response());
        };
        $client = new Client(['handler' => $handlerStack]);
