### ISSUE TITLE
Function name must be callable

### ISSUE THREAD

**Issue by Beee4life** [guzzle/guzzle#2297]
**Guzzle version(s) affected**: 6.x

**Description**  

My PhpStorm throws an error in CurlFactory.php line 519

This is the if wrapping it:
```
if ($onHeaders) {
    try {
        $onHeaders($easy->response);
    } catch (\Exception $e) {
        // Associate the exception with the handle and trigger
        // a curl header write error by returning 0.
        $easy->onHeadersException = $e;
        return -1;
    }
}
```

The error is thrown on ` $onHeaders($easy->response);`.

![Screenshot 2019-05-06 at 10 12 49](https://user-images.githubusercontent.com/4508731/57213740-0811f080-6fe8-11e9-9013-8576d3a2f965.png)

**How to reproduce**  

View the file with PhpStorm (I think)... I never configured anything...

**Comment by alexeyshockov** [comment]
Try to update to master and check if the error still there.

Also do you get an error/exception when you run your script? Or your concerns are just about PHPStorm highlighting the line above?

**Comment by Beee4life** [comment]
Concerns is a big word :) I just noticed it and thought I'd report it.

I didn't notice any errors while using it (yet)...

**Comment by Tobion** [comment]
This is just a false positive PhpStorm warning. I fixed that in https://github.com/guzzle/guzzle/commit/49086392c15e3bfe26be148618aee64332158284 as far as I remember.
You seem to use a very old Guzzle version btw.
