### ISSUE TITLE
Guzzle 6 Returns JSON body with HTTP Headers

### ISSUE THREAD

**Issue by rsalunga29** [guzzle/guzzle#2298]
I'm having a problem with how Guzzle 6.x returns my results, due to this I am receiving "Syntax Error" when I try to ```json_decode``` my results. I have used ```var_dump()``` and ```print_r()``` to get my actual results and it turns out that my JSON results returns with a HTTP Header included in it. Actual results below:

```json
string(486) "Array
(
    [Content-Type] => application/json
    [Content-Length] => 23
    [X-Auth-Key] => XXXXXXXXXXXXXXXXXXXXXXX
    [X-Apikey] => XXXXXXXXX
    [User-Agent] => GuzzleHttp/6.3.3 curl/7.54.0 PHP/7.1.23
    [Host] => example.com
)
{
    "message": {
        "value": "successful",
        "status_code": "200"
    },
    "details": {
        "status": [
            "00:00|Data 1|"
        ]
    }
}"
```

I've done my research and I've tried altering my code I've tried the following:

```php
$result = (string) $response->getBody(); // 1

$result = $response->getBody()->getContents(); // 2
```

Below is my code on how I send HTTP requests to my server:

```php
$response = $this->client->post('', [RequestOptions::JSON => $data]);
$result = $response->getBody()->getContents();
$contents = json_decode($raw); // this returns NULL and syntax error
```

My expected results should be this:

```json
{
    "message": {
        "value": "successful",
        "status_code": "200"
    },
    "details": {
        "status": [
            "00:00|Data 1|"
        ]
    }
}
```

**Comment by phansys** [comment]
@rsalunga29, please check the tests at #2299. They couldn't reproduce what you are describing.
