### ISSUE TITLE
Cannot send already serialized json array

### ISSUE THREAD

**Issue by GuillaumeTediber** [guzzle/guzzle#2302]
**Guzzle version(s) affected**: 6.3.3

**Description**  
We have a serialised array of json objects. 
If we use json option for a put or post request, the array is serialised a second time.
If we use body option, we get an error triggered by `is_array($options['body'])` :

> Passing in the "body" request  option as an array to send a POST request has been deprecated. Please use the "form_params" request option to send a application/x-www-form-urlencoded request, or the "multipart" request option to send a multipart/form-data request.

We can only decode and encode again with json option, is it possible to modify this depreceated?

Thank you,
Regards,
Guillaume

**Comment by alexeyshockov** [comment]
Could you add an example of "a serialised array of json objects"?

I assume it's a string, but in this case you should not have any issues passing it to `body` request option.

**Comment by Nyholm** [comment]
I agree with Alexey. Closing due inactivity.
