### ISSUE TITLE
Empty POST form_parameters are ignored/excluded

### ISSUE THREAD

**Issue by JakeBooher** [guzzle/guzzle#2307]
**Guzzle version(s) affected**: 6.3.3

**Description**  
Guzzle isn't including empty parameters that I pass in the request which is causing issues with Paypal IPN as there are cases in which they can have an empty parameter

**How to reproduce**  
This is the request from PayPal's callback to our server, as you can see `item_number1` is empty (even though we don't pass it at all) so PayPal is expecting verification request to contain that key with an empty value, but Guzzle (or, more specifically `http_build_query`) is excluding this value breaking our payment handling. This seems undesirable as there are plenty of valid use cases for an empty string vs no input whatsoever. `transaction_subject` is another example here.

```
mc_gross=8.00&protection_eligibility=Eligible&item_number1=&payer_id=LB586C6G5CH5E&payment_date=12%3A58%3A40+Jun+04%2C+2019+PDT&payment_status=Completed&charset=windows-1252&first_name=John&mc_fee=0.53&notify_version=3.9&custom=6434ef74-084a-4886-8b9f-73c456b66156&payer_status=verified&business=admin%40dev.com&num_cart_items=1&verify_sign=AtUbgugC4KybUOS9Xzrs4wqyfk7uATYehOVtD0vU.0Xr-gggOILSnxms&payer_email=customer%40dev.com&txn_id=21473347HY3854026&payment_type=instant&last_name=Doe&item_name1=%241+Credit+Package&receiver_email=admin%40dev.com&payment_fee=0.53&shipping_discount=0.00&quantity1=8&receiver_id=VN2QJHXRA2BAL&insurance_amount=0.00&txn_type=cart&discount=0.00&mc_gross_1=8.00&mc_currency=USD&residence_country=US&test_ipn=1&shipping_method=Default&transaction_subject=&payment_gross=8.00&ipn_track_id=4d17b09ba30d
```

**Comment by thicolares** [comment]
Hey @JakeBooher, I would like to confirm that I understand it correctly.

So, given a request with a `null` param such as:

```php
$client->request('POST', 'path', [
    'form_params' => [
        'my_null_param' => null // will be ignored
    ]
]);
```

You expect`my_null_param` **not to be ignored by guzzle** (currently, guzzle indeed does). This is it?

----

And strictly speaking, guzzle ignores `null` variables in form_params. But if that's an **empty string,** guzzle doesn't ignore it:
```php
$client->request('POST', 'path', [
    'form_params' => [
        'my_empty_string_param' => '' // will NOT be ignored
    ]
]);
```

**Comment by gmponos** [comment]
I don't have anything more to add to @thicolares answer..
