### ISSUE TITLE
form_params not sending

### ISSUE THREAD

**Issue by KieronWiltshire** [guzzle/guzzle#2308]
**Guzzle version(s) affected**: 6.3^

**Description**  
I'm using Guzzle to send a post request, however the form_params can't be found on the server.

**How to reproduce**  
```php
          $client = new HttpClient([
            'base_uri' => url(''),
            'http_errors' => false
          ]);

          // Guzzle is not guzzling.
          // form params not sending...
          $freeBetResponse = $client->post('pulse/server/api/wallet?cmd=PLACE_FREE_BET&generateBetId=true', [
            'form_params' => [
              'account_id' => $player->id,
              'game_id' => $game->id,
              'amount' => 0
            ],
            'headers' => [
              'Authorization' => 'ApiKey ' . $apiKey->key
            ]
          ]);
```

**Additional context**  
Here is what I'm doing on the server then to debug:
```php
$database->Debug('ACCOUNT ID FROM API  : : ' . print_r($_REQUEST, true));
```

Which outputs:
```
(
    [cmd] => PLACE_FREE_BET
    [generateBetId] => true
)
```

**Comment by gmponos** [comment]
From the context of the issue this does not seem neither as a bug nor as a feature request. Support questions should be addressed to other channels like https://github.com/guzzle/.github/blob/master/SUPPORT.md

If there is something that I miss please feel free to provide more context.
