### ISSUE TITLE
[bug?]option connect_timeout do not work

### ISSUE THREAD

**Issue by xiezhen19920612** [guzzle/guzzle#2310]
**Guzzle version(s) affected**: 6.3.3

**Description**  
option connect_timeout does not work

**How to reproduce**  
![image](https://user-images.githubusercontent.com/16033066/59410548-b2511500-8deb-11e9-9384-18225f3a1d49.png)
![image](https://user-images.githubusercontent.com/16033066/59410575-bf6e0400-8deb-11e9-9c8d-8dbdffd608f8.png)

1. set guzzle http client option connect_timeout to 1
2. make a http request to a domain which is not exists by guzzle client
3. but it used 10s

**Possible Solution**  

**Additional context**  
centos 7
php 7.0.30

**Comment by gmponos** [comment]
Checking the code it seems that the message is predefined by curl.

two things here. 

1. Adding debug option could be helpful: http://docs.guzzlephp.org/en/stable/request-options.html#debug
2. Giving more info here like the stack trace of the exception.

**Comment by GrahamCampbell** [comment]
"connect_timeout" is not the only timeout. That only is the timeout on waiting for the first byte, essentially. You probably need to also set timeout on reads (called `read_timeout`).
