### ISSUE TITLE
Feature: can set default CookieJar for Client

### ISSUE THREAD

**Issue by 4n70w4** [guzzle/guzzle#2316]
**Description**  
This is useful for api clients where need to add a cookie stored in a database or somewhere else.

**Example**  
`new Client([RequestOptions::COOKIES => $cookieJar]);`

**Comment by gmponos** [comment]
I don't understand what this issue is about. Can you provide more info?

**Comment by gmponos** [comment]
Closing as comment on the related PR here: https://github.com/guzzle/guzzle/pull/2317
