### ISSUE TITLE
function name must be callable

### ISSUE THREAD

**Issue by Beee4life** [guzzle/guzzle#2321]
**Guzzle version(s) affected**: 6.2.x

**Description**  
The function createHeaderFn() (in CurlFactory.php line 496) gives a permanent error in PhpStorm.

**How to reproduce**  
I didn't do anything, it's just there after install

**Possible Solution**  
No suggestions.

**Additional context**  
![Screenshot 2019-06-26 at 15 37 21](https://user-images.githubusercontent.com/4508731/60184643-b6882400-9828-11e9-8bd6-7be5ec2f41cc.png)

**Comment by andrewnclark** [comment]
This issue appears to have been fixed from 6.2.1 onward. The best course of action would be to use version `^6.2.1`  I believe.

**Comment by Nyholm** [comment]
Please provide a failing unit test to prove this bug. Until then I'll close this issue thanks to @andrewnclark comment.
