### ISSUE TITLE
Allow yielding objects as keys in Pool requests

### ISSUE THREAD

**Issue by BenMorel** [guzzle/guzzle#2322]
**Description**  

Guzzle [can now](https://github.com/guzzle/guzzle/pull/1203) yield `int` and `string` keys in `Pool`. This is very useful, but sometimes we need more.

For example, in [spatie/crawler](https://github.com/spatie/crawler) we'd like to pass a `CrawlUrl` object as the key to `Pool` requests, to avoid a lookup in the `fulfilled` and `rejected` callbacks to get the original object back, thereby simplifying the code and improving performance.

**Example**  

Before:

```php
$pool = new Pool($this->client, $this->getCrawlRequests(), [
    'fulfilled' => function(ResponseInterface $response, string $url) {
        // lookup the original CrawlUrl object from the stringified URL
        $crawlUrl = $this->crawlQueue->lookup($url);
    }
]);
```
```php
protected function getCrawlRequests(): Generator
{
    while ($crawlUrl = $this->crawlQueue->getFirstPendingUrl()) {
        ...
       // yield the stringified URL that can be used to lookup the original CrawUrl object later
       yield ((string) $crawlUrl->url) => new Request('GET', $crawlUrl->url);
    }
}
```

After:

```php
$pool = new Pool($this->client, $this->getCrawlRequests(), [
    'fulfilled' => function(ResponseInterface $response, CrawlUrl $crawlUrl) {
        // use the CrawlUrl object directly!
    }
]);
```
```php
protected function getCrawlRequests(): Generator
{
    while ($crawlUrl = $this->crawlQueue->getFirstPendingUrl()) {
        ...
       // yield the CrawlUrl object directly!
       yield $crawlUrl => new Request('GET', $crawlUrl->url);
    }
}
```

**Required changes**

The issue lies in the use of native arrays, for example in `EachPromise` we get an *Illegal offset type* error in `$pending` when attempting to yield an object as key:

https://github.com/guzzle/promises/blob/e6d006f1ced100d81755966f09625d71ce6a7dca/src/EachPromise.php#L157

The solution would be to either:

- explicitly handle objects by replacing them with their [hash](https://www.php.net/manual/en/function.spl-object-hash.php) or [id](https://www.php.net/manual/en/function.spl-object-id.php) 
- or better yet, replace arrays with a generic map implementation, such as the [polyfill](https://github.com/php-ds/polyfill) for [Ds\Map](https://www.php.net/manual/en/class.ds-map.php) or a simpler, custom implementation.

If you're willing to go ahead with this request, I can submit a PR!

**Comment by kkopachev** [comment]
There is a way to achieve this without yielding objects as keys.
`Pool` can accept iterable of callables as it's argument. It does not have to be requests. 
So you could create array of callbacks like: 
```php
yield => function() use ($crawlUrl) {
    return $client->sendAsync(new Request('GET', $crawlUrl->url))->then(function($response) use($crawlUrl) { 
        return [$response, $crawlUrl]; // or just wrap them in custom object?
    });
}
``` 

You can use `EachPromise` directly, so you can skip passing useless `$client` to `Pool`

**Comment by Tobion** [comment]
Closing as there seems to be a solution.
