### ISSUE TITLE
Large file download support

### ISSUE THREAD

**Issue by jdescelliers** [guzzle/guzzle#2324]
**Guzzle version(s) affected**: 6.3.3
**PHP versions **: 5.6/7.0
**Description**  
Large file download native support.

**How to reproduce**  
Perform an HTTP request on a resource that is larger than PHP memory_limit setting.

No matter what settings I add to the client constructor, even content-type:application/json or any other parameter is ignored.

Please try to answer the question about native support and the problem ms listed above before considering closing this.

Thanks.

The code : 

```php
$url = "https://some-url.com";

            $jar = CookieJar::fromArray
            (
                [
                    "session_id" => "ABCD123"
                ], "https://some-url.com"
            );

            $client = new \GuzzleHttp\Client(
                [
                    "headers" => ["Content-Type" => "application/json"],
                    "body"    => json_encode( $dataArray ),
                    "cookies" => $jar
                ]
            );
            $r = $client->post( $url );

```

Now, the cookie content is accurate, and yet when I inspect the response, I don't see the headers I set and do not get the expected response body.

Is there something obvious I missed?

**Comment by alexeyshockov** [comment]
Have you tried using [`sink` option](http://docs.guzzlephp.org/en/stable/request-options.html#sink) to stream the response body to a file directly?
