### ISSUE TITLE
URL pointing to the localhost

### ISSUE THREAD

**Issue by oleonides** [guzzle/guzzle#2325]
does guzzle have issues when using the localhost as the base_uri?

for example:
if I use this BASE URI `localhost:8000` it works perfect, of course in this case I run the virtual host in lumen.

but if I use the URL `http://localhost/LumenAuthorsApi/public/` does not work and get a 500 internal server error.

thanks.

**Comment by asadsureify** [comment]
500 is a server side error. It has nothing to do with http client you are using.
Here is a list of codes for reference https://developer.mozilla.org/en-US/docs/Web/HTTP/Status

**Comment by oleonides** [comment]
yes I could figure it out, it was nothing related to guzzle.

thanks.
