### ISSUE TITLE
Zttp

### ISSUE THREAD

**Issue by johnss** [guzzle/guzzle#2328]
**Description**  
Guzzle developer team seems focus just to improve the manageabilty of the code for big apps instead of focusing on programming with less code
**Example** 
With Zttp it needs just 2 or 3 lines of code while with Zttp it need significantly more lines of code, i hope in the next major releases can bring some idea from Zttp

**Additional context**
it is article from 2017 but most probably still relevant now because guzzle rarely introduce new API (class method and property) to make coding faster & easier https://laravel-news.com/zttp-guzzle-wrapper

**Comment by sagikazarmark** [comment]
Guzzle is a mid-level HTTP client library providing a rich API over several HTTP client solutions in PHP. 

IMHO simplifying the API would make the library less flexible. If you find the API too complex, wrappers like Zttp might be the way to go for you.
