### ISSUE TITLE
Support curl_multi options

### ISSUE THREAD

**Issue by darvids0n** [guzzle/guzzle#2329]
**Description**  
I'm using Guzzle to download many files in parallel using PSR-7 streams. At the moment we can construct a CurlMultiHandler which passes options to each handle via `$options['curl']`. However, passing options to the implicit multihandle resource `$this->_mh` is not supported, and is currently an implementation detail.

**Example**  
```php
$client = new \GuzzleHttp\Client();
$request = new \GuzzleHttp\Psr7\Request('GET', 'http://httpbin.org');
$options = [
    'curl' => [
        CURLOPT_TIMEOUT => 300,
    ],
    'curl_multi' => [
        CURLMOPT_MAX_HOST_CONNECTIONS => 4,
    ]
];
$promise = $client->sendAsync($request, $options)->then(function ($response) {
    echo 'I completed! ' . $response->getBody();
});
```

**Additional context**
Some of the config this would allow is already achievable using an EachPromise, but this feature request is more about the general functionality as well as future-proofing for any newly defined CURLMOPT options which may be useful to define in some edge cases.

**Comment by alexeyshockov** [comment]
Take a look at the related PR #2287, it adds `curl_multi` option to the client configuration level. It makes more sense to do it there, because multi options affect a bunch of requests, not only one.
