### ISSUE TITLE
update documentation on website 

### ISSUE THREAD

**Issue by corexz** [guzzle/guzzle#2332]
****Description****  
while I was working with Guzzle, I come through the documentation , 
http://docs.guzzlephp.org/en/stable/request-options.html#body
and when sending Body in the param array i got this exception message .

> InvalidArgumentException Passing in the "body" request option as an array to send a POST request has been deprecated. Please use the "form_params" request option to send a application/x-www-form-urlencoded request, or the "multipart" request option to send a multipart/form-data request.

the problem fixed when i replace body with form_params

****Example****  
the following code through the above  exception 

```
$response = $client->request('GET', $url, ['headers' => [
            'content-type' => 'application/x-www-form-urlencoded'         
        ],
        'body' => [
            'grant_type' => 'XXX',
            'username' => 'XXXX',
            'password' => 'XXXX'
        ]
    ]);

```
this code will not through the exception

```
$response = $client->request('GET', $url, ['headers' => [
            'content-type' => 'application/x-www-form-urlencoded'         
        ],
        'form_params' => [
            'grant_type' => 'XXXX',
            'username' => 'XXXX',
            'password' => 'XXXX'
        ]
    ]);

```
**advice**
please update the docs.

**Comment by atymic** [comment]
Unless I'm missing something, the accepted types shown on the docs are:
```
string
fopen() resource
Psr\Http\Message\StreamInterface
```

Which is correct?
I can't see anything stating that `array` is supported.

**Comment by sagikazarmark** [comment]
@corexz this is the expected functionality and as far as I can tell, it's documented properly.

http://docs.guzzlephp.org/en/stable/request-options.html#body
http://docs.guzzlephp.org/en/stable/request-options.html#form-params
