### ISSUE TITLE
Guzzle Post Request doesn't work in production

### ISSUE THREAD

**Issue by sairam2188** [guzzle/guzzle#2336]
I am making a Post request through Guzzle, everything works fine in my local environment, but in production it does not work, it does not give error or messages in the log file

On my local server I use Wamp Server, with laravel and php 7.0.29. In production I use a shared hosting with Bluehost and the same version of php

`$client = new Client(["base_uri" => url()]);

$options = [
    'form_params' => $form
];
$response = $client->post("/salud/parte2", $options);`

I receive status code 200 but when reviewing the database I hope the form is saved but it does not

**Comment by sagikazarmark** [comment]
If you receive a 200 status code, it means the server processed your request. If your data is not saved, it's a server side problem.

**Comment by sairam2188** [comment]
> If you receive a 200 status code, it means the server processed your request. If your data is not saved, it's a server side problem.

It's weird because everything works fine in the local environment, in production it doesn't do anything

**Comment by sagikazarmark** [comment]
Even more likely, that it's not a client side issue.
