### ISSUE TITLE
Guzzle not working when encoded with source guardian

### ISSUE THREAD

**Issue by stoufa06** [guzzle/guzzle#2338]
**Guzzle version(s) affected**: 6.3.3

**Description**  
I have encoded my entire project with source guardian then i have received multiple warning and notices and guzzle http client does not work anymore. After some troubleshooting i have found the cause.
in src/Handler/StreamHandler.php line 324
```
$this->lastHeaders = $http_response_header;
```

**How to reproduce**  

install source guardian and encode the files
run simple code
```
use GuzzleHttp\Client;
$client = new Client(['timeout' => '15']);
$result = $client->get($url)
```

**Possible Solution**  
use stream_get_meta_data function instead
```
$http_response_header = stream_get_meta_data($resource)['wrapper_data'];
```

**Comment by Nyholm** [comment]
Hey. 
Thank you. 

Im not familiar with source guardian. You need to provide way more details if you want to convince me that this is a Guzzle issue and not an issue with source guardian.

**Comment by gmponos** [comment]
Closing as no feedback has been provided.. :)
