### ISSUE TITLE
Undefined offset: 1 in CurlFactory.php

### ISSUE THREAD

**Issue by Gerk** [guzzle/guzzle#2339]
**Guzzle version(s) affected**: 6.3.3

**Description**  
Currently this is tossing notices in my log files constantly.  I do have a letsencrypt SSL file in place, but guessing this is assuming that something (password?) is populated in `$sslKey[1]` and it's not in my case.  This is a production instance and haven't tried pulling updates yet (but the code appears unchanged in current release on a quick glance).

**How to reproduce**  
Code block:
```            $sslKey = $options['ssl_key'];
            if (is_array($sslKey)) {
                $conf[CURLOPT_SSLKEYPASSWD] = $sslKey[1];
                $sslKey = $sslKey[0];
            }
```
**Possible Solution**  
Not necessarily the best way to do this, but it will squelch all the warnings.  I don't have enough familiarity with the code base to suggest a better fix at this point ... but this does quiet the warnings in my case.
Code block:
```
            $sslKey = $options['ssl_key'];
            if (is_array($sslKey)) {
                $conf[CURLOPT_SSLKEYPASSWD] = @$sslKey[1];
                $sslKey = $sslKey[0];
            }
```
**Additional context**

**Comment by andrewnclark** [comment]
Can you share the options array you are passing into the request? I would Imagine that you are doing something along these lines where there is no password provided:

```php
$options = [
    'ssl_key' => ['/some/file/path']
]
```

The easiest fix for you would be to change those options and pass a string as your sslkey option instead of an array, like so:

```php
$options = [
    'ssl_key' => '/some/file/path'
]
```

That being said, I am working on a PR that doesn't suppress the warnings.

**Comment by Gerk** [comment]
I will check on this, I just have to remember which project was tossing these warning :)

**Comment by Gerk** [comment]
Confirmed.  Changing it to a string eliminated the error.  The fix in your PR looks like it should work.

**Comment by andrewnclark** [comment]
> Confirmed. Changing it to a string eliminated the error. The fix in your PR looks like it should work.

Brilliant. Glad I could help!
