### ISSUE TITLE
Can we change this to let JSON pass in the second parameter control?

### ISSUE THREAD

**Issue by baicaiit** [guzzle/guzzle#2342]
Can we change this to let JSON pass in the second parameter control?
![image](https://user-images.githubusercontent.com/42630572/62263930-7a139d80-b450-11e9-8138-ed111dc134fa.png)

**Comment by andrewnclark** [comment]
I can see how this would be useful and achievable by tweaking the options. I'll submit a PR if they're open to the idea.

**Comment by andrewnclark** [comment]
I started work on something but it's possible to do what you need without changes so it's unlikely they will be merged. You request options array should look something like:

```php
[
    'body' => json_encode($data, JSON_UNESCAPED_UNICODE),
    'headers' => [
        'Content-Type' => 'application/json'
    ]
]
```

**Comment by Nyholm** [comment]
Thank you @andrewnclark for your answer!
