### ISSUE TITLE
Call to undefined function GuzzleHttp\\Psr7\\uri_for()

### ISSUE THREAD

**Issue by skkarthikdev** [guzzle/guzzle#2345]
use GuzzleHttp\Exception\GuzzleException;
use GuzzleHttp\Client; 
$client = new \GuzzleHttp\Client();
                $response = $client->request('POST', $api, [
                        'body' => $json,
                        'headers' => [
                            'Content-Type' => 'application/json'
                        ]
                ]);

"message": "Call to undefined function GuzzleHttp\Psr7\uri_for()", "exception": "Symfony\Component\Debug\Exception\FatalThrowableError", "file": "/var/www/html/equity-dev/vendor/guzzlehttp/guzzle/src/Client.php"

I am getting an error response as above for every guzzle request, please help me to solve this issue 
regards

**Comment by shijinbharati** [comment]
hey man, What is your problem?

**Comment by andrewnclark** [comment]
What version or Guzzle and PHP please?

**Comment by Nyholm** [comment]
You have forgotten to use composer's autoloader. 

If Im wrong, please ask your question on Stackoverflow or similar website.
