### ISSUE TITLE
why return nothing

### ISSUE THREAD

**Issue by npqzxc** [guzzle/guzzle#2351]
$client = new Client();;

        $response = $client->request('GET', 'https://api.github.com/repos/guzzle/guzzle');
var_dump($response->getStatusCode());die;
this code return nothing

**Comment by baspeeters** [comment]
@npqzxc When I run your code, I get a normal response.

Are you:
1. Loading libraries by including `vendor/autoload.php`?
1. Importing the client class with `use GuzzleHttp\Client;`?

**Comment by npqzxc** [comment]
I have 

> @npqzxc When I run your code, I get a normal response.
> 
> Are you:
> 
> 1. Loading libraries by including `vendor/autoload.php`?
> 2. Importing the client class with `use GuzzleHttp\Client;`?

it doesn't work in my local environment，but product it's ok

**Comment by Nyholm** [comment]
Closing due inactivity and because we cannot answer to support issues. Only bugs with the library.
