### ISSUE TITLE
Guzzle replaced my custom request class to GuzzleHttp\Psr7\Request

### ISSUE THREAD

**Issue by Selol** [guzzle/guzzle#2353]
**Guzzle version(s) affected**: 6.3.3

**Description**  

Summary:
      Guzzle replaced my custom Request class to GuzzleHttp\Psr7\Request
Detail:
I'm sending request and i want to use retry middleware, and I want to use another $host:$port when retrying, I think I should custom my own request class (implement RequestInterface of course) and call new method refreshUri in retry middleware. But in Client::applyOptions, it will change request class to GuzzleHttp\Psr7\Request(by using  Psr7\modify_request). This lead two issues
1. According to the doc of modify_request, it should return RequestInterface, but it can only return instance of Request of ServerRequest.
2. In Client::applyOptions, the default value of $modify is
       [
            'set_headers' => [],
       ];
     this behavior make modify_request will change the original request at any time

I'm wondering how to keep the custom request class, or how to use another $host:$port when retrying?
 

**How to reproduce**  

```php
class CustomRequest implements \Psr\Http\Message\RequestInterface
{
   // refresh uri to another $host:$port
   // other methods are copy from GuzzleHttp\Psr7\Request
    public function refreshUri()
    {
        // an valid url
        $this->uri = new \GuzzleHttp\Psr7\Uri('http://127.0.0.1:5000/');
    }
}

$decider = function ($retries, CustomRequest $request, $response, $error) {
    // try another host 
    $request->refreshUri();
    return true;
};


$stack = HandlerStack::create();
$stack->push(Middleware::retry($decider));

$client = new Client([
    'handler' => $stack,
]);
// a invalid url
$client->send(new CustomRequest('GET', 'http://127.0.0.1:6000/'));
```

**Comment by sagikazarmark** [comment]
> According to the doc of modify_request, it should return RequestInterface, but it can only return instance of Request of ServerRequest.

I don't see a contradiction here. It returns a `RequestInterface` which is the only guarantee Guzzle gives you. I think the doc should even explicitly say somewhere that there are no guarantees that the request object will always be the same. This is because if the immutable nature of PSR-7.

I think you are trying to solve to wrong problem. Instead of focusing on the custom request, I'd rather add a subsequent handler to the chain that checks the `$options['retries']` value. On the first request it's zero, on the first retry it's 1. The you can modify the request on your middleware and pass down any kind of request you want.

**Comment by Selol** [comment]
> I think the doc should even explicitly say somewhere that there are no guarantees that the request object will always be the same

agreed


> I'd rather add a subsequent handler to the chain

Thanks for your reply, but I'm sorry i don't quite understand, 
In Client::transfer, handler is called after Client::applyOptions(it will change my origin request), how does my custom handler know some custom informations(like next pair of host:port)？
```php
$request = $this->applyOptions($request, $options);
$handler = $options['handler'];
```

**Comment by Selol** [comment]
> I'd rather add a subsequent handler to the chain that checks the `$options['retries']` value. On the first request it's zero, on the first retry it's 1.

I think I just got your point, here it's my code, Look forward to your kindly reply.

```php
class MyRetryMiddleware extends \GuzzleHttp\RetryMiddleware
{

    public function __invoke(RequestInterface $request, array $options)
    {
        if (!isset($options['retries'])) {
            $options['retries'] = 0;
        }

        if ($options['retries'] > 0 && isset($options['on_retry'])) {
            $request = ($options['on_retry'])($request);
        }
        return parent::__invoke($request, $options);
    }

}


$stack = HandlerStack::create();
$middleware = function (callable $handler) {
    return new MyRetryMiddleware(
        function ($retries, $request, $response, $error) {
            if (!$response || $response->getStatusCode() != 200) {
                return true;
            } else {
                return false;
            }
        },
        $handler,
        null
    );
};
$stack->push($middleware);

$client = new Client([
    'handler' => $stack,
]);

echo $client->get('some invalid url', ['on_retry' => function (RequestInterface $request) {
    echo "in hook";
    return $request->withUri(new Uri('http://127.0.0.1:5000'));
}])->getBody();
```

**Comment by sagikazarmark** [comment]
I don't think you need to extend the middleware. You can write your own that comes after the retry middleware in the stack.

**Comment by Selol** [comment]
> I don't think you need to extend the middleware. You can write your own that comes after the retry middleware in the stack.

ok, thanks for your help. I think my problem is solved.
