### ISSUE TITLE
Throwing Error

### ISSUE THREAD

**Issue by bhaswanth97** [guzzle/guzzle#2356]
Hi
I am using this package in my project and I must say it is the great package and worked perfectly. But I am facing an issue while API returns error message.

When the requested URL returns an error, it's directly showing error page instead of returning the error as a response.

![image](https://user-images.githubusercontent.com/49803830/64421312-ecfedc80-d0be-11e9-9cd8-c263aec9ca75.png)

Here is my code

        $headers = ['Referer' => 'referrer_url'];
        $client = new Client();
        $result = $client->post('post_url', [
            'json' => $formdata
        ], ['http_errors' => false]);
        $res = $result->getBody()->getContents();
        $res = json_decode($res, true);

Any help regarding this will be appreciated.
Thank you

**Comment by SamuelNitsche** [comment]
The `post` method only expects two parameters, the uri and options (see http://docs.guzzlephp.org/en/stable/psr7.html#request-methods). I think correct would be the following code.

```php
$headers = ['Referer' => 'referrer_url'];
$client = new Client();
$result = $client->post('post_url', [
    'json' => $formdata,
    'http_errors' => false
]);
$res = $result->getBody()->getContents();
$res = json_decode($res, true);
```

**Comment by Nyholm** [comment]
RTFM
http://docs.guzzlephp.org/en/stable/request-options.html#http-errors
