### ISSUE TITLE
Status code 200, errno 23 after redirects

### ISSUE THREAD

**Issue by bperek** [guzzle/guzzle#2357]
**Guzzle version(s) affected**: 6.3.x-dev
**Description**  
I got some problems with website crawling, one of them is doing some redirects but at last request, I got status code of 200 but the request is failed. I've debugged a problem and it is in CurlFactory::finish method. Curl get error status 23 so it is finished with error. But on debugger, I can call 
`$html = $response->getBody()->rewind() && $response->getBody()->getContents()` and I recieve expected html.

It might be also cURL problem since when running request from console I got something like that:
![Screenshot from 2019-09-10 12-02-03](https://user-images.githubusercontent.com/8179472/64605514-921dfb80-d3c4-11e9-94fe-c6e9cc99a18b.png)

I'm not sure but it seems that curl have closed stream but after that error with failed writing body remaining html is sent.

Any clues how to handle such cases?

**Comment by Nyholm** [comment]
Hm... no. Not on the top of my head. 

Did you manage to solve it?
