### ISSUE TITLE
How to handle timeout exception in guzzle ?

### ISSUE THREAD

**Issue by nerdial** [guzzle/guzzle#2359]
Hello,
**Is there any official exception for handling timeout in guzzle ? 
Is there any way to get tcp socket error from guzzle object ? or does curl support such a thing at all ?** 

I have a couple of issues with exception handling listed below:

- **I need a way to handle timeout exception. i know there is a ConnectException for that, but this is not really precise and requires a lot efforts to handle it. if you believe i can implement a separate Exception for timeout please help me implement that.**

- **Second issue  is that since $e->getCode() return 0 in ConnectException and can't be used for troubleshooting and reporting. what i need is tcp socket error like** 
110 = Connection timed out
111 = Connection refused

"guzzlehttp/guzzle": "~6.0"
"php 7.2"

 sorry for asking many questions here.

**Comment by Nyholm** [comment]
```php
try {
  // Code
} catch(GuzzleHttp\Exception\GuzzleException $e) {
  // Handle excpetion
}
```

**Comment by MatteoOreficeIT** [comment]
Hi, and how to handle Async Request timeout ?

**Comment by alireza-nazari** [comment]
> ```
> try {
>   // Code
> } catch(GuzzleHttp\Exception\GuzzleException $e) {
>   // Handle excpetion
> }
> ```

That was not working for me, I just did like following code:
```
try{
    $this->request = $this->client->request('POST', $this->params);
    $this->response = $this->request->getBody()->getContents();
} catch (RequestException $e){
    Log::alert('Request Exception: '.$e ,[$this->params]);
}
```
Hope this help some body.

**Comment by ddse** [comment]
> ```
> try {
>   // Code
> } catch(GuzzleHttp\Exception\GuzzleException $e) {
>   // Handle excpetion
> }
> ```

that was worked for me.

**Comment by MikeGodin** [comment]
In PHP7, I had to use:

```
try {
  // Code
} catch(\GuzzleHttp\Exception\GuzzleException $e) {
  // Handle excpetion
}
```

**Comment by ooiginla** [comment]
> In PHP7, I had to use:
> 
> ```
> try {
>   // Code
> } catch(\GuzzleHttp\Exception\GuzzleException $e) {
>   // Handle excpetion
> }
> ```

this worked for me too.

**Comment by EdgarSedov** [comment]
i guess the topic starter point is he wants to discriminate timeout from another errors, and same goes for me. Is there any reliable way to do that?

**Comment by JeremyWorkWork** [comment]
> i guess the topic starter point is what he wants to discriminate timeout from another errors, and same goes for me. Is there any reliable way to do that?

If Guzzle is using cURL as the HTTP handler, for a timeout exception you can capture the ConnectException and inspect the exception object like this:

$exception->handlerContext->errno <-- for example 28 for cURL error 28 (Operation timeout. The specified time-out period was reached according to the conditions.)

Keep in mind this: 

https://github.com/guzzle/guzzle/blob/7.7/src/Exception/ConnectException.php

```
/**
 * Get contextual information about the error from the underlying handler.
 *
 * The contents of this array will vary depending on which handler you are
 * using. It may also be just an empty array. Relying on this data will
 * couple you to a specific handler, but can give more debug information
 * when needed.
 */
public function getHandlerContext(): array
{
    return $this->handlerContext;
}
```
