### ISSUE TITLE
I get connection refused, help me please

### ISSUE THREAD

**Issue by SebastianCBA** [guzzle/guzzle#2361]
Hi! I have this url:
http://omnimax.tv:25461/player_api.php?username=stv090519&password=getstunned

if I test on https://onlinecurl.com/ I get as expected.

But on my server, with laravel, I do this:
```
    $client = new \GuzzleHttp\Client();
    $request = $client->get('http://omnimax.tv:25461/player_api.php?username=stv090519&password=getstunned', array());
    $response = $request->getBody();
    dd($response);        

```
I get this error:

cURL error 7: Failed to connect to omnimax.tv port 25461: Connection refused (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)
Can you help me please?

**Comment by SamuelNitsche** [comment]
I just tried the exact code you posted and everything works like expected. Do you still get the error?

**Comment by Nyholm** [comment]
We cannot provide help in the issue tracker. 

Our time is not enough :/

Try with the great people at Stackoverflow.
