### ISSUE TITLE
cURL error 56: OpenSSL

### ISSUE THREAD

**Issue by celleyes** [guzzle/guzzle#2363]
I have been trying to resolve this issue for the psat 3 days.
Something isn't right. i have created a script in my laravel project which connects to an external API and downloads bunch of zip files everyday.

After downloading 3 or 4 zip files it throws it throws an error saying:

cURL error 56: OpenSSL SSL_read: SSL_ERROR_SYSCALL, errno 10054 (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)

Not sure whats going on .. openSSL is active in php.ini 

$client = new \GuzzleHttp\Client();

            $res = $client->request('GET', $url, [
                'auth' => ['username', 'password'],

                'headers' => [
                    'Accept'     => 'application/json',
                    'Content-Type'     => 'application/json'
                ],
            ]);

           $responses = json_decode($res->getBody()->getContents());

           foreach ($responses->incrementalFeed as $feed)
           {
                if(Carbon::parse($feed->lastModDt)->format('Y-m-d') == Carbon::today()->format('Y-m-d'))
                {
                    $downloadLink = $url . $feed->name;
                    $response = $client->get($downloadLink, ['auth' => ['username', 'password']]);
                    Storage::put('downloads/'.$feed->name, $response->getBody());  
		}
	   }

**Comment by Nyholm** [comment]
Im sorry that I cannot provide support in the issue tracker. 
I have to close this because it is not an issue with the library. 

If you have your solution, feel free to post it here and you may help someone in a similar situation. If you still have this issue I would recommend you do ask on Stackoverflow or a similar forum.
