### ISSUE TITLE
Bug in php parse_url cases InvalidArgumentException

### ISSUE THREAD

**Issue by idetailaid-team** [guzzle/guzzle#2364]
**Guzzle version(s) affected**: 4.2-dev

**Description**  
This is for an older version of Guzzle that we have to use, and I know the issue is a bug in PHP,  but I was wondering if there is a known workaround ?

File guzzle/src/Url.php:36

````php
if (false === ($parts = parse_url($url))) {
throw new InvalidArgumentException('Was unable to parse malformed url: ' . $url);
}
````

Turns out there is a bug in `parse_url` that incorrectly thinks part of the URI is the port, tries to validate it as a port and fails under the following circumstances:

there is a colon in the URI   :
there is a sequence of numbers after the colon that are 1 - 5 characters in length
that number is in the range of 65535 - 99999

If that is the case, php thinks it's a port number, and it's beyond the 65534 limit, and so it fails!!!  

**How to reproduce**  

:65536 - 5 digits long, and above 65535 will fail

````php
$result = parse_url('objects/binders/18817/documents/1568025717845:65536');
var_dump( $result );
````
````
bool(false)
````

:65535 - 5 digits long, and 65535 or below will work

````php
$result = parse_url('objects/binders/18817/documents/1568025717845:65535');
var_dump( $result );
````
````
array(3) {
  ["host"]=>
  string(7) "objects"
  ["port"]=>
  int(65535)
  ["path"]=>
  string(44) "/binders/18817/documents/1568025717845:65535"
}
````

:100000 - above 5 digits long will work

````php
$result = parse_url('objects/binders/18817/documents/1568025717845:100000');
var_dump( $result );
````

````
array(1) {
  ["path"]=>
  string(52) "objects/binders/18817/documents/1568025717845:100000"
}

````

**Possible Solution**  

**Additional context**  
Having  a colon in the URI is valid, it doesn't mean there is a port in there, so this is a bug with PHP.   Is there a known workaround for this ?

**Comment by idetailaid-team** [comment]
There is a simple workaround for anyone else coming to this.

`parse_url` works when there is a scheme present, so passing a full URL with the above numbers will work.

For Guzzle, this means passing the FULL url to `createRequest` :

```php
$this->httpClient->createRequest('GET', 'https://www.domain.com/objects/binders/18817/documents/1568025717845:65536');
```

**Comment by Nyholm** [comment]
Thank you for a detailed error report and the solution. 

I will close this issue because 4.2 is not maintained anymore.
