### ISSUE TITLE
Guzzle3 send raw Post request

### ISSUE THREAD

**Issue by cap-hkacemi** [guzzle/guzzle#2367]
**Guzzle version(s) affected**: 3.9.3

**Description**  
I am working on project that uses Guzzle3 (v3.9.3), I would like to know how to send a raw post request, I have tried the solutionfound in the documentation but it is not working https://guzzle3.readthedocs.io/http-client/request.html?highlight=raw#raw-post-data

erreur : Client error response [status code] 404 [reason phrase] Not Found
**How to reproduce**  
$client = new Client();
$client->setDefaultOption('headers', array(
'Authorization' =>  'Bearer '.$token,
'Accept' => 'application/json'
));

$body = '{"filter_":{"user":{"email":"aaa@test.com"}}}';
$req = $client->post($url, array(), $body,
array(
 'cert' => array($certification, 'password'),
)
);
$response = json_decode($client->send($req)->getBody(true)); 

**Possible Solution**  

**Additional context**

**Comment by kingofnull** [comment]
404 response code usually related to your url not the library. check your endpoint url with an API tester like postman and make sure your API service works properly.

**Comment by cap-hkacemi** [comment]
Hello, 
I can't upgrade to a newer version, because the version3 is used in many places in the project.
Anyway, I'm posting the solution in case someone need it, I had to put all the bloc between try catch (in case WS returns empty array, if no results found, I get the error mentionned above, now with try catch I am no longer getting it)

try{
$client = new Client();
$client->setDefaultOption('headers', array(
'Authorization' => 'Bearer '.$token,
));
$body = '{"filter_":{"user":{"email":"aaa@test.com"}}}';
$req = $client->post($url, array(), $body,
array(
'cert' => array($certification, 'password'),
)
);
$response = json_decode($client->send($req)->getBody(true));
catch(Guzzle\Http\Exception\BadResponseException $e){
$response = json_decode($e->getResponse()->getBody(),true);
}

**Comment by sagikazarmark** [comment]
Guzzle 3 and 6 (the latest) can coexist as they are separate packages.
