### ISSUE TITLE
Why it returns fatal error if server responses error?

### ISSUE THREAD

**Issue by nimasdj** [guzzle/guzzle#2369]
If Bitly response has error messages, why it returns fatal error, instead of error message?
It should not throw exception, but just status and reason data,
```
PHP Fatal error:  Uncaught Guzzle\Http\Exception\ClientErrorResponseException: Client error response
[status code] 403
[reason phrase] INVALID_ACCESS_TOKEN
[url] https://api-ssl.bitly.com/v3/user/link_save?access_token=xxxxx&longUrl=http%3A%2F%2Fwww.example.com&title=test in /vendor/guzzlehttp/guzzle/src/Guzzle/Http/Exception/BadResponseException.php:43
Stack trace:
#0 /vendor/guzzlehttp/guzzle/src/Guzzle/Http/Message/Request.php(145): Guzzle\Http\Exception\BadResponseException::factory(Object(Guzzle\Http\Message\Request), Object(Guzzle\Http\Message\Response))
#1 /vendor/symfony/event-dispatcher/EventDispatcher.php(260): Guzzle\Http\Message\Request::onRequestError(Object(Guzzle\Common\Event), 'request.error', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#2 /vendor/symfo in /vendor/guzzlehttp/guzzle/src/Guzzle/Http/Exception/BadResponseException.php on line 43
```

Isn't it because of some dependency version mistakes in your json?
Hpatoio version: 2.0.5
Guzzle version: 3.8.1
PHP version: 7.2

**Comment by alexeyshockov** [comment]
It's the default behaviour of the library, but you can change it. Take a look at [`http_errors` option](http://docs.guzzlephp.org/en/stable/request-options.html#http-errors).

**Comment by nimasdj** [comment]
Thanks for the hint. Sorry for my ignorance as I was not using Guzzle directly. Hpatoio is using it. I guess this option is hardcoded in their code and no api provided so if I customize it I will loose it if the pack is updated so I am going to open a ticket with them to request an api to turn this setting off. Thanks again for the hint.

**Comment by sagikazarmark** [comment]
@nimasdj please note that Guzzle 3 is not supported anymore. I strongly urge you to upgrade, if possible.

**Comment by Nyholm** [comment]
Closing this because it is not an issue with Guzzle. Please read the documentation or ask on a forum like Stackoverflow.
