### ISSUE TITLE
Statuscode 400 -> RequestException config for exclude

### ISSUE THREAD

**Issue by saschaarthur** [guzzle/guzzle#2370]
Hello,

Guzzle is throwing when http_errors => true (which is default) an RequestException in case of statuscode 400.

Statuscode 400 or sometimes 422 is used on a lot of rest APIs as an "invalid data" response. e.g. the user puts an wrong email.

I saw plenty of workarounds for this like
 ```

try {
            $result = $this->provider->request($method, $uri, $options);
} 
catch (RequestException $e) {
            if ($e->hasResponse()) {
                switch ($e->getResponse()->getStatusCode()) {
                    case "400": //validation error by api -> its fine return to user
                        return new Response(
                            $e->getResponse()
                        );
                }
            }
}

```

This is like the best practice as an workaround atm.
It would be awesome to have an config variable for example http_errors_exclude which would exclude statuscode 400 and dont throw this Exception.

Thanks

**Comment by alexeyshockov** [comment]
You can try to customise [`http_errors` middleware](https://github.com/guzzle/guzzle/blob/master/src/Middleware.php#L53) and implement your desired behaviour.

I'm not sure if it needs to be included in Guzzle itself, but you can experiment with it and propose a PR.

**Comment by Nyholm** [comment]
I agree with @alekseykuleshov. 

Or you can do `http_errors => false`

**Comment by saschaarthur** [comment]
http errors false would remove the exception for all errors..

**Comment by sagikazarmark** [comment]
@saschaarthur unfortunately we cannot accept everything in the core library, it would become insanely large and unmaintainable.

A custom middleware indeed sounds like the proper solution in this case instead of the default one.
