### ISSUE TITLE
cURL error 28: Operation timed out after 10070 milliseconds with 0 bytes received

### ISSUE THREAD

**Issue by 310K** [guzzle/guzzle#2372]
guzzlehttp/guzzle: 6.3.3

Hi !

my vuejs app send multiple ajax query to a Laravel application. This laravel application makes API calls to other Laravel application (on the same machines). Everything work fines if ajax queries are sent in sequence. But when two ajax queries are sent in parallele (meaning that two instance of the same Laravel application will make the same API call through Guzzle), I've got:

`cURL error 28: Operation timed out after 10070 milliseconds with 0 bytes received ...`

It is of course not a timeout problem because I also tried to increase it to 2 minutes with the same effect... It is the `with 0 bytes received` that I find strange.

I'm using MAMP Pro on MacOS 10.14 - PHP 7.3.8 - nginx (last version).

I tried to increase php configuration like memory, max_execution_time, ... does not work.

Do I miss something ?

**Comment by Nyholm** [comment]
Hey.

Im sorry that I cannot provide support. There is no issue with Guzzle. You should look for a help-forum like Stackoverflow to get your question answered.
