### ISSUE TITLE
curl 28 

### ISSUE THREAD

**Issue by ohmygd** [guzzle/guzzle#2377]
**Guzzle version(s) affected**: ^6.3

**Description**  
i write an api with go, the api no problem, you get my order
i'm in test, use laravel+guzzle to get the go's api info, everything is right , but suddenly guzzle gives me an error:
cURL error 28: Connection timed out after 4514 milliseconds (see http://curl.haxx.se/libcurl/c/libcurl-errors.html), url:http://dev.market.soholly.com/within/gb/skuInfo, params:{"sku":"YNJ-S"}

just a few seconds earlier, it  runs ok, i didn't change anything

then i search some information, i use the demo to test
$client = new \GuzzleHttp\Client();
$request = $client->get('https://www.baidu.com');
$response = $request->getBody();

it still time out, what's wrong? please

**Comment by Nyholm** [comment]
Timeouts depends on your server or network. It is not an issue with Guzzle. 

Please refer to Stackoverflow or similar forum for help.
