### ISSUE TITLE
Make 5.3 EOL

### ISSUE THREAD

**Issue by Nyholm** [guzzle/guzzle#2386]
I vote for making branch 5.3 EOL after release of 5.3.4 ([diff](https://github.com/guzzle/guzzle/compare/5.3.3...5.3)). 

We cannot focus on 3 major versions at the same time. So lets drop version 5 and focus on version 7.

**Comment by GrahamCampbell** [comment]
:+1:

**Comment by sagikazarmark** [comment]
Yeah, sounds good to me.

**Comment by Nyholm** [comment]
This is fixed!
