### ISSUE TITLE
Support setAuth() without a password

### ISSUE THREAD

**Issue by amacneil** [guzzle/guzzle#239]
Currently the first thing `Request->setAuth()` does is check a username and password was supplied (which seems a little silly given that password has a default parameter of empty string).

```
public function setAuth($user, $password = '', $scheme = CURLAUTH_BASIC)
{
    // If we got false or null, disable authentication
    if (!$user || !$password) {
        $this->password = $this->username = null;
        $this->removeHeader('Authorization');
        $this->getCurlOptions()->remove(CURLOPT_HTTPAUTH);
    }
    // etc
```

However, some API's (like [Stripe](https://stripe.com/docs/api#authentication)) only require a username, and use a blank string for the password.

Is it possible to remove this check, or at least compare `$password` to null but allow using setAuth() with an empty string as the password? Is there a reason for the current behavior?

Obviously for now I can resort to simply base64 encoding my own Authorization header, but if I wanted to write low level code I wouldn't be using this flash library now would I :)

**Comment by smonson78** [comment]
This problem still affects people who try to use a password without a username, eg Mailchimp 3.0 API. Of course you can use "any string" for the username in Mailchimp but many people will assume an empty string is fine, leading to a lot of confusion when it silently fails.  Maybe you could check if BOTH are null before disabling authentication? Or throw an exception.

**Comment by mtdowling** [comment]
Can you send a PR please? Thanks!

**Comment by smonson78** [comment]
Sure can, but not for a while because I'm on my employer's time for now and stuck with v3.9.1. But I gather it'd be similar to Adrian's original change, but changing that one line from "if (!$user) {" to "if (!$user && !$password) {".

**Comment by adrianmacneil** [comment]
If you're stuck on v3, just set the header manually:

    $request->setHeader('Authorization', 'Basic ' . base64_encode($username . ':' . $password));
