### ISSUE TITLE
Cookie functionality as separate package?

### ISSUE THREAD

**Issue by bmack** [guzzle/guzzle#2396]
Hello Guzzle maintainers,

first of all - I love Guzzle and its great usability and interoperability. We've been using Guzzle under-the-hood in TYPO3 CMS since 4 years.

**Description** 
I've been looking into ways on how to work with Guzzle Cookie and use this in our process properly, and I like that it has almost no dependencies (other than PSR). I wonder if you're interested in separating the Cookie* classes into separate packages so we can depend on them more freely without having to worry about version concerns when it comes to the main Guzzle package.

That's why I wonder if you were interested in any kind of migrating the cookie functionality into a separate package like "guzzlehttp/cookie" as you've done with PSR-7 implementation. Hopefully, in the future, this could lead to a separate standalone library that people that do not use Guzzle (yet) to use Cookies in a generic way (or maybe it could become the boilerplate for a new PSR-X?)

Thanks in advance for your feedback, I'm fine with an answer if you'll be interested in doing so, or if you don't see any benefits for doing so.

Benni.

**Comment by sagikazarmark** [comment]
Hi @bmack 

I don't think we ever had such request before. I could imagine a separate library for cookies, but it would always have to be following Guzzle needs.

I'm pretty sure there are already tons of other libraries for cookie handling out there, quality is another question though.

I'm not against creating a separate package, but I'm not sure we have the resources right now for that.

**Comment by bmack** [comment]
Hi @sagikazarmark 

thanks for your answer. Totally legit, and I see your point on the resources. Looks like we also need some more parts on top, but if something evolves around that, which might make sense to split off the package where I can help in terms of work load, I'll let you know.

I'll close this issue in the meantime
