### ISSUE TITLE
Exception Argument 3 passed to GuzzleHttp\MessageFormatter::format() must be an instance of Exception or null, string given

### ISSUE THREAD

**Issue by ankahla** [guzzle/guzzle#2397]
**Guzzle version(s) affected**: 6.2.1

**Description**  
When Mock is enabled and mode = replay sometimes we got this exception
```
Argument 3 passed to GuzzleHttp\MessageFormatter::format() must be an instance of Exception or null, string given, called in /var/www/zola-orders/vendor/guzzlehttp/guzzle/src/Middleware.php on line 200
```
This is because the recorded mock is missing but we should not crash the application with 500 error.

**How to reproduce**  
use the Mock middleware with mode = replay without recording any mock

**Possible Solution**  
Pass to the method `format()` the correct exception or null

**Additional context**

**Comment by gmponos** [comment]
I think this is related https://github.com/guzzle/guzzle/pull/2311

We will release a v7 which will fix that... thank you

**Comment by Nyholm** [comment]
@ankahla can you try master to confirm that it is fixed?

**Comment by Nyholm** [comment]
Friendly ping to @ankahla

**Comment by gmponos** [comment]
The message [here](https://github.com/guzzle/guzzle/pull/2524/files#diff-ff73e042e738204c6da009e2ed19f783R474) says about `POST` although `form_params` can be used with `GET` also.

**Comment by Nyholm** [comment]
Closing due inactivity.
