### ISSUE TITLE
Fatal Error on 404 Not Found response in RequestException.php

### ISSUE THREAD

**Issue by rolinger** [guzzle/guzzle#2407]
**Guzzle version(s) affected**: 6.3.3

**PHP Version** : 7.3.11

**Description**  
Fatal Error on RequestException.php on line 113 "resulted in a `404 Not Found` response:
{"error":"No information found about this instance id."} "

**How to reproduce**  
Connecting to Google FCM to lookup up a tokenID...if not found, the 404 response causes Fatal Error.  If the tokenID exists, all is good.

**Possible Solution**  

**Additional context**  
This error was also reported in another Issue but it doesn't look like there was any real resolution.  https://github.com/guzzle/guzzle/issues/1947 

The actual error:

```
Fatal error: Uncaught GuzzleHttp\Exception\ClientException: Client error: `POST https://iid.googleapis.com/iid/info/dk4jUDTwi6E:APA91bFj6R4P6E0RiE5Wc9D267gquYcpKtLjczg-Ok5llCAf_BNbbFp_HyH-r4A5CrxfkCCfIqLx1j4Fc2U9XyFnyrtXBE0WK744wH8dbCz7Wr-kXJxh3ErsQ71ZoEmxbGmCXtJ-yMiS?details=true` resulted in a `404 Not Found` response:
{"error":"No information found about this instance id."}
 in /home/dev/public_html/api/assets/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:113
Stack trace:
#0 /home/dev/public_html/api/assets/vendor/guzzlehttp/guzzle/src/Middleware.php(66): GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Psr7\Request), Object(GuzzleHttp\Psr7\Response))
#1 /home/dev/public_html/api/assets/vendor/guzzlehttp/promises/src/Promise.php(203): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Response))
#2 /home/dev/public_html/api/assets/vendor/guzzlehttp/promises/src/Promise.php(156): GuzzleHttp\Promise\Promise::callHandler(1, Object(GuzzleH in /home/dev/public_html/api/assets/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php on line 113
```

**Comment by rolinger** [comment]
Not certain why, but Google chooses to return a HTML 404 Not Found page error when a FCM tokenID does not exist.  It returns an error object `{"error":"No information found about this instance id."}`

But that 404 error causes the Fatal Error to be thrown.  Is there any other way guzzle can handle these without having to throw a Fatal Error?  Not all 404 errors, esp in a recursive loop, need to cause the script to exit on a fatal error.

My temporary fix for this is was to modify the below code, In line 66 of `vendor/guzzlehttp/guzzle/src/Middlewar.php` I changed the function from:

```
                    function (ResponseInterface $response) use ($request, $handler) {
                        $code = $response->getStatusCode();
                        if ($code < 400) {
                            return $response;
                        } 
                        throw RequestException::create($request, $response);
                        }
                    }
```

To this:

```
                    function (ResponseInterface $response) use ($request, $handler) {
                        $code = $response->getStatusCode();
                        if ($code < 400) {
                            return $response;
                        } else if ($code == 404){
                            return $response ;
                        } else {
                          throw RequestException::create($request, $response);
                        }
                    }
```

This by no means is a permanent fix, but it temporarily allows my scripts to keep working.    I think guzzlehttp needs to find a permanent fix or offer a switch of some sort regarding `do` or `do not` throw fatal error on 404 (or maybe other response codes too) - not all 404 Responses need to be turned into `throw` Fatal Errors.

This temporary fix works for very specific Google FCM issues, but could cause issues if this guzzlehttp is used for other scripts outside of the php-fcm package.

**Comment by gmponos** [comment]
>This error was also reported in another Issue but it doesn't look like there was any real resolution. #1947

I am not sure how the two issues (current one and 1947) are related. Never the less I guess you are looking for http://docs.guzzlephp.org/en/stable/request-options.html#http-errors

**Comment by rolinger** [comment]
@gmponos - yes!  I didn't know this option existed.  Glad it exists.  I can remove my custom code update and just use this option.  Thank you.

**Comment by innvouday** [comment]
Guzzle 6.x
Per the docs, the exception types you may need to catch are:

Refer Link: [https://guzzle3.readthedocs.io/http-client/request.html#http-errors](url)

GuzzleHttp\Exception\ClientException for 400-level errors
GuzzleHttp\Exception\ServerException for 500-level errors
GuzzleHttp\Exception\BadResponseException for both (it's their superclass)
Code to handle such errors thus now looks something like this:

$client = new GuzzleHttp\Client;
try {
    $client->get('http://abc.com/xyzpage');    
}
catch (GuzzleHttp\Exception\ClientException $e) {
    $response = $e->getResponse();
    $responseBodyAsString = $response->getBody()->getContents();
}
