### ISSUE TITLE
Get header size from response

### ISSUE THREAD

**Issue by Artisan-Asad** [guzzle/guzzle#2408]
There should be something in Guzzle to get response information like curl_getinfo()

I am trying to get CURLINFO_HEADER_SIZE form the response but there is no such way found. 
With normal curl request one would use following function to get header size:
`curl_getinfo($curl, CURLINFO_HEADER_SIZE)`

Not sure how could we apply the same method in Guzzle 6

**Comment by alexeyshockov** [comment]
You can get it inside `on_stats` handler, like this:

```php
$httpClient->get($url, ['on_stats' => function (\GuzzleHttp\TransferStats $stats) {
    echo $stats->getHandlerStat('header_size');
}]);
```

Guzzle [takes this info](https://github.com/guzzle/guzzle/blob/6.5.0/src/Handler/CurlFactory.php#L122) internally from `curl_getinfo()`, just not specifying the exact part (to get all the info).

**Comment by gmponos** [comment]
does the solution proposed by @alekseykuleshov works for you?

**Comment by gmponos** [comment]
Closing as there was no feedback here :) 

thank you
