### ISSUE TITLE
TLS for docs.guzzlephp.org

### ISSUE THREAD

**Issue by bradjones1** [guzzle/guzzle#2410]
**Description**  
The `docs.guzzlephp.org` site should be protected with TLS

**Example**  
This should be possible with ReadTheDocs, per their [documentation](https://docs.readthedocs.io/en/stable/custom_domains.html).

**Additional context**
TLS is basically free and it sets a good example. :-)

**Comment by Nyholm** [comment]
@sagikazarmark I think you are the only one that have access to fix this, right?

**Comment by sagikazarmark** [comment]
Done
