### ISSUE TITLE
Add support for P12 cert format via CURLOPT_SSLCERTTYPE

### ISSUE THREAD

**Issue by razvanphp** [guzzle/guzzle#2411]
**Description**  
New version of openssl (versions 0.9.3 and later) suport P12 certificate files, it would be nice to be able to specify the type as the third parameter of `cert` or even detect them by the extension maybe and set the correct CURLOPT_SSLCERTTYPE value. Here is the official documentation: https://curl.haxx.se/libcurl/c/CURLOPT_SSLCERTTYPE.html

**Example**  
it currently works with specifying the `curl` option manually:
```
$response = $client->post($url, [
    RequestOptions::HEADERS => ['apns-topic' => $topic],
    RequestOptions::JSON => json_decode('{}'),
    RequestOptions::VERSION => 2.0,
    RequestOptions::CERT => ['./certificates/cert.p12', '123456'],
    'curl' => [
        CURLOPT_SSLCERTTYPE => 'P12'
    ]
]);
```

I can prepare a PR if this change is welcome. Thank you!

**Comment by razvanphp** [comment]
PR is open, so this ticket should stay open. I will add one test.

**Comment by Nyholm** [comment]
Please do finish that PR. 

Thank you

**Comment by razvanphp** [comment]
@Nyholm PR was updated, but not reviewed and merged yet.

**Comment by Nyholm** [comment]
Hey. 
I missed that you update the PR. I checked again an hour ago but Github didn't showed me the changes. Same thing now. 

<img width="1355" alt="Screenshot 2021-02-01 at 16 56 07" src="https://user-images.githubusercontent.com/1275206/106483055-66664e80-64ae-11eb-99ab-2cdba30c7ad0.png">

**Comment by mfn** [comment]
PS: works now (for me) https://github.com/guzzle/guzzle/pull/2413/files
![image](https://user-images.githubusercontent.com/87493/106615465-befc2100-656c-11eb-96d7-b5a941b45168.png)
