### ISSUE TITLE
Exceptions thrown by CurlMultiHandler in async requests trigger a php TypeError due wrong parameter fed to following middleware onFulFill closure

### ISSUE THREAD

**Issue by MatteoOreficeIT** [guzzle/guzzle#2414]
**Guzzle version(s) affected**: 6.4.1

**Description**  

The following middlewares :

- `\GuzzleHttp\Middleware::httpErrors`
- `\GuzzleHttp\RedirectMiddleware`

Cannot handle CurlMultiHandler exceptions that come in from handler or previous middleware triggering a php TypeError

```php

// for httpErrors middleware
TypeError: Argument 1 passed to GuzzleHttp\Middleware::GuzzleHttp\{closure}() 
must be an instance of Psr\Http\Message\ResponseInterface,
 instance of GuzzleHttp\Exception\ConnectException given on Middleware.php:71

```

**How to reproduce**  
```php

$client = new GuzzleHttpClient([
     'handler' => \GuzzleHttp\HandlerStack::create()
      // Base URI is used with relative requests
      'base_uri' => 'https://hostname:5001' ,
      // very short timeout
      'timeout' => 0.1
])

$client->requestAsync('POST',[])->otherwise(function($error){
     // original exception is  masquerated by a php TypeError
});

```

**Possible Workaround**  

To workaround the problem I removed all middlewares and in user code my `onFulFill / then` is not contrained to `ResponseInterface` type, so I can original exception in user code es:

```php

$client->requestAsync('POST',[])->then(function($responseOrException){
    if($responseOrException instanceof \RequestException) {
        // handle original exception here
    }
});

```

**Possible Solution**  

Remove ResponseInterface type hint in previous middlewares and handle input type with instanceof switch

**Context**  

We use a GuzzleHttp client in a ReactPHP application with a custom promise ticker available at [https://gist.github.com/MatteoOreficeIT/cf38a8a4c04bc71bf1557ee10fbea737](https://gist.github.com/MatteoOreficeIT/cf38a8a4c04bc71bf1557ee10fbea737)

**Comment by gmponos** [comment]
Would like to help here.. but what I have as reproducer is this:

<?php

use GuzzleHttp\Client;

require_once 'vendor/autoload.php';
```
$client = new Client([
    'handler' => \GuzzleHttp\HandlerStack::create(),
    'timeout' => 0.1
]);

/** @var \Psr\Http\Message\ResponseInterface $response */
$response = $client->requestAsync('get', 'https://www.google.com')->wait();

var_dump($response->getStatusCode());
```

Which works fine.. would you mind giving me one that reproduces the issue..

If the problem is with the gist you have attached then I would appreciate a simpler example..

**Comment by MatteoOreficeIT** [comment]
I discovered The problem was not imputable to guzzle , I ran this code in a reactphp loop, see this class  https://gist.github.com/MatteoOreficeIT/cf38a8a4c04bc71bf1557ee10fbea737

At first guzzle request I start a promise ticker timer , and I stop this timer after last request ended, chaining on the resulting promise

The problem was I returned the chained promise and not the original
