### ISSUE TITLE
(Feature request or bug report) Message: Unexpected character encountered while parsing value: E. Path '', line 0, position 0.

### ISSUE THREAD

**Issue by 01viniciusmelo** [guzzle/guzzle#2418]
I have the following question because I don't know if it really is a bug in Guzzle. When consuming the service of my API I am having the following error: Unexpected character encountered while parsing value: E. Path '', line 0, position 0.

This "E." is the initial of the word company (my language is Brazilian Portuguese), but I don't know what this message is trying to tell me. I'm confused. I am using Guzzle in other 3 service of my API and it is working perfectly, but in this 4th service I am having this error. Using Postman I have no problem with this service and I am using Laravel 5.5 and Guzzle 6

Message in the Laravel:
![photo_2019-12-05_22-39-18](https://user-images.githubusercontent.com/7417002/70288336-23c4bb80-17b0-11ea-8d82-504bcb48f59f.jpg)

My class PHP in the VSCode:
![photo_2019-12-05_22-39-22](https://user-images.githubusercontent.com/7417002/70288337-245d5200-17b0-11ea-93c9-be9c5609880e.jpg)

Running in Postman:
![photo_2019-12-05_22-39-28](https://user-images.githubusercontent.com/7417002/70288339-245d5200-17b0-11ea-83d2-0c3d6214a17d.jpg)

**Comment by wmmaw** [comment]
Hi, what version of Guzzle do you use?
Any progress on this?

**Comment by alexeyshockov** [comment]
It looks like your API expects JSON, but you send `form_params` instead and get the [parsing error from a .NET app](https://stackoverflow.com/questions/23259173/unexpected-character-encountered-while-parsing-value) back. It's not a Guzzle error.

Try to use `json` instead of `form_params`.
