### ISSUE TITLE
IDNs are not properly converted to ASCII on automatic redirects

### ISSUE THREAD

**Issue by acelaya** [guzzle/guzzle#2423]
**Guzzle version(s) affected**: 6.5

**Description**  

I have been waiting for this PR to be merged, https://github.com/guzzle/guzzle/pull/2286, which brings IDN support to guzzle.

The thing is that I have just tested v6.5, which includes it, and I have realized that the `idn_to_ascii` function is only applied to the first domain provided by the user, but if for some reason some other IDN is returned in the `Location` header and guzzle is configured to automatically follow redirects, it does not apply it to those, causing some domains to not properly resolve.

**How to reproduce**  

I have some internationalized domain names that can be used to test, which I also use for my e2e tests.

These are all the use cases I cover:

* IDN redirecting to regular domain: http://tést.shlink.io -> https://shlink.io
* Regular domain redirecting to IDN: http://test.shlink.io -> http://tést.shlink.io
* IDN redirecting to IDN: http://téstb.shlink.io -> http://tést.shlink.io

For now, I just disable automatically following redirects and use a recursive function.

**Comment by gmponos** [comment]
Will this solve the problem? #2424

**Comment by acelaya** [comment]
Yeah, I guess it should :)

I can try if my tests pass using your fork.

**Comment by acelaya** [comment]
Hey @gmponos.

I have tried installing your version on my project, by adding your fork as a VCS composer repository, but then, when I use the `dev-issue#2423` version constraint, it thinks I want to install commit with ID `2423` from branch `issue`, and fails.

I have tried escaping/encoding the `#` char in different ways, but it always fails to resolve to the proper branch.

Could you rename the branch so that it does not include special chars?

**Comment by GrahamCampbell** [comment]
You could just edit the vendor folder with the changes from the PR. Would be faster...

**Comment by acelaya** [comment]
You are completely right. I overengineered the whole process 😅

**Comment by acelaya** [comment]
@gmponos I just tested your changes by copy-pasting the code as @GrahamCampbell suggested, and I can confirm it works :smile:

**Comment by gmponos** [comment]
Btw I think I fixed that on the related PR #2424 

I also pushed a branch `issue2423` without `#` in case you want to retest it :)

**Comment by acelaya** [comment]
Hey @gmponos 

I tested again with your branch, and it continues working. Thanks!

**Comment by Nyholm** [comment]
This is fixed by https://github.com/guzzle/guzzle/pull/2424

Will be released in 6.5.1
