### ISSUE TITLE
Can only getBody() once

### ISSUE THREAD

**Issue by happyclicker** [guzzle/guzzle#2452]
**Guzzle version(s) affected**: 6.5.0

**Description**  
It appears that using getBody(), getReasonPhrase(), et al clears after you call it once in 6.5.0?  If I call it twice, the second call is null.

**Comment by GrahamCampbell** [comment]
What did it do in 6.3.x, by comparison?

**Comment by GrahamCampbell** [comment]
That is, could you clarify if you are reporting a BC break in the 6.x series?

**Comment by happyclicker** [comment]
If I called it more than once in the previous version, it didn't return a null, I got the data back each time.

**Comment by GrahamCampbell** [comment]
Hmm, so `getBody()` doesn't exist in this package itself. Could you clarify the version of https://github.com/guzzle/psr7 is where things change?

**Comment by GrahamCampbell** [comment]
So, in Guzzle 6.4.1 with the psr package 1.5.2, do things work? Does changing to 1.6.1 break things, or keep the same. Similarly, what about Guzzle 6.5.0.

**Comment by happyclicker** [comment]
This is using Guzzle.  If I do this, I can see the data in the JSON returned:

       $client = new Client([
            'base_uri' => $this->base_url
        ]);

        try {
            $res = $client->get('ws', [
                'query' => ['xmldata' => $body],
                ]);

            $this->response_code = $res->getStatusCode();
            $this->response_message = $res->getReasonPhrase();
            $this->response_data = $res->getBody()->getContents();
            $this->response_body = $res->getBody();

            return(response()->json([
                'code' => $this->response_code,
                'message' => $this->response_message,
                'data' => $this->response_data,
                'body' => $this->response_body
            ]));
        } catch (GuzzleException $e) {
            // Handle the errors
            return(response()->json([
                'error' => $e->getMessage()
            ], 500));
        }

If I do this, I get null's in the JSON, but the $this-> variables have the data:

$client = new Client([
            'base_uri' => $this->base_url
        ]);

        try {
            $res = $client->get('ws', [
                'query' => ['xmldata' => $body],
                ]);

            $this->response_code = $res->getStatusCode();
            $this->response_message = $res->getReasonPhrase();
            $this->response_data = $res->getBody()->getContents();
            $this->response_body = $res->getBody();

            return(response()->json([
                'code' => $res->getStatusCode(),
                'message' => $res->getReasonPhrase(),
                'data' => $res->getBody()->getContents(),
                'body' => $res->getBody()
            ]));
        } catch (GuzzleException $e) {
            // Handle the errors
            return(response()->json([
                'error' => $e->getMessage()
            ], 500));
        }

**Comment by sagikazarmark** [comment]
You are trying to read the body more than once. In PSR-7 the body is a stream object which needs to be rewinded every time you want to read it.

Furthermore, it's worth mentioning that `getContents` will return the **remaining content** in the stream, not the whole content, so you probably want to avoid using it.

I'm not sure what *previous version* means for you, chances are Guzzle 3 and 4 worked differently.

Please clarify if you experience this sort of "break" in behavior between major or minor versions. If you upgraded from Guzzle 3 or 4 then you should read the PSR-7 standard for details about reading from message bodies.

**Comment by pilgrimage65** [comment]
> You are trying to read the body more than once. In PSR-7 the body is a stream object which needs to be rewinded every time you want to read it.
> 
> Furthermore, it's worth mentioning that `getContents` will return the **remaining content** in the stream, not the whole content, so you probably want to avoid using it.
> 
> I'm not sure what _previous version_ means for you, chances are Guzzle 3 and 4 worked differently.
> 
> Please clarify if you experience this sort of "break" in behavior between major or minor versions. If you upgraded from Guzzle 3 or 4 then you should read the PSR-7 standard for details about reading from message bodies.





https://extrapolation8.github.io/aP3aBAeTjmsbyqL0_N3y/
