### ISSUE TITLE
Cannot get latest commits

### ISSUE THREAD

**Issue by johncarlson21** [guzzle/guzzle#2455]
**Guzzle version(s) affected**:6.5.0

**Description**  
Upgraded package yesterday to 6.5.0 but in the change log it has a date of 11/27/2019, today I try to update the package again and there is nothing to update, even though there are multiple changes.
below is my composer.json

{
    "name": "guzzlehttp/guzzle",
    "type": "library",
    "description": "Guzzle is a PHP HTTP client library",
    "keywords": [
        "framework",
        "http",
        "rest",
        "web service",
        "curl",
        "client",
        "HTTP client"
    ],
    "homepage": "http://guzzlephp.org/",
    "license": "MIT",
    "authors": [
        {
            "name": "Michael Dowling",
            "email": "mtdowling@gmail.com",
            "homepage": "https://github.com/mtdowling"
        }
    ],
    "require": {
        "php": ">=5.5",
        "ext-json": "*",
        "guzzlehttp/promises": "^1.0",
        "guzzlehttp/psr7": "^1.6.1"
    },
    "require-dev": {
        "ext-curl": "*",
        "phpunit/phpunit": "^4.8.35 || ^5.7 || ^6.4 || ^7.0",
        "psr/log": "^1.1"
    },
    "suggest": {
        "psr/log": "Required for using the Log middleware",
        "ext-intl": "Required for Internationalized Domain Name (IDN) support"
    },
    "config": {
        "sort-packages": true
    },
    "extra": {
        "branch-alias": {
            "dev-master": "6.5-dev"
        }
    },
    "autoload": {
        "psr-4": {
            "GuzzleHttp\\": "src/"
        },
        "files": [
            "src/functions_include.php"
        ]
    },
    "autoload-dev": {
        "psr-4": {
            "GuzzleHttp\\Tests\\": "tests/"
        }
    }
}

**Comment by Nyholm** [comment]
If you have an issue with composer try running `composer why` or similar to help you figure out what happens. 

As far as I can tell there are no issue with Guzzle.
