### ISSUE TITLE
Guzzle 6.5 w/ Laravel 6.x - reCAPTCHA V2

### ISSUE THREAD

**Issue by NauDev306** [guzzle/guzzle#2456]
Hi everyone,

**My Setup:**

1. guzzle\guzzle 6.5.0
2. laravel\framework 6.7.0
3. Google recaptcha v2
4. PHPUnit 8.5.0

**My Problem:**
Everything basically works, I even get a response from Google, **BUT** with the following _error-codes_:

- missing_input_secret
- missing_input_response

even though I can echo the variables out in PHPUnit, right before setting the request parameters.

**Steps to reproduce:**
`
use Tests\TestCase;
use GuzzleHttp\Client;
use GuzzleHttp\Psr7\Request;
use App\Providers\GoogleServiceProvider;

class GuzzleTest extends TestCase
{
/**
     * Test Guzzle POST to Google
     */
    public function testGuzzlePostToGoogleRecaptcha()
    {
        $secret = GoogleServiceProvider::SECRET;
        $url = GoogleServiceProvider::URL;
        $res = '123';
        $client = new Client();
        $request = new Request('POST', $url, [
            'form_params' => [
                'secret' => $secret,
                'response' => $res
            ],
        ]);
        $response = $client->send($request);
        $body = $response->getBody();
        $contents = $body->getContents();
        $arrayContents = json_decode($contents, true);
        //print_r($body);
        print_r($contents);
        print_r($arrayContents);
        $this->assertEquals(200, $response->getStatusCode());
        $this->assertEmpty($arrayContents['success']);
        $this->assertFalse($arrayContents['success']);
        $this->assertIsArray($arrayContents['error-codes']);
    }  
}
`

Now, even if I try it as a regular json it doesn't work, and the params are empty.

Your help would be much appreciated.

regards

**Comment by Nyholm** [comment]
This does not seam like a problem with Guzzle. If you check with the documentation with the server. 

Feel free to ask for help on Stackoverflow or similar forums.
