### ISSUE TITLE
idn_to_ascii() argument error

### ISSUE THREAD

**Issue by jonnott** [guzzle/guzzle#2459]
**Guzzle version(s) affected**: 6.5.0

**Description**  
Since composer update to 6.5.0 (from 6.4.x) now getting this error:

```Warning: idn_to_ascii() expects parameter 3 to be long, string given in /home/*****/public_html/vendor/guzzlehttp/guzzle/src/Client.php on line 221```

3rd argument is INTL_IDNA_VARIANT_UTS46 constant, it would seem.

**How to reproduce**  
Very simple requests .. GET/POST/PUT passing JSON to Salesforce REST API endpoints.

**Additional context**  
PHP 5.6 in production

**Comment by jonnott** [comment]
Could it be related to this ? ..

https://forge.typo3.org/issues/87953

"Our Server run with CPanel on CentOS 6, and only an old version of Intl is installed, and the constant INTL_IDNA_VARIANT_UTS46 not exist."

The production server I'm on is running CPanel on CentOS 6 :(

Any work-around?

**Comment by jonnott** [comment]
I've looked at phpinfo() on the server under 'intl' (internationalisation support) and ICU version is 4.2.1

PHP docs for idn_to_ascii() for argument 3 are:

variant
Either INTL_IDNA_VARIANT_2003 (deprecated as of PHP 7.2.0) for IDNA 2003 or INTL_IDNA_VARIANT_UTS46 (only available as of ICU 4.6) for UTS #46.

What do I do?

**Comment by jonnott** [comment]
Guess I need to update the ICU RPM on my server.

In the meantime, how do I use the new `idn_conversion` (false) Request Option to disable this for my requests?

**Comment by jonnott** [comment]
I tried replacing

```
			$client = new GuzzleHttp\Client();
```

with

```
			$client = new GuzzleHttp\Client([
				'defaults' => [
					'idn_conversion' => false
				]
			]);
```

..but that doesn't seem to have worked :(

**Comment by jonnott** [comment]
Oops, realised with the above I was using the Guzzle 5.x method for setting defaults, so I fixed by just using `'idn_conversion' => false` not inside a `'defaults'` array.

Anyway, the bigger problem here seems to be that when the server's ICU version is < 4.6, Guzzle must detect this and not assume `INTL_IDNA_VARIANT_UTS46` constant is defined (which causes the original error above), and fall back to `INTL_IDNA_VARIANT_2003` instead...

There is apparently an undocumented PHP constant `INTL_UCI_VERSION` for this:
https://stackoverflow.com/questions/53996249/php-get-icu-version
http://svn.php.net/viewvc/?view=revision&revision=311714

**Comment by jonnott** [comment]
Proof the constant works!

```
<? exit(INTL_ICU_VERSION);
```

**Comment by jonnott** [comment]
I guess it's all irrelevant, and Guzzle requires PHP ^7.2.5, but `INTL_IDNA_VARIANT_2003` was deprecated in PHP 7.2 :(

**Comment by alexeyshockov** [comment]
Please also take a look at #2454

**Comment by jonnott** [comment]
> Please also take a look at #2454

Great! Also, do you think the `INTL_ICU_VERSION` constant would be of any use to simplify the patch that's already been done? Would you perhaps not need the PHP 7.2 version comparison? I guess you might as the 2003 variant constant is deprecated from PHP >7.2 ..?

**Comment by jonnott** [comment]
Feel free to close this issue - it's a duplicate of https://github.com/guzzle/guzzle/issues/2448 and other .. I was just externally processing as I was working out what was going wrong ;)

**Comment by alexeyshockov** [comment]
> Also, do you think the INTL_ICU_VERSION constant would be of any use to simplify the patch that's already been done?

Don't think so... We need PHP version check anyway because of the deprecation, yes.
