### ISSUE TITLE
localStorage

### ISSUE THREAD

**Issue by saycoder** [guzzle/guzzle#2472]
**Description**  
How to enable local Storage in guzzle
Some sites read some information and settings from the local Storage for example filters and display settings.How to use this in guzzle

**Example**  

`var d=localStorage.getItem("Rainbow_"+f+"_SelTab")`

**Comment by GrahamCampbell** [comment]
Guzzle is not a web browser, and doesn't execute javascript.

**Comment by sagikazarmark** [comment]
As @GrahamCampbell said, Guzzle is a PHP HTTP client, local storage is a client-side technology.
