### ISSUE TITLE
NOTICE: idn_to_ascii() INTL_IDNA_VARIANT_2003 only takes 3

### ISSUE THREAD

**Issue by nao-pon** [guzzle/guzzle#2488]
**Guzzle version(s) affected**: 5.6.1
**PHP version**: 5.5.38 (hint: `php --version`)
**cURL version**: 7.51.0 (hint: `php -i | grep cURL`)

**Description**  

Notice error occurs.

"NOTICE: idn_to_ascii(): 4 arguments were provided, but INTL_IDNA_VARIANT_2003 only takes 3 - extra argument ignored in guzzlehttp/guzzle/src/functions.php line 362."

**How to reproduce**  

Execute in an environment where `INTL_IDNA_VARIANT_UTS46` is not defined.

**Comment by gmponos** [comment]
did it happen to explicitly set the `idn_conversion` option to true?

**Comment by nao-pon** [comment]
@gmponos No,

https://github.com/guzzle/guzzle/blob/6.5/src/Client.php#L243-L250

`function_exists ('idn_to_ascii')` and `PHP_VERSION_ID <70200` are true.

**Comment by gmponos** [comment]
New version with the fix is tagged... https://github.com/guzzle/guzzle/releases/tag/6.5.2

**Comment by nao-pon** [comment]
@gmponos , @alekseykuleshov Thanks! 👍 

The problem I got was solved!
