### ISSUE TITLE
Using GuzzleHttp On IIS 10, PHP 5.6.39, and Laravel 5.2

### ISSUE THREAD

**Issue by Tieantono** [guzzle/guzzle#2491]
Hi @sagikazarmark, I just want to let you know that for an error that only display blank error page that's happening when doing a HTTP request using GuzzleHttp on these environment specifications:
- IIS version 10
- PHP version 5.6.40
- Laravel version 5.2
- GuzzleHttp version 6.2

The rootcause for that error page (from what I found) is we need to grant write access for IIS' Application Pool Identity account (in this case, IUSR), since from what I have found so far, php:\\temp will write on temp folder on Windows, and the web server application must have write access on the temp folder. After grant the access, GuzzleHttp will work.

My suggestion here are:
- Put a notes on the documentation about using GuzzleHttp on IIS
- Display the exception on the page, instead of the blank page

**Comment by sagikazarmark** [comment]
Hi @Tieantono 

The documentation part might be a good idea, although I would probably rephrase that in a general form stating that Guzzle needs write access to a temp directory (that's true regardless of the OS).

As for the blank page: I'm pretty sure that's caused by Laravel (I'm guessing in prod mode exceptions are not displayed, but they might be logged)

**Comment by Tieantono** [comment]
> 
> 
> Hi @Tieantono
> 
> The documentation part might be a good idea, although I would probably rephrase that in a general form stating that Guzzle needs write access to a temp directory (that's true regardless of the OS).
> 
> As for the blank page: I'm pretty sure that's caused by Laravel (I'm guessing in prod mode exceptions are not displayed, but they might be logged)

Alright, thank you for considering my suggestion.

As for the log part, from what I remembered, it seems I didn't find any log message regarding the exception for this matter, but for other kind exception like Laravel invalid CSRF token, it was displayed in my browser in development settings using IIS, but no error was displayed for GuzzleHttp exception.
