### ISSUE TITLE
Finalize the list with php-cs-fixer rules

### ISSUE THREAD

**Issue by gmponos** [guzzle/guzzle#2498]
I would like to propose and we can discuss about a final list with rules for php-cs-fixer:

```
        '@PSR2' => true,
        'array_syntax' => ['syntax' => 'short'],
        'blank_line_after_opening_tag' => true,
        'concat_space' => ['spacing' => 'one'],
        'declare_strict_types' => false,
        'function_to_constant' => ['functions' => ['php_sapi_name']],
        'fully_qualified_strict_types' => true,
        'header_comment' => false,
        'lowercase_cast' => true,
        'is_null' => ['use_yoda_style' => false],
        'magic_method_casing' => true,
        'modernize_types_casting' => true,
        'multiline_comment_opening_closing' => true,
        'native_constant_invocation' => true,
        'no_alias_functions' => true,
        'no_alternative_syntax' => true,
        'no_blank_lines_after_phpdoc' => true,
        'no_empty_comment' => true,
        'no_empty_phpdoc' => true,
        'no_extra_blank_lines' => true,
        'no_leading_import_slash' => true,
        'no_spaces_around_offset' => true,
        'no_superfluous_phpdoc_tags' => ['allow_mixed' => true],
        'no_trailing_comma_in_singleline_array' => true,
        'no_unset_cast' => true,
        'no_unused_imports' => true,
        'no_useless_else' => true,
        'no_useless_return' => true,
        'no_whitespace_in_blank_line' => true,
        'ordered_imports' => true,
        'php_unit_mock' => ['target' => 'newest'],
        'php_unit_dedicate_assert_internal_type' => ['target' => 'newest'],
        'php_unit_expectation' => ['target' => 'newest'],
        'php_unit_no_expectation_annotation' => ['target' => 'newest'],
        'php_unit_test_annotation' => ['style' => 'prefix'],
        'php_unit_test_case_static_method_calls' => ['call_type' => 'self'],
        'php_unit_mock_short_will_return' => true,
        'phpdoc_align' => ['align' => 'vertical'],
        'phpdoc_line_span' => ['method' => 'multi', 'property' => 'multi'],
        'phpdoc_scalar' => true,
        'phpdoc_separation' => true,
        'phpdoc_single_line_var_spacing' => true,
        'phpdoc_trim' => true,
        'phpdoc_trim_consecutive_blank_line_separation' => true,
        'phpdoc_types' => true,
        'phpdoc_types_order' => ['null_adjustment' => 'always_last', 'sort_algorithm' => 'none'],
        'phpdoc_var_without_name' => true,
        'short_scalar_cast' => true,
        'single_trait_insert_per_statement' => true,
        'standardize_not_equals' => true,
        'visibility_required' => true,
        'yoda_style' => false,
```

Some of these might not be useful today but they will be useful during reviews.

You can find more details of the rules here: https://mlocati.github.io/php-cs-fixer-configurator/#version:2.16

**Comment by alexeyshockov** [comment]
> '@PSR2' => true,

I would suggest to stick with PSR-12 from the beginning, even if it's not released as a separate ruleset yet (should be [available soon](https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/4502)).

**Comment by gmponos** [comment]
I tired to stick with PSR-12 (adding any rule I know that already exists). 

Do you see any rule from the ones added that violates it... or do you have rule that should be added?

**Comment by alexeyshockov** [comment]
> or do you have rule that should be added?

No, I'm definitely fine with all the rules above. Just thought that we can reuse [something like this](https://www.tomasvotruba.cz/blog/2018/04/09/try-psr-12-on-your-code-today/) until PSR-12 ruleset is released officially.

**Comment by sagikazarmark** [comment]
Not entirely sure what you are suggesting @alexeyshockov . Do you suggest using the easy coding standard tool? (Quickly went through the post, but I couldn't find a "use this snippet until PSR-12 is out" kinda thing.)

**Comment by GrahamCampbell** [comment]
We should also add `'compact_nullable_typehint' => true,`. This is a requirement of the PSR-12 spec.

**Comment by GrahamCampbell** [comment]
Also, `'declare_equal_normalize' => ['space' => 'none'],`, even though Guzzle doesn't use this (yet).

**Comment by GrahamCampbell** [comment]
We should add the following rules too, which are PSR-12 rules:

```php
[
    'compact_nullable_typehint' => true,
    'declare_equal_normalize' => ['space' => 'none'],
    'function_typehint_space' => true,
    'no_leading_namespace_whitespace' => true,
    'space_before' => 'none',
]
```

**Comment by GrahamCampbell** [comment]
> Quickly went through the post, but I couldn't find a "use this snippet until PSR-12 is out" kinda thing.

I've just created one on the upstream repo. ;)

**Comment by GrahamCampbell** [comment]
Many of the new rules and subtle changes aren't yet supported by php-cs-fixer, yet, so the rule list is not complete, or totally accurate in the changes it actually makes (in particular, the PSR2 braces stuff is not compatible with the PSR-12 braces stuff, but close enough for now).

**Comment by gmponos** [comment]
Hello after the great work of @rvanlaak [here](https://github.com/guzzle/guzzle/pull/2677) I would to bring up again this matter and proceed with this.. 

The PR above contained some style fixes that could be spotted by php-cs-fixer and it could help future reviews.

**Comment by rvanlaak** [comment]
Maybe update the concept PSR12 config and go with that for now? Looks like CS-Fixer will have the final set ready before Guzzle 7.0 will get released.

**Comment by gmponos** [comment]
Closing... updates might still occur.

**Comment by GrahamCampbell** [comment]
I think we should add the rule(s) that makes sure casts are normalised: `cast_spaces`, `lowercase_cast`.
