### ISSUE TITLE
Release 7.0.0-beta1

### ISSUE THREAD

**Issue by Nyholm** [guzzle/guzzle#2510]
Weeks of hard work has lead us to this moment. Lots of people have helped with code, reviews and thoughts. Special thanks to @sagikazarmark, @gmponos, @GrahamCampbell and @alexeyshockov.

I suggest we tag 7.0.0-beta1 the next few days. Before we do that, any reviews on  [UPGRADING.md](https://github.com/guzzle/guzzle/blob/master/UPGRADING.md), [CHANGELOG.md](https://github.com/guzzle/guzzle/blob/master/CHANGELOG.md) and [the diff](https://github.com/guzzle/guzzle/compare/6.5.0..master) would be appreciated. And please, test **master** in your projects.

When preparing for the beta release, we should also see if the documentation needs to be updated.

**Comment by sagikazarmark** [comment]
Don't leave @Nyholm out of the list. 🙂

**Comment by sagikazarmark** [comment]
https://github.com/guzzle/guzzle/releases/tag/7.0.0-beta.1
