### ISSUE TITLE
Mark classes with final annotation in 7.1

### ISSUE THREAD

**Issue by gmponos** [guzzle/guzzle#2521]
As per the title says here we can have a discussion about adding final annotation to classes and then making them final on version 8

The reason we want to do that on 7.1 is that we don't want towards version 7 to introduce more major changes than the ones we already have.. 

So the thought is to make them final on version 8. Before that there is a though about adding final annotations to classes on version 7.1

**Comment by GrahamCampbell** [comment]
Big :-1: on this. I am totally against annotations that are not actually enforced, when it comes to something being final.

**Comment by GrahamCampbell** [comment]
I am in favour of making some things properly final in version 8 (like the client, BUT only if we have the interface changes).

**Comment by gmponos** [comment]
> Big 👎 on this.

But what is the reason? What difference will make for you as a developer if there is a final annotation. The reason we want to have final annotation is in order to inform the developers that we will do the change on v8.. something like a deprecation... If I could do it with a deprecation then I would.. If it is possible then let me know.. 

if I am not mistaken symfony does the same with annotations as well..

**Comment by GrahamCampbell** [comment]
Because it's being marked as final in a missleading way. It's not actually final.

**Comment by GrahamCampbell** [comment]
> if I am not mistaken symfony does the same with annotations as well..

Really? Can you show me a class from Synfony 5.0 that is annotated final, but is not actually final.

**Comment by gmponos** [comment]
https://github.com/symfony/symfony/blob/4.4/src/Symfony/Bundle/FrameworkBundle/Controller/AbstractController.php#L65

**Comment by GrahamCampbell** [comment]
That's marking a method as final, not a class?

**Comment by gmponos** [comment]
For the reason that it is used I fail to see the difference but never the less here is another example.. https://github.com/symfony/symfony/blob/4.4/src/Symfony/Bundle/FrameworkBundle/Command/ConfigDebugCommand.php#L28

> It's not actually final.

Yes.. that's the goal.. otherwise it would've been made on v7.

**Comment by GrahamCampbell** [comment]
Hmmm. I guess symfony has a special reason for doing this. Are they only doing it to 4.4 classes because of the simultaneous release of 5.0 where they become enforced? This is kinda difference to just randomly doing it in 4.2.0.

**Comment by gmponos** [comment]
> Hmmm. I guess symfony has a special reason for doing this. 

it's the same as adding a deprecation annotation for extending a class.. I guess if they (or we) could add a deprecation notice because someone extended a class then we would and the final annotation would not be needed.. but personally I don't know how this is possible.. so adding a final annotation is the perfect path here..

**Comment by gmponos** [comment]
Note also that ppl who use symfony if they extend a class that is marked with a final annotation profiler bar shows a warning.

**Comment by GrahamCampbell** [comment]
Meh. I guess I'm kinda neutral now. I mostly just think it would be a waste of someone's time to implement in 7.x, now.

**Comment by Nyholm** [comment]
Fixed in #2726

**Comment by pullthefuse** [comment]
I really hate this adding final to classes. I understand that it encourages developers to use composition or decorate the service but firstly there are instances where extending a class is valid and saves writing excess code and should we be forcing developers to code in a "correct" way.

In my instance I extend the class in a test bundle I have written as it allows me to intercept all external calls made with Guzzle and test accordingly. Now the only way for me to get it to work with final is to use the ClientInterface on a new class, inject the Client and now I have to implement all the methods and call the Client on each one as I only need to add functionality to the requestAsync method.

**Comment by mfn** [comment]
> allows me to intercept all external calls made with Guzzle and test accordingly

Have you considered https://docs.guzzlephp.org/en/stable/testing.html#mock-handler ?

I've a project where I use 20+ different guzzle clients with different configurations, integrated with other API clients (like google sdk, fb sdk, etc.) and the `MockHandler` truly helps catching _and_ asserting external calls.

HTH

**Comment by pullthefuse** [comment]
I am using the mock handler as well! 

I have a test bundle that makes testing our microservices much easier and more automatic by setting the mock handlers automatically and generically returning test data. It is setup to intercept external requests with either HttpClient or Guzzle depending on what is being used to call the request. I have it setup with HttpClient without extension but with Guzzle it is a necessity because of how Guzzle is written.
