### ISSUE TITLE
Encoding json data using guzzle 'json' option does not preserve float values.

### ISSUE THREAD

**Issue by quentin389** [guzzle/guzzle#2538]
**Guzzle version(s) affected**: 6.3.3
**PHP version**: 7.3.6
**cURL version**: 7.64.0 (hint: `php -i | grep cURL`)

**Description**  
Guzzle allows for a 'json' parameter to be passed to a request in order to easily upload JSON encoded data as the body of a request.

This encodes the data in https://github.com/guzzle/guzzle/blob/db9e56915c44625a19fad8b5948f7ca039673fc5/src/Client.php#L378 without specifying JSON_PRESERVE_ZERO_FRACTION option (see: https://www.php.net/manual/en/json.constants.php).

This results in PHP values: (float)5.0 and (int)5 being represented identically in the transferred JSON data.

As a result, when I retrieve the guzzle encoded string in another PHP script and decode the data using json_decode() in both situations I end up with integer values.

**How to reproduce**  
```php
$data = file_get_contents('php://input');
if ($data) {
    var_dump($data, json_decode($data, true));
} else {
    $client = new GuzzleHttp\Client();
    $response = $client->request('POST', "http://{$_SERVER['HTTP_HOST']}/", [
        'json' => ['string' => "5", 'integer' => 5, 'float' => 5.0]
    ]);
    echo $response->getBody()->getContents();
}
```
will return:
```html
string '{"string":"5","integer":5,"float":5}' (length=36)
array (size=3)
  'string' => string '5' (length=1)
  'integer' => int 5
  'float' => int 5
```

**Possible Solution**  
add JSON_PRESERVE_ZERO_FRACTION to json_encode (or an option to do so).

**Comment by alexeyshockov** [comment]
In Guzzle `json` is very simple, it's translated to a `json_encode()` call with default options set (as you already noticed). If you want a more complex, specific behaviour, just use `json_encode()` directly with the `body` option:

```php
$response = $client->request('POST', "http://{$_SERVER['HTTP_HOST']}/", [
    'body' => json_encode(['string' => "5", 'integer' => 5, 'float' => 5.0], JSON_PRESERVE_ZERO_FRACTION),
    'headers' => ['Content-Type' => 'application/json']
]);
```

The issue was already discussed in #2343, and until now we haven't found a solution that is flexible and (at the same time) doesn't add unwanted complexity. Maybe the best solution is to remove `json` option at all, because the same question is being asked again and again... Not sure.

**Comment by alexeyshockov** [comment]
To be clear: we are not going to add configurable options for `json_encode()` (at least now), so I'm closing the issue.

I also don't think that the default options set for `json_encode()` should be changed (to include `JSON_PRESERVE_ZERO_FRACTION`). If other maintainers think differently, feel free to reopen.
