### ISSUE TITLE
Memory leak with promises and CurlMultiHandler

### ISSUE THREAD

**Issue by boesing** [guzzle/guzzle#2556]
**Guzzle version(s) affected**: 6.5.2
**PHP version**: 7.3.12 + 7.4.0
**cURL version**: 7.67.0 

**Description**  
Hey there, I am experiencing some memory leaks when using guzzle to asynchronously  fetch multiple JSON documents and parse them into a collection.
I've setup a project where I created a snippet to reproduce that behavior.

Would love if someone can give me either a shot if this is really guzzle related, or, if not, how to profile that script to find the memory leak.

Thanks in advance.

**How to reproduce**  
Check out https://github.com/boesing/guzzle-memory-issue and run the script.

**Possible Solution**  
-

**Additional context**  
-

**Comment by GrahamCampbell** [comment]
Is this the same problem as https://github.com/guzzle/guzzle/issues/2555.

**Comment by boesing** [comment]
Not quite sure, you are talking about streams in your PR but this is Curl related.
I am fine if you change the naming of your ticket to a general memory issue instead of "stream". Would close this ticket and comment your issue with my case.

**Comment by Nyholm** [comment]
Thank you for a nice reproducible issue. I ran the script in Blackfire. 
Here is the profile: https://blackfire.io/profiles/8acbbd71-17d9-45d6-987f-c95180e0ca1a/graph

It makes sense that there is a high memory usage. Because we download that much data and we also json_decode it. If we dont save the data in `$collection`, then memory "after" will go down.

**Comment by boesing** [comment]
Okay but the size of collection is "only" a few MB. 

It should be possible to free that memory as it actually is not used anymore. 
Can you give me a shot where you see memory informations in blackfire? 

How is it possible that the array (collection) wastes more memory than it stores? Would love to see how to get rid of that. 😕

**Comment by boesing** [comment]
Closing this in favor of #2555
