### ISSUE TITLE
Ssl Curl Issue error 60

### ISSUE THREAD

**Issue by WaleedAshrafUsmani** [guzzle/guzzle#2572]
I am getting that Error when i am trying to hit an get request of easypaisa.Get Api of easy paisa is working fine in postman but getting this error when i try with laravel Controller.
Can Any One tell me what was the issue in it.
cURL error 60: Peer's Certificate issuer is not recognized. (see http://curl.haxx.se/libcurl/c/libcurl-
errors.html)

**Comment by gmponos** [comment]
http://docs.guzzlephp.org/en/stable/request-options.html#verify-option
