### ISSUE TITLE
Allow a better way to send empty files

### ISSUE THREAD

**Issue by marekstodolny** [guzzle/guzzle#2575]
**Description**
Sending empty files in a multipart POST form is a proper use case due to web browsers supporting it. 

I worked on a API layer using guzzle that had to work with an existing legacy codebase and trigger some actions (a proxy of some sort). There was a case where files had to be sent with empty content and would not work if you would omit them.

**Example**
_Currently no implementation, just an idea._

**Additional context**
This is how a browser handles an empty file (with a real image being sent below, content truncated):
```
-----------------------------136653946812128712601521111247
Content-Disposition: form-data; name="empty_file"; filename=""
Content-Type: application/octet-stream


-----------------------------136653946812128712601521111247
Content-Disposition: form-data; name="file"; filename="TLBtuIfGT3Y.jpg"
Content-Type: image/jpeg

ÿØÿàJFIFHHÿâICC_PROFILE
```

This can't be replicated in guzzle. Sending a file like this won't work at all:

```php
$this->client->request('POST', 'url', ['multipart' => [
    [
        'name' => 'empty_file',
        'contents' => '',
        'filename' => '',
        'headers' => ['Content-Type' => 'application/octet-stream'],
    ]
]]);
```

But there's a workaround if your code runs on UNIX-like system:

```php
$this->client->request('POST', 'url', ['multipart' => [
    [
        'name' => 'empty_file',
        'contents' => fopen('/dev/null', 'rb'),
        'filename' => '',
        'headers' => ['Content-Type' => 'application/octet-stream'],
    ]
]]);
```
Values like `''`, `"\0"`, null don't work, only thing that has worked for me so far is a /dev/null stream.
So far I haven't been able to find other way to create an empty stream but I'm working on it.

**I was wondering if you want to support this somehow?**

**Comment by alexeyshockov** [comment]
I'm not sure if we want to include it to the code base somehow, but maybe we can add it to the docs? In [FAQ](http://docs.guzzlephp.org/en/stable/faq.html) maybe.
