### ISSUE TITLE
Recommended way to determine Guzzle 7?

### ISSUE THREAD

**Issue by bshaffer** [guzzle/guzzle#2579]
**Description**
For any library compatible with multiple versions of Guzzle, we no longer have a way to reliably determine the version in Guzzle 7, as the `ClientInterface::VERSION` constant has been [removed](https://github.com/guzzle/guzzle/pull/2421). What is the recommended way to tell that Guzzle 7 is installed?

Currently we assume Guzzle 7 if the VERSION constant is not defined, but this will break with Guzzle 8. I've noticed in the PRs that @Nyholm is concerned with breaking BC every time a new release comes out, but if only the major version is captured in the constant, or if the version is specified in a method instead of a constant (e.g. `Client::getGuzzleVersion()`), this would not be the case. 

An even better option would be to simply include a `VERSION` file in the root of this repo with the version number ([like we do here](https://github.com/googleapis/google-cloud-php-storage/blob/master/VERSION))

**Example**
```php
GuzzleHttp\Client::getGuzzleVersion()
```

**Additional context**
https://github.com/googleapis/google-auth-library-php/pull/256/files

**Comment by GrahamCampbell** [comment]
You can get the version from composer. It will tell you.

**Comment by GrahamCampbell** [comment]
```php
<?php

class Example
{
    public static function getGuzzleVersion()
    {
        static $version;

        if ($version === null) {
            $packages = @json_decode(file_get_contents(self::getComposerInstalledFile()), true);

            if (!is_array($packages)) {
                throw new RuntimeException('Unable to obtain Guzzle version from Composer.');
            }

            foreach ($packages as $package) {
                if ($package['name'] === 'guzzlehttp/guzzle') {
                    $version = $package['version'];

                    break;
                }

                throw new RuntimeException('Unable to obtain Guzzle version from Composer.');
            }
        }

        return $version;
    }

    private static function getComposerInstalledFile()
    {
        // UPDATE THIS RELATIVE TO WHERE YOU PUT THIS CODE IN YOUR LIBRARY
        // IN THIS EXAMPLE, I HAVE ASSUMED YOU PUT THIS "Example" CLASS DIRECTLY
        // IN A "src" FOLDER, SO IT IS INSTALLED AS "vendor/your/library/src/Example.php"
        return __DIR__.'/../../../composer/installed.json';
    }
}
```

**Comment by Nyholm** [comment]
I think it is a bad idea to have the full version as a constant. It is one thing that is super easy to forget when releasing a new version since we have not scripted released. It is also technically a BC break. 

But to make things easier, we can add a MAJOR_VERSION constant to both Guzzle 6 and Guzzle 7. 
Would that be a good and easy solution?

**Comment by sagikazarmark** [comment]
Personally, I think the best thing you can do is not depend on Guzzle at all. You should depend on PSR-18 instead and leave choosing a client to the consumer.

Otherwise a MAJOR_VERSION constant sounds like the easiest solution, but TBH, I'm not a huge fan of it.

**Comment by bshaffer** [comment]
@GrahamCampbell the way you suggest relies on a `composer.json` being present, which may not be the case since it may not be deployed in production. Additionally, it's a fairly complicated and inefficient way to go about it, requiring a file read and JSON parsing.

@Nyholm Yes, having a MAJOR_VERSION would be exactly what we're looking for. But @sagikazarmark makes a good point that we may be able to just handle Guzzle 5 vs PSR-18, and otherwise not care.

**Comment by GrahamCampbell** [comment]
> @GrahamCampbell the way you suggest relies on a composer.json being present, which may not be the case since it may not be deployed in production.

No, it doesn;t use the composer.json. It uses the special file within the vendor folder which tells you what packages are there.

**Comment by GrahamCampbell** [comment]
I would definitely say a major version constant is a better idea than recommending people do a hack like I have provided to grab the installed package version. :P

**Comment by bshaffer** [comment]
@GrahamCampbell Ahh, roger that. Thanks for the clarification. I still do not think it wise to depend on a composer config file and require a file read + json parse.

**Comment by gmponos** [comment]
FYI https://github.com/aws/aws-sdk-php/blob/master/src/functions.php#L318

**Comment by Nyholm** [comment]
It's a hack I did, it is not perfect :/

**Comment by bshaffer** [comment]
@Nyholm Aha!! So you DO need it too!! 😄

**Comment by Nyholm** [comment]
I decided not to add it to 6.x because it would not be a reliable way to determine version. 

See #2583
