### ISSUE TITLE
URI parser fails when there is a : in the path

### ISSUE THREAD

**Issue by meshenka** [guzzle/guzzle#2580]
**Guzzle version(s) affected**: 6.5.2
**PHP version**: 7.2.22
**cURL version**: 7.64.0

**Description**  

When i tries a POST to uri https://fcm.googleapis.com/v1/projects/****/messages:send  the Uri is incorrect

```
GuzzleHttp\Psr7\Uri^ {#308
  -scheme: "messages"
  -userInfo: ""
  -host: ""
  -port: null
  -path: "send"
  -query: ""
  -fragment: ""
}
```

not tested on other versions

**Comment by Tobion** [comment]
this is likely a php bug of parse_url. if you encode the `:` it will probably work

**Comment by meshenka** [comment]
That's odd

```php
 php -a    
Interactive mode enabled

php > var_dump(parse_url('https://fcm.googleapis.com/v1/projects/****/messages:send'));
array(3) {
  ["scheme"]=>
  string(5) "https"
  ["host"]=>
  string(18) "fcm.googleapis.com"
  ["path"]=>
  string(31) "/v1/projects/****/messages:send"
}
```
php -v

PHP 7.4.2 (cli) (built: Feb  5 2020 16:50:38) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.2, Copyright (c), by Zend Technologies

I got that on php 7.2.22 will investigate inside a container

**Comment by meshenka** [comment]
```php
php -v
PHP 7.2.14 (cli) (built: Jan 31 2019 00:52:40) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.14, Copyright (c) 1999-2018, by Zend Technologies
/srv # php -a
Interactive shell

php > var_dump(parse_url('https://fcm.googleapis.com/v1/projects/****/messages:send'));
array(3) {
  ["scheme"]=>
  string(5) "https"
  ["host"]=>
  string(18) "fcm.googleapis.com"
  ["path"]=>
  string(31) "/v1/projects/****/messages:send"
}
```

**Comment by meshenka** [comment]
same with php 7.2.22, :(

**Comment by GrahamCampbell** [comment]
https://3v4l.org/WWB1a

**Comment by Tobion** [comment]
So it's not a parse_url bug. Can you provide a reproducer please? At best a failing test case in guzzle.

**Comment by meshenka** [comment]
i found the issue, this reproduce when using baseuri

```php
$http = new Client([
            'base_uri' => 'https://fcm.googleapis.com/v1/projects/test/',
            'timeout' => 0,
            'allow_redirects' => false,
        ]);

        try{
            $response = $http->post('messages:send');

        } catch (RequestException $exception) {
            dump($exception->getRequest());
        }
```

the relative uri is considered an absolute one due to :

**Comment by Tobion** [comment]
Closing as `'messages:send'` is not a valid relative URI. It get's interpreted as a full uri with messages as schema according to the URI RFC spec. What you can do is set `https://fcm.googleapis.com/v1/projects` as base and use `test/messages:send` as relative part.

**Comment by Tobion** [comment]
`'./messages:send'` should also work as relative part.

**Comment by meshenka** [comment]
Thanks
