### ISSUE TITLE
Don't install phpstan using actions

### ISSUE THREAD

**Issue by GrahamCampbell** [guzzle/guzzle#2587]
There is no clear control on the version that is installed, thus we are seeing uncontrolled errors creeping in. Maybe better to install as a dev-dependency in composer?

**Comment by sagikazarmark** [comment]
I think this was intentional, but I agree it would be better to pin a version. I don't think adding a dev-dependency is a good idea though. It's not actually a dependency.

**Comment by AegirLeet** [comment]
I think adding thing sas dev-dependencies even if they aren't strictly required is fine. Most projects seem to handle phpunit, psalm, phpstan, phpmd, ... that way. If they're useful/often used for development/testing/CI, they should be in dev-dependencies IMHO.

**Comment by GrahamCampbell** [comment]
There's also the option of having it as a special separately locked dependency, like for example at https://github.com/schmittjoh/php-option. I've opted not to commit a composer.lock file in the `vendor-bin/phpstan` directory there, but that could be done if wanted.

**Comment by GrahamCampbell** [comment]
NB That special vendor-bin folder is managed by https://github.com/schmittjoh/php-option/blob/master/composer.json#L21.

NB2 In the case of Guzzle there may be little point in this, since phpstan has basically no dependencies since it is shipped as a phar. The package I linked to does this so that it's dev-dependencies can be installed on PHP 5.

**Comment by gmponos** [comment]
I don't remember if we installed first time phpstan on version 0.11 or version 0.12 but the version 0.12 has made a big change by distributing a phar file by default in the package an thus removing all the phpstan dependencies have been removed from their package..

https://phpstan.org/blog/phpstan-0-12-released#phar-distribution-by-default

With this change IMHO there is no reason why not having it as a dev dependency. it will never block you.

**Comment by gmponos** [comment]
I think we can close this now right?
