### ISSUE TITLE
New logo

### ISSUE THREAD

**Issue by sagikazarmark** [guzzle/guzzle#2588]
Hi everyone!

Guzzle 7 is going to be released soon and we thought this would be a great opportunity to create a new logo for the project.

We came up with a few versions and narrowed them down to four which you can see bellow.

Please vote with 👍 if you like a version, or share your thoughts as a comment.

Thanks!

**Comment by sagikazarmark** [comment]
## Candidate 1

![original_5-2](https://user-images.githubusercontent.com/1226384/74601279-c21ca980-509c-11ea-8cb6-f04b602c7720.jpg)

**Comment by sagikazarmark** [comment]
## Candidate 2

![original_7-3](https://user-images.githubusercontent.com/1226384/74601284-cb0d7b00-509c-11ea-978a-229995012b23.jpg)

**Comment by sagikazarmark** [comment]
## Candidate 3

![original_7-1](https://user-images.githubusercontent.com/1226384/74601292-d6f93d00-509c-11ea-943c-6b51d4070abd.jpg)

**Comment by sagikazarmark** [comment]
## Candidate 4

![original_7-4](https://user-images.githubusercontent.com/1226384/74601297-df517800-509c-11ea-9e6a-ab8dace79cbd.jpg)

**Comment by BafS** [comment]
Why not using the G as an arrow ?

Some drafts, to give some ideas:

![image](https://user-images.githubusercontent.com/588205/74685457-ec6e8400-51ce-11ea-831a-b0b30ad47298.png)

Number 6 represents the 2 `/` (for example http:**//**)

**Comment by sagikazarmark** [comment]
@BafS thanks a lot for the suggestions. We will take those into consideration.

**Comment by JABirchallHR** [comment]
I dont know if you are considering 3rd party logo designs, but heres reddit's created logo.
![https://i.imgur.com/pQjl3fn.jpg](https://i.imgur.com/pQjl3fn.jpg)

**Comment by JABirchall** [comment]
May I submit reddits candidate logo design

![Guzzle logo](https://i.imgur.com/pQjl3fn.jpg)

**Comment by mfn** [comment]
> May I submit reddits candidate logo design

I lolled very hard, sorry for the noise here 😄

**Comment by Bilge** [comment]
2 or 4 from @BafS, with some minor tweaks.

**Comment by csimpi** [comment]
None of them makes me feel what Guzzle does... More logos? :)

**Comment by sagikazarmark** [comment]
We are open to ideas, but representing "HTTP" and "client" in a logo is not easy, that's why we decided to have a more abstract icon and "G"s as candidates. We are past 20 something versions now, and a little bit out of ideas.

We've received a few suggestions here and on other channels, but none of them brought us closer so far.

**Comment by csimpi** [comment]
Yes, I see I just wanted to tell, give it more time maybe the perfect candidate will come a bit later :)  

The Candidate 4 looks good, but the logo should represent the request-response directions maybe with arrows or one of the lighter dots should be on the other side of the line. 

Maybe playing around the recycle logo could give a good starting point:
https://hu.pinterest.com/pin/142356038196697293

Some helpful links for brainstorming:
https://hu.pinterest.com/pin/789467009658941373/
https://hu.pinterest.com/pin/369576713165837367
https://hu.pinterest.com/search/pins/?q=logo%20G&rs=typed&term_meta[]=logo%7Ctyped&term_meta[]=G%7Ctyped

This is convertible to a G:
https://i.pinimg.com/originals/d6/7d/53/d67d53369ca6d095005b17d60a97ffdb.png

**Comment by sagikazarmark** [comment]
Thanks for all the ideas and feedback. We decided to go with Candidate 3.

**Comment by Bilge** [comment]
OK, but that's wrong.
