### ISSUE TITLE
SSL routines:ssl3_get_record:wrong version number

### ISSUE THREAD

**Issue by ayman-elmalah** [guzzle/guzzle#2593]
**Guzzle version(s) affected**: x.y.z 
**PHP version**: x.y.z (hint: `php --version`) 7.4
**cURL version**: x.y.z (hint: `php -i | grep cURL`) => 7.65

**Description**  

I'm using cloud flare to make my app secure with ssl, and when i connect to guzzle it give me this error
cURL error 35: error:1408F10B:SSL routines:ssl3_get_record:wrong version number (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)",

**How to reproduce**  

$http = new \GuzzleHttp\Client();
            $response = $http->post($app_url . '/oauth/token', [
                'form_params' => [
                    'grant_type' => 'password',
                    'client_id' => $client->id,
                    'client_secret' => $client->secret,
                    'username' => $email,
                    'password' => $password,
                    'provider' => $provider,
                ],
            ]);
**Possible Solution**  

**Additional context**

**Comment by cgsmith** [comment]
I am having this issue on PHP 7.3.8, CURL 7.58.0 - Guzzle 6.5.0

The CRON and API server are the same but I reference the API URI in the request. 
```
/var/www/backend# php cron.php shiporders
*   Trying 127.0.1.1...
* TCP_NODELAY set
* Connected to api.getshipwise.com (127.0.1.1) port 443 (#0)
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* error:1408F10B:SSL routines:ssl3_get_record:wrong version number
* Closing connection 0
```

**Comment by cgsmith** [comment]
In my case. My Apache VirtualHost was set for the IP address and not the domain name. After setting it for the proper domain name on the VirtualHost and restarting the service my CURL request worked.
