### ISSUE TITLE
Fatal error: Uncaught GuzzleHttp\Exception\ClientException: Client error

### ISSUE THREAD

**Issue by arvindpundir** [guzzle/guzzle#2596]
I am trying to get member details via rest API in php for GRS storefront, I dont know how to use AuthData (), class, why docs of guzzle to hard to understand

<?php
require '../x_static_libs/guzzle/vendor/autoload.php';
$url="https://c2-rewards.com";
use GuzzleHttp\Client;
$client = new Client();  
class AuthData 
{
	 public $id;
	 public $token;
}            
$auth = new AuthData();
$auth->id = 'EFDEMO';
$auth->token = 'BlC8CKxadtiOwdq0S019afV8bczn0Kh2';
//$auth->password = 'EFDEMO'; // not needed if using token
$response = $client->get($url.'/getMemberAccount', array(
    'auth' => base64_encode(json_encode($auth)),
    'verify' => false,
    'timeout' => 30 // seconds
));

$jsonData = json_decode($response->getBody(), true);
echo $jsonData;

**Comment by arvindpundir** [comment]
I am using API from this ,https://www.globalrewardsolutions.com/

**Comment by massimomarazzi** [comment]
Hi, same here, 
Php 7.2.28 on apache

Composer:
`
 "require": {
        "guzzlehttp/guzzle": "^6.5.2"
    },
`
Code: 
`
$access_token_uri = "https://api.instagram.com/oauth/access_token";
		$form_params = [
			'form_params'=> [
				'client_secret' => 'client_secret',
				'client_id' => 'XXXXXXXXXX',
				'grant_type' => 'authorization_code',
				'redirect_uri' => HOME_URL . '/oauth-ok/',
				'code' => $auth_code
			],
			'debug' => DEBUG
		];
		$clientPost = new GuzzleHttp\Client();
		$response_short_token = $clientPost->request('POST', $access_token_uri, $form_params );`

Error Log:

`PHP Fatal error:  Uncaught GuzzleHttp\Exception\ClientException: Client error: `POST https://api.instagram.com/oauth/access_token` resulted in a `400 Bad Request` response:
{"error_type": "OAuthException", "code": 400, "error_message": "Error validating verification code. Please make sure you (truncated...)
 in /vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:113

Stack trace:
#0 //vendor/guzzlehttp/guzzle/src/Middleware.php(65): GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Psr7\Request), Object(GuzzleHttp\Psr7\Response))
#1 /vendor/guzzlehttp/promises/src/Promise.php(203): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Response))
#2 /vendor/guzzlehttp/promises/src/Promise.php(156): GuzzleHttp\Promise\Promise::callHandler(1, Object(GuzzleHttp\Psr7\Res in /vendor/guzzlehttp/guzzle/src/Exception/RequestException.php on line 113
`

**Comment by gmponos** [comment]
Hi,

We use GitHub issues only to discuss bugs and new features. For this kind of questions please use other support channels like stackoverflow. 

https://stackoverflow.com/questions/tagged/guzzle

Never the less if you have any suggestion to improve our docs feel free to submit a PR. Contributions are welcome.
