### ISSUE TITLE
cURL error 60: SSL certificate problem: unable to get local issuer certificate (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)

### ISSUE THREAD

**Issue by iamzouz** [guzzle/guzzle#2601]
**Guzzle version(s) affected**: 6.5
**PHP version**: 7.4.0
**cURL version**: 7.67.0

Hi, i am new to guzzle and laravel, i installed Guzzle using 'composer require guzzlehttp/guzzle', in order to send http request.
and i am receiving the below error:

`cURL error 60: SSL certificate problem: unable to get local issuer certificate (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)`

Here is my code:
Controller:
```
<?php

namespace App\Http\Controllers;
use Illuminate\Http\Request;
use GuzzleHttp\Client;

class GuzzleController extends Controller
{
    public function getData(){
        $client = new \GuzzleHttp\Client();
        $response = $client->request('GET', 'https://api.github.com/repos/guzzle/guzzle');
        echo $response->getStatusCode(); // 200
        echo $response->getHeaderLine('content-type'); // 'application/json; charset=utf8'
        echo $response->getBody(); // '{"id": 1420053, "name": "guzzle", ...}'
        });
        $promise->wait();
    }
}
```
web.php:

`Route::get('/guzzle','GuzzleController@getData');`

Anyone have an idea about the issue?
Thank you in advance

**Comment by vaclavvanik** [comment]
Its not about guzzle but underlying curl library. Try `curl -v 'https://api.github.com/repos/guzzle/guzzle'`. Curl should tell you more info.

**Comment by gmponos** [comment]
There is an FAQ for this: http://docs.guzzlephp.org/en/stable/faq.html#why-am-i-getting-an-ssl-verification-error

**Comment by gmponos** [comment]
I believe we can close this.. If you have any more feedback about this we can reopen if it is needed.
