### ISSUE TITLE
syntax error, unexpected 'return' (T_RETURN) {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): syntax error, unexpected 'return' (T_RETURN) at /x/x/x/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:203)

### ISSUE THREAD

**Issue by robyfirnandoyusuf** [guzzle/guzzle#2602]
**Guzzle version(s) affected**: 6.5
**PHP version**: 7.2.24
**cURL version**: 7.29.0

**Description**  
I've migrated my project into another server which my server the requirements
**PHP version**: 7.2.24
**cURL version**: 7.29.0
**OS  : Centos 7**
and got error like this 
<img src="https://i.postimg.cc/nhhdsqq3/image-8.png">

and guzzle working fine on my old server, which the requrements : 

**PHP version**: 7.2.12
**cURL version**: 7.29.0
**OS  : Centos 7**
Anyone can help me out ?

**Comment by GrahamCampbell** [comment]
Probably because your php version is not actually that. Ask php-fpm what it's version is, in code.

**Comment by robyfirnandoyusuf** [comment]
> Probably because your php version is not actually that. Ask php-fpm what it's version is, in code.

I've try to restart php-fpm and still not working .. is it cause guzzle shouldn't return as object ?

**Comment by GrahamCampbell** [comment]
What is your actual php-fpm version?

**Comment by robyfirnandoyusuf** [comment]
I can't figure it out the version of php-fpm but I think 7.2 , 

![image](https://user-images.githubusercontent.com/17494868/77242554-39140780-6c32-11ea-8858-fb77bcaca5b4.png)

**Comment by robyfirnandoyusuf** [comment]
[SOLVED] - someone try to joke me and edited the source of guzzle
