### ISSUE TITLE
Add psalm

### ISSUE THREAD

**Issue by vladyslavstartsev** [guzzle/guzzle#2603]
**Description**
Adding similar issue to http client repo as this https://github.com/guzzle/psr7/issues/324
tl;dr
add psalm as static analysis tool to the project

**Comment by gmponos** [comment]
I am in the same page as @Tobion on this [comment](https://github.com/guzzle/psr7/issues/324#issuecomment-628355418).

Moreover I believe that there is no actual benefit and it will cause more headaches to developers that want to contribute. Let's focus on resolving the current PHPStan issues and the we can re-discuss about psalm.

**Comment by vladyslavstartsev** [comment]
:+1:
