### ISSUE TITLE
Documentation error: postField vs formParam

### ISSUE THREAD

**Issue by DicksB** [guzzle/guzzle#2604]
**Description**  
Documentation on service descriptions:
https://guzzle3.readthedocs.io/webservice-client/guzzle-service-descriptions.html#postfield-location

It seems this was changed some time back so that we should use "formParam" instead of "postField", and indeed, making the change got my requests working properly. I discovered this through this closed issue:

https://github.com/guzzle/guzzle-services/issues/119

...but it appears the documentation was either never changed, or was reverted at some point.

**Comment by heitoralthmann** [comment]
I am not sure this will be possible until we have a new documentation page for Service Descriptions.

That old site lives in a different project (https://github.com/guzzle/guzzle3) which had been archived, and so we cannot create new PRs anymore.

**Comment by gmponos** [comment]
I also feel that this is related with https://github.com/guzzle/guzzle-services and not guzzle (http client). I am closing this.. feel free to report this to the guzzle-services repo.
