### ISSUE TITLE
Memory leak when throw exception in `Middleware::httpErrors()`.

### ISSUE THREAD

**Issue by limingxinleo** [guzzle/guzzle#2606]
**Guzzle version(s) affected**: 6.5.2
**PHP version**: 7.2.29
**cURL version**:  7.69.1

**Description**  
Memory leak when throw exception in `Middleware::httpErrors()`.

**How to reproduce**  
```
<?php

require_once "vendor/autoload.php";

while (true) {
    echo 'memory:', memory_get_usage() / 1024 / 1024, "\r\n";
    $client = new \GuzzleHttp\Client();
    try {
        $client->get('https://api.cmbchina.com/express/query');
    } catch (\Throwable $exception) {
        var_dump($exception->getCode());
    }
    sleep(1);
}

```

**Possible Solution**  

**Additional context**

**Comment by Nyholm** [comment]
Thank you for a good reproducible script. 

This will be fixed in promises 1.4.0
