### ISSUE TITLE
Faced with error guzzlehttp/psr7/src/Stream.php:225 Error: Allowed memory size

### ISSUE THREAD

**Issue by shubaivan** [guzzle/guzzle#2609]
**Guzzle version(s) affected**: "6.5.2"
**PHP version**:  7.3.14  (hint: `php --version`)
**cURL version**: 7.66.0 (hint: `php -i | grep cURL`)

**Description**  
I use Guzzle with stream condition for download many files in one execute command, this is example for each url

```
        $client = new Client();
        $response = $client->request(
            'GET',
            $url,
            ['stream' => true]
        );
```

and when third time script created request I faced with error about memory

```
PHP  12. fread() /var/www/symfony/vendor/guzzlehttp/psr7/src/Stream.php:225
14:48:49 CRITICAL  [php] Fatal Error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 94380004 bytes) ["exception" => Symfony\Component\ErrorHandler\Error\OutOfMemoryError^ { …}]

In Stream.php line 225:
                                                                                              
  Error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 94380004 bytes)  
```

**How to reproduce**  
example you have three url for download files, example approximately size 70mb each
and I run it by symfony console command which contain code like this

```
$response = $client->request('GET', 'some_url', ['stream' => true]);
$body = $response->getBody();
while (!$body->eof()) {
    echo $body->read(1024);
}
```

**Possible Solution**  
I don't have some suggestion about that

**Additional context**

**Comment by AhmedRaafat14** [comment]
I believe this is not Guzzle issue, it is the memory limitations configured in PHP itself you may need to change the `memory_limit` variable in your [`php.ini`](https://www.php.net/manual/en/ini.core.php#ini.memory-limit) to make it `-1` or the desiered size you want.

I hope this helps can you try it and see if it fixes the issue or not, otherwise I will look if it is an issue in the Guzzle itself.

**Comment by shubaivan** [comment]
I found issue about that and solution 
https://github.com/guzzle/guzzle/issues/2555#issuecomment-607926080

**Comment by gmponos** [comment]
> I found issue about that and solution

So this seems as a duplicate.. and the issue seems to be in PHP and not guzzle.. if I did not understood correctly feel free to comment and we can reopen.
