### ISSUE TITLE
How to implement proxy in guzzle ?

### ISSUE THREAD

**Issue by harshitsinghwap** [guzzle/guzzle#2611]
Please help me to implement proxy in a guzzle request beacuse there is so much confusion as official document didn't worked for me also Stackowerflow too. 
I didn't get any "worked" example on the internet.
So please show me a working example on how to implement proxy in a guzzle(latest version) request.

**Comment by azarecki** [comment]
The simplest example of how to implement proxy:
```
<?php
require __DIR__ . '/vendor/autoload.php';

$client = new \GuzzleHttp\Client([
    \GuzzleHttp\RequestOptions::PROXY => 'http://user:pass@proxy:1234'
]);
$response = $client->request('GET', 'https://google.com');
```
