### ISSUE TITLE
Readme: Build badge uses wrong style and links to image instead of build overview

### ISSUE THREAD

**Issue by pixelbrackets** [guzzle/guzzle#2614]
Guzzle Readme https://github.com/guzzle/guzzle/blob/master/README.md

**Description**  
The build badge has a different style than the other badges. It was tried to appaly the shields style to the GitHub badge URL, but this wont work. The image is linked by default to the image itself. Which is not useful. 

**How to reproduce**  
Open project on GitHub and hover the badges.

**Possible Solution**  
Use shields.io for the workflow badge. They now offer a badge for this service.

Add a link to the workflow page.

**Additional context**  

![Bildschirmfoto von 2020-04-17 11-48-54](https://user-images.githubusercontent.com/1592995/79556548-894f7f80-80a1-11ea-9690-3d7747e39664.png)

**Comment by Nyholm** [comment]
Thank you @pixelbrackets 
Your commit was merged. I had to rebase it first and I could't not force push to your fork. That is why I opened an new PR.
