### ISSUE TITLE
Remove additional message in exception messages?

### ISSUE THREAD

**Issue by zkwbbr** [guzzle/guzzle#2619]
**Description**

Is it possible to remove additional message that Guzzle adds in exception messages?

**Example**
```
try {
   $res = $client->request('POST', 'https://example.com', $data);
} catch (\GuzzleHttp\Exception\RequestException $ex) {
	echo $ex->getMessage();
	exit;
}
```
The exception message in this example has an additional message provided by Guzzle, on top of the original e.g.,

> Client error: `POST http://example.com` resulted in a `400 Bad Request` response: "original exception message goes here"

**Additional context**

It would be nice if Guzzle did not add any message to the original. It would save the developer additional parsing code if the developer only wants the original exception message.

**Comment by mfn** [comment]
> wants the original exception message

There's no "original exception", this is _the_ exception.

What you refer to is the response albeit "summarized" which happens via `\GuzzleHttp\Psr7\get_message_body_summary`.

However this is a `RequestException` which means it can contain the `$response` and what you want it `$ex->getResponse()` and then is if it's non-null and access the body. Or just call `\GuzzleHttp\Exception\RequestException::getResponseBodySummary` with this response manually _to get exactly_ the summary.

**Comment by zkwbbr** [comment]
@mfn You are right, that confused for a bit. Thanks!
