### ISSUE TITLE
Catching errors on Guzzle with Proxies that are broken or dead

### ISSUE THREAD

**Issue by spooksie** [guzzle/guzzle#2622]
I'm using Guzzle to grab .json requests with proxies. However, I have a pool of proxies that I use and will randomly select one from the bunch. It randomizes the proxy for every request. 

The problem I'm having is that a small number of my proxies are broken or dead. Whilst most of the time its all good, sometimes I get these errors. 

```
cURL error 56: Received HTTP code 503 from proxy after CONNECT (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)

cURL error 56: Proxy CONNECT aborted (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)

cURL error 35: OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to www.mywebsite.com:443 (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)
```
I'm using the following code

``` 
// for example which randomizes on every request
$proxy = 'http://1.1.1.1:10101';
                    
try {
$request = $client->request('GET', 'https://the.url.com', ['proxy' => $proxy, 'http_errors' => false]);

if ($request->getStatusCode() == 200) {
                $json = json_decode($request->getBody(), true);
                if (isset($json['data'])) {
                        // do my thing
                    
                } else {
                    // run the script again
                }

} catch (BadResponseException $e) {
// run the script again
}
```

I've tried to fix it with try/catch too. But it always breaks the code with the error message. 

What am I missing?

**Comment by GrahamCampbell** [comment]
You can't use catch blocks to catch errors. You can only catch exceptions. You will need to silence the call to json_decode to stop the error being raised and then inspect the last json error.

**Comment by spooksie** [comment]
> You will need to silence the call to json_decode to stop the error being raised and then inspect the last json error.

How? thanks in advance

**Comment by Art4** [comment]
> > You will need to silence the call to json_decode to stop the error being raised and then inspect the last json error.
> 
> How? thanks in advance

```php
$json = @json_decode($string);

if ($json === null) {
    var_dump(json_last_error_msg());
}
```

https://www.php.net/manual/en/function.json-last-error-msg.php

Since PHP 7.3 you could also use the `JSON_THROW_ON_ERROR` option:

```php
try {
    $json = json_decode($string, true, 512, JSON_THROW_ON_ERROR);
} catch (\JsonException $e) {
    var_dump($e->getMessage());
}
```
https://www.php.net/manual/en/json.constants.php#constant.json-throw-on-error
