### ISSUE TITLE
Fatal error: Uncaught Error: Call to undefined function idn_to_ascii()

### ISSUE THREAD

**Issue by marekdedic** [guzzle/guzzle#2627]
## Description
Hi,
I'm maintaining a WordPress plugin which uses the Google API client library for PHP, which in turn uses Guzzle 6. Recently, some of the users have seen the following error:

```
Fatal error: Uncaught Error: Call to undefined function idn_to_ascii() in /........../vendor/guzzlehttp/guzzle/src/Utils.php:35
```

## Affected versions

From what I have been able to gather about this (by looking at the source and communicating with the users in question), this issue was introduced some time between `guzzlehttp/guzzle` versions `6.4.1` and `6.5.3`.

**Guzzle version(s) affected**: 6.5.3
**PHP version**: 7.3.17
**cURL version**: TBD

## Investigation

I've asked the users about the exact PHP version they're using and will update this issue with that information one I have it available. I have also asked them, whether they have the `intl` extension enabled as the [PHP docs](https://www.php.net/manual/en/function.idn-to-ascii.php) list it as necessary. However, http://docs.guzzlephp.org/en/stable/overview.html does **not** list the extension in the "Requirements" section, which is the reason I am filing this as a bug with Guzzle instead of just telling the users to enable it. Also, the `composer.json` does **not** list `ext-intl` in the `require` section.

If you have any follow-up questions, I'd be happy to help.

**Comment by GrahamCampbell** [comment]
This is because we require the symfony polyfill.

**Comment by GrahamCampbell** [comment]
Are you loading Guzzle using the phar or via composer?

**Comment by GrahamCampbell** [comment]
> does not list the extension in the "Requirements" section

Yeh, it is not a requirement to have the extension.

**Comment by marekdedic** [comment]
Hi, thanks for the response.

Ok, if there is a polyfill, that's great. However, I don't see it in `composer.json` - am I missing something

**Comment by marekdedic** [comment]
Oh, I see it, it's there in version `6.5.3`

**Comment by marekdedic** [comment]
Thanks,
with the polyfill in place, it now works.

**Comment by GrahamCampbell** [comment]
What caused the polyfill to not be in place?

**Comment by marekdedic** [comment]
My oversight :D

For the WordPress plugin I strip parts of the vendor dir because the google api services are huge...

Upon update of guzzle, the polyfill did not get added and since it didn't error out for me, I didn't notice.
