### ISSUE TITLE
Guzzle post is not working with external ip. Throws Failed to connect to 37.XX.XX.XXX port 80: Connection timed out

### ISSUE THREAD

**Issue by dhara15101991** [guzzle/guzzle#2628]
**Guzzle version(s) affected**: 6.3
**PHP version**: 7.2.24
**cURL version**: 7.58.0

**Description**  
Using guzzle in laravel project.
Everything is working properly when it is on local IP. Port 80 is open for the connections.
But when external (static)l IP is used it shows me the following error
`Failed to connect to 37.XX.XX.XXX port 80: Connection timed out`

Although when the same URL is used directly to the browser or postman then it works with external IP. I have done a google and tried but nothing works.

Can anyone help me? I have spent lots of time to solve but nothing works.

**Comment by earlofpudding** [comment]
Could you post the code you are using to send the POST request to the external ip? 

What data are you sending in the POST request? How are you sending it?

**Comment by Nyholm** [comment]
This is not a guzzle issue. 

Ask in a support forum like StackOverflow.
