### ISSUE TITLE
MessageFormatter::$template without file content when logging {req_body}?

### ISSUE THREAD

**Issue by pfdtk** [guzzle/guzzle#2632]
Is there any way `MessageFormatter::$template` log without file content when logging `{req_body}` ?
because file may be too large, i dont want to log the content.

**Comment by gmponos** [comment]
Are you talking about passing your own template on the constructor?

https://github.com/guzzle/guzzle/blob/master/src/MessageFormatter.php#L54

**Comment by pfdtk** [comment]
@gmponos 
Yes, my template is:
```
new MessageFormatter("URL: {url}\nRequest Header: {req_headers}\nRequest Body: {req_body}\nResponse Header: {res_headers}\nResponse Content: {res_body}")
```

**Comment by gmponos** [comment]
Why don't you simply remove `Content: {res_body}` or `Request Body: {req_body}`

**Comment by pfdtk** [comment]
@gmponos 
Because `req_body` also has some params I need to log.

**Comment by gmponos** [comment]
Is it possible you could describe in more details your use case.. Out of the context you have I can not understand what you need. Guzzles message formatter either logs the body or not. It can not log "some" info of the body.

Please note we use GitHub issues only to discuss bugs and new features/ideas. If this is a support question better to be addressed to other channels like stackoverflow.
