### ISSUE TITLE
E_DEPRECATED: idn_to_ascii(): INTL_IDNA_VARIANT_2003 is deprecated  or  IDN conversion failed

### ISSUE THREAD

**Issue by runphp** [guzzle/guzzle#2634]
**Guzzle version(s) affected**: 6.5.3
**PHP version**:7.3.13 (hint: `php --version`)
**cURL version**:7.19.7 (hint: `php -i | grep cURL`)

**Description**  
when "symfony/polyfill-intl-idn":"v1.16.0" 
error IDN conversion failed

**How to reproduce**  

error IDN conversion failed
```
$uri = \GuzzleHttp\Psr7\uri_for('https://api.eelly.com/live/live/getStoreLive?tpl=1');

\GuzzleHttp\Utils::idnUriConvert($uri,IDNA_DEFAULT);
```

I found https://github.com/symfony/polyfill-intl-idn/blob/ab0af41deab94ec8dceb3d1fb408bdd038eba4dc/bootstrap.php#L81

```
if (!defined('INTL_IDNA_VARIANT_UTS46')) {
    define('INTL_IDNA_VARIANT_UTS46', 1);
}
```
but guzzle/src/Utils.php
```
$idnaVariant = defined('INTL_IDNA_VARIANT_UTS46') ? INTL_IDNA_VARIANT_UTS46 : 0;
```
when idnaVariant  = 0   

error 
NOTICE: E_DEPRECATED: idn_to_ascii(): INTL_IDNA_VARIANT_2003 is deprecated

**Possible Solution**  

**Additional context**

**Comment by GrahamCampbell** [comment]
Please check existing bug reports before posting. There is already an issue for this https://github.com/guzzle/guzzle/issues/2620 and a fix: https://github.com/guzzle/guzzle/issues/2620.

**Comment by runphp** [comment]
@GrahamCampbell 
https://github.com/guzzle/guzzle/blob/44de375f467fad2710f8e073f201c39d9681f093/src/Utils.php

Did this fix the problem

What version？

thx
