### ISSUE TITLE
IDN conversion fails with domains containing multiple hyphens

### ISSUE THREAD

**Issue by Rudloff** [guzzle/guzzle#2640]
**Guzzle version(s) affected**: 6.5.3
**PHP version**: 7.3.14
**cURL version**: 7.64.0

**Description**  
With some domains containing multiple hyphens, IDN conversion fails with this error:
```
PHP Fatal error:  Uncaught GuzzleHttp\Exception\InvalidArgumentException: IDN conversion failed (errors: IDNA_ERROR_HYPHEN_3_4) in /home/pierre/www/alltube/vendor/guzzlehttp/guzzle/src/Utils.php:56
```

**How to reproduce**  
```php
<?php

use GuzzleHttp\Client;

require_once __DIR__ . '/vendor/autoload.php';

$client = new Client();
$client->get('https://r3---sn-25glene6.example.com/');
```

**Possible Solution**  
The workaround I am using:
```php
$client = new Client(['idn_conversion' => false]);
```

**Comment by GrahamCampbell** [comment]
I think this may already be fixed in the latest polyfill version. Please update all your dependencies.

**Comment by GrahamCampbell** [comment]
I think https://github.com/guzzle/guzzle/pull/2626 should fix your problem. Can you confirm please?

**Comment by Rudloff** [comment]
I am using symfony/polyfill-intl-idn 1.17.0.

66061654fffa535004625a27bceb847f8f24de42 does indeed fix the issue.

**Comment by GrahamCampbell** [comment]
Great, thanks for confirming.

**Comment by Nyholm** [comment]
Thank you. 

#2626 has been merged.
