### ISSUE TITLE
Request to an external API using Guzzle randomly returns Server error: 504 but it works using cURL

### ISSUE THREAD

**Issue by tonyjesus** [guzzle/guzzle#2642]
**Guzzle version(s) affected**: 6.0.2
**PHP version**: 7.0.0
**cURL version**: 7.35.0

**Description**  
I'm giving some maintenance to an old system built on top of Laravel 5.1 (currently providing only bug fixes).

This system needs to make a request to an external API and uses GuzzleHttp (6.0.2) in order to achieve that. This has worked for several years but last week it started to randomly return Server **Error 504** in some cases.

I've contacted the company that developed and maintains the external API and they say on their logs they can see my requests as being **Error 408** (so a client error).

I've made some tests and tried to make the exact same requests using cURL and all worked properly.

**Code using Guzzle**  
`$client = new GuzzleHttp\Client();`
`$response = $client->get('https://example.com/user/1')->getBody();`

With this code, sometimes it manages to make a few requests before it fails (with 504), sometimes it fails immediately on the first attempt.

**Code using cURL**  
`$curl = curl_init();`
`curl_setopt_array($curl, [`
`    CURLOPT_RETURNTRANSFER => 1,`
`    CURLOPT_URL => 'https://example.com/user/1'`
`]);`
`$result = curl_exec($curl);`

With this code, works 100% of the times.

As stated, nothing changed recently. The only maintenance given to this system is related to bug fixes (latest update was almost 2 years ago). Also, the guys who developed the external API also said that nothing changed on their side.

Any hint of what could have caused this problem suddenly?

Thanks in advance

**Comment by bram1028** [comment]
I just ran into a similar issue with NameSIlo's API. It's returning empty response bodies.

I tracked it down to the User-Agent being used. Try overriding it to remove `GuzzleHttp/Guzzle`

```
[
    'User-Agent' => 'curl/' . curl_version()['version'] . ' PHP/' . PHP_VERSION,
]
```

**Comment by mfn** [comment]
I had this in the (distant past) too: server would truly return errornous responses based on the user-agent; try to unset or match it

**Comment by tonyjesus** [comment]
Hey guys, 

Thanks for your replies. I've just tried to set the user agent to something different, and I've even tried to unset it and still have the same behaviour. Some requests work, some requests fail.

**Comment by Nyholm** [comment]
Are you sure it is the client? 
Maybe there is a server issue. I mean, 5xx suggest a server issue.

**Comment by tonyjesus** [comment]
I totally agree with you. I was almost convinced that it was something related to the server. However, after they said that nothing changed on their side and testing performing all the requests using cURL and confirming that they all worked it made me think it could be Guzzle related. I'm not sure where to look at

**Comment by Nyholm** [comment]
I would suggest to ask the server maintainers why they answer 5xx. That is definitely and issue on their side. If guzzle caused it, they should return 4xx. 

So ask them to fix their issue first. After that you know if there is an issue with guzzle (or your app).

**Comment by tonyjesus** [comment]
Thanks for your reply @Nyholm.
I've already talked to them and they say that on their side the requests are being logged as **408**. So, on my side I get:

`[GuzzleHttp\Exception\ServerException]`  
`Server error: 504`

However, on their side they only see 408

**Comment by fatihsari** [comment]
> I just ran into a similar issue with NameSIlo's API. It's returning empty response bodies.
> 
> I tracked it down to the User-Agent being used. Try overriding it to remove `GuzzleHttp/Guzzle`
> 
> ```
> [
>     'User-Agent' => 'curl/' . curl_version()['version'] . ' PHP/' . PHP_VERSION,
> ]
> ```

I was hesitant to google it :) Thanks!
