### ISSUE TITLE
Remove composer normalize from dev deps and use a phar

### ISSUE THREAD

**Issue by gmponos** [guzzle/guzzle#2643]
The https://github.com/ergebnis/composer-normalize/releases now distributes a phar. When we have added that I think it was not.

I am not that familiar with GH actions to perform the change. Will try to learn it as well.. until then maybe someone can give it a shot.

**Comment by gmponos** [comment]
I discovered this.. https://github.com/ergebnis/composer-normalize-action

might give it a try later...

**Comment by Nyholm** [comment]
Yes please. Any solution is okey. We use the phar at AsyncAws: https://github.com/async-aws/aws/blob/master/.github/workflows/checks.yml#L6
