### ISSUE TITLE
What is the fastest way to send 100,000 HTTP requests and retrieve data from them?

### ISSUE THREAD

**Issue by oleksandr-roskovynskyi** [guzzle/guzzle#2647]
Need to get numerical values from a large list of profiles on the REST API + JWT, aggregation method API system where you need to get data there.

**Comment by gmponos** [comment]
Hi.. We use GitHub issues only to discuss bugs and new features. Please use stackoverflow or another channel of communication for these kind of questions. https://stackoverflow.com/questions/tagged/guzzle
