### ISSUE TITLE
default header are ignored

### ISSUE THREAD

**Issue by weichenlin** [guzzle/guzzle#2657]
**Guzzle version(s) affected**: 6.5.3
**PHP version**: 7.2.7
**cURL version**: 7.58.0

**Description**  
when given any array as header to the `request()` method
the default header that passed into Client constructor are ignored
even if it's empty array

**How to reproduce**  
```php
$client = new GuzzleHttp\Client(['headers' => ['X-Foo' => 'Bar']]);
$client->request('GET', '/get', ['headers' => []]);
```
set break point at Client.php line 159, the variable `$header` are empty
but it should apply the default headers

**Comment by gmponos** [comment]
Options per request have precedence and they are not supposed to be "merged". Have you found anything in the code or in the docs saying otherwise?

**Comment by weichenlin** [comment]
from request-options.rst:
> When headers are used as default options, they are only applied if the request being created does not already contain the specific header

I think an empty header array didn't contains any `specific header`, so the default header should be applied. But I'm not sure if I misunderstood.

**Comment by Nyholm** [comment]
Hm. I would assume they were being merged. 

Is it a special case when you pass an empty header array?

**Comment by GrahamCampbell** [comment]
Yeh, they are merged. In order to remove a header, you need to pass it as null, I think?

**Comment by GrahamCampbell** [comment]
The reason they are merged, is so you can have things like authentication and user agents set by default. You wouldn't expect them to be deleted if you don't then specify them again!

**Comment by Nyholm** [comment]
Can someone link or provide a test to this?

I want to make sure we can close this.

**Comment by arnegroskurth** [comment]
We have also stumbled over this and would expect out default `Authorization` header to be kept when setting an additional `Content-Type` header for a specific API route.

**Comment by fmarencic** [comment]
This still happens and has not been fixed.
