### ISSUE TITLE
Extract some of the middlewares to separate packages

### ISSUE THREAD

**Issue by gmponos** [guzzle/guzzle#2659]
My idea is that if we extract various middlewares that are inside this package to separate package we reduce the chances to introduce breaking changes to the http client package.

Middlewares that can be extracted:
- LoggerMiddleware
- RetryMiddleware

Also maybe we could reboot some
- OAuth middleware (https://github.com/guzzle/oauth-subscriber)
- Cache Middleware  (https://github.com/guzzle/cache-subscriber)

And even create some new
- Stopwatch middleware (for sf)

**Comment by GrahamCampbell** [comment]
Work for no gain? Not like we need to make breaking changes to them often?

**Comment by gmponos** [comment]
> Work for no gain?

Do you mean extracting or rebooting? which part exactly? I believe here it fits the "divide and rule" phrase.
