### ISSUE TITLE
IDN conversion failed when using Laravel Socialite

### ISSUE THREAD

**Issue by himanshugunv** [guzzle/guzzle#2668]
**Guzzle version(s) affected**: 6.5.4
**PHP version**: 7.3.18
**cURL version**: 7.70.0

**Description**  
I'm trying to use [Laravel Socialite](https://laravel.com/docs/7.x/socialite) (4.3.2) in Laravel (7.13.0) but getting this issue

```
GuzzleHttp\Exception\InvalidArgumentException
IDN conversion failed
```
![image](https://user-images.githubusercontent.com/65996043/82987104-a1a5a900-a014-11ea-8ad7-5c94aeae00a3.png)

Let me know how can i solve this issue.

**Comment by gmponos** [comment]
Can you check again which version of guzzle you have.

The error says that the exception is throw on line Utils::56 which is the line on guzzle 6.5.3 and not 6.5.4 that you are mentioning.

**Comment by himanshugunv** [comment]
Here as i checked

```
{
            "name": "guzzlehttp/guzzle",
            "version": "6.5.4",
            "source": {
                "type": "git",
                "url": "https://github.com/guzzle/guzzle.git",
                "reference": "a4a1b6930528a8f7ee03518e6442ec7a44155d9d"
            },
            "dist": {
                "type": "zip",
                "url": "https://api.github.com/repos/guzzle/guzzle/zipball/a4a1b6930528a8f7ee03518e6442ec7a44155d9d",
                "reference": "a4a1b6930528a8f7ee03518e6442ec7a44155d9d",
                "shasum": ""
            },
            "require": {
                "ext-json": "*",
                "guzzlehttp/promises": "^1.0",
                "guzzlehttp/psr7": "^1.6.1",
                "php": ">=5.5",
                "symfony/polyfill-intl-idn": "1.17.0"
            },
            "require-dev": {
                "ext-curl": "*",
                "phpunit/phpunit": "^4.8.35 || ^5.7 || ^6.4 || ^7.0",
                "psr/log": "^1.1"
            },
            "suggest": {
                "psr/log": "Required for using the Log middleware"
            },
            "type": "library",
            "extra": {
                "branch-alias": {
                    "dev-master": "6.5-dev"
                }
            },
            "autoload": {
                "psr-4": {
                    "GuzzleHttp\\": "src/"
                },
                "files": [
                    "src/functions_include.php"
                ]
            },
            "notification-url": "https://packagist.org/downloads/",
            "license": [
                "MIT"
            ],
            "authors": [
                {
                    "name": "Michael Dowling",
                    "email": "mtdowling@gmail.com",
                    "homepage": "https://github.com/mtdowling"
                }
            ],
            "description": "Guzzle is a PHP HTTP client library",
            "homepage": "http://guzzlephp.org/",
            "keywords": [
                "client",
                "curl",
                "framework",
                "http",
                "http client",
                "rest",
                "web service"
            ],
            "time": "2020-05-25T19:35:05+00:00"
        }
```

**Comment by GrahamCampbell** [comment]
Is definitely the installed version? Can you restart php-fpm and show us your `vendor/installed.json` file?

**Comment by GrahamCampbell** [comment]
The stack trace you showed us is **not** from Guzzle 6.5.4, it's from 6.5.3.

**Comment by gmponos** [comment]
or maybe the screenshot is wrong.... but for now the SS shows that the version used is 6.5.3

**Comment by himanshugunv** [comment]
I'm just downgrade the Guzzle version to 6.4.1 as found somewhere and now its works.

**Comment by himanshugunv** [comment]
> Is definitely the installed version (and not just the locked version)? Can you restart php-fpm and show us your `vendor/installed.json` file?


![image](https://user-images.githubusercontent.com/65996043/83000691-51d0dd00-a028-11ea-992e-792e1489137c.png)

**Comment by GrahamCampbell** [comment]
Please upgrade to Guzzle 6.5.4. Telling us an old version works is not helpful. We need the latest version to work.

**Comment by himanshugunv** [comment]
> Please upgrade to Guzzle 6.5.4. Telling us an old version works is not helpful. We need the latest version to work.

I have both versions installed separately, and with Guzzle 6.5.4 I'm not able to run this, 
I don't know how you guys are saying is 6.5.3 not 6.5.4 but what i can see in `vendor/composer/installed.json` or in `composer.lock` version mentioned is 6.5.4

**Comment by GrahamCampbell** [comment]
Do you have any globally installed dependencies?

**Comment by himanshugunv** [comment]
I just completely remove package and installed again all dependencies and it got worked, so it could be some unmet-dependency issue.

Its working now
Thanks everyone!!
