### ISSUE TITLE
cURL error 60 in Laravel project v.5.8.18

### ISSUE THREAD

**Issue by mcfoi** [guzzle/guzzle#2680]
**Guzzle version(s) affected**: 6.3.3
**PHP version**: 7.3.5
**cURL version**: 7.19.7

**Description**  
In a Laravel v5.8.18 project, all Guzzle calls to URL - **even on plain HTTP protocol** - are aborted by a GuzzleHttp\\Exception\\RequestException blaiming for "**cURL error 60: SSL certificate problem: certificate has expired**"

**Additional context**  
The Laravel project relying on Guzzle is on a shared host. The app was successfully in production since July 2019.
The issue appeared without any change in the app itself.
While in SSH on the shared host, cURL commands equivalent to those executed by Guzzle do succeed.
The same happens using Postman from Desktop: the endpoints do reply successfully, both in HTTP and HTTPS.
All SSL certificates are valid and have not been touched since a while (they have not just be replaced): the **"cURL error 60: SSL certificate problem: certificate has expired" is completely misleading**.

**Conclusion-Question**
Can any change to the server policy or any update of the cURL tool (now at version 7.19.7) be tha cause of an incompatibility between Guzzle and cURL?

I can see no reason Guzzle complaining about certificates while quering plain HTTPS enpoints!

**Comment by gmponos** [comment]
Have you tried `debug => true` in order to see what curl does in more details?

**Comment by mcfoi** [comment]
I enabled debug in Client setup ad I am getting this:

*   Trying 3.124.173.111...
* TCP_NODELAY set
* Connected to smartscouting.cassandratech.it (3.124.173.111) port 443 (#0)
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
* SSL certificate problem: certificate has expired
* Closing connection 0
{
    "message": "cURL error 60: SSL certificate problem: certificate has expired (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)",
    "exception": "GuzzleHttp\\Exception\\RequestException",
....

Note that with browser you can reach the App at:
https://smartscouting.cassandratech.it/api/v1/wps/version/
and you can see the certificate is valid!

**Comment by gmponos** [comment]
Well.. as we understand now we are kind of sure that this is a native error thrown by cURL.

Could it be that your cURL has set [verify](http://docs.guzzlephp.org/en/stable/request-options.html#verify) as false? 

And the same could be for your postman.. Guzzle sets the verify to true by default.

Also you can enable the `debug` from your curl script as well.. 

```
curl_setopt($curlhandle, CURLOPT_VERBOSE, true);
```

**Comment by mcfoi** [comment]
I checked  setting something like
```
$​guzzleClient​ = ​new​ ​Client​([
    ​'verify'​ => ​false
]);
```
and this works.
Does this mean there is something wrong with the Certificate chain both Postman and Chrome do not detect as they do not seek in the Certificates detal?

**Comment by mcfoi** [comment]
Further investigations and study allowed me to shed some light on the topic.
The issue is caused by the fact that despite the certificate isvalid, it refers to other authorities to demonstrate this. The resulting chain might not be wholly known to the client (cURL). This ultimately makes the verification fail.

This is does not happen in browsers as they are loaded with certificates of Authorities so can traverse even CA chains that do not provide full details of each intermediate CA.
On servers this can happen much easier.

Using **Firefox** to browse to the target website allows to i**nspect the certificate** and to **Download the PEM (chain) file**. This pem file, copied to the server, can be used to instruct cURL how to run across the whole chain of Certification Authorities:

```
$​guzzleClient​ = ​new​ ​Client​([
    ​'verify'​ => ​'/absolute/server/path/to/file/ca-chain.pem'
]);
```

**Comment by mcfoi** [comment]
CLOSING ISSUE
The issue was not related with Guzzle nor with cURL but rather to a rare event of an expired Root Certificate of a trusted CA, not bein correctly handeld by Server maintainer not having updated the Certificata chain.

**Comment by deress** [comment]
so how you get pass that error sir? I got the same error too
