### ISSUE TITLE
Guzzle v3.x cacert.pem outdated

### ISSUE THREAD

**Issue by igor875126** [guzzle/guzzle#2693]
**Guzzle version(s) affected**: 3.x

**Description**  
Some of our projects are using libraries that use guzzle 3.x version. At 1. Juni 2020 sectigo certificate has expired and guzzle is not able to validate our (fresh, working) certificate. Please see: https://support.sectigo.com/articles/Knowledge/Sectigo-AddTrust-External-CA-Root-Expiring-May-30-2020 

**How to reproduce**  
Try to make a SSL connection using Guzzle3 to e.g. https://meloman.kz website, you will see that guzzle is complaining about not valid certificate (but it's not)

**Possible Solution**  
Please update the cacert.pem + cacert.pem.md5 files with new certificates, you can take them from here: https://curl.haxx.se/docs/caextract.html

**Comment by GrahamCampbell** [comment]
Guzzle 3 is no longer maintained. Please upgrade to Guzzle 7.

**Comment by GrahamCampbell** [comment]
Note that the out of date CA file doesn't matter if you are using a version of PHP which doesn't have known security policies (ie PHP 7), since it is only used on old versions of PHP.

**Comment by GrahamCampbell** [comment]
NB You don't have to use Guzzle's bundled CA file. You can provide on at runtime.

**Comment by gmponos** [comment]
Closing for the reasons Graham mentions.. 

as an alternative you can clone the project.. although I suggest updating as well..
