### ISSUE TITLE
Support PHP 8

### ISSUE THREAD

**Issue by Nyholm** [guzzle/guzzle#2702]
We currently do not support PHP 8. We need to update CI config, update composer.json and make sure that we handle the new resource object in PHP 8.

**Comment by GrahamCampbell** [comment]
I imagine phpstan might start to work against us here, lol. We'll have to be careful our types and phpdoc are accurate.

**Comment by Nyholm** [comment]
This is fixed in master.

**Comment by loading84** [comment]
Hello, 
![chybaroundcube](https://user-images.githubusercontent.com/15268574/113609507-2a856c00-964c-11eb-8e51-6ea45353d878.jpg)
I am installing a roundcube and it reports an error, see a screenshot, can you please advise me? I use php 8 in my linux server. Thanks.
