### ISSUE TITLE
Curl error 7 on redirect

### ISSUE THREAD

**Issue by Driky** [guzzle/guzzle#2717]
**Guzzle version(s) affected**:6.5.3
**PHP version**: 7.4.6
**cURL version**: 7.67.0

**Description**
App in a docker container calling another app also in a docker container.  
On a request with a session cookie I get the following error:
```
cURL error 7: Failed to connect to tesla.localhost port 8181: Connection refused (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) (GuzzleHttp\Exception\ConnectException)
```

Until the cookiejar was added I didn't get that error. 

**How to reproduce**  
```
$this->httpClient->send($appRequest->getRequest(), $appRequest->getOptions());
```

In `$appRequest->getOptions()` an instance of CookieJar is found. It is used to keep the session cookie.

**Additional context**  
I'm smoke testing an old magento app before upgrading the php version (and making the change necessary for that).
I was able to test the REST API using the same step I'm taking now, minus the `CookieJar` that wasn't needed.

**Comment by gmponos** [comment]
Hi.. I fail to see how there is a connection of your error with the guzzle code having a bug...

**Comment by Driky** [comment]
Well,
No CookieJar -> The request return a response
CookieJar -> The request crash curl

There seems to be something going on with the way cookies are sent. If I use Postman to send the request everything is going fine.

If it's has nothing todo with Guzzl what would be the probable cause ? (real question I'm not trying to be sarcastic).
