### ISSUE TITLE
Not compatible with openstack identity api

### ISSUE THREAD

**Issue by antond1990** [guzzle/guzzle#2719]
**Guzzle version(s) affected**: 6.5.5
**PHP version**: 7.3.18
**cURL version**: hint don't works --> (hint: `php -i | grep cURL`)

**Description**  
Guzzle is not compatible to openstack identity api. See https://docs.openstack.org/api-ref/identity/v3/?expanded=password-authentication-with-unscoped-authorization-detail#password-authentication-with-unscoped-authorization

When `auth` is used in the options array I get the following error.

![grafik](https://user-images.githubusercontent.com/24891375/86221935-dbbf1900-bb85-11ea-960b-cb6ad03c8afd.png)

**How to reproduce**  
Try to authenticate on an openstack identity api endpoint (see docs https://docs.openstack.org/api-ref/identity/v3/?expanded=password-authentication-with-unscoped-authorization-detail#password-authentication-with-unscoped-authorization)

**Comment by GrahamCampbell** [comment]
I think you are not calling Guzzle correctly? What did you write for the username and password array keys? You need to not give them names.

**Comment by GrahamCampbell** [comment]
> cURL version: hint don't works --> (hint: php -i | grep cURL)

This means you don't have curl installed.

**Comment by GrahamCampbell** [comment]
Can you show us your code which specifies Authentication?

**Comment by antond1990** [comment]
Here is my code:

 ```
       $guzzle = new Client([
            'base_uri' => 'https://cloud.domain.de:5000/v3/',
        ]);

        $options = [
            'auth' => [
                'identity' => [
                    'methods' => [
                        'password',
                    ],
                    'password' => [
                        'user' => [
                            'name' => '',
                            'domain' => [
                                'name' => 'Default',
                            ],
                            'password' => '',
                        ]
                    ]
                ]
            ]
        ];
        $result = $guzzle->request('GET', '/auth/tokens', $options);
```

**Comment by antond1990** [comment]
> > cURL version: hint don't works --> (hint: php -i | grep cURL)
> 
> This means you don't have curl installed (which is fine, Guzzle doesn't need it).

**Comment by GrahamCampbell** [comment]
Yep, that code is incorrect. Guzzle's Basic auth format is:

```
       $options = [
           'auth' => ['username-here', 'password-here'],
       ];
```

You will need to work out what the username is meant to be.

**Comment by GrahamCampbell** [comment]
If you are trying to send a json payload, rather than set the Authorization header, you need to encode it yourself, and send it as the body.

**Comment by GrahamCampbell** [comment]
```pjp
      $guzzle = new Client([
           'base_uri' => 'https://cloud.domain.de:5000/v3/',
       ]);

       $json = [
           'auth' => [
               'identity' => [
                   'methods' => [
                       'password',
                   ],
                   'password' => [
                       'user' => [
                           'name' => '',
                           'domain' => [
                               'name' => 'Default',
                           ],
                           'password' => '',
                       ]
                   ]
               ]
           ]
       ];

       $result = $guzzle->request('GET', '/auth/tokens', ['json' => $json]);
```

**Comment by gmponos** [comment]
closing as explained by @GrahamCampbell this is more a problem of code rather than guzzle. Please refer to other communication channels for support.
