### ISSUE TITLE
Globally set or disable user agent string

### ISSUE THREAD

**Issue by rkuntoro** [guzzle/guzzle#2722]
**Description**
The default user agent contains some sensitive information like the versions of Guzzle, CURL, and PHP. I would like to omit this or set my own user agent.

I can control the Guzzle user agent of my app (through header option), but there are lots of composer dependencies that is out of my control.

There should be an easy way to globally set the default user agent without maintaining a fork.

**Example**

```
function default_user_agent()
{
    if (defined('GUZZLE_DEFAULT_USER_AGENT')) {
        return GUZZLE_DEFAULT_USER_AGENT;
    }
   ...
```

**Comment by gmponos** [comment]
In Guzzle 7 we removed a lot of these sensitive info.

Furthermore you can set your own header on constructing the client

```
$client = new Client([
    'headers' => [ 'User-Agent' => ''],
]);
```

**Comment by rkuntoro** [comment]
@gmponos Thanks for the info.

I know that I can set my own header, but I just have no controls over what other libraries do that we include via composer. This is especially for many integration SDKs that sends requests using Guzzle.

Any chance this can get added to v6? Unfortunately we're not using PHP 7.2 yet.

**Comment by GrahamCampbell** [comment]
You should be able to pass a Guzzle client instance to the libraries you are using. If they don't support this, suggest they add it (and possibly send a PR to implement it).

**Comment by GrahamCampbell** [comment]
I think we didn't implement this user agent change on Guzzle 6 because we considered it to be a breaking change.

**Comment by GrahamCampbell** [comment]
Is there a library in particular you had in mind?

**Comment by rkuntoro** [comment]
A few that we use and dependencies of the libraries we included:

- https://github.com/IsraelOrtuno/pipedrive
- https://github.com/HubSpot/hubspot-php (this one actually sets their own user agent)
- https://github.com/infusionsoft/infusionsoft-php
- https://github.com/egeloen/ivory-http-adapter
- https://github.com/php-http/guzzle6-adapter

**Comment by GrahamCampbell** [comment]
> https://github.com/php-http/guzzle6-adapter

You can certainly set the user agent header here. PSR requests let you do that.

**Comment by rkuntoro** [comment]
@GrahamCampbell Thanks. I closed the issue
