### ISSUE TITLE
Deprecation Notice: Class Guzzle\Tests\Common\Cache\NullCacheAdapterTest

### ISSUE THREAD

**Issue by CaddyDz** [guzzle/guzzle#2727]
**Guzzle version(s) affected**: 7.0
**PHP version**: 7.4.8
**cURL version**: 7.71.1

**Description**  
Many test classes throw a deprecation notice like so
> Deprecation Notice: Class Guzzle\Tests\Common\Cache\NullCacheAdapterTest located in ./vendor/guzzle/guzzle/tests/Guzzle/Tests/Cache/NullCacheAdapterTest.php does not comply with psr-0 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/local/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201

Some of those classes are:
* Guzzle\Tests\Parsers\UriTemplate\UriTemplateTest
* Guzzle\Tests\Parsers\UriTemplate\PeclUriTemplateTest
* Guzzle\Tests\Parsers\UriTemplate\AbstractUriTemplateTest
* Guzzle\Tests\Common\AbstractHasAdapterTest
* Guzzle\Tests\Http\CommaAggregatorTest
* Guzzle\Tests\Http\PhpAggregatorTest
* Guzzle\Tests\Http\DuplicateAggregatorTest
* Guzzle\Tests\Plugin\Redirect\RedirectPluginTest
* Guzzle\Tests\Http\Message\HttpRequestFactoryTest
* Guzzle\Tests\Message\ResponseTest
* Guzzle\Tests\Message\HeaderComparisonTest
* Guzzle\Tests\Plugin\Redirect\StaticClientTest
* Guzzle\Tests\Service\Command\ConcreteClassFactoryTest
* Guzzle\Tests\Service\Command\AliasFactoryTest
* Guzzle\Tests\Service\Command\MapFactoryTest
* Guzzle\Tests\Service\Command\ServiceDescriptionFactoryTest
* Guzzle\Tests\Service\Command\CompositeFactoryTest
* Guzzle\Tests\Service\Command\VisitorFlyweightTest
* Guzzle\Tests\Service\ServiceBuilderTest

**How to reproduce**  
`composer require vendor/package` on a project that uses guzzle

**Comment by GrahamCampbell** [comment]
Why are you trying to load Guzzle's tests? Are you sure you have loaded Guzzle 7.0.1?

**Comment by GrahamCampbell** [comment]
That error looks like it was generated by a Guzzle 3 install. Guzzle 3 is no longer supported.

**Comment by gmponos** [comment]
This is definitely not guzzle 7. @CaddyDz please note that only v6 & v7 are supported.

**Comment by CaddyDz** [comment]
Well this is just a plain Laravel 7 project, I didn't install Guzzle manually and `composer.json` states `"guzzlehttp/guzzle": "^7.0",`

**Comment by GrahamCampbell** [comment]
That warning is generated from `guzzle/guzzle:^3.0` though...

**Comment by GrahamCampbell** [comment]
A different package.

**Comment by GrahamCampbell** [comment]
You should run `composer why guzzle/guzzle`

**Comment by CaddyDz** [comment]
This is what I get
```
▶ composer why guzzle/guzzle
guzzle/guzzle         v3.8.1  replaces  guzzle/batch (self.version)
guzzle/guzzle         v3.8.1  replaces  guzzle/cache (self.version)
guzzle/guzzle         v3.8.1  replaces  guzzle/common (self.version)
guzzle/guzzle         v3.8.1  replaces  guzzle/http (self.version)
guzzle/guzzle         v3.8.1  replaces  guzzle/inflection (self.version)
guzzle/guzzle         v3.8.1  replaces  guzzle/iterator (self.version)
guzzle/guzzle         v3.8.1  replaces  guzzle/log (self.version)
guzzle/guzzle         v3.8.1  replaces  guzzle/parser (self.version)
guzzle/guzzle         v3.8.1  replaces  guzzle/plugin (self.version)
guzzle/guzzle         v3.8.1  replaces  guzzle/plugin-async (self.version)
guzzle/guzzle         v3.8.1  replaces  guzzle/plugin-backoff (self.version)
guzzle/guzzle         v3.8.1  replaces  guzzle/plugin-cache (self.version)
guzzle/guzzle         v3.8.1  replaces  guzzle/plugin-cookie (self.version)
guzzle/guzzle         v3.8.1  replaces  guzzle/plugin-curlauth (self.version)
guzzle/guzzle         v3.8.1  replaces  guzzle/plugin-error-response (self.version)
guzzle/guzzle         v3.8.1  replaces  guzzle/plugin-history (self.version)
guzzle/guzzle         v3.8.1  replaces  guzzle/plugin-log (self.version)
guzzle/guzzle         v3.8.1  replaces  guzzle/plugin-md5 (self.version)
guzzle/guzzle         v3.8.1  replaces  guzzle/plugin-mock (self.version)
guzzle/guzzle         v3.8.1  replaces  guzzle/plugin-oauth (self.version)
guzzle/guzzle         v3.8.1  replaces  guzzle/service (self.version)
guzzle/guzzle         v3.8.1  replaces  guzzle/stream (self.version)
league/oauth1-client  1.6.2   requires  guzzle/guzzle (3.*)
```

**Comment by GrahamCampbell** [comment]
You need to upgrade `league/oauth1-client` to `^1.7`.

**Comment by CaddyDz** [comment]
That's a dependency in [laravel/socialite](https://github.com/laravel/socialite) defined [here](https://github.com/laravel/socialite/blob/4.0/composer.json#L23)

Guess I'll just fork it and fix that, thanks

**Comment by GrahamCampbell** [comment]
You don't need to fix anything. Composer will already install the latest version of that package without you forcing to exclude the older versions unnecessarily.

**Comment by shehi** [comment]
Problem is, `league/oauth1-client` 1.7 doesn't support Guzzle 7.
