### ISSUE TITLE
Uncaught exception when using sink and fopen, closing resource before saving it

### ISSUE THREAD

**Issue by murilozilli** [guzzle/guzzle#2732]
**Guzzle version(s) affected**: 6.3-dev
**PHP version**: 7.3.14
**cURL version**: 7.66.0

**Description**  
Getting **Uncaught Exception: Invalid resource type: resource (closed)** when trying to save the response of a request directly to a file, one of the issues is that it only happens some times, this code works fine for most of the time.

The resource(closed)  should be the gettype only after fclose() so I am not sure what is going on.

**How to reproduce**  
```
        $client = new Client();
        $fn      = tempnam(sys_get_temp_dir(), 'some-prefix-');
        $fp      = fopen($fn, 'r+');
        $res = $client->request('GET', $url, ['sink' => $fp]);
        $stream = $res->getBody()->detach();
        $stat   = fstat($stream);
        fclose($fp);
```

**Possible Solution**  
Maybe it is related to something asycronous happening?

**Additional context**  
This is a code I have to upload files directly from a URL

**Comment by GrahamCampbell** [comment]
I don't think this is a bug in Guzzle. It's a bug in your code's 3rd line. You are not checking if fopen fails.

**Comment by murilozilli** [comment]
@GrahamCampbell cheers I will do that but having said that it works 99.9% of the time, can you foresee any reason why fopen wouldn't work here sporadically ? Also, if it fails what should be the correct handling? Just keep trying to open the file until it does? Seems odd

**Comment by bgreco** [comment]
I get the "Invalid resource type: resource (closed)" message when using the 'sink' option and the requested URL returns a 301 redirect.

**Comment by Chi-teck** [comment]
Can Guzzle throw more meaningful exception in this case?
 I would actually consider this as a bug, because per contract `GuzzleHttp\ClientInterface::request` can only throw `GuzzleException` not `InvalidArgumentException`.
