### ISSUE TITLE
Relative URL with Colon results in "Unable to parse URI"

### ISSUE THREAD

**Issue by Neokil** [guzzle/guzzle#2734]
# Summary
When instantiating a Guzzle-Client with a `base_uri` and then requesting a url which contains a colon the parsing fails with the Message "Unable to parse URI".

# Code-Example
```
$client = new GuzzleHttp\Client([
    'base_uri' => 'https://localhost/api'
]);
$client->get('/entity/Customer:123');
```
Error-Message:
```
PHP Fatal error:  Uncaught InvalidArgumentException: Unable to parse URI: /entity/Customer:123 in vendor/guzzlehttp/psr7/src/Uri.php:71
Stack trace:
#0 vendor/guzzlehttp/psr7/src/functions.php(59): GuzzleHttp\Psr7\Uri->__construct('/entity/Custo...')
#1 vendor/guzzlehttp/guzzle/src/Client.php(154): GuzzleHttp\Psr7\uri_for('/entity/Custo...')
#2 vendor/guzzlehttp/guzzle/src/Client.php(181): GuzzleHttp\Client->requestAsync('GET', '/entity/Custo...', Array)
#3 vendor/guzzlehttp/guzzle/src/ClientTrait.php(44): GuzzleHttp\Client->request('GET', '/entity/Custo...', Array)
#4 index.php(8): GuzzleHttp\Client->get('/entity/Custo...')
#5 {main}
  thrown in vendor/guzzlehttp/psr7/src/Uri.php on line 71

Fatal error: Uncaught InvalidArgumentException: Unable to parse URI: /entity/Customer:123 in vendor/guzzlehttp/psr7/src/Uri.php on line 71
```

# The Issue
The underlying  issue of this is the parsing of the URL.
The relative URL that is given to the `get`-Function is directly passed down into the "Psr7\uri_for"-Function [see here](https://github.com/guzzle/guzzle/blob/master/src/Client.php#L156) which is then using the php-function `parse_url` to parse the relative url.
Problem there is, that the function is not designed to validate relative URLs and therefore fails when a colon is present without having a scheme defined before that.

# A Solution
A solution to the issue would be quite simply to not validate the relative url on its own but only after merging it with the base-url.
As a quick solution I changed the `buildUri`-Function to simply concat the strings and it solved the issue:
### Before
```
    private function buildUri(UriInterface $uri, array $config): UriInterface
    {
        if (isset($config['base_uri'])) {
            $uri = Psr7\UriResolver::resolve(Psr7\uri_for($config['base_uri']), $uri);
        }
```
### After
```
private function buildUri(string $uri, array $config): UriInterface
    {
        if (isset($config['base_uri'])) {
            $uri = Psr7\uri_for($config['base_uri'] . $uri);
        }
...
```
Something more sophisticated than a concat will be required for the Urls but this Concept should solve the Bug easily.

**Comment by GrahamCampbell** [comment]
I don't agree this is a bug. I think you are calling Guzzle incorrectly. You need to escape the colon by encoding the URI first. Guzzle cannot automatically do that, and indeed should not, because then you'd break the code of people passing actual URIs.

**Comment by Neokil** [comment]
The Problem is that colons are valid URI Characters and will cause issues with the Target-API if escaped. 
Lets have an example with a more popular site, Wikipedia:
The Url I am trying to reach is `https://en.wikipedia.org/wiki/Template:Welcome`. And please correct me if I am wrong, but since I would want to do multiple Calls to wikipedia I would initialise the Client with a base_uri of `https://en.wikipedia.org` and then run into the same issue when calling `$client->get('/wiki/Template:Welcome');`. And calling `$client->get('/wiki/Template%2FWelcome');` does not work at all because the target Webserver does not unescape the Colon.

Yes, I get that `/wiki/Template:Welcome` in itself might not be a valid URI, but the URI that will be called in the End definitely is. So the validation is just done in the wrong place.

As an addition, when you are using an HTML-Hyperlink there is a similar issue:
`<a href="Template:Welcome">Welcome Template</a>` is invalid because it takes `Template` as the Scheme,
but `<a href="./Template:Welcome">Welcome Template</a>` is completely valid.
So it is not uncommon to have those partial URIs that only get valid if they are joined with their base-URI.

**Comment by gmponos** [comment]
Can you do something for us.

```
$uri = new Uri('replace_this_with_your_base')

$uri = $uri->withPath('your_semicolon_path');
```

and check if it works?

**Comment by Neokil** [comment]
@gmponos yes, that seems to work properly:
```
$uri = new GuzzleHttp\Psr7\Uri('https://localhost/api');
$uri = $uri->withPath('accounts/Customer:123');
var_dump($uri->__toString());
```
results in
```
index.php:12:
string(39) "https://localhost/accounts/Customer:123"

**Comment by Nyholm** [comment]
The colon is a reserved url character. If you don’t use it in the “reserved place” then you need to encode it. 

I agree it feels weird, but the current implementation is correct according to the RCF. 

Thank you Graham.

**Comment by chao** [comment]
The colon is not a reserved character in relative path, please check RCF 3986. It only says "the  first path segment cannot contain a colon (":") character." I believe "https://localhost/accounts/Customer:123" is a validate URL.

**Comment by jmvezic** [comment]
@Nyholm RFC @chao This is a bit of a confusing issue and in my opinion it should either be specifically documented or fixed.

For example:

```
$client->get('http://samplesite.com/api/some:thing');
```
works, but
```
$client = new GuzzleHttp\Client([
    'base_uri' => 'http://samplesite.com/api/'
]);
$client->get('some:thing');
```
doesn't, which is wildly inconsistent, and the documentation makes it seem like all Guzzle does is "merge" the base_uri with the given string in the get function for the purpose of being user-friendly and making it possible not to repeat the base_uri constantly. 

A colon is indeed a reserved character, but in my opinion, if Guzzle is to follow the RFC to the letter it should either:

A) Disallow URIs like this
```
$client->get('http://samplesite.com/api/some:thing');
```

B) Allow something like this
```
$client->get('./some:thing');
```
since the RFC states:

A path segment that contains a colon character (e.g., "this:that")
   cannot be used **as the first segment of a relative-path reference**, as
   it would be mistaken for a scheme name.  Such a segment must be
   preceded by a dot-segment (e.g., "./this:that") to make a relative-
   path reference.

The last sentence here is especially important. Also note that technically, the forward slash "/" is also a reserved character, but it's of course allowed in the relative path segment unencoded, like this:
```
$client->get('some/random/path');
```

**Comment by davedevelopment** [comment]
I just ran into this. Early enough for me to change my urls, but thought I'd mention that this is recorded against PHP's parse_url - https://bugs.php.net/bug.php?id=70942.

**Comment by eluz-helcim** [comment]
I am facing the same issue, and this is the way I solved:

```php

$url = $baseURL . '/api/v1/objects:record';

// get a PSR7 request object
$request = new GuzzleHttp\Psr7\Request('GET', $url);

$response = $client->send($request);

$textResponse = $response->getBody()->getContents();

```
