### ISSUE TITLE
Create request methods enumerator

### ISSUE THREAD

**Issue by xorock** [guzzle/guzzle#2743]
Isn't it a good idea to create a uniform enumerator with the names of the request methods? Similar to RequestOptions.

```php
final class RequestMethods
{
    public const POST = 'POST';

    public const GET = 'GET';
    //etc
}
```

This approach minimizes the risk of error and standardizes the code.

**Comment by Nyholm** [comment]
No. I don’t think so. It is a matter of taste. Feel free to create a separate class/package with this.
