### ISSUE TITLE
MAJOR_VERSION undefined class constant in src/utils.php

### ISSUE THREAD

**Issue by kradkahaddi** [guzzle/guzzle#2744]
**Guzzle version(s) affected**: *7.0.1
**PHP version**: 7.2.24
**cURL version**: 7.58.0

**Description**  
Getting an undefined class constant error when running the "vendor/bin/wp theme update -all" command from [this tutorial](https://cloud.google.com/community/tutorials/run-wordpress-on-appengine-standard)

**How to reproduce**  
On GAE standard environment, activate the GCS plugin on the live site and try to run any update on the local version. The error does not exist when GCS plugin is deactivated on live site during updates.

**Additional context**  
vendor/bin/wp theme update --all --path=my-wordpress-projectPHP Fatal error:  Uncaught Error: Undefined class constant 'MAJOR_VERSION' in /home/val-wp/vendor/guzzlehttp/guzzle/src/Utils.php:121

**Comment by GrahamCampbell** [comment]
This is not a bug?

**Comment by Nyholm** [comment]
Talk with the people writing that tutorial...

It seams like you have more than on guzzle installation loaded.

**Comment by RIKIPB** [comment]
ok risolto grazie

**Comment by zavan** [comment]
Just in case anyone bumps into this too:
In my root project I had guzzle 7 installed, but I also had a legacy subproject that was loaded with the root project that had guzzle 6 installed, upgrading it to 7 too fixed the problem.

**Comment by helloarpitgshah** [comment]
Is there any way that we can use Guzzle Library for all the PHP version >= 7.4

I need general for all the PHP version with latest.
