### ISSUE TITLE
Connections in pool reconnects randomly when using urls of two different domains.

### ISSUE THREAD

**Issue by aimanzaheb** [guzzle/guzzle#2750]
**Guzzle version(s) affected**: Latest stable version
**PHP version**: 7.4.8 
**cURL version**:  **7.70.0**

**Description**  
My array of requests is something like this
 $requests[0] = new \GuzzleHttp\Psr7\Request('GET', https://domainX/anything , ['verify' => false, 'force_ip_resolve' => 'v4']);
 $requests[1] = new \GuzzleHttp\Psr7\Request('GET', https://domainY/anything , ['verify' => false, 'force_ip_resolve' => 'v4']);
 $requests[2] = new \GuzzleHttp\Psr7\Request('GET', https://domainX/anything , ['verify' => false, 'force_ip_resolve' => 'v4']);
 $requests[3] = new \GuzzleHttp\Psr7\Request('GET', https://domainY/anything , ['verify' => false, 'force_ip_resolve' => 'v4']);
.....
.....
 $requests[n] = new \GuzzleHttp\Psr7\Request('GET', https://domainY/anything , ['verify' => false, 'force_ip_resolve' => 'v4']);
I want to do asynchronous requests to both domains X and Y with pool of 20 requests i.e. 10 requests of domainX and 10 requests of domain Y at a time because my both domains has less potential to handle multiple requests. But the problem is 20 connections used in pool ,reconnects randomly something like  at request no. 74, 846, 1741 etc which i checked using code  
if($stats->getHandlerStats()['connect_time'] > 0.1)
                        echo "CONNECT TIME = ".$stats->getHandlerStats()['connect_time'] . "\n";
. It increases time tremendously for large requests.
But if i use array  of requests with only one domain something like this
  $requests[0] = new \GuzzleHttp\Psr7\Request('GET', https://domainX/anything , ['verify' => false, 'force_ip_resolve' => 'v4']);
 $requests[1] = new \GuzzleHttp\Psr7\Request('GET', https://domainX/anything , ['verify' => false, 'force_ip_resolve' => 'v4']);
 $requests[2] = new \GuzzleHttp\Psr7\Request('GET', https://domainX/anything , ['verify' => false, 'force_ip_resolve' => 'v4']);
 $requests[3] = new \GuzzleHttp\Psr7\Request('GET', https://domainX/anything , ['verify' => false, 'force_ip_resolve' => 'v4']);
.....
.....
$requests[n] = new \GuzzleHttp\Psr7\Request('GET', https://domainX/anything , ['verify' => false, 'force_ip_resolve' => 'v4']);

$requests[n+1] = new \GuzzleHttp\Psr7\Request('GET', https://domainY/anything , ['verify' => false, 'force_ip_resolve' => 'v4']);
$requests[n+2] = new \GuzzleHttp\Psr7\Request('GET', https://domainY/anything , ['verify' => false, 'force_ip_resolve' => 'v4']);
$requests[n+3] = new \GuzzleHttp\Psr7\Request('GET', https://domainY/anything , ['verify' => false, 'force_ip_resolve' => 'v4']);
....
....

Everything works fine, connections start to reconnect after completing 2000 requests i.e.  100 requests of per connection. But i want more performance by using both domains at same time.

**How to reproduce**  
 $requests[0] = new \GuzzleHttp\Psr7\Request('GET', https://domainX/anything , ['verify' => false, 'force_ip_resolve' => 'v4']);
 $requests[1] = new \GuzzleHttp\Psr7\Request('GET', https://domainY/anything , ['verify' => false, 'force_ip_resolve' => 'v4']);
 $requests[2] = new \GuzzleHttp\Psr7\Request('GET', https://domainX/anything , ['verify' => false, 'force_ip_resolve' => 'v4']);
 $requests[3] = new \GuzzleHttp\Psr7\Request('GET', https://domainY/anything , ['verify' => false, 'force_ip_resolve' => 'v4']);
.....
.....
$pool = new Pool($client, $requests, [
                'concurrency' =>  20,
                'fulfilled' => function (Response $response, $index) {
                },
                'rejected' => function ($reason, $index) {  
                }
                ,'options' => ['on_stats' => function(TransferStats $stats) {
                    echo "URL = ".$stats->getEffectiveUri(). "\n";
                    if($stats->getHandlerStats()['connect_time'] > 0.1)
                        echo "CONNECT TIME = ".$stats->getHandlerStats()['connect_time'] . "\n";

                    ob_flush();
                    flush();
                }]
            ]);

            // Initiate the transfers and create a promise
            $promise = $pool->promise();

           // $promise->then(function ($value) { echo $value; });
            // Force the pool of requests to complete.
            $promise->wait();

**Possible Solution**  
Can there be something like using multiple client objects for multiple domains i.e. multiple base URLs inside a single pool?, so that connections will not get disconnect randomly.

**Comment by aimanzaheb** [comment]
![Screenshot (149)](https://user-images.githubusercontent.com/50737539/91754044-5fc56980-ebe6-11ea-925e-fc5894144209.png)
See scrollbar in browser to see there is consistency in connections reconnects if using same type of domain URLs in pool


![Screenshot (150)](https://user-images.githubusercontent.com/50737539/91754279-c5195a80-ebe6-11ea-9f73-1f75c2e74aab.png)
But in this other pic there is no consistency in connection reconnects if using two different domain URLs in pool

**Comment by aimanzaheb** [comment]
Please someone resolve this issue.

**Comment by aimanzaheb** [comment]
Why any author is not responsing?

**Comment by kkopachev** [comment]
As a workaround you can supply pool object with iterable (array) of callables which will return promises. 
See https://github.com/guzzle/guzzle/blob/master/src/Pool.php#L59-L60 
In that case `$client` argument is ignored.
So you can put what ever logic you want into what client to use where right in your callback. 
Something like this:

```php
$client1 = ...;
$client2 = ...;


$requests[0] = function() { return $client1->getAsync('https://domainX/anything' , ['verify' => false, 'force_ip_resolve' => 'v4']); };
$requests[1] = function() { return $client2->getAsync('https://domainY/anything' , ['verify' => false, 'force_ip_resolve' => 'v4']); };
$requests[2] = function() { return $client1->getAsync('https://domainX/anything' , ['verify' => false, 'force_ip_resolve' => 'v4']); };
$requests[3] = function() { return $client2->getAsync('https://domainY/anything' , ['verify' => false, 'force_ip_resolve' => 'v4']); };

```
You could also use `EachPromise` directly.

**Comment by aimanzaheb** [comment]
Any update guzzle team?

**Comment by GrahamCampbell** [comment]
This is an open source project. It's up to everyone to resolve issues, not just previous contributors or people with push access. If you'd like this to move faster, please feel free to reach out to me for a quote: hello@gjcampbell.co.uk.

**Comment by GrahamCampbell** [comment]
Not stale.

**Comment by aimanzaheb** [comment]
Not stale.

**Comment by aimanzaheb** [comment]
Not stale

**Comment by GrahamCampbell** [comment]
Given there is nobody willing to work this, this is stale. It's time to close this out.

**Comment by GrahamCampbell** [comment]
Like I said earlier, if you'd like to purchase paid support, I'd be happy to look into this, but I can't prioritize this personally, as is, since this is a super niche issue specific to yourself. I have to allocate my time to those things that will have maximum impact for all Guzzle users.
