### ISSUE TITLE
Header Function does not catch response exceptions

### ISSUE THREAD

**Issue by williamjulianvicary** [guzzle/guzzle#2762]
On this line:
https://github.com/guzzle/guzzle/blob/c2c9d72f8ba225b585351bbe4922255837ddbd80/src/Handler/CurlFactory.php#L584

Exceptions are not caught, this then leads to a catastrophic error and intermittent failures of Guzzle Pools. When using this with unknown endpoints that may generate non-conforming status codes the PSR7 Response exceptions are thrown which causes cURL and therefore Guzzle to act in odd ways.

The solution is straightforward - catch the exception and return -1 - as has been done for the header callback just below this method call.

Related Pull Request from 6.5 that is still a relevant fix for 7.x: https://github.com/guzzle/guzzle/pull/2591

This is a blocking bug for Guzzle pools for anyone doing crawling and is an incredibly simple fix. Can we get this merged so we don’t need to continue patching Guzzle?

**Comment by strarsis** [comment]
+1, this is a debilitating bug. When an API sends a HTTP response with untypical HTTP status code, the whole thing just crashes.

**Comment by Nyholm** [comment]
This was fixed in #2591 and will be released in 7.2.0
