### ISSUE TITLE
Make the test pass with guzzle/psr7 version 1.7.0

### ISSUE THREAD

**Issue by Nyholm** [guzzle/guzzle#2765]
It has not yet been released but there are one test failing. See https://github.com/guzzle/psr7/pull/330

> There was 1 failure:
>
> 1) GuzzleHttp\Tests\Exception\RequestExceptionTest::testCreatesExceptionWithoutPrintableBody
Failed asserting that Binary String: 0x536572766572206572726f723a2060474554202f6020726573756c74656420696e2061206035303020496e7465726e616c20536572766572204572726f726020726573706f6e73653a0a47494638396101000100800000000000ffffff21f90401000000002c000000000100010000020144003b0a does not contain "GIF89a����!�,D;".
>
> /Users/tobias/Workspace/PHPStorm/guzzle/tests/Exception/RequestExceptionTest.php:141

**Comment by GrahamCampbell** [comment]
We already discussed this a few months ago and decided this was not a bug. We just should delete the test.

**Comment by Nyholm** [comment]
Okey. I miss that discussion (or I dont remember it). If that is the case, feel free to submit a PR to remove the test. 

Make sure we target master.
