### ISSUE TITLE
The file Middleware.php contains a malicious code pattern

### ISSUE THREAD

**Issue by gaupoit** [guzzle/guzzle#2771]
**Guzzle version(s) affected**: 7.0
**PHP version**: 7.3.8
**cURL version**: 7.65.1

**Description**  
I am using https://github.com/aws/aws-sdk-php for my WordPress plugin and it's using 

`"guzzlehttp/guzzle": "^5.3.3|^6.2.1|^7.0"`

One of my users reported that there is a malicious code pattern in Middleware.php file. See below image:
https://imgur.com/a/4yFlLer

**How to reproduce**  
Just got a VaultPress account and it detected a security issue as the description. 

I have a look in the codebase, it seems a valid pattern then. Any ideas why VaultPress reported it? Thanks.

```
return function (callable $handler) use($fn) {
      return function ($request, array $options) use($handler, $fn) {
            return $handler($fn($request), $options);
       };
 };
```

**Comment by GrahamCampbell** [comment]
And why would that code be vulnerable to attack? Can you provide an example, otherwise I think this should be closed.

**Comment by gmponos** [comment]
I think it is a false positive as well. If you CAN detect what's the security vulnerability please feel free to join slack and discuss it with as Personally or through the email you can find on readme

**Comment by gaupoit** [comment]
hi @GrahamCampbell , personally I don't see any vulnerables to attack. However, our clients using VaultPress (developed by WordPress) is showing the threads.

**Comment by Nyholm** [comment]
Thank you for getting back.

I would recommend you to report an issue to VaultPress.
