### ISSUE TITLE
PUT requests with parameters with location of "postField" don't get included in request

### ISSUE THREAD

**Issue by bradfeehan** [guzzle/guzzle#278]
When I have an operation like this:

``` javascript
    // ...
    "MyCommand": {
        "httpMethod": "PUT",
        "parameters": {
            "my_post_param": {
                "location": "postField"
            }
        }
    }
    // ...
```

An example `Request` object for this command, when cast to a string, looks like:

``` http
PUT / HTTP/1.1
Host: 127.0.0.1:8901
User-Agent: Guzzle/3.3.1 curl/7.24.0 PHP/5.3.15
Content-Type: application/x-www-form-urlencoded

my_post_param=my_value
```

But the actual request sent on the wire looks more like:

``` http
PUT / HTTP/1.1
Transfer-Encoding: chunked
Host: 127.0.0.1:8901
User-Agent: Guzzle/3.3.1 curl/7.24.0 PHP/5.3.15
Content-Type: application/x-www-form-urlencoded

0


```

I get the `Transfer-Encoding: chunked` stuff is different, but the main issue I'm concerned with is that there's no body sent at all, whereas the request (and the log plugin) indicates that the request was sent differently to how it actually is.

Am I doing something wrong? Maybe `postField` and `PUT` requests weren't meant to go together? :smile:

I wrote a script which can show the difference for a given request, which may help with testing. It's in [this Gist](https://gist.github.com/bradfeehan/5276257). I could possibly convert this to a test case, I'll try getting the Node server going (I haven't used it before).

**Comment by JLGouwy** [comment]
I've the problem with METHOD PATCH and send "postfield" location parameters.
And i've "Must be a POST body interface" ...
I don't understand why ...

Version : 5.0 guzzle
VERSION : 0.5 guzzle service
