### ISSUE TITLE
How to rotate proxy with retry middleware ?

### ISSUE THREAD

**Issue by gadnis** [guzzle/guzzle#2780]
Hi @alexeyshockov, I think what @inkrement was saying or asking about is: 
- How to rotate proxy using middleware::retry 

Am I right. @inkrement ? 

Well at least I am looking for that 😁  Don't know why, but I was thinking that retry middleware was reconstructing `Guzzle/Client` on each retry and in this way proxy was rotating together (I am using my `Proxy::random()` helper for that) 😁  stupid me.. 😁 

So similar question is:

How to use Retry Middleware to rotate proxy value?

_Originally posted by @gadnis in https://github.com/guzzle/guzzle/issues/1670#issuecomment-699050953_

**Comment by Nyholm** [comment]
Im not sure. This sounds like a specific support question. 

Im sure it is possible somehow, worst case scenario you add your own retry middleware. 

Im closing since it is not an issue with guzzle. 

Also see https://github.com/guzzle/guzzle#help-and-docs

**Comment by gadnis** [comment]
@Nyholm, ok. I made my own retry middleware as you offer. Thanks ;)
