### ISSUE TITLE
fatal error : Host must be a string

### ISSUE THREAD

**Issue by nadia-am** [guzzle/guzzle#2784]
as #2458 mention  i face the error `Exception Host must be a string`
as #2458  mentioned i add the `if ($asciiHost === false || $asciiHost === null) {`  instead of  `if ($asciiHost === false) {` but another error comes up and it didnt solve my problem.
`
Fatal error: Uncaught GuzzleHttp\Exception\InvalidArgumentException: IDN conversion failed in .../translate/vendor/guzzlehttp/guzzle/src/Client.php:243 Stack trace: #0 .../translate/vendor/guzzlehttp/guzzle/src/Client.php(156): GuzzleHttp\Client->buildUri(Object(GuzzleHttp\Psr7\Uri), Array) #1 .../translate/vendor/guzzlehttp/guzzle/src/Client.php(184): GuzzleHttp\Client->requestAsync('get', 'https://transla...', Array) #2 .../translate/vendor/guzzlehttp/guzzle/src/Client.php(97): GuzzleHttp\Client->request('get', 'https://transla...', Array) #3 .../translate/vendor/stichoza/google-translate-php/src/GoogleTranslate.php(304): GuzzleHttp\Client->__call('get', Array) #4 .../translate/vendor/guzzlehttp/guzzle/src/Client.php on line 243
`
Can you help me how to fix it?

**Comment by Mark-H** [comment]
Have you upgraded guzzle? The problem in #2458 was fixed in v6.5.2 if I remember correctly. There's been more releases since but you don't mention what version you're using

**Comment by nadia-am** [comment]
@Mark-H I am using v 6.5.0, i will update it and announce you about the result.

**Comment by Nyholm** [comment]
@nadia-am Did it work?

**Comment by nadia-am** [comment]
@Nyholm yes it did thanks alot.
