### ISSUE TITLE
Create a model instead of handlerStats array

### ISSUE THREAD

**Issue by TheGarious** [guzzle/guzzle#2798]
**Description**

For this handlerStats variable in the TransferStats class, I think we can replace this array with a model or make a documentation that explains what this array contains for more information.

**Example**

**Additional context**

**Comment by Nyholm** [comment]
The contents of that depends on your PHP version and Curl version. Using a data model for that will be very difficult to update and for no real benefit. 

I understand it is had to know what it contains but use Xdebug or print it and you are all set.
