### ISSUE TITLE
Two letter of Arabic language is not rendered successfully

### ISSUE THREAD

**Issue by muath-ic** [guzzle/guzzle#2803]
**Guzzle version(s) affected**: ^6.4
**PHP version**: PHP 7.2.14 (cli) (built: Jan  9 2019 22:23:26)
**cURL version**: 7.61.1

**Description**  
This letters "ح" and "ف" are not send successfully as they are appear, I got  something like "�"

**How to reproduce**  
```php
$client = new \GuzzleHttp\Client();
$client->get('https://www.google.com/search?q=' . 'رمز التحقق لإعادة تعيين كلمة السر  في تطبيق موكا هو');
```

> Change the domain to one that will accept this string

**Comment by Nyholm** [comment]
Did you try to `urlencode()` the query string?

**Comment by GrahamCampbell** [comment]
What happens if you do:

```
$client->get('https://www.google.com/search', ['query => ['q' => 'رمز التحقق لإعادة تعيين كلمة السر  في تطبيق موكا هو']]);
```

to allow Guzzle to build the URI.

**Comment by GrahamCampbell** [comment]
Also note that calling google's search endpoint as a bot is against their terms of service.

**Comment by muath-ic** [comment]
I thank @GrahamCampbell for his contribution it solved my issue. And the domain is not google

**Comment by Nyholm** [comment]
Lovely.
