### ISSUE TITLE
Multiple clients no concurrency

### ISSUE THREAD

**Issue by FreelancerMarketplaces** [guzzle/guzzle#2809]
**Guzzle version(s) affected**: 6.3
**PHP version**: 7.2.33
**cURL version**: 7.29.0

**Description**  
When settling multiple async requests from different GuzzleHttp\Client's there is no concurrency. Not sure if this is a bug; but I would expect the same bahaviour as with a single client.

**How to reproduce**  
```php
$client1 = new GuzzleHttp\Client(['base_uri' => 'https://service1.example.com']);
$client2 = new GuzzleHttp\Client(['base_uri' => 'https://service2.example.com']);

$request = new Request('GET', '/some-call');
$promises[] = $client1->sendAsync($request);
$request = new Request('GET', '/other-call');
$promises[] = $client2->sendAsync($request);

$results = \GuzzleHttp\Promise\settle($promises)->wait();
```
Second request will not start before the first one is finished. Note that I understand you could do the same with just one client. But I have a situation where the clients also have different config settings apart from the different base URI.

**Possible Solution**  
What I have found to work is explicitly assigning both clients the same CurlMultiHandler. But I don't know if that is safe; nor if it is supposed to be done like that. E.g.:
```php
$handler = new GuzzleHttp\Handler\CurlMultiHandler();

$client1 = new GuzzleHttp\Client(['base_uri' => 'https://service1.example.com', 'handler' => GuzzleHttp\HandlerStack::create($handler)]);
$client2 = new GuzzleHttp\Client(['base_uri' => 'https://service2.example.com', 'handler' => GuzzleHttp\HandlerStack::create($handler)]);
```
(of course this is not a suggested fix; but more a suggested way to work around it)

**Comment by GrahamCampbell** [comment]
I think this is the expected behaviour. Sharing clients and handlers should be perfectly fine. :)

**Comment by GrahamCampbell** [comment]
Note that your code there is not the same before and after, because you have not included the redirect following and error handling middleware (among others). You need to pass the handler to the handler stack yourself.

**Comment by Nyholm** [comment]
Yes. This is expected and @GrahamCampbell is correct. Thank you.

**Comment by FreelancerMarketplaces** [comment]
Ok, great info.

May I ask one more question: is it also safe/fine to pass the same handler stack? Instead of create separate stacks from the same handler.

Thanks.

**Comment by FreelancerMarketplaces** [comment]
> Note that your code there is not the same before and after, because you have not included the redirect following and error handling middleware (among others). You need to pass the handler to the handler stack yourself.

Those are not among the default middleware? Because the HandlerStack::create is documented as "You can ensure that the handler you provide to a client uses the default middlewares by wrapping the handler in the GuzzleHttp\HandlerStack::create(callable $handler = null) static method."

I thought this would add all the default middleware.

**Comment by GrahamCampbell** [comment]
I'd recommend just reading the handler stack source code. It will answer all your questions.
