### ISSUE TITLE
Problem when sending request with empty header

### ISSUE THREAD

**Issue by jdecool** [guzzle/guzzle#2810]
**Guzzle version(s) affected**: 7.x.
**PHP version**: 7.2.x
**cURL version**: 7.52.1

**Description**  
Two years ago [an issue](https://github.com/guzzle/guzzle/issues/1882) was opened because of a problem with sending empty headers.

This issue was fixed by this [PR](https://github.com/guzzle/guzzle/pull/1915).

The fix worked with headers defined manually, but for headers which are set automatically by Guzzle, the fix was not applied.

Examples:
* https://github.com/guzzle/guzzle/blob/master/src/Handler/CurlFactory.php#L329
* https://github.com/guzzle/guzzle/blob/master/src/Handler/CurlFactory.php#L390
* https://github.com/guzzle/guzzle/blob/master/src/Handler/CurlFactory.php#L303
* https://github.com/guzzle/guzzle/blob/master/src/Handler/CurlFactory.php#L308
* and some others

**Comment by andreweifill** [comment]
Can anybody help me set up a geofencing solution?
*Let us take your business to the next level*
256 258 8696 <2562588696>



*FOCUSED TARGETED PRECISE *

[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
10/12/20,
09:46:23 PM
