### ISSUE TITLE
why it say Class 'GuzzleHttp\Psr7\Utils' not found

### ISSUE THREAD

**Issue by npqzxc** [guzzle/guzzle#2811]
**Guzzle version(s) affected**: x.y.z
**PHP version**: x.y.z (hint: `php --version`)
**cURL version**: x.y.z (hint: `php -i | grep cURL`)

**Description**  

**How to reproduce**  

**Possible Solution**  

**Additional context**

**Comment by Nyholm** [comment]
Could you do:

composer show | grep guzzle

**Comment by npqzxc** [comment]
> Could you do:
> 
> composer show | grep guzzle

npq@thismac es_task_a % composer show | grep guzzle      
guzzlehttp/guzzle                        7.2.0              Guzzle is a PHP HTTP client library
guzzlehttp/promises                      1.4.0              Guzzle promises library
guzzlehttp/psr7                          1.7.0              PSR-7 message implementation that also provides common utility methods

**Comment by GrahamCampbell** [comment]
Are you seeing these issues on php-fpm? If so, restart it.

**Comment by Nyholm** [comment]
Everything should work. 

It seams that you either have things cached some how (see @GrahamCampbell suggestion) or that your autoloader does not load the required files. (Normal composer autoloader will)

**Comment by pierrotevrard-dbit** [comment]
@npqzxc  Try `composer require guzzlehttp/psr7:^1.6.1 guzzlehttp/promises:^1.3.1`

**Comment by GrahamCampbell** [comment]
If you have already required guzzle, there is no need to do this. Do make sure all your dependencies are up-to-date, however, and that the autoloader has been re-generated.

**Comment by rafaelxavierborges** [comment]
Try to run:
`composer require guzzlehttp/psr7`

**Comment by ssi-anik** [comment]
I'd like to add one point here. I faced the same issue because I used `"minimum-stability": "dev"` and no `"prefer-stable"` in the composer file. Adding `"prefer-stable": true` in the `composer.json` file fixed the issue.
