### ISSUE TITLE
GreenLight 2.7.7 fail to start on Bigbluebutton 2.2.28

### ISSUE THREAD

**Issue by alonyango** [guzzle/guzzle#2814]
**TCP port binding stops docker from running**: 
**Greenlight version**: 2.7.7 
**Bigbluebutton version**: 2.2.28

**Description**  
Please Help with the error below. I did a BBB install on a brand new server then migrated the entire contents of greenlight from the old installation together with recordings. Now i get this error:

ERROR: for db  Cannot start service db: driver failed programming external connectivity on endpoint root_db_1 (546099036df704742e3dfdea9aafa365d8cf13e536700bdb02ea03aa673c6816): Error starting userland proxy: listen tcp 127.0.0.1:5432: bind: address already in use

ERROR: Encountered errors while bringing up the project.

**How to reproduce**  

**Possible Solution**  

**Additional context**

**Comment by Nyholm** [comment]
This is not related to guzzle. 

Please try stackoverflow.
