### ISSUE TITLE
Can't get cookies

### ISSUE THREAD

**Issue by Boy-W** [guzzle/guzzle#2815]
Guzzle version(s): 6.3.0
PHP version: 7.4.10
cURL version: 7.58.0

**Description**  

```
$http = new Client(['cookies' => true]);
$response = $http->post('api.test.com', [
     'headers' => [
         'Content-type' => 'application/json',
         'sec-fetch-site' => 'same-origin',
         'sec-fetch-mode' => 'cors',
     ],
    'json' => [
         'username' => $username,
         'password' => $password,
     ]
]);

$config=$http->getConfig('cookies');
dd($config);
```

I can only get the cookie whose Domain is `api.test.com`, but I cannot get the cookie whose Domain is `test.com`.

After actual testing, I can get the cookie whose domain is test.com through Chrome and Postman.

`api.test.com` is an example URL.

![image](https://user-images.githubusercontent.com/37936633/97973245-c5112300-1e00-11eb-8079-90eddd2c9cda.png)

![image](https://user-images.githubusercontent.com/37936633/97973477-15888080-1e01-11eb-8293-6bc1b12dc34d.png)

![image](https://user-images.githubusercontent.com/37936633/97973590-47014c00-1e01-11eb-88e9-73f83ab9561f.png)

<strong>What should I do to get all the cookies? Or it is not available at all, is it a bug?</strong>

**Comment by Nyholm** [comment]
Is this also true for the latest version of guzzle?

**Comment by Boy-W** [comment]
It's solved.
