### ISSUE TITLE
Response content is modified

### ISSUE THREAD

**Issue by fentanyluser** [guzzle/guzzle#2816]
When receiving a response, the content is modified.

Raw data sent from server:
```
{
  "id": "curltext",
  "jsonrpc": "2.0",
  "result": {
    "number": 9485595355308250426
   }
}
```
Data returned by $response->getBody()->getContents():
```
{"id":"curltext","jsonrpc":"2.0","result":{"number":9.485595355308251e+18}}
```
As you can see all the whitespace and newlines are removed, and most importantly, the number is converted to an exponent with missing precision.

How can we disable this so that the raw response is retrieved?

**Comment by Nyholm** [comment]
Hey. 

Can you show a reproducible script? As far as I remember, we don't read or manipulate the body at all. I think this just an issue when you print it. 

Also, you should use `$response->getBody()->__toString()`

**Comment by GrahamCampbell** [comment]
I think what you're looking at there is a browser rendering of the son. Most browsers only use 32 bit signed integers, which is why this is being converted to a float. You should send large integers as string to prevent this from happening.
