### ISSUE TITLE
Base uri not applied depending on query?!

### ISSUE THREAD

**Issue by MichaelBelgium** [guzzle/guzzle#2829]
**Guzzle version(s) affected**: 6.5.5
**PHP version**: 7.4.3
**cURL version**: 7.68.0

**Description**  
The specified base_uri in Client() is not applied for some requests.

Example: 

```PHP
$this->client = new Client([
    'base_uri' => 'https://domain/'
]);

$response = $this->client->request('GET', 'api/v1/users/sis_user_id:'.$user_id.'/logins', [
    RequestOptions::HEADERS => [
        'Authorization' => 'Bearer xxxx'
    ],
    RequestOptions::VERSION => '1.2',
]);

echo json_decode((string)$response->getBody());
```

If `$user_id` equals 118833 it sends the request succesfully.
If `$user_id` equals 18833 or 6326 it throws an exception:
```
cURL error 6: Could not resolve host: api (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)
```

**Comment by GrahamCampbell** [comment]
Guzzle 6 is EOL. Please try with Guzzle 7.2.

**Comment by MichaelBelgium** [comment]
Looks like we're not able to update guzzle (yet), one of our project required packages has only guzzle 6 required, not 7 .. damn it.

**Comment by guilliamxavier** [comment]
Same error with Guzzle 7.2.0.

Ultimately related to a call to `parse_url` with a non-strictly-valid relative URL in https://github.com/guzzle/psr7/blob/1.7.0/src/Uri.php#L70.

<details>

https://www.php.net/manual/en/function.parse-url.php says:

> This function is *not* meant to validate the given URL, it only breaks it up into the above listed parts. Partial URLs are also accepted, `parse_url()` tries its best to parse them correctly.

and warns:

> **Note:**
> This function may not give correct results for relative URLs.

</details>

In your specific case, it seems that a `$user_id` value shorter than 6 digits is parsed as a port number (see https://3v4l.org/ZsnR3 for example).

According to https://en.wikipedia.org/wiki/Percent-encoding you should encode the colon `:` to its equivalent `%3A` in your string

**Comment by sagikazarmark** [comment]
Looks like it's not a bug then.
