### ISSUE TITLE
Client leaks memory when using a lot of consequent bulk async requests

### ISSUE THREAD

**Issue by dchaplinsky** [guzzle/guzzle#2830]
**Guzzle version(s) affected**: 6.5
**PHP version**: 7.1.33
**cURL version**: 7.54.0

**Description**  
I'm sending a lot of bulk requests in a loop, like this:
```
        $client = new Client(['base_uri' => 'https://api.openprocurement.org/']);
	while (!is_null($since)) {

		$response = $client->request('GET', "api/2.5/contracts", ['query' => ['offset' => $since]]);

		$listing_body = json_decode($response->getBody());
		$contract_requests = [];
		foreach ($listing_body->data as $contract) {
			$contract_requests[$contract->id] = $client->getAsync("api/2.5/contracts/" . $contract->id);
		}
               $contract_responses = Promise\Utils::settle($contract_requests)->wait();
               [....]
       }
```
and the memory footprint is growing constantly. 

**How to reproduce**  
You can see the whole code in my repo https://github.com/dchaplinsky/allzorro/blob/main/sync.php.
It's using an open API and also relies on Doctrine, but you can safely delete the code, which creates Contracts.

I've also tried to remove the Doctrine related code to see if it affects the memory footprint, but it gave me nothing.

**Possible Solution**  
I've tried to re-create client on each iteration, unsetting it and instantiating again and it seems that it helped partially (footprint is growing anyway but slower).

**Comment by mephlaren** [comment]
try null-ing your variables and see if theres any difference. NULL-ing takes away CPU, however for some reason it is faster than unset(). (editing vs removing from symbol table). 

Seems more like a general PHP question than a Guzzle one.

**Comment by dchaplinsky** [comment]
I've tried unsetting both, variables and Client itself, seems that it was a
bit helpful but still it leaks as an old bucket :(

**Comment by dchaplinsky** [comment]
Haha, classic

**Comment by mfn** [comment]
Your repo example is still "a lot of code", it would be helpful to have a really minimal example, also with exact steps how you measure the memory part etc. Just something which can be quickly run locally without having to worry about too many variables.

**Comment by dchaplinsky** [comment]
Sorry, I'm not a PHP developer, so can be a little of help here.
I've identified that issue when I was working on a small side project,
which required PHP. Later it was rewritten using PHP curl lib by another
developer.
