### ISSUE TITLE
Why Cloudfront returning 403 with Guzzle?

### ISSUE THREAD

**Issue by allanzi** [guzzle/guzzle#2832]
**Guzzle version(s) affected**: 6.5.5
**PHP version**: 7.2.34-8+ubuntu18.04.1+deb.sury.org+1
**cURL version**: 7.58.0

**Description**  
I can't consume an API that use Cloudfront , always return 403 (The request could not be satisfied.), but if i do the request with PHP Curl will normal.

**How to reproduce**  
```php
    /**
     * @return void
     */
    public function __construct()
    {
        $this->client = new Client([
            'base_uri' => env('API_HOST'),
            'headers'  => [
                'Accept' => 'application/json',
                'Content-Type' => 'application/json',
            ],
            'timeout' => 30,
            'debug' => true,
        ]);
    }

    /**
     * @param string $method
     * @param string $url
     * @param array $body
     * @param bool $isMultipart
     *
     * @return ResponseInterface
     */
    private function request(string $method, string $url, array $body = [], bool $isMultipart = false): ResponseInterface
    {
        if ($isMultipart) {
            $params['multipart'] = [$body];
        } else {
            $params['json'] = $body;
        }

        $url = $this->appedAuthTokensToUrl($url);

        return $this->client->request($method, $url, $params);
    }
```

**Additional context**  
![image](https://user-images.githubusercontent.com/11529597/102891117-706f4900-443c-11eb-991f-2ac79dc4a0a7.png)

**Comment by mallardduck** [comment]
As stated in my comment on the #1311 error - you're not manually setting the `User-Agent` and are instead relying on the default GuzzleHttp UA string. Given that a lot of web proxies block the UA string by default, you need to configure the `User-Agent` header to something that they do allow.

If Guzzle were to update this default header value then cloud proxies like CloudFront and Securi would just update their configs to block that UA string. So there's really nothing for Guzzle as a project to adjust or fix here.

Update your headers array to include
```php
'User-Agent' => "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36",
```

That way CloudFront will think your PHP script is Chrome on windows. Then I'd bet you won't see a 403.
If that's the case then this is literally a duplicate issue of #1311 and should just be closed.

**Comment by mallardduck** [comment]
Additionally, using your replication steps on a known public site that uses CloudFront - in this case espn.com - doesn't yield the same issue you are reporting here. So I would reason that this is an additional sign that the issue isn't a Guzzle issue, but a client configuration one.

```php
$client = new \GuzzleHttp\Client([
    'base_uri' => "https://espn.com",
    'headers'  => [
        'Accept' => 'application/json',
        'Content-Type' => 'application/json',
    ],
    'timeout' => 30,
    'debug' => true,
]);

$res = $client->get('/');
```

So it's unlikely others will be able to help with this issue as we likely cannot reproduce it to begin with without knowing the domain you're experiencing the issue on.

**Comment by allanzi** [comment]
> Additionally, using your replication steps on a known public site that uses CloudFront - in this case espn.com - doesn't yield the same issue you are reporting here. So I would reason that this is an additional sign that the issue isn't a Guzzle issue, but a client configuration one.
> 
> ```
> $client = new \GuzzleHttp\Client([
>     'base_uri' => "https://espn.com",
>     'headers'  => [
>         'Accept' => 'application/json',
>         'Content-Type' => 'application/json',
>     ],
>     'timeout' => 30,
>     'debug' => true,
> ]);
> 
> $res = $client->get('/');
> ```
> 
> So it's unlikely others will be able to help with this issue as we likely cannot reproduce it to begin with without knowing the domain you're experiencing the issue on.

Hello, 

responding your first I tried to test with `User-Agent`, but not worked.

According the second comment, i tried to call the espn like your example, and I get the same error.

Here part of code will call a GET to https://espn.com and I tried to set a lot of header:
```php
/**
     * @return void
     */
    public function __construct()
    {
        $this->client = new Client([
            'base_uri' => 'https://www.espn.com',
            'referer' => true,
            'headers'  => [
                'Accept' => 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9',
                'Content-Type' => 'application/json',
                'User-Agent' => 'curl/7.58.0',
                'Accept-Encoding' => 'gzip, deflate, br',
                'Accept-Language' => 'en-US,en;q=0.9',
                'Cache-Control' => 'max-age=0'
            ],
            'timeout' => 30,
            'debug' => true,
            'force_ip_resolve' => 'v4'
        ]);
    }

    /**
     * @param string $method
     * @param string $url
     * @param array $body
     * @param bool $isMultipart
     *
     * @return ResponseInterface
     */
    private function request(string $method, string $url, array $body = [], bool $isMultipart = false): ResponseInterface
    {
        if ($isMultipart) {
            $params['multipart'] = [$body];
        } else {
            $params['json'] = $body;
        }

        return $this->client->request('GET', '/', $params);
    }
```

and here the guzzle log from this request:
![image](https://user-images.githubusercontent.com/11529597/102899202-54be6f80-4449-11eb-834a-66c2ce85bfe4.png)

**Comment by mallardduck** [comment]
Well I'm getting a 200 with my ESPN example...so doesn't that seem like an obvious indicator that it's not Guzzle, nor the `User-Agent` fix that they're blocking here? It seems to me that if it works fine for me, then CloudFront is likely blocking your IP from accessing protected sites.

![Screen Shot 2020-12-22 at 9 36 27 AM](https://user-images.githubusercontent.com/619938/102899632-3badc280-4439-11eb-8613-56ff98281e65.png)
![Screen Shot 2020-12-22 at 9 36 37 AM](https://user-images.githubusercontent.com/619938/102899638-3e101c80-4439-11eb-8065-29aead7acbb1.png)

**Comment by allanzi** [comment]
Maybe cloudfront blocking my IP, but I can call with curl for example:

```php
// create curl resource
        $ch = curl_init();

        // set url
        curl_setopt($ch, CURLOPT_URL, "https://www.espn.com");

        //return the transfer as a string
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);

        // $output contains the output string
        $output = curl_exec($ch);
        dd($output);

        // close curl resource to free up system resources
        curl_close($ch);
```

result:
![image](https://user-images.githubusercontent.com/11529597/102900113-a1ef1100-444a-11eb-9060-2a794b691fa1.png)

**Comment by allanzi** [comment]
Cloudfront only block me when I call with Guzzle

**Comment by allanzi** [comment]
For example if I call the API with curl it works:
```php
//  Initiate curl
        $ch = curl_init();
        // Will return the response, if false it print the response
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
        // Set the url
         curl_setopt($ch, CURLOPT_URL, env('API_HOST') . $this->appedAuthTokensToUrl($url));
        // Execute
        $result=curl_exec($ch);
        // Closing
        curl_close($ch);

        // Will dump a beauty json :3
        dd(json_decode($result, true));
```

**Comment by allanzi** [comment]
Finally found solution. If had a body in the GET request the Cloudfront will return 403.

So in my case the problem is this if (always setting a body):
```php
       if ($isMultipart) {
            $params['multipart'] = [$body];
        } else {
            $params['json'] = $body;
        }
```

[Here link of Cloudfront docs](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/RequestAndResponseBehaviorCustomOrigin.html)
![image](https://user-images.githubusercontent.com/11529597/102903664-686cd480-444f-11eb-9ecf-39ceb697518a.png)

**Comment by allanzi** [comment]
Thanks a lot @mallardduck for your help

**Comment by hsmfawaz** [comment]
For me, i had to add the `Accept` header to work
