### ISSUE TITLE
guzzlehttp stuck when host becomes unavailable with "no route to host" error and remains stuck when host comes back

### ISSUE THREAD

**Issue by yutv** [guzzle/guzzle#2835]
**Guzzle version(s) affected**: 6.5.5 - 7.2.0
**PHP version**: 7.2.34 - 8.0.0
**cURL version**: 7.68.0 - 7.75.0-DEV or with curl extension disabled

**Description**  

Guzzle Http stuck when host becomes unavailable with "no route to host" error, and left stuck when host becomes available.

**How to reproduce**  

1. composer require guzzlehttp/guzzle:6.5.5 # or 7.2.0 it doesn't matter
2. create a test script
```php
<?php

require __DIR__ . '/vendor/autoload.php';

$url = 'https://upload.wikimedia.org/wikipedia/commons/f/ff/Pizigani_1367_Chart_10MB.jpg';

$client = new \GuzzleHttp\Client();
for ($i = 0; $i < 10; $i++) {
    echo $i;
    $response = $client->request('GET', $url);
    echo ' ' . $response->getStatusCode() . PHP_EOL;
}
```
3. define upload.wikimedia.org ip address
```bash
ping upload.wikimedia.org
PING upload.wikimedia.org (91.198.174.208) 56(84) bytes of data
```
4. run test
```
php test.php
```
5. emulate 'no route to host' network error in a separate terminal as root user
```
iptables -I OUTPUT -d 91.198.174.208 -j REJECT --reject-with=icmp-host-unreachable
```
6. check connection by curl, should be "no route to host" error:
```bash
curl https://upload.wikimedia.org/wikipedia/commons/f/ff/Pizigani_1367_Chart_10MB.jpg
curl: (7) Failed to connect to upload.wikimedia.org port 443: No route to host
```
7. confirm that test.php is stuck somewhere in the iteration between 0 an 9, e.g.:
```
0 200
1 200
2 200
3 200
4 200
5 200
6 200
7
```
8. **important:** wait 5 min
9. restore network connectivity
```bash
iptables -D OUTPUT -d 91.198.174.208 -j REJECT --reject-with=icmp-host-unreachable
```
10. check image can be downloaded
```
$ curl -sI https://upload.wikimedia.org/wikipedia/commons/f/ff/Pizigani_1367_Chart_10MB.jpg | head -1
HTTP/2 200 
```
11. back to the first terminal

**Actual Result:** test.php process stuck forever
```
0 200
1 200
2 200
3 200
4 200
5 200
6 200
7
```
**Expected Result:** connection timeout error or continuation of the loop or whatever but not stucking

![guzzlehttp](https://user-images.githubusercontent.com/1616522/103002217-2cad3a00-4537-11eb-8fba-bccac97a2c7c.png)

**Comment by GrahamCampbell** [comment]
I don't think what you are describing is a bug in Guzzle. Surely it's an issue with libcurl? Have you tried building PHP with the latest version of libcur?

**Comment by yutv** [comment]
> I don't think what you are describing is a bug in Guzzle. Surely it's an issue with libcurl? Have you tried building PHP with the latest version of libcurl?

The issue remains in the php 8.0.0 and the latest libcurl v. 7.75.0-DEV. Also in both guzzlehttp versions: 6.5.5 and 7.2.0.

![guzzlehttp2](https://user-images.githubusercontent.com/1616522/103031799-38b0f000-4567-11eb-9cd9-a3f5898171e4.png)

**Comment by GrahamCampbell** [comment]
Then I suppose this is an unfixed bug in libcurl. What happens if you disable the curl extension?

**Comment by yutv** [comment]
> Then I suppose this is an unfixed bug in libcurl. What happens if you disable the curl extension?

Nothing changed, the issue persists. 

![guzzlehttp3](https://user-images.githubusercontent.com/1616522/103039061-9ef23e80-4578-11eb-9af9-766b58c10fcc.png)

**Comment by GrahamCampbell** [comment]
And what happens if you set a connect timeout for Guzzle?

**Comment by yutv** [comment]
@GrahamCampbell, yes adding timeout helps, e.g.
```php
$client = new \GuzzleHttp\Client(['timeout' => 180 /* 3 minutes */ ]);
```

Magento 2 uses GuzzleHttp with default settings, and the only possibility to add timeout to GuzzleHttp is by using composer patch.

May you consider adding default timeout to GuzzleHttp  itself  rather than using infinite timeout?

Also it would be great to backport it to the older GuzzleHttp versions (6.x I suppose) in order to fix the issue on Magento 2.3.x which in my case has the following requirements:
```bash
$ composer why guzzlehttp/guzzle
astock/stock-api-libphp             1.1.4     requires  guzzlehttp/guzzle (~6.0)    
klarna/module-core                  5.3.1     requires  guzzlehttp/guzzle (^6.0)    
magento/ece-tools                   2002.1.4  requires  guzzlehttp/guzzle (^6.2)    
magento/framework                   102.0.6   requires  guzzlehttp/guzzle (^6.3.3)  
magento/product-community-edition   2.3.6     requires  guzzlehttp/guzzle (^6.3.3)  
magento/product-enterprise-edition  2.3.6     requires  guzzlehttp/guzzle (^6.3.3)  
php-http/guzzle6-adapter            v1.1.1    requires  guzzlehttp/guzzle (^6.0)    
```

**Comment by GrahamCampbell** [comment]
> $client = new \GuzzleHttp\Client(['timeout' => 180 /* 3 minutes */ ]);

This is not the same as a connect timeout. This is a timeout. See the docs at https://docs.guzzlephp.org/en/stable/request-options.html?highlight=timeout#connect-timeout.

**Comment by GrahamCampbell** [comment]
I think there is possibly a good reason why the default is zero? // cc @Nyholm

**Comment by GrahamCampbell** [comment]
> Also it would be great to backport it to the older GuzzleHttp versions (6.x I suppose)

Guzzle 6 is EOL. You should get them to support Guzzle 7 too. Upgrading is usually very easy. Guzzle 7 was intentionally designed that way.

**Comment by yutv** [comment]
@GrahamCampbell,

Sorry, but it is not clear from the documentation what is a good reason to keep infinite timeout. May you please explain?

I noticed that TCP connection created on the first request in the loop (see test php script in description) and used for further iterations. If GuzzleHttp client initialized like this
```php
$client = new \GuzzleHttp\Client(['timeout' => 180 /* 3 minutes */ ])
```
and, lets imagine, an iteration take 1 minute
will the loop be broken after 3-rd iteration?
If no, that is fine, the "timeout" is what I need.
Should I use "connection_timeout" instead?
