### ISSUE TITLE
Less blocking, less memory consuming Pool::batch()?

### ISSUE THREAD

**Issue by githubeing** [guzzle/guzzle#2844]
**Description**
Wouldn't it be a good idea if Guzzle allowed to limit memory consumption by `Pool::batch()`? (using the `concurrency` option) Why the decision was made to force it keep all results in memory?

**Example**
```php
$promisesGenerator = (function () {
    for ($i = 0; $i < 1000; $i++) {
        $contextData = new stdClass();
        $contextData->hello = 'world';
        $contextData->i = $i;
        $promise = new Promise(fn() => doSomeWork($contextData));
        yield $contextData => $promise;
    }
})();

$resultsGenerator = Pool::batch(
    new Client(),
    $promisesGenerator,
    ['concurrency' => 10]
);

foreach ($resultsGenerator as $contextData => $workResult) {
    // do smth
};
```

**Additional questions**
- Why it is needed to keep the order of requests and results? Since the work is asynchronous, obviously there will be many cases when the order doesn't matter but reducing the blocking time worth it to return results as they arrive - and not waiting for response `#17` before returning the already obtained results `##18-45`?
- Why does the Pool enforces me to provide a client instance? What if I'm not using one? Why cannot it create it by himself since it is him who need it, not me?
- Is it possible to use arbitrary data as keys? Why not?

**Comment by githubeing** [comment]
Upd. And what do you think about renaming the `batch` method to maybe `batchUnwrap` or smth similar? Because what it does is obviously unwraps - that is `$promise->wait(unwrap: true)` - a batch of promises...

**Comment by githubeing** [comment]
And why does Guzzle require to provide an iterable of either Requests or callables that return a Promise? Even in the example from docs, the iterable provided is a Generator - so why do I have to generate callables that return a Promise instead of generating Promises directly? Why Guzzle doesn't support this? e.g. compare with:
```php
$promiseCallablesGenerator = (function () {
    for ($i = 0; $i < 1000; $i++) {
        $contextData = new stdClass();
        $contextData->hello = 'world';
        $contextData->i = $i;
        $promise = new Promise(fn() => doSomeWork($contextData));
        $promiseCallable = fn() => $promise; // why this extra step needed?
        yield $contextData => $promiseCallable;
    }
})();

$resultsGenerator = Pool::batch(
    new Client(),
    $promiseCallablesGenerator,
    ['concurrency' => 10]
);
```

**Comment by GrahamCampbell** [comment]
Controlling memory usage is hard to do, however I can't image you will run into any issues, unless you are forcefully loading response bodies into memory. // cc @Nyholm
