### ISSUE TITLE
Middleware::retry() (and others) typing

### ISSUE THREAD

**Issue by zerkms** [guzzle/guzzle#2846]
**Description**

Its return type is declared as

```
@return callable Returns a function that accepts the next handler.
```

while it in fact should be

```
@return callable(callable):callable Returns a function that accepts the next handler.
```

because `HandlerStack::push()` is declared as

```
    /**
     * Push a middleware to the top of the stack.
     *
     * @param callable(callable): callable $middleware Middleware function
     * @param string                       $name       Name to register for this middleware.
     */
    public function push(callable $middleware, string $name = ''): void
    {
        $this->stack[] = [$middleware, $name];
        $this->cached = null;
    }
```

**Example**

At the moment this code

```php
            $stack->push(Middleware::retry(
                $this->retryDecider($logger),
                function (int $retries): int {
                    return $retries * 1000;
                }
            ));
```

does not pass type check, because `Middleware::retry` return value is more generic than `$stack->push` argument parameter type.

**Additional context**

**Comment by GrahamCampbell** [comment]
I'd be happy to review a PR that added more precise typing information (and possibly eliminated some lines from our static analyzer baseline files),

**Comment by zerkms** [comment]
@GrahamCampbell instead of reducing baseline psalm I increased it significantly, sorry :-D

**Comment by zerkms** [comment]
Not stale - there is a PR

**Comment by zerkms** [comment]
I hate leaving such messages and I understand it's very low priority, but "not stale" :-)
