### ISSUE TITLE
ConnectException message format leaking potential sensitive data

### ISSUE THREAD

**Issue by TheLevti** [guzzle/guzzle#2851]
**Guzzle version(s) affected**: 7.2.0
**PHP version**: 7.4.14
**cURL version**: 7.68.0

**Description**

There is no clean way to define or overwrite how the connect exception message is produced in the `CurlFactory` class. And because of the fact that the default implementation appends the request uri to the exception message, it is a potential problem with uris, that contain sensitive data. This exception message is propagated throughout the whole system, potentially processed further and sent to external tools/monitoring tools and logging systems.

One example is the telegram bot API. It requires that the access token is part of the path. Every exception that is generated now leaks the access token all over the place (logs, monitoring, etc.). Some parts like the `http_error` middleware with it's `RequestException` throwing are easily overwritable, but not one special case where a `ConnectException` in the `CurlFactory` has to be thrown.

The affected method `CurlFactory::createRejection()` is static and also the exception format is not in an extensible method.

It would be awesome, if this code is refactored a bit so that at least we get some control over how the exceptions are generated or what message it contains.

**How to reproduce**  

Do a request with a `timeout` of `0.01` and you see a timeout (ConnectException) being thrown, which contains the uri.

**Possible Solution** 

**Additional context**  

In the case of the telegram bot api the following message is generated:

> cURL error 28: Resolving timed out after 10 milliseconds (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://api.telegram.org/botSOMEclearTEXTtoken/sendMessage

For RequestException errors that are generated through the `http_error` middleware it is quite easy to overwrite the logic and add a custom message like this the following example that is thrown on a client exception:

> Client error: `POST https://api.telegram.org/bot**********/sendMessage` resulted in a `400 Bad Request` response:
 (truncated...)

**Comment by Nyholm** [comment]
It seams like this is an issue for Telegram. 

The URL should not contain sensitive data. Never. Even using HTTP basic authentication is not a good way forward.

**Comment by GrahamCampbell** [comment]
Moreover, removing secrets from logs is a solved problem, and does not belong inside Guzzle, owing to separation of concerns.

**Comment by TheLevti** [comment]
Yes, no question about that. Telegram was an example. The problem here is that the related classe is lacking the possibility to easily extend functionality to give us an option to customize how those errors are generated.

**Comment by TheLevti** [comment]
Also this issue is specifically for the connection exception creation. Like I stated it is easy to add/extend functionality for Client/Server exception handling. Not so for connection exceptions. It would be nice if this can be added/refactored.

**Comment by TheLevti** [comment]
Please re-open the issue, because many websites/services have their token in the query parameters as well, which are also just dumped in the connect exception.

E.g.

```
cURL error 6: Could not resolve host: pro.ip-api.com (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for http://pro.ip-api.com/json/127.0.0.1?key=**************
```

**Comment by GrahamCampbell** [comment]
As I explained, removal of secrets from exception messages in logs is outside of the scope of Guzzle. You need to implement this yourself, or using off the shelf stuff.

**Comment by TheLevti** [comment]
> As I explained, removal of secrets from exception messages in logs is outside of the scope of Guzzle. You need to implement this yourself, or using off the shelf stuff.

The problem is that the library does not give the option to do this. The URL is part of the exception message, which should not be. The whole url is just concatenated in between of the exception message. This makes it hard to make sure to not have the potential token all over the place that handles this exception. Please check the referenced class. There is no way to make the library not put the whole url in the exception message. The only way would be to swallow the whole exception and rethrow a different one without chaining. But that way we lose the original cause of the error.

**Comment by TheLevti** [comment]
```php
private static function createRejection(EasyHandle $easy, array $ctx): PromiseInterface
    {
        static $connectionErrors = [
            \CURLE_OPERATION_TIMEOUTED  => true,
            \CURLE_COULDNT_RESOLVE_HOST => true,
            \CURLE_COULDNT_CONNECT      => true,
            \CURLE_SSL_CONNECT_ERROR    => true,
            \CURLE_GOT_NOTHING          => true,
        ];

        if ($easy->createResponseException) {
            return P\Create::rejectionFor(
                new RequestException(
                    'An error was encountered while creating the response',
                    $easy->request,
                    $easy->response,
                    $easy->createResponseException,
                    $ctx
                )
            );
        }

        // If an exception was encountered during the onHeaders event, then
        // return a rejected promise that wraps that exception.
        if ($easy->onHeadersException) {
            return P\Create::rejectionFor(
                new RequestException(
                    'An error was encountered during the on_headers event',
                    $easy->request,
                    $easy->response,
                    $easy->onHeadersException,
                    $ctx
                )
            );
        }

        $message = \sprintf(
            'cURL error %s: %s (%s)',
            $ctx['errno'],
            $ctx['error'],
            'see https://curl.haxx.se/libcurl/c/libcurl-errors.html'
        );
        $uriString = (string) $easy->request->getUri();
        if ($uriString !== '' && false === \strpos($ctx['error'], $uriString)) {
            $message .= \sprintf(' for %s', $uriString);
        }

        // Create a connection exception if it was a specific error code.
        $error = isset($connectionErrors[$easy->errno])
            ? new ConnectException($message, $easy->request, null, $ctx)
            : new RequestException($message, $easy->request, $easy->response, null, $ctx);

        return P\Create::rejectionFor($error);
    }
```

First of all the whole method is private, which makes it impossible to overwrite. Then the exception message format is arbitrary chosen without a real reason to put the whole uri inside the message. Would it be ok if I provide a pull request to refactor this to first of all make this method overwritable + use a dedicated method/factory method to generate a connection exception. In a similar way it is done for the Client/Server exception?

**Comment by Nyholm** [comment]
No, we will not accept a PR to make this method non-private. Nor to use a "dedicated method/factory". 

I will not change my mind on this base on any on the arguments I've seen so far. I doubt that we will ever do that to be honest.

Here is how to move forward: 
1. Decorate the Guzzle client
2. Don't blindly log all exceptions

I may be open to move the URL to the exception's context. But I need some more compelling arguments for making that change. An argument not based on poorly configured/secured logs.

**Comment by TheLevti** [comment]
> No, we will not accept a PR to make this method non-private. Nor to use a "dedicated method/factory".
> 
> I will not change my mind on this base on any on the arguments I've seen so far. I doubt that we will ever do that to be honest.
> 
> Here is how to move forward:
> 
> 1. Decorate the Guzzle client
> 2. Don't blindly log all exceptions
> 
> I may be open to move the URL to the exception's context. But I need some more compelling arguments for making that change. An argument not based on poorly configured/secured logs.

Again it has nothing to do with logs.

Second of all why do you then have obfuscation logic in a different exception? Your answer makes no sense.

**Comment by Nyholm** [comment]
Petr, I appreciate your enthusiasm and your devotion to this topic. 

I've given you both a workaround and what you should do if you really want to change this. Please reread [my comment](https://github.com/guzzle/guzzle/issues/2851#issuecomment-794495238)

**Comment by TheLevti** [comment]
Point 2. does not apply here, because it has not much to do with logs. With point one you lose track of the origin of the exception. One should be able to chain exceptions without adding extra layer of complexity just to avoid some libraries mistake.

An example: The exception is collected by many monitoring tools and is further processed. They do not care about the contents of the exception message and can not know that there is sensitive content (just to name a few, sentry, ignition, etc.). It's the responsibility of the exception thrower to not put sensitive content in the message. It's basically throwing plaintext passwords out in the wild and expecting that everyone will make sure to obfuscate guzzle exception messages.

Then you did not answer why you do this exact thing that you do not want to agree on in the RequestException class (making sure to not expose sensitive parts of the url in the message). Either you do not obfuscate anything or you do it consistently in all exceptions where the uri is part of the message.

There is a reason why curl itself is not including any payload data in the error message. If additional information is needed, one can just fetch what he needs in the context.
