### ISSUE TITLE
Mimic web browser behaviour

### ISSUE THREAD

**Issue by pmnmpr** [guzzle/guzzle#2852]
**Description**
Initiate sub-requests, after recieving the response, mostly like any web browser.

**Example**
Currently Guzzle sends the request and recieves the http response with no further initiating http requests for page assets , etc.

It would be greate to have an option to set Guzzle to initiate sub requests on the response html like css and js assets out of the box.

**Comment by GrahamCampbell** [comment]
You should consider using a web crawler instead, or an actual web browser. I don't think this use case was ever intended to fall into what Guzzle can do. Guzzle is mostly for calling API endpoints.

**Comment by Nyholm** [comment]
Yes, Correct. Guzzle is not a browser. Guzzle is an HTTP client.
