### ISSUE TITLE
Server received posted data,but it's garbled

### ISSUE THREAD

**Issue by zmofsx** [guzzle/guzzle#2856]
**Guzzle version(s) affected**: 7.2
**Laravel version**: 8.26.1
**PHP version**: 7.4.3
**cURL version**: 7.68.0

**Description**  

Post chinese to server.At server received garbled string. Using curl_ functions in the previous Laravel version did not have this problem.

**How to reproduce**  

The code:
```php
     * @param $url
     * @param null $data
     * @return array|mixed
     */
    static function postAsFormToService($url, $data = null)
    {
        $response = Http::asForm()
            ->acceptJson()
            ->post($url, $data);
        if ($response->ok()) {
            return $response->json();
        } else {
            return ['id' => $response->status(), 'message' => $response->body()];
        }
    }

```
$data is

```php
array (
  'config' => 'allyworld@qq.com',
  'to' => 'zmofsx@qq.com',
  'subject' => 'Feedback from allyworld.cn',
  'content' => 'Please connect user by info [Name:张茂; Email:zmofsx@qq.com; Message:有发票吗？]',
)  

```

Server code in JAX-RS:

```
    @POST
    @Produces(value = MediaType.APPLICATION_JSON)
    @Consumes(value = MediaType.APPLICATION_FORM_URLENCODED)
    public void post(
            @Suspended final AsyncResponse asyncResponse,
            @FormParam(value = "config") final String config,
            @FormParam(value = "from") final String from,
            @FormParam(value = "to") final String to,
            @FormParam(value = "bc") final String bc,
            @FormParam(value = "bcc") final String bcc,
            @FormParam(value = "subject") final String subject,
            @FormParam(value = "content") final String content,
            final String body) {

        LOG.log(Level.SEVERE, content);
        LOG.log(Level.SEVERE, body);

    }
```

Server received data is:

2021-02-17 13:26:29,044 SEVERE [cn.allyworld.y6.jaxrs.MailResource -> post] (default task-18) Please connect user by info [Name:???¨¨??; Email:zmofsx@qq.com; Message:????????¡§??????]
2021-02-17 13:26:29,045 SEVERE [cn.allyworld.y6.jaxrs.MailResource -> post] (default task-18) subject=Feedback from allyworld.cn&to=zmofsx@qq.com&config=allyworld@qq.com&content=Please connect user by info [Name:???¨¨??; Email:zmofsx@qq.com; Message:????????¡§??????]

**Comment by Nyholm** [comment]
Laravel is not a dependency of this package. I dont understand this report, how to reproduce the bug or what the bug actually is.
