### ISSUE TITLE
JSON MALFORMED CHARSET BUG

### ISSUE THREAD

**Issue by burakbuylu** [guzzle/guzzle#2861]
**Guzzle version(s) affected**: 6.5.5
**PHP version**: 7.2.5 (hint: `php --version`)
**cURL version**: 7.64.1 (hint: `php -i | grep cURL`)

**Description**  
We have LATIN5 charset database. I want to login via curl but If I have NON-UTF8 charset in my code I got UTF-8 MALFORMED ERROR (JSON_ENCODE)

**How to reproduce**  
In laravel im trying to change encoding to ISO type. But when I sent post request it must be go on exception page!

$request->merge(['password' => iconv("UTF-8","ISO-8859-9", mb_convert_encoding($request->input('password'),'UTF-8','UTF-8'))]);

**Possible Solution**  
I was fixed this bug with CURL

**Additional context**  
'Malformed UTF-8 characters, possibly incorrectly encoded'

**Comment by Nyholm** [comment]
I dont understand how this is related to Guzzle.

**Comment by tianci100** [comment]
src/Exception/RequestException.php:107
