### ISSUE TITLE
Conflict between  guzzlehttp/guzzle ~6.0 and 7.0

### ISSUE THREAD

**Issue by kiwango** [guzzle/guzzle#2862]
our requirements could not be resolved to an installable set of packages.

  Problem 1
    - jobapis/jobs-common[2.0.0-beta, ..., 2.1.2] require guzzlehttp/guzzle ~6.0 -> found guzzlehttp/guzzle[6.0.0, ..., 6.5.x-dev] but it conflicts with your root composer.json require (^7.0.1).
    - jobapis/jobs-careerjet 0.1.0 requires jobapis/jobs-common ^2.0.0 -> satisfiable by jobapis/jobs-common[2.0.0-beta, ..., 2.1.2].
    - Root composer.json requires jobapis/jobs-careerjet ^0.1.0 -> satisfiable by jobapis/jobs-careerjet[0.1.0].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.
**How I can install both version to solve the problem**

**Comment by GrahamCampbell** [comment]
You cannot install them both. `jobapis/jobs-common` needs to upgrade to Guzzle 7.
