### ISSUE TITLE
[Bug] MessageFormatter makes the response body empty

### ISSUE THREAD

**Issue by root-aza** [guzzle/guzzle#2863]
**Guzzle version(s) affected**:  7.2.0
**PHP version**: 8.0.2
**cURL version**: 7.74.0

**Description**  
When use the template {response} for the MessageFormatter with the built-in logger midleware Middleware::Log, the response body becomes empty.

**How to reproduce**  
```php
<?php

use GuzzleHttp\Client;
use GuzzleHttp\Psr7\Request;

$client   = new Client();
$request  = new Request('GET', 'https://jsonplaceholder.typicode.com/todos/1');
$response = $client->sendRequest($request);

$formatter = new \GuzzleHttp\MessageFormatter('{response}');
$message   = $formatter->format($request, $response);

if ($response->getBody()->getContents() === '') { // WTF???
    echo 'empty body' . \PHP_EOL;
    echo $message . \PHP_EOL;
}
```

**Possible Solution**  
Rewind the stream at retrieving response content.

**Comment by Nyholm** [comment]
I know this is super weird, however, it is not wrong. `getContents()` says: "Print the rest of the stream". You are making an assumption that the stream pointer is at the beginning. There is no place where PSR7 or Guzzle promise the position of the pointer. 

You should always use `$response->getBody()->__toString()`

**Comment by root-aza** [comment]
Oh. Sory. Then I close the issue.

**Comment by Nyholm** [comment]
No worries. As I said: This is weird and super confusing.
