### ISSUE TITLE
[Docs] Dead link to Sphinx

### ISSUE THREAD

**Issue by Darylgolden** [guzzle/guzzle#2865]
**Description**  
Clicking on Sphinx at the bottom right corner of the docs leads to a dead link.

**Possible Solution**  
https://github.com/guzzle/guzzle_sphinx_theme/pull/49 should fix it. The repo looks rather inactive, so I posted here for more attention.

**Additional context**

**Comment by Nyholm** [comment]
Thank you.

**Comment by Darylgolden** [comment]
The bug still persists and will continue to until a new version of the theme is released and the docs is updated to use it.
