### ISSUE TITLE
Guzzle Http with Maatwebsite Excel Response Content Type

### ISSUE THREAD

**Issue by doremi666** [guzzle/guzzle#2870]
**Guzzle version(s) affected**: 7.0.1
**PHP version**: 7.4.6

**Description**  
I am using Postman for the excel export API testing. I have the response data as shown in the picture below.
![image](https://user-images.githubusercontent.com/26452088/110796253-b527b500-82b2-11eb-84a1-1fee00e6e849.png)

After I press "Save Response to a file", it's giving me a html file (response.html) instead of a excel file (the filename should be "transactions_2021-02-27.xlsx") with defined filename. I have checked the response Content-Type header, it's returning text/html. May I know how to set the response Content-Type so that the downloaded file is in excel format instead of html?

**Comment by Nyholm** [comment]
I dont see an issue with Guzzle in this PR. 

We cannot provide support in the issue tracker. Please use Stackoverflow or other forums.
