### ISSUE TITLE
Slack signup link in readme fails with service timeout

### ISSUE THREAD

**Issue by prondubuisi** [guzzle/guzzle#2871]
I don't know if this passes for a bug, but following the signup link for Slack, in this project's [readme](https://github.com/guzzle/guzzle#help-and-docs), leads to a Service Unavailable error. Is there another way to join the slack channel? I have questions about implementing PSR18  complaint requests using Guzzle7

**Comment by sagikazarmark** [comment]
Yeah, I'm working on a fix for that. I can send you an invite if you want.

**Comment by prondubuisi** [comment]
Yes @sagikazarmark, please do, my email is onyemenamndu@gmail.com

**Comment by sagikazarmark** [comment]
Done
