### ISSUE TITLE
Support for: content-encoding: br

### ISSUE THREAD

**Issue by mkrvaric** [guzzle/guzzle#2873]
Please consider using one of the issue templates (bug report, feature request).
Adding support for br content encoding could save up to 80-90% for tested HTML responses (according to chrome network inspect). 

"Javascript files compressed with Brotli are 14% smaller than gzip.
HTML files are 21% smaller than gzip.
CSS files are 17% smaller than gzip."

"Fewer bytes transferred not only leads to faster page load but also helps in reducing costs of Content Delivery Network (CDN). Now that we know all these benefits, let’s see how to enable Brotli…"

Also, when using a proxy with the guzzle this could benefit in reducing proxy costs.

**Comment by GrahamCampbell** [comment]
I think this is already supported, if you have ext-curl loaded?

**Comment by GrahamCampbell** [comment]
Here's a test script to a site which supports Brotli compression:

```php
<?php

require __DIR__.'/vendor/autoload.php';

echo GuzzleHttp\Psr7\Message::toString(
    $request = new GuzzleHttp\Psr7\Request('GET', 'https://styleci.io/', ['Accept-Encoding' => 'br'])
);

echo GuzzleHttp\Psr7\Message::toString(
    (new GuzzleHttp\Client)->send($request)
);
```

Using the stream handler, this works:

```
GET / HTTP/1.1
Host: styleci.io
Accept-Encoding: br

HTTP/1.1 200 OK
Date: Mon, 22 Mar 2021 01:09:06 GMT
Content-Type: text/html; charset=utf-8
Transfer-Encoding: chunked
Connection: keep-alive
Set-Cookie: __cfduid=d2e2d4f25c6238aa75f522c1eda4fef331616375346; expires=Wed, 21-Apr-21 01:09:06 GMT; path=/; domain=.styleci.io; HttpOnly; SameSite=Lax; Secure
Cache-Control: max-age=691200
Expires: Fri, 19 Mar 2021 17:51:29 GMT
Vary: Origin, Accept-Encoding
CF-Cache-Status: HIT
Age: 27669
cf-request-id: 08f9138c52000018938d322000000001
Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
Report-To: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report?s=r8UpukRXvryCvpJN04cR1fuJ%2FXSyQF5FqKs8%2FlnJQRs1C1u27CM6oKNI9DnIpkZt62lGVzysFEkMYeAX15vaJZbFYPA3F%2Fz%2Bgu0r"}],"group":"cf-nel","max_age":604800}
NEL: {"max_age":604800,"report_to":"cf-nel"}
Strict-Transport-Security: max-age=15552000; includeSubDomains; preload
X-Content-Type-Options: nosniff
Server: cloudflare
CF-RAY: 633b885a18fd1893-MAN
alt-svc: h3-27=":443"; ma=86400, h3-28=":443"; ma=86400, h3-29=":443"; ma=86400
x-encoded-content-encoding: br

<!DOCTYPE html><html><head><meta charset="utf-8" /><meta http-equiv="x-ua-compatible" content="ie=edge" />...
```

But using the curl handler:

```
GET / HTTP/1.1
Host: styleci.io
Accept-Encoding: br

PHP Fatal error:  Uncaught GuzzleHttp\Exception\RequestException: cURL error 23: Unrecognized content encoding type. libcurl understands deflate, gzip content encodings. (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://styleci.io/ in /data/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:211
Stack trace:
#0 /data/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(158): GuzzleHttp\Handler\CurlFactory::createRejection()
#1 /data/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(110): GuzzleHttp\Handler\CurlFactory::finishError()
#2 /data/vendor/guzzlehttp/guzzle/src/Handler/CurlHandler.php(47): GuzzleHttp\Handler\CurlFactory::finish()
#3 /data/vendor/guzzlehttp/guzzle/src/Handler/Proxy.php(28): GuzzleHttp\Handler\CurlHandler->__invoke()
#4 /data/vendor/guzzlehttp/guzzle/src/Handler/Proxy.php(48): GuzzleHttp\Handler\Proxy::GuzzleHttp\Handler\{closure}()
#5 /data/vendor/guzzlehttp/guzzle/src/PrepareBodyMiddleware.php(35): GuzzleHttp\Handler\Proxy::GuzzleHttp\Handler\{closure}()
#6 /data/vendor/guzzleht in /data/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php on line 211
```

**Comment by GrahamCampbell** [comment]
It's kinda funny - the response built by the stream handler seems to have been decoded, however I don't see how, since the code only decodes gzip and deflate!

**Comment by GrahamCampbell** [comment]
Closing, since we do support brotli. It's just a matter of having a new enough PHP installation and libcurl. :)

**Comment by GrahamCampbell** [comment]
Related: https://github.com/docker-library/php/issues/1140.

**Comment by Nicolas-Gong** [comment]
@GrahamCampbell 
Hello, can you help me with this problem? My php has enabled brotli, nginx has also enabled brotli, and restarted the service, but the brotli_version cannot be viewed when printing curl_version, and this method of request is not supported.

![image](https://user-images.githubusercontent.com/23067153/205804869-cc32927b-0f4b-4501-b0d1-0708b2b555b2.png)

![image](https://user-images.githubusercontent.com/23067153/205804937-3d59a93d-f0f2-442e-b8d9-a8a6c6ada808.png)

![image](https://user-images.githubusercontent.com/23067153/205804781-78208b12-0e2f-48ac-bf7e-bc18d596a76e.png)
