### ISSUE TITLE
Hello, I have the same issue. Does anyone find out what was causing this problem? Is it guzzle, or opposite side does not reply correctly when big file is send??

### ISSUE THREAD

**Issue by janholusa** [guzzle/guzzle#2886]
Hello, I have the same issue. Does anyone find out what was causing this problem? Is it guzzle, or opposite side does not reply correctly when big file is send?? 
Communication looks like this:
```
Host: x.x.x.x
User-Agent: GuzzleHttp/6.3.3 curl/7.64.0 PHP/7.4.10
Content-Type: multipart/form-data; boundary=69d74e069af293c0ea24db3508d7a725743dc1e6
Accept: application/json
Expect:
x-auth-token: ae18007986b4b1246ed4e3afc9fffcc66ad5f7ba
Content-Length: 31895351

* We are completely uploaded and fine
* Empty reply from server
* Connection #20 to host x.x.x.x left intact
```
When attempted to send it via curl, it works correctly.

_Originally posted by @janholusa in https://github.com/guzzle/guzzle/issues/1848#issuecomment-768928854_

**Comment by Nyholm** [comment]
Failed to reprodue

**Comment by qq690712575** [comment]
mee to

**Comment by Nyholm** [comment]
Please provide a reproducible script. 

If nobody can reproduce this it would be impossible to fix.
