### ISSUE TITLE
Undefined class constant 'MAJOR_VERSION'

### ISSUE THREAD

**Issue by iceverge** [guzzle/guzzle#2889]
**Guzzle version(s) affected**: ^7.0.0
**PHP version**: ^7.2

**Description**  
I got error on Undefined class constant 'MAJOR_VERSION'.

How to fix this issue?

**Comment by GrahamCampbell** [comment]
That constant was removed. Don't try to use it.

**Comment by GrahamCampbell** [comment]
Check you don't have Guzzle 6 global installed, and that's being autoloaded instead. That constant exists only in version 7.
