### ISSUE TITLE
Typo or PHP voodoo magic?

### ISSUE THREAD

**Issue by sualko** [guzzle/guzzle#2894]
Hi everyone. Can someone explain this line?

https://github.com/guzzle/guzzle/blob/de6f1e58e735754b888649495ed4cb9ae3b19589/tests/Cookie/SetCookieTest.php#L377

@SamuelWei @FelixJacobi and I think the `!=` should be a `-`.

**Comment by SamuelWei** [comment]
@GrahamCampbell Any updates on this or your PR?

**Comment by sualko** [comment]
@villfa can you maybe look into this issue?

**Comment by villfa** [comment]
@sualko I'm just a contributor of this project, not a maintainer.

Anyway I have open a PR to this problem #2977
