### ISSUE TITLE
Could Not Resolve Host

### ISSUE THREAD

**Issue by mztlive** [guzzle/guzzle#2898]
The introduction of amp/http-client will cause guzzlehttp to trigger the could not resolve host exception (occasionally)

It should be noted that: only composer refers to amp/http-client, and does not use any code inside

When I removed the dependency of amp/http-client from composer, everything returned to normal, and it was the same result after repeated testing.

**Comment by Nyholm** [comment]
My first thought was that this was a coincidence. My second thought is that `amphp/http-client` is doing something to resolve DNS asynchronously which causes trouble. 

Nevertheless, it is not related to Guzzle. If you really really think it is, please provide a unit test or create a reproducer repository.
