### ISSUE TITLE
Message: Call to undefined method GuzzleHttp\Utils::chooseHandler()

### ISSUE THREAD

**Issue by chiragvels** [guzzle/guzzle#2900]
**Guzzle version(s) affected**: 7.3.0
**PHP version**: 7.4.14
**cURL version**: 7.58.0 (hint: `php -i | grep cURL`)

**Description**  
GuzzleHttp\Utils::chooseHandler() when calling google ads api 

**How to reproduce**  
https://github.com/googleads/google-ads-php/issues/612#issuecomment-859560324

**Comment by GrahamCampbell** [comment]
Chances are you are not using Guzzle 7.3.0, but a globally installed version of Guzzle different to the version you thought.

**Comment by chiragvels** [comment]
How I can identify globally installed version and different versions? 


I may say that I have 2 repo which might require different guzzle versions but those 2 repo are installed with composer in 2 different folders with 2 autoload file.

So is this a issue?

**Comment by chiragvels** [comment]
Hi @GrahamCampbell ,

Is there any hint how I can differentiate which is global and which is local guzzle version?

Thanks,

**Comment by Nyholm** [comment]
Use xdebug to look at the stacktrace.
You also see what version you have installed in composer.lock. (Or run `composer show`). 

Please refer to a support forum for support. This issue tracker is for bugs.
