### ISSUE TITLE
Throws doc block. 

### ISSUE THREAD

**Issue by Legion112** [guzzle/guzzle#2902]
**Guzzle version(s) affected**: 6.5.5
**PHP version**: 7.4.0 (hint: `php --version`)
**cURL version**: 7.68.0 (hint: `php -i | grep cURL`)

**Description**  
The magic method does not show which exception might be thrown 
![image](https://user-images.githubusercontent.com/20613430/122032531-666d4800-cdd8-11eb-9d6c-ed47f691c217.png)
The PHP storm says `Exception 'ClientException' is never thrown in the corresponding try block`. 

**How to reproduce**  

Call one of the magic method 
```
 * @method ResponseInterface get(string|UriInterface $uri, array $options = [])
 * @method ResponseInterface head(string|UriInterface $uri, array $options = [])
 * @method ResponseInterface put(string|UriInterface $uri, array $options = [])
 * @method ResponseInterface post(string|UriInterface $uri, array $options = [])
 * @method ResponseInterface patch(string|UriInterface $uri, array $options = [])
 * @method ResponseInterface delete(string|UriInterface $uri, array $options = [])
 * @method Promise\PromiseInterface getAsync(string|UriInterface $uri, array $options = [])
 * @method Promise\PromiseInterface headAsync(string|UriInterface $uri, array $options = [])
 * @method Promise\PromiseInterface putAsync(string|UriInterface $uri, array $options = [])
 * @method Promise\PromiseInterface postAsync(string|UriInterface $uri, array $options = [])
 * @method Promise\PromiseInterface patchAsync(string|UriInterface $uri, array $options = [])
 * @method Promise\PromiseInterface deleteAsync(string|UriInterface $uri, array $options = [])
```
Add try-catch block with ClientException. Use PhpStorm or any other static tool analyzer to verify code validity.
**Possible Solution**  

Remove magic method and create real one with PHP throws doc block.
**Additional context**

**Comment by Legion112** [comment]
Maybe we can take this approach https://stackoverflow.com/a/51535347/7921383

**Comment by GrahamCampbell** [comment]
Guzzle 6 is not maintained anymore, other than for security fixes. This issue is not present in Guzzle 7.
