### ISSUE TITLE
Exceptions documentation contradictory about networking errors

### ISSUE THREAD

**Issue by Chealer** [guzzle/guzzle#2906]
**Guzzle version(s) affected**: N/A
**PHP version**: N/A
**cURL version**: N/A

**Description**  
[The Exceptions section of the Guzzle documentation](https://docs.guzzlephp.org/en/stable/quickstart.html#exceptions) contains both of the following statements:

> In the event of a networking error (connection timeout, DNS errors, etc.), a GuzzleHttp\Exception\RequestException is thrown.

> A GuzzleHttp\Exception\ConnectException exception is thrown in the event of a networking error.

Given that the tree at the top shows that RequestException and ConnectException objects are exclusive, these statements are clearly contradictory.

**How to reproduce**  
I do not consider this as a behavioral bug.

**Comment by GrahamCampbell** [comment]
I think this is left over from the exception hierarchy in guzzle 6. Guzzle 7 tweaked that stuff. Thanks for the heads up. If you could correct the docs with a PR, that'd be really awesome! Otherwise, I'll get to it whenever I get to it, lol. 🎉

**Comment by Chealer** [comment]
I'm not sure what a PR is, but thank you for the explanation @GrahamCampbell , that makes a lot of sense.

**Comment by GrahamCampbell** [comment]
> PR

Pull request.

**Comment by Nyholm** [comment]
This statement is wrong: 

> In the event of a networking error (connection timeout, DNS errors, etc.), a GuzzleHttp\Exception\RequestException is thrown.

If anybody would like to correct/remove this I would appreciate that.
