### ISSUE TITLE
A specific URL causes Segmentation Fault when running in Docker

### ISSUE THREAD

**Issue by arall** [guzzle/guzzle#2907]
**Guzzle version(s) affected**: 7.3.0
**PHP version**: 7.4.20
**cURL version**: 7.64.0

**Description**  
A specific URL is causing Segmentation Fault when running in Docker, but works outside Docker.
I'm using Docker 20.10.7 in a M1 mac.

**How to reproduce**  
Sample code: 
```
<?php

require __DIR__ . '/vendor/autoload.php';

use GuzzleHttp\Client;

$client = new Client();
$client->request('GET', 'https://registry.yarnpkg.com/@babel/code-frame');

echo 'Executed!';

```

Executed with: `docker run --rm -it -v /path/to/dir:/app php:7.4-fpm php /app/test.php`.

Just in case, here is the composer.json file:
```
{
    "require": {
        "guzzlehttp/guzzle": "^7.3"
    }
}
```

However, if I use `https://google.com/` it works as expected.

**Comment by GrahamCampbell** [comment]
Thanks for getting in touch. segfaults are bugs in PHP itself. Please report this issue to them. :)
