### ISSUE TITLE
Call to undefined function GuzzleHttp\\Psr7\\modify_request()

### ISSUE THREAD

**Issue by sureshkumarsaravanan** [guzzle/guzzle#2912]
**Guzzle version(s) affected**: 2.x

**Description**  
After the latest upgrade, we see the files functions.php and functions_include.php missing under "guzzlehttp/psr7/src"

**How to reproduce**  
Run composer update and see if the files are vanishing

**Possible Solution**  
Replace the required files please

**Additional context**  
This issue may affect globally whoever using your plugin

**Comment by GrahamCampbell** [comment]
Yes. Those functions are not included in v2. Please see the deprecation messages in v1 and upgrade your code to use the new functions. :)

**Comment by sureshkumarsaravanan** [comment]
Thanks Graham!
