### ISSUE TITLE
Stream with digest authentication

### ISSUE THREAD

**Issue by yh1224** [guzzle/guzzle#2913]
**Description**

The request with 'stream' and 'auth' (digest) option doesn't work currently. I hope this works.

**Example**

```php
$client = new Client();
$response = $client->get($url, [
    RequestOptions::STREAM => true,
    RequestOptions::AUTH => [$user, $pass, 'digest']
]);
```

**Comment by Nyholm** [comment]
Why doesn't it work? Do you get any exceptions?

Please provide a Unit test to show how this is broken.

**Comment by yh1224** [comment]
@Nyholm 
It results 401 response.
I understand that the digest authentication is not supported by Streaming handler now.

Request Options - auth - digest
https://docs.guzzlephp.org/en/stable/request-options.html

> This is currently only supported when using the cURL handler, but creating a replacement that can be used with any HTTP handler is planned.

**Comment by GrahamCampbell** [comment]
Streaming is not the same as "using the stream driver". If you have curl installed, you can use the streaming option together with the auth option. :)

**Comment by yh1224** [comment]
@GrahamCampbell Thanks for your answer.

Without stream option, the [CurlHandler](https://github.com/guzzle/guzzle/blob/master/src/Handler/CurlHandler.php) is used but with stream option, [StreamHandler](https://github.com/guzzle/guzzle/blob/master/src/Handler/StreamHandler.php) is used automatically.
How can I use curl with stream option?

**Comment by GrahamCampbell** [comment]
>  But with stream option, the StreamHandler is used automatically.

No, I don't think so?

**Comment by yh1224** [comment]
@GrahamCampbell 
Sorry for my wrong guess.
But it is also true that it does'nt works well, so I'm going to organize again.

Thank you for your answer.
