### ISSUE TITLE
"getaddrinfo() thread failed to start" randomly occurring

### ISSUE THREAD

**Issue by elken** [guzzle/guzzle#2920]
**Guzzle version(s) affected**: 7.2.0
**PHP version**: 
PHP 7.4.16 (cli) (built: Mar  5 2021 07:54:38) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.16, Copyright (c), by Zend Technologies

**cURL version**: 7.68.0

**Description**  
(I can't post the URLs as they're for a private service, the issue is 100% not related to them)

When attempting to run a job in laravel which sends a PUT request to said endpoint, it doesn't complete and errors as below

![image](https://user-images.githubusercontent.com/2872862/127300139-1eee2503-b93d-4344-9b41-bfb55be85400.png)

Despite what the error says, it's not DNS as every other job that hits the service can succeed, and for the specific endpoint we are able to connect in tinker.

**How to reproduce**  

```php
/**
     * Send a PUT request to $url with $data
     *
     * @param string     $url
     * @param array      $data
     * @param array|null $query
     *
     * @throws DealcloudAuthenticationException
     * @throws GuzzleException
     * @throws DealcloudClientException
     * @return mixed
     */
    private function put(string $url, array $data = [], array $query = null, bool $multipartData = false, callable $streamingCallback = null)
    {
        $token = $this->getToken();

        $response = $this->client->request('PUT', $url, array_filter([
            'stream' => $streamingCallback !== null,
            'query' => $query ?? [],
            $multipartData ? 'multipart' : 'json' => $data,
            'headers' => array_filter([
                'Content-Disposition' => $multipartData ? 'model' : [],
                'Accept' => $multipartData ? '*/*' : 'application/json',
                'Authorization' => "Bearer $token",
                'charset' => 'utf-8'
            ])
        ]));

        if ($streamingCallback === null) {
            return $this->verifyBody($response) ? json_decode($response->getBody(), true) : [];
        }
        $stream = StreamWrapper::getResource($response->getBody());
        foreach (JsonMachine::fromStream($stream) as $key => $value) {
            $streamingCallback($key, $value);
        }
    }
```

Is the code responsible
**Possible Solution**  

**Additional context**

**Comment by GrahamCampbell** [comment]
I don't think we can do anything about this. What I'd suggest doing is using a retry middleware, and setting a connect timeout low enough so that you have time for a few retries. :)

**Comment by GrahamCampbell** [comment]
https://github.com/GrahamCampbell/Guzzle-Factory makes Guzzle with some sensible defaults and 3 retries.

**Comment by elken** [comment]
We have, this fails even with retry middleware.

**Comment by GrahamCampbell** [comment]
I don't understand all the downvotes here. You are complaining that the `getaddrinfo` function doesn't work. That's nothing to do with Guzzle? We can't do anything about that.
