### ISSUE TITLE
Guzzle Making Extra GET Requests

### ISSUE THREAD

**Issue by johnxy84** [guzzle/guzzle#2922]
**Guzzle version(s) affected**: 6.5.5
**PHP version**: 7.4.2

**Description**  
When making a PUT request, I see another GET request being made simultaneously 

**How to reproduce**  
Make PUT request using
`$this->client->request('PUT', $url, [
            'headers' => [
                'Content-Type' => "application/json",
            ],
            'json' => $content,
        ]);`

**Additional context**  
![image](https://user-images.githubusercontent.com/16444619/128375007-1f40c474-399b-4bd1-a9d4-5acab7a0b77a.png)

**Comment by mfn** [comment]
I'll bet a 🍺 it's not guzzle but your code/app/framework/etc.

Hope I'm not wrong 😅

- guzzle 6 is not supported anymore
- please provide a small reproducible script

**Comment by GrahamCampbell** [comment]
Going to close this out. If you'd like to provide a way to reproduce this on Guzzle 7, please feel free to open a new issue. Without anything concrete to go on, we can't make any progress here.

**Comment by GrahamCampbell** [comment]
NB The version of PHP you have there is horribly outdated too, FYI.
