### ISSUE TITLE
Timeout not working

### ISSUE THREAD

**Issue by krajcikondra** [guzzle/guzzle#2923]
**Guzzle version(s) affected**: 7.3.0
**PHP version**: 7.4.6
**cURL version**: 7.64.0)

**Description**  
When I disable wifi on my laptop and try send request to some web then I must ever wait over 10 seconds althought I have timeout set to 2 seconds. Timeout in options is ignored?

**How to reproduce**  

```			$options = [
				'request.options' => array (
					'timeout' => 2,
					'connect_timeout' => 2
				),
				'connect_timeout' => 2,
				'read_timeout' => 2,
				'timeout' => 2,
			];

			$client = new Client();
			$response = $client->request('GET', $url, $options);
```

It is some reason why timeout is ignored? I solve situation when remote web is not available or overloaded. I dont want have slow webpage when some remote service is slow. Information from remote webpage are only additional and not important.

**Comment by tsmgeek** [comment]
I also seem to have this but with Guzzle 6.5.5, it may be an internal PHP bug causing it to hang.
