### ISSUE TITLE
Stream with digest authentication doesn't work

### ISSUE THREAD

**Issue by yh1224** [guzzle/guzzle#2924]
**Guzzle version(s) affected**: 7.3.0
**PHP version**: 7.4.22
**cURL version**: 7.78.0

**Description**  
The request with [stream](https://docs.guzzlephp.org/en/stable/request-options.html#stream) and digest [auth](https://docs.guzzlephp.org/en/stable/request-options.html#auth) option doesn't work.

**How to reproduce**  
```php
$client = new Client();
$response = $client->get($url, [
    RequestOptions::STREAM => true,
    RequestOptions::AUTH => [$user, $pass, 'digest']
]);
```

**Additional context**  
Got exception.
```
PHP Fatal error:  Uncaught GuzzleHttp\Exception\ClientException: Client error: `GET http://xxxx` resulted in a `401 Unauthorized` response in xxxx/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:113
```

It works without `RequestOptions::STREAM => true`.
```php
$client = new Client();
$response = $client->get($url, [
    RequestOptions::AUTH => [$user, $pass, 'digest']
]);
```

It works with basic authentication. (This server is configured both of basic and digest authentication.)
```php
$client = new Client();
$response = $client->get($url, [
    RequestOptions::STREAM => true,
    RequestOptions::AUTH => [$user, $pass, 'basic']
]);
```

**Comment by unst** [comment]
Hello, same issue (

**Comment by GergoKormoczy** [comment]
+1

**Comment by fidelix** [comment]
This is still an issue.

**Comment by ghost** [comment]
This still doesn't work.
