### ISSUE TITLE
The save_to config param does not alias to sink, as specified by the deprecation notice in the docs

### ISSUE THREAD

**Issue by validumitruro** [guzzle/guzzle#2925]
**Guzzle version(s) affected**: 7.x
**PHP version**: 8.0.9
**cURL version**: 7.68.0

**Description**  
The docs mention that the save_to option has been deprecated, but it should still work as an alias to sink.

**How to reproduce**  
```
$testUrl = 'https://people.sc.fsu.edu/~jburkardt/data/csv/addresses.csv';
$destinationPath = '/tmp/test-addresses.csv';

$client = new Client();

// This does not work, even though it's supposedly aliased to 'sink'
$client->get($testUrl, ['save_to' => $destinationPath]);

// This works perfectly
$client->get($testUrl, ['sink' => $destinationPath]);
```

I will try to come up with a PR as soon as I get some free time, unless somebody patches this in the meanwhile.

**Comment by GrahamCampbell** [comment]
I think this was deprecated in 6.x and removed in 7?
