### ISSUE TITLE
Can guzzle be expanded to allow requests be ran on remote Internal corporate servers ?

### ISSUE THREAD

**Issue by alfonsoFortinbrass** [guzzle/guzzle#2935]
**Description**
Can guzzle be expanded to allow requests be ran on remote Internal corporate servers ?

**Example**

**Additional context**
instead of using on the command line.

`ssh user@server curl -v ........`

**Comment by GrahamCampbell** [comment]
Thanks for getting in touch. This seems to be quite far out of scope of a bug report on this open source repo, but I can still help you. :) Please get in touch with me at hello@gjcampbell.co.uk and we can discuss rates.
