### ISSUE TITLE
Failed writing header errors

### ISSUE THREAD

**Issue by freekmurze** [guzzle/guzzle#2944]
**Guzzle version(s) affected**: 7.3.0
**PHP version**: 8.0.8
**cURL version**: 7.77.0

**Description**  
Sending a request to some sites now results in error number 23: Failed writing header

**How to reproduce**  
If you send a request to https://www.infino.be/nl using Guzzle 7.3.0 it fails with that error. In 7.2.0 it works

**Possible Solution**  
I've haven't researched the cause any further

**Comment by k3dt** [comment]
I have similar problem (in 7.2.0 ok. 7.3.0 - Failed writing header)
After some debugging i found, problem is in parsing (invalid) response header. 

this is raw response:

> GET / HTTP/1.1
> Host: 100.64.10.250
> Connection: keep-alive
> sec-ch-ua: " Not A;Brand";v="99", "Chromium";v="98", "Opera";v="84"
> sec-ch-ua-mobile: ?0
> sec-ch-ua-platform: "macOS"
> Upgrade-Insecure-Requests: 1
> User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.0.0 Safari/537.36
> Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
> Sec-Fetch-Site: same-origin
> Sec-Fetch-Mode: navigate
> Sec-Fetch-Dest: document
> Referer: https://100.64.10.250/handleform
> Accept-Encoding: gzip, deflate, br
> Accept-Language: cs,en;q=0.9
> Cookie: auth_cookie=0000AKX6Tbpr13

Here is stackdump for Guzzle 7.4.1:
https://www.dropbox.com/s/wyeqtzg9gq3ns6g/Screenshot%202022-02-25%20at%209.12.17.png?dl=0

As you can see, assertHeader throws '"HTTP/1.1 200 OK" is not valid header name' which is OK.. but, is neccessary terminate whole request, instead skipping of this invalid header? Thanks:)

PS: If i skip assertHeader() calling inside setHeaders() in MessageTrait.php, it works.

Thank you, Michal
