### ISSUE TITLE
 Protocol "ttps" not supported or disabled in libcurl

### ISSUE THREAD

**Issue by chama1996** [guzzle/guzzle#2949]
how can i fix this, i am not a developer im totally lost please help

thrown in /home/mizovid1/public_html/api/fetch/streamsb/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php on line 211
[18-Oct-2021 15:49:33 UTC] PHP Fatal error:  Uncaught GuzzleHttp\Exception\RequestException: cURL error 1: Protocol "ttps" not supported or disabled in libcurl (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for ttps://tubesb.com/srzslw396nya.html in /home/mizovid1/public_html/api/fetch/streamsb/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:211
Stack trace:
#0 /home/mizovid1/public_html/api/fetch/streamsb/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(158): GuzzleHttp\Handler\CurlFactory::createRejection()
#1 /home/mizovid1/public_html/api/fetch/streamsb/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(110): GuzzleHttp\Handler\CurlFactory::finishError()
#2 /home/mizovid1/public_html/api/fetch/streamsb/vendor/guzzlehttp/guzzle/src/Handler/CurlHandler.php(47): GuzzleHttp\Handler\CurlFactory::finish()
#3 /home/mizovid1/public_html/api/fetch/streamsb/vendor/guzzlehttp/guzzle/src/Handler/Proxy.php(28): GuzzleHttp\Handler\CurlHandler->__invoke()
#4 /home/mizovid1/public_html/api/fetch/streamsb/vendor/guzzlehttp/guzzle/src/Handler/Proxy.php(48): GuzzleHttp\Handler\Proxy::GuzzleHttp\Handler\{closure}()
#5 /home/mizovid1/public_html/api/fetch/streamsb/vendor/guzzlehttp/guzzle/src/PrepareBodyMiddleware.php(35): GuzzleHttp\Handler\Proxy::GuzzleHttp\Handler\{closure}()
#6 /home/mizovid1/public_html/api/fetch/streamsb/vendor/guzzlehttp/guzzle/src/Middleware.php(31): GuzzleHttp\PrepareBodyMiddleware->__invoke()
#7 /home/mizovid1/public_html/api/fetch/streamsb/vendor/guzzlehttp/guzzle/src/RedirectMiddleware.php(55): GuzzleHttp\Middleware::GuzzleHttp\{closure}()
#8 /home/mizovid1/public_html/api/fetch/streamsb/vendor/guzzlehttp/guzzle/src/Middleware.php(63): GuzzleHttp\RedirectMiddleware->__invoke()
#9 /home/mizovid1/public_html/api/fetch/streamsb/vendor/guzzlehttp/guzzle/src/HandlerStack.php(75): GuzzleHttp\Middleware::GuzzleHttp\{closure}()
#10 /home/mizovid1/public_html/api/fetch/streamsb/vendor/guzzlehttp/guzzle/src/Client.php(331): GuzzleHttp\HandlerStack->__invoke()
#11 /home/mizovid1/public_html/api/fetch/streamsb/vendor/guzzlehttp/guzzle/src/Client.php(168): GuzzleHttp\Client->transfer()
#12 /home/mizovid1/public_html/api/fetch/streamsb/vendor/guzzlehttp/guzzle/src/Client.php(187): GuzzleHttp\Client->requestAsync()
#13 /home/mizovid1/public_html/api/fetch/streamsb/vendor/guzzlehttp/guzzle/src/ClientTrait.php(44): GuzzleHttp\Client->request()
#14 /home/mizovid1/public_html/api/fetch/streamsb/get_ss.php(5): GuzzleHttp\Client->get()
#15 {main}

**Comment by GrahamCampbell** [comment]
You have typoed the URL, missing the h off of https. :)

**Comment by chama1996** [comment]
the link canbe play in the web but it cannot be play in my application

 thrown in /home/mizovid1/public_html/api/fetch/streamsb/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php on line 211
[19-Oct-2021 06:54:05 UTC] PHP Fatal error:  Uncaught GuzzleHttp\Exception\RequestException: cURL error 18: transfer closed with outstanding read data remaining (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://tubesb.com/npmlzppv1ov5.html in /home/mizovid1/public_html/api/fetch/streamsb/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:211
Stack trace:
#0 /home/mizovid1/public_html/api/fetch/streamsb/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(158): GuzzleHttp\Handler\CurlFactory::createRejection(Object(GuzzleHttp\Handler\EasyHandle), Array)
#1 /home/mizovid1/public_html/api/fetch/streamsb/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(110): GuzzleHttp\Handler\CurlFactory::finishError(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))
#2 /home/mizovid1/public_html/api/fetch/streamsb/vendor/guzzlehttp/guzzle/src/Handler/CurlHandler.php(47): GuzzleHttp\Handler\CurlFactory::finish(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHa in /home/mizovid1/public_html/api/fetch/streamsb/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php on line 211
[19-Oct-2021 07:35:07 UTC] PHP Fatal error:  Uncaught GuzzleHttp\Exception\RequestException: cURL error 18: transfer closed with outstanding read data remaining (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://playersb.com/xn58oj6pkeho.html in /home/mizovid1/public_html/api/fetch/streamsb/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:211
Stack trace:
