### ISSUE TITLE
Remove content type header when a redirect changes the method to GET and removes the body

### ISSUE THREAD

**Issue by apokryfos** [guzzle/guzzle#2955]
**Description**
When we redirect as a response to a 303 status, or when using non-strict redirect rules for 301 and 302 statuses, currently any `Content-Type` header is kept. However since there is no content this should be removed. 

**Additional context**
I came across an issue while working with AWS S3 signed URLs. I had an API which responded with a redirect to such a URL to trigger a download of a resource however the validation of the signature failed because validation included headers in this case. 

While I don't think this is a bug, I also don't think the content-type header remains relevant after the content is removed.

**Comment by TimWolla** [comment]
> While I don't think this is a bug, I also don't think the content-type header remains relevant after the content is removed.

The cURL CLI client preserves the 'content-type' header when following a 303 See Other. The correct behavior does not appear to be standardized. In this case I would do what cURL does, because that's generally the right thing. So IMO no change is needed.
