### ISSUE TITLE
Guzzle http does not send a json request to the server

### ISSUE THREAD

**Issue by StasToken** [guzzle/guzzle#2957]
**Guzzle version(s) affected**: 7.4
**PHP version**: 7.4.3
**cURL version**: 7.68.0

**Description**  
Guzzle http does not send a json request to the server

**How to reproduce**  

1. composer init 
2. composer require guzzlehttp/guzzle 
3. touch test.php
4. touch dump.php
**test.php**
```
<?php    require 'vendor/autoload.php';
use GuzzleHttp\Client;

$client = new Client();

$response = $client->post('http://localhost:8000/dump.php', [
    GuzzleHttp\RequestOptions::JSON => ['foo' => 'bar'] // or 'json' => [...]
]);
```
**dump.php**
```
<?php
        ob_start();
        var_dump($_GET,$_POST);
        $output = ob_get_clean();
        file_put_contents('log.txt', $output,FILE_APPEND);
```
> php -S localhost:8000

>php test.php

**Possible Solution**  
not detected

**Additional context**  
Expected result ([according to the documentation](https://docs.guzzlephp.org/en/stable/request-options.html#json)):
Get in log.txt json request sent by the POST method
**The resulting result:**
The request arrives, and the request type is correct

```
[Sat Nov 13 19:34:55 2021] PHP 7.4.3 Development Server (http://localhost:8000) started
[Sat Nov 13 19:36:21 2021] 127.0.0.1:51976 Accepted
[Sat Nov 13 19:36:21 2021] 127.0.0.1:51976 [200]: POST /dump.php
[Sat Nov 13 19:36:21 2021] 127.0.0.1:51976 Closing
```
But cat log.txt

```
array(0) {
}
array(0) {
}

```
Empty, I could not find a solution on the sites, all of the above does not send json in the request body. Can you tell me what I'm doing wrong? or is it still some kind of bug, the examples from the documentation on the link above also do not work, the request body also does not come.

**Comment by GrahamCampbell** [comment]
I think Guzzle is working fine, but your test server is wrong. Replace the `var_dump($_GET,$_POST);` with `stream_get_contents(STDIN);` to see the json request body. PHP won't propulate the POST super global with the json, or even attempt to parse the body. You need to do that yourself. :)

**Comment by GrahamCampbell** [comment]
BTW, Upgrade that PHP version. That one has known security vulnerabilities. ;)

**Comment by StasToken** [comment]
Ok, I see. Thanks.
