### ISSUE TITLE
Is curl exception 28 really a connection exception?

### ISSUE THREAD

**Issue by sandervanhooft** [guzzle/guzzle#2960]
Potential bug.

**Guzzle version(s) affected**: unsure, code has been there for at least 7 years.

**Description**
I am improving the Guzzle integration in a payment platform client where only _connection_ timeout exceptions are allowed to be retried. Retrying any non-connection timeout exception possibly results in issues like performing a payment twice. So I am diving a bit deeper into this than usual. 😄 

Per curl's definition, the curl exception `28 \CURLE_OPERATION_TIMEOUTED` gets triggered on _any_ kind of timeout exception.

If I understand the Guzzle implementation correctly, curl's `28 \CURLE_OPERATION_TIMEOUTED` however is _always_ being used here for triggering a Guzzle connect exception:

https://github.com/guzzle/guzzle/blob/868b3571a039f0ebc11ac8f344f4080babe2cb94/src/Handler/CurlFactory.php#L163-L169

What's the reasoning behind this behaviour? 

**Possible Solutions**

Some ideas include:
- Explain to me how I am getting it all wrong
- Remove curl exception 28 from Guzzle connect exception: potential breaking change, only on next major release
- Make it configurable
- Document or clarify in code the actual logic behind the connection exceptions or the mapping between curl exceptions and Guzzle exceptions (I'm happy to send in a PR once we resolve the issue).

**Context** 

- https://curl.se/libcurl/c/libcurl-errors.html

**Comment by TimWolla** [comment]
Possibly related: #2933

**Comment by Nyholm** [comment]
Does this happen in a version of Guzzle released in the latest 12 months?

**Comment by sandervanhooft** [comment]
Hi @Nyholm !

It appears so, the same code is still on the master branch.

**Comment by sandervanhooft** [comment]
Hi @Nyholm ,

Not sure tbh 😅 .

I have been over the test cases. After a careful inspection it seems to me I should test against the `CurlFactory` to see what's actually happening. Correct?

**Comment by sandervanhooft** [comment]
Not stale
