### ISSUE TITLE
Sending multiselect form values through to endpoint with Guzzle 7.4

### ISSUE THREAD

**Issue by crmpicco** [guzzle/guzzle#2962]
**Guzzle version(s) affected**: 7.4.0
**PHP version**: 7.4.22 (hint: `php --version`)
**cURL version**: 7.78.0 (hint: `php -i | grep cURL`)

**Description**  

I am using `guzzlehttp/guzzle` version 7.4.0 in my Symfony 4.4 project and I am attempting to form data to an end point with the following code:
```
$response = $this->client->request('POST', $url, [
   'form_params' => $params,
   'http_errors' => false,
   'timeout' => 5,
   'verify' => false,
]);
```
$params looks like this:
```
array:16 [▼
  "oid" => "00D751234508hOT"
  "retURL" => "http://crmpicco.co.uk"
  "first_name" => "Stefan"
  "last_name" => "Klos"
  "email" => "crmpicco@crmpicco.co.uk"
  "phone" => "07720962787"
  "description" => "servicehelp"
  "company" => "vtech"
  "country" => "DE"
  "url" => "https://crmpicco-email-val.s.crmpicco.co.uk"
  "00N4P12345GUEH3" => "Marketing"
  "00N4P12345GUEH4" => "Corporate"
  "00N4P12345FpC5G" => "Less than 500"
  "00N4P12345Gm0Qn" => "1,001-10,000"
  "00N4P12345GUEGL" => "White Label"
  "00N4P12345GhXWd" => array:2 [▼
    0 => "Consulting"
    1 => "Hosting"
  ]
]
```
**ALL** of the other fields pull through excluding the "multiple" select (or multiselect) which has two values - Consulting and Hosting.

If I create a simple HTML form, save it as a .html file and submit the form to match my Symfony-built form then the data pulls through to the endpoint fine and when I inspect the data sent through in the browser's console I can see the structure looks like this:
```
{
...
    "00N4P12345GhXWd": [
        "Consulting",
        "Hosting"
    ],
...
}
```
Does Guzzle support a "multiselect" and if so how do I pass this through?

**Comment by GrahamCampbell** [comment]
I don’t think we do, and i’m not sure if it’s actually supported by the RFC to repeat fields?

**Comment by crmpicco** [comment]
It feels like a hacky workaround, but this worked:

`'00N4P12345GhXWd' => implode(';', $servicehelp)`

**Comment by Nyholm** [comment]
That seams about right. Thank you
