### ISSUE TITLE
Is there a way to use SOAP Basic Auth while making a SOAP call?

### ISSUE THREAD

**Issue by federicocandiago** [guzzle/guzzle#2964]
Hello, I need to make a SOAP requestw with Basic Authentication. Following the Auth documentation, I'm calling the request method in this way:

```
<?php
//...
$client = new GuzzleHttp\Client();
$response = $client->request('POST', $soapUri, [
    'body'    => $xmlRequest, // <x:Envelope ... ><x:Header/>...
    'headers' => [
         'Content-Type' => 'text/xml',
         'accept' => '*/*',
         'accept-encoding' => 'gzip, deflate'
    ],
    'auth' => [
        $username // basic auth username,
        $password // basic auth password,
    ]
]);
$responseBody = $response->getBody();
```
But apparently this is not the correct way, as the response I get is "MISSING AUTHENTICATION", despite the Header Authentication in the XML being correct, so those parameters appear not to be passed to the SOAP perver.

Is there a correct way to use the Soap Basic Auth with Guzzle?
Thanks in advance.

**Comment by Martyr2** [comment]
Could it be because you are putting your commas at the end of a comment? You should have your commas after the `$username` variable. Notice where I put the comma

```
'auth' => [
        $username, // basic auth username
        $password // basic auth password
 ]
```

Otherwise that should be the correct way to setup basic auth according to the docs. :)

**Comment by Nyholm** [comment]
Well spotted @Martyr2
