### ISSUE TITLE
self signed certificate suddenly causes curl errors

### ISSUE THREAD

**Issue by justageek** [guzzle/guzzle#2966]
**Guzzle version(s) affected**: 6.5
**PHP version**:7.4.1
**cURL version**: curl-7.76.1-7.amzn2.0.2.x86_64

We have been accessing a third party api for over a year with Guzzle 6.5, then last week the calls suddenly started failing with the error "cURL error 60: SSL certificate problem: self signed certificate in certificate chain", the Guzzle "verify" options has always been left to the default value of true, but apparently that isn't working any more and I have no idea why it would have stopped.  We did change to the new Amazon Linux 2 for our underlying Lambda, so maybe a change in curl versions is the culprit?  Any help is appreciated.

**Comment by GrahamCampbell** [comment]
I think the most likely thing to have happened is one of your certificates has actually expired, or been removed removed from our system's root CA. BTW, Guzzle 6.5 is EOL - please consider upgrading to Guzzle 7.

**Comment by GrahamCampbell** [comment]
>We did change to the new Amazon Linux 2 for our underlying Lambda, so maybe a change in curl versions is the culprit?

I think the change in system CA file is the culprit. ;)
