### ISSUE TITLE
PHP 8.1 support

### ISSUE THREAD

**Issue by isaeken** [guzzle/guzzle#2971]
**Description**
Can PHP version be update to 8.1?

**Comment by GrahamCampbell** [comment]
Yes, we support PHP 8.1

**Comment by GrahamCampbell** [comment]
Note that you will need to use the very latest version of Guzzle 7.

**Comment by isaeken** [comment]
I can't using in PHP 8.1 beacuse missing version in [composer.json](https://github.com/guzzle/guzzle/blob/master/composer.json#L54) ``"php": "^7.2.5 || ^8.0 || ^8.1",`` 
need to add php 8.0 and 8.1 versions separately in composer

**Comment by GrahamCampbell** [comment]
That's not true. Please read the docs for the behaviour of `^` in composer.

**Comment by GrahamCampbell** [comment]
uzzle 6 is in security fix mode only, and does not support PHP 8.0 or 8.1. You'll need to upgrade to Guzzle 7, or support them both in parallel - Guzzle 7 and Guzzle 6 are intentionally very similar to enable people to do that.

**Comment by fgm** [comment]
That's simple for custom projects, not when depending something the size of Drupal.
