### ISSUE TITLE
The `allow_redirects` option doesn't work for `sendRequest` method

### ISSUE THREAD

**Issue by gladyshev** [guzzle/guzzle#2980]
**Guzzle version(s) affected**: 7.3.0
**PHP version**: 8.0.7
**cURL version**: 7.77.0

**Description**  
The `allow_redirects` client option does not work for `sendRequest` method.

**How to reproduce**  

```php
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\Client;

$httpClient = new Client([
    'allow_redirects' => true
]);

$response = $httpClient->sendRequest(new Request('GET', 'https://gmail.com'));

var_dump($response->getStatusCode()); // 301
```

**Possible Solution**  
Before setting the following options, check if the default options are set.

```php
public function sendRequest(RequestInterface $request): ResponseInterface
{
    $options[RequestOptions::SYNCHRONOUS] = true;
    $options[RequestOptions::ALLOW_REDIRECTS] = false;
    $options[RequestOptions::HTTP_ERRORS] = false;

    return $this->sendAsync($request, $options)->wait();
}
```

**Additional context**

**Comment by GrahamCampbell** [comment]
Thanks for getting in touch. This is not a bug, but the intentional behaviour. Please see https://github.com/guzzle/guzzle/issues/2584 for a detailed discussion. I think you need to use the `send` method, instead.

**Comment by gladyshev** [comment]
Thanks for answer. Unfortunately, I can't use the `send` method. I need to make a factory that will return the `\Psr\Http\Client\ClientInterface` with specific follow-redirects behavior. 
Perhaps I need to dig deeper into the middleware mechanism to find a solution.

**Comment by GrahamCampbell** [comment]
I think your factory is returning something that's too granular. Things that implement that shouldn't be following redirects or performing retries. That stuff happens in the layer one above that interface, and it's that next layer up that I think you really wanted, not the psr client interface. While it is possible to manhandle our middleware to still follow redirects even when the config is off, I would not recommend it - you'd be violating the interface.

**Comment by GrahamCampbell** [comment]
There is no standard PSR interface for that next up layer, so you might as well just use the guzzle client interface. :)
