### ISSUE TITLE
Guzzle 6.5.5 Providing RequestException instead of ConnectException

### ISSUE THREAD

**Issue by kcrawford-godaddy** [guzzle/guzzle#2986]
**Guzzle version(s) affected**: 6.5.5
**PHP version**: 7.2.34
**cURL version**: 7.29.0 (hint: `php -i | grep cURL`)

**Description**  

```bash
cURL error 0: The cURL request was retried 3 times
and did not succeed. The most likely reason for the failure
is that cURL was unable to rewind the body of the request
and subsequent retries resulted in the same error. Turn on
the debug option to see what went wrong. See
https://bugs.php.net/bug.php?id=47204 for more information.
(see https://curl.haxx.se/libcurl/c/libcurl-errors.html)
```
This error is delivered as a `RequestException`, but should it not be delivered as a `ConnectException` ? I mean, its a `0` `http_code`.

I'm getting an error from guzzle based on that `_curl_retries` logic in `CurlFactory`.

**How to reproduce**  

will find some time

**Possible Solution**  

none yet

**Additional context**  

happens when making requests to headless chrome by localhost:port

**Comment by GrahamCampbell** [comment]
Is this present in 7.4.1? Guzzle 6 is EOL.

**Comment by kcrawford-godaddy** [comment]
can't say, as we're stuck on an unsupported version of PHP

**Comment by Nyholm** [comment]
Guzzle v6 is "security issues only". 

If we cannot reproduce this bug in v7 then I suggest we close this issue.

**Comment by Jurigag** [comment]
Actually i can confirm that we have RequestException being thrown in some cases also:

```
GuzzleHttp\Exception\RequestException
cURL error 56: OpenSSL SSL_read: Connection reset by peer, errno 104 (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)
```

We use guzzle 7.4.0
