### ISSUE TITLE
i'm trying to install guzzle version 7 and i'm getting this error what should i do

### ISSUE THREAD

**Issue by daliamahmoudd** [guzzle/guzzle#2987]
Root composer.json requires guzzlehttp/guzzle 7.0, found guzzlehttp/guzzle[7.0.0] but these were not loaded, likely 
because it conflicts with another require.

**Comment by GrahamCampbell** [comment]
Looks like you asked for `7.0` instead of `^7.0` by mistake.

**Comment by GrahamCampbell** [comment]
Your error messages says different.

**Comment by daliamahmoudd** [comment]
![lara](https://user-images.githubusercontent.com/95777797/155312669-ca03043c-5a53-462c-9bcd-2a0655ae0c16.PNG)
that's what i'm writing
