### ISSUE TITLE
Warning:  foreach() argument must be of type array|object when response is null

### ISSUE THREAD

**Issue by mynthon** [guzzle/guzzle#2999]
**Guzzle version(s) affected**: 6.3.0
**PHP version**: 8.1.3
**cURL version**: 7.29.0

**Description**  

Guzzle throws warning:
PHP Warning:  foreach() argument must be of type array|object, null given in /vendor/guzzlehttp/guzzle-services/src/ResponseLocation/JsonLocation.php on line 71"

When response JSON is null (not empty but null). Probably the same will happen for true, false and other valid responses that are not object/array/empty.
https://datatracker.ietf.org/doc/html/rfc8259#section-2

**Possible Solution**  
Check if $this->json is iterable before passing it to foreach().

**Comment by GrahamCampbell** [comment]
Thanks for the report, however Guzzle 6 is EOL, and 6.3.0 is not even the latest 6.x version, and also this sounds like an issue in the guzzle-services repo, not Guzzle. Please post a fresh issue there if this occurs with the latest version of Guzzle services and Guzzle 7.

**Comment by GrahamCampbell** [comment]
Current latest versions:

```
guzzlehttp/guzzle: 7.4.2
guzzlehttp/psr7: 2.2.1
guzzlehttp/promises: 1.5.1
guzzlehttp/guzzle-services: 1.3.2
guzzlehttp/command: 1.2.2
guzzlehttp/uri-template: 1.0.1
```

**Comment by GrahamCampbell** [comment]
Note also that Guzzle 6.x does not support PHP 8.1, and 6.3.0 doesn't support PHP later than 7.3.
