### ISSUE TITLE
This required for psr7 should be at least 1.8.4 as there's a security problem with versions before 

### ISSUE THREAD

**Issue by melayyoub** [guzzle/guzzle#3001]
This required for psr7 should be at least 1.8.4 as there's a security problem with versions before 
https://github.com/guzzle/guzzle/blob/e8ed4dbf49b260ff129ff0e0400718c3269971bf/composer.json#L28

**Comment by GrahamCampbell** [comment]
This is not necessary. If composer wants to get an older version of psr7, it'll just get the version of this package one before we bumped the constraint, which is arguably worse.
