### ISSUE TITLE
when `base_uri` like `www.foo.com/bar`, and request `/abc/defg`, final guzzle build url `www.foo.com/abc/defg`

### ISSUE THREAD

**Issue by allowing** [guzzle/guzzle#3003]
**Guzzle version(s) affected**: 7.2.0 or new
**PHP version**: 8.1.0
**cURL version**: x.y.z (hint: `php -i | grep cURL`)

**Description**  
when `base_uri` like `www.foo.com/bar`, and request `/abc/defg`, final guzzle build url `www.foo.com/abc/defg`

**How to reproduce**  
```php
$c = new Client([
    'base_uri' => 'https://github.com/guzzle',
]);

$c->get('/fooo/bar');

// see the request http log
// will find https://github.com/fooo/bar
```
**Possible Solution**  

**Additional context**

**Comment by allowing** [comment]
![image](https://user-images.githubusercontent.com/20262949/161432955-4abf69a5-77ad-4966-84cb-12ec8df4fcd7.png)
The bug is here

**Comment by GrahamCampbell** [comment]
This is not a bug, but the proper behaviour, as per the spec that we follow. We have tests that verify things are working correctly, and those fail when you broke the behaviour in your PR. Thanks, anyway.

**Comment by GrahamCampbell** [comment]
You need to write:
php
```
$c = new Client([
    'base_uri' => 'https://github.com/guzzle/',
]);

$c->get('fooo/bar');
```

**Comment by GrahamCampbell** [comment]
NB This behaviour as as per [RFC 3986, section 5.2](https://tools.ietf.org/html/rfc3986#section-5.2).
