### ISSUE TITLE
atal error: Declaration of Infusionsoft\Http\GuzzleHttpClient::request($method, $uri = NULL, array $options = Array)

### ISSUE THREAD

**Issue by waleed0bjects** [guzzle/guzzle#3007]
**Guzzle version(s) affected**: 7.4.2
**PHP version**: 7.4.28 (hint: `php --version`)
**cURL version**: 7.66.0, OpenSSL/1.1.1n-fips (hint: `php -i | grep cURL`)

**Description**  
 Fatal error: Declaration of Infusionsoft\Http\GuzzleHttpClient::request($method, $uri = NULL, array $options = Array) must be compatible with GuzzleHttp\Client::request(string $method, $uri = '', array $options = Array): Psr\Http\Message\ResponseInterface in /home/customer/www/hydrotab.com/public_html/wp-content/plugins/infusionsoft-for-woocommerce/vendor/infusionsoft/php-sdk/src/Infusionsoft/Http/GuzzleHttpClient.php on line 58

**How to reproduce**  
 when return from about below code execution 
	private function __request_access_token_for_first_time() {
			 
			if ( function_exists( 'wp_verify_nonce' ) && wp_verify_nonce( isset($_GET['code']), 'code' ) ) {
				$dummuy = sanitize_text_field($_GET['code']);
			}
			if (isset($_GET['code'])) {
				try {
					$this->__woo_infusionsoft_api_handler->requestAccessToken( sanitize_text_field($_GET['code']) );
				} catch (Exception $exception) {
					$bypass_sniffer=true;
				}
			} 
			if ( $this->__woo_infusionsoft_api_handler->getToken() ) {
				$token = $this->__woo_infusionsoft_api_handler->getToken();
				Woo_Infusion_API_Handler::update_infusion_soft_token($token);
			}

			//wp_safe_redirect(  );
			header('Location: ' . admin_url( 'admin.php?page=woo-infusionsoft-page' ));

			exit;
		}

**Comment by SachinBahukhandi** [comment]
https://github.com/infusionsoft/infusionsoft-php/issues/67

**Comment by GrahamCampbell** [comment]
This is a bug in infusionsoft.
