### ISSUE TITLE
Error:(313, 53) 'hrtime' is available starting with 7.3 PHP version

### ISSUE THREAD

**Issue by felipenaf** [guzzle/guzzle#3009]
**Guzzle version(s) affected**: 7.4
**PHP version**: 
PHP 7.2.34-28+ubuntu20.04.1+deb.sury.org+1 (cli) (built: Nov 19 2021 06:36:58) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.34-28+ubuntu20.04.1+deb.sury.org+1, Copyright (c) 1999-2018, by Zend Technologies
    with Xdebug v3.1.2, Copyright (c) 2002-2021, by Derick Rethans

**cURL version**: 
cURL support => enabled
cURL Information => 7.68.0

**Description**  
The hrtime function only works in php7.3. Wich version of guzzle can i use in this case ?

**Comment by GrahamCampbell** [comment]
Guzzle works with PHP 7.2.5 or higher. We don't require the hrtime function to exist.
