### ISSUE TITLE
when use retry middleware, if the http status code is 4xx or 5xx, it callable fulfilled, not rejected

### ISSUE THREAD

**Issue by chnljx** [guzzle/guzzle#3012]
is it a bug?

**Comment by GrahamCampbell** [comment]
It depends on what the final state us. If a retry results in a success, it will be fulfilled. Otherwise, it will be rejected.

**Comment by chnljx** [comment]
> It depends on what the final state us. If a retry results in a success, it will be fulfilled. Otherwise, it will be rejected.

I try it 3 times, the final state is 403
`use GuzzleHttp\HandlerStack;
use GuzzleHttp\Handler\CurlHandler;
use GuzzleHttp\Middleware;

$handlerStack = new HandlerStack();
$handlerStack->setHandler(new CurlHandler());

handlerStack->push(Middleware::retry(function($retries, $request, $response, $exception){
            if ($retries >= 3) {
                return false;
            }

            if ($exception instanceof ConnectException) {
                return true;
            }

            if ($response && $response.getStatusCode() === 403) {
                return true;
            }

            return false;
}));
`

**Comment by GrahamCampbell** [comment]
not stale
