### ISSUE TITLE
With default Client and http_errors disabled, cURL errors still thrown

### ISSUE THREAD

**Issue by cscomfort** [guzzle/guzzle#3015]
**Guzzle version(s) affected**: 6.5.5
**PHP version**: 7.4.20
**cURL version**: 7.64.0

**Description**
Following the documentation, I'm trying to disable HTTP errors with a default Client (that, from what I read, should include the GuzzleHttp\Middleware::httpErrors middleware):

```php
use GuzzleHttp\Client;

...

$client = new Client();

$response = $client->request(
    'GET',
    'https://some-nonexistent-host',
    ['http_errors' => false]
);

echo $response->getStatusCode();
```

Instead of echoing the response code, Guzzle returns a cURL error ("Could not resolve host"). Am I, perhaps, overlooking some other Client config parameter?

Thanks in advance.

**Comment by GrahamCampbell** [comment]
That's correct. Disabling http errors means that if you get a non-2xx status code, we don't raise an exception. It does not mean that if you encounter some other kind of error such as DNS resolution or failed TLS negotiation, that we don't raise exceptions. :)
