### ISSUE TITLE
Timeout not being respected (GuzzleHttp\Exception\ConnectException: cURL error 28: Operation timed out )

### ISSUE THREAD

**Issue by allan-simon** [guzzle/guzzle#3016]
**Guzzle version(s) affected**: 7.4.2
**PHP version**: 8.1.6
**cURL version**:  7.83.1

**Description**  
Even though we configured the guzzle client to timeout after 6.0 seconds, we often get timeout exception exceeding this time 

ex:

* GuzzleHttp\Exception\ConnectException: cURL error 28: Operation timed out after 67171 milliseconds
* GuzzleHttp\Exception\ConnectException: cURL error 28: Operation timed out after 122671 milliseconds 

Note: it also works sometimes 

**How to reproduce**  
```
        $this->client = new GuzzleClient([
            'handler' => $this->stack,
            'base_uri' => $baseUrl,
            'connect_timeout' => 6.0,
            'timeout' => 6.0,
            'read_timeout' => 6.0, // should not be needed as it's not a stream request , but we were desperate 
            'cookies' => true,
        ]);
```

it only happens to us with one specific host (as it's a private API from a 3rd party we can't post it here, but we can provide details in private.

**Comment by allan-simon** [comment]
the issue is still occuring

**Comment by allan-simon** [comment]
still occuring

**Comment by Tanguy-Magnaudet** [comment]
Hello,

I'm facing the same problem and the ConnectException error seems uncatchable.

**Comment by GrahamCampbell** [comment]
As far as I can tell, the timeout controls come from inside curl, and there's nothing we can do to mitigate/work around any funky behaviour there. You could try opening an issue with curl to clarify with them why this is happening.

**Comment by karliehgf** [comment]
> As far as I can tell, the timeout controls come from inside curl, and there's nothing we can do to mitigate/work around any funky behaviour there. You could try opening an issue with curl to clarify with them why this is happening. All other PHP HTTP clients using curl will be in the same boat, too.

hi, did you try to change it to use php curl to send the same request? And dit it work well?
