### ISSUE TITLE
Add small fix to support PHP8.1 as used by Behat 3 with Drupal 9.3

### ISSUE THREAD

**Issue by fgm** [guzzle/guzzle#3020]
**Guzzle version(s) affected**: 6.5.6
**PHP version**: 8.1.6
**cURL version**: 7.83.1

**Description**  
Guzzle is compatible with PHP 8.1 in 7.x versions, but not in 6.x versions.

This is a problem when using Behat 3 with Drupal latest 9.3.x, which is locked to Guzzle ^6.5.6 while recommending PHP 8.1 in preperation for 9.4.

Running Behat 3 in that case causes these two warnings:

```
Deprecated: Return type of GuzzleHttp\Cookie\CookieJar::count() should either be compatible with Countable::count(): int, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /Users/fgm/src/GammVert/magpj/vendor/guzzlehttp/guzzle/src/Cookie/CookieJar.php on line 220

Deprecated: Return type of GuzzleHttp\Cookie\CookieJar::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /Users/fgm/src/GammVert/magpj/vendor/guzzlehttp/guzzle/src/Cookie/CookieJar.php on line 225
``` 

**How to reproduce**  

- Build a Drupal 9.3 recommended-project
- Composer require --dev behat/behat

**Possible Solution**  

I just tested, and patching Guzzle with just these two methods ` #[\ReturnTypeWillChange]` attributes fixes the problem with PHP 8.1 and does not break 7.x, so it would let 6.5.x remain compatible with earlier versions while allowing use with PHP 8.1. 

I can submit a PR if you want.

**Additional context**  

Not the same issue as #2971

**Comment by fgm** [comment]
Here is a patch containing the suggested fix: [guzzle-3020.patch.txt](https://github.com/guzzle/guzzle/files/8833852/guzzle-3020.patch.txt)

**Comment by GrahamCampbell** [comment]
Guzzle 6 is in security fix mode only, and does not support PHP 8.0 or 8.1. You'll need to upgrade to Guzzle 7, or support them both in parallel - Guzzle 7 and Guzzle 6 are intentionally very similar to enable people to do that.

**Comment by fgm** [comment]
@GrahamCampbell That's simple for fully custom code, not when depending on something the size of Drupal + Behat locking you out of V7.

**Comment by wayne-weibel** [comment]
Issue still exists in Drupal 9.4.8, locked to Guzzle 6.

**Comment by azovsky** [comment]
[Moving from drupal/core-recommended to drupal/core](https://www.drupal.org/docs/develop/using-composer/manage-dependencies#s-moving-from-drupalcore-recommended-to-drupalcore) can help with Drupal + Guzzle 7.

**Comment by GrahamCampbell** [comment]
Like I said, Guzzle 6 does not support PHP 8. You should only run Drupal 6 on PHP 7.4. If they say they are compatible with PHP 8.0 or 8.1, they are mistaken.

**Comment by GrahamCampbell** [comment]
That patch you provide there is not enough to actually support PHP 8. There were major changes needed, which were only applied to Guzzle 7.
