### ISSUE TITLE
Getting Fatal Error for PhP Version not greater than or equal to 8.1.0

### ISSUE THREAD

**Issue by frogydiak** [guzzle/guzzle#3048]
**Guzzle version(s) affected**: 7.4.5
**PHP version**: 8.0.2 (hint: `php --version`)
**cURL version**: 7.61.1 (hint: `php -i | grep cURL`)

**Description**  
I just downloaded Guzzle, the latest version and it says it is compatible with PhP 7.2 to 8.0 but when I just added:

require __DIR__ . '/vendor/autoload.php';

I get a Fatal Error:

Fatal error: Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 8.1.0". You are running 8.0.20. in /var/www/html/vendor/composer/platform_check.php on line 24

I thought it's compatible with Php 7.2.x upto 8.0? Am I doing something wrong?

**Comment by GrahamCampbell** [comment]
This happens if you run composer as PHP 8.1. You need to run composer using PHP 8.0 or set platform config to lock to PHP 8.0.

**Comment by frogydiak** [comment]
@GrahamCampbell Got it! Thank you!
