### ISSUE TITLE
Unexpected HTTP/1.x request

### ISSUE THREAD

**Issue by srinivaskolla** [guzzle/guzzle#3058]
**Guzzle version(s) affected**: 6.5
**PHP version**: 7.4.3 
**cURL version**: Not Installted (hint: `php -i | grep cURL`)

**Description**  
When giving a POST request to Apple Push Notification Servers, I am getting the following error.
RuntimeException: HTTP version missing from header data in  guzzlehttp/guzzle/src/Handler/HeaderProcessor.php:34
: GuzzleHttp\Handler\HeaderProcessor::parseHeaders()
**How to reproduce**  
  https://api.sandbox.push.apple.com/3/device/

**Possible Solution**  

**Additional context**

**Comment by GrahamCampbell** [comment]
Thanks for getting in touch. Guzzle 6 is EOL, and PHP 7.4.3 is not the latest version of PHP. Please open a new issue if you encounter this issue with the latest version of PHP 7.4 (or PHP 8) and the latest version of Guzzle 7.
