### ISSUE TITLE
报错 Status code must be an integer value between 1xx and 5xx.

### ISSUE THREAD

**Issue by suxiangw** [guzzle/guzzle#3059]
运行下面代码直接报错 “Status code must be an integer value between 1xx and 5xx.”
如何解决？
 
try {
     $res = $client->request('GET', 'https://www.apicloud.com/addApp');
     echo $res->getBody();
} catch (RequestException $e) {
    echo $e->getRequest();
    if ($e->hasResponse()) {
        echo $e->getResponse();
    }
}

**Comment by GrahamCampbell** [comment]
Please raise this issue with apicloud.com. They are not conforming to the HTTP spec. This is an issue on their side.
