### ISSUE TITLE
Request to php file directly

### ISSUE THREAD

**Issue by Mirmuxsin** [guzzle/guzzle#3062]
**Guzzle version(s) affected**: 6.5.5
**PHP version**: 7.3

**Description**  
I can't do request to site.com/login.php

**How to reproduce**  
Just allow to do request to files directly

**Comment by GrahamCampbell** [comment]
Thanks for getting in touch. We'll need more details than this. Are you trying to download a local file, without running a PHO-FPM server?

**Comment by andresayac** [comment]
Provide more information is not very clear to me

**Comment by GrahamCampbell** [comment]
This sounds like a configuration issue on your web server, not a bug with Guzzle. I'd recommend asking on some forums or getting some paid help.
