### ISSUE TITLE
Deprecated: Implicit conversion from float to int

### ISSUE THREAD

**Issue by utdrmac** [guzzle/guzzle#3071]
**Guzzle version(s) affected**: Unknown, aws-php 3.235.0
**PHP version**: 8.1.8
**cURL version**:  7.84.0

**Description**  
```
PHP Deprecated:  Implicit conversion from float 14999979.763058946 to int loses precision in phar:///Users/ghost/aws/aws.phar/GuzzleHttp/Handler/CurlMultiHandler.php on line 143
```

**How to reproduce**  
Use the aws-php library, which includes Guzzle, to launch an EC2 instance. Warnings ensue.

**Possible Solution**  
Unknown. Probably some code patch will fix it?

**Additional context**  
None

**Comment by utdrmac** [comment]
The AWS guys said that since this is an issue with your library, I should open an issue here and not with their codebase.

**Comment by GrahamCampbell** [comment]
What version of Guzzle is used here please?

**Comment by utdrmac** [comment]
Looks like 7.4.5
https://github.com/aws/aws-sdk-php/blob/master/composer.json#L20

**Comment by mfn** [comment]
At minimum, but optionally also 6. It depends on other dependencies you might have.

You can tell the exact version with `composer show guzzlehttp/http`.

It would also be good to provide a full stacktrace.

**Comment by GrahamCampbell** [comment]
Looks like they are bunnding 6.5.5 in their phars. That means their Phars only work on PHP 5.5-7.4, and not PHP 8.

**Comment by utdrmac** [comment]
Thanks for the investigation.
