### ISSUE TITLE
Support named arguments instead of config arrays.

### ISSUE THREAD

**Issue by luckydonald** [guzzle/guzzle#3074]
**Description**
Add support for php 8.0's [Named Arguments](https://www.php.net/manual/en/functions.arguments.php#functions.named-arguments) for what previously would be an `$config` array.

This has the advantage that there could be strict typing, as well as better IDE code hints.

Yes, calling with named arguments, that is a PHP 8+ feature, but not on the function (i.e. guzzle) side.
There it would be just optional parameters in the constructor, and thus it would be both **backwards compatible with existing implementations, as well as compatible with PHP 7**.

So in detail this would mean to add optional arguments for all the settable options. Those would default to `null`,  and once it's set to something proper by the caller, it will be merged into the options array. Alternatively the options array could fill variables instead, but that would be a bigger change which would make this change too heavy, and if wanted I'd like to do separately. 

Overall I think it makes sense to embrace that new language feature.

---

**Example**

Before:
```php
use GuzzleHttp\Client;

$client = new Client([
    'base_uri' => 'http://httpbin.org',
    'timeout'  => 2.0,
]);
```
After:

```php
$client = new Client(baseUri: 'http://httpbin.org', timeout: 2.0);
```

---

With the `GuzzleHttp\Client` changing like this:
Before:
```php
public function __construct(array $config = []) {
    …
```
After:
```php
public function __construct(array $config = [], string $baseUri = null, float timeout = null, …) {
    …
```

---

**Additional context**

> Screenshot of some code completion:
> <img width="738" alt="Screenshot 2022-09-21 at 10 25 19" src="https://user-images.githubusercontent.com/2737108/191454770-dc51a17e-2527-4777-83b4-bd56825d7f85.png">

---

Should I prepare a PR for that?

**Comment by GrahamCampbell** [comment]
Apologies for the delay here. No, I don't like named parameters, and many major codebases, including the Laravel Framework do not consider parameter names to be part of the BC policy, making them largely unusable in practice, outside of application code calling application code.
