### ISSUE TITLE
create an addHeaders() method if getConfig is being deprecated?

### ISSUE THREAD

**Issue by treii28** [guzzle/guzzle#3076]
**Description**
Many apis require an Authorization header or similar credentials to function properly. Guzzle seems to support adding headers when a client is created, then has an ability to supply headers in options when a request is actually made. The problem is that when authorization is added when creating the client, supplying headers in a request over-writes any values that were in the client headers.  The Authorization header goes bye-bye!

It therefore, might be useful to have an ability to specify 'additional' headers when making a request as opposed to replacing headers when 'headers' is included in a request's options.

**Example**
I discovered this when it was necessary to add a Content-type header in a specific post using a client that was created from another method which added in the Authorization header:

    function getClient() {
        return new Client([
            'base_uri' => 'https://api.somehost.com/v1/',
            'headers' => [
                'Authorization' => 'Bearer ' . env('MY_API_TOKEN')
            ]
        ]);
    }

    function getData($requestJson) {
        $client = $this->getClient();
        $responseStream = $client->post(
                sprintf("data/%s/details.json", env("DATA_SOURCE_ID")),
                [
                    'headers' => [ // including this negates the client's Authorization header
                        'Content-Type' => 'application/json',
                        'Accept' => 'application/json'
                    ],
                    'body' => $requestJson
                ]
            );
        return $responseStream->getBody()->getContents();
    }

**Additional context**
    My first thought was to pull the existing headers from the client and doing an array merge. But there did not seem to be a 'getHeaders()' method and 'getConfig("headers")' appears to be subject to deprecation.
    Perhaps another way to go about this would be to always do an array merge of the headers whenever a request is being made.

**Comment by CharlieLaver** [comment]
Adding a getHeaders() method to the Client class will be useful (especially as getConfig() is being depreciated).
I am happy to implement this.
