### ISSUE TITLE
PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 118784 bytes) in /www/wwwroot/wallet/vendor/guzzlehttp/psr7/src/Utils.php on line 414

### ISSUE THREAD

**Issue by phpmac** [guzzle/guzzle#3077]
PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 118784 bytes) in /www/wwwroot/wallet/vendor/guzzlehttp/psr7/src/Utils.php on line 414

   Symfony\Component\ErrorHandler\Error\FatalError 

  Allowed memory size of 134217728 bytes exhausted (tried to allocate 118784 bytes)

  at vendor/guzzlehttp/psr7/src/Utils.php:414
PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 135168 bytes) in /www/wwwroot/wallet/vendor/nunomaduro/collision/src/Highlighter.php on line 155

**Comment by GrahamCampbell** [comment]
This is because you have some code somewhere that is trying to load the entire body into memory. This is not a bug with our code. If the body is large, then you won't be able to do that.
