### ISSUE TITLE
"SIGSEGV" error

### ISSUE THREAD

**Issue by cryzyor** [guzzle/guzzle#3094]
**Guzzle version(s) affected**: 6.3.0
**PHP version**: 7.2.34 (hint: `php --version`)
**cURL version**: 7.64.0 (hint: `php -i | grep cURL`)

**Description**  
When requesting other service interfaces, if the other party puts back the status code "999", the current process will report an error of "SIGSEGV", causing the process to restart

child 60 exited on signal 11 (SIGSEGV) after 67.959713 seconds from start
child 101 started

**How to reproduce**  

Only when the status code is 999, other status codes are normal, and only online, but not local. How to solve this problem

linux core:Linux 192.168.90.26 3.10.0-1160.el7.x86_64

**Possible Solution**  

**Additional context**

**Comment by GrahamCampbell** [comment]
Segfaults are a bug in PHP itself, and need to be reported to the PHP team. I'm sorry that there's nothing we can do here in userland.

**Comment by cryzyor** [comment]
Thank you
