### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by navaranjithsai** [guzzle/guzzle#3096]
Please consider using one of the issue templates (bug report, feature request).
installing guzzle using composer facing errors like Failed to download phpunit/php-text-template from dist: The zip extension and unzip/7z commands are both missing, skipping. most of the files are getting this type of errors and also failing psr/http-client. I have tried using document from guzzle document webpage.
![image](https://user-images.githubusercontent.com/39221284/212556188-f2695d8b-035c-4b91-9867-0fcf1656fcc8.png)
and
![image](https://user-images.githubusercontent.com/39221284/212556212-991ca87f-b3ca-4dad-8a19-af02495ef572.png)

**Comment by GrahamCampbell** [comment]
This issue doesn't look to be related to Guzzle. There's nothing we can do here on our side to make a difference here, sorry.
