### ISSUE TITLE
The http_errors option doesn't work for sendRequest method

### ISSUE THREAD

**Issue by cxlblm** [guzzle/guzzle#3097]
**Guzzle version(s) affected**: 7.5.0
**PHP version**: 8.2.1
**cURL version**: 7.87.0

**Description**  
The http_errors client option does not work for sendRequest method.

**How to reproduce**  
```
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\Client;

$httpClient = new Client(); 

$response = $httpClient->sendRequest(new Request('GET', 'https://gmail.com/test_path'));

var_dump($response->getStatusCode()); // 404
```

**Possible Solution**  
Before setting the following options, check if the default options are set.
```
public function sendRequest(RequestInterface $request): ResponseInterface
{
    $options[RequestOptions::SYNCHRONOUS] = true;
    $options[RequestOptions::ALLOW_REDIRECTS] = false;
    $options[RequestOptions::HTTP_ERRORS] = false;

    return $this->sendAsync($request, $options)->wait();
}
```
**Additional context**

**Comment by micahbule** [comment]
While I can confirm the issue, further searching within the repo suggests that it is by purpose. Looking at #3088, it seems like the option to override `http_errors` for the `sendRequest()` method was done on purpose to adhere to [PSR-18](https://www.php-fig.org/psr/psr-18/#error-handling) standards for error handling -- which makes sense.

Just feels weird that this is not documented properly given the code in question is already 3 years old and that anyone who would use this library for API wrappers would more likely use the `sendRequest()` method after crafting resource requests objects.

**Comment by cxlblm** [comment]
The case is in compliance with the psr-18 specification
