### ISSUE TITLE
Make RequestOptions extendable - remove the final keyword

### ISSUE THREAD

**Issue by ignas-poklad** [guzzle/guzzle#3099]
I'd like to propose removing the final keyword from the RequestOptions. 
With the final keyword, it is impossible to extend the RequestOptions to add more constants. This is quite useful when you have a big project with multiple developers and you tend to use the Guzzle client with the same custom middleware that has numerous options. In IDE you'd get autocompletion and documentation.

**Comment by GrahamCampbell** [comment]
I would never recommend extending a class to add more constants. Just make a new class?

**Comment by ignas-poklad** [comment]
@GrahamCampbell Why? So I have to make a new class and just copy everything from RequestOptions manually? Or every time I want to use Guzzle, I write `use RequestOptions` and `use MyOwnOptions` and then try to figure out in which of them a specific option I need is located? How these two scenarios are any better?

If in my specific use case I want to use a specific middleware every time, why can't I create my own options class that extends the RequestOptions? What's the big deal? It does not affect Guzzle project.

The reason why having custom Options is so useful is due to the way Guzzle middlewares work. The single set of options is passed to all of them, meaning that there has to be a single set of Options. Option names need to be unique.
