### ISSUE TITLE
PHP 8.2: Creation of dynamic property GuzzleHttp\Psr7\MultipartStream::$stream is deprecated

### ISSUE THREAD

**Issue by SejberCze** [guzzle/guzzle#3102]
guzzlehttp/guzzle                    7.5.0
guzzlehttp/promises                  1.5.2
guzzlehttp/psr7                      1.9.0
PHP 8.2.3
Apache/2.4.33 (Unix)
nette/application 3.1.10

Deprecated: Creation of dynamic property GuzzleHttp\Psr7\MultipartStream::$stream is deprecated

![image](https://user-images.githubusercontent.com/20661934/220668579-b5d2d396-749f-4890-9681-f4e6c88f11a5.png)

**Comment by TimWolla** [comment]
> guzzlehttp/psr7 1.9.0

Upgrade to guzzlehttp/psr7 2.4.x.

**Comment by GrahamCampbell** [comment]
As per https://github.com/guzzle/psr7#version-guidance, the 1.x line of our psr7 package only supports up to PHP 8.0. Not 8.1 or 8.2.

**Comment by GrahamCampbell** [comment]
You can use `composer why guzzlehttp/psr7` to find out why you have 1.x btw - chances are some other package you are using is asking for 1.x - you can upgrade them to 1.x || 2.x or just 2.x, or at least let them know.
