### ISSUE TITLE
The host from the PSR-7 request is empty for a relative URI and a client created with a base_uri

### ISSUE THREAD

**Issue by robopzet** [guzzle/guzzle#3105]
**Guzzle version(s) affected**: 7.5.0
**PHP version**: 8.1.6
**cURL version**: 7.11.0

**Description**  
A method to perform requests receives a standard PSR ClientInterface and RequestInterface. To log errors when performing the requests I want to retrieve the complete URL of the request.

According to [the documentation](https://docs.guzzlephp.org/en/stable/psr7.html#host) that should be possible with `$req->getUri()->getHost()` or `$req->getHeader('Host')`. The first option returns an empty string, the second an empty array.

Because I don't want to force the use of Guzzle, I only want to use the methods of the PSR compatible interfaces.

The client is created with the `base_uri` option.

**How to reproduce**  
```php
<?php
declare(strict_types = 1);

use GuzzleHttp\Client;
use GuzzleHttp\Psr7\Request;
use Psr\Http\Client\ClientInterface;
use Psr\Http\Message\RequestInterface;

require_once 'vendor/autoload.php';

function doreq (
    ClientInterface     $clt,
    RequestInterface    $req
): void {
    var_dump(
        $req->getMethod(),
        $req->getUri()->getHost(),
        $req->getHeader('Host'),
        $req->getUri()->getPath());

    $resp = $clt->sendRequest($req);
    var_dump($resp->getStatusCode());
}

doreq(
    new Client(['base_uri' => 'https://example.com']),
    new Request('GET', '/xyz'));
```

Output:
```
string(3) "GET"
string(0) ""
array(0) {
}
string(4) "/xyz"
int(404)
```

**Comment by GrahamCampbell** [comment]
Everything you have written there looks like not a bug. There's no way the request will have its host set before you give it to the client? If you are add dumps later on inside the guzzle code or enable the log middlware, you will see the host header does eventually get added.

**Comment by robopzet** [comment]
After the request is done the values I see are still empty for `$req->getUri()->getHost()` and `$req->getHeader('Host')`.

**Comment by GrahamCampbell** [comment]
That is because we don't mutate the original request object.

**Comment by GrahamCampbell** [comment]
https://github.com/gmponos/guzzle-log-middleware

**Comment by robopzet** [comment]
Clients and requests can be provided by other packages, which may use their own implementation. It looks like I can't use the PSR interfaces for this. Thanks for the info.
