### ISSUE TITLE
Fatal error: Uncaught Error: Class 'Utils' not found

### ISSUE THREAD

**Issue by Dravenrip** [guzzle/guzzle#3107]
**Guzzle version(s) affected**: 7.5.0
**PHP version**: 7.4.30 and 8.0.22 (hint: `php --version`)
**cURL version**: 7.88.1

i'm trying Guzzle for the first time to do API request and sending files.

My code is based on postman exemple and look like this `<?php

use GuzzleHttp\Client;

$client = new Client();
$headers = [
  'Authorization' => 'Basic mflzelkazlerjalzker',
];
$options = [
  'multipart' => [
    [
      'name' => 'request',
      'contents' => '{
  "shouldStartWKF": false,
  "company": "ALP_MO",
  "tenant": "ALP_MO",
  "initializeIndexFromActId": false,
  "list": [
    {...}'
    ],
    [
      'name' => 'files',
      'contents' => Utils::tryFopen('PATH_TO_my_file.pdf', 'r'),
      'filename' => 'my_file.pdf',
      'headers'  => [
        'Content-Type' => '<Content-type header>'
      ]
    ]
]];
$request = new Request('POST', URL , $headers);
$res = $client->sendAsync($request, $options)->wait();
`

But i get an error who says "Fatal error: Uncaught Error: Class 'Utils' not found ... " and i can't understand why... 

if it can help : 
`composer show | grep guzzle

guzzlehttp/guzzle                7.5.0     Guzzle is a PHP HTTP client library
guzzlehttp/promises              1.5.2     Guzzle promises library
guzzlehttp/psr7                  2.4.4     PSR-7 message implementation that also provides common utility methods`

thanks for your help

**Comment by GrahamCampbell** [comment]
It looks like you need to import the Utils class.

**Comment by Dravenrip** [comment]
oh yes ! exactly ! 
thank you !
