### ISSUE TITLE
Supporting PHP 8.1 in Guzzle 6

### ISSUE THREAD

**Issue by ingluisjimenez** [guzzle/guzzle#3109]
**Guzzle version(s) affected**: 6.5.x
**PHP version**: 8.1.x 

**Description**  
@GrahamCampbell Thank you for your continuing work supporting this great project.

We have been using it with PHP 8.0 for a couple of years without any issues and are in the process to migrate a large project to 8.1. We are aware that Guzzle 6 is only receiving security updates, but seems like there is only a minor issue to allow it to work with PHP 8.1. 

Would you be open to merge/release a [very small pull-request](https://github.com/guzzle/guzzle/pull/3110) that addresses the compatibility issue with PHP 8.1? It would basically need this same change https://github.com/guzzle/guzzle/commit/74ca2cb463a7a99a0b99f195ca809cc4ba6c3147?

We are onboard with the option of moving to Guzzle 7, but we are in the last steps of migrating to PHP 8.1 and that would introduce an additional set of requirements for the migration.

**How to reproduce**  
N/A

**Possible Solution**  
https://github.com/guzzle/guzzle/commit/74ca2cb463a7a99a0b99f195ca809cc4ba6c3147

**Additional context**  
N/A

**Comment by GrahamCampbell** [comment]
No, it is not possible to support PHP 8 in Guzzle 6. We don't just not support PHP 8.1, but we also don't support PHP 8.0 on Guzzle 6. That very small pull request is not any where near enough to support PHP 6 - we had to change thousands of lines in Guzzle 7 to support PHP 8.0, 8.1, and then 8.2, combined.

**Comment by GrahamCampbell** [comment]
You may find that Guzzle 6 appears to work with PHP 8.0, but are likely experiencing bugs and not even knowing, since it can "do the wrong thing", but not crash. I would very strongly recommend only using Guzzle 7 on any PHP 8 version.

**Comment by ingluisjimenez** [comment]
Thank you for the feedback. I am surprised that you expect Guzzle 6 to not work at all with PHP 8.0, as we have been using it extensively for about 2 years now without any issues.

With that said, we will pursue the upgrade to Guzzle 7.

**Comment by GrahamCampbell** [comment]
I don't remember all the details, but I think one of the handlers was affected more than the other (either the curl one, or the php streams one). Depending on which you are using, you may experience fewer issues. The supported PHP versions are documented at: https://github.com/guzzle/guzzle#version-guidance.

**Comment by GrahamCampbell** [comment]
We also made upgrading to Guzzle 7 as easy as we could, so that people could get onto PHP 8 quickly. Most users will not need to change any code.

**Comment by GrahamCampbell** [comment]
See https://github.com/guzzle/guzzle/blob/master/UPGRADING.md#other-backwards-compatibility-breaking-changes and https://github.com/guzzle/psr7#upgrading-from-function-api.

**Comment by ingluisjimenez** [comment]
Thank you for the guidance. 

We have an internal package that wraps Guzzle and adds a few features on top of it. Updating that to use Guzzle 7 seemed straightforward. One of the main areas where we saw breaking changes was with the Request exceptions, and luckily we have our own exceptions equivalent to the Guzzle ones, so our services will require minor changes if any.

**Comment by Bendihossan** [comment]
Is there any reason the [supported versions](https://github.com/guzzle/guzzle#version-guidance) documented are not enforced by composer version constraints? 

E.g.: shouldn't this show >= 5.5 < 8.0?
<img width="867" alt="Screenshot 2023-05-05 at 11 26 42" src="https://user-images.githubusercontent.com/593224/236434755-da112c56-af91-4211-98d4-dc9c4ca342af.png">

I think that would help prevent people using of guzzle on unsupported platform versions.

**Comment by GrahamCampbell** [comment]
It is too late to make that change (Composer will just install an older version of Guzzle 6, which is arguably worse), and it is common place to not do that in any case - see https://github.com/symfony/symfony/issues/42993.

**Comment by GrahamCampbell** [comment]
That is, support for new PHP version is treated as a bug fix, and as Guzzle 6 is out of bug fix support, that is a bug that will not be fixed.
