### ISSUE TITLE
Effective URL

### ISSUE THREAD

**Issue by ghost** [guzzle/guzzle#311]
I don't seem to find a way to access the effective URL for a request. What I mean by that is the URL after a redirect has happened.

Curl has an option to find that via CURLINFO_EFFECTIVE_URL - but guzzle doesn't seem to. Can this be added?

Apologies if I'm mistaken.

**Comment by sikanderiqbal** [comment]
This is why OSS is awesome :+1: 

Thanks @mtdowling!
