### ISSUE TITLE
Error Call to undefined function GuzzleHttp\Psr7\get_message_body_summary()

### ISSUE THREAD

**Issue by ysilvela** [guzzle/guzzle#3111]
**Guzzle version(s) affected**: x.y.z
**PHP version**: x.y.z (hint: `php --version`) 7.4
**cURL version**: x.y.z (hint: `php -i | grep cURL`) support enabled and 7.87.0

**Description**  
Error: Call to undefined function GuzzleHttp\Psr7\get_message_body_summary() in 
/home/appli/public_html/clientarea/includes/ovhcloudlib/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:127
Stack trace:
#0 /home/appli/public_html/clientarea/includes/ovhcloudlib/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php(107): GuzzleHttp\Exception\RequestException::getResponseBodySummary(Object(GuzzleHttp\Psr7\Response))
#1 /home/appli/public_html/clientarea/includes/ovhcloudlib/vendor/guzzlehttp/guzzle/src/Middleware.php(65): GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Psr7\Request), Object(GuzzleHttp\Psr7\Response))
#2 /home/appli/public_html/clientarea/includes/ovhcloudlib/vendor/guzzlehttp/promises/src/Promise.php(204): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Response))
#3 /home/appli/public_html/clientarea/includes/ovhcloudlib/vendor/guzzlehttp/promises/src/Promise.php(153): GuzzleHttp\Promise\Promise::callHandler(1, Object(GuzzleHttp\Psr7\Response), NULL)
#4 /home/appli/public_html/clientarea/includes/ovhcloudlib/vendor/guzzlehttp/promises/src/TaskQueue.php(48): GuzzleHttp\Promise\Promise::GuzzleHttp\Promise\{closure}()
#5 /home/appli/public_html/clientarea/includes/ovhcloudlib/vendor/guzzlehttp/promises/src/Promise.php(248): GuzzleHttp\Promise\TaskQueue->run(true)
#6 /home/appli/public_html/clientarea/includes/ovhcloudlib/vendor/guzzlehttp/promises/src/Promise.php(224): GuzzleHttp\Promise\Promise->invokeWaitFn()
#7 /home/appli/public_html/clientarea/includes/ovhcloudlib/vendor/guzzlehttp/promises/src/Promise.php(269): GuzzleHttp\Promise\Promise->waitIfPending()
#8 /home/appli/public_html/clientarea/includes/ovhcloudlib/vendor/guzzlehttp/promises/src/Promise.php(226): GuzzleHttp\Promise\Promise->invokeWaitList()
#9 /home/appli/public_html/clientarea/includes/ovhcloudlib/vendor/guzzlehttp/promises/src/Promise.php(62): GuzzleHttp\Promise\Promise->waitIfPending()
#10 /home/appli/public_html/clientarea/includes/ovhcloudlib/vendor/guzzlehttp/guzzle/src/Client.php(129): GuzzleHttp\Promise\Promise->wait()
#11 /home/appli/public_html/clientarea/includes/ovhcloudlib/vendor/ovh/ovh/src/Api.php(306): GuzzleHttp\Client->send(Object(GuzzleHttp\Psr7\Request), Array)
#12 /home/appli/public_html/clientarea/includes/ovhcloudlib/vendor/ovh/ovh/src/Api.php(344): Ovh\Api->rawCall('GET', '/me', NULL, true, Array)
#13 /home/appli/public_html/clientarea/includes/ovhcloud.php(25): Ovh\Api->get('/me')
#14 /home/appli/public_html/clientarea/modules/servers/ovhcloud/ovhcloud.php(25): ovhcloudWrapper->__construct()
#15 /home/appli/public_html/clientarea/vendor/whmcs/whmcs-foundation/lib/Module/AbstractModule.php(0): ovhcloud_ConfigOptions(Array)
#16 /home/appli/public_html/clientarea/vendor/whmcs/whmcs-foundation/lib/Module/Server.php(348): WHMCS\Module\AbstractModule->call('ConfigOptions', Array)
#17 /home/appli/public_html/clientarea/admin/configproducts.php(0): WHMCS\Module\Server->call('ConfigOptions', Array)
#18 {main}

**How to reproduce**  
Internally, calling autoload.php

**Possible Solution**  
N/A

**Additional context**  
I only execute composer 'require ovh/ovh' to install de SDK

**Comment by GrahamCampbell** [comment]
The bug is in the `ovh/ovh` package.
