### ISSUE TITLE
Make default http version publicly accessible

### ISSUE THREAD

**Issue by mkaisercross** [guzzle/guzzle#3125]
**Description**
Currently the default HTTP version used by Guzzle is hard coded in src/Client.php.

```
// src\Client.php::asyncRequest()
...
$version = $options['version'] ?? '1.1';
...
```

Right now to get the http version used by a request you would need to do something like this:

```
// bad
$requestVersion = array_key_exists($options, 'version') ? $options['version'] : '1.1';
```
... but this is bad because the app is hard coding 1.1 but that value could change in future version of guzzle and then app would be incorrect. It'd be better if the default value was somehow exposed either via getConfig() or alternatively via a constant value.

**Example**
```
$httpVersion = $client->getConfig()['version'];

// or 

$httpVersion = GuzzleDefaults::HTTP_VERSION;

```

**Comment by GrahamCampbell** [comment]
Can't you pass no value to request the default?

**Comment by mkaisercross** [comment]
The problem is not setting the http version it is reading it. I am trying to read what HTTP version is being used so it can be logged.

**Comment by mkaisercross** [comment]
I think I found a way access the version using Guzzle Handlers and Middleware. The Psr7 RequestInterface has a method getProtocolVersion().
