### ISSUE TITLE
The test-cookie `'fr=synced'` is missing a semi-colon after `Max-Age=604800`

### ISSUE THREAD

**Issue by Boegie** [guzzle/guzzle#3139]
**Guzzle version(s) affected**: 7.6.0
**PHP version**: (I think irrelevant to this bug)
```
PHP 8.1.12 (cli) (built: Oct 25 2022 18:16:21) (ZTS Visual C++ 2019 x64)
Copyright (c) The PHP Group
Zend Engine v4.1.12, Copyright (c) Zend Technologies
    with Xdebug v3.1.3, Copyright (c) 2002-2022, by Derick Rethans
```
**cURL version**: (I think irrelevant to this bug)
```
curl 7.88.1 (x86_64-w64-mingw32) libcurl/7.88.1 OpenSSL/1.1.1t (Schannel) zlib/1.2.13 brotli/1.0.9 zstd/1.5.4 libidn2/2.3.4 libpsl/0.21.2 (+libidn2/2.3.3) libssh2/1.10.0 nghttp2/1.52.0
Release-Date: 2023-02-20
Protocols: dict file ftp ftps gopher gophers http https imap imaps ldap ldaps mqtt pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: alt-svc AsynchDNS brotli HSTS HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz MultiSSL NTLM PSL SPNEGO SSL SSPI threadsafe TLS-SRP UnixSockets zstd
```

**Description**  
(Discovered whilst working on PR #3138)

The new test-cookie fr=synced'` in ``\GuzzleHttp\Tests\CookieJar\SetCookieTest::cookieParserDataProvider is missing a semi-colon after `Max-Age=604800`.

When this is added the validation on `expires` fails.

**How to reproduce**  
See PR #3140.

**Possible Solution**  

**Additional context**

**Comment by GrahamCampbell** [comment]
Yes, it is intentionally missing a semi-colon to prove that it doesn't crash with bad syntax.
