### ISSUE TITLE
Error since the support of guzzlehttp/promises v2

### ISSUE THREAD

**Issue by aless673** [guzzle/guzzle#3143]
**Guzzle version(s) affected**: 7.7.0
**PHP version**: 8.2.0
**cURL version**: 7.74.0

**Description**  
Error while using guzzle : `Attempted to call function "rejection_for" from namespace "GuzzleHttp\Promise".`

**How to reproduce**  
Use the request method of your Guzzle client

**Possible Solution**  
Instant solution : add local composer requirement `"guzzlehttp/promises": "^1.5"`

**Additional context**  
Error happens since this commit https://github.com/guzzle/guzzle/commit/7936fe9e180ce969680b21c40b221b3c2c661369
Package `guzzlehttp/promises` is now installed by default in version ^2 and not anymore ^1.5

**Comment by GrahamCampbell** [comment]
We don't have any code that calls that function, so this is likely an issue on your side. Can you search your codebase including the vendor directory for `rejection_for`?

**Comment by aless673** [comment]
> this is likely an issue on your side. Can you search your codebase including

you are right, this is called by this other package : https://github.com/8p/EightPointsGuzzleBundle/
