### ISSUE TITLE
BC break in version ^7

### ISSUE THREAD

**Issue by camohub** [guzzle/guzzle#3145]
**Guzzle version(s) affected**: 7.7
**PHP version**: 7.4

**Description**  
It seems you made a BC break in some of the latest 7.x versions. I have a Cloudinary library which uses Guzzle version ^7. 
This means any minor version of package under the major version 7. But minor versions should not include BC breaks. Can you fix it?

The error message says:
**Call to undefined function GuzzleHttp\Promise\promise_for()**

**Comment by GrahamCampbell** [comment]
Thanks for getting in touch, but this is not a BC break. This is a bug in the Cloudinary library because it is using the guzzlehttp/promises library without actually requiring it.

**Comment by GrahamCampbell** [comment]
https://github.com/cloudinary/cloudinary_php/pull/385 should fix your issue.

**Comment by GrahamCampbell** [comment]
You also already opened this issue already. I don't appreciate the double issue.

**Comment by camohub** [comment]
Cloudinry use promisses without actually requiring it? Dont understand. It called the method which did exists till now and now it is not. It seems like a BC break on your side.

**Comment by GrahamCampbell** [comment]
This is not a BC break. Had they correctly required the promises library v1, they would not have experienced this issue.
