### ISSUE TITLE
Dependency "deprecation-contracts" PHP version 8.1 and up

### ISSUE THREAD

**Issue by sitenzo** [guzzle/guzzle#3148]
**Guzzle version(s) affected**: 7.5 and up
**PHP version**: 8.0.9

**Description**  
[symfony/deprecation-contracts (v3.3.0)](https://packagist.org/packages/symfony/deprecation-contracts#v3.3.0) dependency is only php 8.1 and up. and not 8.*

**How to reproduce**  
Create following composer.json 

```
{
    "require": {
        "guzzlehttp/guzzle": "^7.7"
    },
    "platform": {
        "php": "8.0.9"
    }
}
```

**Additional context**

**Comment by GrahamCampbell** [comment]
We don't require v3.

**Comment by GrahamCampbell** [comment]
If you try the example, you will see v3.0.2 is installed, which works on 8.0.9.
