### ISSUE TITLE
GuzzleHttp\Exception\ConnectException: cURL error 35: error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://groundzerocustoms.myshopify.com/api/2022-10/graphql.json

### ISSUE THREAD

**Issue by 5priyanka** [guzzle/guzzle#3150]
**Guzzle version(s) affected**: x.y.z
**PHP version**: x.y.z (hint: `php --version`)
**cURL version**: x.y.z (hint: `php -i | grep cURL`)

**Description**  

**How to reproduce**  

**Possible Solution**  

**Additional context**  

GuzzleHttp\Exception\ConnectException cURL error 35: error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://inspiranzadesigns.myshopify.com/api/2022-10/graphql.json
(Most recent call first)

**Comment by GrahamCampbell** [comment]
This is almost certainly not a Guzzle issue, but an issue with out of date libraries (including system libraries). Make sure you are using the latest version of:

* Guzzle (currently 7.7.0)
* PHP (currently 8.0.29 or 8.1.20 or 8.2.7)
* libcurl (currently 8.1.2)
* openssl (currently 1.1.1u or 3.0.9)
