### ISSUE TITLE
Package php-http/message-factory is abandoned, you should avoid using it. Use psr/http-factory instead

### ISSUE THREAD

**Issue by vheins** [guzzle/guzzle#3153]
**Guzzle version(s) affected**: 7.7.0
**PHP version**: 8.1 (hint: `php --version`)

**Description**  
Package php-http/message-factory is abandoned, you should avoid using it. Use psr/http-factory instead

**How to reproduce**  
Composer Install

**Possible Solution**  
Use psr/http-factory

**Comment by GrahamCampbell** [comment]
This issue doesn't seem related to Guzzle. If you install only guzzle, you will not see this issue.
