### ISSUE TITLE
Abandoned php-http/message-factory package is used

### ISSUE THREAD

**Issue by mvczajkowski** [guzzle/guzzle#3154]
Guzzle version(s) affected: 7.7.0
PHP version: 8.2 (hint: php --version)

**Description**  
When using "composer install" a "Package php-http/message-factory is abandoned, you should avoid using it. Use psr/http-factory instead" warning appears. It seems that since 7.7.0 uses php-http/message-factory package which is abandoned.

**How to reproduce**  
Composer Install

**Possible Solution**  
Use psr/http-factory

**Additional context**  
Package was added in [Fixed tests](https://github.com/guzzle/guzzle/commit/aff112895ebd2c59585f5ba3adce0a51c105e164) commit and released in 7.7.0.

**Comment by GrahamCampbell** [comment]
This only in require-dev. When you use guzzle in your own code, this package is not pulled in.

**Comment by mvczajkowski** [comment]
This still isn't proper package and creates warnings. It shouldn't be used there.

**Comment by GrahamCampbell** [comment]
The warnings are totally fine, and don't affect you in any way.

**Comment by bastien-wink** [comment]
We should still plan to migrate to psr/http-factory at some point. It will otherwise show this warning in lots of projects.

**Comment by GrahamCampbell** [comment]
Can you show me where installing guzzle in your app or library shows the warning please?

**Comment by bastien-wink** [comment]
During a `composer install` (including require-dev)

The warning is 
`Package php-http/message-factory is abandoned, you should avoid using it. Use psr/http-factory instead.`

Tested with Composer 2.1.8

**Comment by GrahamCampbell** [comment]
That is not relevant for installing within this repo itself. If you don't see this warning when requiring guzzle as a dependency, then it doesn't matter.

**Comment by ghost** [comment]
My project does not require guzzle at all directly. It requires "league/oauth2-client", which requires guzzle and I sill get the warning.


```
composer install
Installing dependencies from lock file (including require-dev)
Verifying lock file contents can be installed on current platform.
Nothing to install, update or remove
Package php-http/message-factory is abandoned, you should avoid using it. Use psr/http-factory instead.
Generating optimized autoload files
64 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
```

**Comment by GrahamCampbell** [comment]
That's probably not from us. Can you run `composer why php-http/message-factory` please?

**Comment by ghost** [comment]
A thanks, you are right.
