### ISSUE TITLE
Maximum execution time of 30 seconds exceeded

### ISSUE THREAD

**Issue by tree1891** [guzzle/guzzle#3166]
**Guzzle version(s) affected**: 7.7
**PHP version**: 8.1.2
**cURL version**: 7.81.0

**Description**  
After call post in loop, get exception.
{
    "message": "Maximum execution time of 30 seconds exceeded",
    "exception": "Symfony\\Component\\ErrorHandler\\Error\\FatalError",
    "file": "/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php",
    "line": 595,
    "trace": []
}

**Comment by mfn** [comment]
See https://www.php.net/manual/en/info.configuration.php#ini.max-execution-time

**Comment by GrahamCampbell** [comment]
I'm not too sure what the goal of the issue report is. Possibly you need to set a connect timeout lower than your max execution time.
