### ISSUE TITLE
upgradin to PHP 8 and Guzzle 7. Breaks app

### ISSUE THREAD

**Issue by cubecleveland** [guzzle/guzzle#3172]
**Guzzle version(s) affected**: 7.4
**PHP version**: x.y.z (8.1)
**cURL version**: x.y.z (hint: `php -i | grep cURL`)

**Description**  
We had an app running Guzzle 6.5 with php 5.4 running. When converting the app to php 8.1 and Guzzle 7.4. (Debian machine)
We started experimenting Curl Error 6 ( getaadrinfo() can not resolve host...

The errors come sephordicaly and seems to not be connected to any speicfic end point. We are not suing and framework, but just raw PHP and all the guzzle simple request stayed intact and where not changed. Some requests are successful which make sit super hard to debug --> looking for any help as how to proceed looking at the issue.

**How to reproduce**  

**Possible Solution**  

**Additional context**

**Comment by GrahamCampbell** [comment]
Probably the best place to ask this question is some forums. There's not a lot we can do, with little information. Try upgrading to the very latest Debian, PHP and libcurl.
