### ISSUE TITLE
Remove content-type header when a redirect to GET: cURL does and Guzzle doesn't

### ISSUE THREAD

**Issue by nison-jp** [guzzle/guzzle#3173]
**Guzzle version(s) affected**: 7.7.0
**PHP version**: 8.2.8 (hint: `php --version`)
**cURL version**: 7.81.0 (hint: `php -i | grep cURL`)

**Description**  

* When we POST to some form, the server responds with the redirect: "302 Moved Permanently"
* Then the client should redirect to url shown in 'Location' header and create GET request to there
* GET request should NOT have any contents, so GET request should NOT have 'Content-Type' header, even if it's a redirect from POST
* Usually, browsers, cURL CLI commands, or other HTTP Client libraries (such as axios) behave like that
* However, when Guzzle client redirecting to GET, 'Content-Type' header is left
* **Some CDNs such as Akamai refuse GET requests with 'Content-Type' and does NOT RESPOND to them**, facing "time out" error finally.

Relevant issue found but closed: #2955

**Comment by GrahamCampbell** [comment]
This is a bug in Akamai. The HTTP spec does not say MUST NOT here. See https://github.com/guzzle/guzzle/issues/2955#issuecomment-979832664 for why we are not changing this. If you need a different behaviour, it's pretty easy to implement your own redirect middleware.

**Comment by GrahamCampbell** [comment]
The spec doesn't even say SHOULD NOT. It says that it is out of scope of the spec to assign a semantics to such requests.

**Comment by GrahamCampbell** [comment]
https://www.rfc-editor.org/rfc/rfc7231#section-4.3.1
