### ISSUE TITLE
Pool promise wait() breaks with guzzlehttp/promises v2

### ISSUE THREAD

**Issue by compwright** [guzzle/guzzle#3178]
**Guzzle version(s) affected**: 7.7+

**PHP version**: 7.4.33

**cURL version**: 8.0.1

**Description**  

Now encountering this error after the update:

```
GuzzleHttp\Promise\RejectionException: The promise was rejected with reason: Invoking the wait callback did not resolve the promise

vendor/guzzlehttp/promises/src/Create.php:59
vendor/guzzlehttp/promises/src/Promise.php:79
...
```

**How to reproduce**  

The error is triggered in this block of code:

```php
class HydrateJobs
{
    public function __invoke(array $jobs, int $concurrency = 10): array
    {
        $pool = new Pool(
            $this->apiClient->getHttpClient(), // Returns an instance of GuzzleHttp\Client
            $this->loadDatasets($jobs), // Generator that yields callables that each return a GuzzleHttp\Promise\PromiseInterface
            compact('concurrency')
        );
        $pool->promise()->wait(); // This triggers the error
        return $jobs;
    }
}
```

**Additional context**  

Changing $concurrency = 1 had no effect.

**Comment by GrahamCampbell** [comment]
Can you pin point the exact package versions that changed. Did the version of our promises library change when you upgraded, too?

**Comment by compwright** [comment]
Yes, and yes - see https://github.com/guzzle/guzzle/blob/7.8/CHANGELOG.md#770---2023-05-21

**Comment by GrahamCampbell** [comment]
I'm not asking about the change log, I'm asking about the actual versions installed for you before and after.

**Comment by compwright** [comment]
I thought I answered that already, but I'll spell it out:

7.6.1 works (uses guzzle/promises 1.5.3)

7.7.0 doesn't work (uses guzzle/promises 2.0.0). Ditto for 7.7.1 and 7.8.0, and guzzle/promises 2.0.1.

**Comment by compwright** [comment]
@GrahamCampbell thanks for looking into this!

**Comment by GrahamCampbell** [comment]
Does downgrading to promises 1.5.3 with 7.7.0 work?

**Comment by compwright** [comment]
@GrahamCampbell yes, 7.7.0 and 7.8.0 work as expected with guzzle/promises 1.5.3.

**Comment by GrahamCampbell** [comment]
Hmm, pretty odd, given we basically didn't change anything: https://github.com/guzzle/promises/compare/1.5.3...2.0.1. Can you spot the issue in here? I'm not sure there's much else I can do to help, otherwise.

**Comment by compwright** [comment]
By way of update, this happens when the callbacks the iterable returns return a promise. It seems that the pool does not automatically resolve each promise; the callback needs to handle that itself.
