### ISSUE TITLE
[DOCS] In online documentation, the request option connect_timeout still says that the default value of 0 waits indefinitely, which was never true

### ISSUE THREAD

**Issue by georaldc** [guzzle/guzzle#3183]
https://docs.guzzlephp.org/en/stable/request-options.html#connect-timeout

This actually threw me off initially because I always thought that the default was exactly that: to wait indefinitely. I didn't know that the actual default was 150 seconds previously, which got changed to 300 seconds recently to match curl.

Speaking of connection timeouts, I ran into a rather strange issue where previously with an older Guzzle 6.3.3, I had no issues making calls to a 3rd party storage service (Google Cloud Storage). Immediately after upgrading to 7.8.0, I started seeing intermittent "cURL error 35: TCP connection reset by peer" errors. This is when I found the connect_timeout difference between the 2 versions as I was investigating, so I forced my guzzle code to include a "connect_timeout: 150" seconds config just to mimic previous behavior and the ConnectException errors stopped. This is outside of the scope of this issue report, but I just found it odd since I would think decreasing the connection timeout should actually lead to more ConnectExceptions (if it was a connection issue) instead of eliminating it altogether.

**Comment by GrahamCampbell** [comment]
I believe we can consolidate this in Guzzle 8.

**Comment by GrahamCampbell** [comment]
Actually, I believe the docs are out of date. The docs in the repo are right, but the website build seems old... which is something I need to look into.

**Comment by GrahamCampbell** [comment]
See https://github.com/guzzle/guzzle/blob/7.8/docs/request-options.rst#connect_timeout.
