### ISSUE TITLE
Organization Information

### ISSUE THREAD

**Issue by mashiox** [guzzle/guzzle#3187]
**Description**  

I have been obligated by a government entity to list all open source products used by the proposed software system we are trying to sell to them.

I am including organization names in this list, intended to de-risk this class of software.

For instance, when I tell include Debian on this list, I describe Debian as:

- The Debian Project, Debian/GNU Linux

I want to include guzzlehttp in this list because OpenTHC uses the Guzzle HTTP library extensively in our projects. 

However, I have not been able to find organizational information that would cover the individuals named in places like `composer.json`

What would proper org name like "The Debian Project" label for guzzlehttp?

Is there some org or foundation information anyone can point out to me?

**Additional context**  

I attempted to ask this question in Slack per the [Support](https://github.com/guzzle/.github/blob/master/.github/SUPPORT.md) section of the FAQ. Slack is not admitting users with outside of the `php-http.org`, or httplug.io` domains.

**Comment by GrahamCampbell** [comment]
There is no formal organization.
