### ISSUE TITLE
Security vulnerabilities in guzzlehttp/psr7 dependency in v6.x

### ISSUE THREAD

**Issue by gravelld** [guzzle/guzzle#3197]
Thanks for your work on this library.

**Guzzle version(s) affected**: 6.5.8
**PHP version**: 7.4
**cURL version**: Not relevant

**Description**  
Due to GHSA-wxmh-65f7-jcvw the minimum version for the 1.x version of guzzlehttp/psr7 should be 1.9.1. This means the entry in composer.json should be:

    "guzzlehttp/psr7": "^1.9.1"

Is this something you are likely to change and issue a release for?

**Comment by GrahamCampbell** [comment]
No, it is not necessary for us to change this. One could just install an old version of guzzle to get the vulnerability, in the same way one could install an old psr7 package.

**Comment by gravelld** [comment]
Context: this is a security audit. `composer.json`s are scanned to look for dependencies on vulnerable software.

If the `composer.json`s are declared such that it can be proved that there are no dependencies on vulnerable software, the audit is passed. Otherwise, it is failed.

In that context, you cannot "just install an old version of guzzle" because it would be vulnerable.

I guess I'm missing something?

**Comment by GrahamCampbell** [comment]
Yes, but in any case, Guzzle 6 is EOL and doesn't support even a version of PHP that is still getting security fixes. Guzzle 7 is the only release of Guzzle that should be used, today.
