### ISSUE TITLE
Link header parsing for responses

### ISSUE THREAD

**Issue by mtdowling** [guzzle/guzzle#320]
Implement a helper on a Response object to make working with Link headers easier.

Something similar to Requests: http://docs.python-requests.org/en/latest/user/advanced/?highlight=link#link-headers

**Comment by davidbarratt** [comment]
@mtdowling,

It looks like the `getLinks()` method no longer exists?

**Comment by paulocoliver** [comment]
See: https://github.com/guzzle/guzzle/blob/master/docs/psr7.rst#complex-headers
