### ISSUE TITLE
Supports json to array conversion

### ISSUE THREAD

**Issue by xfstu** [guzzle/guzzle#3200]
**Description**

We want to support json to array conversion without the developer having to write the array conversion method twice

**Example**

example：
```php
$client = new Client(['base_uri' => 'http://foo.com/api/']);
$response = $client->get('data');
$body = $response->getBody()->getContents()->toArray();
```

**Additional context**

**Comment by GrahamCampbell** [comment]
Thanks but this is not part of the PSR7 interface, so will never be possible.
