### ISSUE TITLE
400 Bad Value Push

### ISSUE THREAD

**Issue by AzharAbbas10** [guzzle/guzzle#3221]
**Guzzle version(s) affected**: 7.8.1
**PHP version**: 8.1
**cURL version**: Sorry Don't Know

**Description**  
Following is my code but it give me error bad request push
`public function createKlarnaOrder(Request $request)
    {

        $orderId = $request->input('order_id');
        $amount = $request->input('amount');
        $order = Order::find($orderId);

        if (!$order) {
            return response()->json(['error' => 'Order not found.'], 404);
        }

        $client = new Client();

        try {
            $response = $client->post("{$this->klarnaBaseUrl}/checkout/v3/orders", [
                'auth' => $this->klarnaAuth,
                'json' => [
                    "purchase_country" => "GB",
                    "purchase_currency" => "GBP",
                    "locale" => "en-GB",
                    "order_amount" => $amount * 100, 
                    "order_tax_amount" => 0,
                    "order_lines" => [
                        [
                            "type" => "physical",
                            "reference" => $order->id,
                            "name" => "Repair Service",
                            "quantity" => 1,
                            "quantity_unit" => "pcs",
                            "unit_price" => $amount * 100,
                            "tax_rate" => 0,
                            "total_amount" => $amount * 100,
                            "total_discount_amount" => 0,
                            "total_tax_amount" => 0
                        ]
                    ],
                    "merchant_urls" => [
                        "terms" => "https://www.example.com/terms.html",
                        "checkout" => "https://www.example.com/checkout.html",
                        "confirmation" => "https://www.example.com/confirmation",
                        "push" => route('klarnaPush', ['orderId' => $orderId])
                    ]
                ]
            ]);

            $responseBody = json_decode($response->getBody()->getContents(), true);
            \Log::info('Klarna response', ['response' => $responseBody]);

            if (isset($responseBody['html_snippet'])) {
                return response()->json(['htmlSnippet' => $responseBody['html_snippet']]);
            } else {
                return response()->json(['error' => 'HTML snippet not found in Klarna response'], 400);
            }
        } catch (\GuzzleHttp\Exception\ClientException $e) {
            \Log::error('Klarna ClientException', ['error' => $e->getMessage()]);
            return response()->json(['error' => $e->getMessage()], 400);
        } catch (\Exception $e) {
            \Log::error('Klarna Exception', ['error' => $e->getMessage()]);
            return response()->json(['error' => $e->getMessage()], 500);
        }
    }`

I have Route for this and also fuction
`Route::post('/klarna-push/{orderId}', [PaymentController::class, 'klarnaPush'])->name('klarnaPush');
`
`public function klarnaPush(Request $request, $orderId)
    {

        $order = Order::find($orderId);

        if (!$order) {
            return response()->json(['error' => 'Order not found.'], 404);
        }

        // $klarnaOrderId = $request->input('klarna_order_id');

        $order->advance_payment_recevied = "Payment Recived";
        $order->payment_method = "Stripe";
        $order->save();

        return response()->json(['status' => 'ok'], 200);
    }`

**Comment by GrahamCampbell** [comment]
This doesn't appear to be a bug report with Guzzle, more a support request. I'd recommend asking elsewhere such as stack-overflow.
