### ISSUE TITLE
Tag a PHP 8.4 compat release

### ISSUE THREAD

**Issue by lolli42** [guzzle/guzzle#3230]
**Guzzle version(s) affected**: 7.8.1
**PHP version**: 8.4.0alpha1 (hint: `php --version`)

**Description**  
With 8.4.0alpha1 being there, we're starting to look at PHP 8.4 compat issues.
It seems guzzle main and sub repos got a couple of 8.4 fixes already.

I hope it's to ask for a tag/release soon :)

**Comment by GrahamCampbell** [comment]
I'd recommend using dev stability for now. We're in no rush to tag fixes for non-stable versions of PHP. If people want to test bleeding edge, it's not unreasonable for them to also use bleeding edge Guzzle. ;)

**Comment by lolli42** [comment]
Ack. Thx.

**Comment by lolli42** [comment]
I understand there is no pressure from your side to get this tagged, but I don't really like it:
guzzle is an important library for many and currently emits E_DEPRECATED with PHP 8.4, which is fixed codewise already, just not tagged.

With 8.4 alpha1 being released, frameworks start adding PHP 8.4 support and depend on libraries being ready, to be ready when 8.4.0 is released. For projects adding PHP 8.4 to their supported stable branches, switching to dev stability of libraries is not a great option, though. There are always solutions and all that, they are simply not great options ;)

I thus simply hope guzzle still sees tags including the patches relatively soon.

**Comment by GrahamCampbell** [comment]
Yep, and you can use `dev` stability in the interim.

**Comment by GrahamCampbell** [comment]
I've gone ahead and made PHP 8.4 compatible releases of our psr7 and promises packages, and now in turn this package.
