### ISSUE TITLE
Guzzle selects StreamHandler on php 7.4.33 and connections fail to establish

### ISSUE THREAD

**Issue by rgagnon24** [guzzle/guzzle#3240]
**Guzzle version(s) affected**: 7.9.1
**PHP version**: 7.4.33
**cURL version**: 7.29.0

**Description**  
Code that used to work started failing after composer update brought in v7.9.1 of Guzzle.  Traced it to a change in the chooseHandler() method of Utils:
https://github.com/guzzle/guzzle/commit/9678673d2164429e03d755522dc4558862f2c429

**How to reproduce**  
`

		$http_client = new \GuzzleHttp\Client([
			'debug' => $file_handle,
			'base_uri' => 'https://some.server.com/rest',
			'headers' => $request_headers,
			'http_errors' => false,
			'verify' => false,
			'connect_timeout' => self::HTTP_CONNECT_SECONDS,
			'timeout' => self::HTTP_TIMEOUT_SECONDS,
			]);
`

**Possible Solution**  
Remove or change the check for PHP version from line 90 of src/Utils.php.  On the server I was using, all the other checks of the if-statement passed and would allow the CurlHandler to be selected as before.

**Additional context**  
The workaround I came up with that forces use of the CurlHandler is:
`

		$handler = new \GuzzleHttp\Handler\CurlHandler();
		$stack = \GuzzleHttp\HandlerStack::create($handler);

		$http_client = new \GuzzleHttp\Client([
			'debug' => $file_handle,
			'base_uri' => 'https://some.server.com/rest',
			'headers' => $request_headers,
			'http_errors' => false,
			'verify' => false,
			'connect_timeout' => self::HTTP_CONNECT_SECONDS,
			'timeout' => self::HTTP_TIMEOUT_SECONDS,
			'handler' => $stack
			]);
`

**Comment by rgagnon24** [comment]
I see the code in issue 3220 trying to resolve issue 3219 that was changed was attempting to fix a supposed missing constant CURL_SSLVERSION_TLSv1_2, but on our server:

```
# php -a
Interactive shell

php > print CURL_SSLVERSION_TLSv1_2;
6
php >

```

**Comment by GrahamCampbell** [comment]
The reason is that the version of libcurl you have is too old. You need at least 7.34.0 or higher for Guzzle to select the curl handler by default. You can manually choose it, at your own risk, if you want, but there are known issues.

**Comment by rgagnon24** [comment]
Here's the problem.  The change creates a compatibility-breaking change.  By just performing a composer update, existing code that's been working for years just starts to fail.

What risk?

**Comment by rgagnon24** [comment]
The constant CURL_SSLVERSION_TLSv1_2 mentioned as not existing in the comments of issue 3219/3220 actually DOES exist in PHP 7.4.33

```
# php -v
PHP 7.4.33 (cli) (built: Jun  5 2024 05:05:14) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.33, Copyright (c), by Zend Technologies

# php -i|grep cURL
cURL support => enabled
cURL Information => 7.29.0

# cat /etc/redhat-release
CentOS Linux release 7.9.2009 (Core)

```

Also, without selecting the CurlHandler by default, the StreamHandler gets selected and that thing doesn't even establish a connection to the remote server properly.

**Comment by rgagnon24** [comment]
Maybe the if-statement should be checking curl_version instead of php_version?

```
 var_export(curl_version());
array (
  'version_number' => 466176,
  'age' => 3,
  'features' => 558781,
  'ssl_version_number' => 0,
  'version' => '7.29.0',
  'host' => 'x86_64-redhat-linux-gnu',
  'ssl_version' => 'NSS/3.90',
  'libz_version' => '1.2.7',
  'protocols' =>
  array (
    0 => 'dict',
    1 => 'file',
    2 => 'ftp',
    3 => 'ftps',
    4 => 'gopher',
    5 => 'http',
    6 => 'https',
    7 => 'imap',
    8 => 'imaps',
    9 => 'ldap',
    10 => 'ldaps',
    11 => 'pop3',
    12 => 'pop3s',
    13 => 'rtsp',
    14 => 'scp',
    15 => 'sftp',
    16 => 'smtp',
    17 => 'smtps',
    18 => 'telnet',
    19 => 'tftp',
  ),
  'ares' => '',
  'ares_num' => 0,
  'libidn' => '1.28',
  'iconv_ver_num' => 0,
  'libssh_version' => 'libssh2/1.8.0',
)
```

**Comment by GrahamCampbell** [comment]
Why does the connection fail to establish. A change to how we select what handler to use is not breaking, but if the stream handler is not working, that is potentially an issue, if it's something that is Guzzle's fault. What error are you seeing?

**Comment by GrahamCampbell** [comment]
> Maybe the if-statement should be checking curl_version instead of php_version?

We are looking at the curl version. In your case you have a very out of date version of curl, likely with many security issues.

**Comment by GrahamCampbell** [comment]
The constant existing in the PHP version is not enough for it to actually function correctly with the linked curl version.

**Comment by rgagnon24** [comment]
> > Maybe the if-statement should be checking curl_version instead of php_version?
> 
> We are looking at the curl version. In your case you have a very out of date version of curl, likely with many security issues.

On this... my bad... I was going from quick look and the mention in a commit comment of looking for version 7.34 or better, mixing that up with PHP version 7.4.33 that we're running which has Curl 7.29.0

**Comment by rgagnon24** [comment]
> Why does the connection fail to establish. A change to how we select what handler to use is not breaking, but if the stream handler is not working, that is potentially an issue, if it's something that is Guzzle's fault. What error are you seeing?

Without the workaround this is what shows up in the debug file under the StreamHandler being selected... with some information redacted of course:
```
<POST https://redactedserver.name/rest/Session/login> [CONNECT]
<POST https://redactedserver.name/rest/Session/login> [FAILURE] severity: "2" message: "HTTP/1.1 500 Internal Server Error
" message_code: "500"
<POST https://redactedserver.name/rest/Session/login> [MIME_TYPE_IS] message: "application/json; charset=UTF-8"
<POST https://redactedserver.name/rest/Session/login> [PROGRESS]
<POST https://redactedserver.name/rest/Session/login> [PROGRESS] bytes_transferred: "111"
<POST https://redactedserver.name/rest/Session/login> [PROGRESS] bytes_transferred: "116"
```

Comparison to what happens by just forcing the CurlHandler:
```
* About to connect() to [[REDACTED]] port 443 (#0)
*   Trying [[REDACTED_IP_ADDRESS]]...
* Connected to [[REDACTED]] ([[REDACTED_IP_ADDRESS]]) port 443 (#0)
* Initializing NSS with certpath: sql:/etc/pki/nssdb
* skipping SSL peer certificate verification
* SSL connection using TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA
* Server certificate:
*  subject: CN=[[REDACTED]],O="[[REDACTED]]",ST=[[REDACTED]],C=[[REDACTED]]
*  start date: Jun 11 00:00:00 2024 GMT
*  expire date: Jul 11 23:59:59 2025 GMT
*  common name: [[REDACTED]]
*  issuer: CN=Sectigo RSA Organization Validation Secure Server CA,O=Sectigo Limited,L=Salford,ST=Greater Manchester,C=GB
> POST /rest/Session/login HTTP/1.1
User-Agent: [[REDACTED]]/1.0
Host: [[REDACTED]]
Content-Length: 99

* upload completely sent off: 99 out of 99 bytes
< HTTP/1.1 200 OK
< Date: Mon, 22 Jul 2024 14:24:44 GMT
< Server: Apache
< X-Frame-Options: SAMEORIGIN
< Strict-Transport-Security: max-age=31536000; includeSubdomains
< Set-Cookie: SID=[[REDACTED]]; path=/; expires=Wed, 24-Jul-2024 14:24:45 GMT; max-age=172800; secure; HttpOnly; SameSite=None
< Set-Cookie: Admin_Access_Token=[[REDACTED]]; path=/; expires=Wed, 24-Jul-2024 14:24:45 GMT; max-age=172800; secure; HttpOnly; SameSite=None
< Set-Cookie: Admin_Refresh_Token=[[REDACTED]]; path=/; expires=Wed, 24-Jul-2024 14:24:45 GMT; max-age=172800; secure; HttpOnly; SameSite=None
< Vary: Origin,Accept-Encoding
< Transfer-Encoding: chunked
< Content-Type: application/json; charset=UTF-8
< 
* Connection #0 to host [[REDACTED]] left intact
```

Although looking at this might not actually show a connection problem, it seems that the data that should be posted in the body is not being sent because the remote side is suddenly replying by telling us information is missing from the POST body JSON---which does not happen when the CurlHandler is used.

**Comment by rgagnon24** [comment]
Something odd as well... On this CentOS server, it actually gets v7.9.1 of the Utils.php file that contains the longer if-statement on line 90, but on my Windows machine if I do a composer update, it SAYS I have version 7.9.1 in the CHANGELOG.md file, but the content of Utils.php is not the same (even if I delete the entire vendor folder, and the composer.lock file)

**Comment by Housik** [comment]
I am having similar issue, after upgrading to 7.9.1 I am unable to connect. Nothing has changes except guzzle client library version. Server OS is Redhat 7, PHP version is 8.3.9.

In config I am using:

- `verify` set to certificate (string)
- `cert` set to certificate (string)
- `ssl_key` set to certificate (string)

`/vendor/guzzlehttp/guzzle/src/Handler/StreamHandler.php:78)\n[previous exception] [object] (GuzzleHttp\\Exception\\ConnectException(code: 0): Connection refused for URI https://example.com/`

After reverting back to 7.8.2 everything is working as expected.

**Comment by GrahamCampbell** [comment]
Ah, this is happening because the stream handler does not support custom certificates. Are you able to upgrade to a newer, secure version of curl?

**Comment by GrahamCampbell** [comment]
The reason we made this change was to fix https://github.com/guzzle/guzzle/issues/3219, FYI.

**Comment by GrahamCampbell** [comment]
It is possible to force Guzzle 7.9.x to use the curl handler still, even if it's "not supported":

```php
use GuzzleHttp\Client\CurlHandler;
use GuzzleHttp\HandlerStack;
use GuzzleHttp\Handler\CurlHandler;
use GuzzleHttp\Handler\CurlMultiHandler;
use GuzzleHttp\Handler\Proxy;

$client = new Client([
    'handler' => new HandlerStack(
        Proxy::wrapSync(new CurlMultiHandler(), new CurlHandler())
    ),
]);
```

**Comment by GrahamCampbell** [comment]
At this point, it's still unclear if it would be better to revert the min version change. It may be that more people are affected by this issue than the other one. However, on the flip side, it may be useful to let those people know they have a super old version of curl that should be upgraded.

**Comment by Housik** [comment]
@GrahamCampbell Graham, can you be more specific please - which version of curl is required/supported? Versions >7.33 are OK? Btw, it looks like the update betwen 7.8.2 and 7.9.1 introduced a breaking change. Did you consider new major version, or I am wrong?

**Comment by GrahamCampbell** [comment]
The change is just to the default handler selection algorithm. We no longer choose the curl handler if the curl version is less than 7.34.0 due to serious bugs, security issues and missing features that we need. It's still possible to force Guzzle to use the curl handler, if you really need. It's hard to say if this is a breaking change or even a security fix - it's common to considered bug fixes as both of those, one of those, or neither.

**Comment by GrahamCampbell** [comment]
I am considering reverting this change, delaying it to Guzzle 8. I did not not anticipate people still using ancient curl versions, older than PHP 7.2.5 itself. cURL 8.34.0 was released on Dec 17 2013.

**Comment by GrahamCampbell** [comment]
I believe https://github.com/guzzle/guzzle/pull/3241 may fix the issue for everyone that commented here, without them needing to make code changes. The trade-off is it breaks things for the reporter of the earlier issue, but I am leaning towards this issue being worse than the other one.

**Comment by Housik** [comment]
Thanks Graham for quick response. You are right - it is a good reminder to update CURL library or even better whole OS, as for example Redhat 7 (and its siblings) may contains this old curl 7.29 version in many many cases.

**Comment by GrahamCampbell** [comment]
Guzzle 7.9.2 has now been released, which should fix the issues that everyone has reported in this thread.
