### ISSUE TITLE
Thumbor crashing after guzzle upgrade to 7.9.2

### ISSUE THREAD

**Issue by nimafallahian** [guzzle/guzzle#3243]
**Guzzle version(s) affected**: 7.9.2
**PHP version**: 8.3.9
**cURL version**: 7.88.1

**Description**  
After the batch upgrade of guzzle from 7.9.1 to 7.9.2, [thumbor:6.7.5](https://hub.docker.com/r/minimalcompact/thumbor) keeps crashing. My logs are insufficient to tell the cause of the issue, although memory usage of thumbor peaks quite often, and the pod running it restarts. After reverting to 7.9.1 I see no more fails.

**How to reproduce**  

1. Deploy a setup with two pods: one for your application and one for thumbor.
2. Use Guzzle 7.9.1 in your application.
3. Upgrade Guzzle to 7.9.2.
4. Observe the memory usage of thumbor.
5. Notice that the thumbor pod crashes and restarts frequently.

**Comment by GrahamCampbell** [comment]
Not sure why. Both versions are almost identical. Did the 7.8.x series also not work?

---

https://github.com/guzzle/guzzle/compare/7.9.1...7.9.2

**Comment by GrahamCampbell** [comment]
The reproduction steps here, candidly, do not make any sense, and there's nothing actionable here.
