### ISSUE TITLE
Parsing "Content-Security-Policy"

### ISSUE THREAD

**Issue by guram-vashakidze** [guzzle/guzzle#3246]
**Description**
Some API started adding "Content-Security-Policy" header to response. And sometimes this header value is split by `\r\n`  . As result you could receive "InvalidHeader" exception.

**Example**
```bash
Content-Security-Policy: \r\n
              default-src 'self'; \r\n
              script-src 'self' 'unsafe-eval' data: 'unsafe-inline' https://foo.com http://bar.com \r\n
```
**Additional context**
There is adding closure on `CURLOPT_HEADERFUNCTION`  in `\GuzzleHttp\Handler\CurlFactory` . This closure is taking headers by lines. 

**Solution**
In my app I recall CurlHandler with another factory, where I re-implement closure for `CURLOPT_HEADERFUNCTION` . I'm checking if line started from CSP directive then I'm adding this line to previous headers item.

**Comment by GrahamCampbell** [comment]
This is an invalid response header, according to the HTTP spec, and supporting them opens up security vulnerabilities: https://github.com/guzzle/psr7/security/advisories. Please inform the API vendor that this response is invalid, so they can correct this.

**Comment by jonjieviduya** [comment]
@GrahamCampbell what should be the fix for this? I am currently using laravel9
