### ISSUE TITLE
PHP 8.4 issue with guzzlehttp/promises dependency

### ISSUE THREAD

**Issue by alecpl** [guzzle/guzzle#3248]
**Guzzle version(s) affected**: 7.9.2
**PHP version**: 8.4.0

**Description**  
When using composer with `--prefer-lowest` option. On PHP 8.4 it will choose to install guzzlehttp/promises 1.5.3 which is not compatible with PHP 8.4.

Context, in my project we build a package with platform set to lower than 8.4 and expect these packages to work on PHP 8.4.

**How to reproduce**  
Have a composer dependency `"guzzlehttp/guzzle": "^7.9.2"` and run `composer --prefer-lowest` with platform set to "8.1".

**Possible Solution**  
Drop support for guzzlehttp/promises 1.5.3, and release a new version. I don't see a reason to not do this, but maybe I'm missing something.

**Comment by GrahamCampbell** [comment]
Thanks for getting in touch. We cannot drop support for promises v1, because it is still widely used, and would create real problems for people, instead of theoretical problems with prefer lowest. I'd recommend you directly depend on promises v2 if you want to use prefer lowest.
