### ISSUE TITLE
fatal error

### ISSUE THREAD

**Issue by KrayolaDavid** [guzzle/guzzle#3258]
Response from server: <br />
<b>Fatal error</b>:  Uncaught Error: Class &quot;guzzlehttp\Client&quot; not found in /home/vol4_2/infinityfree.com/if0_37410392/htdocs/generate-paymongo-link.php:73
Stack trace:
#0 {main}
  thrown in <b>/home/vol4_2/infinityf
  
  i have complete files for guzzle on my website

**Comment by GrahamCampbell** [comment]
This is likely happening because your filesystem is case sensitive. It's necessary to use the correct casing for the namespace, in order to autoload the file.

**Comment by GrahamCampbell** [comment]
GuzzleHttp\Client != guzzlehttp\Client
