### ISSUE TITLE
Not possible to have different URL host from Host header.

### ISSUE THREAD

**Issue by bendavies** [guzzle/guzzle#362]
I found this previously discussed on twitter:
https://twitter.com/mtougeron/status/322882012878876672

It is currently not possible to send a different Host header to that or the requested URL.
I want to send a request like this:

```
curl -XPURGE http://some-hostname/en/ -H "Host: some-other-hostname"
```

but guzzle always keeps the URL host and the Host header in sync, so the request always looks like this:

```
curl -XPURGE http://some-other-hostname/en/ -H "Host: some-other-hostname"
```

At the moment I am working around this with reflection:

``` php
$request = $client->createRequest('PURGE', $server . $path);

$headers = $request->getHeaders();
$header = $headers->get('Host');

$refl = new \ReflectionObject($header);
$prop = $refl->getProperty('values');
$prop->setAccessible(true);
$prop->setValue($header, array($host));
```

but this is far from convenient.

Thoughts?
Cheers.

**Comment by thinkjson** [comment]
In case you end up here like I did, as of April 2015 the only way to do this is:

    $request = $client->createRequest( ...
    $request->setHeader('Host', ' ...
    $response = $client->send($request);

**Comment by matrey** [comment]
Another workaround is to use CURLOPT_RESOLVE (but this will only work if Guzzle uses cURL), e.g.

```php
$client = new GuzzleHttp\Client(array(
    'curl' => array(CURLOPT_RESOLVE => array('fakedomain.dev:80:127.0.0.1')),
));
```

(source: https://laracasts.com/discuss/channels/tips/need-guzzlehttpguzzle-tips-with-apache-vhost)
