### ISSUE TITLE
Guzzle is super slow comparing to file_get_content

### ISSUE THREAD

**Issue by scottzhang** [guzzle/guzzle#395]
I get to know guzzle when I integrate an oauthclient which use guzzle by default. 
So when I don't use oauthclient, I still keep guzzle for http request from php.

We are using GuzzleClient to request our oauth protected api. Usually when we visit our api url directly from browser, the response/full load time is about 40ms, we measured this by firebug.

But when we get same url from guzzleClient using GET, it always take ~100-120ms. It is really unacceptable. We try to use file_get_content, it needs ~40-50ms.   

So we follow the code into GuzzleClient, before jump into its 'group->send' call, I use php microtime() to track, it already consumed ~10-20ms for all these addon wrapper code, and its "$group->send()" take about ~90ms. Still slow. 

I know guzzle added many code for some advanced features before a real send but its speed is really slow.  

I am trying to test phpcurl or Http_Request2 which only provide a pure send interface to overcome the performance issue.

**Comment by nczepa** [comment]
slow guzzle depends, but keep attention to your environment! we had the same issue with a slow guzzle/6.2.1 and the problem was an special curl/7.29 version which caused the super slow performance

**Comment by GreenLeewayDesignCastle** [comment]
@nczepa I think I might be having the same problem. To which curl version did you update it to ? Is there a list of specific curl versions that are not recommended to use with specific guzzle versions I can look at somewhere ?
