### ISSUE TITLE
Guzzle not following Reload header style redirects

### ISSUE THREAD

**Issue by captbaritone** [guzzle/guzzle#444]
Please excuse my ignorance, as I don't know much about these issues.

I have a script like located at `http://classicalcode.com/reload_to_google/` that reads like so:

```
<?php header("Refresh:0;url=https://google.com");
```

If I visit that link in my browser (Chrome, Firefox or Safari), I am redirected to google.com. If I load that same url via Guzzle I get an empty page.

```
<?php
require 'vendor/autoload.php';

use Guzzle\Http\Client;

$client = new Client('http://classicalcode.com');

$request = $client->get('/reload_to_google/');
$response = $request->send();
if($response->getHeader('Content-Length') == '0')
{
    echo "Empty page";
}
```

I understand that this may be an intentionally omitted feature since I believe this sort of header is not technically in spec, but since most browsers support it, I wanted to check.
## Why I care

Just so you understand why I'm reporting this issue, I am trying to use [Codeception](http://codeception.com/) to test an existing [CodeIgniter](http://ellislab.com/codeigniter) application which uses [Ion Auth](http://benedmunds.com/ion_auth/) as the authentication library. Ion Auth uses this sort of redirect throughout.

**Comment by younes0** [comment]
@captbaritone did you figure it out?
