### ISSUE TITLE
Failed to pass SSL auth while curl.CURLOPT_CERTINFO is set

### ISSUE THREAD

**Issue by dev2geek** [guzzle/guzzle#478]
``` bash
> php -v
PHP 5.4.17 (cli) (built: Aug 25 2013 02:03:38)
> curl -V
curl 7.30.0 (x86_64-apple-darwin13.0) libcurl/7.30.0 SecureTransport zlib/1.2.5
```

No matter CURLOPT_CERTINFO set to true or false, following request can't pass the SSL authentication.

``` php
<?php
require_once 'vendor/autoload.php';

use Guzzle\Http\Client;


$client = new Client('http://ata.***.com', array(

   'curl.options' => array(
       CURLOPT_CERTINFO => false[or true],
       CURLOPT_SSL_VERIFYPEER => false,
       CURLOPT_COOKIEFILE => './g.cookie',
       CURLOPT_COOKIEJAR => './g.cookie'
   )
));
$request = $client->get('/');
$response = $request->send();
echo $response->getBody();
```

But if remove CURLOPT_CERTINFO like below, it works

``` php
<?php
require_once 'vendor/autoload.php';

use Guzzle\Http\Client;


$client = new Client('http://ata.***.com', array(

   'curl.options' => array(
       CURLOPT_SSL_VERIFYPEER => false,
       CURLOPT_COOKIEFILE => './g.cookie',
       CURLOPT_COOKIEJAR => './g.cookie'
   )
));
$request = $client->get('/');
$response = $request->send();
echo $response->getBody();
```

Since `PhpBrowser` in `codeception` has a default config of 

``` php
protected $curl_defaults = array(
    CURLOPT_SSL_VERIFYPEER => false,
    CURLOPT_CERTINFO => false,
);
```

We can't just remove that configuration

**Comment by augustohp** [comment]
Just as a follow up to this problem:

On OSX 10.9 (Mavericks) [Apple abandoned OpenSSL][1] affecting cURL behavior with self-signed certs. You have some options cleverly pointed out in the link given.

PS: OSX 10.10 is also affected.

[1]: http://curl.haxx.se/mail/archive-2013-10/0036.html

**Comment by denishowe** [comment]
PHP curl_setopt and curl_setopt_array always return false when trying to set CURLOPT_CERTINFO.  This will cause curl_setopt_array to ignore any later parameters.
PHP 5.4.16, curl 7.29.0.
