### ISSUE TITLE
Warning: preg_match(): Unknown modifier '/' in Cookie.php on line 440

### ISSUE THREAD

**Issue by Thinkscape** [guzzle/guzzle#526]
Getting those recently:

```
Warning: preg_match(): Unknown modifier '/' in /app/guzzle/src/Guzzle/Plugin/Cookie/Cookie.php on line 440
```

Probably because the remote server is sending something stupid as the cookie domain. There is some normalization going on in the plugin, though the error means that something is getting through regardless. We might `filter_var()` the `$cookieDomain` against domain name, or something like that...

**Comment by curtisdf** [comment]
I know it's been 4+ years, but this bug has reappeared.  I just submitted a pull request which reapplies the same fix as referenced above. See https://github.com/guzzle/guzzle/pull/1999.
