### ISSUE TITLE
HHVM support

### ISSUE THREAD

**Issue by artursmolarek** [guzzle/guzzle#538]
I would like to ask if you plan support for HHVM (hhvm.com)?
A basic features of Guzzle work, but there are problems with body content for a POST requests.

We are using Laravel + Guzzle. Laravel is fully supported by HHVM, but Guzzle as I wrote is not.

Other people also asked about running your lib under HHVM: http://www.hhvm.com/blog/875/wow-hhvm-is-fast-too-bad-it-doesnt-run-my-code

In case of any question feel free to ask me.

Greetings.

**Comment by isaackearl** [comment]
For me Guzzle 6.0.1 is breaking on HHVM when I use it with Laravel (Socialite).  I can downgrade and use Guzzle 5 for now, but wanted to make a note here of what I'm seeing when trying to use Guzzle 6 on HHVM.

```
ErrorException in CurlFactory.php line 176:
Use of undefined constant CURLOPT_PROTOCOLS - assumed 'CURLOPT_PROTOCOLS'
```

**Comment by mtdowling** [comment]
HHVM nightly supports this option I believe. I think it's just a matter of them putting it in a release.

**Comment by iveoles** [comment]
I'm having a different issue with guzzle 6.0.1 and HipHop VM 3.7.2

    ErrorException in CurlFactory.php line 56:
    Invalid argument: option: 0

**Comment by joshuataylor** [comment]
StaticClient has the following function:
```
    public static function mount($className = 'Guzzle', ClientInterface $client = null)
    {
        class_alias(__CLASS__, $className);
        if ($client) {
            self::$client = $client;
        }
    }

```

This means that when running 'hhvm-repo-mode' on a repository that has guzzle, the following error appears:
```
Exception: class_alias with non-literal parameters is not allowed when WholeProgram optimizations are turned on\n
hphp failed
```

**Comment by GrahamCampbell** [comment]
What about 6.1.0 and 3.9.2?

**Comment by mtdowling** [comment]
Thanks for working on this!

I don't know that there's anything we can do at the Guzzle level to get HHVM compatibility at this point -- I think this is something HHVM will need to address. However, i there are remaining items where Guzzle is utilizing undefined PHP functionality that is not working with HHVM, then I'd prefer individual issues opened for each.
