### ISSUE TITLE
Ability to send requests through a proxy

### ISSUE THREAD

**Issue by mdpatrick** [guzzle/guzzle#57]
It would be nice if Guzzle supported sending requests through a proxy like Zend Http Client:

See Zend Http Client's "proxy adapter" here:
https://github.com/zendframework/zf2/blob/master/library/Zend/Http/Client/Adapter/Proxy.php

(Guzzle was brought to my attention via the recent merge of guzzle into the goutte library)

**Comment by raphaelsaunier** [comment]
For Guzzle 6, see http://docs.guzzlephp.org/en/latest/request-options.html#proxy
