### ISSUE TITLE
composer fails with "requires ext-curl" when cURL is installed

### ISSUE THREAD

**Issue by moagrius** [guzzle/guzzle#575]
I'm 100% positive I have curl installed - I use it often, and have for many hears.  That said, when I run composer from the Tumblr PHP API (which has guzzle as a dependency), it fails with:

```
Loading composer repositories with package information
Installing dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - guzzle/guzzle v3.8.1 requires ext-curl * -> the requested PHP extension curl is missing from your system.
    - guzzle/guzzle v3.8.0 requires ext-curl * -> the requested PHP extension curl is missing from your system.
    - guzzle/guzzle v3.7.4 requires ext-curl * -> the requested PHP extension curl is missing from your system.
    - guzzle/guzzle v3.7.3 requires ext-curl * -> the requested PHP extension curl is missing from your system.
    - guzzle/guzzle v3.7.2 requires ext-curl * -> the requested PHP extension curl is missing from your system.
    - guzzle/guzzle v3.7.1 requires ext-curl * -> the requested PHP extension curl is missing from your system.
    - guzzle/guzzle v3.7.0 requires ext-curl * -> the requested PHP extension curl is missing from your system.
    - guzzle/guzzle v3.6.0 requires ext-curl * -> the requested PHP extension curl is missing from your system.
    - guzzle/guzzle v3.5.0 requires ext-curl * -> the requested PHP extension curl is missing from your system.
    - guzzle/guzzle v3.4.3 requires ext-curl * -> the requested PHP extension curl is missing from your system.
    - guzzle/guzzle v3.4.2 requires ext-curl * -> the requested PHP extension curl is missing from your system.
    - guzzle/guzzle v3.4.1 requires ext-curl * -> the requested PHP extension curl is missing from your system.
    - guzzle/guzzle v3.4.0 requires ext-curl * -> the requested PHP extension curl is missing from your system.
    - guzzle/guzzle v3.3.1 requires ext-curl * -> the requested PHP extension curl is missing from your system.
    - guzzle/guzzle v3.3.0 requires ext-curl * -> the requested PHP extension curl is missing from your system.
    - guzzle/guzzle v3.2.0 requires ext-curl * -> the requested PHP extension curl is missing from your system.
    - guzzle/guzzle v3.1.2 requires ext-curl * -> the requested PHP extension curl is missing from your system.
    - guzzle/guzzle v3.1.1 requires ext-curl * -> the requested PHP extension curl is missing from your system.
    - guzzle/guzzle v3.1.0 requires ext-curl * -> the requested PHP extension curl is missing from your system.
    - Installation request for guzzle/guzzle >=3.1.0,<4 -> satisfiable by guzzle/guzzle[v3.1.0, v3.1.1, v3.1.2, v3.2.0, v3.3.0, v3.3.1, v3.4.0, v3.4.1, v3.4.2, v3.4.3, v3.5.0, v3.6.0, v3.7.0, v3.7.1, v3.7.2, v3.7.3, v3.7.4, v3.8.0, v3.8.1].
```

WAMP, Windows 8.1

Is this a known issue, or am I missing something?

TYIA

**Comment by pmsteil** [comment]
If you happen to be running on Codio, you must run this command:

`parts install php5-curl`

**Comment by ronaldaraujo** [comment]
@DRAKUN Perfect! Thanks!

**Comment by fakixlix** [comment]
Excelente !! Funciona. Gracias :)

**Comment by JoseCage** [comment]
Thank you so much @drakun.. It solve my problem.

**Comment by zekylaf** [comment]
Thanks you @DRAKUN

**Comment by yuvraj339** [comment]
Thanks you @DRAKUN

**Comment by ruhulsw** [comment]
if you use php7 then use apt-get install php-curl

**Comment by framm** [comment]
Thanks @ruhulsw !!

**Comment by joenmarz** [comment]
if you are using php 5.6 then 

> apt-get install php5.6-curl

**Comment by kamaroly** [comment]
if you are using php7.1 then it should apt-get install php7.1-curl

**Comment by mizanur-rahman** [comment]
For anyone who uses php7.0

`sudo apt-get install php7.0-curl`

**Comment by simplyniceweb** [comment]
For windows with PHP7:
find ;extension=php_curl.dll in your php.ini and remove the ";".

**Comment by Samgithub1997** [comment]
Thanks @ruhulsw  @mizanur-rahman

**Comment by mohitpawar10** [comment]
sudo apt-get install php-curl 
worked for me! for php 7.1

**Comment by hariomwebdeveloper** [comment]
Just sudo apt-get install php-curl resolved my problem.

**Comment by saydulk** [comment]
sudo apt-get install php-curl works for me :)

**Comment by delucaspinto** [comment]
First: apt-get update
After: apt-get install php-curl

**Comment by Jagdeep-Sing** [comment]
PHP 7.0: `sudo apt-get install php-curl`
    PHP 5.6: `sudo apt-get install php5.6-curl`
    PHP 5.5: `sudo apt-get install php5.5-curl`

**Comment by serup** [comment]
I had similar issue on windows and it turned out I needed to add following line in my php.ini file:
extension=php_curl.dll

it turns out that curl was not installed correct, hence not capable for composer to fetch the necessary files for guzzle

**Comment by r9software** [comment]
has someone fixed this on mac?

**Comment by Paul-digitalquill** [comment]
I am still having the same problem with raspberry pi.

**Comment by zlocorp** [comment]
> has someone fixed this on mac?

Try `composer install --ignore-platform-reqs`

**Comment by MuhammadSulman** [comment]
sudo apt-get install php7.3-curl for php 7.3
One thing, I want to mention here for this particular extension you have to specify your php version that you can find out by php -v and replace with above 7.3 with your current configure/installed version.

**Comment by ajadi473** [comment]
> sudo apt-get install php7.3.*-curl for php 7.3

This worked for me

**Comment by aacassandra** [comment]
for php 7.4
sudo apt-get install php7.4-curl

**Comment by MertGunduz** [comment]
@DRAKUN 

Thanks a lot, I solved the problem by downloading that package! 👏🏻 ❤️
