### ISSUE TITLE
Binding to IP support

### ISSUE THREAD

**Issue by webbie** [guzzle/guzzle#590]
Would be cool if we can bind to specific IP for making all http requests. Real scenario example: on server with multiple IPs we need to use specific (whitelisted) one for making requests to payment API, etc).

**Comment by site-me** [comment]
with Guzzle 6 you is a bit simpler:
`$client->get( '/login.php', 'curl' => [
        CURLOPT_INTERFACE => xxx.xxx.xxx.xxx
  ]);`

**Comment by stanislavdavid** [comment]
@site-me there is one mistake. It should be:

     $client->get( '/login.php', ['curl' => [ CURLOPT_INTERFACE => xxx.xxx.xxx.xxx ]]);

**Comment by PaulCnth** [comment]
new Client with options:
`'curl.options' => [CURLOPT_INTERFACE => 'xxx.xxx.xxx.xxx']`
it works.

At first, I test the curl command in CentOS 7.

> curl -vvv --interface example.com

and then use the GuzzleHTTP, the same effect.
