### ISSUE TITLE
Guzzle with images

### ISSUE THREAD

**Issue by evancauwenberg** [guzzle/guzzle#597]
Hi there

I have a question related to images and guzzle.
I want to display images from a third party webservice. The images need a custom request header with a valid token to view them.

I can download the image (line 225) but that isn't exactly what i want.

If i log in in the backend of the webservice i get a cookie with the token. If i then surf to the image the image displays to. So i tought maybe to use the guzzle cookie plugin? But this still gives me the problem that i cant display the image.

Thnx in advance!
223         $client = new \Guzzle\Service\Client();
223         $req = $client->get('/v1/api/photo/a5a9e335-60ca-429f-842a-b4a9c1d52385.jpg');
224         $req->addHeader('access_tokenid', 'AAAAAAAAAAAAAAAA');
225         // $req->setResponseBody('/tmp/test.jpg');
226         $response = $req->send();
227 
228         $body = $response->getBody();
229         var_dump($body);
230                 $stream = $body->getStream();
231                 //var_dump($stream);
232                 var_dump(gettype($stream));
233                 // header('Content-Type: image/jpeg');
234 
235 
236                 echo 'data:image/png;base64,'.                                  base64_encode(imagejpeg($stream));
237 die;

**Comment by praditha-ovo** [comment]
Hi @evancauwenberg , can you share your solutions..?

thanks
