### ISSUE TITLE
Http Basic Auth does not work with Guzzle\Service\Client

### ISSUE THREAD

**Issue by witwit** [guzzle/guzzle#605]
I am trying to use the Service\Client to fetch data from a REST web service. Unfortunately I need basic authentication to do so. Passing the "auth" configuration parameter, like stated in the docs, does not work.

What I do:

``` php
$client = new Client('http://webservice/url', [
            'defaults' => [
                'auth'    => ['username', 'password'],
            ]
        ]);
```

Webservice denies access. Using the same combination of login/pass works perfectly in the browser. Does anybody have an idea where the problem may be?

**Comment by jayhaase** [comment]
I did a similar thing by mistakenly including an old composer package. I had included the guzzle/guzzle that only goes up to version 3.9.3.

Guzzle is currently up to version 6.0.1. The correct package is: guzzlehttp/guzzle.
