### ISSUE TITLE
Reason for cURL Multi as default adapter

### ISSUE THREAD

**Issue by pandydavey** [guzzle/guzzle#607]
I'm using PHP < 5.5 and the default adapter is CurlMulti as outlined in the documentation. 

I've noticed that using CurlMulti causes a huge overhead and is up to 10x slower than performing a simple cURL request. 

Is there a reason why CurlHandle isnt the default for serial connections?

**Comment by thorbenheins** [comment]
Hi mtdowling,

what exactly are you referring to when you say `StreamAdapter` ? Could you please elaborate on that? We are using Guzzle3 in Combination with PHP 5.3.3 and suffer from curl_multi_exec's performance during functional testing.

Regards,
Thorben
