### ISSUE TITLE
InvalidArgumentException when posting integers and booleans

### ISSUE THREAD

**Issue by futurevision** [guzzle/guzzle#628]
The post() method doesn't accept booleans and integers in the body:

``` php
$client = new GuzzleHttp\Client;
$client->post('http://docs.guzzlephp.org/en/latest/', [
        'body' => [
                'foo' => false,
                'bar' => 1
        ]
]);

/*
throws:

object(stdClass)#125 (5) {
  ["__CLASS__"]=>
  string(24) "InvalidArgumentException"
  ["message"]=>
  string(30) "Invalid resource type: boolean"
  ["code"]=>
  int(0)
  ["file"]=>
  string(81) "<path>vendor\guzzlehttp\streams\src\functions.php"
  ["line"]=>
  int(39)
}
*/
```

I expect Guzzle to convert them to strings for me just like the get() function does.

**Comment by karlwilbur** [comment]
What happened to this? It looks like the PR was never merged. This is still an issue:
http://stackoverflow.com/questions/33085043/postmark-guzzle-invalidargumentexception-invalid-resource-type-boolean

**Comment by y4nnick** [comment]
I have the same problem.
