### ISSUE TITLE
weird php bug

### ISSUE THREAD

**Issue by cordoval** [guzzle/guzzle#644]
I am running a project with guzzle and under the php $ sudo cat /var/log/apache2/error.log

i see these weird errors, and i am on travis-ci enterprise with php5.5

``` sh
PHP Parse error:  syntax error, unexpected '[' in 
/home/travis/build/x/y/vendor/guzzlehttp/guzzle/src/functions.php on line 20
```

**Comment by BentCoder** [comment]
@dickolsson saved my life https://github.com/travis-ci/travis-ci/issues/6165
Thanks
