### ISSUE TITLE
Can't use $response->isSuccessful() because an exception is thrown

### ISSUE THREAD

**Issue by benswinburne** [guzzle/guzzle#664]
I have recently used Guzzle to scrape a URL, and this works fine when there are no errors.

If however there is for example a 404, let's say 

```
$response = $client->get('http://www.google.com/test')->send();
```

The manual ([Response Status Line](http://guzzle.readthedocs.org/en/latest/http-client/response.html#response-status-line)) suggests the above code will then allow me to call

```
$response->isSuccessful();
```

But `send()` throws a `ClientErrorResponseException` when there is an error receiving the request. The exception thrown is as follows

```
Guzzle\Http\Exception\ClientErrorResponseException
Client error response
  [status code] 404
  [reason phrase] Not Found
  [url] http://www.google.com/test
```

So, catching that exception obviously prevents my application halting, but then means I don't have a response object on which to call the various `isX` methods.

Clearly catching the exception gives me the same answer as `isSuccessful` to some degree, but some of the other methods on the aforementioned manual page would also be useful to use.

Is this incorrect documentation or a bug or am I simply using Guzzle wrong?

**Comment by GabrielDelepine** [comment]
@pjcdawkins answer is correct but the link is broken.

It's still working for Guzzle v6 but it's not documented anymore.

But [this test file](https://github.com/guzzle/guzzle/blob/a1c4a74bf31d4e41d783fafb635c806cc19c2e9b/tests/ClientTest.php) gives the guarantee that this option is well supported.
