### ISSUE TITLE
100% of CPU usage on curl_multi_exec

### ISSUE THREAD

**Issue by Maykonn** [guzzle/guzzle#756]
Hi,

I'm getting 100% of CPU usage when executing parallel request with sendAll(). This lock the CPU and the whole system is failing. See in attachment:

![upload 1](https://cloud.githubusercontent.com/assets/1479805/3780367/e70a4002-198b-11e4-8e2c-670065ffd35f.png)

**Comment by moon0326** [comment]
@mtdowling we are having the similar issue. What was your value for CURLOPT_MAX_SEND_SPEED_LARGE and CURLOPT_MAX_RECV_SPEED_LARGE? I'm having hard time understanding how CURLOPT_MAX_RECV_SPEED_LARGE works

**Comment by Chienle** [comment]
tried set MAX_RECV_SPEED_LARGE value to 1024 ?
