### ISSUE TITLE
Bug setting base URL that does not end with a slash.

### ISSUE THREAD

**Issue by dtrenz** [guzzle/guzzle#770]
It appears that setting a base URL that does not end in a "/" will cause the last URI segment to be omitted from requests.
## Steps to reproduce

Create a client with a base URL that doesn't terminate in a slash:

``` php
$client = new GuzzleHttpClient([
    'base_url' => 'http://www.web-service.com/api'
]);
```

 Perform a request to a relative endpoint:

``` php
$response = $client->get('users');
```

 Actual request URL will be missing the last URI segment from the base URL (e.g. "http://www.web-service.com/users" instead of "http://www.web-service.com/api/users")

**Comment by janopae** [comment]
If you want to request the base uri, but without a trailing slash, you can use `..`:

So if your base uri is `http://foo.bar/baz/` (as we learned: you need the trailing slash), but at one point, you want to just request `http://foo.bar/baz` (without the trailing slash), then you can request `../baz` to get there.
