### ISSUE TITLE
no setField in Body

### ISSUE THREAD

**Issue by khusseini** [guzzle/guzzle#798]
I have tried from docs 

```
$request = $client->createRequest('POST', 'http://httpbin.org/post');
$postBody = $request->getBody();

// $postBody is an instance of GuzzleHttp\Post\PostBodyInterface
$postBody->setField('foo', 'bar');
echo $postBody->getField('foo');
// 'bar'

echo json_encode($postBody->getFields());
// {"foo": "bar"}

// Send the POST request
$response = $client->send($request);
```

However the PostBody does not have a method setField...
What would be the correct way?

I am using version 4.2.1

**Comment by oytuntez** [comment]
I am having a similar issue with PHPStorm. 

```php
$body = $request->getBody();
$body->addFile(new PostFile());
```

This works, however `addFile` method is not found by PHPStorm; so the inspection fails. It's a documentation issue, but may be worth taking a look.
