### ISSUE TITLE
cURL can't verify ssl certificates (possibly only on Yosemite)

### ISSUE THREAD

**Issue by jonnybarnes** [guzzle/guzzle#819]
I'm running Yosemite beta 2, I have PHP-5.6 installed via homebrew compiled against homebrew-curl and homebrew-openssl. Guzzle can't verify SSL certs. For example:

```
$client = new \GuzzleHttp\Client();
$response = $client->get('https://google.com');
return $response;
```

results in a RequestException with error message `cURL error 51: SSL: certificate verification failed (result: 5)`

**Comment by hookdump** [comment]
So, has anyone figured out how to solve this?

**Comment by mtdowling** [comment]
@hookdump What isn't working for you? Did you see https://github.com/guzzle/guzzle/issues/819#issuecomment-59809599?

**Comment by jonnybarnes** [comment]
@hookdump as @mtdowling said, this should be working now? If you use homebrew make sure that the curl command points to the system version. You can check with the output from `which curl`.

**Comment by Synchro** [comment]
I was getting this error 60 with PHP 5.6.20 on 10.11.4 with guzzle 6.2.0, tracked it down to my libcurl (7.48 from homebrew) being compiled with libressl. I recompiled using the default openssl and the problem went away.

**Comment by ice6** [comment]
although this issue was closed, but I hope my answer can help the later googlers.
use this command to check the **Certificate chain**
`openssl s_client -host {the-site-with-tls-problem} -port 443`
then check whether the issuer's **Root Certificates** exist in your system, if not add the Root Certificate to your own system.

**Comment by rickrvo** [comment]
check your ~/.gitconfig file
I fixed my problem by temporarily removing the lines mentioning sslCAInfo and sslVerify.

then don't forget to add them later case the certificate is one that you are using for something else.

**Comment by a-ast** [comment]
OSX EL Capitan (10.11.1)
PHP: 5.6.27
Guzzle: 6.2.2 

I have the same issue:
Works: `curl https://google.com`
Fails: `curl --cacert /usr/local/etc/openssl/cert.pem https://google.com` 
with error
```
curl: (51) SSL: certificate verification failed (result: 5)
```

Tried and *didn't work*:
1. $client = new Client(['defaults' => ['verify' => true]]);
2. $client = new Client(['defaults' => ['verify' => false]]);
3. $client = new Client(['defaults' => ['verify' => '/usr/local/etc/openssl/cert.pem']]);
4. $client = new Client(['defaults' => ['verify' => {cert from http://curl.haxx.se/docs/caextract.html}]]);
5. Latest curl installed with homebrew also fails

**Comment by Guillaumez** [comment]
Updating PHP did the thing

**Comment by mirko77** [comment]
@a-ast I have the same problem, did you manage to fix it?

**Comment by mathiasconradt** [comment]
@Guillaumez From which php version to which did you update?
