### ISSUE TITLE
Notice: Corrupt member variable name in vendor/guzzlehttp/guzzle/src/Subscriber/HttpError.php on line 31

### ISSUE THREAD

**Issue by SergeC** [guzzle/guzzle#836]
I receive such output after few requests, may be this caused by HTTP error 429, PHP 5.5.10, Guzzle is latest version. Please fix it.

**Comment by ashenn** [comment]
Hi everyone,
I managed to get this error with a small mistake I've made. 

`
$likes = $brand->get("upVoteCount");
$likes = ($likes == null) ? 0 : $like;
`

Notice the last $like (I forgot the 's') and that give me the same error.
I don't know if my post is useful, but i thought it could be a good thing to track the bug.

Anyway, good day to you all.
