### ISSUE TITLE
Where do I find this vendor/autoload.php script?

### ISSUE THREAD

**Issue by pkrumins** [guzzle/guzzle#854]
I'm trying to install and use Guzzle and the documentation says: 

```
After installing, you need to require Composer's autoloader:
require 'vendor/autoload.php';
```

However I'm unable to find this vendor/autoload.php script. Do you've a copy that I can use, or could you tell me where to find it?

**Comment by hemuj** [comment]
TRY to use sendgrid while testing getting
**Warning: require(vendor/autoload.php): failed to open stream...**
@pkrumins plz help..

**Comment by sagikazarmark** [comment]
Can you tell us a bit more information? Have you downloaded the zip archive? Installed with composer? Some code examples?

Also, I am 98% sure this is not a bug in guzzle, so I would suggest using StackOverflow for these kind of questions.

**Comment by kapitansaman** [comment]
[http://composite-view.ir](url)
