### ISSUE TITLE
PHP Notice:  Undefined offset: 1 in /vendor/guzzlehttp/ringphp/src/Client/CurlFactory.php on line 82

### ISSUE THREAD

**Issue by camcima** [guzzle/guzzle#873]
``` php
            // Trim out 100-Continue start-lines
            if ($startLine[1] == '100') {
                $startLine = explode(' ', array_shift($headers), 3);
            }
```

**Comment by glodov** [comment]
I used the latest dev version it does not work.
and I used the latest stable version 6.3.3 it does not work.
PHP Notice:  Undefined offset: 0 in /Users/yaroslav/Sites/yaro/jira/vendor/guzzlehttp/guzzle/src/Client.php on line 354
