### ISSUE TITLE
Post file returns Max Content-Length exceeded

### ISSUE THREAD

**Issue by moe2566** [guzzle/guzzle#880]
This is from chrome dev tools capturing the file upload on the destination website where the file upload works just fine.
> Request Headers:
> Accept:text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
> Accept-Encoding:gzip,deflate
> Accept-Language:en-US,en;q=0.8
> Cache-Control:max-age=0
> Connection:keep-alive
> Content-Length:10573
> Content-Type:multipart/form-data; boundary=----WebKitFormBoundaryAauA5ite0s0Ci520
> Cookie:JSESSIONID=9D456DCA826972CFA443D62E11AF2B15
> Host:destination.site.com
> Origin:https://destination.site.com
> Referer:https://destination.site.com/upload_file.jsp?id=0000&type=round&companyid=0000&d_type=O
> User-Agent:Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/38.0.2125.104 Safari/537.36

> Request Payload:
> ------WebKitFormBoundaryAauA5ite0s0Ci520
> Content-Disposition: form-data; name="todo"
> upload
> ------WebKitFormBoundaryAauA5ite0s0Ci520
> Content-Disposition: form-data; name="id"
> 0000
> ------WebKitFormBoundaryAauA5ite0s0Ci520
> Content-Disposition: form-data; name="companyid"
> 0000
> ------WebKitFormBoundaryAauA5ite0s0Ci520
> Content-Disposition: form-data; name="type"
> round
> ------WebKitFormBoundaryAauA5ite0s0Ci520
> Content-Disposition: form-data; name="d_type"
> B
> ------WebKitFormBoundaryAauA5ite0s0Ci520
> Content-Disposition: form-data; name="uploadfile"; filename="loadFile.xlsx"
> Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet

> ------WebKitFormBoundaryAauA5ite0s0Ci520--

And this is my script:
> $post_fields = array(
>     'todo'          => 'upload',
>     'id'     => '0000',
>     'companyid'     => '0000',
>     'type'          => 'round',
>     'd_type' 	   => 'B'
> );
> $request = $client->createRequest('POST', 'https://destination.site.com/upload_file.jsp', ['cookies' => $jar]);
> $postBody = $request->getBody();
> foreach ($post_fields as $key => $value) {
>     $postBody->setField($key, $value);  }   
> $postBody->addFile(new PostFile('uploadfile', fopen($filePath, 'r')));
> $response = $client->send($request);

I tried setting every single HEADER like in chrome but am still getting a 500 error.
I do not have control over the destination server, the most they would give me is that it produces a Java error "java.io.IOException: Max Content-Length exceeded"

Any insight would be greatly appreciated.
Thanks

**Comment by mtdowling** [comment]
Doing a triage. Closing until there's more information that allows me or someone else to reproduce the error.
