### ISSUE TITLE
Can not disable/remove User-Agent or set it to empty string

### ISSUE THREAD

**Issue by frzsombor** [guzzle/guzzle#894]
I'm quite new to guzzle so maybe it's not an issue/deficiency, just my inexperience.

I've tried to remove 'User-Agent' from requests like this:

```
$client = new Client([
    'defaults' => [
        'headers'         => [
            'User-Agent' => '',
        ],
    ],
]);
```

I've also tried null, false, but the request always has been sent with the default user-agent. I couldn't even set it to empty string ("").

I've found that <a href="https://github.com/guzzle/guzzle/blob/master/src/Client.php#L347-L355">this</a> is where guzzle sets default user-agent, so a type casting <a href="https://github.com/guzzle/RingPHP/blob/1.0.2/src/Core.php#L118">here</a> in RingPHP 1.0.2 can cause this problem. However, it's been modified on the current master branch of RingPHP.

I think setting the user-agent to an empty string and completely remove it from the request can be necessary sometimes. I hope the next tag of RingPHP will fix this, or at least make it possible to disable the user-agent somehow.

**Comment by ctrlaltdylan** [comment]
Perfect. Exactly what I was looking for. Thank you!

**Comment by twigs67** [comment]
Little late to the party, but I am not able to alter the headers on my requests.  I believe I've tried everything within Guzzle. I'm beginning to think that the headers are hard-coded with curl. Is this possible? Is there a way to change options via curl?

**Comment by ghunti** [comment]
With Guzzle 6.0 you don't have `getDefaultOption` and `setDefaultOption`, so instead you can do:
`new \GuzzleHttp\Client(['headers' => ['User-Agent' => null]]);`

**Comment by twigs67** [comment]
Thanks ghunti, I appreciate the reply.

**Comment by Libre12** [comment]
> With Guzzle 6.0 you don't have `getDefaultOption` and `setDefaultOption`, so instead you can do:
> `new \GuzzleHttp\Client(['headers' => ['User-Agent' => null]]);`

I tried this, but the upon debugging I found out the the header is still being sent (just blank).

Can I get rid of this header completely?

**Comment by skaero** [comment]
@Libre12 The only way I have found to remove the `User-Agent` header completely in Guzzle 6.x is to add a middleware to remove it:
```
use GuzzleHttp\Client;
use GuzzleHttp\HandlerStack;
use GuzzleHttp\Middleware;
use Psr\Http\Message\RequestInterface;

$handler_stack = HandlerStack::create();

$handler_stack->push(Middleware::mapRequest(function (RequestInterface $request) {
    return $request->withoutHeader('User-Agent');
}));

$client = new Client([
    'handler' => $handler_stack
]);
```
