### ISSUE TITLE
URI templates && arrays as query parameter

### ISSUE THREAD

**Issue by nlegoff** [guzzle/guzzle#90]
Hi, 

I ran into an issue by generating URLs using array into the data URI template variable

``` php
<?php

$request = $client->get(array('http://example.com{+path}{/segments}{?query,data*}', array(
    'path'     => '/foo/bar',
    'segments' => array('one', 'two'),
    'query'    => 'test',
    'data'     => array(
        'more' => array('fun', 'icecream')
    )
)));
```

I think that the resulting of the following URL should become `http://example.com/foo/bar/one/two?query=test&more[]=fun&more[]=icecream` instead the array is encoded using rawurlencode function which is not possible.

**Comment by florianajir** [comment]
+1
I need to build get query like `search/?facet=1&facet=2`
```
$query = array('facet' => array('1', '2'));
$response = $this->client->get('/search', array('query'=>$query));
```
this skip my query array..

**Comment by softwarevamp** [comment]
i have to fix for this https://github.com/guzzle/guzzle/pull/1875
