### ISSUE TITLE
[feature request] Dynamically add requests to Pool

### ISSUE THREAD

**Issue by naquad** [guzzle/guzzle#919]
I have a case where I need to dynamically add requests to the Pool, but from what I see current Pool implementation doesn't allow that.

Use case would be like:

```
$pool = new Pool(
  $client,
  [$client->createRequest('GET', 'http://www.example.com')],
  ['complete' => 'parser']
);
$pool->wait();

function parser(CompleteEvent $e) {
   global $pool; // sorry for global, just for sake of conciseness
   /// handling
   /// ...
   /// some elements were discovered and need to be added to the Pool:
   $pool->add($client->createRequest('....'));
   $pool->add($client->createRequest('....'));
   $pool->add($client->createRequest('....'));
}
```

**Comment by paslandau** [comment]
It's not really necessary to use an `AppendIterator`. The normal `ArrayIterator` is capable of adding requests itself. See my comment at https://github.com/guzzle/guzzle/issues/946#issuecomment-92018988 for a full example or this gist for a more in-depth example of a comparison between [generator, retry and sequential send with guzzle](https://gist.github.com/paslandau/ce8f8c034dd7058c0bfc).
