### ISSUE TITLE
with xdebug enabled, get request stuck in a loop

### ISSUE THREAD

**Issue by luis-deguzman** [guzzle/guzzle#942]
hi,

i am using guzzle on a laravel project.  the client works fine - i am able to make GET and POST requests.  however, when I enable xdebug (under netbeans), a simple GET request get stuck in a loop. I am able to trace where where the loop is occurring:

/src/Adapter/Curl/MultiAdapter.php->perform method

the request gets stuck in the do loop. i have my breakpoint at line 147 and it just goes through this line over and over again.

any help is appreciated. AND thanks for a great library!

environment:
php 5.4.30
xdebug 2.2.6
laravel 4.2.x

**Comment by Eddcapone** [comment]
If I set `xdebug.remote_autostart=0` aka `xdebug.start_with_request=no` (xdebug 3) then it just does not hit any breakpoint
