### ISSUE TITLE
guzzle php mock response content

### ISSUE THREAD

**Issue by tzookb** [guzzle/guzzle#945]
I want to mock a response to the guzzle request:

```
 $response = new Response(200, ['X-Foo' => 'Bar']);

 //how do I set content of $response to--> "some mocked content"

 $client = Mockery::mock('GuzzleHttp\Client');
 $client->shouldReceive('get')->once()->andReturn($response);
```

I noticed I need to add as third parameter the interface:

```
 GuzzleHttp\Stream\StreamInterface
```

but there are so many implementations of it, and I want to return a simple string...

Any ideas?

**Comment by trckster** [comment]
After hours of searching I found a solution: https://laracasts.com/discuss/channels/testing/mocking-the-guzllehttpclient-class-is-not-working
