### ISSUE TITLE
Suggestions to GuzzleHttp\Pool

### ISSUE THREAD

**Issue by stil** [guzzle/guzzle#946]
I think that Pool misses 2 important features:
- customizable timeout on `wait()` method. At the moment, I can't do other tasks while requests pool is running. For example I would like to cancel some requests and add new ones depending on external factors.
- adding and removing requests to/from pool at runtime

Here is an exampe what I need to do (and what Guzzle isn't able to do now).
There is particular HTTP resource that I need to check constantly for any updates.
It takes 300 ms for single update check. Currently I just repeat request one after another. It is ineffective, because I waste the time waiting for every request.

```
Timeline:
request 1: [300 ms] // result after 300 ms
request 2:          [300 ms] // result after 600 ms
request 3:                   [300 ms] // result after 900 ms
```

It would be far better when I could add new requests every 50 ms.

```
Timeline:
request 1: [300 ms] // result after 300 ms
request 2:    [300 ms] // result after 350 ms
request 3:       [300 ms] // result after 400 ms
```

**Comment by alixaxel** [comment]
+1 for the ability to add requests to a pool on runtime, also #919.

http://stackoverflow.com/q/28105093/89771

**Comment by mtdowling** [comment]
You can pass an iterator to the pool that can be appended to. Adding requests at runtime is not needed now that the pool continuously ensures that the number of concurrent requests matches the pool size.

**Comment by exfriend** [comment]
Dynamically changing the pool (not thread count, just request count) is for re-scraping items while working with proxy lists for 100% content delivery. I use this to build high complexity scrapers. Currently thre is what I have:
https://github.com/exfriend/cloudfactory/blob/master/src/Exfriend/CloudFactory/Engine.php

All I want is ability to change proxy if request fails and push it back to queue. My library would be much stronger (or not needed at all) if Guzzle had some features to handle this case.
I noticed that this part is particularly week in Guzzle (or in its documentation maybe?).

I have much time working with scraping, so I might write some code to use the power of Guzzle on CloudFactory, but don't know where to start. Any ides ?

**Comment by thebennos** [comment]
Interesting problem. 
Maybe the 
https://github.com/guzzle/retry-subscriber

can help, you can hook in. Out of the box it support the retry of http response 500 and 503. 
You can add more status codes and write some code to add it again to the pool.

**Comment by paslandau** [comment]
There seems a bit of confusion around the topic of appending new requests to a running pool. Since I ran into the same problem, I created an example to copy and paste to get you started:

```php
<?php

use GuzzleHttp\Client;
use GuzzleHttp\Event\EndEvent;
use GuzzleHttp\Message\Request;
use GuzzleHttp\Message\Response;
use GuzzleHttp\Pool;
use GuzzleHttp\Subscriber\Mock;

include_once "vendor/autoload.php";

$client = new Client();
// convenience function to generate new requests for appending
$createRequestFn = function($url) use ($client){
    return $client->createRequest("GET", $url);
};

$num = 10; // number of initial requests

// each initial request will append one new request
// so we need twice as much responses
$responses = [];
for($i = 0; $i < $num*2; $i++){
    $responses[] = new Response(200);
}
// populate and attach the mock subscriber
$mock = new Mock($responses);
$client->getEmitter()->attach($mock);

// genereate the initial requests
$requests = [];
for($i = 0; $i < $num; $i++){
    $request = $createRequestFn("/request_$i");
    $request->getConfig()->set("initial",true);
    $requests[] = $request;
}

// use a generator to append requests "on the fly"
$generator = new ArrayIterator($requests);

// convenience variable to keep track of the number of requests
$total = 0;
$appendFn = function(EndEvent $ev) use (&$total, $generator, $createRequestFn){
    $request = $ev->getRequest();
    $total++;
    $oldUrl = $request->getUrl();
    echo "[Request {$total}] Got request with url {$oldUrl}\n";
    // check if it's an initial request
    // if so, create and append a new request
    $isInitial = $request->getConfig()->get("initial");
    if($isInitial){
        $oldUrl .= "_appended_request";
        /** @var Request $request */
        $request = $createRequestFn($oldUrl);
        $request->getConfig()->set("initial",false);
        // append new request
        $generator->append($request);
    }
};
$options = [
    "end" => $appendFn,
];
$pool = new Pool($client,$generator,$options);
$pool->wait();
```

This yields an output similar to this:

```
[Request 1] Got request with url /request_0
[Request 2] Got request with url /request_1
[Request 3] Got request with url /request_2
[Request 4] Got request with url /request_3
[Request 5] Got request with url /request_4
[Request 6] Got request with url /request_5
[Request 7] Got request with url /request_6
[Request 8] Got request with url /request_7
[Request 9] Got request with url /request_8
[Request 10] Got request with url /request_9
[Request 11] Got request with url /request_0_appended_request
[Request 12] Got request with url /request_1_appended_request
[Request 13] Got request with url /request_2_appended_request
[Request 14] Got request with url /request_3_appended_request
[Request 15] Got request with url /request_4_appended_request
[Request 16] Got request with url /request_5_appended_request
[Request 17] Got request with url /request_6_appended_request
[Request 18] Got request with url /request_7_appended_request
[Request 19] Got request with url /request_8_appended_request
[Request 20] Got request with url /request_9_appended_request
```

See this gist for a more in-depth example of a comparison between [generator, retry and sequential send with guzzle](https://gist.github.com/paslandau/ce8f8c034dd7058c0bfc).

**Comment by dragonattack** [comment]
Is there any examples appended urls for Guzzle 6?
