### ISSUE TITLE
Problems with Guzzle 5 mocks

### ISSUE THREAD

**Issue by jenssegers** [guzzle/guzzle#954]
I'm have some issues with the Guzzle 5 mocks. I updated this library to use Guzzle 5 https://github.com/jenssegers/php-proxy/blob/guzzle5/src/Adapter/Guzzle/GuzzleAdapter.php and updated the existing unittest as described here http://guzzle.readthedocs.org/en/latest/testing.html.

But unfortunately, when running the unittest I keep getting either `GuzzleHttp\Ring\Exception\RingException: cURL error 3: <url> malformed` or the actual response instead of the mocked response.

**Comment by mtdowling** [comment]
The option you need to pass to the constructor is "handler" not adapter: https://github.com/jenssegers/php-proxy/blob/master/tests/Proxy/Adapter/Guzzle/GuzzleAdapterTest.php#L41

See: http://docs.guzzlephp.org/en/latest/clients.html

**Comment by jenssegers** [comment]
You were looking at the test file on the master branch, the guzzle 5 adjustments are in the guzzle 5 branch. It does:

```
$mock = new Mock([$this->createResponse()]);

$client = new Client;

$client->getEmitter()->attach($mock);

$this->adapter = new GuzzleAdapter($client);
```
