### ISSUE TITLE
Test suite start failing with upcoming 5.5.21RC1 / 5.6.5RC1

### ISSUE THREAD

**Issue by remicollet** [guzzle/guzzle#957]
For your information, Fedora is running some CI on the PHP stack, which include running test suite of all the available packages test suite against the latest RC (so PHP 5.6.5RC1)

See http://koschei.cloud.fedoraproject.org/package/php-guzzlehttp-guzzle

**Comment by mtdowling** [comment]
Thanks for the heads up. I just removed that line from the test for now. I still have to figure out how to address the streams package. If I understand the change correctly, I believe you always have to call fread() more than once now to trigger an feof() now (which seems broken). Closing this issue, but leaving  https://github.com/guzzle/streams/issues/29 open.

**Comment by remicollet** [comment]
> I believe you always have to call fread() more than once now to trigger an feof() now (which seems broken). 

Not really broken, but make memory streams consistent with file streams:

    while (!feof($stream)) var_dump(fgetc($stream));  }

Previous PHP version with memory stream :

    string(1) "t"
    string(1) "e"
    string(1) "s"
    string(1) "t"
    done

Previous PHP with file stream and new PHP with memory or file stream

    string(1) "t"
    string(1) "e"
    string(1) "s"
    string(1) "t"
    bool(false)

But yes, behavior change are always uggly...
