### ISSUE TITLE
Non-blocking Streams

### ISSUE THREAD

**Issue by bryannielsen** [guzzle/guzzle#961]
Is there anyway to setup a non-blocking stream with the current version of Guzzle?  I've tried creating a stream decorator and calling [stream_set_blocking()](http://php.net/manual/en/function.stream-set-blocking.php) on the resource but it doesn't seem like the GuzzleStreamWrapper supports this.  

I'm wondering if this is already handled some other way inside of Guzzle or if I'm just way off in left field.  I looked through the docs and source but couldn't find anything that seemed to help for my situation.  I'm trying to consume a streaming api without having to wait for a full-length `fread` if possible.

**Comment by mtdowling** [comment]
> it doesn't seem like the GuzzleStreamWrapper supports this.

Can you elaborate on this?

**Comment by bryannielsen** [comment]
Sure thing!

If I have a call like this - `stream_set_blocking($resource, 0);`
I end up getting this error

    stream_set_blocking(): GuzzleHttp\Stream\GuzzleStreamWrapper::stream_set_option is not implemented!

I was temporarily just trying this inside of the InflateStream class to see if it would work though it seems like I could do something similar with a [custom decorator](http://guzzle.readthedocs.org/en/latest/streams.html?highlight=decorator#creating-custom-decorators) if this could work.

Thanks for looking into this!

**Comment by mtdowling** [comment]
The Guzzle stream wrapper does not support this, but you could pass a stream into a Guzzle stream wrapper that already has stream_set_blocking set to 0:

```php
$stream = fopen('blah', 'r');
stream_set_blocking($stream, 0);
$guzzleStream = GuzzleHttp\Stream\Stream::factory($stream);
$phpStream = GuzzleHttp\Stream\GuzzleStreamWrapper::getResource($guzzleStream);
```

**Comment by bryannielsen** [comment]
Okay perfect, I'll give that a shot.  Thanks for the help and the great library!
