### ISSUE TITLE
Can't set CURLOPT_PROXY

### ISSUE THREAD

**Issue by stanislas-prime** [guzzle/guzzle#966]
Hi. Please help:

I am trying to set CURLOPT_PROXY but it doesn't work. Maybe I do something wronh?

$client = new GuzzleHttp\Client();
$res = $client->get('http://www.ipmango.com/api/myip', [
    'config' => [
        'curl' => [
            'CURLOPT_PROXY' => '194.135.220.18:8081',
        ],
    ]
]);
echo $res->getBody();

but it displays my ip addess, not that what I set. How to fix this? Thanks!

**Comment by mtdowling** [comment]
Can you try just using the `proxy` request option? Are you sure curl is enabled?

**Comment by mtdowling** [comment]
This should work if curl is enabled, but I recommend using the "proxy" request option: https://github.com/guzzle/guzzle/pull/967

**Comment by stanislas-prime** [comment]
Yes, curl is enabled. If I do this by "raw" curl request - everything works.. So? What is solution?
