### ISSUE TITLE
ServerRequestInterface implementation

### ISSUE THREAD

**Issue by janwalther** [guzzle/guzzle#968]
I recently read about [PSR-7](https://github.com/php-fig/fig-standards/blob/master/proposed/http-message.md) and wondered if Guzzle already has or plans to have a class which implements the ServerRequestInterface. This interface defines an unmutable object which encapsulates all request parameters (like GET, POST, cookies etc.)

**Comment by mtdowling** [comment]
There's no plan to implement a server specific interface. As for PSR-7 in general: I'm not sure. It's still not a thing, and it has changed dozens of times since I initially proposed it. When it's published, I'll consider using it.
