### ISSUE TITLE
Uncaught exceptions

### ISSUE THREAD

**Issue by sebastiaandegeus** [guzzle/guzzle#969]
I'm trying to catch exceptions in a post request but at the moment no exceptions are being catched. For instance a 404 not found throws the following exception:

```
Fatal error: Uncaught exception 'GuzzleHttp\Exception\ClientException' with message 'Client error response [url] http://localhost:3000/broken_path/ [status code] 404 [reason phrase] Not Found' in /myuser/path_to_project/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:89 Stack trace: #0 /myuser/path_to_project/vendor/guzzlehttp/guzzle/src/Subscriber/HttpError.php(33): GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Message\Request), Object(GuzzleHttp\Message\Response)) #1 /myuser/path_to_project/vendor/guzzlehttp/guzzle/src/Event/Emitter.php(109): GuzzleHttp\Subscriber\HttpError->onComplete(Object(GuzzleHttp\Event\CompleteEvent), 'complete') #2 /myuser/path_to_project/vendor/guzzlehttp/guzzle/src/RequestFsm.php(203): GuzzleHttp\Event\Emitter->emit('complete', Object(GuzzleHttp\Event\CompleteEvent)) #3 /myuser/path_to_project/vendor/guzzlehttp/guzzle/src/RequestFsm.php(92): GuzzleHttp\RequestFsm->complete(Object(GuzzleHttp\Transaction)) #4 /myuser/path_to_project/vendor/guzzlehttp/guzzle/s in /myuser/path_to_project/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php on line 89
```

My code that fires the request:

```
$client  = new Client();
$request = $client->createRequest( 'POST', 'http://localhost:3000/broken_path/' );
$request->getBody()->setField( 'some_field', 'some_value' );

try {
      $response = $client->send( $request );
    } catch (\GuzzleHttp\Exception\ClientException $e) {
      $response = $e->getResponse();
      if ($response && $response->getStatusCode() == 406) {
        // Do something with a 406 response here (as an example).
      }
      else {
        throw $e;
      }
    }
```

I got the code from this ticket: https://github.com/guzzle/guzzle/issues/664

Guzzle version: "5.1.0"

**Comment by sebastiaandegeus** [comment]
I also tried it with just `Exception` but that also doesn't work

**Comment by mtdowling** [comment]
What's the error message you're getting?

**Comment by mtdowling** [comment]
I'm guessing you are are getting a fatal error regarding the body of the request not having a setField method. If not, then you're using an older version of Guzzle and need to upgrade to guzzlehttp/guzzle.

**Comment by itsazzad** [comment]
I am getting the similar error using Laravel 5.1 and "guzzlehttp/guzzle": "^6.0" in:
[2015-07-30 10:29:25] production.ERROR: exception 'GuzzleHttp\Exception\ClientException' with message 'Client error: 404' in /vendor/guzzlehttp/guzzle/src/Middleware.php:69

**Comment by itsazzad** [comment]
Sorry i forgot to setup domain and secret in service settings.
Its solved

**Comment by Slader10** [comment]
i have the same problem where did you setup the domain ?

**Comment by scottyg** [comment]
@itsazzad @Slader10 I've got the same issue. Where do the domain and secret go?

**Comment by itsazzad** [comment]
@Slader10 @scottyg I was using Laravel. So what I did was just setting the correct domain/secret for the services I was using. Like I was using mailgun. So to access mailgun I am in need of the correct domain like xyz.mailgun.org and a password/secret. So if you are also having the similar scenario then this may help you, otherwise something else.

**Comment by ahsan154** [comment]
I am having the same issue.

here is my code:

$rets->Login();

//$fields = $rets->GetTableMetadata('Property', 'Listing');

//$results = $rets->Search('Property', 'Listing', '*', ['QueryType' => 'DMQL2','Limit' => 10]);

$results = $rets->Search('Property', 'Listing',  '*', [ 'QueryType' => 'DMQL2', 'Count' => 1, // count and records 
'Format' => 'COMPACT-DECODED', 'Limit' => 9999, 'StandardNames' => 0, // give system names
 ] );

foreach ($results as $r) {
    var_dump($r);
}

FYI, i am able to connect to server.  CREDS are valid

**Comment by sagikazarmark** [comment]
I don't see any Guzzle involvement here. Please raise your issue in the library this code belongs to. 404 is NOT a bug in Guzzle, it's a response given by a server.

**Comment by yousi1914** [comment]
lient error: `POST https://api.twilio.com/2010-04-01/Accounts//Messages.json` resulted in a `404 NOT FOUND` response:\n{\"code\": 20404, \"message\": \"The requested resource /2010-04-01/Accounts//Messages.json was not found\", \"more_info\": \"htt (truncated...)\n",

**Comment by sagikazarmark** [comment]
@yousi1914 I'm not sure what you mean.

**Comment by yousi1914** [comment]
@sagikazarmark  I am sending sms to my phone number but i got above error.
I am following this link. Can you help me out?

https://medium.com/@zilayhuda/sms-verification-using-twilio-api-on-laravel-5-6-23493cdfe12f

**Comment by sagikazarmark** [comment]
Do you use the twilio SDK or call that API endpoint directly?
I would suggest using the SDK: https://www.twilio.com/docs/libraries/php

**Comment by yousi1914** [comment]
@sagikazarmark  I am using twilio sdk in laravel project.

**Comment by sagikazarmark** [comment]
There seem to be a double slash in the URL:

`https://api.twilio.com/2010-04-01/Accounts//Messages.json`

Anyhow, this doesn't seem too be a Guzzle issue.

**Comment by yousi1914** [comment]
$accountSid =config('app.twilio')['TWILIO_ACCOUNT_SID']; 

Issue in this line. Not gelling value from config/app.php. Its not working.

**Comment by sagikazarmark** [comment]
Even more likely, that this has nothing to do with Guzzle.
