### ISSUE TITLE
Maximum execution time of 30 seconds exceeded in streams\src\Stream.php on line 122

### ISSUE THREAD

**Issue by nicholasnet** [guzzle/guzzle#971]
I am getting this error when I run this snippet. Even for 15 requests it is really slow takes around 24 secs. I see the output but it times out.
```PHP
<?php
// index.php localhost
echo (empty($_GET['n']) ? 'Test' : $_GET['n']);
```

```PHP
<?php
require '../vendor/autoload.php';
use GuzzleHttp\Pool;
use GuzzleHttp\Event\ErrorEvent;
use GuzzleHttp\Event\CompleteEvent;

function test()
{
    $client = new \GuzzleHttp\Client();
    
    $i = 1;
    $request = [];
        
    while ($i != 24) {
        $request[] = $client->createRequest('GET', 'http://localhost/?n='.$i);
        $i++;
    }
    
    return Pool::batch($client, $request);
}

$results = test();
foreach ($results as $result){
  echo $result->getBody() . '<br>';    
}
//die(); // If I uncomment this out it works... Obviously not the right way to resolve.
```

**Comment by mtdowling** [comment]
You need to increase the maximum allowed execution time:

1. http://php.net/manual/en/function.set-time-limit.php
2. http://php.net/manual/en/info.configuration.php#ini.max-execution-time

**Comment by nicholasnet** [comment]
I am aware that I can extend the execution time. But I think it is still bit slow than it should be normally. Also I did bit testing with sync and async mode via CLI.

ASYNC
```PHP
<?php
require '../vendor/autoload.php';
use GuzzleHttp\Pool;
use GuzzleHttp\Event\ErrorEvent;
use GuzzleHttp\Event\CompleteEvent;

$time_start = microtime(true);
$client = new \GuzzleHttp\Client();   
$request = $client->createRequest('GET', 'http://localhost/?n=1', ['future' => true]);
$client->send($request)->then(function ($response) use ($time_start) {
       $time_end = microtime(true);
       $time = $time_end - $time_start;
       echo "Process took $time seconds\n";
});
```

SYNC
```PHP
<?php
require '../vendor/autoload.php';
use GuzzleHttp\Pool;
use GuzzleHttp\Event\ErrorEvent;
use GuzzleHttp\Event\CompleteEvent;

$time_start = microtime(true);

$client = new GuzzleHttp\Client();
$response = $client->get('http://localhost/?n=1');
$time_end = microtime(true);
$time = $time_end - $time_start;
echo "Process took $time seconds\n";
```

I noticed that SYNC is always faster. Not sure why? Anyway I do not think it is not a bug. You can close this one.

**Comment by mtdowling** [comment]
If you're using the curl handlers (they're used by default), then the curl_multi powered handler used for async requests might need you to turn off the Nagle algorithm when connecting to extremely low latency hosts (e..g., localhost). See http://curl.haxx.se/libcurl/c/CURLOPT_TCP_NODELAY.html

Here's my exchange on the cURL mailing list regarding a similar slowness I observed: http://comments.gmane.org/gmane.comp.web.curl.library/39947
