### ISSUE TITLE
How to sent empty parameters

### ISSUE THREAD

**Issue by rkmax** [guzzle/guzzle#973]
I haveing trouble with a site i need pass empty arguments on the query. example:

`http://thehost.com?Subject=Hello+World&submit=`

i trying to make

```php

$client = new Client();
$response = $client->get("http://thehost.com", ['query' => ['Subject' => 'Hello World', 'submit => null']]);
```

but guzzle trim the submit parameter, how can solve this issue?

**Comment by mtdowling** [comment]
There are two different ways to do this:

1. Set a query value to an empty string (e.g., `''`) if you want the trailing "=". (i.e., `a=`)
2. Set a query value to null if do not want the trailing "=" (i.e., `a`).

```php
<?php
require 'vendor/autoload.php';
use GuzzleHttp\Client;
$client  = new Client();

$request = $client->createRequest('GET', 'http://httpbin.org/get', [
    'query' => [
        'foo' => 'bar',
        'baz' => '', // sends trailing =
        'qux' => null // no trailing =
    ]
]);

echo $request->getUrl();
```

Outputs: `http://httpbin.org/get?foo=bar&baz=&qux`

**Comment by rkmax** [comment]
thanks @mtdowling

**Comment by dopesong** [comment]
And what about POST request? It should be always with trailing =.

**Comment by simPod** [comment]
@mtdowling  When I set `'qux' => null`, the `qux` param is not added at all. Has something changed during time? :) Thanks!

**Comment by AaronJan** [comment]
I had the same issue as @simPod said. Can we add some docs for this behavior?

**Comment by elyanory** [comment]
Same issue... Any idea ? :)

**Comment by SwordaDev** [comment]
Having the same issue right now

```
'query' => [
                'input' => $search,
                'location' => $this->eventParameter['location'],
                'radius' => $this->eventParameter['radius'],
                'language' => $this->requestStack->getCurrentRequest()->getLocale(),
                'key' => $this->apiKey,
                'strictbounds' => NULL
            ]
```

The parameter `strictbounds` does not affect the result of the request.

**Comment by bangize** [comment]
Hi, is there any work around with this issue?

**Comment by maiermic** [comment]
It seems, you have to build the query string manually (in `guzzlehttp/guzzle` since at least version `6.5.5`), e.g.

```php
<?php

require_once dirname(__FILE__) . '/../bootstrap.php';

use GuzzleHttp\Client;

$query = join('&', [
  http_build_query(
    [
      'foo' => 'bar',
      'baz' => '', // sends trailing =
    ],
    null, '&', PHP_QUERY_RFC3986
  ),
  'qux', // no trailing =
]);
echo $query . PHP_EOL; // foo=bar&baz=&qux

$client = new Client();
$response = $client->get("https://httpbin.org/get", ['query' => $query]);
echo $response->getBody();
```

since AFAIK neither Guzzle nor [http_build_query](https://www.php.net/manual/en/function.http-build-query.php) support query parameters without value and no trailing `=`.

@mtdowling 

> Has something changed during time?
