### ISSUE TITLE
DELETE should still allow a body

### ISSUE THREAD

**Issue by jmargolin-rmn** [guzzle/guzzle#979]
According to the spec you can allow a body in a DELETE request however getBody return's null (http://stackoverflow.com/questions/14323716/restful-alternatives-to-delete-request-body).

```php
$request = $client->createRequest('DELETE', 'http://...');
var_dump($request->getBody()); // null
```

I presume this was intentional? Can we make it unintentional? :)

**Comment by mtdowling** [comment]
It does allow a body. Simply provide a "body" request option.

```php
$request = $client->createRequest('DELETE', 'http://...', ['body' => 'the body']);
```

**Comment by jmargolin-rmn** [comment]
That's odd why does getBody return an object for POST and not DELETE?

**Comment by mtdowling** [comment]
For POST it sets the body to a `GuzzleHttp\Post\PostBody` if no body is provided. This is just a convenience for the most common case to allow you to do stuff like call addFile(), setField(), etc.
