### ISSUE TITLE
Discrepancy with Emitter docs or code

### ISSUE THREAD

**Issue by webbj74** [guzzle/guzzle#981]
[Emitter::once()](https://github.com/guzzle/guzzle/blob/646ca530/src/Event/Emitter.php#L50) includes the Emitter object:
```
$listener($event, $eventName, $this);
```

[Emitter::emit()](https://github.com/guzzle/guzzle/blob/master/src/Event/Emitter.php#L109) does not:
```
$listener($event, $eventName);
```

The example "before" listener described in [events.rst](https://github.com/guzzle/guzzle/blob/646ca530/docs/events.rst) uses the three-argument form:
```
$request->getEmitter()->on(
    'before',
    function (BeforeEvent $e, $name, EmitterInterface $emitter) {
```

But when I used that signature with my EventSubscriber class, I received an exception:
```
[GuzzleHttp\Exception\RequestException]
  Catchable Fatal Error: Argument 3 passed to EventSubscriber::onBefore() must implement interface GuzzleHttp\Event\EmitterInterface, none given, called in .../vendor/guzzlehttp/guzzle/src/Event/Emitter.php on line 109 and defined
```

It looks like the emitter can be obtained from the event (via ```$event->getClient()->getEmitter()```) so I'm wondering if the three-argument signature is even needed.

**Comment by mtdowling** [comment]
Good catch. The three argument signature is not necessary and likely just an oversight after some refactoring.
