### ISSUE TITLE
How do I set a base URL for an existing instance?

### ISSUE THREAD

**Issue by pjcdawkins** [guzzle/guzzle#983]
This works:
```php
$client = new Client(['base_url' => $baseUrl]);
$response = $client->get($url);
```

This doesn't:
```php
$client = new Client();
$response = $client->get($url, ['base_url' => $baseUrl]);
```
`Fatal error: Uncaught exception 'InvalidArgumentException' with message 'No method can handle the base_url config key'`

There is no longer a `Client::setBaseUrl()` method. Why was this removed?

It makes it much harder to reuse client instances.

**Comment by oisvidi** [comment]
It's more immutable this way, which makes it easier to share the client with other objects without cloning it first.

**Comment by pjcdawkins** [comment]
I am not sure I understand that - more mutability means it's harder to share surely (AFAICT the only way another object can change the base URL of a client *is* by cloning it and reconstructing). I found a workaround anyway so feel free to close this. But a clearer explanation would be welcome.

**Comment by mtdowling** [comment]
The reason this isn't supported is that collaborators might be making the assumption that the base_url remains constant. If the base_url is allowed to change, then collaborators must either be notified of the change, or constantly re-calculate any needed derived data by polling the getBaseUrl() method each time a collaborator is invoked.

I'm also not sure I see the point of your use case here. You are giving both the url and the base_url in the same function call, meaning you can easily derive the full URI and not even need to resolve a base_url.

**Comment by pjcdawkins** [comment]
@mtdowling it makes dependency injection at least a bit tricky
```php
public function __construct(ClientInterface $client) {
    // now setDefaultOption() is available for some options
    // but I can't set a base URL
}
```

**Comment by nick4fake** [comment]
This makes managing Guzzle services in container painful. It is not possible to set base url with setter injection.

**Comment by VijitCoder** [comment]
_November 2019, Guzzle 6.5, the best what we have now_

Unbelievably. So popular library, and so wooden made! Configuration via _array_ in the constructor, Carl! 21st century, did you hear about DI at all, not? Maybe DTO also or at least setters? Nope?

**Comment by jonathanraftery** [comment]
Would offering a separate MutableClient class with the same functionality but a mutable config work? This way the default client gets the benefits of immutability, but devs have the option of creating a mutable client by explicitly declaring it as so.
