### ISSUE TITLE
Text is not shown on website in Firefox

### ISSUE THREAD

**Issue by slavafomin** [guzzle/guzzle#984]
Hello!

Text on Guzzle website is not rendered in Mozilla Firefox:
http://guzzle.readthedocs.org/en/latest/

![guzzle php http client and framework for consuming restful web services guzzle documentation 2015-02-25 14-14-25](https://cloud.githubusercontent.com/assets/1702725/6369560/a0eb777e-bcf8-11e4-9be2-b90350ec8d4a.png)

It looks like I have a local installation of Lato font, which is used on this website, but for some reason text is not rendered. I'm using latest Mozilla Firefox on Ubuntu.

### How to reproduce

1. Install Lato font in Ubuntu
2. Install Mozilla Firefox
3. Open [the website](http://guzzle.readthedocs.org/en/latest/)

**Comment by mtdowling** [comment]
We use a hosted theme from readthedocs.org.

I've opened an issue there for this: https://github.com/snide/sphinx_rtd_theme/issues/171
