### ISSUE TITLE
guzzlehttp/guzzle or guzzle/guzzle

### ISSUE THREAD

**Issue by Kryptonit3** [guzzle/guzzle#985]
I am using Laravel 4, you say to use ```"guzzlehttp/guzzle": "~4.0"``` but I did a recent `composer update` and got the following notices
```
Package guzzle/common is abandoned, you should avoid using it. Use guzzle/guzzle instead
Package guzzle/stream is abandoned, you should avoid using it. Use guzzle/guzzle instead
Package guzzle/parser is abandoned, you should avoid using it. Use guzzle/guzzle instead
Package guzzle/http is abandoned, you should avoid using it. Use guzzle/guzzle instead.
```

so which one is it?

**Comment by GrahamCampbell** [comment]
You need to use `"guzzlehttp/guzzle": "~5.0"`. That should work fine with L4.2, even though we've documented that 4.x is needed...

**Comment by dror3go** [comment]
@GrahamCampbell I'm on Laravel 4.2 and I'm getting these same notices when using `"guzzlehttp/guzzle": "~5.0"` & `"guzzlehttp/guzzle": "~5.2"`.
Any ideas why?

**Comment by GrahamCampbell** [comment]
Probably because you're installing a different package which is installing the old guzzle too.

**Comment by dees040** [comment]
Such as laravel/socialite:

``
"require": {
    ...
    "league/oauth1-client": "~1.0",
},
``

league/oauth1-client:

``
"require": {
    ...
    "guzzle/guzzle": "3.*"
},
``
