### ISSUE TITLE
handle progress

### ISSUE THREAD

**Issue by lalop** [guzzle/guzzle#986]
Hello,
I'm trying to handle the progress event without any succes.
I tried with the example found in the documentation :
http://docs.guzzlephp.org/en/latest/events.html#progress

What do you mean by `This event cannot be intercepted.` ?

**Comment by mtdowling** [comment]
What do you mean by "handle"? Is it not being invoked?

Not being able to intercept it means that you cannot return a response in lieu of what is currently being delivered (thereby cancelling the response from continuing to send).

**Comment by lalop** [comment]
yes it's not invoked.

**Comment by mtdowling** [comment]
Can you provide some example code?

**Comment by lalop** [comment]
I use the code given in the documentation
```
use GuzzleHttp\Client;
use GuzzleHttp\Event\ProgressEvent;

$client = new Client(['base_url' => 'http://httpbin.org']);
$request = $client->createRequest('PUT', '/put', [
    'body' => str_repeat('.', 100000)
]);

$request->getEmitter()->on('progress', function (ProgressEvent $e) {
    echo 'Downloaded ' . $e->downloaded . ' of ' . $e->downloadSize . ' '
        . 'Uploaded ' . $e->uploaded . ' of ' . $e->uploadSize . "\r";
});

$client->send($request);
echo "\n";
```
With guzzle 4.2.3

**Comment by mtdowling** [comment]
Ah. Guzzle 4 does not have a progress event. That was added in Guzzle 5.

**Comment by lalop** [comment]
mmmh, that works in a really much better way.
Thank you
