### ISSUE TITLE
How to call a url which automatically redirects to another page?

### ISSUE THREAD

**Issue by intdev03** [guzzle/guzzle#987]
Hi,
My scenario goes like this

1.There is already a url(http://localhost/loginAnothersite) which when fired (in browser) would redirect to anothersite.com
2.Now I have a different url (http://localhost/loginSite/AnotherSite) .This url when fired would expect to call 'http://localhost/loginAnothersite' internally (through guzzle-the only point when guzzle comes into picture),but the end output would be same as the browser would redirect to anothersite.com.

How do I achieve this wih guzzleHTTP ?

**Comment by mtdowling** [comment]
Guzzle will follow redirects like a browser automatically. Is this not working for you?

**Comment by intdev03** [comment]
I tried by setting header and it worked,didnt try with guzzle anymore

**Comment by mtdowling** [comment]
Ok. Does this issue need to be closed then?
