### ISSUE TITLE
Not installing via Composer without cURL?

### ISSUE THREAD

**Issue by khromov** [guzzle/guzzle#988]
I read in this article that Guzzle does not require cURL:  
http://guzzle.readthedocs.org/en/latest/faq.html#does-guzzle-require-curl

However, it still fails to install.

```
Problem 1
  - guzzle/guzzle v3.9.2 requires ext-curl * -> the requested PHP extension curl is missing from your system.
  - guzzle/guzzle v3.9.1 requires ext-curl * -> the requested PHP extension curl is missing from your system.
  - Installation request for guzzle/guzzle ~3.9.1 -> satisfiable by guzzle/guzzle[v3.9.1, v3.9.2].
```

**Comment by GrahamCampbell** [comment]
You are trying to install guzzle 3, but are reading the docs for guzzle 5...

**Comment by khromov** [comment]
My outmost apologies for not RTFM. 

![hats-off-to-you-sir-_7163990b4f3a977689286e8655533874](https://cloud.githubusercontent.com/assets/1207507/6432139/1fd2f34e-c048-11e4-958b-407288c20c16.jpg)

**Comment by jeremeamia** [comment]
Best apology ever. :+1::+1::+1:
