### ISSUE TITLE
Document base url trailing slash

### ISSUE THREAD

**Issue by mnapoli** [guzzle/guzzle#989]
Guzzle's doc mention it follows [RFC 3986](http://tools.ietf.org/html/rfc3986#section-5.2) but honestly that doesn't help a bit. I even tried to read that RFC but…

It could be made clearer in the docs whether a trailing slash is required, forbidden, or trimmed…

Related to #770 I guess.

**Comment by mtdowling** [comment]
Guzzle does exactly what a browser does when resolving a base URL. The RFC shows exactly how different URIs are resolved when combined with a base URI: http://tools.ietf.org/html/rfc3986#section-5.4.1

A trailing slash is not required in a base URI nor is it stripped.

Can you provide some test cases that specifically needs more documentation?

**Comment by mnapoli** [comment]
> Can you provide some test cases that specifically needs more documentation?

I don't see what you mean by test cases?

Take the [Clients documentation](http://guzzle.readthedocs.org/en/latest/clients.html), it says:

> **base_url**

> Configures a base URL for the client so that requests created using a relative URL are combined with the base_url of the client according to section [5.2 of RFC 3986](http://tools.ietf.org/html/rfc3986#section-5.2).

That's not clear because we have to go read the RFC, which is not helpful a bit when you just want to get started quickly and make sure you are writing the URL correctly. We can't expect Guzzle's users to go read HTTP RFCs.

Here is a more helpful version:

> **base_url**

> Configures a base URL for the client so that requests created using a relative URL are combined with the base_url of the client according to section [5.2 of RFC 3986](http://tools.ietf.org/html/rfc3986#section-5.2) (the base url shouldn't contain a trailing slash).

I chose the word "shouldn't" because the paragraph mentions creating requests using a relative URL, so since the trailing slash isn't stripped if it was added it would end up like http://foo.com//bar.html

If you are OK with this change I can open a PR.
