### ISSUE TITLE
issue with json

### ISSUE THREAD

**Issue by pgee70** [guzzle/guzzle#990]
Hi.
I was having an issue with json decode, it was generating an exception because  the JSON was not encoded as UTF-8.  I know it strictly isn't an issue with guzzle - there was something wrong with the streamed data. but this fixed it for me.

in the src/Message/response.php line 141 i wrapped the json string to parse in
utf8_encode( (string) $this->getBody() )

which did the trick.

**Comment by mtdowling** [comment]
I don't think this is something that's really actionable in Guzzle because it depends on the format of the data. Glad you got it working though.
