### ISSUE TITLE
Minimum described PHP version is wrong

### ISSUE THREAD

**Issue by jamiehollern** [guzzle/guzzle#995]
In the composer.json file, the minimum PHP version is described as `>=5.4.0`. However, on line 40 of `guzzlehttp/guzzle/tests/perf.php` a PHP 5.5 generator is used. 

`yield $client->createRequest('GET', '/guzzle-server/perf');`

Although this is in the tests directory and is not required for Guzzle to work properly, this causes my builds to fail on a box running PHP 5.4.

**Comment by mtdowling** [comment]
The minimum version is correct. Why is your build running this script?
