### ISSUE TITLE
You cannot create React\Promise\FulfilledPromise

### ISSUE THREAD

**Issue by Warxcell** [guzzle/guzzle#996]
InvalidArgumentException: You cannot create React\Promise\FulfilledPromise with a promise. Use React\Promise\resolve($promiseOrValue) instead. in /*/vendor/react/promise/src/FulfilledPromise.php on line 12

Any ideas?

**Comment by mtdowling** [comment]
Can you give a stack trace?

**Comment by Warxcell** [comment]
Of course:

#0 */vendor/guzzlehttp/guzzle/src/RequestFsm.php(173): GuzzleHttp\Exception\RequestException::wrapException(Object(GuzzleHttp\Message\Request), Object(InvalidArgumentException))
#1 */vendor/guzzlehttp/guzzle/src/RequestFsm.php(92): GuzzleHttp\RequestFsm->error(Object(GuzzleHttp\Transaction))
#2 */vendor/guzzlehttp/guzzle/src/Client.php(245): GuzzleHttp\RequestFsm->__invoke(Object(GuzzleHttp\Transaction))
#3 *: GuzzleHttp\Client->send(Object(GuzzleHttp\Message\Request))
#4 *
#5 *
#6*
#7 *
#8 {main}

**Comment by mtdowling** [comment]
Thanks.

Can you update to the latest version of Guzzle? Is there a reproducible snippet of code you can provide that I can play around with?

**Comment by Warxcell** [comment]
- Installing guzzlehttp/guzzle (dev-master 589f187)

Still same problem. The request is very simple:

$body = 'valid xml';
$request = $this->client->createRequest('POST', 'http://localhost:8989', array(
            'body' => $body
));

$request->setHeader('Content-Type', 'text/xml');
$response = $this->client->send($request);

**Comment by Warxcell** [comment]
I just found the problem:
It tries three times to send query and enter here: 
return self::retryFailedRewind($handler, $request, $response);
but second time this returns: GuzzleHttp\Ring\Future\CompletedFutureArray, not error.

This is my other question, how can I modify response before ANY validation? I'm integrating with XML API which is returning ALWAYS HTTP Status = 0 ? I need to modify Status to be always 200 so it won't broke Guzzle.

**Comment by mtdowling** [comment]
Weird. That could be a bug in Guzzle.

Are you sure that the service actually returns a status of `0`? Does setting the status code to something other than 0 cause this problem to go away?

**Comment by Warxcell** [comment]
Yes, everything is ok with raw curl. Status is 0.

https://github.com/guzzle/RingPHP/blob/master/src/Client/CurlFactory.php#L89 
`!isset($response['status']) == true` so `self::createErrorResponse($handler, $request, $response) ` is called. 

https://github.com/guzzle/RingPHP/blob/master/src/Client/CurlFactory.php#L108 - There is no real error, actually request is succesfull. 

https://github.com/guzzle/RingPHP/blob/master/src/Client/CurlFactory.php#L109 = yes, it's empty.

so, it call  `return self::retryFailedRewind($handler, $request, $response);` 

internally retryFailedRewing calls recursively https://github.com/guzzle/RingPHP/blob/master/src/Client/CurlHandler.php#L60 which return CompletedFutureArray and outside of that call is wrapped again with CompletedFutureArray

**Comment by alcohol** [comment]
``` php
$array["key"] = 0; 
var_dump(isset($array["key"]));

bool(true)
```

So the problem is not that the status is `0`. The problem is that `$header['status']` is either 
 - not set at all, 
 - is set to `null`.

Can you debug [this block](https://github.com/guzzle/RingPHP/blob/master/src/Client/CurlFactory.php#L79-L87)?

In particular, [this line](https://github.com/guzzle/RingPHP/blob/master/src/Client/CurlFactory.php#L83). If it sets the value to `null`, that would be why the `isset()` call returns false.


The following could explain a lot too though, but the statement is rather vague...

> Also there isn't any headers.

Can you elaborate? You mean the API you are calling does not return any headers at all?

**Comment by Warxcell** [comment]
Yes, the remote API we call does not return any headers. This is curl_info:

 'content_type' => null
  'http_code' => int 0
  'header_size' => int 0
  'request_size' => int 784

**Comment by alcohol** [comment]
Well... that is one seriously broken API.

**Comment by Warxcell** [comment]
It's API of payment broker. :)

Data is in XML. (Also the real status code)

**Comment by alcohol** [comment]
I don't really know how to deal with this. 

If a subscriber with a `onComplete` hook could capture the request before it does the header validation, then you could simply check if the content contains a valid XML body and return the response using `intercept()` (or alternatively, add headers that the request should have).

I would definitely contact your payment broker though and ask them why their API is so broken, and request that they fix it. I've worked with a lot of payment providers in the past, and I have never encountered something like this before.

**Comment by Warxcell** [comment]
I tried to make them fix it, but they don't want to do it.

I tried and the following:
`$this->client->getEmitter()->on('complete', array($this, 'fake'), 'first');`
with no success either.

**Comment by mtdowling** [comment]
Not returning a status code or headers is not a valid HTTP response. I don't think guzzle needs to be modified to support that type of response. Maybe better error reporting would have been better though, and I'd gladly accept a PR along those lines.
