### ISSUE TITLE
Post data fails

### ISSUE THREAD

**Issue by intdev03** [guzzle/guzzle#997]
When I try to execute post by the following code,then it $response->getBody() gives me a stream Object.How to get the json/response from this object?
if ($method == "POST") {
                $client = new GuzzleHttp\Client();
                $request = $client->createRequest('POST', $url);
                $request->addHeader('Accept', $contentTypeValue);
                if($access_type!=NULL && $access_token!=NULL){
                $this->setTokenAsHeader($request, $access_type, $access_token);
                }
                if($dataAsJson!=NULL){
                    $stream = GuzzleHttp\Stream\Stream::factory(htmlentities($dataAsJson));
                $request->setBody($stream);
                }
                $response = $client->send($request);
}
-----------------------------------------

Alternatively if I donot use stream and just do it with the following code 
 if ($method == "POST") {
                $client = new GuzzleHttp\Client();
                $request = $client->createRequest('POST', $url);
                $request->addHeader('Accept', $contentTypeValue);
                if($access_type!=NULL && $access_token!=NULL){
                $this->setTokenAsHeader($request, $access_type, $access_token);
                }
                if($dataAsJson!=NULL){
                $request->setBody($dataAsJson);
                }
                $response = $client->send($request);
is giving me 
Argument 1 passed to GuzzleHttp\Message\AbstractMessage::setBody() must implement interface GuzzleHttp\Stream\StreamInterface, string given

Please help

**Comment by mtdowling** [comment]
> When I try to execute post by the following code,then it $response->getBody() gives me a stream Object.How to get the json/response from this object?

This will give you the JSON data: `$response->json();`

Your second example does not work because you are providing an array and the function expects a stream. You should instead provide an array to the "json" option when creating a request:

```php
$request = $client->createRequest('POST', $url, ['json' => ['foo' => 'bar']]);
```
