### ISSUE TITLE
ClientException in RequestException

### ISSUE THREAD

**Issue by CupOfTea696** [guzzle/guzzle#998]
I keep getting a ClientException within the RequestException.php, and I can't seem to catch it at all.

    try{
        $response = $httpClient->get($url, [
            'query' => $parameters,
            'headers' => $headers,
        ]);
    } catch (Exception $e) {
        dd($e);
    }

Here's a bit of the stack trace attached:
![screen shot 2015-03-09 at 20 24 59](https://cloud.githubusercontent.com/assets/7327050/6563616/72a61f26-c69a-11e4-835b-54eb4cae587b.png)

**Comment by Warxcell** [comment]
You should have \ in front of exception, like this: 
`} catch (\Exception $e) {`
