### ISSUE TITLE
The path in `base_url` is not used to build the final URL

### ISSUE THREAD

**Issue by chocopoche** [guzzle/guzzle#999]
$client = new Client([
        'base_url' => 'http://server.net/services',
    ]);
    $client->post(
        '/files', [
        // ...
        ]
    );
=> request is not issued to `http://service.net/services/files` but to `http://service.net/services/files`

I can reproduce that behavior against the 5.2.0 and the dev-master.

**Comment by Warxcell** [comment]
Something is wrong here.... 

http://service.net/services/files but to http://service.net/services/files

links looks equal to me.

**Comment by rhys-mcguckin** [comment]
I think that was a typo. The result I get from that is http://service.net/files. The issue for me stems from line 564 in src/Url.php... it looks like the combine function is not using the object base path + the incoming url path. I don't know if this is a solution but I changed that line to:
```
    $this->path . $path,
```
While this worked in my limited example, it hasn't been tested overall.

**Comment by chocopoche** [comment]
Ok, i think you both got the point, sorry for the typo!

**Comment by mtdowling** [comment]
Guzzle follows [RFC 3986](https://tools.ietf.org/html/rfc3986#section-5.2) when resolving a base URI and a relative URI. It does exactly what a browser would do.

If you add a trailing slash to your base URL and remove the trailing slash from your relative URL, then it will do what you want.

```php
<?php
require 'vendor/autoload.php';

use GuzzleHttp\Url;

$base = Url::fromString('http://server.net/services/');
echo "Leading slash: " . $base->combine('/files') . "\n";
echo "No slash: " . $base->combine('files') . "\n";
```

Outputs:

```
Leading slash: http://server.net/files
No slash: http://server.net/services/files
```

**Comment by chocopoche** [comment]
My wrong, I though it was just a prepend string. It actually make sense to me as the config parameter is named `base_url`, and it should have gave me the right clue. It does what it says it does.

Don't know if it worth a bit more documentation for people like me that don't get it immediatly when referring the RFC.

And ... thank you for the project and support!
